### ISSUE TITLE
select ... from information_schema.columns leads to a problem

### ISSUE THREAD

**Issue by zz0116** [apache/incubator-shardingsphere#1176]
### Which version of Sharding-Sphere do you using?
3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
tomcat normal  start
### Actual behavior
A problem caused tomcat failed to start properly, it showed that jdbc couldn't find dataSource.columns, but table "columns" was actually in information_schema, and we wrote it correct "information_schema.columns", without sharding-jdbc and the shard tables the tomcat can start normally.
### Reason analyze
Can sharding-jdbc do not intercept the sql which select from information_schema? We just want all table names and fields, the information_schema surely hasn't sharding table.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc
sql: select table_name, group_concat(column_name) column_name from information_schema.columns where table_name in (${table_name}) and table_schema in (${database_name}) group by table_name
this sql is in a .mapper
sharding rule is sharding:inline-strategy, whatever, the rule doesn't matter
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'base.columns' doesn't exist
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'base.columns' doesn't exist

**Comment by terrymanu** [comment]
Right now, Sharing-Sphere cannot support DQL with schema name. We just consider about skip to parse system schema.
We need to carding all system schema of MySQL, Oracle, PostgreSQL and SQLServer.

**Comment by zz0116** [comment]
"skip to parse system schema" is exactly what I expected, if the sharding-jdbc skipped the sql "select ... from information_schema.columns", tomcat wouldn't report "Table 'base.columns' doesn't exist", the database "base" was the dataSource what we used, so what sharding-jdbc had done was parsing the "information_schema.colums" into "base.columns", and I didn't want it to do this conversion.

**Comment by terrymanu** [comment]
I just close this one, let's talk about #3572
