### ISSUE TITLE
Redesign ShardingMetaData module.

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1385]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

Though we have ShardingMetaData now, but it can not meet all the needs for some important scenarios, we need to redesign ShardingMetaData module. The tasks are as follows:

- [x] Implement the interface `getMetaData` of JDBC.
- [x] Read column type when needed.
- [x] Consider about the interface of ShardingResultSetMeta to shade the real column label.

#1321 can be solved in this issue, Please focus on this issue.

**Comment by KomachiSion** [comment]
refer to #1774 .
