### ISSUE TITLE
Read write splitter for `Select ... for update` should route to master data node

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#1496]
### Which version of Sharding-Sphere did you use?

3.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

All

### Expected behavior

Read write splitter for `Select ... for update` should route to master data node

### Actual behavior

Read write splitter for `Select ... for update` route to slave data node now

associated with #767

Tasks here:

- [ ] Parse `Select ... for update`
- [ ] Modify master-slave route engine

**Comment by young891221** [comment]
Hi, @terrymanu 
Could you tell me when to support `select for update`?
I checked `sql-statement-rule-definition.xml` in the '4.0.0-RC1-Release' branch. But, `select for update` does not exist.

**Comment by qixiaobo** [comment]
also  lock in share mode

**Comment by qixiaobo** [comment]
> Hi, @terrymanu
> Our team discusses the introduction of ShardingSphere and needs 'select for update' function.
> So, could you tell me when to support `select for update`?
> I checked `sql-statement-rule-definition.xml` in the '4.0.0-RC1-Release' branch. But, `select for update` does not exist.

For me ，we just use hintmanager

**Comment by terrymanu** [comment]
We need refactor parse for sharding first, and then will plan to do this.
If your team need this feature, we can discuss how to do it, and maybe your team can do it.

**Comment by TonyLuo** [comment]
@terrymanu why close this issue? 4.0.0.RC2 still has select for update issue....

**Comment by TonyLuo** [comment]
or could you pls advise which java files should be focused on to help to fix this issue?

**Comment by qixiaobo** [comment]
```java
public final class MasterSlaveRouter {
    
    private final MasterSlaveRule masterSlaveRule;
    
    private final SQLParseEngine parseEngine;
    
    private final boolean showSQL;
    
    /**
     * Route Master slave.
     *
     * @param sql SQL
     * @param useCache use cache or not
     * @return data source names
     */
    // TODO for multiple masters may return more than one data source
    public Collection<String> route(final String sql, final boolean useCache) {
        Collection<String> result = route(parseEngine.parse(sql, useCache));
        if (showSQL) {
            SQLLogger.logSQL(sql, result);
        }
        return result;
    }
    
    private Collection<String> route(final SQLStatement sqlStatement) {
        if (isMasterRoute(sqlStatement)) {
            MasterVisitedManager.setMasterVisited();
            return Collections.singletonList(masterSlaveRule.getMasterDataSourceName());
        }
        return Collections.singletonList(masterSlaveRule.getLoadBalanceAlgorithm().getDataSource(
                masterSlaveRule.getName(), masterSlaveRule.getMasterDataSourceName(), new ArrayList<>(masterSlaveRule.getSlaveDataSourceNames())));
    }
    
    private boolean isMasterRoute(final SQLStatement sqlStatement) {
        return !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited() || HintManager.isMasterRouteOnly();
    }
```
You should use hintManager

**Comment by TonyLuo** [comment]
@qixiaobo do you mean we need to overrid this method and only use HintManager.isMasterRouteOnly() to check isMasterRoute?
```
  private boolean isMasterRoute(final SQLStatement sqlStatement) {
        return !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited() || HintManager.isMasterRouteOnly();
    }
```

**Comment by qixiaobo** [comment]
> @qixiaobo do you mean we need to overrid this method and only use HintManager.isMasterRouteOnly() to check isMasterRoute?
> 
> ```
>   private boolean isMasterRoute(final SQLStatement sqlStatement) {
>         return !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited() || HintManager.isMasterRouteOnly();
>     }
> ```

Never! Use hint in your sql
