### ISSUE TITLE
Use now() as sharding key

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#1497]
ShardingSphere will get database time, and then calculate and sharding. The tasks:

- [x]  Parse `now()` for MySQL
- [x]  Define a datatime database server in configuration
- [x]  Get current time from datatime database server
- [x]  Route by current time

**Comment by avalon566** [comment]
i am interested in resolving this issue.but it doesn't seem that the dev branch can support the datetime range sharding strategy,i need to finish this task first?

**Comment by xiaoyuge** [comment]
Is this problem fixed?
