### ISSUE TITLE
Parametermized tests for Rewrite module.

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1548]
We will add parameter tests for rewrite module to ensure the rewriting correct and improve the test coverge.
> The basic processing is as follow:
1. ParseResult.xml --->ParseResultEntity-->SQLStatemtent-->Optimize()-->OptimizedResult.xml-->ShardingConditions

2. ShardingConditions+OptimizedResult.xml-->
ShardingConditions+SQLStatemtent-->SQLRewriteEngine-->Rewrite()-->SQLBuilder-->Actual SQLs

3. RewriteResult.xml-->Excpected SQLs

4. Assert(Actual SQLs, Excpected SQLs)-->AssertMessage-->Output.

**Comment by terrymanu** [comment]
After rewrite module refactor already finished, we can redefine tasks for rewrite test module.

- [ ] Use yaml to setup encrypt rewrite engine
- [ ] Unify sharding and encrypt's configuration of table names and column names
- [ ] Use parse engine to setup SQLStatementContext
- [ ] Use Parametermized test and XML to setup rewrite test engine

**Comment by terrymanu** [comment]
Parametermized test's xml definition: 

<rewrite-assertions>
    <rewrite-assertion original-sql="xxx" original-parameters="xx, xx" rewrited-sql="xxx" rewrited-parameters="xx, xx" />
</rewrite-assertions>

**Comment by terrymanu** [comment]
finally, the xml definition is:

```xml
<rewrite-assertions yaml-rule="xxx.yaml">
    <rewrite-assertion id="xxx" db-type="xxx">
        <input sql="xxx" parameters="x, x" />
        <output sql="xxx" parameters="x, x" />
    </rewrite-assertion>
</rewrite-assertions>
```
