### ISSUE TITLE
get wrong result of some interfaces of GeneratedKeysResultSetMetaData

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1661]
get wrong result of some interfaces of GeneratedKeysResultSetMetaData:

    @Override
    public String getSchemaName(final int column) {
        Preconditions.checkArgument(column == 1);
        return "";
    }

    @Override
    public String getTableName(final int column) {
        Preconditions.checkArgument(column == 1);
        return "";
    }
    
    @Override
    public String getCatalogName(final int column) {
        Preconditions.checkArgument(column == 1);
        return "";
    }

**Comment by KomachiSion** [comment]
I test native JDBC, `getSchemaName` and `getCatalogName` return '' also.
`getTableName` return null.

So should we only change the return value of `getTableName` to null?
