### ISSUE TITLE
Support inline expression configuration for Sharding-springboot

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1686]
#### Task content 
User can use `ds,ds_${0..1}` to configure sharding.jdbc.datasource.names, i.e.
> sharding.jdbc.datasource.names=ds,ds_${0..1}

#### Current situation
User can not use inline expression to configure this item simply, i.e.
> sharding.jdbc.datasource.names=ds,ds_0,ds_1

#### Others
 There is a pr to solve this problem,  so you can incorporate your thinking in this issue and make a new pr for Sharding-spring project.

#### Reference
* Existed PR: https://github.com/sharding-sphere/sharding-sphere/pull/1320
* Sharding-spring project: https://github.com/sharding-sphere/sharding-spring

**Comment by tristaZero** [comment]
> i want to do it

Hi, welcome. You can do it at your pace, but can you give us an approximate time?

**Comment by terrymanu** [comment]
@chinacode Thank you and welcome, I just assign this issue to you

**Comment by tristaZero** [comment]
Thanks @xuminwlt to raise [PR#13](https://github.com/sharding-sphere/sharding-spring/pull/13) to finish this task, and it was merged already.
