### ISSUE TITLE
Support springboot placeholder configruation for Sharding-springboot

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1687]
#### Task content 
User can use springboot placeholder`${} ` to configure sharding.jdbc.datasource.names, i.e.
> sharding.jdbc.datasource.names=db_${random.int}

#### Current situation
User can not use springboot placeholder to configure sharding configurations.

#### Others
There is another issue [#1686](https://github.com/sharding-sphere/sharding-sphere/issues/1686) related to this one, welcome to be responsible for two issues together for Sharding-spring project.

#### Reference
* Related issue: https://github.com/sharding-sphere/sharding-sphere/issues/1686
* Sharding-spring project: https://github.com/sharding-sphere/sharding-spring

**Comment by xiangtao** [comment]
good

**Comment by binlaniua** [comment]
+1， for example
```
sharding.jdbc.datasource.xx.url=${ENV_DS_URL}
```
or
```
ds.url=xxx
sharding.jdbc.datasource.xx.url=${ds.url}
```

**Comment by xuminwlt** [comment]
An want to make it.

**Comment by tristaZero** [comment]
@xuminwlt Hi, do you want to accept this task? And you can do it by your own pace, but can you tell us an approximate finish time?

**Comment by terrymanu** [comment]
@xuminwlt Thank you and welcome.

**Comment by xuminwlt** [comment]
I test the code from project sharding-spring/sharding-jdbc-spring-boot-starter, It's already support by spring environment.

config
```
sharding.jdbc.datasource.names=ds_master,ds_slave_${random.int(2)}

```

code result
```
        String prefix = "sharding.jdbc.datasource.";
        String dataSources = environment.getProperty(prefix + "names");
```
then dataSources print
- ds_master,ds_slave_0
or
- ds_master,ds_slave_1

Config in spring boot will prepare some default propertySources like this
![image](https://user-images.githubusercontent.com/5835937/51372067-ed9a3100-1b36-11e9-8105-3221739ec06c.png)


Maybe I don't get the issue's mean.

**Comment by xuminwlt** [comment]
I have commit a PR to sharding-spring.

**Comment by tristaZero** [comment]
@xuminwlt  Thanks for your [PR#13](https://github.com/sharding-sphere/sharding-spring/pull/13), and it was merged already.
