### ISSUE TITLE
Refactor design of sharding transaction 2PC XA 

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#1694]
I'll refactor sharding-transaction-2pc-xa, here is the detail design, please feel free to give me some advices.
![image](https://user-images.githubusercontent.com/8317649/50502306-3b240080-0a99-11e9-9518-b98e4da3bd43.png)

### changes

- faced to XA DataSource to handle XA Connection instead of AtomikosDataSourceBean
- adapt Connection to XAConnection if needed
- Get XAResource, then inject it into XA transactionManager if needed
- Add ShardingTransactionAPI to handle all transaction operation, this can be used in other transaction type

**Comment by cherrylzhao** [comment]
> @cherrylzhao How does the Sharding XA Resource enlist the XAResource to participate in the transaction ? I think it could be delegate to the different TM implementation or we can consider to use the common dbcp2. And how can we register it to the recovery manager ?

you're right, we have delegated to the different TM to enlist the resource.
and we can leverage the pool feature of common datasource, instead of fixed dbcp2 and atomikosDataSourceBean. if datasource pool don't have XA feature, we can first get the connection, then wrap it to XAConnection. of course, in the XATransactionManager spi, we should provide register recovery method to complete recovery resource registration at bootstrap step.

**Comment by cherrylzhao** [comment]
we have tried to redefine the XATransaction SPI like this [XATransactionManager](https://github.com/cherrylzhao/sharding-sphere/blob/e4b6bfce09afd2177024d74788b4f0f14ed102ef/sharding-transaction/sharding-transaction-2pc/sharding-transaction-xa/sharding-transaction-xa-spi/src/main/java/io/shardingsphere/transaction/xa/spi/XATransactionManager.java#L37),
please feel free to give us some idea.

**Comment by cherrylzhao** [comment]
hi, zhfeng 

I have made a Bitronix integration with sharing-sphere.
you can see more detail from my repository
https://github.com/cherrylzhao/sharding-sphere-bitronix.git

**Comment by cherrylzhao** [comment]
hi, zhfeng

>Why does it introduce the SingleXAResource ?
>Why does it need the enlistResource method ? Although I think in the different vendor, the >implementation could be similar here just like
>TransationMangager.getCurrentTransaction().enlist(xaResource);

`SingleXAResource` has the resourceName associated with registered recovery resource.
usually JTA manager vendor have provided their owed XA transactional datasource pool to encapsulate process of `XAResource enlist`, we can enlist XAResource manually within sharding-sphere TransactionEngine layer. you can see more detail in `XAShardingTransactionEngine.getConnection`

**Comment by terrymanu** [comment]
Hi all,
    In current implementation for sharding-transaction-core, `ShardingTransactionManager` and `ShardingTransactionEngine` both define `begin`, `commit` & `rollback` method which are duplicated.
    We just remove `ShardingTransactionManager`, and let XA or Saga‘s provider to adapt it by themselves. For `XATransactionManager` , it doesn't need implements `ShardingTransactionManager`. Just care about `XAShardingTransactionEngine` is enough. We just add a new method to return `TransactionManager` from JTA is fine here.

**Comment by zhfeng** [comment]
OK, I will add the narayana one.

**Comment by zhfeng** [comment]
@cherrylzhao it looks like missing the io.shardingsphere:sharding-transaction-saga:jar:4.0.0.M1-SNAPSHOT. Do we have the snapshot building of the current sharding-sphere ?

**Comment by cherrylzhao** [comment]
@zhfeng I have created another issue #1777 to track the narayana integration, thanks a lot!

**Comment by zhfeng** [comment]
OK, it looks good to me.

**Comment by zhfeng** [comment]
@cherrylzhao is there any way we can pass the configuration parameters of the transaction manager ?

**Comment by cherrylzhao** [comment]
@zhfeng Atomikos and Bitronix pass the configuration through `jta.properties` files.
we can place this file in classpath to override the default parameters.
