### ISSUE TITLE
hope to support with count sub query sql

### ISSUE THREAD

**Issue by lazeyliu** [apache/incubator-shardingsphere#1753]
## Bug Report

**For English only**, other languages will not accept.
SQL: 
```
SELECT COUNT(1) FROM ( 
     SELECT
        r.`channel` as `channel_code`,
        r.`channel_name` as `channel_name`,
        COUNT(r.id) `total_cnt`,
        COUNT(r.connect_flag = "Y") `connected_cnt`
        FROM record_callin r
        LEFT JOIN sys_org_tree_rel tree ON tree.teamid = r.teamid
        LEFT JOIN sys_user u ON u.brokerid = r.brokerid
        where
        r.create_time between '2018-01-01 00:00:00' and   '2019-01-01 00:00:00'
        GROUP BY 
        r.`channel` 
) TOTAL
```
hope to support it

**Comment by codefairy08** [comment]
already fixed

**Comment by terrymanu** [comment]
@codefairy08 We should support this kind of SQL, it is a regression. ShardingSphere support it before.

**Comment by terrymanu** [comment]
FIY: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/

search `Available for not only sub-query of pagination`

**Comment by terrymanu** [comment]
fixed at #1873

**Comment by terrymanu** [comment]
Not finished yet, it need to support route to multiple tables

**Comment by JeddyHj** [comment]
When can this problem be fixed, our technical research sharding-jdbc is blocked by this problem

**Comment by terrymanu** [comment]
I am sorry, but we can not promise it.
If you have requirement, do you mind try to submit a pull request?
