### ISSUE TITLE
When starting spring boot application with Sharding Sphere throws java.sql.SQLDataException: ORA-01424: 转义符之后字符缺失或非法

### ISSUE THREAD

**Issue by sixianli** [apache/incubator-shardingsphere#1755]
## Bug Report

[please click this link for bug report content](https://www.zybuluo.com/survivorZzz/note/1390476)

Looking forward to your reply! Thank you !

**Comment by meAsky** [comment]
I want to do it.

**Comment by sixianli** [comment]
To solve this issue i customize sharding-core module for my project and it works. I change a code snippet in this funciton `io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer#getAllTableNames` like this:
```java
private Collection<String> getAllTableNames(final String dataSourceName) throws SQLException {
        Collection<String> result = new LinkedHashSet<>();
        try (Connection connection = connectionManager.getConnection(dataSourceName);
             ResultSet resultSet = connection.getMetaData().getTables(dataSourceName, null, null, new String[]{"TABLE"})) {
            while (resultSet.next()) {
                String tableName = resultSet.getString("TABLE_NAME");
                if (!tableName.contains("$") && !tableName.contains("/")) {
                    result.add(tableName);
                }
            }
        }
        return result;
    }
```

**Comment by tuohai666** [comment]
@sixianli So why not pr ?

**Comment by tuohai666** [comment]
@meAsky you can submit a pull request, I'll review it.

**Comment by sixianli** [comment]
> @sixianli So why not pr ?

ok, i will do it later

**Comment by tuohai666** [comment]
One more system table which contains "/". 
"$" has been found before, please refer to https://github.com/apache/incubator-shardingsphere/issues/1227

**Comment by tuohai666** [comment]
Good finding, @sixianli
