### ISSUE TITLE
INSERT ON DUPLICATE KEY UPDATE with dynamic parameters

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#1756]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support dynamic parameter on INSERT ON DUPLICATE KEY UPDATE.
for example (mybatis mapper):
```
INSERT INTO BlackMember (memberId, activeId, passiveId, project, platform, source)
      VALUE (#{memberId}, #{activeId}, #{passiveId},#{project}, #{platform}, #{source})
      ON DUPLICATE KEY UPDATE shieldStatus = #{shieldStatus}
```
### Actual behavior
```
Cause: java.sql.SQLException: No value specified for parameter 7
```
### PS
Although I can find some explanation about why this feature should not be supported #1066 , it's not convictive enough I think. As the official doc says sharding-jdbc is 100% compatible for single-node routing SQL, it will not be true if this issue exists, and I find it's really hard to migrate my projects from Mycat to the Sharding-Sphere since it is common usage in my projects. 
So, could you please reconsider the possibility to support this feature.
![image](https://user-images.githubusercontent.com/1615053/51166056-322a9000-18dd-11e9-91dc-30ba06085892.png)

**Comment by joooohnli** [comment]
I'v read all related issues and your explanation and I think it's a little arbitrary to mark them **won't fix** as I mentioned in the PS.

**Comment by maxiaoguang64** [comment]
sorry, we think about it carefully and get back to you later.

**Comment by maxiaoguang64** [comment]
@joooohnli we decided fix it in antlr parser engine, possible in 4.0.0

**Comment by kagowu** [comment]
我也遇到相同的问题，也是3.1.0版本。使用原生的SQL可以，和mybatis集成就有问题

**Comment by Stuben** [comment]
@maxiaoguang64 

Has this problem been fixed in 4.0.0-RC1?

**Comment by terrymanu** [comment]
fixed at 4.0.0-RC2

**Comment by terrymanu** [comment]
fixed at 4.0.0-RC2

**Comment by zhegexiaohuozi** [comment]
@terrymanu 4.0.0-RC2 这个问题依然存在

**Comment by Jaskey** [comment]
I have the same problem in version of  4.0.1, would you please help me ? I use mybatis to generate a sql, but when I use on duplicate key update, the same problem that No value specified for parameter X is occured

**Comment by Jaskey** [comment]
<insert id="insertOnDuplicateKeyUpdateSelective" parameterType="com.xxxxxx.yyyyyy.duhbepay.dao.entity.HeytapPayOrderInfoExt">
    insert into heytap_pay_order_info_ext
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="id != null">
        id,
      </if>
      <if test="tradeNo != null">
        trade_no,
      </if>
      <if test="tradeProvince != null">
        trade_province,
      </if>
      <if test="tradeCity != null">
        trade_city,
      </if>
      <if test="tradeDistrict != null">
        trade_district,
      </if>
      <if test="recipientProvince != null">
        recipient_province,
      </if>
      <if test="recipientCity != null">
        recipient_city,
      </if>
      <if test="recipientDistrict != null">
        recipient_district,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="id != null">
        #{id,jdbcType=INTEGER},
      </if>
      <if test="tradeNo != null">
        #{tradeNo,jdbcType=VARCHAR},
      </if>
      <if test="tradeProvince != null">
        #{tradeProvince,jdbcType=VARCHAR},
      </if>
      <if test="tradeCity != null">
        #{tradeCity,jdbcType=VARCHAR},
      </if>
      <if test="tradeDistrict != null">
        #{tradeDistrict,jdbcType=VARCHAR},
      </if>
      <if test="recipientProvince != null">
        #{recipientProvince,jdbcType=VARCHAR},
      </if>
      <if test="recipientCity != null">
        #{recipientCity,jdbcType=VARCHAR},
      </if>
      <if test="recipientDistrict != null">
        #{recipientDistrict,jdbcType=VARCHAR},
      </if>
    </trim>
    ON DUPLICATE KEY UPDATE
    <trim suffixOverrides=",">
      <if test="tradeNo != null">
        trade_no = #{tradeNo,jdbcType=VARCHAR},
      </if>
      <if test="tradeProvince != null">
        trade_province = #{tradeProvince,jdbcType=VARCHAR},
      </if>
      <if test="tradeCity != null">
        trade_city = #{tradeCity,jdbcType=VARCHAR},
      </if>
      <if test="tradeDistrict != null">
        trade_district = #{tradeDistrict,jdbcType=VARCHAR},
      </if>
      <if test="recipientProvince != null">
        recipient_province = #{recipientProvince,jdbcType=VARCHAR},
      </if>
      <if test="recipientCity != null">
        recipient_city = #{recipientCity,jdbcType=VARCHAR},
      </if>
      <if test="recipientDistrict != null">
        recipient_district = #{recipientDistrict,jdbcType=VARCHAR},
      </if>
    </trim>
  </insert>


But the actual sql seems the `<if test="recipientCity != null">` does not work now
