### ISSUE TITLE
The correct result cannot be found when the binding table is associated with the query

### ISSUE THREAD

**Issue by chenshao6311** [apache/incubator-shardingsphere#1763]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
String sql = "SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id and o.order_id = 292325090350071808";

### Actual behavior
can find result,but no result return 

### Reason analyze (If you can)

When the queries are associated with two bound tables, I don't understand why the corresponding dataNode can be found through the main table, then the index can be found through the dataNode, and finally the dataNode of another table can be determined by the index.            
As long as the order of dataNodes I configure is different, the results of the association query are incorrect.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

private static TableRuleConfiguration getOrderItemTableRuleConfiguration() {
TableRuleConfiguration result = new TableRuleConfiguration();
result.setLogicTable("t_order_item");
result.setActualDataNodes("demo_ds_0.t_order_item_1,demo_ds_0.t_order_item_0,demo_ds_1.t_order_item_1,demo_ds_1.t_order_item_0");
//result.setActualDataNodes("demo_ds_${0..1}.t_order_item_${[0, 1]}");
return result;
}
private static TableRuleConfiguration getOrderTableRuleConfiguration() {
TableRuleConfiguration result = new TableRuleConfiguration();
result.setLogicTable("t_order");
result.setActualDataNodes("demo_ds_${0..1}.t_order_${[0, 1]}");
result.setKeyGeneratorColumnName("order_id");
return result;
}
shardingRuleConfig.getBindingTableGroups().add("t_order, t_order_item");
shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "demo_ds_${user_id % 2}"));
shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("order_id", new PreciseModuloShardingTableAlgorithm()));

### Example codes for reproduce this issue (such as a github link).

###PS
When the queries are associated with two bound tables, I don't understand why the corresponding dataNode can be found through the main table, then the index can be found through the dataNode, and finally the dataNode of another table can be determined by the index.            As long as the order of dataNodes I configure is different, the results of the association query are incorrect. For example:            My configuration: 

private static TableRuleConfiguration getOrderItemTableRuleConfiguration() {
TableRuleConfiguration result = new TableRuleConfiguration();
result.setLogicTable("t_order_item");
result.setActualDataNodes("demo_ds_0.t_order_item_1,demo_ds_0.t_order_item_0,demo_ds_1.t_order_item_1,demo_ds_1.t_order_item_0");
//result.setActualDataNodes("demo_ds_${0..1}.t_order_item_${[0, 1]}");
return result;
}
private static TableRuleConfiguration getOrderTableRuleConfiguration() {
TableRuleConfiguration result = new TableRuleConfiguration();
result.setLogicTable("t_order");
result.setActualDataNodes("demo_ds_${0..1}.t_order_${[0, 1]}");
result.setKeyGeneratorColumnName("order_id");
return result;
}
shardingRuleConfig.getBindingTableGroups().add("t_order, t_order_item");
shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("user_id", "demo_ds_${user_id % 2}"));
shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("order_id", new PreciseModuloShardingTableAlgorithm()));

If the data is inserted first and then the order_id is used as the query condition for the association query, the correct result will not be obtained.            

By Finding Statements :
String sql = "SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id and o.order_id = 292325090350071808";

The routing result is ：
 "SELECT i.* FROM t_order_0 o, t_order_item_0 i WHERE o.order_id = i.order_id and o.order_id = 292325090350071808";

**Comment by KomachiSion** [comment]
Hi @chenshao6311, I can not recurrent your problem with your description.
I need more information.

1.  Is that ShardingSphere example? if not, please provides your full ShardingSphere configuration or try to run ShardingSphere example first.
2. Can you open `sql.show` and provide the SQLstatement and actual SQL like following:
```
[INFO ] 2019-01-18 09:32:21,022 --main-- [ShardingSphere-SQL] Logic SQL: SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id and o.order_id=?; 
[INFO ] 2019-01-18 09:32:21,022 --main-- [ShardingSphere-SQL] SQLStatement: SelectStatement(super=DQLStatement(super=io.shardingsphere.core.parsing.parser.sql.dql.select.SelectStatement@181e72d3), containStar=true, firstSelectItemStartPosition=7, selectListLastPosition=11, groupByLastPosition=0, items=[StarSelectItem(owner=Optional.of(i))], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null, subQueryStatements=[], subQueryConditions=[]) 
[INFO ] 2019-01-18 09:32:21,022 --main-- [ShardingSphere-SQL] Actual SQL: ds_1 ::: SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id and o.order_id=?; ::: [[292953431725834241]] 
[INFO ] 2019-01-18 09:32:21,022 --main-- [ShardingSphere-SQL] Actual SQL: ds_0 ::: SELECT i.* FROM t_order_1 o, t_order_item_1 i WHERE o.order_id = i.order_id and o.order_id=?; ::: [[292953431725834241]]
```

**Comment by chenshao6311** [comment]
In the binding table, the main change is the order of dataNodes of this table rule. The dataNodes of the two binding tables are as follows:
t_order:
result.setActualDataNodes("demo_ds_${0..1}.t_order_${[0, 1]}");

t_order_item:
result.setActualDataNodes("demo_ds_0.t_order_item_1,demo_ds_0.t_order_item_0,demo_ds_1.t_order_item_1,demo_ds_1.t_order_item_0");


[INFO ] 2019-01-18 10:27:23,760 --main-- [ShardingSphere-SQL] Logic SQL: SELECT i.* FROM t_order o, t_order_item i WHERE o.order_id = i.order_id AND o.order_id = 292966288664297473 
[INFO ] 2019-01-18 10:27:23,760 --main-- [ShardingSphere-SQL] SQLStatement: SelectStatement(super=DQLStatement(super=io.shardingsphere.core.parsing.parser.sql.dql.select.SelectStatement@4da9f723), containStar=true, selectListLastPosition=11, groupByLastPosition=0, items=[StarSelectItem(owner=Optional.of(i))], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null, subQueryStatements=[]) 
[INFO ] 2019-01-18 10:27:23,760 --main-- [ShardingSphere-SQL] Actual SQL: demo_ds_0 ::: SELECT i.* FROM t_order_1 o, t_order_item_0 i WHERE o.order_id = i.order_id AND o.order_id = 292966288664297473 
[INFO ] 2019-01-18 10:27:23,760 --main-- [ShardingSphere-SQL] Actual SQL: demo_ds_1 ::: SELECT i.* FROM t_order_1 o, t_order_item_0 i WHERE o.order_id = i.order_id AND o.order_id = 292966288664297473 

order data in dataNode[demo_ds_1.t_order_1] and order_item   data in   dataNode[demo_ds_1.t_order_item_1],So the two statements routed are not satisfied, so the results can not be found.
