### ISSUE TITLE
GROUP_CONCAT print error log "no viable alternative at input"

### ISSUE THREAD

**Issue by lin199231** [apache/incubator-shardingsphere#1764]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**### Which version of ShardingSphere did you use?**
3.1.0

**### Which project did you use? Sharding-JDBC or Sharding-Proxy?**
Sharding-JDBC

SQL

> SELECT GROUP_CONCAT(column) FROM table

there will a error log, but the result is right. Not happen when use spring-jdbc

error log:

> line 1:34 no viable alternative at input 'GROUP_CONCAT(authority.name)'

Would you tell me the reason, please?

**Comment by codefairy08** [comment]
thanks,  i will fix it
