### ISSUE TITLE
some case,SELECT COUNT(DISTINCT col1) FROM tbl_name   cannot working as expected

### ISSUE THREAD

**Issue by stoneSpoon** [apache/incubator-shardingsphere#1772]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-jdbc-core 3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
selcect  COUNT(DISTINCT col1)  can Get the correct calculation
### Actual behavior
console println below Exception
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0] with root cause 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
....
### Reason analyze 
[myAnalyze.txt](https://github.com/apache/incubator-shardingsphere/files/2767561/myAnalyze.txt)
(If you can)
Please refer to the attachment for details.

**Comment by tristaZero** [comment]
This problem has been fixed in 4.0.0.M1-SNAPSHOT.

**Comment by tuohai666** [comment]
Known issue. Please refer to:
https://github.com/apache/incubator-shardingsphere/issues/1718
