### ISSUE TITLE
Sharding-jdbc supports multiple logic databases

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#1779]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No
### Describe the feature you would like.
Since I've been using the Orchestration to manage sharding-jdbc configurations, the project depending on datasource connection only need to refer the logic db by this way:
```
sharding.jdbc.config.orchestration.name=db1
sharding.jdbc.config.orchestration.overwrite=false
sharding.jdbc.config.orchestration.registry.namespace=sharding-jdbc-business
sharding.jdbc.config.orchestration.registry.server-lists=10.x.x.x:2181
```
The Question is that some projects need to connect to multiple logic databases( for example the backend management system), and I what I want is to refer multiple logic databases like this way:
```
sharding.jdbc.config.orchestration.name=db1,db2,db3
```
So I can then change these logic databases in my projects dynamically.

By the way, after reading source code, I find there is only one logic db named ```logic_db``` existing in context by hard coding. I wonder If it can be renamed to the orchestration name which could make it more convenient to manage these logic databases.

**Comment by terrymanu** [comment]
We have no plan to do it, anybody inserted on that maybe provide pull request.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
