### ISSUE TITLE
How to configure multi-statement-allow

### ISSUE THREAD

**Issue by lsz-clark** [apache/incubator-shardingsphere#1780]
**my "application.properties"**
sharding.jdbc.datasource.t_user_0.filter.wall.enabled = true
sharding.jdbc.datasource.t_user_0.filter.wall.config.multi-statement-allow = true

but, can not suport

How can I configure it?

sharding-jdbc 2.0.3 + druid Datasource

**Comment by terrymanu** [comment]
can not support it
