### ISSUE TITLE
Fail in updating mulitiple tables' field values in one update statement

### ISSUE THREAD

**Issue by jmbkeyes** [apache/incubator-shardingsphere#1786]
## Bug Report
There is a bug when updating serveral tables' field values.

UPDATE group_booking gb 
INNER JOIN group_booking_instance gbi ON gbi.groupBookingId = gb.id and gbi.`status` = 1  
INNER JOIN group_booking_instance_detail gbd ON gbd.groupBookingInstanceId = gbi.id 
SET gb.`status` = 2,gbi.`status` = 3,gbd.`status` = 4 
WHERE gb.endTs < now() AND gb. STATUS = 3

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
the sql should be successful.
### Actual behavior
NullPoinerException, but deep into the actual exception is
io.shardingsphere.core.parsing.parser.exception.SQLParsingUnsupportedException: Cannot support Multiple-Table.

**Comment by terrymanu** [comment]
Hello, this is an excepted exception.

**Comment by jmbkeyes** [comment]
Hmm, It maybe my misunderstanding. 
![image](https://user-images.githubusercontent.com/12583734/51453474-98e6f800-1d7a-11e9-8418-db751c270d3e.png)

As the 3.1.0 release notes said "All SQL 100% compatible if route to single data node (MySQL Only)."

**Comment by Anricx** [comment]
will 4.x support this feature?
