### ISSUE TITLE
 Sharding-Jdbc Can't continue running（Locked?）

### ISSUE THREAD

**Issue by oawang** [apache/incubator-shardingsphere#1793]
Which version of ShardingSphere did you use?
3.0.0
Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Jdbc
Expected behavior
Can't continue running
Actual behavior
Read DatabaseMetaData is locked When start running
Reason analyze (If you can)
I guess the Sharding-Jdbc read data lock

jstack>>>>>>>>>>>>>>>>>>>>>

[jstack (2).txt](https://github.com/apache/incubator-shardingsphere/files/2781250/jstack.2.txt)

**Comment by terrymanu** [comment]
I saw this info from your jstack:

```
"Druid-ConnectionPool-Create-756222660" #30 daemon prio=5 os_prio=0 tid=0x00007f1715a4b800 nid=0x1ad5 waiting on condition [0x00007f16e0094000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000fd3197f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2443)
```

Did you close your connection correctly?

**Comment by oawang** [comment]
亮哥，英文不给力呀，中文回你。背景：大概有不到十个业务系统（应用），按业务来做分库，每个应用各自跑了128个分片，每个分片初始一个连接。Spring boot 启动过程中，当初始化到128个分片时就会出现程序卡顿的问题

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
