### ISSUE TITLE
Shardgingsphere 3.1.0, Oracle 11g, unable to access the data source, data source in the acquisition of stuck phenomenon, using version 2.0.3 everything is normal.

### ISSUE THREAD

**Issue by ganlulei** [apache/incubator-shardingsphere#1809]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Shardgingsphere 3.1.0, Oracle 11g, unable to access the data source, data source in the acquisition of stuck phenomenon, using version 2.0.3 everything is normal.

**Comment by terrymanu** [comment]
Can you paste jstack info here

**Comment by ganlulei** [comment]
2019-01-24 13:18:14,462 [RMI TCP Connection(2)-127.0.0.1] [com.alibaba.druid.pool.DruidDataSource]-[INFO] {dataSource-1} inited

**Comment by ganlulei** [comment]
Stop here all the time and you can't continue to execute it.

**Comment by zjcnb** [comment]
you can debug this class：YamlTableRuleConfiguration build()

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
