### ISSUE TITLE
typo in cn doc

### ISSUE THREAD

**Issue by hqq2023623** [apache/incubator-shardingsphere#1811]
English doc : Architects can adjust the system architecture to the most applicable one to current business more freely
Google translate : 使得架构师可以更自由地将系统架构调整为最适用于当前业务的架构
cn doc :
http://shardingsphere.io/document/current/cn/overview/
 _使得架构师_ 更加自由的调整 _适合与_ 当前业务的最佳系统架构

1、change "适用与" to "适用于" and "使得架构师" to "使得架构师可以" or "架构师可以"
2、Just use the google translate which is more unified

**Comment by terrymanu** [comment]
fixed at https://github.com/apache/incubator-shardingsphere-doc/commit/2400f71a73a76db1fe35303787880eea8edb8850
