### ISSUE TITLE
How to do config the sharding rule for date split usage? 

### ISSUE THREAD

**Issue by ruiaylin** [apache/incubator-shardingsphere#1815]
## Question

 I want to do sharding functionality to my app using sharding-proxy. 
The Rule is every table per/month , the sharding key is datetime . Now I do not know how to config the rule in 
config-sharding.yaml.  I can not find information about this . who can gives me a example ?

**Comment by terrymanu** [comment]
you can develop customized sharding algorithm by yourself

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
