### ISSUE TITLE
关于springboot application.properties中写数据库名称带下划线启动报错的问题

### ISSUE THREAD

**Issue by huhaoshida** [apache/incubator-shardingsphere#1821]
sharding.jdbc.datasource.names=master_0,master_1

sharding.jdbc.datasource.master_0.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.master_0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.master_0.url=jdbc:mysql://xxx.xx.xx.xxx:3306/master_0
sharding.jdbc.datasource.master_0.username=root
sharding.jdbc.datasource.master_0.password=123456

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
