### ISSUE TITLE
 When will the the sharding sphere 4.0.0 be released。

### ISSUE THREAD

**Issue by guowdxp** [apache/incubator-shardingsphere#1828]
A few days ago, I found that the sharding-sphere 3.1.0 version has a bug with character sharding, and issued an issue (#1813). You replied that the bug has been fixed. After testing, the bug is indeed fixed. I want to know  When will the the sharding sphere 4.0.0 be released?

**Comment by terrymanu** [comment]
FYI: https://lists.apache.org/thread.html/f9ec4720b3bce7c63d22d6a6995d606f8016c5ba4b51973c1b3a0300@%3Cdev.shardingsphere.apache.org%3E

**Comment by jiejiecool** [comment]
group_concat function isn't supported in version 3.1.0,and i can't see the time 4.0.0.M1 will be released.
so when will 4.0.0.M1 be released?
