### ISSUE TITLE
What's this configuration: ' proxy.backend.use.nio' used for in sharding-proxy?

### ISSUE THREAD

**Issue by pleasecheckhere2016** [apache/incubator-shardingsphere#1839]
version:3.1.0

If I configure 'proxy.backend.use.nio=true' in sharding-proxy  server.yaml, sharding-proxy cyclic print  the following logs  and do noting with my target sql:

`[INFO ] 15:51:17.400 [nioEventLoopGroup-3-1] i.n.handler.logging.LoggingHandler - [id: 0x973f6c23, L:/0:0:0:0:0:0:0:0:3307] READ: [id: 0x2a38ed70, L:/10.22.3.47:3307 - R:/10.22.3.47:61936]
[INFO ] 15:51:17.400 [nioEventLoopGroup-3-1] i.n.handler.logging.LoggingHandler - [id: 0x973f6c23, L:/0:0:0:0:0:0:0:0:3307] READ COMPLETE
[INFO ] 15:51:17.415 [ShardingSphere-Command-1] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 15:51:17.415 [ShardingSphere-Command-1] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.46 ( Revision: 9cc87a48e75c2d2e87c1a293b2862ce651cb256e ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 15:51:17.415 [ShardingSphere-Command-1] ShardingSphere-SQL - SQLStatement: SelectStatement(super=DQLStatement(super=io.shardingsphere.core.parsing.parser.sql.dql.select.SelectStatement@3afe0d6e), containStar=false, firstSelectItemStartPosition=96, selectListLastPosition=924, groupByLastPosition=0, items=[CommonSelectItem(expression=@@session.auto_increment_increment AS auto_increment_increment, alias=Optional.of(auto_increment_increment)), CommonSelectItem(expression=@@character_set_client AS character_set_client, alias=Optional.of(character_set_client)), CommonSelectItem(expression=@@character_set_connection AS character_set_connection, alias=Optional.of(character_set_connection)), CommonSelectItem(expression=@@character_set_results AS character_set_results, alias=Optional.of(character_set_results)), CommonSelectItem(expression=@@character_set_server AS character_set_server, alias=Optional.of(character_set_server)), CommonSelectItem(expression=@@collation_server AS collation_server, alias=Optional.of(collation_server)), CommonSelectItem(expression=@@init_connect AS init_connect, alias=Optional.of(init_connect)), CommonSelectItem(expression=@@interactive_timeout AS interactive_timeout, alias=Optional.of(interactive_timeout)), CommonSelectItem(expression=@@license AS license, alias=Optional.of(license)), CommonSelectItem(expression=@@lower_case_table_names AS lower_case_table_names, alias=Optional.of(lower_case_table_names)), CommonSelectItem(expression=@@max_allowed_packet AS max_allowed_packet, alias=Optional.of(max_allowed_packet)), CommonSelectItem(expression=@@net_buffer_length AS net_buffer_length, alias=Optional.of(net_buffer_length)), CommonSelectItem(expression=@@net_write_timeout AS net_write_timeout, alias=Optional.of(net_write_timeout)), CommonSelectItem(expression=@@query_cache_size AS query_cache_size, alias=Optional.of(query_cache_size)), CommonSelectItem(expression=@@query_cache_type AS query_cache_type, alias=Optional.of(query_cache_type)), CommonSelectItem(expression=@@sql_mode AS sql_mode, alias=Optional.of(sql_mode)), CommonSelectItem(expression=@@system_time_zone AS system_time_zone, alias=Optional.of(system_time_zone)), CommonSelectItem(expression=@@time_zone AS time_zone, alias=Optional.of(time_zone)), CommonSelectItem(expression=@@tx_isolation AS transaction_isolation, alias=Optional.of(transaction_isolation)), CommonSelectItem(expression=@@wait_timeout AS wait_timeout, alias=Optional.of(wait_timeout))], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null, subQueryStatements=[], subQueryConditions=[])
[INFO ] 15:51:17.415 [ShardingSphere-Command-1] ShardingSphere-SQL - Actual SQL: ds_0 ::: /* mysql-connector-java-5.1.46 ( Revision: 9cc87a48e75c2d2e87c1a293b2862ce651cb256e ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
[INFO ] 15:51:17.946 [nioEventLoopGroup-3-1] i.n.handler.logging.LoggingHandler - [id: 0x973f6c23, L:/0:0:0:0:0:0:0:0:3307] READ: [id: 0x54384473, L:/10.22.3.47:3307 - R:/10.22.3.47:61937]
[INFO ] 15:51:17.946 [nioEventLoopGroup-3-1] i.n.handler.logging.LoggingHandler - [id: 0x973f6c23, L:/0:0:0:0:0:0:0:0:3307] READ COMPLETE
[INFO ] 15:51:17.946 [ShardingSphere-Command-2] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 15:51:17.946 [ShardingSphere-Command-2] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.46 ( Revision: 9cc87a48e75c2d2e87c1a293b2862ce651cb256e ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout.......
`
is this a bug or an unfinished code?

**Comment by terrymanu** [comment]
useless for now, please ignore.
This is configuration never in document
