### ISSUE TITLE
sharding-jdbc schema need to be configurable 

### ISSUE THREAD

**Issue by kofkyobsa** [apache/incubator-shardingsphere#1846]
Which version of Sharding-Sphere do you using?
3.1.0

Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

if i use one zk center for sharding-jdbc and sharding-proxy, and i use multiple schema, the sharding-jdbc in app needs to know which schema it use~

**Comment by terrymanu** [comment]
duplicate with #1779
