### ISSUE TITLE
pagination is not working well after 3.1.0

### ISSUE THREAD

**Issue by xuchaoguo1983** [apache/incubator-shardingsphere#1857]
I have a table with no sharding configuration, if I try to ask a page request with certain offset (not zero), it will always return the first page.

I took a look at class DQLMergeEngine, and found that some weird code below.
`@Override
    public MergedResult merge() throws SQLException {
        if (1 == queryResults.size()) {
            return new IteratorStreamMergedResult(queryResults);
        }
        selectStatement.setIndexForItems(columnLabelIndexMap);
        return decorate(build());
    }`
    
it will always return IteratorStreamMergedResult instance even it's a select request with limit.

It's working at 3.0.0 with different logic, please take a look.

**Comment by tuohai666** [comment]
Your description is not very clear. Please fill in the template below.
Also, I suggest you use dev brance have a try. Several pagination issue have been resolved in dev:

**Comment by tuohai666** [comment]
Duplicate with https://github.com/apache/incubator-shardingsphere/issues/1722
Please try 4.0.0.M1.
