### ISSUE TITLE
Add TransactionalDataSource to encapsulation distribute transaction. 

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#1858]
Now we have provided a mechanism to ensure the distributed transaction in one `ShardingDataSource`. we can extract an independent `TransactionalDataSource` which include all distributed transaction operation. according to implement JTA Transaction manager interface, we can support transaction between different `TransactionalDataSource`. `ShardingDataSource` will upgrade to `TransactionalDataSource` if you have depended transaction module, here is the draft design, please feel free to give us some idea.

![image](https://user-images.githubusercontent.com/8317649/52610952-34711180-2ebe-11e9-8dbb-c81c506c55f3.png)

**Comment by zhfeng** [comment]
It looks good but I just wonder what is the different between "sharding" and "normal" TransactionalDataSource ?

**Comment by cherrylzhao** [comment]
normal TransactionalDataSource only wrap the non-sharding datasource (ex: raw hikari) for supporting  distribute transaction. and sharding TransactionalDataSource will support both sharding and distribute transaction.

**Comment by zhfeng** [comment]
Thanks for the explanation and from user's perspective, they DO NOT need to know the detail of the data source and just declare that it depends on the transaction and we will wrap it with the right TransacionalDataSource ?

**Comment by cherrylzhao** [comment]
yes, we will provide api and spring-boot and namespace configuration to make the wrap transactionalDataSource easy.

**Comment by terrymanu** [comment]
Close for expired
