### ISSUE TITLE
subquery with sharding key cannot work as expected

### ISSUE THREAD

**Issue by stoneSpoon** [apache/incubator-shardingsphere#1862]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
subquery can  work as expect
### Reason analyze (If you can)

[bug.txt](https://github.com/apache/incubator-shardingsphere/files/2864758/bug.txt)

**Comment by terrymanu** [comment]
duplicated with #1753
