### ISSUE TITLE
springboot2.0.7+shardingsphere3.0.0版本在mysql驱动版本为6.0+时不兼容

### ISSUE THREAD

**Issue by biuabiu** [apache/incubator-shardingsphere#1869]
![image](https://user-images.githubusercontent.com/38499411/52845002-f8011800-3140-11e9-964f-6a519cb8258a.png)
高版本mysql驱动是需要带时区的

**Comment by biuabiu** [comment]
是我简写了mysql的host和port,请完善

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
