### ISSUE TITLE
please help me:why do i start project slowly after integration shardingjdbc??

### ISSUE THREAD

**Issue by lemon-simple** [apache/incubator-shardingsphere#1872]
## Question

why do i start project slowly after integration shardingjdbc?? more than 2 minutes.
how to reslove，please help me.

most time spent on these actions,the details are as follows:

![image](https://user-images.githubusercontent.com/28141497/52896699-47f5e280-3206-11e9-9a9f-012148e54248.png)

**Comment by terrymanu** [comment]
try to close metadata check

**Comment by terrymanu** [comment]
for version 3.1.0, it will disable metadata check by default

**Comment by terrymanu** [comment]
duplicate with #1688
