### ISSUE TITLE
Add API for configuring whether ShardingSphere cache the metadata of the same sharding tables at startup

### ISSUE THREAD

**Issue by shaojie925** [apache/incubator-shardingsphere#1874]
Add API for configuring whether ShardingSphere cache the metadata of the same sharding tables at startup.

### Question
Many users will pay more attention on performance at startup, and the metadata of the sharding-tables are mostly the same. So add a cache can reduce startup time.

Therefore we will add API to make user decide to cache metatata or not.

**Comment by terrymanu** [comment]
duplicate with #1688

**Comment by shaojie925** [comment]
It is not a duplicate question with #1688. I means the sharding tables of the same logical table all have the same table structure, so we don't need to load the table structure of each table from the database. we can cache the table structure of the same logical table and therefore reducing the startup time.

**Comment by shaojie925** [comment]
<img width="1183" alt="25ac7f77-1c68-40b7-b836-1b2a5df96867" src="https://user-images.githubusercontent.com/11688731/52909908-81902180-32ca-11e9-8918-5cd105bed292.png">
