### ISSUE TITLE
SQLStatement cache for parser-engine should not be a singleton object

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#1877]
we have used a singleton `ParsingResultCache` which key is prepared logic-sql to cache the SQLStatement. if the sharding-rule of the logic-sql have changed, or access the same logic-sql from multi-sharding-datasources, we will get an unexpected SQLStatement which sharding-condition is wrong. so we should cache the parsed SQLStatement within lifecycle of `ShardingContext`.

- [x] Make ParsingResultCache multi-instances available
- [x] Using ParsingResultCache in ShardingContext
- [x] resolve memory leak for hash map

**Comment by terrymanu** [comment]
fixed with #1921

**Comment by techzealot** [comment]
> fixed with #1921

is there any way to resolve this problem in version 3.1.0?thank you!
