### ISSUE TITLE
a question about Database connection PoolSize

### ISSUE THREAD

**Issue by jizhidezhaojun** [apache/incubator-shardingsphere#1879]
## Question

I set the maximumPoolSize=20,not set the minimumPoolSize,then i found the Database connection PoolSize is 20.Is that the right performance? 
if i only set the maximumPoolSize,the Database connection PoolSize will be maximumPoolSize.Can I think so?
Thank you!

**The conf is below:**

schemaName: xxs
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/xxs?serverTimezone=UTC&useSSL=false&useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: 123456
    autoCommit: true
    connectionTimeout: 10000
    idleTimeout: 30000
    maxLifetime: 5000000
    maximumPoolSize: 20

shardingRule:
  defaultTableStrategy:
    none:
  props:
    sql.show: true

**Comment by terrymanu** [comment]
Sharding-Proxy use hikariCP, the data source pool param is same meaning with hikariCP.
You can check hikariCP for more info

**Comment by jizhidezhaojun** [comment]
Thanks for reply!
I have another question.I found that there is no **minimumPoolSize** config in Sharding-Proxy 3.3.0.Is that true?Or it is exists and I just not found?
Thanks!
