### ISSUE TITLE
ShardingStrategyConfiguration changed, and  unfriendly to extension

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#1881]
in the old version (2.x) of sharding-jdbc, the ShardingStrategyConfiguration interface has a build method.
so we can make extension like CustomStrategyConfiguration and use CustomStrategy extend ShardingStrategy.

now in the new version (3.x),  it use a final class ShardingStrategyFactory to create ShardingStrategy and we cannot extend it anymore. It may be a bad idea to do this change and customized sharding strategy is necessary sometimes.

Otherwise we suggest to add some context to ShardingStrategy.doSharding method, because we need more info to do the sharding, not only the availableTargetNames and shardingValues.

**Comment by terrymanu** [comment]
We never want user to extent API. Java Vector is a bad example
