### ISSUE TITLE
between ... and ... for column of datetime  type is not supported

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#1884]
## Bug Report
SQL like "select * from t_order  where create_time between '2018-01-01 00:00:00' and '2018-01-02 00:00:00'"  is not supported, we use create_time for RangeShardingAlgorithm
` public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<String> value)`

CommonExpressionSegment.java not support the string value and in the code of PredicateExtractor
it extract the number value and ignore the string value.
` private Optional<? extends ExpressionSegment> buildExpression(final Map<ParserRuleContext, Integer> questionNodeIndexMap, final ParserRuleContext valueNode) {
        Optional<? extends ExpressionSegment> sqlExpression = new ExpressionExtractor().extract(valueNode);
        if (!sqlExpression.isPresent() || !(sqlExpression.get() instanceof CommonExpressionSegment)) {
            return sqlExpression;
        }
        CommonExpressionSegment commonExpressionSegment = (CommonExpressionSegment) sqlExpression.get();
        Optional<ParserRuleContext> expressionNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.QUESTION);
        if (expressionNode.isPresent()) {
            Integer index = questionNodeIndexMap.get(expressionNode.get());
            commonExpressionSegment.setIndex(index);
        } else {
            Optional<ParserRuleContext> bitExprNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.BIT_EXPR);
            expressionNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.NUMBER);
            if (expressionNode.isPresent() && (!bitExprNode.isPresent() || 1 == bitExprNode.get().getChildCount())) {
                commonExpressionSegment.setValue(NumberUtil.getExactlyNumber(expressionNode.get().getText(), 10));
            }
        }
        return sqlExpression;
    }`

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
supported
### Actual behavior
not supported
### Reason analyze (If you can)
as mentioned above
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
as mentioned above
### Example codes for reproduce this issue (such as a github link).
as mentioned above

**Comment by terrymanu** [comment]
It is depends on your customized RangeShardingAlgorithm, in your example, the generic of  RangeShardingAlgorithm is String, not Date
