### ISSUE TITLE
Left Join不支持<符号 SQL syntax error, expected token is 'EQ', actual token is 'LT', literals is '<'.

### ISSUE THREAD

**Issue by zhengwangColder** [apache/incubator-shardingsphere#1886]
SQL如下
SELECT m1.* FROM phone_tag m1
        LEFT JOIN phone_tag m2 ON m1.telephone = m2.telephone AND m1.updatetime &lt; m2.updatetime
        WHERE m1.telephone in
        (
        <foreach item="item" collection="telephones" index="index" separator=",">
            #{item}
        </foreach>
        ) AND m2.id is NULL AND m1.isactive = 1;

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
