### ISSUE TITLE
Each logical table only needs to load one sharding table metadata instead of loading each of the sharding tables.

### ISSUE THREAD

**Issue by shaojie925** [apache/incubator-shardingsphere#1888]
### Which version of Sharding-Sphere do you using?
3.1.0

### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
All sharding tables' structure of a logic table are mostly same, so we can load one sharding table metadata instead of loading each of the sharding tables.

### Actual behavior
Loading all metadata from database, causing startup too slowly.
check.table.metadata.enabled = false

<img width="1080" alt="96e686af-0c11-4285-9161-9f5c2135502c" src="https://user-images.githubusercontent.com/11688731/53022912-265f5a00-3497-11e9-8cce-941ad0092eda.png">

<img width="1182" alt="931d5ce9-a4c2-47ac-89ed-40706a420e51" src="https://user-images.githubusercontent.com/11688731/53023008-60c8f700-3497-11e9-8cfd-0ef887a42d2e.png">

**Comment by terrymanu** [comment]
duplicate with #1688
