### ISSUE TITLE
Why didn't I find sharding-jdbc-spring-namespace moudle in the source code

### ISSUE THREAD

**Issue by JeddyHj** [apache/incubator-shardingsphere#1889]
Why didn't I find sharding-jdbc-spring-namespace moudle in the source code

**Comment by terrymanu** [comment]
They are not in apache repo

**Comment by terrymanu** [comment]
We need adjust on this module and cannot put into apache repo now

**Comment by daizf** [comment]
@terrymanu Brother liang:
Where can I get the source of sharding-jdbc-spring-namespace moudle for V3.1.0 ?
