### ISSUE TITLE
Left Join not support < sign. Detail Exception: SQL syntax error, expected token is 'EQ', actual token is 'LT', literals is '<'

### ISSUE THREAD

**Issue by zhengwangColder** [apache/incubator-shardingsphere#1890]
Deatil SQL follow:
SELECT m1.* FROM phone_tag m1
LEFT JOIN phone_tag m2 ON m1.telephone = m2.telephone AND m1.updatetime < m2.updatetime
WHERE m1.telephone in
(

#{item}

) AND m2.id is NULL AND m1.isactive = 1;

**Comment by terrymanu** [comment]
duplicate with #1819
