### ISSUE TITLE
order by 排序有问题

### ISSUE THREAD

**Issue by mcdull6226** [apache/incubator-shardingsphere#1891]
select id,price/origin from goods group by id order by price/origin;
select id,price/origin as t from goods group by id order by t;
select id,abs(price/origin) as t from goods group by id order by t;
select id,price/origin from goods group by id order by price/origin limit 0,10;
第一条是OK的下面的都不行,

select id,abs(price/origin) as t from goods group by id order by t;这样也是OK的

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
