### ISSUE TITLE
Remove netty backend impl

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#1893]
Netty backend impl doesn't make sense for Sharding-Proxy now.
Netty backend impl is big different with JDBC backend impl, continue to implement Netty backend impl need to spend more time. 
So we just remove it now.
In future we want to abstract SPI to provide interface for communication module only, and will try to implement a new Netty backend impl again.

**Comment by sgc109** [comment]
Aren't there any future plans for this?
