### ISSUE TITLE
3.1.0版本怀疑内存泄露

### ISSUE THREAD

**Issue by Mkeeper6** [apache/incubator-shardingsphere#1902]
Sharding JDBC更新3.1.0 ,分库分表查询，开始内存泄露；

MAT分析结果：

![image](https://user-images.githubusercontent.com/12479469/53091110-0b9aed00-354c-11e9-8feb-7e40304cc140.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
