### ISSUE TITLE
解析mysql关键字status解析不出来？

### ISSUE THREAD

**Issue by winrunwang** [apache/incubator-shardingsphere#1906]
是否是个BUG？
我翻看源代码查到parseSelectItemAlias这个类里面getCustomizedAvailableKeywordsForSelectItemAlias这个方法里面没有加入MySQLKeyword.STATUS.

目前还不确定是否是个BUG。

希望解答

**Comment by winrunwang** [comment]
版本号是Sharding-Sphere 3.0.0.M4

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
