### ISSUE TITLE
Log configuration from reg center into log files

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#1907]
Log configuration online into log files
- [ ] At start up, we will write configuration online into log files in the uniform format.
- [ ] When configuration is refreshed, new configuration will be written into log files.
- [ ] Move the module of yaml conversion from orchestration to sharding core.

**Comment by wgy8283335** [comment]
I'd like to take the issue!But,is it friendly for first time contributing?

**Comment by wgy8283335** [comment]
I'd like to take the issue.Could you explain what is "write configuration online"? And which version should I code on,3.1.0 or 4.0.0-RC1?

**Comment by wgy8283335** [comment]
I'd like to take the issue.Could you explain what is "write configuration online"? And which version should I code on,3.1.0 or 4.0.0-RC1?@terrymanu

**Comment by terrymanu** [comment]
I just modify title of this issue

**Comment by wgy8283335** [comment]
And which version should I pull from project for contributing the issue ,3.1.0 or 4.0.0-RC1?@terrymanu

**Comment by terrymanu** [comment]
@wgy8283335 all pr should base on dev branch
