### ISSUE TITLE
ParsingReultCache Object may cause Memory leak

### ISSUE THREAD

**Issue by Mkeeper6** [apache/incubator-shardingsphere#1916]
## Bug Report

ParsingReultCache Object may cause Memory leak

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
query data

### Actual behavior
query data

### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/12479469/53321292-f7236f80-3912-11e9-9c44-cadc3f7a2d22.png)
Cache SQL 2.9G, Meybe Memory leak

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
select * from table where time 

select id, user_id, room_id,, member_type  from table_20190225 WHERE id = ? and dateline between ? and ?

**Comment by terrymanu** [comment]
duplicated with #1877
