### ISSUE TITLE
[sharding.jdbc.config.orchestration.overwrite = false]  not work

### ISSUE THREAD

**Issue by zouxiaoming2000** [apache/incubator-shardingsphere#1924]
## Bug Report

according to the official documentation, if set up sharding.jdbc.config.orchestration.overwrite = false, so would prefer using the registry configuration to cover local configuration, but the actual testing failed to meet expectations.

In the current experiment with read-write separation using version 3.0.0, the local configuration was used every time the application was started, and the configuration data source in the zookeeper registry was not used.

**Comment by tristaZero** [comment]
@zouxiaoming2000 
Hi, i speculate you mistake this setting item.
If you set sharding.jdbc.config.orchestration.overwrite to false, the local configuration will not be written to registry, and the shardingSphere will start up with local config.  if you want to use the configuration from regsitry, you only need to write the configuration of zookeeper into configuration file.
