### ISSUE TITLE
why HOLD_CURSORS_OVER_COMMIT NOT CLOSE_CURSORS_AT_COMMIT

### ISSUE THREAD

**Issue by baisijian** [apache/incubator-shardingsphere#1926]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Can you make your words clear?

**Comment by baisijian** [comment]
thank you for reply,
i saw sharding using ResultSet.HOLD_CURSORS_OVER_COMMIT instead of CLOSE_CURSORS_AT_COMMIT , HOLD_CURSORS_OVER_COMMIT is support at jdbc 3.0 ,  If I change  HOLD_CURSORS_OVER_COMMIT  to CLOSE_CURSORS_AT_COMMIT , sharding will still working fine?

code: MasterSlavePreparedStatement.java:50
        this(connection, sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);

**Comment by terrymanu** [comment]
I don't test it, do you meet some problem if change it?

**Comment by terrymanu** [comment]
If no update, i will close this issue the day after tomorrow.

**Comment by baisijian** [comment]
Thanks a lot
