### ISSUE TITLE
Route error when query table sharded by string column

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#1931]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
no error
### Actual behavior
```
ERROR 3054 (HY000): Unknown exception: java.lang.Integer cannot be cast to java.lang.String
```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. configure a string column A as sharding column.
2. select * from x where A='abc';
3. error

**Comment by terrymanu** [comment]
This problem cause by your customized algorithm use int to sharding, and sharding value in SQL is varchar.
