### ISSUE TITLE
7/5000   Distributed primary key issues

### ISSUE THREAD

**Issue by maomy** [apache/incubator-shardingsphere#1946]
Does your distributed primary key use the default snowflake algorithm? Can you have a problem, encounter a problem in use process?

**Comment by terrymanu** [comment]
What is your question?

**Comment by terrymanu** [comment]
If no other update, I will close this issue tomorrow.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
