### ISSUE TITLE
Insert data to all sharding table when the value of sharing column is null.

### ISSUE THREAD

**Issue by songxu** [apache/incubator-shardingsphere#1966]
# Version
## io.shardingsphere.sharding-jdbc-spring-boot-starter:3.0.0
io.shardingsphere Configuration:
sharding.jdbc.datasource.names=ds
sharding.jdbc.datasource.ds.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.config.sharding.tables.test_record.actual-data-nodes=ds.test_record_${0..9}
sharding.jdbc.config.sharding.tables.test_record.table-strategy.inline.sharding-column=record_id
sharding.jdbc.config.sharding.tables.test_record.table-strategy.inline.algorithm-expression=test_record_${record_id % 10}
sharding.jdbc.config.sharding.default-data-source-name=ds
sharding.jdbc.config.props.sql.show=true

## Mybatis Version: 3.4.6

# Issue:
Insert record to sharing table: test_record with mybatis insertSelective, if the value of sharding-column:record_id is null, it will insert records to all sharing tables( test_record_0...,test_record_9).
# Expected result:
throw exception instead of insert records to all sharing tables.

**Comment by terrymanu** [comment]
What is your expected behaviour if sharding value is null?

**Comment by songxu** [comment]
> What is your expected behaviour if sharding value is null?

I expected to thrown an exception.

**Comment by songxu** [comment]
If has a variable to config the behavior: throw exception or insert to all table will be good.

**Comment by terrymanu** [comment]
throw exception from shardingsphere maybe not a good idea.
shardingsphere should leave it to sharding strategy to let end user to make decision.

**Comment by terrymanu** [comment]
No response any more, I just close this issue.
