### ISSUE TITLE
support to check slave replication lag and deactivate slave data source

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#1968]
## Feature Request

i suggest to add the feature to check the slave replication status.
if the slave replication lag is very huge and exceed the threshold , then deactivate the slave data source for query.
for example we can use Seconds_Behind_Master to determine the replication delay.

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
Promote the high availability for production usage.

**Comment by terrymanu** [comment]
ShradingSphere is not MySQL database middleware, it is a public databases middleware, we don't want to MySQL special on this product.
Management MySQL is another tool, I think user should separate them. Any suggestions?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
