### ISSUE TITLE
DefaultDataSource config not useful 

### ISSUE THREAD

**Issue by mfeng-ya** [apache/incubator-shardingsphere#1971]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
no config rule table use default datasource
### Actual behavior
always first datasource used
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/42688346/53799664-dcd23d00-3f75-11e9-9652-30b68e887891.png)

**Comment by cherrylzhao** [comment]
hi, thanks for feedback. we have fixed this issue in 4.0.0.M1-SNAPSHOT, you can verify it in dev branch, thanks.

**Comment by cherrylzhao** [comment]
fix at #1713
