### ISSUE TITLE
no config rule table limit error

### ISSUE THREAD

**Issue by mfeng-ya** [apache/incubator-shardingsphere#1972]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
no config rule table without rewrite sql
### Actual behavior
limit sql rewrite

**Comment by terrymanu** [comment]
What's mean 'no config rule table'?

**Comment by mfeng-ya** [comment]
Table not sharding,used dedaut datasource

**Comment by mfeng-ya** [comment]
Table not sharding, used default datasource

**Comment by tuohai666** [comment]
Please refer to https://github.com/apache/incubator-shardingsphere/issues/1857
