### ISSUE TITLE
How to configure a custom sharding strategy?

### ISSUE THREAD

**Issue by xiaoxing598** [apache/incubator-shardingsphere#1976]
## Question

1. I use 8 databases at the same time, the sharding strategy needs to be customized, because the modulo algorithm can't meet my requirements, I need to use the consistent hash algorithm.
1. Can I configure sharding-JDBC in both the properties file and the program?
1. I followed the steps below but did not succeed, please help me!

```java
@Configuration
public class ShardingConfig {
    @Bean
    StandardShardingStrategyConfiguration getStandardShardingStrategyConfiguration() {
        return new StandardShardingStrategyConfiguration(
                "order_no",
                new PreciseConsistentHashShardingDatabaseAlgorithm()
        );
    }
}
```

```java
public class PreciseConsistentHashShardingDatabaseAlgorithm implements PreciseShardingAlgorithm<String> {
    @Override
    public String doSharding(final Collection<String> databaseNames, final PreciseShardingValue<String> shardingValue) {
        int nodeNumber = Hashing.consistentHash(Hashing.sha256().hashString(shardingValue.getValue(), StandardCharsets.UTF_8), 8);
        for (String databaseName : databaseNames) {
            if (String.format("db_", nodeNumber).equals(databaseName)) {
                return databaseName;
            }
        }
        throw new UnsupportedOperationException();
    }
}
```

1. Other configuration information is recorded in the properties file, but it is not shown here.
1. According to the above method did not achieve my purpose, that is to say, the custom sharding algorithm does not take effect, I feel that it must be where the configuration problem.
1. If you can configure a custom sharding algorithm in the properties file, that's the most reasonable, because I don't want to do such complicated processing in the program.

**Comment by xiaoxing598** [comment]
What if you specify a custom sharding algorithm in the configuration file?

```properties
sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=master$->{user_id % 2}
```

This should be the question I eventually want to ask. I don't want to move all the configuration in the file into the code.

**Comment by xiaoxing598** [comment]
@terrymanu help me!

**Comment by terrymanu** [comment]
Have you been read document and try to example first?

**Comment by xiaoxing598** [comment]
Please believe me, I have read all the documentation! I found out how to customize the sharding algorithm, but I didn't find how to specify it in the config file, I mean it is configured in the properties file.

**Comment by cherrylzhao** [comment]
please see the raw-jdbc-example

**Comment by tristaZero** [comment]
@xiaoxing598 
[here](https://github.com/apache/incubator-shardingsphere-example/tree/dev/example-utility/src/main/java/io/shardingsphere/example/algorithm) is exmaple.

**Comment by xiaoxing598** [comment]
@tristaZero Thank you for the example given. Can the above rules be applied to the library logic? I don't want to repeat the configuration for each table, after all, their fragmentation rules are the same.

I just tried to use the following configuration, but the log failed.
```
sharding.jdbc.config.sharding.default-database-strategy.inline.preciseAlgorithmClassName = com.xxx.xxx.config.PreciseConsistentHashShardingDatabaseAlgorithm

Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException: Sharding algorithm expression cannot be null.
```

**Comment by xiaoxing598** [comment]
> please see the raw-jdbc-example

I did not find in the project "incubator-shardingsphere-example" how the custom shard logic is configured in the Properties file, only to find out how to use code configuration, and XML file configuration.
There is indeed a missing configuration example for the Properties file.

**Comment by xiaoxing598** [comment]
> @xiaoxing598
> [Here](https://github.com/apache/incubator-shardingsphere-example/tree/dev/example-utility/src/main/java/io/shardingsphere/example/algorithm) is exmaple.
> 
> How to use your customized sharding statergy? Please refer to:
> 
> ```
> sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.standard.sharding-column=order_id
> sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.standard.preciseAlgorithmClassName=io.shardingsphere.example.algorithm.PreciseModuloShardingTableAlgorithm
> ```

I need to set the sharding strategy of the sub-library instead of the sub-table strategy. The example you gave is incorrect.

**Comment by xiaoxing598** [comment]
@terrymanu I need to set the sharding strategy on the specified data node. I don't split the table in my project, just split the different data sources.

I expect to be able to configure this as follows:
```properties 
sharding.jdbc.config.sharding.master-slave-rules.ds0.master-data-source-name = master0
sharding.jdbc.config.sharding.master-slave-rules.ds0.slave-data-source-names = master0slave0
sharding.jdbc.config.sharding.master-slave-rules.ds1.master-data-source-name = master1
sharding.jdbc.config.sharding.master-slave-rules.ds1.slave-data-source-names = master1slave0
sharding.jdbc.config.sharding.master-slave-rules.ds2.master-data-source-name = master2
sharding.jdbc.config.sharding.master-slave-rules.ds2.slave-data-source-names = master2slave0

sharding.jdbc.config.sharding.master-slave-rules.ds->{1..2}.strategy.preciseAlgorithmClassName=xxx.PreciseConsistentHashShardingDatabaseAlgorithm
```

**Comment by xiaoxing598** [comment]
@tristaZero According to the following configuration, I can fulfill my needs.

```Properties
sharding.jdbc.config.sharding.default-database-strategy.standard.sharding-column=order_id
sharding.jdbc.config.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.xxx.config.PreciseConsistentHashShardingDatabaseAlgorithm
```

**Comment by vuhoanghiep1993** [comment]
I add my full source to custom sharding algorithm 

```
    private Map<String, AlgorithmConfiguration> getShardingAlgorithms() {
        Map<String, AlgorithmConfiguration> shardingAlgorithms = new LinkedHashMap<>();

        Properties databaseAlgorithmslocation = new Properties();
        databaseAlgorithmslocation.setProperty("strategy", "standard");
        databaseAlgorithmslocation.setProperty("algorithmClassName", LocationDatasourceShardingAlgorithm.class.getName());
        shardingAlgorithms.put("database-inline-location", new AlgorithmConfiguration("CLASS_BASED", databaseAlgorithmslocation));

        return shardingAlgorithms;
    }

public DataSource getShardingDataSource() throws SQLException {
        Map<String, DataSource> dataSourceMap = new HashMap<>();
        dataSourceMap.put("db0", dataSource0());
        dataSourceMap.put("db1", dataSource1());
        dataSourceMap.put("db2", dataSource2());

        serverMap.put("North", "db0");
        serverMap.put("West", "db1");
        serverMap.put("South", "db2");

        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();

        shardingRuleConfig.setShardingAlgorithms(getShardingAlgorithms());
        orderTableRuleConfig.setDatabaseShardingStrategy(new StandardShardingStrategyConfiguration("location", "database-inline-location"));

        shardingRuleConfig.getTables().add(orderTableRuleConfig);

        return ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton(shardingRuleConfig), properties);
    }

public class LocationDatasourceShardingAlgorithm implements StandardShardingAlgorithm<OrderEntity> {
    @Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<OrderEntity> preciseShardingValue) {
        return serverMap.get(preciseShardingValue.getValue());

    }

    @Override
    public Collection<String> doSharding(Collection collection, RangeShardingValue rangeShardingValue) {
        return collection;

    }
}

```
