### ISSUE TITLE
io.shardingjdbc.core.routing.strategy.hint.HintShardingStrategy#shardingColumns will not setting anyway

### ISSUE THREAD

**Issue by wayne0zhang** [apache/incubator-shardingsphere#1980]
sourceCode:
io.shardingjdbc.core.routing.type.simple.SimpleRoutingEngine#getTableShardingValuesFromHint
this method get shardingValues from ShardingStrategy ,but HintShardingStrategy will not set that value。so HintShardingAlgorithm#sharding   method will never execute.
Is something wrong with my understanding?
so i implements ShardingStrategy to fix this!

public class MyHintShardingStrategy implements ShardingStrategy {

**Comment by tristaZero** [comment]
@wayne0zhang which version do you use?
In latest version, i.e.,4.0.0.M1-SNAPSHOT,
```
package org.apache.shardingsphere.core.routing.type.standard;

private List<RouteValue> getTableShardingValuesFromHint() {
        return getRouteValues(HintManagerHolder.getTableShardingValues(logicTableName));
    }
```
We get shardingValues from HintManagerHolder, where user puts shardingValues. And then we will pass shardingValues to doSharding() in HintShardingAlgorithm, and calculate the target tables by calling doSharding() in HintShardingAlgorithm.

**Comment by wayne0zhang** [comment]
where can i find another version?
https://mvnrepository.com/artifact/io.shardingjdbc/sharding-jdbc-core

**Comment by wayne0zhang** [comment]
> @wayne0zhang which version do you use?
> In latest version, i.e.,4.0.0.M1-SNAPSHOT,
> 
> ```
> package org.apache.shardingsphere.core.routing.type.standard;
> 
> private List<RouteValue> getTableShardingValuesFromHint() {
>         return getRouteValues(HintManagerHolder.getTableShardingValues(logicTableName));
>     }
> ```
> We get shardingValues from HintManagerHolder, where user puts shardingValues. And then we will pass shardingValues to doSharding() in HintShardingAlgorithm, and calculate the target tables by calling doSharding() in HintShardingAlgorithm.
> 
> _**Therefore, shardingColumns in HintShardingStrategy will not be used, but doSharding() in HintShardingAlgorithm will be called anyway.**_

ok ,i got it. you fixed it in the later version. but we can not get it from maven .

**Comment by tristaZero** [comment]
@wayne0zhang  I am sorry, but we will release our next version of Apache in this or next month, and then you can find it in Maven. Thanks for your attention.
