### ISSUE TITLE
single shards limit error

### ISSUE THREAD

**Issue by m65536** [apache/incubator-shardingsphere#1984]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
> 3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
> sharding-jdbc-core
### Actual behavior
> 分页查询路由到单表后，ParsingSQLRouter对limit做了改写（不需要改写limit语句），但是又没有做归并。
### Reason analyze (If you can)
> 路由到单表本来不需要做sql改写，`3.0.0.M1`这个版本是正确，对比代码如下：
* `3.0.0.M1`
```
 private void processLimit(List<Object> parameters, SelectStatement selectStatement, boolean isSingleRouting) {
        if (isSingleRouting) {
            selectStatement.setLimit((Limit)null);
        } else {
            boolean isNeedFetchAll = (!selectStatement.getGroupByItems().isEmpty() || !selectStatement.getAggregationSelectItems().isEmpty()) && !selectStatement.isSameGroupByAndOrderByItems();
            selectStatement.getLimit().processParameters(parameters, isNeedFetchAll);
        }
    }
```
* `3.1.0`
```
   private void processLimit(final List<Object> parameters, final SelectStatement selectStatement) {
        boolean isNeedFetchAll = (!selectStatement.getGroupByItems().isEmpty() || !selectStatement.getAggregationSelectItems().isEmpty()) && !selectStatement.isSameGroupByAndOrderByItems();
        selectStatement.getLimit().processParameters(parameters, isNeedFetchAll, databaseType);
    }
```

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by ty666** [comment]
same problem
