### ISSUE TITLE
sharding-jdbc can't work in multi thread  concurrent 

### ISSUE THREAD

**Issue by mfeng-ya** [apache/incubator-shardingsphere#1990]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.M1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
multi thread  concurrent  can't work

### Reason analyze (If you can)
InsertStatement(other Statement no validation) is not thread safe, PreparedStatementRoutingEngine#route fetch Statement used cache 
![image](https://user-images.githubusercontent.com/42688346/53943341-d8359200-40f7-11e9-90d9-623ee854a68e.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/42688346/53943248-aa504d80-40f7-11e9-9d4f-106d44987c0d.png)

**Comment by mfeng-ya** [comment]
Which version is stable and usable now?

**Comment by mfeng-ya** [comment]
new question
![image](https://user-images.githubusercontent.com/42688346/53947909-afb29580-4101-11e9-8e73-20552c538e25.png)
org.apache.commons.collections4.map.ReferenceMap is not thread-safe, cache used with it no problem in multi thread concurrent?
![image](https://user-images.githubusercontent.com/42688346/53948327-847c7600-4102-11e9-9030-b5a5b7bfaf38.png)

**Comment by mfeng-ya** [comment]
Could change  field 'parsingResultCache' to #ThreadLocal in #ShardingRule?

**Comment by codefairy08** [comment]
@mfeng-ya  it caused by shared SQLStatement, ParsingResultCache is global cache, it cloud not change to ThreadLocal

**Comment by mfeng-ya** [comment]
@codefairy08 ParsingResultCache  may be could refer to the ConcurrentReferenceHashMap in hibernate-validator's util package 
![image](https://user-images.githubusercontent.com/42688346/54068102-976a8400-4283-11e9-93c5-e7cc3ae67df5.png)

**Comment by codefairy08** [comment]
@mfeng-ya It does not work,  It is not caused by  ParsingResultCache , the  instance in ParsingResultCache  should not be changed.

**Comment by mfeng-ya** [comment]
@codefairy08 I see, however it's a new question

**Comment by ToukitsuLin** [comment]
I have met a problem while using sharing-jdbc version 3.1.0. Thread hang in with high CPU load. Thread call  stack show thread hang in HashMap.getEntry(). So how can i fix this problem beacuse of HashMap is not thread save in ParsingResultCache.

**Comment by yanglifan** [comment]
This should be a VERY BASIC issue which should not happen since everybody know that `HashMap` is NOT THREAD-SAFE.

**Comment by Ah39** [comment]
mark
