### ISSUE TITLE
HintShardingStrategy and StandardShardingStrategy cannot use together?

### ISSUE THREAD

**Issue by wy-coder** [apache/incubator-shardingsphere#1993]
## Question
HintShardingStrategy and StandardShardingStrategy cannot use together?

I have a distributed batch. When reading data, I only read a section of data from a identify database allocated by the global scheduler. At this time, I want to use HintShardingStrategy and use the read data as the list of data to be processed for batch processing. However, after this data is processed, the StandardShardingStrategy should be used when submitting the data.

**Comment by terrymanu** [comment]
No, sharding strategy cannot exist together
