### ISSUE TITLE
Do not support GROUP_CONCAT

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#1996]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support GROUP_CONCAT
### Actual behavior
```
Table 'etl_data.MailSensitiveWord' doesn't exist
```
### Reason analyze (If you can)
antlr parsing error. ```AntlrParsingEngine``` did not extract ```FromWhereSegment```
![image](https://user-images.githubusercontent.com/1615053/53952965-286b1f00-410d-11e9-8da2-eae00b15d150.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. config 2 datasources  
2. config logic table A mapping to table A of one of datasource(not the default one)  
3. select group_concat(wordType) from A group by wordType;  
4. error  

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
duplicate with #1764

**Comment by joooohnli** [comment]
No, it has not been fixed yet. I've checked the newest dev branch, this issue still exists. @terrymanu
