### ISSUE TITLE
Force route is a one time thing,should not be a Hint Strategy which have Algorithm.

### ISSUE THREAD

**Issue by wy-coder** [apache/incubator-shardingsphere#1997]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

We have a shard table Account in 3 databases.

There is a batch to loop the Account table to do a job.

The Account table is so big . so we design a distributed batch running in 10 nodes.

Each node reads a piece of data from a specific database for processing.

A scheduler will assign each node which database to read from, from begin index to end index.

So we need to specify a database when reading data, but we can still write data with ShardingAlgorithm as usual.

### Describe the feature you would like.
make force route a one time thing , use the ShardingAlgorithm but value from hintmanager.

or force route to a specify database .

thanks

**Comment by terrymanu** [comment]
I don't want define one time query for database, sharing-jdbc is jdbc extension and sharding-proxy is database  extension.
Define a new concept need more discuss. 
We prefer don't add new behaviour by default.
For batch job or some business query, the better way is dev this logic to business codes, not at ShardingSphere. We should keep ShardingSphere clear

**Comment by wy-coder** [comment]
That is to say：

All jdbc supports full table **paging** scanning , but sahrding does not.

if do not support force route to a specify database, how to do full table **paging**?

limit 200 300

db1 : limit 0 300
db2 : limit 0 300
db3 : limit 0 300
assemble and sort 0 900

limit 200 300 from 0 900
This is not efficient.

we need:
node1 : db1 : limit 0 100
node2 : db1 : limit 100 200
node3 : db1 : limit 200 300
