### ISSUE TITLE
Full table **no sort paging** scanning

### ISSUE THREAD

**Issue by wy-coder** [apache/incubator-shardingsphere#1998]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

#1997 

### Describe the feature you would like.
That is to say：

All JDBCs support full table **no sort paging** scanning , but sahrding-jdbc does not.

if do not support force route to a specific database, how to do full table **no sort paging**?

limit 200 300

db1 : limit 0 300
db2 : limit 0 300
db3 : limit 0 300
assemble and sort 0 900

limit 200 300 from 0 900
This is not efficient.

we need:
node1 : db1 : limit 0 100
node2 : db1 : limit 100 200
node3 : db1 : limit 200 300

**Comment by terrymanu** [comment]
Closed until somebody interesting about this issue
