### ISSUE TITLE
问一下 database-strategy.complex.sharding-columns设置的字段，字段；查询时是只能包含着两个字断才能查询，不能只使用某一个查询吗

### ISSUE THREAD

**Issue by jiangbin216** [apache/incubator-shardingsphere#2000]
如：使用这两个分片策略的 merchant_id,out_user_id  ；
sql查询时，select * from t_recharge where merchant_id='' and out_order_id=''  
这个查询就直接报空指针了，在mysql库里查询sql是没有问题的

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
