### ISSUE TITLE
how to sharding table by day?eg:order_20190101->20201231

### ISSUE THREAD

**Issue by jinjim** [apache/incubator-shardingsphere#2005]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

i have try to use groovy script like order_${2019..2020}${01..12}${01..31}

**Comment by jinjim** [comment]
is there any way to sharding table by script or in other way?

**Comment by qiankunshe** [comment]
You can look at the documentation, which has a custom sharding implementation

**Comment by qiankunshe** [comment]
https://shardingsphere.apache.org/document/legacy/3.x/document/en/features/sharding/concept/sharding/

**Comment by jinjim** [comment]
> https://shardingsphere.apache.org/document/legacy/3.x/document/en/features/sharding/concept/sharding/ Look at the bottom of this

understand that,but i  it would be better  by RangeShardingAlgorithm

**Comment by terrymanu** [comment]
@jinjim Is it resolve your question？ Can you close this issue？

**Comment by jinjim** [comment]
> @jinjim Is it resolve your question？ Can you close this issue？

However, there is no！
