### ISSUE TITLE
Do not support connectionInitSqls config of druid connection while using datasource orchestration

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#2010]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support     connectionInitSqls
### Actual behavior
do not
### Reason analyze (If you can)
connectionInitSqls config is a collection:

com.alibaba.druid.pool.DruidAbstractDataSource
```
    public Collection<String> getConnectionInitSqls() {...}
```
while uploading, only general types will be serialized, which do not include ```Collection```

io.shardingsphere.core.config.DataSourceConfiguration
```
        GENERAL_CLASS_TYPE = Sets.<Class<?>>newHashSet(boolean.class, Boolean.class, int.class, Integer.class, long.class, Long.class, String.class);
```

**Comment by cherrylzhao** [comment]
@joooohnli how do you config a list value of `connectionInitSqls` with DruidDataSource

**Comment by cherrylzhao** [comment]
is it ok if we support the collection, and separate each item with `,` .

**Comment by cherrylzhao** [comment]
below tasks need to be enhanced.
- [ ]  DataSourceConfiguration `sharding-core`
- [ ] DataSourceUtil `sharding-jdbc-orchestration-spring-boot-starter`
- [ ] DataSourceUtil `sharding-jdbc-spring-boot-starter`

**Comment by pitymonkey** [comment]
@cherrylzhao Sharding-JDBC version 4.0.0-RC2-SNAPSHOT，have the same problem.
see the source code。
`static {
        generalClassType = Sets.<Class<?>>newHashSet(boolean.class, Boolean.class, int.class, Integer.class, long.class, Long.class, String.class);
    }`
This causes the configuration ‘connectionInitSqls’ not to take effect. 
Indirect causes mysql insert emojj error

**Comment by cherrylzhao** [comment]
we have not fixed it yet, you can contribute a PR for it if possible.

**Comment by menghaoranss** [comment]
I will try to fix it, please assign this issue to me.

**Comment by terrymanu** [comment]
@menghaoranss Great

**Comment by kimmking** [comment]
Any thing forward or meet some problem?
