### ISSUE TITLE
Insert value with operator ~

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#2018]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
insert into table_x(userId,switchers) values (10001, ~1);

table_x is a default table.

```
java.lang.NullPointerException: null
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.execute(ShardingStatement.java:163)
```

### Reason analyze (If you can)
sql parsing error

**Comment by terrymanu** [comment]
Support INSERT SQL with expression in values is unnecessary with sharding databases
