### ISSUE TITLE
Support mulit-tenant for sharding-proxy

### ISSUE THREAD

**Issue by windyii** [apache/incubator-shardingsphere#2028]
## Feature Request
Support mulit-tenant for sharding-proxy.

Sharding-proxy only has one user for all schemas. But we want DBA and normal user to access the same sharding-proxy cluster especially for sharding. DBA should be allowed to use DDL but normal user shouldn't.  
It may be done if there are mulit-tenant and user<->schema relations configured.  Set different user in schemas and let MySQL do ACL.
Reference: https://github.com/actiontech/dble

**Comment by terrymanu** [comment]
Mulit-tenant is cloud or PAAS feature, ShardingSphere focus infra now, no plan to do this feature.
Mulit-tenant is additional feature based on ShardingSphere, if some one need it, cloud dev based on it.
