### ISSUE TITLE
batch insert have a bug in version 3.1.0

### ISSUE THREAD

**Issue by ratyzhang** [apache/incubator-shardingsphere#2031]
INSERT INTO t_table_yymmdd (xx, xx,....M) VALUES
(xx,xx,....M),
(xx,xx,....M),
(xx,xx,....M)
....N
当M(字段数)N(记录数)比较大，进行分表操作时，如500*20时，sql执行非常慢，基本上卡死了。根据debug 应该问题出在 sqlRoute 和 sqlParse 这块。请确认。备注：版本为3.1.0

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
