### ISSUE TITLE
if has space in select field will not use sharding rule. 

### ISSUE THREAD

**Issue by trojanliu** [apache/incubator-shardingsphere#2034]
like: 

select a.  id  from table where payDate = 20190101;  
it will not use rule. and get nothing notice.

**Comment by trojanliu** [comment]
i find this bug in 3.0.0 and 3.1.0.    before in 1.5.4 has no this bug.

**Comment by codefairy08** [comment]
@trojanliu thanks for your issue, it caused by wrong parse result
