### ISSUE TITLE
select  limit offset statement has a bug

### ISSUE THREAD

**Issue by ratyzhang** [apache/incubator-shardingsphere#2039]
Example:
   original sql : SELECT col1,col2,col3 FROM tbl_xx_yymmdd limit 1 offset 0;
   but after parse Actual sql is :  SELECT col1,col2,col3 FROM tbl_xx_yymmdd limit 0 offset 1; 
   return empty result.
sharding-jdbc version : 3.1.0

**Comment by terrymanu** [comment]
Duplicate with #1722
