### ISSUE TITLE
limit bug

### ISSUE THREAD

**Issue by 13127898836** [apache/incubator-shardingsphere#2044]
in group io.shardingsphere artifactId sharding-jdbc-core:3.1.0
when i use the single database and single table,the sql contains limit,and the result more than
expect。
Than i use the  group io.shardingjdbce artifactId sharding-jdbc-core:2.0.3 
the result is right.
This version did'nt rewrite the sql.

**Comment by yuancaihua** [comment]
m

**Comment by terrymanu** [comment]
duplicate with #2039
