### ISSUE TITLE
Mave moudle has wrong compile order, sharding-sql-test should be compiled before sharding-core

### ISSUE THREAD

**Issue by tankilo** [apache/incubator-shardingsphere#2045]
## Bug Report

Mave moudle has wrong compile order.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1-SNAPSHOT
### Expected behavior
```
    <modules>
        <module>sharding-sql-test</module>

        <module>sharding-core</module>
        
        <module>sharding-jdbc</module>
        <module>sharding-proxy</module>
        
        <module>sharding-transaction</module>
        <module>sharding-orchestration</module>
        <module>sharding-opentracing</module>
    
        <module>sharding-spring</module>
    </modules>
```
### Actual behavior
sub modules of `sharding-core` rely on module `sharding-sql-test`, compile will fail if you are doing this for the first time.
![image](https://user-images.githubusercontent.com/10413284/54483954-93e48780-4897-11e9-8536-e29212102b7b.png)
```
    <modules>
        <module>sharding-core</module>
        
        <module>sharding-jdbc</module>
        <module>sharding-proxy</module>
        
        <module>sharding-transaction</module>
        <module>sharding-orchestration</module>
        <module>sharding-opentracing</module>
    
        <module>sharding-spring</module>
        <module>sharding-sql-test</module>
    </modules>
```

**Comment by terrymanu** [comment]
Can you explain the reason for close this issue?

**Comment by tankilo** [comment]
> Can you explain the reason for close this issue?

In fact, yesterday night, i did ran into error when i try to compile the code. But this morning, after i post this issue , i can't reproduce this problem again (clean related jars in  local maven repo and compile).
Though `sharding-sql-test` is the last one  in the `<modules>` element of the parent pom.xml, it's still compiled before some modules of `sharding-core`.
```
[INFO] Reactor Build Order:
[INFO] 
[INFO] sharding-sphere
[INFO] sharding-core
[INFO] sharding-core-api
[INFO] sharding-core-common
[INFO] sharding-core-parse
[INFO] sharding-core-parse-spi
[INFO] sharding-sql-test
[INFO] sharding-core-parse-common
[INFO] sharding-core-parse-mysql
[INFO] sharding-core-parse-postgresql
[INFO] sharding-core-parse-oracle
[INFO] sharding-core-parse-sqlserver
```

Before, i think module building order is just the same as what we define in <modules> element of the parent pom.xml. 
And after Googling, maven is smarter than I thought.
https://stackoverflow.com/questions/18629897/maven-build-order-multiple-modules
http://maven.apache.org/guides/mini/guide-multiple-modules.html

> Reactor Sorting
>Because modules within a multi-module build can depend on each other, it is important that the reactor sorts all the projects in a way that guarantees any project is built before it is required.
>
> The following relationships are honoured when sorting projects:
>
> a project dependency on another module in the build
a plugin declaration where the plugin is another module in the build
a plugin dependency on another module in the build
a build extension declaration on another module in the build
the order declared in the <modules> element (if no other rule applies)
