### ISSUE TITLE
mysql parse can not parse cast function

### ISSUE THREAD

**Issue by avalon566** [apache/incubator-shardingsphere#2047]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Execute this SQL routing correctly
select cast(order_id as varchar) from t_order
### Actual behavior
routing to random datasource
### Reason analyze (If you can)
anltr mysql not support cast function
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
select cast(order_id as varchar) from t_order

**Comment by codefairy08** [comment]
cast function Syntax is different with other general function, it was fixed
