### ISSUE TITLE
Should  add a method in HintManager to hint only use default datasource and none SQL rewrite

### ISSUE THREAD

**Issue by mfeng-ya** [apache/incubator-shardingsphere#2050]
complex sql  parsing always error, but it not need sharding

**Comment by terrymanu** [comment]
Skip complex SQL parsing is not good way to solve the issue, the better solution is make complex SQL parsing accurate. 
So we prefer make great efforts on SQL parsing, but not skip them on some special situation.

**Comment by mfeng-ya** [comment]
@terrymanu You're right，however it's also good to provide another way for users to choose for themselves.

**Comment by mfeng-ya** [comment]
and might perform better

**Comment by terrymanu** [comment]
Provide another way may out of scope of sharding sphere. 
For example, use 2 datasource, one with sharding sphere, other one without sharding sphere.

**Comment by mfeng-ya** [comment]
Users must be aware of the impact , only take effect with sharding sphere datasource

**Comment by terrymanu** [comment]
If user want use sharding sphere as not transparent model (eg. know they are using default data source), that is not sharding sphere's expected usage

**Comment by joooohnli** [comment]
@terrymanu 
> Skip complex SQL parsing is not good way to solve the issue, the better solution is make complex SQL parsing accurate.
So we prefer make great efforts on SQL parsing, but not skip them on some special situation.

I've reported some issues related to this topic, and you just marked them **won't fix**. So could you please let us know what your plan is. Current version has so many problems to parse single node sql correctly.

**Comment by terrymanu** [comment]
The plan is do better for SQL parse.
We cannot afford all SQL parsed, why not join community to contribute codes? It is better than just waiting.

**Comment by joooohnli** [comment]
#2017 #2018 #2059 sqls in these issues are all single node routing and supposed to be sent to physical datasource to be executed, but actually failed because of wrong sql parsing.

How about changing back to Druid SQL parsing, which could make sure SQL compatibility as much as possible. @terrymanu

**Comment by mfeng-ya** [comment]
@joooohnli You can try to switch data sources on your own.

**Comment by terrymanu** [comment]
Can I close this issue?
