### ISSUE TITLE
2个数据源事务无法回滚

### ISSUE THREAD

**Issue by zhouxianrongtest** [apache/incubator-shardingsphere#2051]
1：程序连了A和B两个数据库，A数据源声明为@Primary
2：测试A库一个单表的多条写入时，当代码发生异常，数据库事务回滚
3：测试B库时，事务无法回滚，比如我insert 4条记录，当insert完第2条后throw Exception，这时数据库表已经写入了前面2个记录
4：期望是B库的写入2条记录被回滚

sharding 依赖
<sharding.jdbc.core.version>1.5.4.1</sharding.jdbc.core.version>
<sharding.jdbc.transaction.storage.version>1.5.4.1</sharding.jdbc.transaction.storage.version>
<sharding.jdbc.config.spring.version>1.5.4.1</sharding.jdbc.config.spring.version>

**Comment by zhouxianrongtest** [comment]
问题类似: https://github.com/apache/incubator-shardingsphere/issues/213

**Comment by zhouxianrongtest** [comment]
问题类似:https://github.com/apache/incubator-shardingsphere/issues/213

但是如果我把B数据源声明为@primary，那么测试B库的事务回滚就没有问题

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
