### ISSUE TITLE
Do not support sum(if()) expression

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#2055]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support
### Actual behavior
do not
### Reason analyze (If you can)
sql parsing error
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. ```select sum(if(status=0, 1, 0)) from xx group by xx;```
2. Table 'xx.xx' doesn't exist
### Example codes for reproduce this issue (such as a github link).

**Comment by codefairy08** [comment]
IF is a keyword,  When the function nested function . the inner functionname is the keyword， it failed parsing
