### ISSUE TITLE
Wrong LIMIT rewrite while using nested SELECT

### ISSUE THREAD

**Issue by joooohnli** [apache/incubator-shardingsphere#2059]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
![image](https://user-images.githubusercontent.com/1615053/54603877-69095780-4a80-11e9-85a9-24f29911a385.png)

### Reason analyze (If you can)

io.shardingsphere.core.parsing.parser.context.limit.Limit#rewrite
![image](https://user-images.githubusercontent.com/1615053/54603960-90602480-4a80-11e9-9400-fad3c56d8281.png)

io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter#processLimit
![image](https://user-images.githubusercontent.com/1615053/54604030-c00f2c80-4a80-11e9-90cd-e4b5f57317b8.png)

I guess it is related to the wrong sql parsing.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Run it with PreparedStatement:
```
SELECT MIN(momentID) FROM (SELECT momentID FROM LatestMoment WHERE momentID < ? ORDER BY momentID DESC LIMIT ?)
```

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
Do not support subquery if not on single sharding data node.
Please note, we want focus SQL more make sense for sharding databases, not for all SQL
