### ISSUE TITLE
automCommit not support

### ISSUE THREAD

**Issue by tonnixu** [apache/incubator-shardingsphere#2060]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
```
Exception in thread "main" Cannot create property=dataSources for JavaBean=io.shardingsphere.shardingproxy.config.yaml.YamlProxyRuleConfiguration@14899482
 in 'reader', line 11, column 1:
    schemaName: ds_1
    ^
Cannot create property=autoCommit for JavaBean=io.shardingsphere.core.rule.DataSourceParameter@11028347
 in 'reader', line 15, column 5:
        url: jdbc:mysql://127.0.0.1:3306 ...
        ^
Unable to find property 'autoCommit' on class: io.shardingsphere.core.rule.DataSourceParameter
 in 'reader', line 18, column 17:
        autoCommit: true
                    ^

 in 'reader', line 14, column 3:
      ds_0:
      ^
```

**Comment by tonnixu** [comment]
`dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: Root@123
    autoCommit: true
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    minPoolSize: 10
    maxPoolSize: 10
`

**Comment by terrymanu** [comment]
`autoCommit` is not a valid configuration item of Sharding-Proxy.
FYI: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/

**Comment by tonnixu** [comment]
3.1.0  why not support autoCommit property?

**Comment by terrymanu** [comment]
Configuration item is defined by Sharding-Proxy.

autoCommit is connection or JDBC URL's property, they are different
