### ISSUE TITLE
Why shardingspere need to load all meta data?

### ISSUE THREAD

**Issue by songxu** [apache/incubator-shardingsphere#2063]
## Version
io.shardingsphere.sharding-jdbc-spring-boot-starter:3.0.0

During the initializing, shardingspere will load all table meta in TableMetaDataInitializer.

TableMetaDataInitializer.load(final ShardingRule shardingRule) {
...
     result.putAll(loadDefaultTables(shardingRule));
}

It takes much time(almost 2 minutes) to load all meta data.

## Question
Why shardingspere need to load all meta data? If I don't load them, what will happen?

Thanks a lot.

**Comment by tristaZero** [comment]
@songxu 
Hi,  your issue is duplicate with [#1951](https://github.com/apache/incubator-shardingsphere/issues/1951).
Are you interested in this one? If available, maybe you can fix this problem and give us a pr.

**Comment by songxu** [comment]
> @songxu
> Hi, your issue is duplicate with [#1951](https://github.com/apache/incubator-shardingsphere/issues/1951).
> Are you interested in this one? If available, maybe you can fix this problem and give us a pr.

Thanks for you reply.
If the meta data isn't loaded at the initializing time, is there any impact?

**Comment by tristaZero** [comment]
@songxu Hi, recently i am fixing this problem, and this issue occurrs to me. ShardingSphere needs a copy of metadata info to help parsing your SQLs, and checks the metadata consistancy of all the sharding tables. But there is a switch named `check.table.metadata.enabled` to decide to check it or not. If you don't want to cost too much time when startup, you can config this property. More details, please refer to our document. Thanks.
