### ISSUE TITLE
全库所有表如何统一配置分表

### ISSUE THREAD

**Issue by abbbud** [apache/incubator-shardingsphere#2064]
<sharding:table-rule logic-table="t_order" actual-data-nodes="demo_ds_${0..1}.t_order_${0..1}" database-strategy-ref="databaseStrategy" table-strategy-ref="orderTableStrategy" key-generator-ref="orderKeyGenerator" />

hello，logic-table里是否有通配符的配置方式， 表示所有表都采用相同的分库分表策略。

 我的意思是我一个库里有几百张表，而且后面还要增加， 我可不想对每张表配置一条table-rule。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
