### ISSUE TITLE
HOW to set the same tableRule config FOR all tables OR tables group?

### ISSUE THREAD

**Issue by abbbud** [apache/incubator-shardingsphere#2065]
Hello,HOW to set the same tableRule config FOR all tables OR tables group?

I mean，can i set ‘*’ or ‘$’ in logic-table. (<sharding:table-rule logic-table="t_order" database-strategy-ref="databaseStrategy" key-generator-ref="orderKeyGenerator" />)

It cost me a hour to type the question  in EN. so  Look forward to the reply.

**Comment by terrymanu** [comment]
Just take a look at default strategy

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
