### ISSUE TITLE
why it throw SQLParsingException when i execut a sql like 'CREATE TABLE IF NOT EXIST a1 LIKE a'

### ISSUE THREAD

**Issue by lemondwm** [apache/incubator-shardingsphere#2066]
why it throw SQLParsingException when i execute a sql like 'CREATE TABLE IF NOT EXISTS a1 LIKE a',
i executed it on mysql is correct,sharding-jdbc version is 3.0.0.M3

**Comment by terrymanu** [comment]
Is it really necessary in sharding databases? `a1` and `a` is sharding table or non-sharding table, and how shardingsphere can find them?
It need to comb all passable  scenario, if you need this requirement, please try to comb all scenario first.

**Comment by terrymanu** [comment]
If close issue by yourself without any reason, let me set label as invalid
