### ISSUE TITLE
the link in CONTRIBUTING.md can not access

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2072]
The link in CONTRIBUTING.md can not access.
[Core developers list](https://github.com/apache/incubator-shardingsphere/blob/dev/en/organization)     
and 
[Development conventions](https://github.com/apache/incubator-shardingsphere/blob/dev/en/contribute/convention)
can not access,please check!

**Comment by terrymanu** [comment]
Thank you
