### ISSUE TITLE
EncryptDatasource does not support sql which is not DML

### ISSUE THREAD

**Issue by codefairy08** [apache/incubator-shardingsphere#2081]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
execute sql which is not DML
### Actual behavior
throw Exception, Message is "Unsupported SQL of ${SQL}"
### Reason analyze (If you can)
current just fill DML statement to  DMLStatement, the other sql does not fill，design a new class for the sql which is not DML. do not execute filler logic.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
use EncryptDatasource execute a DDL statement: "CREATE TABLE t_test (id int primary key auto_increment, pwd varchar(100), pwd_assist varchar(100));"

**Comment by tristaZero** [comment]
Testing for this issue has been done. Everything is ok.
