### ISSUE TITLE
关于3.0.0 版本spring 命名空间sharding.xsd问题

### ISSUE THREAD

**Issue by jingjian-1420** [apache/incubator-shardingsphere#2089]
官网给出的spring 命名空间配置为：
http://shardingsphere.apache.org/schema/shardingsphere/sharding 
http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd
但是 
http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd 里面的地址没改啊 老兄
![image](https://user-images.githubusercontent.com/34017711/54922807-e67f0d00-4f43-11e9-8d29-4d5f5443d4be.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
