### ISSUE TITLE
Update sharding key is allowed but not work

### ISSUE THREAD

**Issue by windyii** [apache/incubator-shardingsphere#2092]
## Bug Report
Update sharding key is allowed in Sharding-Proxy. The new value may not be routed to the same backend as the old one. So this kind sql should not be allowed.

### Which version of ShardingSphere did you use?
ShardingSphere 4.0.0RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
Sharding table test1 by column ‘k’ % 2
1. insert into test1(k, c) values ( 1,  'a');
2. select * from test1 where k=1;
  1 rows in set
3. update test1 set k=2 where k=1;
4. select * from test1 where k=2;
  1 rows in set

### Actual behavior
4. select * from test1 where k=2;
  Empty set

### Reason analyze (If you can)
Update sharding key should keep the route as old key but ShardingProxy doesn't check it. Just disallow that kind sql should be ok.

**Comment by betterjava** [comment]
@terrymanu if user use shardingsphere to update shard key,shoul throw a UnsupportedOperationException?

**Comment by betterjava** [comment]
I think we should check all the config not just for update shard key. So I closed the my previous pull. @terrymanu Is my understanding correct?

**Comment by betterjava** [comment]
> More discuss we can do on that pull request

@terrymanu ,what can I do for this issue? can you give me some suggestions?

**Comment by terrymanu** [comment]
@betterjava Welcome to discuss this issue.

For this issue, we should judge the SQL is update sharding key or not, if sharding key updated, should throw an exception.
We'd better add judge logic on `optimized` module, the class should be in `ShardingUpdateOptimizeEngine`

**Comment by betterjava** [comment]
Ok,I got it.I will try do that.

**Comment by betterjava** [comment]
Need I consider more than one table being updated  in one UpdateStatement? I see when Encrypt value for  UpdateStatement,others does not consider this situation. Can you give me some suggestions？
