### ISSUE TITLE
使用问题求教？找不到组织

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#2095]
## Question

**For English only**, other languages will not accept.
Can authentication be specified for schemaName in the configuration file server.xml? When I have multiple databases, it is not appropriate to use the same password. For questions like this, where should I go to find the answer? Is there any contact information like organization or QQ group
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
