### ISSUE TITLE
`java.io.NotSerializableException` occurred when setting parameters into PreparedStatement

### ISSUE THREAD

**Issue by mydingwei** [apache/incubator-shardingsphere#2105]
+ table_demo (id int primary key, column_a int, column_b longtext)

+ mybatis dynamic sql like this: 
```
insert into table_demo (id, column_a, column_b) values ((#{id,jdbcType=VARCHAR}, #{columnA,jdbcType=INTEGER}, #{columnB,jdbcType=LONGVARCHAR})
```

If jdbcType of columnB is specified as `org.apache.ibatis.type.JdbcType.LONGVARCHAR`, this parameter will be handled in `SimpleExecutor.preparedStatement(..)` method, and then `org.apache.ibatis.type.ClobTypeHandler.setNonNullParameter(..)` method will be called. 

Type of column_b will be packaged in StringReader, thus the `parameters` property's type in ShardingPreparedStatement will be set to StringReader. 

Subsequently, `replaySetParameter(final PreparedStatement preparedStatement, final List<Object> parameters)` will be called in `ShardingPreparedStatement's route()` method. 

When the code goes to `each.invoke(preparedStatement);`, `com.mysql.jdbc.PreparedStatement.setObject(int parameterIndex, Object parameterObj)` will be invoked, and `StringReader` cannot be identified by `PreparedStatement`, then `setSerializableObject` will be called, but `StringReader` doesnot implement `Serializable`, so `java.io.NotSerializableException` occur.

**Comment by mydingwei** [comment]
version is 3.0.0.M1

**Comment by tuohai666** [comment]
Thanks for your report, will be fixed in 4.0.0.

**Comment by tuohai666** [comment]
Duplicate with #1567.
Will be fixed together.

**Comment by tuohai666** [comment]
Fixed via https://github.com/apache/incubator-shardingsphere/pull/2388.
