### ISSUE TITLE
sharding_proxy : lack of config file for config_sharding_masterslave.yaml  缺少数据分片+读写分离的配置模板

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-shardingsphere#2108]
sharding_proxy的conf文件中，缺少 数据分片+读写分离的配置模板，单独的读写分离模板和分片模板是可以用的，
但是按照网站上的配置数据分片+读写分离模板经常报错，能否提供 数据分片+读写分离的配置模板的yaml模板？

it is difficult for me to write config file for config_sharding_masterslave.yaml 。 can sharding_proxy suppply template file of config_sharding_masterslave.yaml ?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
