### ISSUE TITLE
how to use shardingsphere multiple databases store different tables sharding?

### ISSUE THREAD

**Issue by joey168** [apache/incubator-shardingsphere#2110]
I use shardingsphere to split a large table into multiple database stores
And store the data in different tables in each database according to the time. 
like. 
ds-0.{table1,table2},   table1 store 2018-01 data table store 2018-02 data
ds-1.{table3,table4},   table3 store 2018-03 data table store 2018-04 data
ds-2.{table5,table6}   ...............
ds-.....
use rangeAlgorithm for create_date filed to sharding
when query conditions span multiple databases throws exection SQLSyntaxErrorException: Table table3 doesn't exist
like. create_date between '2018-01-01' and '2018-04-31'

how to store different sharding tables in multiple databases？

shardingsphere version: 3.0.0.M3

**Comment by wgy8283335** [comment]
Did you configure algorithm of tableStrategy and algorithm of databaseStrategy correctly?
In my opinion, 
2018-01 and 2018-02 should equal to 0 in the algorithm of databaseStrategy.
2018-03 and 2018-04 should equal to 1 in the algorithm of databaseStrategy.
2018-01 should equal to 1 in the algorithm of tableStrategy.
2018-02 should equal to 2 in the algorithm of tableStrategy.
As you see, you should configure two algorithm with different algorithm expression.

**Comment by wgy8283335** [comment]
@joey168

**Comment by joey168** [comment]
@wgy8283335 thanks for answers
But my database and tables are dynamically generated, so I can't write multiple fixed algorithms.

**Comment by joey168** [comment]
@wgy8283335 
But you reminded me of a good idea. I'm trying to use another solution to solve this problem. Thank you.

**Comment by wgy8283335** [comment]
UR welcome.

**Comment by wgy8283335** [comment]
@joey168, could u close the issue?

**Comment by terrymanu** [comment]
Close because no reply by creator.

**Comment by Spacebody** [comment]
@joey168 Hi, I have two database with 4 tables in each,
db_00{tbl0, tbl1, xtb0, xtb1}, 
db_01{tbl2, tbl3, xtb2, xtb3}

So how should I configure the properties and the sharding algorithm? Which sharding alogirthm should I implement?
