### ISSUE TITLE
Where can I find detailed documentation on shardingsphere configuration

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#2114]
## Question

**For English only**, other languages will not accept.
Can authentication be specified for schemaName in the configuration file server.xml? When I have multiple databases, it is not appropriate to use the same password. For questions like this, where should I go to find the answer? Is there any contact information like organization or QQ group
Before asking a question, make sure you have:
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/

**Comment by lklkxcxc** [comment]
@terrymanu How does sharding proxy use different usernames and passwords for different databases？

**Comment by wgy8283335** [comment]
@lklkxcxc ，you could find the answer in incubator-shardingsphere-example.
https://github.com/apache/incubator-shardingsphere-example.
take a look at application-sharding.properties document of the example
as below


sharding.jdbc.datasource.ds_0.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds_0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_0.url=jdbc:mysql://10.8.29.93:30306/demo_ds_0
sharding.jdbc.datasource.ds_0.username=root
sharding.jdbc.datasource.ds_0.password=root

sharding.jdbc.datasource.ds_1.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds_1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_1.url=jdbc:mysql://10.8.29.93:30306/demo_ds_1
sharding.jdbc.datasource.ds_1.username=root
sharding.jdbc.datasource.ds_1.password=root

**Comment by terrymanu** [comment]
Can you close issue if your question is resolved?

**Comment by lklkxcxc** [comment]
@wgy8283335 you answer is use shareding-sphere connect backend mysql config not client username and passwd config

**Comment by wgy8283335** [comment]
Excuse me , I do not understand your comment.But, I think these example maybe helpful.https://github.com/apache/incubator-shardingsphere-examplehttps://github.com/apache/incubator-shardingsphere-example
