### ISSUE TITLE
PredicateExtractor not support String Expression

### ISSUE THREAD

**Issue by kofkyobsa** [apache/incubator-shardingsphere#2123]
sharding jdbc & proxy 
version:3.1.0
when i use sql like 
" select snapshot_no from pt_item_base_snapshot where snapshot_no ='20190304152137155168409726302111' "
sharding-sphere can't get the value of column snapshot_no correctly
, it's always be -1;
I debug the source code ,in the class **PredicateExtractor** ,the method **buildExpression**
only support number:
 ` Optional<ParserRuleContext> bitExprNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.BIT_EXPR);
            expressionNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.NUMBER);
            if (expressionNode.isPresent() && (!bitExprNode.isPresent() || 1 == bitExprNode.get().getChildCount())) {
                commonExpressionSegment.setValue(NumberUtil.getExactlyNumber(expressionNode.get().getText(), 10));
            }`

if I change code like '  expressionNode = ExtractorUtils.findFirstChildNode(valueNode, RuleName.STRING);' , the sql going well !

**Comment by codefairy08** [comment]
duplicate #1754
