### ISSUE TITLE
not support count if,  database will be the default , not the true

### ISSUE THREAD

**Issue by trojanliu** [apache/incubator-shardingsphere#2125]
i has two databases; like 'comon' and 'user'; 
'comon' as the default database;
table 'tx_user' is in 'user' database.

SELECT count(IF(sex = 1 , TRUE , NULL)) AS maleCount FROM tx_user;
can be explain to comon.tx_user;

**Comment by codefairy08** [comment]
@trojanliu thanks for you issue,  is 'user' database  for sharding ?  please show your sharding rule.

**Comment by trojanliu** [comment]
`	<sharding:data-source id="myDataSource">
		<sharding:sharding-rule data-source-names="common,user"
								default-data-source-name="common"
								default-database-strategy-ref="noneStrategy"
								default-table-strategy-ref="noneStrategy">
			<sharding:table-rules>
				<sharding:table-rule logic-table="tx_user" actual-data-nodes="user.tx_user" generate-key-column-name="uid"/>
			</sharding:table-rules>
		</sharding:sharding-rule>
		<sharding:props>
			<prop key="sql.show">${hibernate.show_sql}</prop>
			<prop key="executor.size">2</prop>
		</sharding:props>
	</sharding:data-source>`

**Comment by trojanliu** [comment]
<sharding:table-rule logic-table="tx_user" actual-data-nodes="user.tx_user" generate-key-column-name="uid"/>

**Comment by trojanliu** [comment]
`tx_user ` is a single table. no databases rule , no tables rule .

**Comment by codefairy08** [comment]
@trojanliu  which shardingsphere version do you use? have a try using dev branch code , i use    [sharding-spring-namespace-mybatis-example](https://github.com/apache/incubator-shardingsphere-example) , shardingsphere code is the lastest, result of routing is correct.See the following figures for the results.
![image](https://user-images.githubusercontent.com/39583929/55311746-50446d00-5496-11e9-9548-2f5cadad73d0.png)
![image](https://user-images.githubusercontent.com/39583929/55311830-8a157380-5496-11e9-9b8a-3d557557bbb9.png)
![image](https://user-images.githubusercontent.com/39583929/55311850-98fc2600-5496-11e9-944e-a89cb6d58716.png)

**Comment by trojanliu** [comment]
i use 3.1.0.  dev branch code is ok? i try it later .

**Comment by codefairy08** [comment]
use  this version 4.0.0-RC1-SNAPSHOT, compile it by yourself using source code,,just mvn clean install in root dir of project

**Comment by trojanliu** [comment]
i change the position, data-source-names="user,common".  
it change to user. tx_user.

another problem `default-data-source-name` has not effect.

**Comment by trojanliu** [comment]
![image](https://user-images.githubusercontent.com/8016811/55699691-92256400-59fe-11e9-9560-43a275d29a20.png)
![image](https://user-images.githubusercontent.com/8016811/55699767-f6e0be80-59fe-11e9-833b-6303688c4d56.png)

IN VERSION 3.1.0 

if sql is 'SELECT count(IF(sex = 1 , TRUE , NULL)) AS maleCount FROM tx_user;'

it will parsing ends up before `if`.  
AND tablename is not parsing, so it use the default database;
