### ISSUE TITLE
SQLLogger should have a junit test

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2126]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
SQLLogger should have a junit test.

**Comment by betterjava** [comment]
I am working on it.

**Comment by terrymanu** [comment]
I add some code review comments on your pr
