### ISSUE TITLE
ResultSetMetaData for Encrypt ResultSet

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#2132]
When users use encrypt data source to get encrypt resultset, we need to consider the resultset metadata. Especially,  when users use `ShardingQueryAssistedEncryptor`, how about the assistedQueryColumn in resultset metadata? 

assistedQueryColumn shoule be **invisible** for users.

**Comment by zhouchangjiang** [comment]
hello @tristaZero , @terrymanu 

I have a question about this issues.
When the following SQL statement is executed
```
select *  from mytable_with_assistedQueryColumn;
select assistedQueryColumn from mytable_with_assistedQueryColumn;
```
assistedQueryColumn  can be returned  normally;

In this case,why assistedQueryColumn  need to be invisible to users?

**Comment by tristaZero** [comment]
@zhouchangjiang  You're right, we need to overwrite interface of resultSetMetaData to hide assistedQueryColumn.

**Comment by tristaZero** [comment]
This issue has been done, please see [#2934](https://github.com/apache/incubator-shardingsphere/pull/2934).
