### ISSUE TITLE
sharding-proxy customer database or table strategy config

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2133]
Is there any way config my own custom database or table strategy in sharding-proxy?   Maybe support this  in the recently version?  After all ,I think this will be needed for most users.

**Comment by wgy8283335** [comment]
Hello, my friend. Sharding-Proxy already provide custom strategy.
U could find some examples at link : https://github.com/apache/incubator-shardingsphere-example
For example,shardingColumn and algorithmExpression could be configured in yaml file.
"shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGeneratorColumnName: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item_${order_id % 2}
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds_${user_id % 2}
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator"

**Comment by wgy8283335** [comment]
@osbornjonny

**Comment by DongJigong** [comment]
@wgy8283335 It seems custom strategy config using Class short name,is that right? E.g my Class called 'MyHintShardingStrategy' ,I shall use myHint in my yaml file?

**Comment by wgy8283335** [comment]
@DongJigong 
In sharding-proxy source code,you could find YamlShardingStrategyConfiguration. There are five kinds of Strategy.If you wanna use custom strategy, you could choose standard or complex. And set **AlgorithmClassName to your custom Algorithm.
org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingStrategyConfiguration
@Getter
@Setter
public class YamlShardingStrategyConfiguration implements YamlConfiguration {
    
    private YamlStandardShardingStrategyConfiguration standard;
    
    private YamlComplexShardingStrategyConfiguration complex;
    
    private YamlHintShardingStrategyConfiguration hint;
    
    private YamlInlineShardingStrategyConfiguration inline;
    
    private YamlNoneShardingStrategyConfiguration none;
}
@Getter
@Setter
public final class YamlStandardShardingStrategyConfiguration implements YamlBaseShardingStrategyConfiguration {
    
    private String shardingColumn;
    
    private String preciseAlgorithmClassName;
    
    private String rangeAlgorithmClassName;
}

**Comment by wgy8283335** [comment]
@DongJigong 
Another way, u could reference to ShardingRule. In 1.5.4.1 version use ShardingRule builder could configure strategy. But I am not sure whether it work at your version.

**Comment by DongJigong** [comment]
@wgy8283335 Many thanks! It's very helpful. I already understood.
