### ISSUE TITLE
When will version 4.0 start?

### ISSUE THREAD

**Issue by gaodesen163** [apache/incubator-shardingsphere#2135]
When will version 4.0 start?

**Comment by gaodesen163** [comment]
When will version 4.0 start?

**Comment by terrymanu** [comment]
FIY: https://lists.apache.org/thread.html/ebdd59188ceee264d6f64823becf9a4ee0ae92ccf85eb30f09f02b17@%3Cdev.shardingsphere.apache.org%3E
