### ISSUE TITLE
shareding-sphere don't supoort SQL that with "-" database name

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#2140]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
select * from `abc-d.95_abc_table`

### Actual behavior
report error：
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-d.`95_abc_table`' at line 1

but in shell commond is correct

**Comment by terrymanu** [comment]
SQL that contains schema is unavailable, for the concept of ShardingSphere is to use multiple data source as one data source, so all the SQL visits are based on one logic schema.
FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/
