### ISSUE TITLE
OpenTracingSQLExecutionHook.toStringList NullPointerException

### ISSUE THREAD

**Issue by zhanghj-java** [apache/incubator-shardingsphere#2142]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.0.1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
sharding-opentracing log trace without effect main execute
### Actual behavior
log trace throw NullPointerException effect sql execute
### Reason analyze (If you can)
OpenTracingSQLExecutionHook.toStringList method, when params has null, such as insert, call guava Joiner.toString throw NullPointerException 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
As above
### Example codes for reproduce this issue (such as a github link).
As above

**Comment by zhanghj-java** [comment]
sorry ，version is 3.1.0

**Comment by tuohai666** [comment]
I think you find the root cause. Would you like to submit a pull request?

**Comment by tuohai666** [comment]
This problem wasn't completely resolved. This pr treated two cases:
`null == parameterSets`
and
`parameterSets.isEmpty()`

What if null value in parameterSets? Like:
`insert into t_order (order_id, user_id, status) values (?, ?, ?)`
With parameters:
`(1, 1, null)`
This will also fired a NullPointerException.
