### ISSUE TITLE
how to pass mapping logic into sharding-algorithm?

### ISSUE THREAD

**Issue by qinnnyul** [apache/incubator-shardingsphere#2148]
## we would like to do table sharding by tenant id,  however, it is not good to split data by hash mod, it will be nicer if we can use the following mapping logic, e.g: {tenant1, tenant99, tenant101} ->  table_00, {other_tenant} -> table_01. 

But we can not find a way to pass around this kind of mapping logic into XXShardingAlgorithm, as it only accept two parameters: 

```
 /**
     * Sharding.
     * 
     * @param availableTargetNames available data sources or tables's names
     * @param shardingValue sharding value
     * @return sharding result for data source or table's name
     */
```

please advise what we can do to achieve this goal? thx

**Comment by terrymanu** [comment]
All examples in here:
https://github.com/sharding-sphere/sharding-sphere-example

**Comment by qinnnyul** [comment]
@terrymanu thanks for your reply, but I can not find any examples related to our requirement, please point out which one is relevant sample?  thx

**Comment by wgy8283335** [comment]
@qinnnyul .Hello,my friend.U quit the group of wechat so quickly, as u did not tell which issue number is your concern. Finally, I find your issue. In version 1.5.4.1 ,link :https://github.com/apache/incubator-shardingsphere/tree/1.5.4.1.  com.dangdang.ddframe.rdb.sharding.example.jdbc.algorithm.ModuloTableShardingAlgorithm. It is the example of custom algorithm.U can program your algorithm in java, so as to meet your needs.

**Comment by qinnnyul** [comment]
@wgy8283335 thanks mate, however, it is a way to "hard coded" your mapping logic in java class, which is NOT friendly to users, what we want is making it configurable, and monitored by etc/zk as well, as sharding logic will be changed in future and also needs to be disturbed dynamically.

**Comment by wgy8283335** [comment]
Another way is configuring algorithm  with inline expression in yaml file. As the expression is totally surpported by Groovy.Reference to the link:https://shardingsphere.apache.org/document/legacy/3.x/document/cn/features/sharding/other-features/inline-expression/.

**Comment by qinnnyul** [comment]
@wgy8283335 yep, actually that is the very first solution which I tried, you know, nobody likes writing their own sharding algorithm if inline expression is suitable to this case:)

So what I did today was writing customised spring configuration to capture tenant related mapping logic, then pass it along to XXShardingAlgorithm, it works, but it seems like this kind of configuration will not be `watched` or `monitored` by etcd/zk or `mysql, which is a new register center, we extended from  sharding-orchestration-reg-api`

e.g:
```
XX.sharding.tenant-id.tables.t_order.1=_0
XX.sharding.tenant-id.tables.t_order.4=_0
XX.sharding.tenant-id.tables.t_order.5=_0
XX.sharding.tenant-id.tables.t_order.7=_0
XX.sharding.tenant-id.tables.t_order.other=_1

XX.sharding.tenant-id.tables.t_order_item.1=_0
XX.sharding.tenant-id.tables.t_order_item.4=_0
XX.sharding.tenant-id.tables.t_order_item.5=_0
XX.sharding.tenant-id.tables.t_order_item.7=_0
XX.sharding.tenant-id.tables.t_order_item.other=_1
```
what do you recommend?  thx

**Comment by wgy8283335** [comment]
@terrymanu . Do u have any suggestion?

**Comment by terrymanu** [comment]
Closed caused by creator do not reply anymore.

**Comment by qinnnyul** [comment]
what?
