### ISSUE TITLE
How about support HintShardingStrategy with other ShardingStrategy at same time?

### ISSUE THREAD

**Issue by neil4dong** [apache/incubator-shardingsphere#2149]
### Is your feature request related to a problem?
I was upgrading from version 1.5.x which is support hint with other shardingStrategy.
I find out that I can not only update/modify sharding-jdbc related code in my project to migrate to version 3.1.0 .

example:
Given a table **order** with columns: **order_id,name,user_id** sharding-column is user_id.
In  UserOrderList module, I need to find all the orders belongs to this user, so we pass user_id to SQL, which is correct.
But In another module ,outer system request for a Order's detail, and they only have order_id, order_id can infer a sharding value, In this case if hint supported will be very helpful.

### Describe the feature you would like.
How about support HintShardingStrategy with other ShardingStrategy at same time?
make HintShardingStrategy has higher priority than other ShardingStrategy?

**Comment by terrymanu** [comment]
duplicated with #1993

**Comment by neil4dong** [comment]
You just close issues，No Discussion
Waste of my time

**Comment by terrymanu** [comment]
I am sorry to wasting your time.
For ShardingSphere, some features are unnecessary, we need make the kernel-concept lightweight and clear. 
I just labeled the issue as duplicated, if you want to discuss, you can discuss from original issues, it is easy to search friendly.

**Comment by terrymanu** [comment]
@neil4dong We are Interested withOpen-source, but we do not have any responsibility to accept your blame or abuse.
If nobody teach you polite and respect each other, maybe someone can tell you how to discuss like a community style, please learn how to communication first.
For technical discuss we always welcome, for other discuss, I hope never see again.

**Comment by neil4dong** [comment]
@terrymanu 
Sorry for what I was saying. 

But still this issue is not duplicated.   Another issue is asking yes or no , but it is obvious no ,and I was making a proposal.

Quoting"we need make the kernel-concept lightweight and clear." will be fine .  No mater whether I think of this idea is right or not , but that will be work for me . 

Finally,  I use ComplexityShardingStrategy to make my legacy code work(not a good idea but work).
Anyway this project helps me a lot ,Thanks.

**Comment by terrymanu** [comment]
How to storage data in database in static structure, the sharding strategy is mapping of data storage.
Have more than one sharding strategies will make enduser confused.
