### ISSUE TITLE
hikari datasource connection-test-query become useless

### ISSUE THREAD

**Issue by wy-coder** [apache/incubator-shardingsphere#2154]
## Question

ShardingSphere-SQL - Logic SQL: /* ping */ SELECT 1

hikari datasource connection-test-query become useless , becouse of UnicastRoutingEngine.

**Comment by KomachiSion** [comment]
@wy-coder, The SQL `SELECT 1` should not be from hikariCP but from your application, such as `spring-boot-actuator`, detail see #2344 .
The `hikari datasource connection-test-query` will not print SQL Log by `ShardingSphere-SQL`.

Information you provided is not enough to reproduce this problem, so can you provide more information such as harding-sphere versions, sharding configurations and so on.
If you can provide a example code in GitHub will be better

**Comment by KomachiSion** [comment]
The process of execute sql is 
`Application --> ShardingDataSource(parse, route) --> printSQL if sql.show = true --> Hikari connection pool.`

So the SQL`connection-test-query` set should not be print by ShardingSphere.
the reason why your log print `ShardingSphere-SQL - Logic SQL: /* ping */ SELECT 1` may be something in your application invoke ShardingSphere to execute check/test SQL, such as `spring-boot-actuator`(detail see #2344 ).

So I think it's not a problem for ShardingSphere
