### ISSUE TITLE
Can not find a way to set KeyGeneratorConfiguration for broadcast table

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2156]
I can  not find a way to set KeyGeneratorConfiguration for broadcast table.
for example:

- 't_country' is a broadcast table.(id is the PRIMARY key and AUTO_INCREMENT)
- there are two  data-node 'db1' and 'db2'.
- in 'db1',the AUTO_INCREMENT of t_country is begin with 100,
   in 'db2',the AUTO_INCREMENT of t_country is begin with 200.
- insert a record to 't_country'.
-  the id of the new record from 'db1'  is 101.
   the id of the new record  from 'db1'  is 201.

is this a problem?

**Comment by cherrylzhao** [comment]
I think it's ok, broadcast table does't need a global unique primary key, usually we fetch some dictionary info using left-join on country_code as above.

**Comment by betterjava** [comment]
ok. That is reasonable
