### ISSUE TITLE
how to recovery when xa transaction manager crashed after commit some resou

### ISSUE THREAD

**Issue by wenweihu86** [apache/incubator-shardingsphere#2160]
## Question
how to recovery when xa transaction manager crashed after commit some resource?

**For English only**, other languages will not accept.
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by wenweihu86** [comment]
@cherrylzhao why not store transaction log in database, so that:
1. another instance can recover when instance crash.
2. in paas environment, instance may drift.

**Comment by cherrylzhao** [comment]
we just integrated XA transaction manager of third-party, local filesystem is the recovery way for atomikos. also we consider about extending the log persistence for cloud native environment in future.

**Comment by cherrylzhao** [comment]
any other questions? we'd like to close issue if no response more than 7 days.
