### ISSUE TITLE
Integrate mongodb transaction conflict error

### ISSUE THREAD

**Issue by jimmycheng888** [apache/incubator-shardingsphere#2170]
### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC 
### Actual behavior
 Switching transaction Type is unsupported for transaction manager org.springframework.data.mongodb.MongoTransactionManager

### Example codes for reproduce this issue (such as a github link).
java Code
```
@Configuration
public class MongoConfig {

    @Bean
    MongoTransactionManager mongoTransactionManager(MongoDbFactory mongoDbFactory) {
        return new MongoTransactionManager(mongoDbFactory);
    }
}
```
maven Configuration information
```
<!--sharing-jdbc start-->
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
	<version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-spring-boot-starter</artifactId>
	<version>3.1.0</version>
        </dependency>
        <!--sharing-jdbc end-->

       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
	<version>2.1.5.RELEASE</version>
        </dependency>
```

**Comment by cherrylzhao** [comment]
hi, @jimmycheng888 
would you please push your demo-project to GitHub, let me have a try.

**Comment by jimmycheng888** [comment]
> hi, @jimmycheng888
> would you please push your demo-project to GitHub, let me have a try.

Impossible internal company project, because it uses the features of mongdb4.X to support the transaction, but you can reproduce it according to the code configuration above, the project is the spring boot project.

The reason for the abnormality is because class io.shardingsphere.transaction.aspect;ShardingTransactionalAspect 
Caused by this method
private void setTransactionManagerHandler(PlatformTransactionManager transactionManager) {
        switch(ShardingTransactionalAspect.TransactionManagerType.getTransactionManagerTypeByClassName(transactionManager.getClass().getName())) {
        case DATASOURCE:
            this.transactionManagerHandler = new DataSourceTransactionManagerHandler(transactionManager);
            break;
        case JPA:
            this.transactionManagerHandler = new JpaTransactionManagerHandler(transactionManager);
            break;
        case UNSUPPORTED:
        default:
            throw new ShardingException(String.format("Switching transaction Type is unsupported for transaction manager %s", transactionManager.getClass().getName()), new Object[0]);
        }

    }

**Comment by cherrylzhao** [comment]
ok, I'll try to reproduce it in my local environment.

**Comment by jimmycheng888** [comment]
> ok, I'll try to reproduce it in my local environment.
ShardingTransactionalAspect In this package
sharding-transaction-spring-3.1.0.jar

**Comment by cherrylzhao** [comment]
@jimmycheng888 , I'm sorry for my lately reply.
would you please let me know your sharding-configuration with `mongodb `.
mongodb-driver haven't implemented DataSource interface but we need it.
it seems that mongodb can't integrate with shardingshphere currently.
do your project need access multiple databases  like mysql , mongodb? and shardingsphere only integrated configuration with mysql?

**Comment by cherrylzhao** [comment]
ShardingSphere only support relation database currently, also we consider about adding no-sql support in future.

**Comment by cherrylzhao** [comment]
we'll close this issue due to no response more than 7 days.
