### ISSUE TITLE
sharding.jdbc.config.config.map.key1 文档示例错误

### ISSUE THREAD

**Issue by MorganYoung** [apache/incubator-shardingsphere#2176]
https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/
some config example was incorrect "config.map"
sharding.jdbc.config.config.map.key1=  
the correct properties should be "config-map"
sharding.jdbc.config.config-map.key1=

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
