### ISSUE TITLE
mysql Insert missing the into keyword causes no logical table name to be resolved

### ISSUE THREAD

**Issue by ztgoto** [apache/incubator-shardingsphere#2178]
sharding-jdbc-core:3.1.0

io.shardingsphere.core.parsing.parser.clause.TableReferencesClauseParser

protected final void parseTableFactor(final SQLStatement sqlStatement, final boolean isSingleTableOnly)

**Comment by terrymanu** [comment]
We are using new parse engine on 4.x, so I just close this issue. Old parse engine should be expired
