### ISSUE TITLE
performance test of sharding_proxy

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-shardingsphere#2188]
we want to use sharding_proxy in our product. is their any performance test result of sharding_proxy used on mysql server?

**Comment by tuohai666** [comment]
Not yet. We plan to supply a performance report recently.
Before the report is done. If you would like to test the performance in your environment, we can discuss about it here.

**Comment by tuohai666** [comment]
We can find the progress of performance test in this new issue: https://github.com/apache/incubator-shardingsphere/issues/2908
