### ISSUE TITLE
routeResult 获取不到时,没有抛弃异常

### ISSUE THREAD

**Issue by hexiangtao** [apache/incubator-shardingsphere#2203]
![image](https://user-images.githubusercontent.com/6630743/56091663-3407ed80-5ee4-11e9-81f2-d7c752dcc738.png)

![image](https://user-images.githubusercontent.com/6630743/56091994-fa85b100-5ee8-11e9-950e-ae7d8ff3db24.png)

route()方法抛异常，直接进finally,导致这里拿到的RouteResult为null,然后JDBCShardingRefreshHandler.execute()方法内部调getRouteResult()获取到的是null。getRouteResult().canRefreshMetaData()抛NullPointerException而没有告知具体的SqlException,对使用者来说不好排查问题，建议把具体的SQLException打印出来

**Comment by cherrylzhao** [comment]
duplicate with  #1882

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
