### ISSUE TITLE
 select a.id ,c.id  order by a.id, the result  can not sort by designated column

### ISSUE THREAD

**Issue by lucy3399** [apache/incubator-shardingsphere#2204]
### Which version of ShardingSphere did you use?
   3.0.0.M1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
correct sort by designated column,or when cannot surpport throw exception inform  user ？

### Actual behavior
multi-result can not correct sort by designated column

### Reason analyze (If you can)
 i see the encapsulate select columns is map  and map's key from columnLabel,so the same column will be overwrite  ,when  setIndexForOrderItem(columnLabelIndexMap, orderByItems);  orderby column   will  find  error index ,so that result sort is wrong .i use alias with different table same column name and order by their alias can get a right result

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT
        i.user_id  ,o.user_id 
        FROM
        t_order o, t_order_item i
        WHERE
        o.order_id = i.order_id
        order by i.user_id

**Comment by KomachiSion** [comment]
@lucy3399 Can you provide your sharding configuration?

**Comment by lucy3399** [comment]
https://github.com/lucy3399/sharding-mybatis-demo

**Comment by KomachiSion** [comment]
@lucy3399 sorry, what's your correct result and SQL?  I run your demo code, but it work well.

**Comment by KomachiSion** [comment]
OK, I understand your problem. In your demo, if `user_id` in **t_order** and **t_order_item** are different, the `order by` will be sorted by later defined not by former defined?

**Comment by lucy3399** [comment]
Yes，this is my problem




| |
朱婷
|
|
邮箱：lucy636@163.com
|

签名由 网易邮箱大师 定制

On 04/17/2019 09:43, 杨翊 Sion Yang wrote:

OK, I understand your problem. In your demo, if user_id in t_order and t_order_item are different, the order by will be sorted by later defined not by former defined?

**Comment by lucy3399** [comment]
Yes this is my problem

**Comment by KomachiSion** [comment]
Hi @lucy3399, `columnLabelIndexMap` is created from JDBC's resultset metadata, but resultset metadata doesn't include the owner information of column( like `o` or `i`). 
So we may fix this bug thoroughly by doing some change in `parsingEngine`, it may cost more time.

For now, I suggest you use unique alias to avoid this problem. It also can make your SQL more accurate.

At last, thanks for your useful feedback.
