### ISSUE TITLE
mysql insert decimal error

### ISSUE THREAD

**Issue by michaeljinxq** [apache/incubator-shardingsphere#2211]
sharding proxy version
https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin.tar.gz

(1)
create table tbname1 (id int primary key,key_price decimal(16,2) DEFAULT NULL);

(2)
mysql> INSERT INTO tbname1 VALUES (1,13.00);
ERROR 10002 (C1000): 2Unknown exception: [For input string: "13.00"]

thanks

**Comment by codefairy08** [comment]
it  could not convert double string value to number, it must convert to double
