### ISSUE TITLE
ProxyMain in sharding-proxy-example. The connection to sharding-proxy server refused.

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#2213]
Run ProxyMain.java in 'sharding-proxy-example' of  'incubation-shardingsphere-example' project, the connection to sharding-proxy server was refused.
Client and server have been configured as below:
Client
ProxyMain.java
    private static DataSource createDataSource() {
        BasicDataSource result = new BasicDataSource();
        result.setDriverClassName(com.mysql.jdbc.Driver.class.getName());
        result.setUrl(String.format("jdbc:mysql://%s:%d/sharding_db?useServerPrepStmts=true&cachePrepStmts=true", PROXY_IP, PROXY_PORT));
        result.setUsername("root");
        result.setPassword("");
        return result;
    }

Sharding-proxy server
server.yaml
orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    serverLists: localhost:2181
    namespace: orchestration
authentication:
  username: root
  password:
props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.transaction.enabled: false
  proxy.opentracing.enabled: false
  sql.show: false

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by tuohai666** [comment]
The password should be "root".

**Comment by wgy8283335** [comment]
@tuohai666. I've tried to change the password to "root". But, the same error happened again.

**Comment by wgy8283335** [comment]
@tuohai666 
link:
https://github.com/apache/incubator-shardingsphere-example/tree/sharding-jdbc-transaction-saga-example.
java file:
incubator-shardingsphere-example/sharding-proxy-example/src/main/java/io/shardingsphere/example/proxy/ProxyMain.java

**Comment by wgy8283335** [comment]
@tuohai666 . Thanks for your help.

**Comment by tuohai666** [comment]
@wgy8283335 Could you tell why close this issue?

**Comment by wgy8283335** [comment]
@tuohai666. Beacuse, the issue has been resolved, after modified config-sharding.yaml.
