### ISSUE TITLE
add extension support for sharding master slave router

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#2218]
## Feature Request

we suggest to add extension support like spi for sharding master slave router.
in some scenario we many need to check weather to router to master only based on some custom context(not HintMnager)

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no
### Describe the feature you would like.
extension support for sharding master slave router

**Comment by terrymanu** [comment]
Hi, I don't think add so many extension is necessary, and we don't have any evidence to prove enduser need this feature.
Add complexity without benefit is  unnecessary, can you prove importance of this extension?

**Comment by terrymanu** [comment]
No response any more, if not want discuss further, I just close this issue.
