### ISSUE TITLE
SnowflakeShardingKeyGenerator hava a bug 

### ISSUE THREAD

**Issue by traceless** [apache/incubator-shardingsphere#2219]
## Bug Report

i have found a bug when i review code in SnowflakeShardingKeyGenerator.java 

### Which version of Sharding-Sphere do you using?
3.1.0.M1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC

## Bug in here
```  
    if (lastMilliseconds == currentMilliseconds) {
            if (0L == (sequence = (sequence + 1) & SEQUENCE_MASK)) {
                currentMilliseconds = waitUntilNextTime(currentMilliseconds);
            }
        } else {
            vibrateSequenceOffset();
            sequence = sequenceOffset;
        }
```
i think sequence need reset sequenceOffset when ' (sequence = (sequence + 1) & SEQUENCE_MASK) == 0' ;

### show you my code
```  
    if (lastMilliseconds == currentMilliseconds) {
            if (0L == (sequence = (sequence + 1) & SEQUENCE_MASK)) {
                vibrateSequenceOffset();
                sequence = sequenceOffset;
                currentMilliseconds = waitUntilNextTime(currentMilliseconds);
            }
        } else {
            vibrateSequenceOffset();
            sequence = sequenceOffset;
        }
```
Because I also need sequenceOffset in my project and  i find my code have different with you, so I'm not sure who's right.

**Comment by tristaZero** [comment]
@traceless Hi,
If we want to vibrateSequenceOffset() for every sequence, i think the better solution is,
```
@Override
    public synchronized Comparable<?> generateKey() {
        long currentMilliseconds = timeService.getCurrentMillis();
        if (waitTolerateTimeDifferenceIfNeed(currentMilliseconds)) {
            currentMilliseconds = timeService.getCurrentMillis();
        }
        if (lastMilliseconds == currentMilliseconds) {
            if (0L == (sequence = (sequence + 1) & SEQUENCE_MASK)) {
                currentMilliseconds = waitUntilNextTime(currentMilliseconds);
            }
        }
        vibrateSequenceOffset();
        sequence = sequenceOffset;
        lastMilliseconds = currentMilliseconds;
        return ((currentMilliseconds - EPOCH) << TIMESTAMP_LEFT_SHIFT_BITS) | (getWorkerId() << WORKER_ID_LEFT_SHIFT_BITS) | sequence;
    }
```
How do you think this solution？

**Comment by traceless** [comment]
@tristaZero Hi
I thought the 'SequenceOffset' was designed for the sequence offset ，but i can find anyway to set the variable 'SequenceOffset' , so i just run the vibrateSequenceOffset method and found the result was alternate 1,0,1,0 . i don't konw why don't you set it to 0 directly?

**Comment by traceless** [comment]
@tristaZero 
oh， i just kown why you design the method vibrateSequenceOffset.

**Comment by traceless** [comment]
@tristaZero 
so , it no problem in you code.   Because I misunderstood it ('vibrateSequenceOffset')

**Comment by tristaZero** [comment]
@tristaZero Thanks for your reply, so can we close this issue?

**Comment by traceless** [comment]
@tristaZero 
OK ，without doubt

**Comment by tristaZero** [comment]
@tristaZero Thanks for your reply, so can we close this issue?
