### ISSUE TITLE
Incorrect integer value: 'NULL' for column

### ISSUE THREAD

**Issue by michaeljinxq** [apache/incubator-shardingsphere#2222]
【 int 】
(1)create table tb1 (id int);

(2)insert into tb1 values (null);
ERROR 1366 (HY000): Incorrect integer value: 'NULL' for column 'id' at row 1

**Comment by michaeljinxq** [comment]
apache-shardingsphere-incubating-4.0.0-RC1-SNAPSHOT-sharding-proxy-bin.tar

**Comment by codefairy08** [comment]
check null value for sharding column

**Comment by cjj137783** [comment]
@codefairy08  below is my sql , my sharding column is user_id 

```
insert into log_user_key_action_1 (id, user_id,exchange_id ) 
values (575292640792121344, 112243515, null ) ;
```
the exchange_id is Int  in mysql , and got an error message 'Incorrect integer value: 'null' for column 'exchange_id' at row 1'     ,  but I can execute in my  Sub-table   like  this :

```
insert into log_user_key_action_1 (id, user_id,exchange_id ) 
values (575292640792121344, 112243515, null ) ;
```
