### ISSUE TITLE
Can not execute  DML in proxy where contain now() function

### ISSUE THREAD

**Issue by michaeljinxq** [apache/incubator-shardingsphere#2225]
mysql> insert into my_orders(name,create_time,age,ttt,dc) values('ruiaylin1', '2019-04-16 18:00:00', null,now(), 14.56) ;
ERROR 1292 (22001): Data truncation: Incorrect datetime value: 'now()' for column 'ttt' at row 1

Actual SQL: online_ds ::: insert into my_orders_201904 (name, create_time, age, ttt, dc) VALUES ('ruiaylin1', '2019-04-16 18:00:00', null, 'now()', 14.56)
[INFO ] 09:42:23.927 [ShardingSphere-Command-1] ShardingSphere-SQL -

**Comment by terrymanu** [comment]
duplicate with #1497

**Comment by xiaoyuge** [comment]
Is this problem fixed?
