### ISSUE TITLE
Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

### ISSUE THREAD

**Issue by limeng546364** [apache/incubator-shardingsphere#2233]
## Bug Report
I am using sharding-jdbc 3.1.0 or 4.0.0-RC2-SNAPSHOT， spring boot version 2.1.4 
The startup service has the following problem

![image](https://user-images.githubusercontent.com/13583921/56417236-dac60280-62c5-11e9-9aeb-1fe5490abda5.png)

Could you please tell me how to solve this problem

**Comment by terrymanu** [comment]
Spring boot 2.x cannot permit user use key name contains `_`
It is Spring boot's problem

**Comment by limeng546364** [comment]
I am using Spring boot 2.1.4 supported user use key contains _ The following

Configuration center
![image](https://user-images.githubusercontent.com/13583921/56490215-01c74300-6517-11e9-81ed-643d28e63214.png)
The program
![image](https://user-images.githubusercontent.com/13583921/56490243-14417c80-6517-11e9-9c04-1e81efcc3d4a.png)
Thank you for

**Comment by Adarshkl** [comment]
The `_` works with `@Value`. The kebab case restriction is when you are using the `@ConfigurationProperties` config pojos
