### ISSUE TITLE
I can't find class MySQLStatementParser

### ISSUE THREAD

**Issue by a137872798** [apache/incubator-shardingsphere#2242]
你好 我想看Shardingsphere的源码 但是在看到SQLParser类的时候发现最重要的parse()实现类MySQLStatementParser 竟然找不到

**Comment by codefairy08** [comment]
Create issue in englist please，this class was generated by antlr, use command mvn clean install

**Comment by a137872798** [comment]
thank you for your answer


发自我的iPhone

------------------ Original ------------------
