### ISSUE TITLE
I can't find class MySQLStatementParser

### ISSUE THREAD

**Issue by a137872798** [apache/incubator-shardingsphere#2245]
after use command mvn clean install -Prelease, I can't find class MySQLStatementParser,and class
MySQLParser is depend on it

**Comment by codefairy08** [comment]
please execute mvn clean install in root directory of shardingsphere
![image](https://user-images.githubusercontent.com/39583929/56548768-8cf61680-65b3-11e9-8057-ea2790641621.png)
After successful execution of the command， In the  directory of "${incubator-shardingsphere}\sharding-core\sharding-core-parse\sharding-core-parse-mysql\target", antlr generate java file is in the directory of generated-sources, compiled classed file is in the directory of  classes
![image](https://user-images.githubusercontent.com/39583929/56549023-3b9a5700-65b4-11e9-832a-c278b6669a31.png)

![image](https://user-images.githubusercontent.com/39583929/56549329-11956480-65b5-11e9-973b-e15d571fd255.png)

**Comment by a137872798** [comment]
thank you for your answer


发自我的iPhone

------------------ Original ------------------

**Comment by terrymanu** [comment]
@a137872798 can you close issue?

**Comment by xiaoyi001yeye** [comment]
这个解释只是解决了编译期间的问题，在开发中那些Visitor 还是飘红的，我想对这块做一些二次开发，完全不能开发。

**Comment by sgc109** [comment]
For anyone who comes to this issue, this might help! https://stackoverflow.com/a/46812593/4773879
