### ISSUE TITLE
Wrong Batch Comment

### ISSUE THREAD

**Issue by xlongshu** [apache/incubator-shardingsphere#2247]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
[start.bat](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-distribution/sharding-proxy-distribution/src/main/resources/bin/start.bat)
Batch Comment `@rem` or `rem`
### Actual behavior
shell comment `#`

**Comment by tristaZero** [comment]
Thanks for your issue.💖
