### ISSUE TITLE
分表的字段支持负数吗？

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#2250]
如果业务上unit_id是包含负数和正数，当unit_id是负数时，下面的配置，得到的表名可能是l_unit_-1，请问该如何正确配置呢？ 

yaml关键配置:
....
tables:
        l_unit:
          actual-data-nodes: ms.l_unit_$->{0..1}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
             sharding-column: unit_id
             algorithm-expression: l_unit_$->{unit_id % 2}

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
