### ISSUE TITLE
shardingsphere4.0.0-RC1,Incorrect datetime value: 'now()' for column 'create_time' at row 

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#2253]
shardingsphere4.0.0-RC1,report the following error：

Incorrect datetime value: 'now()' for column 'create_time' at row 

ShardingSphere-SQL - Actual SQL: rw0 ::: insert into t_order(id, first_channel, biz_bill_no, orig_bill_no, warehouse_id, sku_code, change_inv_type, change_num, change_time, remark, create_time, create_person, update_time, update_person, is_deleted, version, sale_company, owner_id, bill_type, warehouse_code, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'now()', ?, 'now()', ?, 0, 0, ?, ?, ?, ?, ?) ::: [xx, xx, hh, hhh, xx, bb, xx, -6, 2019-04-24 09:22:54.825, null, xx, xx, xx, xx, 6, 0303, 0]

It seems that sharding treats the mysql now() function as a string.

**Comment by xfyang1989** [comment]
This problem is OK in version 3.0.1

**Comment by xfyang1989** [comment]
Is Shardingsphere 4.0.0-RC1 having this problem?

**Comment by codefairy08** [comment]
@xfyang1989  it also has this problem, i will fix it

**Comment by AlbertTao** [comment]
Is there any workgroud to avoid this problem now ?

I just try SYSDATE() but, also has this problem :

```
Exception in thread "main" com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: 'SYSDATE()' for column 'gmt_created' at row 1
```

**Comment by codefairy08** [comment]
@xfyang1989  it was fixed，please have a try using latest dev branch code

**Comment by xfyang1989** [comment]
3Q,When will these bugs be released to release a new version?

**Comment by xfyang1989** [comment]
I feel that this 4.0.0-RC1 introduces a new bug, and these features are OK in version 3.0.1. I have used the smallest version of 4.0.0 in the project to keep the wrong version. . I feel that I will not continue to upgrade in the future.
