### ISSUE TITLE
May sharding-column supports both  negative and positive number ?

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#2255]
If unit_id may be a negative or positive number，when unit_id is a negative number，the table name may be l_unit_-1，but our table names are unit_id_0 and unit_id_1.

How can we config this case?

====yaml====
....

> tables:
   l_unit:
       actual-data-nodes: ms.l_unit_$->{0..1}
       key-generator:
            column: id
            type: SNOWFLAKE
      table-strategy:
         inline:
             sharding-column: unit_id
             algorithm-expression: l_unit_$->{unit_id % 2}

**Comment by terrymanu** [comment]
You can use `standard` ShardingStrategy. 
FYI: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-yaml/

**Comment by childewuque** [comment]
> You can use `standard` ShardingStrategy.
> FYI: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-yaml/

**If unit_id equals -1, the tablename will be  unit_id_-1**
But I don't find the correct stragegy.

**Comment by terrymanu** [comment]
You can use standard ShardingStrategy. How to return table name is up to developer

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
