### ISSUE TITLE
官网的文档可不可以详细点？

### ISSUE THREAD

**Issue by keji94** [apache/incubator-shardingsphere#2259]
最近项目做服务拆分，可能用到分库分表以及读写分离。很想尝试shrding-jdbc。但是官网的文档太粗糙，有用的信息很少。希望文档能够简单介绍下原理，有什么弊端这些。比如我用读写分离，shrding-jdbc的策略是怎么样的？有没有什么限制？事务的支持是怎么样的？到什么颗粒度？这些官方文档都找不到，或者隐藏的很深。

一个友好，全面的文档，是开源项目不可或缺的，希望尽快完善。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
