### ISSUE TITLE
How to config JNDI in datasource

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#2260]
No sample,below is error:

spring.shardingsphere.datasource.ds0.type=JNDI
spring.shardingsphere.datasource.ds0.jndiname=java:comp/env/jdbc/mymaster

What is correct?

**Comment by terrymanu** [comment]
`type` mean is your data source pool class name, JNDI is not  data source pool class name obviously.
You can use java API to generate datasource from JNDI and pass them to sharding rule config.

**Comment by childewuque** [comment]
The above code is just a guess.
Hard code is not simple，we must bind datasource and all rules， even a bit cumbersome...
Additionally, Spring boot 2.0 supports JNDI now. So I hope Shardingsphere could support it.
