### ISSUE TITLE
missing org.apache.shardingsphere.core.parse.antlr.autogen.MySQLStatementParser

### ISSUE THREAD

**Issue by EvanDylan** [apache/incubator-shardingsphere#2262]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Actual behavior
i have clone sourcecode,but in the module of `sharding-core-parse-mysql`, `MySQLParser` has import class of `org.apache.shardingsphere.core.parse.antlr.autogen.MySQLStatementParser` .Then i have search whole project, but i still can't find it. It's anything i do wrong? pls help me

**Comment by codefairy08** [comment]
duplicated #2245
