### ISSUE TITLE
com.mysql.jdbc.jdbc2.optional.MysqlXADataSource Deprecated

### ISSUE THREAD

**Issue by t5721654** [apache/incubator-shardingsphere#2268]
-----------------------------
public final class XADataSourceFactory {
    
    private static final Map<DatabaseType, String> XA_DRIVER_CLASS_NAMES = new HashMap<>(DatabaseType.values().length, 1);
    
    static {
        XA_DRIVER_CLASS_NAMES.put(DatabaseType.H2, "org.h2.jdbcx.JdbcDataSource");
        XA_DRIVER_CLASS_NAMES.put(DatabaseType.MySQL, "com.mysql.jdbc.jdbc2.optional.MysqlXADataSource");
        XA_DRIVER_CLASS_NAMES.put(DatabaseType.PostgreSQL, "org.postgresql.xa.PGXADataSource");
        XA_DRIVER_CLASS_NAMES.put(DatabaseType.Oracle, "oracle.jdbc.xa.client.OracleXADataSource");
        XA_DRIVER_CLASS_NAMES.put(DatabaseType.SQLServer, "com.microsoft.sqlserver.jdbc.SQLServerXADataSource");
    }

--------------------------------------------
Mysql - com.mysql.jdbc.jdbc2.optional.MysqlXADataSource  is deprecated in latest mysql-connector-java!!   and no any messages shows when convert dataSource to transactionDataSource failed! 

-----------------------

public final class XADataSourceConverter implements TransactionalDataSourceConverter {
    
    private final XATransactionManager xaTransactionManager = XATransactionManagerSPILoader.getInstance().getTransactionManager();
    
    @Override
    public TransactionType getType() {
        return TransactionType.XA;
    }
    
    @Override
    public Map<String, DataSource> convert(final DatabaseType databaseType, final Map<String, DataSource> dataSourceMap) {
        Map<String, DataSource> result = new HashMap<>(dataSourceMap.size(), 1);
        try {
            for (Entry<String, DataSource> entry : dataSourceMap.entrySet()) {
                DataSourceParameter parameter = DataSourceSwapperRegistry.getSwapper(entry.getValue().getClass()).swap(entry.getValue());
                DataSource dataSource = xaTransactionManager.wrapDataSource(databaseType, XADataSourceFactory.build(databaseType), entry.getKey(), parameter);
                result.put(entry.getKey(), dataSource);
            }
            return result;
        } catch (final Exception ex) {
            return result;
        }
    }
}

**Comment by cherrylzhao** [comment]
we suggested you use 4.0.0-RC1, thanks.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
