### ISSUE TITLE
why version 3.0 has no spring module?

### ISSUE THREAD

**Issue by nexxxxxxx** [apache/incubator-shardingsphere#2269]
I integrate shardingsphere useing sharding-jdbc-spring-boot-starter
but I can't find the source code of sharding-jdbc-spring-boot-starter in version3
only dev branch has the spring module

can you guys give us an explanation?

thanks a lot !

**Comment by terrymanu** [comment]
At version 3.0, spring module is not donate to ASF yet. 
Spring module is available on 4.0.0-RC1.

**Comment by nexxxxxxx** [comment]
@terrymanu 
ok!
I appreciate your answer
