### ISSUE TITLE
ShardingSphere4.0.0-RC1 batch query (500) performance is seriously degraded

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#2270]
ShardingSphere4.0.0-RC1 with fragmentation and database unique index Batch query (500) is significantly worse than 3.0.1 version, faster query in version 3.0.1, almost inquiries in the smallest 4.0.0-RC1

Is there such a problem?

**Comment by terrymanu** [comment]
Can you provide more details?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
