### ISSUE TITLE
ERROR when tried to import sql file into a  sharding-proxy system

### ISSUE THREAD

**Issue by Zatomsmasher** [apache/incubator-shardingsphere#2277]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere 3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
import data from sql file
### Actual behavior
get ERROR

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. use mysqldump  to get the sql file
 e.g. mysqldump  -uroot -p database table > table.sql
2.use mysql CLI cilent to sharding-proxy and source the sql file
mysql -u root -p -P 3307 -h 127.0.0.1 
mysql>source table.sql
then I got this error:
mysql> source /usr/local/mysql/table.sql
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'INT', literals is 'int'.
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'java'.
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'INT', literals is 'int'.
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'INT', literals is 'int'.
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'INT', literals is 'int'.
ERROR 3054 (HY000): Unknown exception: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'INT', literals is 'int'.

**Comment by tuohai666** [comment]
1. What if execute one of the insert SQLs from table.sql via ShardingProxy? 
2. What if execute one of the insert SQLs from table.sql directly connect to the database ? 
3. Please show the SQLs that can not execute.

**Comment by Zatomsmasher** [comment]
@tuohai666 
1.same error
2.worked well
3. insert into info_title values(1521846697390,'搜索结果：\'swatch 、\'');

**Comment by Zatomsmasher** [comment]
@tuohai666 sry for the delay

**Comment by tuohai666** [comment]
@Zatomsmasher I have tried the SQL in raw database and got a error message:
```
insert into info_title values(1521846697390,'搜索结果：'swatch 、'')
> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'swatch 、'')' at line 1
> 时间: 0.002s
```
The MySQL server version is 5.6.23. Please double check the SQL.

**Comment by Zatomsmasher** [comment]
@tuohai666 
MySQL Community Server 5.5.52
![Uploading image.png…]()

**Comment by tuohai666** [comment]
@Zatomsmasher Please describe table.

**Comment by Zatomsmasher** [comment]
@tuohai666 
CREATE TABLE `info_title` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by tuohai666** [comment]
@Zatomsmasher I got it . These two SQLs are not identical.

**Comment by tuohai666** [comment]
@Zatomsmasher This is a parsing problem. Are there any more SQLs that can't execute? We may fix together.

**Comment by Zatomsmasher** [comment]
i did a little test. It seems that all the error sql contains **\'**  character

**Comment by tuohai666** [comment]
`insert into info_title values(1521846697390,'搜索结果：\'swatch 、\'');`
This SQL can't be executed if the table do not have a sharding rule. 
If you want to execute INSERT SQLs without a sharding rule, change the SQL to:
`insert into info_title(id, info) values(1521846697390,'搜索结果：\'swatch 、\'');`

**Comment by Zatomsmasher** [comment]
or I can make a sharding rule like %1?

**Comment by tuohai666** [comment]
or master-slave rule which master and slave share the same datasource.

**Comment by Zatomsmasher** [comment]
![image](https://user-images.githubusercontent.com/37434384/56888991-e83e7200-6aa7-11e9-8fec-3d55167a4f5d.png)
I have tried to adjust my sql and re-config the .yaml file .it stil doesn't work for me at all.

**Comment by tuohai666** [comment]
This error may happens in 3.1.0. Can you try 4.0.0-RC1?

**Comment by Zatomsmasher** [comment]
👌 I'll have a shot

**Comment by tuohai666** [comment]
@Zatomsmasher any progress?

**Comment by Zatomsmasher** [comment]
> @Zatomsmasher any progress?
updated to 4.0.0-RC1 and problem was  resolved. Thx~
