### ISSUE TITLE
proxy3.1.0，SQL cannot be executed

### ISSUE THREAD

**Issue by 799983050** [apache/incubator-shardingsphere#2281]
用proxy3.1.0 导入sql文件。INSERT INTO `user_info` VALUES (485145, 489235, '1', 111811, NULL, '张维彬\'', '1')  。报错为Unknown exception: INSERT INTO column size mismatch value size.
是 张维彬\' 后面的\'导致的，proxy解析有问题，执行不了这条语句，但是把这个语句在原生的mysql库执行是没问题的。 3.0.0的报错信息不准确（Unknown exception:Index:6,Size:6）所以没发现问题。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
