### ISSUE TITLE
proxy4.0.0 Unable to start properly

### ISSUE THREAD

**Issue by 799983050** [apache/incubator-shardingsphere#2282]
![图片](https://user-images.githubusercontent.com/45658355/56807936-c607e280-6862-11e9-967b-1d1130ab8042.png)
![图片](https://user-images.githubusercontent.com/45658355/56808140-5c3c0880-6863-11e9-8bdb-2d4d53331251.png)

After decompression,lib Add to  mysql-connector-java-5.1.47.jar. start.sh is executed directly.

Download links
https://www.apache.org/dyn/closer.cgi?path=incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin.tar.gz

**Comment by cherrylzhao** [comment]
maybe you haven't comment out the setting in your yaml file.

**Comment by 799983050** [comment]
@cherrylzhao After modifying the configuration file, the startup is successful.
But the first message I got was that you can start without any modifications.Hope this is clear to users
