### ISSUE TITLE
Can a broadcast table specify some data sources instead of all data sources?

### ISSUE THREAD

**Issue by xinghh100-githhub** [apache/incubator-shardingsphere#2283]
Version of ShardingSphere is 4.0.0-RC1

Can a broadcast table specify some data sources instead of all data sources?

**Comment by terrymanu** [comment]
I can't understand, what'e mean "broadcast table specify some data sources"? and what is all data sources, what is the relationship of broadcast table and all data sources?

**Comment by xinghh100-githhub** [comment]
----------------------
schemaName: xxx

dataSources:
  ds_1:
    url: jdbc:mysql://localhost:3306/bizb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_0:
    url: jdbc:mysql://localhost:3306/biza?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_2:
    url: jdbc:mysql://localhost:3306/bizc?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_2.t_order_${201901..201912}
      tableStrategy:
        standard:
          shardingColumn: op_time
          preciseAlgorithmClassName: cc.xxx.shardingsphere.sharding.PartitionByMonthPreciseShardingAlgorithm
          rangeAlgorithmClassName: cc.xxx.shardingsphere.sharding.PartitionByMonthRangeShardingAlgorithm
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
  broadcastTables:
    - t_district
    - t_parklot

  defaultDataSourceName: ds_0
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

----------------------
For example, the configuration of the upper description：

The broadcast table t_district in the configuration, the default data node is ds_${0..2}.t_district, but in the actual application scenario, only the data node needs to be broadcast: ds_${0..1}.t_district, and The table t_district does not exist in the data source ds_2. When a DML operation is performed, an exception is thrown: ERROR 1146 (42S02): Table 'bizc.t_district' doesn't exist.

I think if the existing version supports the above-mentioned actual application scenario, if it is not supported, is there any plan for the subsequent version? (The above scenario MyCat is supportable)

**Comment by terrymanu** [comment]
> the default data node is ds_${0..2}.t_district
How to understand  `default data node is ds_${0..2}.t_district`?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
