### ISSUE TITLE
ComplexKeysShardingAlgorithm 不支持 Between And吗？

### ISSUE THREAD

**Issue by Kanepan** [apache/incubator-shardingsphere#2284]
版本：4.0.0-RC1
期望，用snowflake的主键，作为分表规则，查询的时候，如果带有创建时间 gmt_create 则根据时间来判断。
spring.shardingsphere.sharding.tables.biz_order.table-strategy.complex.sharding-columns=id,createTime
spring.shardingsphere.sharding.tables.biz_order.table-strategy.complex.algorithm-class-name=com.kane.shardingjdbctest.shardingjdbcext.rules.TimeAndFlowSlakeShardingAlgorithm
spring.shardingsphere.sharding.tables.biz_order.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.biz_order.key-generator.column=id

当我查询语句带有 
SELECT * FROM biz_order WHERE gmt_create  between #{startTime} and  #{endTime}
则报错
BetweenRouteValue cannot be cast to org.apache.shardingsphere.core.strategy.route.value.ListRouteValue

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
