### ISSUE TITLE
Whether to support the use of select last_insert_id () to return the self-growth primary key？

### ISSUE THREAD

**Issue by xinghh100-githhub** [apache/incubator-shardingsphere#2285]
Version of ShardingSphere is 4.0.0-RC1

Whether to support the use of select last_insert_id () to return the self-growth primary key？

**Comment by terrymanu** [comment]
No, we prefer use distributed sequence to instead of non-distributed sequence is sharding tables.
Unfortunately, `last_insert_id` is return MySQL's non-distributed sequence which does not make sense.

**Comment by xinghh100-githhub** [comment]
----------------------
schemaName: xxx

dataSources:
  ds_1:
    url: jdbc:mysql://localhost:3306/bizb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_0:
    url: jdbc:mysql://localhost:3306/biza?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_2:
    url: jdbc:mysql://localhost:3306/bizc?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XXX
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_2.t_order_${201901..201912}
      tableStrategy:
        standard:
          shardingColumn: op_time
          preciseAlgorithmClassName: cc.xxx.shardingsphere.sharding.PartitionByMonthPreciseShardingAlgorithm
          rangeAlgorithmClassName: cc.xxx.shardingsphere.sharding.PartitionByMonthRangeShardingAlgorithm
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
  broadcastTables:
    - t_district
    - t_parklot

  defaultDataSourceName: ds_0
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
----------------------
For example, the configuration of the upper description：

The broadcast table t_district in the configuration, the default data node is ds_${0..2}.t_district, but in the actual application scenario, only the data node needs to be broadcast: ds_${0..1}.t_district, and The table t_district does not exist in the data source ds_2. When a DML operation is performed, an exception is thrown: ERROR 1146 (42S02): Table 'bizc.t_district' doesn't exist.

I think if the existing version supports the above-mentioned actual application scenario, if it is not supported, is there any plan for the subsequent version? (The above scenario MyCat is supportable)

**Comment by xinghh100-githhub** [comment]
Some business scenarios need to return to the auto-increment primary key after the insert operation, rather than before the insert, for example:
<insert id="insertSelective" parameterType="xxx" >
     <selectKey resultType="java.lang.Long" keyProperty="id" order="AFTER" >
       Select LAST_INSERT_ID()
     </selectKey>
     Insert into ...
</insert>
The current version is not compatible with this mode, and can only be used in the mode of first obtaining the distributed primary key and then inserting it. (MyCat supports the above modes)

**Comment by xinghh100-githhub** [comment]
Some business scenarios need to return to the auto-increment primary key after the insert operation, rather than before the insert, for example:
<insert id="insertSelective" parameterType="xxx" >
     <selectKey resultType="java.lang.Long" keyProperty="id" order="AFTER" >
       Select LAST_INSERT_ID()
     </selectKey>
     Insert into ...
</insert>
The current version is not compatible with this mode, and can only be used in the mode of first obtaining the distributed primary key and then inserting it. (MyCat supports the above modes)

**Comment by xinghh100-githhub** [comment]
Some business scenarios need to return to the auto-increment primary key after the insert operation, rather than before the insert, for example:
`<insert id="insertSelective" parameterType="xxx" >`
`    <selectKey resultType="java.lang.Long" keyProperty="id" order="AFTER" >`
      select LAST_INSERT_ID()
`    </selectKey>`
    insert into ...
`</insert>`
The current version is not compatible with this mode, and can only be used in the mode of first obtaining the distributed primary key and then inserting it. (MyCat supports the above modes)
