### ISSUE TITLE
Select resultset sometimes missing

### ISSUE THREAD

**Issue by monkeyfriend123** [apache/incubator-shardingsphere#2291]
We have 2 databases which store data, I use sharding-jdbc (Version:3.1.0) to select data,
when i query data very fast, it sometimes return data that less than correct data. even the data
is only in one datatabase

**Comment by terrymanu** [comment]
What is your SQL and query result, how to reproduce it?

**Comment by monkeyfriend123** [comment]
I use mybatis to select data from mysql dbs about 10000 times, each times select {min-create_time to max-create_time} range orders . it sometimes return less data.  
the below is my sql
`select
        t.`id`,t.`order_no`,t.`order_amount` ,t.`finish_type`,t.`finish_time`,t.`create_time`
        from <include refid="ORDER_TABLE_NAME"/> t
        where
        UNIX_TIMESTAMP(t.create_time)*1000  >= #{searchStartTime}
        and <![CDATA[ UNIX_TIMESTAMP(t.create_time)*1000  <= #{searchEndTime}]]>
        and t.channel_id in ('100')
        order by t.order_no
        limit 0,100`

**Comment by terrymanu** [comment]
what is your sharding key?

**Comment by monkeyfriend123** [comment]
order_no % 2 shard db.

**Comment by monkeyfriend123** [comment]
for example the db0 have order 2,4,6, db1 have 1,3,5 when i select , it sometimes only return order 2,4. and sometimes return 1,2,3,5,6 . all query is same parameters

**Comment by monkeyfriend123** [comment]
sometimes return 1,2,3,4,5,6

**Comment by terrymanu** [comment]
Does your SQL include sharding-key? For my understanding, every time will return all data sources for this SQL

**Comment by monkeyfriend123** [comment]
I found my problem is that , my sql limit rowcount.value is dynamic  then in multi thread context serveral selectstatements use the same Limit object , in the below code, the `limit.getRowCountValue()` maybe the other selectstatement setted, so it reads less data
`  @Override
    public boolean next() throws SQLException {
        if (skipAll) {
            return false;
        }
        if (limit.getRowCountValue() < 0) {
            return getMergedResult().next();
        }
        return ++rowNumber <= limit.getRowCountValue() && getMergedResult().next();
    }.`  when i use a static rowcount , it is correct

**Comment by terrymanu** [comment]
duplicate with #2136
