### ISSUE TITLE
Hint route is closed after use

### ISSUE THREAD

**Issue by jimmycheng888** [apache/incubator-shardingsphere#2297]
Which version of ShardingSphere did you use?
3.1.0

Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
Actual behavior
The first time I went to the database query, I was able to get the hint route, but the second time I couldn't get the hint route because HyintManager.close()

```
HintManager hintManager = HintManager.getInstance();
hintManager.addDatabaseShardingValue("t_user",“a”);
hintManager.addDatabaseShardingValue("t_person",“a”);
//After going to the database query successfully, you can get the hint route.
List<User> imGroupList = userMapper.allUser();
//Cannot get the hint route
List<Person> imGroupList = personMapper.allPerson();

```
**I hope that in the same method, I only need to use HintManager.getInstance(); once, because the project uses a lot of hint routes, which will lead to code confusion, and some colleagues' code is not standardized, or an exception causes HintManager.close() Not called, because I will encapsulate the HintManager in the custom annotation of the spring framework, unified control of the hint route**

Example codes for reproduce this issue (such as a github link).
java Code
```
public class HintAlgorithm implements HintShardingAlgorithm {
    private static final Logger logger = LoggerFactory.getLogger(HintAlgorithm.class);

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, ShardingValue shardingValue) {
        List<String> shardingResult = new ArrayList<>();
        /**
         * The first time you can come in, the second time you can never execute the segment code,
          * because the system has already called HyintManager.close()
         */
        if(shardingResult != null && shardingResult.size() > 0) {
            return shardingResult;
        }
        logger.error("Hint Algorithm fragmentation parameter error: availableTargetNames:{},shardingValue:{}",availableTargetNames,shardingValue);
        throw new UnsupportedOperationException();
    }


}
```

**Comment by jimmycheng888** [comment]
I don't understand why every time I use it to close, I think because I am worried about JVM memory overflow, I hope to leave an option for developers to close themselves, so that they can better extend the application.

**Comment by cherrylzhao** [comment]
hi, we have enhanced it in 4.0.0-RC1, you can see #2164
