### ISSUE TITLE
The strategy of master-slave-rule is not valid

### ISSUE THREAD

**Issue by gitOfhouge** [apache/incubator-shardingsphere#2306]
Version: Sharding-jdbc 4.0.0-RC1 release
Test: sharding-jdbc-spring-namespace
Database: Mysql 5.1.9
Description:
     First, I`m sure that my configuration of master-slave is right.  
     I want to use my own strategy of master-slave, so,  I have implemented the strategy interface of master-slave by myself, but it`s not valid when I debug my own strategy of master-slave. Finally, I find it`s master  when write DB and it`s slave when read DB. So, I guess that it`s default strategy not my own strategy when sharding database. Thank you!

**Comment by cherrylzhao** [comment]
thanks for feedback, I'll try to reproduce this problem in my local environment.

**Comment by cherrylzhao** [comment]
we should add a <sharding:load-balance-alogrithm> tag to handle customize load-balance strategy, I'll fix this later.

**Comment by cherrylzhao** [comment]
@gitOfhouge 
I have resolved this issue, you can verify it from our dev branch(4.0.0-RC2-Snapshot).
for customize master-slave strategy, we defined a new tag `<master-slave:load-balance-algorithm>` to extend it, your strategy should implement `MasterSlaveLoadBalanceAlgorithm` and the type literal is what should write in the `<master-slave:load-balance-algorithm>id='xxx' type='xxx' />`.
As customize strategy is based on SPI mechanism, so you should config  `META-INF.services` in your project to let service loader can find it, you can see what we have done in [org.apache.shardingsphere.spi.masterslave.MasterSlaveLoadBalanceAlgorithm](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-common/src/main/resources/META-INF/services/org.apache.shardingsphere.spi.masterslave.MasterSlaveLoadBalanceAlgorithm)

**Comment by gitOfhouge** [comment]
OK, I see. Thank you for your help.
