### ISSUE TITLE
sharing-jdbc 3.1.0  mybatis batch insert  performance is not satisfied

### ISSUE THREAD

**Issue by kofkyobsa** [apache/incubator-shardingsphere#2318]
## Question
I used sharing-jdbc version 3.1.0 to my project；
the ShardingAlgorithm is hash%64;
mybatis batch insert like insert values（）（）（）；
 500 records every submits;
its performance is not satisfied，just 50/s;
its too slow for my insert operation;

**how could i optimize the performance？**

**Comment by tuohai666** [comment]
Is the batch insert SQL lead to full routing?
Can you provide the sharding config and the logic SQL?

**Comment by kofkyobsa** [comment]
yes，full routing。
sharing config：
`actualDataNodes: yt_alita.t_wx_user_form_${0..31}
tableStrategy:
        inline:
          shardingColumn: open_id
          algorithmExpression: t_wx_user_form_${Math.abs(open_id.hashCode()%32)}`

logic SQL：
  

`INSERT INTO  
    t_wx_user_form_15
      (
             
    creator,editor,create_time,edit_time,is_deleted,open_id,form_id,form_type,remain_count,app_id,submit_time
     
            ) VALUES    (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ), (
            ?,
            ?,
            now(),
            now(),
            0,
            ?,
            ?,
            ?,
            ?,
            ?,
            now()
            ) ::: [[system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 1PF0ik64O20Qm4er2VG8eANjQbVvAm0Dt, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, GQlJUjeP6bIClvRDAVWcWWmRUEY3jS5h4, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 4RSKPMxnExf55dBWe02WIyMTQoBJm5zYv, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 0oCyF7XbPeqctxKzE73rCFbJFVqnG0hOr, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ae8qDFTC9099wgEtmibV9ZJyDfmZNagS9, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, hy7cqlZKG0trtfyp1rvbITZ3KG7ZLk4AB, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, gKbLV4pq74dxSVHu8CCqiTjJ1XoDFwg7c, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, yKKax6CEKBkkxEjlAZ3R3aRdc0lZOY3G2, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, wLdOde0EEF3c0RVX6iM3Y4ivagnPyT3FP, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 4Lj5O3E0FkGvUI5HFqvV9KfiBxYqv8ETY, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, COqs7Ss8GBwgClMCrsK9qiG9VONkJKi6o, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, h3KhokXjc8XrQlprg3Kyg9yNGUfEUu6XC, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, xu9OUSFIIJ9k9gipEKADDJ3ntNIzqOb7Y, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, GV6imIM8zekyEvSavR9nnMhhaUxoiHyyN, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, eQWJCYVPlttHeovVML31WeRaixjhngocx, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, O7VmaYBL2Yxw3509xTf3hy00OcU3dvtd3, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, j6eGbh0Le858Dybcr70Z0QkqmLL8yV7wk, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, bXpGxviRiUrNcnqimFwKTKOpWu3MBtodd, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, OrlziQxSPa5NDm0P4MHXA9uNjdlyK29Jk, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, fTxZeDOEjfXkkK0GWMQvGzHfYxonACfra, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Hn4SKGu6KArJ5rr1jReWoHZh5Mn8jbEf6, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, VdiKRO4eeGGrjLZxDDoiCnhlxIVDH5pUE, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ajm1IovxfalBnbRzm5o4ukDY3Byvacoyd, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, JpCtscSNarbsnG5rhHMXQj6SVa9WkpSFd, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 6hn2YlSelGQSNMj2dFsykWz0vQ20ZrqQ0, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, S5ZExKRorkNe6oroNTeTOwrG2DLJ1Tlua, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, XhB8yJ84f7MekDRiFtuMM5YFE4SBSsVOR, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, yx3rqKPLggqpYUPwprIpNzFTC9pi7YjKD, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ljcdCOXVmNfbkxHqUZj0qGSFTAOrayfk2, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, enTVHA5mjhRXp3WZxobWcitcaWPDGMHNz, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Pk1ow0QebOSLK3tCUrIz1tPcrCpmQ5RrC, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, snRAvdV7cfEw2PSX0HeZ7leMmAZTyjLOy, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, gskIVCUCx5du9r9IvsSbL5sKoAxb8jiRV, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, zINZqWVhu28SUyXmHuvsgFTkqhHSDYHEW, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Yl1CWIsYyvFnucsa3JCMxo7W2o5o1uFP0, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 28l6D61nSU8P06PCillFN8tkhuboN0DBH, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, U76DhVj42Fuhzl8TekAx4S3ESbVf6SOkl, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, kxu3vOCG4FihBEC6uaAqDksAZiZYgMV7p, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, uh8R7ulqdAXzIZ1qtbZGkLHRilCuzs0Qz, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, IUtTLgJ8txUFGqpUq4fiESAyUXQkSZ4Fx, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, lO0FEvkHRqrdjeG3VKOGOkkHW4xrd4W3u, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ZUNUMni3KJMRx3ME6Hpkj1wIjidSsNgv4, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, n4TLlmh3KrTnHTRuVCD0Cu2JxppMDN9xc, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Z8wvCMqGIp0gEk90aFRHMG9gTn9mcQMIB, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, taVsbbeM9YWfsW1GpQmg2vYuKmJzu4Qxq, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, I9mt4oHL4aYu37ZS5AigLCcM2I2Xf4qcU, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, xtUbxduwhWuljNbhMwagIUxL3AIdGmxHY, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, GL7g5VVKd2zL9gteUrkofDYrVfZi1MH3W, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 95zhh1eG0S3lirlaRX0hezjuGWouQLRvL, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 0DfYHksoBbtKU4cUD4O0VBoiEnEuPIBYM, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 4wwJqmugO2UwNzzDhBjX5pS0edf70bKLa, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, BQPMfiJiKg2uSqBKOsGGVYtmDq0kIw0lp, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, yEPsUSqW8xpdxqnvif3bccH9JVi3iFepy, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, h5mlMI6Z4fCzIujsx8tCEZtHMan9FP5oO, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Bq9YHZQrLAxGAV18BkOe7laS8yhe6pSuC, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, rA8JsRAQfUgFIUSfvcueWFA99JVMMosmD, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Ne8r3RLvG8QyjLSwF0UtoLmu9xS5tYM8J, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, vPc6INQ6Bn8jMNU8hofqPCdNRiNVSIpkP, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, kRk0OIL0BP1LrsFAsUXXe4wdrTRase717, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, C9yzq9S6UfcrYyMyId1as5NmGAlxQaR6o, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, RIHwMCEDTCRDNe8t49OUwnXTZrYQRwk6E, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, EncxL4uyLdUUG91Ft1fIEWOI7450AckZi, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ZB2ORa5cUFGWbC5DX87NQaZL98y3d3KJF, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 3beAmKYwDIomL4r5T91WuD280rK3RKTH9, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, gV1lzDV72rIr8pfIHDua8bsJ07rO5KkD2, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, NgSnlxjSfWuYHDAh4wF9PH4SOkmzkE7cj, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 6SLJoTKyATGQyRTZCBLpe0hsrwHyB2ANW, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, K69DV6Zs85LioyqxLSV3uIgjJg1nGFFuG, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, PlcMbNRHiBS2VbDMA2jDuzokFt4VaJPRU, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, lWdJiXkEvXTQ4lA2G70LqO6sKSv3PVwTX, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ycG4XEuTb9p6hXYQwddDNsDcBgj5cyX17, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, PPaslfMqESGCLnGOb60hgQ20TH60oS6DJ, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, SCw7NFiW0FwAbbe9oa2RwXyAq6sY60cUb, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, c7i0DXE85TIpyISl2aDD5sLdoyp076YmT, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Lsw6pLcHfzM7Tzk2ZoLZAYIB9sjfWezKv, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, cfJ3klc2dNCpJkV4g7p7We6C1Wtngq7BH, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ztUTo6VLqPBnTj93xy7mQbOHyMm5p3KCW, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, RDbFdLw7KngZcw8XklKX7hpup3r3kmRGE, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, WOrvMqsEYGTDOaAfxQp8MtpbG2bka8U8b, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 6d8muZWPLQ8E5sEEpLCayR1FmWEwPjKPA, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, FHaMxVb5BHVhqqQNgP6gLDRMqVTnlRAeu, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ZiRJiY2mb3RvRM1Guwpc9RMVhUq3x6MvJ, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 8DAJ2IfXijUliRQTfM0jGkBiQob0gOCtv, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 72vNY0Fj0CrADFeuJclxTPNjoVGIN6nyB, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, LzCUlVX3lewpPaAbjXCloDsJ9YFbAtCLT, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, 8qVsXHG6ZGptdVUSYuQ0ldqCxdivVwekT, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, CYaztsH1dSAdnKvlFQFeMbDumEjdAhH1n, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, xnNutAqGCSuOinYE0Cy73lbnAtiljZ2JK, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Ll0spYYaXeBxpK7OFd50uSl9nek84wZdf, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, nsgwWNvENvZGsdti25uBbQFJBH0tGFkG5, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, Gt3CjoBlBIkUwIwAKSCzH9OC9LYk3dCZ9, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ZysHLTDadvTBnGGVQge7lO3pdwHAsiaMq, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, TkjmOLvzoQeWL2yXsc7Jrh7923cuaS0O7, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, tIoUQvLXctvn0enWCUaSwni1g4WQljxrQ, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, vhO3nug3giGfhjodnYlHl8jUESzKOpZbK, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, YYmAX3EsQ3AAP6kD25RNIbyBaV9dzjbUA, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, f2Ieq5aHFUkgcwiOXR7KdwlcikorzapMA, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, YbEnqLkbKeH4I7DQHOsGVL3kTf086c6Gc, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, ZECWaG9QzZ6nXLWpthqQceGcp7CfNJ1ak, 1, 1, wx462866902173e846, system, system, 6DVKS1NHV7KcvdEQASxfZf0vLsbL, bwPpz7zbGezIE32XRZUtTg5cmNHz03N5m, 1, 1, wx462866902173e846]]`

**Comment by kofkyobsa** [comment]
![image](https://user-images.githubusercontent.com/2143295/57193119-7021f180-6f6a-11e9-8d7d-4dce57cd3c0b.png)

**Comment by tuohai666** [comment]
How many MySQL instance? And what's your hardware environment?
Generally, you can adjust properties for:
  max.connections.size.per.query: 1(to 32)
  acceptor.size: 16(to 128)  # The default value is available processors count * 2.
  executor.size: 16(to 128)  # Infinite by default.
The ideal value of the properties depend on your hardware.

**Comment by kofkyobsa** [comment]
MySQL instance number：1
  max.connections.size.per.query: 1
  acceptor.size: 16
  executor.size: 16

**Comment by tuohai666** [comment]
Try to adjust properties for performance improvement.

**Comment by tuohai666** [comment]
1. I wonder what's the QPS for this scenario without Sharding-JDBC before.
2. Can you turn on sql.show and show me the log?

**Comment by kofkyobsa** [comment]
I changed the max.connections.size.per.query to 8 ,the acceptor.size to 32 ,
and it's ok now, up to 5000 qps;
thanks!!!
