### ISSUE TITLE
  When sharding is not required, can SQL checking and validation skip？ 

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#2321]
For example：
insert into the_biz(id,ser_id,biz_time) values (1,1,now())

NoneShardingStrategy is default for no sharding tables,but error occurs .because of sql checking?
When in no-sharding table cases,could we make shardingsphere look like it doesn't exist?

**Comment by terrymanu** [comment]
The 3rd generation parse can support all SQL. 
It is worked on #2084.
So may I mark this issue as duplicated?

**Comment by childewuque** [comment]
> The 3rd generation parse engine can support all SQL.
> It is worked on #2084.
> So may I mark this issue as duplicated?

Thanks ,now i use the version shardingsphere and the below sql ,but error occurs. Isn't it the 3nd generation parse engine in 4.0.0-RC1?

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>

insert into the_biz(id,ser_id,biz_time) values (1,1,now())

 Data truncation: Incorrect datetime value: 'now()' for column 'biz_time'

**Comment by terrymanu** [comment]
No, it still on working, probably finished at 4.0.0-RC2

**Comment by childewuque** [comment]
OK，I wait for 4.0.0-RC2.
Thanks.
