### ISSUE TITLE
The SQL of select id, count(*)/100 from t_order group by id throws exception.

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#2326]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding proxy
### Expected behavior
The SQL of select id, count(*)/100 from t_order group by id can run properly.
### Actual behavior
The SQL of select id, count(*)/100 from t_order group by id throws exception.
> ERROR 10002 (C1000): 2Unknown exception: [Can't find index: AggregationSelectItem(type=COUNT, innerExpression=(*), alias=Optional.absent(), derivedAggregationSelectItems=[], index=-1), please add alias for aggregate selections]

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/79137190-d652fd80-7de4-11ea-9581-897d1f20fe00.png)

It's okay now.
