### ISSUE TITLE
ParsingResultCache should be cleared when sharding data source was reconstruct

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#2328]
## Bug Report

When we try to reconstrcut the sharding data source because of the table sharding state has been changed.(from not sharding to sharding)
the ParsingResultCache was not cleared because it is static instance and not associated with the sharding data source.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
ParsingResultCache for sql will be clean
### Actual behavior
not clean
### Reason analyze (If you can)
1.create a sharding data source
2.use sql "select count(1) from xxx where a = 'x'", now xxx table is not in sharding
3.do table sharding in the database and reconstruct sharding data source without restart
4.the route result is not correct, still to all the shards

**Comment by cherrylzhao** [comment]
@lalicw we have fixed it in 4.0.0, the lifecycle of parsingResultCache is same with `ShardingContext`

**Comment by cherrylzhao** [comment]
fix at #1877
