### ISSUE TITLE
While using database,it will select a random database!!!

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2331]
the logs likes that:
First use database:
![20](https://user-images.githubusercontent.com/34736778/57217009-082fe180-7024-11e9-90fc-b8ebeff438c3.png)
Second use database:
![21](https://user-images.githubusercontent.com/34736778/57217050-25fd4680-7024-11e9-9231-f50c7c65d7af.png)

the sharding-proxy version is 4.0.0-RC2-SNAPSHOT.

**Comment by cherrylzhao** [comment]
thanks for reply. I have analyzed it in #2301

**Comment by cherrylzhao** [comment]
- [ ] add DataSourceGroupBroadcastRoutingEngine for show xxx
- [ ] refactor RoutingEngineFactory of DAL

**Comment by cherrylzhao** [comment]
@tianyijushi I have fixed this issue, you can verify it again.

**Comment by cherrylzhao** [comment]
close this issue for no response more than 7 days.
