### ISSUE TITLE
Springboot jap query results totalElements and totalPages are wrong

### ISSUE THREAD

**Issue by windlikeman** [apache/incubator-shardingsphere#2332]
方法
PageRequest pageRequest = PageRequest.of(1, 10);
Page<SysRole> sysRoles = sysRoleRepository.findAll(pageRequest);

result is：
"totalElements":20,"totalPages":2
但是数据库明明就14条数据
数据库postgre SQL

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
