### ISSUE TITLE
Support distributed transaction by integrating seata.

### ISSUE THREAD

**Issue by ujjboy** [apache/incubator-shardingsphere#2335]
## Feature Request

[Seata: Simple Extensible Autonomous Transaction Architecture](https://github.com/seata/seata) is an easy-to-use, high-performance, java based, open source distributed transaction solution.

It provides several distributed transaction solutions: AT(FMT)、TCC、XA

Can we integrate `Seata` as a kind of distributed transaction implementation in sharding-sphere/sharding-transaction?

**Comment by terrymanu** [comment]
Welcome Seata's committers to discuss how to integrated with ShardingSphere.
I will add more design details later

**Comment by terrymanu** [comment]
Basic tasks:
- [ ] Add a new module name as `sharding-transaction\sharding-transaction-base\sharding-transaction-seata-at`
- [ ] Implement SPI `ShardingTransactionManager`with Seata's transaction API

Enhancement tasks to be discuss further:
- [ ] Define a new interface and SPI for SQL AST result on Seata, ShardingSphere will implement this SPI to assemble AST, to avoid parse SQL twice
- [ ] Think about how to use same configuration of register center to distribute for Seata and ShardingSphere,  to avoid user configure twice

**Comment by terrymanu** [comment]
![image](https://user-images.githubusercontent.com/5516298/57267046-360f3780-70b1-11e9-9cb7-c32a98a957f1.png)

**Comment by slievrly** [comment]
Note that the java version used by Seata is openjdk 1.8.

**Comment by terrymanu** [comment]
@slievrly yes, it is a problem, we prefer use SPI to import Seata and let end user to provide jdk version

**Comment by cherrylzhao** [comment]
we have made a design for `using Seata AT transaction in ShardingSphere`
![image](https://user-images.githubusercontent.com/8317649/57828370-df56db80-77dd-11e9-9c86-103787cb5f56.png)
After we completed the `SeataShardingTransactionManager`, we will consider about
- Design Revert SQL SPI to avoid parsing SQL twice between Seata and ShardingSphere
- Integrating ShardingSphere between micro-service using Seata AT Transaction

**Comment by cherrylzhao** [comment]
Enhancement tasks to be discuss further in other issues.
