### ISSUE TITLE
which repository can find version 3.1.0.1?

### ISSUE THREAD

**Issue by gdouyang** [apache/incubator-shardingsphere#2339]
i have same question like bug #1722, i find this bug is fixed at version 3.1.0.1, but i can't find this version at `https://mvnrepository.com`. Please tell me where can I download to version 3.1.0.1?

thanks!

**Comment by cherrylzhao** [comment]
we have submit several PR for this issue, in factor, 4.0.0-RC1 is OK.

**Comment by terrymanu** [comment]
We never release this version
