### ISSUE TITLE
How to dynamic table in v3.1?

### ISSUE THREAD

**Issue by tiannet** [apache/incubator-shardingsphere#2341]
For example, I created tables like  t_20190101,  t_20190102 ,  t_20190103... , there is a column date which value like 20190101, 20190102, 20190103...

How can I insert data to they by column date value ?

**Comment by terrymanu** [comment]
Hi, maybe you can search closed issue first, somebody ask same question before

**Comment by terrymanu** [comment]
I will close this issue soon if no response any more

**Comment by terrymanu** [comment]
Closed cause by no response any more
