### ISSUE TITLE
Sharding-proxy Query result :extraneous data in "D" message ,reason: have chinese

### ISSUE THREAD

**Issue by bxvs888** [apache/incubator-shardingsphere#2343]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy 
### Expected behavior
table data have Chinese .select * from table show error message :
extraneous data in "D" message
### Actual behavior
proxy backend POSTGRES , frontend postgres 
### Reason analyze (If you can)
reason Chinese , Postgres server_encoding ,client_encoding UTF-8
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
any table ,have Chinese is error.
### Example codes for reproduce this issue (such as a github link).

**Comment by tuohai666** [comment]
What is your OS? MAC, Linux or Windows?

**Comment by tuohai666** [comment]
> What is your OS? MAC, Linux or Windows?

I found that it is not encoding but a protocol problem.

**Comment by bxvs888** [comment]
MAC, linux 都测试过，都是这样。

**Comment by tuohai666** [comment]
@bxvs888 fixed in 4.0.0-RC2-SNAPSHOT
