### ISSUE TITLE
mysql client can't get the proxy configuration dynamically.

### ISSUE THREAD

**Issue by duanbin0414** [apache/incubator-shardingsphere#2346]
after zk update proxy configuration  and add new schemas,mysql client could not Automatic access to，unless restart proxy. version 3.0.0

**Comment by terrymanu** [comment]
Can you modify the title to make it more make sense and search friendly?

**Comment by duanbin0414** [comment]
Let me take a screenshot of my problem
![1](https://user-images.githubusercontent.com/50389867/57420157-d17ee480-7238-11e9-9ac7-b06c051574ed.jpg)
![2](https://user-images.githubusercontent.com/50389867/57420166-e65b7800-7238-11e9-90a9-c17c30726821.jpg)
picture 1.2,is my add configure in proxy registry zk node
![3](https://user-images.githubusercontent.com/50389867/57420203-1b67ca80-7239-11e9-9194-01b3f419ce37.jpg)
mysql client can't get the configuration dynamically.
Only I reboot shardingProxy,mysql client Access to the schema that i configured.
![4](https://user-images.githubusercontent.com/50389867/57420341-aba60f80-7239-11e9-8340-844ec6750f82.jpg)

**Comment by terrymanu** [comment]
What I mean is the ***title*** of this issue. This title does not make since.

**Comment by duanbin0414** [comment]
> What I mean is the _**title**_ of this issue. This title does not make since.
> The title `shardingProxy issues` is too generic.

Is the title ok

**Comment by tristaZero** [comment]
Thanks for your pictures to make this issue clearer, can you use 4.0.0-RC1 or 3.1.0 to test this issue?
We fixed this problem in the next version of 3.0.0.
@duanbin0414

**Comment by tristaZero** [comment]
Hi, are you there?
