### ISSUE TITLE
4.0.0 RC1 ComplexKeysShardingAlgorithm not support between... and?

### ISSUE THREAD

**Issue by xllove-moon** [apache/incubator-shardingsphere#2347]
## Question
sql like :
SELECT COUNT(id)  FROM table_a  WHERE  id in(...) and create_date between ? and ? 

it reports an exception:
Error querying database.  Cause: java.lang.ClassCastException: org.apache.shardingsphere.core.strategy.route.value.BetweenRouteValue cannot be cast to org.apache.shardingsphere.core.strategy.route.value.ListRouteValue

because 3.1 not support some sub query and 4.0 fix this problem ,so i want upgrade ,but this new problem make us awkward....

**Comment by terrymanu** [comment]
No, they are not supported

**Comment by superjinxiao** [comment]
well, the document is written as follows "ComplexShardingStrategy provides support for the sharding operation of =, IN and BETWEEN AND in SQL." Is there a misleading?
