### ISSUE TITLE
While inserting has error,then the sharding-sphere process is stuck!

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2350]
like the title!
![22](https://user-images.githubusercontent.com/34736778/57364449-cdf64980-71b5-11e9-987e-67f060a37861.png)
version:apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin
Everytime ,error has happened,or sometimes rollback has happend,the process is stuck.then I cannot connect the sharding-proxy with mysql command and navicat.

**Comment by cherrylzhao** [comment]
thanks for feedback, it seems that same with #2356, I will  enhance it today.

**Comment by cherrylzhao** [comment]
I have made a enhance at #2356, would you please make a test again using `dev` branch

**Comment by cherrylzhao** [comment]
close this issue for no response more than 7 days.
