### ISSUE TITLE
使用3.1.0版本，每次执行完SQL都会执行HintManagerHolder.clear方法？

### ISSUE THREAD

**Issue by liunancun** [apache/incubator-shardingsphere#2353]
使用3.1.0版本，每次执行完SQL都会执行HintManagerHolder.clear方法？

这样使用HintShardingAlgorithm的时候，每次执行SQL之前都需要设置HintManagerHolder，我一个Dao里面执行多条SQL，或者一个service里面执行多个Dao方法，想通过AOP拦截的形式在调用方法之前设置HintManagerHolder，调用方法结束后执行clear，没办法实现

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
