### ISSUE TITLE
With version 3.1.0, the HintManagerHolder.clear method is executed each time SQL is executed?

### ISSUE THREAD

**Issue by liunancun** [apache/incubator-shardingsphere#2354]
With version 3.1.0, the HintManagerHolder.clear method is executed each time SQL is executed?

When using HintShardingAlgorithm, you need to set HintManagerHolder before executing SQL. I execute multiple SQL in Dao, or execute multiple Dao methods in a service. I want to set HintManagerHolder in the form of AOP interception before calling the method. Execute clear after the end, there is no way to achieve

**Comment by terrymanu** [comment]
@cherrylzhao just check it is duplicated or not

**Comment by cherrylzhao** [comment]
we have enhanced it in 4.0.0-RC1, you can see #2164

**Comment by liunancun** [comment]
4.0 When is the official version issued?

**Comment by cherrylzhao** [comment]
maybe within 2 months.
