### ISSUE TITLE
About select for update

### ISSUE THREAD

**Issue by herryliq** [apache/incubator-shardingsphere#2355]
## Question
Which type will be judged with the sql like follows in shardingsphere.
`select tbl.next_val from hibernate_sequences tbl where tbl.sequence_name=? for update`

I use the previous version io.shardingjdbc that version is 2.0.3, in this version, 
the below sql will be judged with DQL, in my application environment, the slave
database was read only, so when execute the above sql, database will throw a exception.

**Comment by terrymanu** [comment]
Duplicated with #1496
