### ISSUE TITLE
When routing to only one table, can it do not rewrite limit?

### ISSUE THREAD

**Issue by jasonlong10** [apache/incubator-shardingsphere#2360]
As shown below：
![image](https://user-images.githubusercontent.com/5526521/57437171-ceedb080-7273-11e9-8f90-6aa7625d620c.png)

If RoutingResult can routing to only one table, it is not necessary to rewrite limit and offset.

It can change like this :

> if (sqlStatement instanceof SelectStatement && null != ((SelectStatement) sqlStatement).getLimit() _**&& routingResult.getTableUnits().getTableUnits().size() > 1**_) {
            processLimit(parameters, (SelectStatement) sqlStatement);
        }

**Comment by tuohai666** [comment]
Fixed. Please refer to #2062 #1759 #1722 #1672 #1643

**Comment by jasonlong10** [comment]
fixed in which version？ @tuohai666

**Comment by jasonlong10** [comment]
I see it in dev branch. When will it be released?

**Comment by tuohai666** [comment]
> fixed in which version？ @tuohai666

Fixed in 4.0.0-RC1 which is already released.
