### ISSUE TITLE
about 11000000 data insertion，just find 21000data success，there is no any errors i could find.

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2361]
4.0.0-RC2

    face:
      actualDataNodes: ds_5.face_${0..19}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: face_${id % 20}
      keyGenerator:
        type: SNOWFLAKE
        column: id

**Comment by cherrylzhao** [comment]
please tell us more details, sharding-jdbc or proxy? transaction type? python client or java?
and how can we reproduce it?

**Comment by terrymanu** [comment]
@tianyijushi Hi, summit a issue without necessary information can not help us to reproduce it.
Can you provide more details can let us and other interested one to reproduce and try to analyze it?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
The information you that provided is not enough.
