### ISSUE TITLE
Method "SnowflakeShardingKeyGenerator.setWorkerId()" is missing

### ISSUE THREAD

**Issue by jasonlong10** [apache/incubator-shardingsphere#2368]
In current dev branch, method "SnowflakeShardingKeyGenerator.setWorkerId()" is missing.

![image](https://user-images.githubusercontent.com/5526521/57593700-4753ba80-756f-11e9-8791-309f30d6ecff.png)

**Comment by jasonlong10** [comment]
Method "SnowflakeShardingKeyGenerator.setMaxTolerateTimeDifferenceMilliseconds" is also missing.

**Comment by jasonlong10** [comment]
This class is not complete ?

**Comment by terrymanu** [comment]
We are change distributed key's api, please read document first
