### ISSUE TITLE
In single project, how to realize using sharding-jdbc in sharding scenario, but don't use sharding-jdbc in none sharding scenario.

### ISSUE THREAD

**Issue by bigkun** [apache/incubator-shardingsphere#2378]

**Comment by wenweibin** [comment]
You can get connection from ShardingDataSource(shardingjdbc) in sharding scenario, but fetch connection from other normal DataSource(dbcp、hikariCP、druid...) in non-sharding scenario

**Comment by terrymanu** [comment]
You can create more than one different datasource on your application as you want

**Comment by bigkun** [comment]
We use mybatis in our springboot project.  I don't known how to configure it .  normal tables use normal mybatis connection; sharding tables , mybatis can work with  sharding-jdbc.

**Comment by terrymanu** [comment]
How to config multiple data source on Mybatis and springboot are Mybatis and springboot's issue.
Can you google first?
If cannot find way, you can try to search for stackoverflow or talk on  springboot or Mybatis's issue
