### ISSUE TITLE
3.0.0不支持条件是name的关键字条件查询

### ISSUE THREAD

**Issue by abcwangjingjing** [apache/incubator-shardingsphere#2383]
sql：select * from 表名  where name = '全局配置' ，
数据库里这条能查出来，但是使用sharding是查不出来的，name 加不加那个引号都不行。而name改成id就可以。
以下写法均不行:
select * from 表名 t  where `name`= '全局配置'
select * from 表名 t  where t.`name`= '全局配置'
select * from 表名 t  where t. name = '全局配置'

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
