### ISSUE TITLE
使用sharding-proxy分库分表之后，使用PageHelper插件查询一对多数据，返回记录条数不正确

### ISSUE THREAD

**Issue by haj8888888** [apache/incubator-shardingsphere#2385]
代码如下：
![image](https://user-images.githubusercontent.com/15724396/57768484-4fae2000-773e-11e9-8d86-db3352e30d0f.png)
![image](https://user-images.githubusercontent.com/15724396/57768498-58065b00-773e-11e9-915b-f3e8c6ff1d95.png)
返回如下
[DEBUG] 2019-05-15 18:18:58,167 --main-- [com.mec.dao.OrderDao.selectByJoin_COUNT] ==>  Preparing: SELECT count(*) FROM t_order t JOIN t_order_item ti ON t.order_id = ti.order_id  
[DEBUG] 2019-05-15 18:18:58,228 --main-- [com.mec.dao.OrderDao.selectByJoin_COUNT] ==> Parameters:  
[DEBUG] 2019-05-15 18:18:58,243 --main-- [com.mec.dao.OrderDao.selectByJoin_COUNT] <==      Total: 1 
[DEBUG] 2019-05-15 18:18:58,244 --main-- [com.mec.dao.OrderDao.selectByJoin] ==>  Preparing: SELECT t.*, ti.order_item_id as a_order_item_id, ti.order_id as a_order_id, ti.user_id as a_user_id, ti.`status` as a_status FROM t_order t JOIN t_order_item ti ON t.order_id = ti.order_id limit ?,?  
[DEBUG] 2019-05-15 18:18:58,247 --main-- [com.mec.dao.OrderDao.selectByJoin] ==> Parameters: 0(Integer), 2(Integer) 
[DEBUG] 2019-05-15 18:18:58,255 --main-- [com.mec.dao.OrderDao.selectByJoin] <==      Total: 2 
[INFO ] 2019-05-15 18:18:58,256 --main-- [com.mec.order.test.ShardingProxyMybatisTest] Order{orderId=1557913094808, userId=688, status='ON', orderItemList=[OrderItem{orderItemId=1557913094807, orderId=1557913094808, userId=688, status='OFF'}, OrderItem{orderItemId=1557913094808, orderId=1557913094808, userId=688, status='ON'}]} 
![image](https://user-images.githubusercontent.com/15724396/57768658-b4697a80-773e-11e9-9cdd-91120428cf89.png)
数据库结果集：
![image](https://user-images.githubusercontent.com/15724396/57768780-ee3a8100-773e-11e9-9cb9-d1298e20557a.png)

问题详细描述：使用join分页查询时，数据关系1对多，查询返回记录条数不正确，预期返回2条记录，时间返回一条数据，实际应该返回2条order数据
数据库

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
