### ISSUE TITLE
can I not use sql parse?

### ISSUE THREAD

**Issue by DaC1989** [apache/incubator-shardingsphere#2392]
## Question
sometimes sql parse do not support my sql:
`org.apache.shardingsphere.core.parse.exception.SQLParsingUnsupportedException: Unsupported SQL of begin`
but i need it work. is there some way to avoid sql parse?
**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
We have no plan to support some customized requirement

**Comment by DaC1989** [comment]
Maybe it's not a customized requirement.
When sharding-jdbc can't support any sql, we can pass sql parse.
But now, I have to write jdbc connection.This is not graceful

**Comment by terrymanu** [comment]
How to sharding if pass sql parse?
