### ISSUE TITLE
sharding-jdbc的4.0.0-RC1版本，key-generator.column最终赋值给了另一个非配置的字段

### ISSUE THREAD

**Issue by kobeguang** [apache/incubator-shardingsphere#2400]
druid+mybatis
入库的时候，一个vo有几十个字段，差不多10个左右是not null的，我把所有not null的字段都写入了vo，然后入库，debug发现自增主键赋值给了另一个属性（而不是我配置的id属性），我对该vo多对vo某一个其他属性赋值，就发现没有这个问题了。请问是不是bug啊？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by hanxuewen** [comment]
我遇到了相同的问题
