### ISSUE TITLE
saga transaction error

### ISSUE THREAD

**Issue by thineagle** [apache/incubator-shardingsphere#2418]
i try to use saga transaction,  when something wrong , i rollback transaction manually ， but some tables data has already been commited

**Comment by cherrylzhao** [comment]
please tell us more details, version? saga config?

**Comment by thineagle** [comment]
vesion 4.0.0-RC1 , saga version 0.3.0 , saga config如下
 `#Saga引擎所使用的线程池大小
saga.actuator.executor.size=5   
#Saga引擎所使用的线程池大小
saga.actuator.executor.size=5
#Saga引擎对失败SQL的最大重试次数
saga.actuator.transaction.max.retries=5

#Saga引擎对失败SQL的最大尝试补偿次数
saga.actuator.compensation.max.retries=5

#Saga引擎对失败SQL的重试间隔，单位毫秒
saga.actuator.transaction.retry.delay.milliseconds=5000

#Saga引擎对失败SQL的补偿间隔，单位毫秒
saga.actuator.compensation.retry.delay.milliseconds=3000

#Saga引擎对快照及执行日志进行持久化
saga.persistence.enabled=false  

#Saga引擎对失败事务的补偿策略，ForwardRecovery为最大努力送达，BackwardRecovery为反向SQL补偿
saga.actuator.recovery.policy=ForwardRecovery`
sql is common sql , insert into tables(column,column) values('value','value) , like this
after the sql , our business program throw some exception , then invoke rollback,  but the value has been  insert the table

**Comment by cherrylzhao** [comment]
please use BackwardRecovery policy, forwardRecovery policy will not do revert in 4.0.0-RC1.

**Comment by cherrylzhao** [comment]
we have optimized the policy in dev branch, SagaTransaction will select the policy automatic.

**Comment by thineagle** [comment]
ok ， i will try again

**Comment by cherrylzhao** [comment]
any feedback for this issue，can you close it？

**Comment by thineagle** [comment]
i will use BackwardRecovery  try again
