### ISSUE TITLE
Spring boot starts loading data source asynchronously?

### ISSUE THREAD

**Issue by jimmycheng888** [apache/incubator-shardingsphere#2420]
**In the case of multiple data sources and very many shards (for example, I have 100 or even more data source shards), the data source is loaded very slowly. I hope that the program can take advantage of the cpu multithreading feature. Use the Future mode to asynchronously load the data source, reducing the time to start the program.
The version number I am using is 3.1.**

**Comment by cherrylzhao** [comment]
I think you can try to adjust the `max.connections.size.per.query` parameter or make`check.table.metadata.enabled=false`

**Comment by jimmycheng888** [comment]
> I think you can try to adjust the `max.connections.size.per.query` parameter or make`check.table.metadata.enabled=false`


Nín hǎo, zài nǎlǐ pèizhì? Bù tài míngbái
13/5000
Hello, where is the configuration? do not understand

**Comment by jimmycheng888** [comment]
> I think you can try to adjust the `max.connections.size.per.query` parameter or make`check.table.metadata.enabled=false`

Still no substantial performance improvement, or as slow as a turtle, I hope this problem can be optimized in subsequent versions.

**Comment by KomachiSion** [comment]
What's your database? and Which connection pool you used?

**Comment by KomachiSion** [comment]
@jimmycheng888, Can you provide your database type(MySQL, Oracle, PostgreSQL or others), and Which connection pool you used?

And you can try to upgrade to 4.0.0-RC1. This version has some enhancement for this problem.

**Comment by jimmycheng888** [comment]
The database I use is PostgreSQL, the database connection pool is HikariDataSource, and there are too many connection pool threads in multiple data sources. Will it affect the production environment?

**Comment by jimmycheng888** [comment]
> @jimmycheng888, Can you provide your database type(MySQL, Oracle, PostgreSQL or others), and Which connection pool you used?
> 
> And you can try to upgrade to 4.0.0-RC1. This version has some enhancement for this problem.

The database I use is PostgreSQL, the database connection pool is HikariDataSource, and there are too many connection pool threads in multiple data sources. Will it affect the production environment?

**Comment by KomachiSion** [comment]
> The database I use is PostgreSQL, the database connection pool is HikariDataSource
About PostgreSQL and Oracle, ShardingSphere will get all tables in datasource even these tables are not sharding tables. The problem has fixed in 4.0.0-RC1, I suggest you upgrade.

> There are too many connection pool threads in multiple data sources. Will it affect the production environment?
You can set `maxSize` of connection pool to control the threads. it depends ability of your environment. From the current feedback, as long as the maxSize of connection pools is controlled properly, there will be no affect.

**Comment by KomachiSion** [comment]
@jimmycheng888, Any new information about this problem? If no more problems, can you close this issue?

**Comment by KomachiSion** [comment]
No response **more than 7 days**, close this issue.
