### ISSUE TITLE
请问什么时候可以优化 in 查询，

### ISSUE THREAD

**Issue by yaoyuandota** [apache/incubator-shardingsphere#2426]
![image](https://user-images.githubusercontent.com/48268070/58156864-af11b000-7ca9-11e9-9ea1-f1a8f9196781.png)
如果是分库分表，in 很多个id， 那么几乎所有的表都要执行 in (all id)。如上图文档所示，什么时候能优化呀

**Comment by hwuHarry** [comment]
同问

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by yaoyuandota** [comment]
ok.... When can we optimize 'in' query
for example： db1 (table_1, table_3, table_5), db2(table_0,table_2,table_4). sharding key is 'id'.
sharding role is 'id %6'。 We have 3 records : id = 1, id = 2, id =4 。 so the real sql is : select * from db1.table_1 where id in (1 ,2,3) , select * from db2.table_2 where id in (1 ,2,3), select * from db1.table_3 where id in (1 ,2,3). so much in，it is not necessary i think。 
if we do batchGetByids => in (.............), it will do in all tables, it is inefficient i think。

**Comment by yaoyuandota** [comment]
> **For English only**, other languages will not accept.


ok.... When can we optimize 'in' queryfor example： db1 (table_1, table_3, table_5), db2(table_0,table_2,table_4). sharding key is 'id'.sharding role is 'id %6'。 We have 3 records : id = 1, id = 2, id =4 。 so the real sql is : select * from db1.table_1 where id in (1 ,2,4) , select * from db2.table_2 where id in (1 ,2,3), select * from db2.table_4 where id in (1 ,2,3). so much in，it is not necessary i think。if we do batchGetByids => in (.............), it will do in all tables, it is inefficient i think。
--
