### ISSUE TITLE
Can we get the operation type of CRUD in current SQL when using routing algorithm?

### ISSUE THREAD

**Issue by lthaoshao** [apache/incubator-shardingsphere#2429]
When we use Sharding-jdbc (4.0.0-RC1) for partitioning, we may want to use the CRUD type of SQL as part of the partitioning condition.
For example, we divide the main database and the historical database. All the 'insert' operations are expected to be directly inserted into the main database. We will periodically migrate the data to the historical database. When querying, we will determine the route based on the time parameter and whether it is an insert operation. In a single library or in multiple libraries.
When we were using it, we found that the subinterface of 'ShardingAlgorithm' only contains the table name and the fragment column parameters and values, and can't get the CRUD type.
Can you support this feature?

**Comment by terrymanu** [comment]
If insert to main database, query from slave databases, you can consider about master-slave.
If query by periodically, design time during as a sharding key is better than judge SQL CRUD type.

**Comment by lthaoshao** [comment]
Yes, first of all, thank you for your response, what you said is very reasonable.
But the situation here may not be the same. We mainly want to put the data that may be changed frequently in the near future to the main database, while the historical database stores some data with less change probability, but there may be a need to modify the history library, such as a transaction order that occurs for nearly half a year. Suddenly a refund request was initiated, and the original order may be modified at this time, so the history library is not completely a read-only database.
We want the 'insert' operation to follow the specified route, while other operations are routed by key.

**Comment by terrymanu** [comment]
We are middleware developer, we don't care about business logic.

Master-Slave + Sharding can satisfied most of general requirement, we have no plan to add more complexity to increase end-user's understanding costs.
If we open an API to let user can sharding by SQL CRUD type, it is a big conflict with Sharding + Master-Slave, it will make more user confuse

**Comment by lthaoshao** [comment]
> Master-Slave + Sharding can satisfied most of general requirement, we have no plan to add more complexity to increase end-user's understanding costs.
> 
> If we open an API to let user can sharding by SQL CRUD type, it is a big conflict with Sharding + Master-Slave, it will make more users confused.

Thank you very much, we will think of other ways to meet our business needs.
