### ISSUE TITLE
Redesign hint database only route

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#2432]
Because of 3rd parse engine can parse all SQL, do not need skip parse.
So just remove hint database only route.

**Comment by tristaZero** [comment]
Here are the key points:
1. Delete DatabaseHintSQLRouter or move it to RoutingEngineFactory
2. No table rules, tableNames.isEmpty() in sqlstatement, how about UnicastRoutingEngine and StandardRoutingEngine?
3. Default datasource and defaultDatabaseStrategy?
4.Preconditions.checkState(!routedTables.isEmpty(), "no table route info") in StandardRoutingEngine
