### ISSUE TITLE
Mysql client operation proxy exception

### ISSUE THREAD

**Issue by duanbin0414** [apache/incubator-shardingsphere#2436]
proxy version 4.0
![image](https://user-images.githubusercontent.com/50389867/58240187-13517400-7d7d-11e9-8ae2-fad615aefe4a.png)
![image](https://user-images.githubusercontent.com/50389867/58240461-9672ca00-7d7d-11e9-8216-438e1612b11e.png)

![image](https://user-images.githubusercontent.com/50389867/58240382-76dba180-7d7d-11e9-89b2-2ddb9434acff.png)

**Comment by terrymanu** [comment]
The error message talk us: Cannot invoke method mod() on null object

If your sharding value can be null, avoid use null to call any method.
