### ISSUE TITLE
provide demo for spring boot 2.x 

### ISSUE THREAD

**Issue by iamzxj** [apache/incubator-shardingsphere#2439]
springboot2.0 demo???

**Comment by terrymanu** [comment]
We cannot develop all demos for all frameworks, and spring boot 2.x 's version is same as spring boot 1.x
If somebody want to contribute demo for spring boot 2.x, we are welcome.
We will open this issue for several days.

**Comment by edidada** [comment]
I will try it

**Comment by terrymanu** [comment]
@edidada Thank you, the pull request can be to https://github.com/apache/incubator-shardingsphere-example/issues
We have already spring boot 1.x's example: 
https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example
and
https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example

Please make spring boot 2.x and 1.x is really different if submit a pull request

**Comment by edidada** [comment]
Till now , I meet a problem like this https://github.com/apache/incubator-shardingsphere/issues/1247
 in the first glance， I thank I should change SpringBoot source code, any suggestions?

**Comment by terrymanu** [comment]
change SpringBoot source code? how to do it?

**Comment by terrymanu** [comment]
Does this article helpful? 
https://zhuanlan.zhihu.com/p/67911677

**Comment by terrymanu** [comment]
Starter for spring boot 2.x and 1.x is same, so I prefer close this issue, any feedback?

**Comment by terrymanu** [comment]
closed
