### ISSUE TITLE
'-Long.MAX_VALUE' in assertSetWorkerIdFailureWhenTooMuch() method is not reasonable

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#2442]
Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
incubator-shardingsphere version is ‘dev’

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
incubator-shardingsphere/sharding-core/sharding-core-common

### Expected behavior
In SnowflakeShardingKeyGeneratorTest.java, the path is:
incubator-shardingsphere/sharding-core/sharding-core-common/src/test/java/org/apache/shardingsphere/core/strategy/keygen/SnowflakeShardingKeyGeneratorTest.java.
In assertSetWorkerIdFailureWhenTooMuch() method.
The code in line "properties.setProperty("worker.id", String.valueOf(Long.MIN_VALUE));"

### Actual behavior
In the method assertSetWorkerIdFailureWhenTooMuch() of SnowflakeShardingKeyGeneratorTest.java
The code in line "properties.setProperty("worker.id", String.valueOf(-Long.MAX_VALUE));"

### Reason analyze (If you can)
I think using Long.MIN_VALUE is more reasonable than -Long.MAX_VALUE.

### Example codes for reproduce this issue (such as a github link).
https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-common/src/test/java/org/apache/shardingsphere/core/strategy/keygen/SnowflakeShardingKeyGeneratorTest.java

**Comment by tristaZero** [comment]
Hi, @wgy8283335 thanks for your issue.
Actually, the bounds of worker.id is `worker.id >= 0L && worker.id < WORKER_ID_MAX_VALUE`.
In this test case, although whether `Long.MIN_VALUE` or `-Long.MAX_VALUE` can make this case pass, but `Long.MIN_VALUE` is more accurate.
Thanks for your suggestion, if it is available, can you send a pull request to fix this issue?
Waiting for your reply.

**Comment by wgy8283335** [comment]
@tristaZero. OK, I can fix this issue.
