### ISSUE TITLE
Question about ORDER_BY_DERIVED_xxx

### ISSUE THREAD

**Issue by baisijian** [apache/incubator-shardingsphere#2447]
## Question
sharding-jdbc will add some colum into sql, eg:ORDER_BY_DERIVED_xx, AVG_DERIVED_COUNT_xx
I want to know why to add them? 
how can i get rid of them?
**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
no answer
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
no answer
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).
no answer

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
FIY: https://shardingsphere.apache.org/document/current/en/features/sharding/principle/rewrite/
