### ISSUE TITLE
I suggested that add this to FAQ doc

### ISSUE THREAD

**Issue by zhouchangjiang** [apache/incubator-shardingsphere#2450]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

when clone shardingsphere from github，my git report error like this：Filename too long unable to create file.
you can fix it by this git command:    git config --global core.longpaths true.
can you add this to FAQ doc?

**Comment by terrymanu** [comment]
Can you provide a pull request?

**Comment by zhouchangjiang** [comment]
Ok，I can do it ,I will finish it as soon as possible！

**Comment by terrymanu** [comment]
Expecting on this

**Comment by zhouchangjiang** [comment]
Hi @terrymanu ,I finish my  pull request  apache/incubator-shardingsphere-doc#188.

**Comment by terrymanu** [comment]
Thank you, already merged
