### ISSUE TITLE
force index primary

### ISSUE THREAD

**Issue by cuizhancong** [apache/incubator-shardingsphere#2452]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

i have sql like 'select a.* from a force INDEX (primary) inner join b  force index(toid_pushid) on a.id=b.id' ,but when i run project prompt  not exist 'primary_a' ,other index i can rename index_tableName,but primary key can not rename.

**Comment by terrymanu** [comment]
What database do you use?

**Comment by cuizhancong** [comment]
i use mysql version is 10.3.7-MariaDB,both of i use sharding-jdbc 3.0.0 and sharding-jdbc 3.1.0 were presented the problem

**Comment by cuizhancong** [comment]
#configuration
sharding.jdbc.config.sharding.tables.b.logicTable=b
sharding.jdbc.config.sharding.tables.b.logicIndex=to_id
sharding.jdbc.config.sharding.tables.b.actual-data-nodes=ds_master.b_${0..15}
sharding.jdbc.config.sharding.tables.b.table-strategy.standard.sharding-column=to_id
sharding.jdbc.config.sharding.tables.b.table-strategy.standard.precise-algorithm-class-name=com.java.shardingJdbc.tableAlgorithm.BTableAlgorithm

**Comment by terrymanu** [comment]
I never try to with MariaDB.
But I think maybe we don't support MariaDB now.

**Comment by terrymanu** [comment]
Another information I want to update is ShardingSphere don't change index for MySQL, it only change index name for PostgreSQL and Oracle because MySQL are permit user create same index name with different table.

So I guess your problem is not cause by this reason.

**Comment by cuizhancong** [comment]
OK ，that is mean say now ShardingSphere can not solve that problem and thanks all the same,looking forward to the new version.

**Comment by terrymanu** [comment]
What I mean is we need to find real reason of this problem. Use MariaDB cannot cause this problem. Do you want do more research?

**Comment by cuizhancong** [comment]
Yes , i think so,use MariaDB cannot cause this problem,it is SQLRewriteEngine make index like 'primay_a' ，but i find other question,the program will run to IndexFiller.class,execute fill(....) method,method codes is 
  public void fill(IndexSegment sqlSegment, SQLStatement sqlStatement, String sql, ShardingRule shardingRule, ShardingTableMetaData shardingTableMetaData) {
        IndexToken indexToken = sqlSegment.getToken();
        if (!sqlStatement.getTables().isEmpty() && null == indexToken.getTableName()) {
            indexToken.setTableName(sqlStatement.getTables().getSingleTableName());
        } else {
            indexToken.setTableName("");
        }

        sqlStatement.getSQLTokens().add(sqlSegment.getToken());
    };

 public String getSingleTableName() {
        Preconditions.checkArgument(!this.isEmpty());
        return ((Table)this.tables.get(0)).getName();
    };
when run  indexToken.setTableName(sqlStatement.getTables().getSingleTableName()) is get first table,but i have two tables, so second index will rewrite 'toid_pushid_a' and sql is error,as a matter of fact sceond index should be rewrite 'toid_push_b'

**Comment by terrymanu** [comment]
In dev, we just refactor this part, you may try again

**Comment by cuizhancong** [comment]
Thanks a bunch,i have try and discovery came into effect,expect stable release version.

**Comment by lifw555** [comment]
mysql 5.6 has the same error 

sharding 5.0.0 version
