### ISSUE TITLE
Move SQLToken from parse module to rewrite module

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#2457]
- [X] Add SQLTokenGenerateEngine & SQLTokenGenerator
- [x] Split SQLRewriter & ParameterRewriter
- [X] Move AggregationDistinctToken to rewrite module
- [X] Move Attachable to rewrite module
- [X] Move EncryptColumnToken to rewrite module
- [X] Move IndexToken to rewrite module
- [X] Move InsertAssistedColumnsToken to rewrite module
- [X] Move InsertColumnsToken to rewrite module
- [X] Move InsertGeneratedKeyToken to rewrite module
- [X] Move InsertSetAddAssistedColumnsToken to rewrite module
- [X] Move InsertSetAddGeneratedKeyToken to rewrite module
- [X] Move InsertSetEncryptValueToken to rewrite module
- [X] Move InsertValuesToken to rewrite module
- [X] Move OffsetToken to rewrite module
- [X] Move OrderByToken to rewrite module
- [X] Move RemoveToken to rewrite module
- [X] Move RowCountToken to rewrite module
- [X] Move SelectItemPrefixToken to rewrite module
- [X] Move SelectItemsToken to rewrite module
- [X] Move SQLToken to rewrite module
- [X] Move Substitutable to rewrite module
- [X] Move TableToken to rewrite module

**Comment by tristaZero** [comment]
All done
