### ISSUE TITLE
The influence of different configurations of data-masking/encrypt on show-SQL

### ISSUE THREAD

**Issue by fdlzp** [apache/incubator-shardingsphere#2466]
**Question Description：**

![图片](https://user-images.githubusercontent.com/44960833/58543510-2dce9600-8232-11e9-83f1-ec08f94b9ae5.png)
![图片](https://user-images.githubusercontent.com/44960833/58543559-45a61a00-8232-11e9-9034-6fd1cc487b2e.png)
![图片](https://user-images.githubusercontent.com/44960833/58543590-5191dc00-8232-11e9-9b8c-4228f2155bd7.png)

The configuration of picture-1  make the configuration of  picture-3 doesn't work.
The configuration of  picture-2 may not.

It has no effect on encrypt/decrypt.

**My environment：**

springboot + JPA + mysql +sharding-jbdc

**Which version of ShardingSphere did you use?**

4.0.0-RC1

**Expected behavior**

just show  sql

**Actual behavior**

cann't see sql be printed

**Reason analyze**

**Solution：**
Just config like picture-2，and wait for the next version 

Thank you!

**Comment by terrymanu** [comment]
Thank you for suggestion, does anybody want to do a pull request on this?

**Comment by zhouchangjiang** [comment]
Hi @terrymanu
I will try it, This is my preliminary idea.
1,Refactoring the constructor of [EncryptDataSource ](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/datasource/EncryptDataSource.java) and add java.util.Properties parameters, similar to [MasterSlaveDataSource](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/datasource/MasterSlaveDataSource.java);
2,Refactoring the createDataSource method of [EncryptDataSourceFactory ](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/api/EncryptDataSourceFactory.java) and add java.util. Properties parameters,similar to [MasterSlaveDataSourceFactory](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/api/MasterSlaveDataSourceFactory.java);
3,Refactoring the constructor of  and add  ShardingProperties parameters;
4,Modify the getSQLUnit method of [EncryptPreparedStatement ](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptPreparedStatement.java) to print the rewritten SQL log according to configuration information;
5,Modify the getRewriteSQL method of [EncryptStatement ](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/EncryptStatement.java) to print therewritten SQL log according to configuration information;

**Comment by terrymanu** [comment]
Ok, let @tristaZero to review it.

**Comment by tristaZero** [comment]
@zhouchangjiang Hi, i think your preliminary idea is great, you can have a try firstly. 
Moverover please consider different configuration forms , e.g. java code, yaml, springboot, spring-namespace.

**Comment by zhouchangjiang** [comment]
Ok,I get it,Thank you! @tristaZero

**Comment by tristaZero** [comment]
@zhouchangjiang  Hi, Is everything ok? Any problems, please contact me.
