### ISSUE TITLE
using C++ to connect sharding-proxy and Direct connection sharding-proxy,there are different result

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2471]
using C++ to connect sharding-proxy:
the exception is :
exception one :ERR: 1Unsupported command: [COM_STMT_SEND_LONG_DATA] 
exception two :SQLException: 2Unknown exception: [readerIndex(19) + length(1) exceeds writerIndex(19): PooledSlicedByteBuf(ridx: 19, widx: 19, cap: 19/19, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2081, widx: 2081, cap: 4096))]

Direct connection sharding-proxy: all is ok

**Comment by tianyijushi** [comment]
Hope for quick feedback. We're using it now. Thanks!

**Comment by terrymanu** [comment]
Hi, if you are urgency, we will do our best to try to find problem.

But for all previous issues you submitted, you do not reply any more when we ask you to provide future informations, it is not a good way to participate the community. 

We need ***corporate*** each other, if you have question, we will try to resolve them, but we still need you feedback your further information and status of the issue too.  If your problem is resolved, please update your issue's status. 

***By the way, can you register your company at***: #234 ***if your company is using ShardingSphere?*** More feedback will support the community more and more strong.

For this issue, please provide more information followed by template, we need to kwon your using version, database env, sharding rule configuration, exception stack trace etc..., we need more information to investigate it.

**Comment by tuohai666** [comment]
@tianyijushi 
What's the name of the C++ driver and it's version?

Please fill in the bug report template:

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by tianyijushi** [comment]
Which version of ShardingSphere did you use?
4.0.0-RC1
Which project did you use? Sharding-JDBC or Sharding-Proxy?
apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin
Expected behavior:
i want c++ connect sharding-proxy success;
Actual behavior:
the config-sharding.yml:
![图片](https://user-images.githubusercontent.com/34736778/58683984-1d8cf700-83a9-11e9-8f54-af160e34b772.png)
the server.yml:
![图片](https://user-images.githubusercontent.com/34736778/58684011-39909880-83a9-11e9-83ec-3288ef772001.png)
the C++ code:
![图片](https://user-images.githubusercontent.com/34736778/58684296-59748c00-83aa-11e9-9417-ff2866e293d7.png)
![图片](https://user-images.githubusercontent.com/34736778/58684297-59748c00-83aa-11e9-8c7b-c70873e297f6.png)
then connecting failed(see the bug  #2470,the schemaName always was null)
if i set the true schemaName ,the connect ok.


when modify like this 
![图片](https://user-images.githubusercontent.com/34736778/58684546-35657a80-83ab-11e9-81be-4f463b3c8cd7.png)
C++ connect ok ,bug if excute a long sql like :
update capture set keypoint= case id  where ? then ?...,alerted=case id  where ? then ? where id in (...)
the exception is :
exception two :SQLException: 2Unknown exception: [readerIndex(19) + length(1) exceeds writerIndex(19): PooledSlicedByteBuf(ridx: 19, widx: 19, cap: 19/19, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2081, widx: 2081, cap: 4096))]


hope for your help!

**Comment by tuohai666** [comment]
Can you modify the codes like this and try again to find any clues?

![image](https://user-images.githubusercontent.com/24643893/58691423-7fa42700-83be-11e9-8da6-343b764a42f5.png)

Change to:

```
driver_->connect(host, user, passwd);
conn_->setSchema(m_schema);
conn_->createStatement();
```

The changes are removing the reset() and changing order of setSchema() and createStatement().

**Comment by tianyijushi** [comment]
![图片](https://user-images.githubusercontent.com/34736778/58692821-00b0ed80-83c2-11e9-8888-3829410f9660.png)

the error is appended in driver_->connect(host, user, passwd);

**Comment by tuohai666** [comment]
I noticed you set sql.show : ture. Can you put on the log here?

**Comment by tianyijushi** [comment]
[DEBUG] 17:49:37.732 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
[INFO ] 17:49:38.478 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0xf06229f6, L:/0:0:0:0:0:0:0:0:3307] READ: [id: 0xa13d8f51, L:/172.17.100.87:3307 - R:/172.16.1.9:51004]
[INFO ] 17:49:38.479 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0xf06229f6, L:/0:0:0:0:0:0:0:0:3307] READ COMPLETE
[DEBUG] 17:49:38.542 [nioEventLoopGroup-3-1] io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
[DEBUG] 17:49:38.543 [nioEventLoopGroup-3-1] io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
[DEBUG] 17:49:38.543 [nioEventLoopGroup-3-1] io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
[DEBUG] 17:49:38.543 [nioEventLoopGroup-3-1] io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
[DEBUG] 17:49:38.560 [nioEventLoopGroup-3-1] io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
[DEBUG] 17:49:38.563 [nioEventLoopGroup-3-1] i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@5909f46d
[DEBUG] 17:49:38.573 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Write to client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 4c 00 00 00 0a 35 2e 36 2e 30 2d 53 68 61 72 64 |L....5.6.0-Shard|
|00000010| 69 6e 67 2d 50 72 6f 78 79 20 34 2e 30 2e 30 2d |ing-Proxy 4.0.0-|
|00000020| 52 43 32 00 01 00 00 00 67 30 32 4d 39 45 4d 4a |RC2.....g02M9EMJ|
|00000030| 00 4f b7 21 02 00 00 00 00 00 00 00 00 00 00 00 |.O.!............|
|00000040| 00 00 00 53 58 4f 56 54 70 32 37 47 61 76 50 00 |...SXOVTp27GavP.|
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.583 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Read from client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 3a 00 00 01 85 a2 be 01 00 00 00 40 21 00 00 00 |:..........@!...|
|00000010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
|00000020| 00 00 00 00 72 6f 6f 74 00 14 63 fc b5 9a 2a ff |....root..c...*.|
|00000030| f6 f6 9f 7e 4f 9a e9 9f f5 3a 3c e4 ae 22       |...~O....:<.."  |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.593 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Write to client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 07 00 00 02 00 00 00 02 00 00 00                |...........     |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.599 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Read from client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 11 00 00 00 03 73 65 74 20 61 75 74 6f 63 6f 6d |.....set autocom|
|00000010| 6d 69 74 3d 31                                  |mit=1           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.648 [ShardingSphere-Command-0] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=set autocommit=1)
[DEBUG] 17:49:38.670 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Write to client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 07 00 00 01 00 00 00 02 00 00 00                |...........     |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.673 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Read from client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 38 00 00 00 03 53 45 54 20 53 45 53 53 49 4f 4e |8....SET SESSION|
|00000010| 20 54 52 41 4e 53 41 43 54 49 4f 4e 20 49 53 4f | TRANSACTION ISO|
|00000020| 4c 41 54 49 4f 4e 20 4c 45 56 45 4c 20 52 45 50 |LATION LEVEL REP|
|00000030| 45 41 54 41 42 4c 45 20 52 45 41 44             |EATABLE READ    |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:38.674 [ShardingSphere-Command-1] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ)
[DEBUG] 17:49:39.188 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Write to client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 1d 00 00 01 ff 16 04 23 33 44 30 30 30 4e 6f 20 |.......#3D000No |
|00000010| 64 61 74 61 62 61 73 65 20 73 65 6c 65 63 74 65 |database selecte|
|00000020| 64                                              |d               |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:39.192 [nioEventLoopGroup-3-1] o.a.s.s.transport.codec.PacketCodec - Read from client a13d8f51 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 01 00 00 00 01                                  |.....           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 17:49:39.193 [ShardingSphere-Command-2] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUIT, value: org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.admin.quit.MySQLComQuitPacket@2cac8927

**Comment by tuohai666** [comment]
The last SQL before the error response is `SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ`. I suggest that you open a new issue for this problem first. I believe the c++ connector will work after this problem solved.
![image](https://user-images.githubusercontent.com/24643893/58698999-06f99680-83cf-11e9-9073-7cb495596533.png)
