### ISSUE TITLE
when updating a blob column ,the result was modified

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2475]
version of ShardingSphere: Sharding-Proxy-V4.0.0-RC1
info:
java project:springboot2 + mybatis 
sharding-rule:
![图片](https://user-images.githubusercontent.com/34736778/58634095-fe488800-831c-11e9-94af-2da2390e8db0.png)
table desc:
![图片](https://user-images.githubusercontent.com/34736778/58634135-18826600-831d-11e9-8ff6-3d3ce5d8fa19.png)
java resources:
![图片](https://user-images.githubusercontent.com/34736778/58634168-30f28080-831d-11e9-9d69-c865ac7ca844.png)
![图片](https://user-images.githubusercontent.com/34736778/58634440-e6253880-831d-11e9-9437-3b8e8b1d6c6f.png)
the test datas are 512 floats combined a binary data,then every float Occupy 8 bytes,
512*8=4096bit=2048B=2k
but the result is :
![图片](https://user-images.githubusercontent.com/34736778/58634476-f76e4500-831d-11e9-8e3e-e32a77713839.png)

When I connect directly to the mysql :
![图片](https://user-images.githubusercontent.com/34736778/58634785-c4788100-831e-11e9-80eb-be05c803b3f3.png)

I see that there are BLOB field types in shardingsphere source code. Did I need special usage methods?

**Comment by tianyijushi** [comment]
the column type is blob,but get it with LONGVARBINARY;
![图片](https://user-images.githubusercontent.com/34736778/58676330-7ac58000-838a-11e9-9a61-dfd1714b87a4.png)

**Comment by tuohai666** [comment]
Getting it with LONGVARBINARY is because:
![image](https://user-images.githubusercontent.com/24643893/58689394-795f7c00-83b9-11e9-9b40-9c235b150471.png)
Please change to BLOB.

BTW, I think the size of float in bytes is 4.

**Comment by tianyijushi** [comment]
float occupy  8bit ,also 4Byte
![图片](https://user-images.githubusercontent.com/34736778/58691920-f392ff00-83bf-11e9-95aa-1ca659c3d681.png)
i change the jdbcType to BLOB ,bug the problem is still

**Comment by tianyijushi** [comment]
@tuohai666

**Comment by tianyijushi** [comment]
@tuohai666  can you tell me 2471 and 2490 are the same problem.
2471 has problems:
1、#3D000No database selected
2、update sql happend “Unknown exception: [readerIndex(19) + length(1) exceeds writerIndex(19): PooledSlicedByteBuf(ridx: 19, widx: 19, cap: 19/19, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2081, widx: 2081, cap: 4096))]”
2490 has problem:
1、COM_STMT_PREPARE problem : select sqlhappend “java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): PooledSlicedByteBuf(ridx: 11, widx: 11, cap: 11/11, unwrapped: PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 464))”

OR close this 2475 bug too.

**Comment by tuohai666** [comment]
Fixed in 4.0.0-RC2-SNAPSHOT. Please refer to #1910 and #1567

**Comment by tianyijushi** [comment]
@tuohai666 
Yesterday，i downloaded the 4.0.0-RC2-release source code, and check this bug ，just used sharding-proxy，no sharding-jdbc。
info：
sharding-proxy version：4.0.0-RC2-release
sharding-rule: same with this issue
my code:
![图片](https://user-images.githubusercontent.com/34736778/60229256-e0445800-98c7-11e9-8285-eebff602e086.png)
![图片](https://user-images.githubusercontent.com/34736778/60229264-e63a3900-98c7-11e9-933b-7f22c0dc9137.png)

If i connect directly to MySQL,the result is :
![图片](https://user-images.githubusercontent.com/34736778/60229283-f0f4ce00-98c7-11e9-9807-d7ccd73dd9d8.png)
If i connect to MySQL with sharding-proxy,the result is :
![图片](https://user-images.githubusercontent.com/34736778/60230363-01597880-98c9-11e9-9909-b1e02468cb0f.png)

should i test in last release?
