### ISSUE TITLE
ShardingDataSource wrapped with EncryptDataSource for PostgreSQL

### ISSUE THREAD

**Issue by wowojyc** [apache/incubator-shardingsphere#2480]
## Bug Report
In my project, My database type is postgreSQL, and I want to use ShardingDatasource with encrypt configuration.

For example, the encrypt column is "goods_name" and the assist column is "goods_name_new", but it does not work.

When i debug the code, i find the code below.

`public Optional<ShardingEncryptor> getShardingEncryptor(final String logicTableName, final String columnName) {
        for (ShardingEncryptorStrategy each : shardingEncryptorStrategies.values()) {
            Optional<ShardingEncryptor> result = each.getShardingEncryptor(logicTableName, columnName);
            if (result.isPresent()) {
                return result;
            }
        }
        return Optional.absent();
    }`
The sharding jdbc rewrites the sql with column alias, for example

select goods0_.goods_id as goods_id1_0_, goods0_.goods_name as goods_na2_0_, goods0_.goods_type as goods_ty3_0_ from goods goods0_

So when it comes to the code before, the table name is right, however the column is alias name.

I think it is due to PostgreSQL PgResultSet.class. Its attributes 'fields' is set according to  alias value rather than querying its from the PostgreSQL meta.

My PostgreSQL is 10.1
the sharding jdbc version is 4.0.0-RC1

Thank you very much!

**Comment by terrymanu** [comment]
4.0.0-RC1 is not support encrypt for PostgreSQL.
It finished at #2410 and will be released at 4.0.0-RC2.
You may try it on dev branch

**Comment by wowojyc** [comment]
Thank you for responds. When will the 4.0.0-RC2 version release?

**Comment by terrymanu** [comment]
No release plan yet.
For this issue, can you close it?

**Comment by wowojyc** [comment]
Thank you very much
