### ISSUE TITLE
Introducing the transaction manager leads to conflict with the tcc-transaction framework

### ISSUE THREAD

**Issue by jimmycheng888** [apache/incubator-shardingsphere#2482]
**Which version of ShardingSphere did you use?**
3.1.0

**Which project did you use? Sharding-JDBC or Sharding-Proxy?**
Sharding-JDBC

**Actual behavior**
The introduction of the transaction manager leads to a conflict with the tcc-transaction framework, because after the exception occurs, the jdbc transaction of tcc-transaction is managed by the shardingsphere, and from a business perspective, the business transaction and the log transaction should be separated. This will cause my tcc transaction log to be lost during the try phase, because I have an abnormal behavior during the try phase. Since shardingsphere is a distributed component, I hope that shardingsphere can be compatible with more middleware.

### Example codes for reproduce this issue (such as a github link).
java Code

```
@Transactional(value = "dataSourceTransactionManager", rollbackFor = Exception.class)
    @Compensable(confirmMethod = "confirmIssue", cancelMethod = "cancelIssue")
public void issue(@UniqueIdentity String transactionXid, String test){
/ / The following is pseudo code
//My business code
/ / Start throwing an exception
}
public void confirmIssue( String transactionXid, String test){
}
public void cancelIssue( String transactionXid, String test){
}
```
   ```
     <!--sharing-jdbc start-->
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-spring-boot-starter</artifactId>
        </dependency>
        <!--sharing-jdbc end-->
```

**Comment by terrymanu** [comment]
You do some customized development, so can you put all of your code to github and provide the link here?

We may do not have enough time to Integrate with all frameworks, so is anyone interested with this issue?

**Comment by terrymanu** [comment]
Closed without reason with issue owner, I just set it as invalid
