### ISSUE TITLE
An idea about adapting to any databases more than MySQL Postgres 

### ISSUE THREAD

**Issue by Kiddinglife** [apache/incubator-shardingsphere#2484]
### Describe the feature you would like.
Have a sidecar pod running on the same node with database pod and playing as the agent of database . The sidecar will have common api that must be fulfilled by the users to adapt for their specific database. E.g. influx-dB. users can provide their own sidecar docker image that implement the api standards with a database’s specific crud statements and database administration commands and so on.

**Comment by terrymanu** [comment]
Does someone interest on this issue?

**Comment by Kiddinglife** [comment]
I am interested at it.
But do not know if it is achievable.
Regards.
________________________________

**Comment by lalicw** [comment]
it's a good idea.it will be helpful!

**Comment by terrymanu** [comment]
I just close this issue because the scope is too big.
If someone want to implement with a new database, should talk about how to parse sql, how to implement database protocol and so on.
If some one really want to do this, please contact us again.
