### ISSUE TITLE
when insert set primary key is null  will show not support complex expression value

### ISSUE THREAD

**Issue by Yohox** [apache/incubator-shardingsphere#2486]
### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
insert success
### Actual behavior

insert failure

Unknown exception: INSERT INTO can not support complex expression value on sharding column 'id'. 

### Reason analyze (If you can)
when insert if the primary key is null it's will show not support complex expression value.
### Example codes for reproduce this issue (such as a github link).
```
CREATE TABLE `user` (
  `id` bigint(100) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `expiration_time` int(11) DEFAULT NULL,
  `point` varchar(255) DEFAULT NULL,
  `created_time` int(11) DEFAULT NULL,
  `pro_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


INSERT INTO user  ( id, username,password,expiration_time,point,created_time,pro_id ) VALUES( null, 'dsff','dsfdsf',2,2,1,2 )
```

**Comment by dongzl** [comment]
@Yohox  Hi, I used the 4.0.0-RC1 version, success, you can try it.

**Comment by Yohox** [comment]
i use the 4.0.0RC2 show 

10002 - 2Unknown exception: [No signature of method: java.lang.String.mod() is applicable for argument types: (java.lang.Integer) values: [2]
Possible solutions: drop(int), find(), any(), use([Ljava.lang.Object;), any(groovy.lang.Closure), find(java.util.regex.Pattern)], Time: 0.038000s

**Comment by terrymanu** [comment]
No matter Groovy or Java can not support use class type `String` to call `mod()` method.
Inline expression is Groovy expression, you need to follow Groovy's grammar.


.
