### ISSUE TITLE
sharding-proxy(4.0.0-RC1) can not reback the COM_STMT_PREPARE status

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2490]
Which version of ShardingSphere did you use?
4.0.0-RC1
Which project did you use? Sharding-JDBC or Sharding-Proxy?
apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin
Expected behavior:
i want c++ connect sharding-proxy and excute sql success;

bug info:
the error sql:SELECT id FROM face_group where status='active';
the table face_group is not submeter;
the c++ connect code:
![图片](https://user-images.githubusercontent.com/34736778/58791367-a5326a00-8624-11e9-99b8-32310cc85852.png)

if i don't use COM_STMT_PREPARE,directly use excute_query(sql) is ok !

the error log:
[DEBUG] 16:41:17.794 [ShardingSphere-Command-4] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_PING, value: org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.admin.ping.MySQLComPingPacket@2e780b64
[DEBUG] 16:41:17.796 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Write to client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 07 00 00 01 00 00 00 02 00 00 00                |...........     |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.799 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Read from client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 31 00 00 00 16 53 45 4c 45 43 54 20 69 64 20 46 |1....SELECT id F|
|00000010| 52 4f 4d 20 66 61 63 65 5f 67 72 6f 75 70 20 77 |ROM face_group w|
|00000020| 68 65 72 65 20 73 74 61 74 75 73 3d 27 61 63 74 |here status='act|
|00000030| 69 76 65 27 3b                                  |ive';           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.799 [ShardingSphere-Command-5] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_STMT_PREPARE, value: MySQLComStmtPreparePacket(sql=SELECT id FROM face_group where status='active';)
[DEBUG] 16:41:17.812 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Write to client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 0c 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 |................|
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.815 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Read from client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 01 00 00 00 0e                                  |.....           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.816 [ShardingSphere-Command-6] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_PING, value: org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.admin.ping.MySQLComPingPacket@23de7769
[DEBUG] 16:41:17.816 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Write to client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 07 00 00 01 00 00 00 02 00 00 00                |...........     |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.818 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Read from client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 0a 00 00 00 17 01 00 00 00 00 01 00 00 00       |..............  |
+--------+-------------------------------------------------+----------------+
[ERROR] 16:41:17.824 [ShardingSphere-Command-7] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): PooledSlicedByteBuf(ridx: 11, widx: 11, cap: 11/11, unwrapped: PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 464))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
	at org.apache.shardingsphere.shardingproxy.transport.mysql.payload.MySQLPacketPayload.readInt1(MySQLPacketPayload.java:49)
	at org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.query.binary.execute.MySQLComStmtExecutePacket.<init>(MySQLComStmtExecutePacket.java:79)
	at org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.MySQLCommandPacketFactory.newInstance(MySQLCommandPacketFactory.java:67)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:55)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:46)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:84)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[DEBUG] 16:41:17.830 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Write to client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| cb 00 00 01 ff 12 27 23 43 31 30 30 30 32 55 6e |......'#C10002Un|
|00000010| 6b 6e 6f 77 6e 20 65 78 63 65 70 74 69 6f 6e 3a |known exception:|
|00000020| 20 5b 72 65 61 64 65 72 49 6e 64 65 78 28 31 31 | [readerIndex(11|
|00000030| 29 20 2b 20 6c 65 6e 67 74 68 28 31 29 20 65 78 |) + length(1) ex|
|00000040| 63 65 65 64 73 20 77 72 69 74 65 72 49 6e 64 65 |ceeds writerInde|
|00000050| 78 28 31 31 29 3a 20 50 6f 6f 6c 65 64 53 6c 69 |x(11): PooledSli|
|00000060| 63 65 64 42 79 74 65 42 75 66 28 72 69 64 78 3a |cedByteBuf(ridx:|
|00000070| 20 31 31 2c 20 77 69 64 78 3a 20 31 31 2c 20 63 | 11, widx: 11, c|
|00000080| 61 70 3a 20 31 31 2f 31 31 2c 20 75 6e 77 72 61 |ap: 11/11, unwra|
|00000090| 70 70 65 64 3a 20 50 6f 6f 6c 65 64 55 6e 73 61 |pped: PooledUnsa|
|000000a0| 66 65 44 69 72 65 63 74 42 79 74 65 42 75 66 28 |feDirectByteBuf(|
|000000b0| 72 69 64 78 3a 20 31 34 2c 20 77 69 64 78 3a 20 |ridx: 14, widx: |
|000000c0| 31 34 2c 20 63 61 70 3a 20 34 36 34 29 29 5d    |14, cap: 464))] |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.832 [nioEventLoopGroup-3-4] o.a.s.s.transport.codec.PacketCodec - Read from client c23d8947 : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 05 00 00 00 19 01 00 00 00                      |.........       |
+--------+-------------------------------------------------+----------------+
[DEBUG] 16:41:17.833 [ShardingSphere-Command-8] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_STMT_CLOSE, value: MySQLComStmtClosePacket(statementId=1)

**Comment by tuohai666** [comment]
It seems like the connecting problem(#2471) didn't happen, Why?
Did you see my last respnse in #2471? Can you reply?

**Comment by terrymanu** [comment]
@tianyijushi Hello, I am sorry to tell you that we cannot serve you if you don't follow way of community.

**Comment by tianyijushi** [comment]
the problem #2471  is that the schemaName has a null value;
then i set the true value to schemaName ,now C++ connecting ok !
but this bug #2490 is another problem,did you find the error is IndexOutOfBoundsException,not conneting error.

**Comment by tianyijushi** [comment]
Did you look at the problem description in detail?
By the way, your last respnse in #2471, i had read it carefully!!!!!
Then i found the bug is closed ,Please tell me the similarity of these two problems!
