### ISSUE TITLE
Group by in SQL statements takes a long time ,the index seems to be not working...

### ISSUE THREAD

**Issue by wbliubin** [apache/incubator-shardingsphere#2491]
### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 

### Expected behavior
I have a sql , eg:
`SELECT
	  a.tid 
FROM A  a Left join B b on  a.tid = b.tid
WHERE a.user_id= 1234567890
AND a.sid = 1234567890
AND b.user_id= 1234567890
AND b.sid = 1234567890
   GROUP BY  
	 a.tid 
ORDER BY
	a.tid DESC
limit 10`

1. The execution time of the database client is only 0.004s,
![image](https://user-images.githubusercontent.com/3971394/58799726-9eaded80-8638-11e9-958e-cdfff9474e1e.png)

### Actual behavior
2. But , in Sharding-JDBC project ,it takes 4s~9s !

### Reason analyze (If you can)
3. this SQL takes 0.01s~0.1 to get rid of the "group by" inside ,I mean, the index seems to be not working...

**Comment by terrymanu** [comment]
Can you explain your SQL to make sure the index?
ShardingSphere do not process with index in MySQL, it probably original SQL's problem

**Comment by terrymanu** [comment]
No feedback any more, closed as invalid.
