### ISSUE TITLE
although  atomikos rollback, but data still exist in database

### ISSUE THREAD

**Issue by EvanDylan** [apache/incubator-shardingsphere#2499]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior

the use case as blow (ps : use atomikos)

```java
@Transactional
    public void xaTransaction() {
        userMapper.insertUser(887, 20);
        throw new RuntimeException();
    }
```
the end line with throw **RuntimeException**, so the insert data user while be rollback

### Actual behavior
although atomikos execute rollback, but data still exist in database;

### Example codes for reproduce this issue (such as a github link).
https://github.com/EvanDylan/sharding-samples.git

**Comment by cherrylzhao** [comment]
hi, you have integrated XA transaction in a wrong way.
please reference our [example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example/transaction-2pc-xa-example).

I have not seen @ShardingTransactionType or TransactionTypeHolder API in your example.

**Comment by EvanDylan** [comment]
In the version of 4.0.0-RC1 ,annotation of SharindTransationType is not available and the examples of integrated with spring namespace without TransantionTypeHolder too.

**Comment by EvanDylan** [comment]
You can running the demo directly and rollback log will be print by atomikos, i am not sure this issue cause by Sharding-JDBC

**Comment by cherrylzhao** [comment]
this atomikos log is come for spring-boot jpa

**Comment by cherrylzhao** [comment]
you have open boot autoconfiguration，boot have discovery atomikos jar, so it instance atomikos transaction manager directory, but this is not what sharding need.

**Comment by cherrylzhao** [comment]
> In the version of 4.0.0-RC1 ,annotation of SharindTransationType is not available and the examples of integrated with spring namespace without TransantionTypeHolder too.

you can mvn clean install from our https://github.com/OpenSharding/shardingsphere-spi-impl

**Comment by EvanDylan** [comment]
thanks a lot,I had big mistake,lol

**Comment by EvanDylan** [comment]
@cherrylzhao the [example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example/transaction-2pc-xa-example/transaction-xa-spring-boot-example) you has provided also use spring boot autoconfiguration too. So could you pelease update the example and fix the error.

**Comment by cherrylzhao** [comment]
example is ok, we have provided `sharding-transaction-spring-boot-starter` to avoid it happen, or you can use @exculed annotation manually.

**Comment by EvanDylan** [comment]
got it, thanks again
