### ISSUE TITLE
Refactor LoadBalanceStrategyConfiguration

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#2503]
### Is your feature request related to a problem?
No.
### Describe the feature you would like.
LoadBalanceStrategyConfiguration should implement TypeBasedSPI like ShardingEncryptor.

**Comment by cherrylzhao** [comment]
`LoadBalanceStrategyConfiguration` have implemented `TypeBasedSPIConfiguration`, this issue should be closed.

**Comment by tuohai666** [comment]
Yes, @cherrylzhao refactored before.
