### ISSUE TITLE
algorithmExpression multi-tenant

### ISSUE THREAD

**Issue by nieoding** [apache/incubator-shardingsphere#2505]
I try to make sharding by tenant on sharding-proxy, can algorithmExpression support?
> tenant_id=a -> schema_a.user
> tenant_id=b -> schema_b.user
> default -> schema_default.user

**Comment by dongzl** [comment]
Hi @nieoding , You can define your own sharding algorithm class, 

the class need implement interface:

org.apache.shardingsphere.api.sharding.standard.PreciseShardingAlgorithm

**Comment by nieoding** [comment]
how to use custom class in sharding-proxy(not in sharding-jdbc)?
build jar and config by algorithmClassName?
where i can find the example?

**Comment by dongzl** [comment]
@nieoding  you can define you own sharding algorithm class, and  generate a jar file with maven; put this jar into sharding-proxy/lib directory.

You can reference this article：
https://www.jianshu.com/p/0e3f770eb489

**Comment by nieoding** [comment]
@dongzl 能否自定义算法只实现逻辑，具体条件参数存储在配置中心呢？我看官方文档有configmap一说

![image](https://user-images.githubusercontent.com/12727335/58943554-8c57bf00-87b2-11e9-8232-5c79fde19ba3.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
