### ISSUE TITLE
强制主库路由如何设置

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2508]
“官网中的“基于Hint的强制主库路由”，这个是在应用代码程序中实现还是在proxy中可以配置？如何配置？
因为有些库或者有些表实时性比较高，需要即时查询，要直接强制主库查询，这个怎么设置proxy可以实现？

谢谢！”

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
