### ISSUE TITLE
Can Proxy Only do proxy for the database, do not slice the table?

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2519]
I want proxy my multiple databases use shardingsphere-proxy, is there any solutions? Also, without table slice.

**Comment by terrymanu** [comment]
FIY: https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/sharding/raw/jdbc/config/ShardingDatabasesConfigurationPrecise.java
