### ISSUE TITLE
if shardingsphere can create tables  automatically?

### ISSUE THREAD

**Issue by fdlzp** [apache/incubator-shardingsphere#2521]
**Description：**

**Data Node Configuration：**
spring.shardingsphere.sharding.tables.t_basic_up_msg.actual-data-nodes=\
sharding-test.t_basic_up_msg_20${19..24}_0${1..9},sharding-test.t_basic_up_msg_2019${19..24}_${10..12}

Sharding_test
  ├── t_basic_up_msg_2019_01
  ├── t_basic_up_msg_2019_02
  ├── t_basic_up_msg_2019_03
  ├── t_basic_up_msg_2019_04
  ├── t_basic_up_msg_2019_05
  ├── t_basic_up_msg_2019_06
  ├── t_basic_up_msg_2019_07
  ├── t_basic_up_msg_2019_08
  ├── t_basic_up_msg_2019_09
  ├── t_basic_up_msg_2019_10
  ├── t_basic_up_msg_2019_11
  ├── t_basic_up_msg_2019_12
  ………
  ├── t_basic_up_msg_2024_07
  ├── t_basic_up_msg_2024_08
  ├── t_basic_up_msg_2024_09
  ├── t_basic_up_msg_2024_10
  ├── t_basic_up_msg_2024_11
  ├── t_basic_up_msg_2024_12

（There are 72 tables in total.）

**Sharding Key**
receipt_time  (type :datetime)

**Actual behavior of creating tables** 

A、Use MySQL stored procedures or sql script.
B、By springboot：
spring.jpa.properties.hibernate.hbm2ddl.auto= create

**Expected behavior**

sharidngsphere can help create tables  automatically.

For example,
we don't need to create so many tables at first.
May be we can just create tables from  t_basic_up_msg_2019_01 to  t_basic_up_msg_2019_12.
Wait until 2020.01.01 ，and then shardingsphere can create tables from  t_basic_up_msg_2020_01 to  t_basic_up_msg_2020_12.
And so on.
It's a mechanism like this for  creating tables automatically.

**My environment：**

springboot + JPA + mysql +sharding-jbdc

I think this is a problem that we may face in the production environment
（when the type of sharding key is datetime and the number of tables is too big）.

 It's a little inconvenient  although we can create tables first.

That's what I want to suggest.
Thank you.

**Comment by terrymanu** [comment]
If user execute DDL will create table for all sharding nodes;
Is there any reason to let ShardingSphere create table without any user call?

**Comment by terrymanu** [comment]
Sharding-JDBC of ShardingSphere is a JDBC extension;
Sharding-Proxy of ShardingSphere is a MySQL/PostgreSQL proxy.

Auto create tables is not ShardingSphere's scope, it should be do at orm or other database framework. ShardingSphere is a driver layer, do not focus user's business logic.

**Comment by fdlzp** [comment]
Ok, I get it , thanks！
