### ISSUE TITLE
CachedDatabaseMetaData.getTables throw NullPointerException when use MasterSlaveDataSource

### ISSUE THREAD

**Issue by caszhou** [apache/incubator-shardingsphere#2527]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Return table names
### Actual behavior
Get npe
### Reason analyze (If you can)
asset shardingRule is null
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
DatabaseMetaData databaseMetaData = connection.getMetaData();
databaseMetaData.getTables(null, null, "ACT_ID_PROPERTY", new String[]{ "TABLE" });

**Comment by KomachiSion** [comment]
Hi @caszhou, can you provide your sharding rule configuration?

**Comment by caszhou** [comment]
@KomachiSion I'm using master-slave modal, no sharding rules.

I look into MasterSlaveDataSource, see

`
    private DatabaseMetaData createCachedDatabaseMetaData(final Map<String, DataSource> dataSourceMap) throws SQLException {
        try (Connection connection = dataSourceMap.values().iterator().next().getConnection()) {
            return new CachedDatabaseMetaData(connection.getMetaData(), dataSourceMap, null);
        }
    }
`

when instance CachedDatabaseMetaData, the sharding rule is always null.

**Comment by KomachiSion** [comment]
Thanks, I has known the problem, I will fix this problem soon.
