### ISSUE TITLE
It would be perfect if you could use it with apollo！

### ISSUE THREAD

**Issue by windlikeman** [apache/incubator-shardingsphere#2530]
It would be perfect if you could use it with apollo.

**Comment by terrymanu** [comment]
Does anybody want to do this?

**Comment by windlikeman** [comment]
Yes, I think there is a lack of a configuration tool. I think I should be able to develop it according to the interface

**Comment by terrymanu** [comment]
Thank you, you can ref zookeeper and etcd's implementation.

**Comment by terrymanu** [comment]
Because use other reg center is not master feature request, if nobody go ahead to do this issue, I will close it soon.

**Comment by terrymanu** [comment]
Closed until somebody as a volunteer to do it
