### ISSUE TITLE
Modify configuration of actual-data-nodes from zookeeper invalid

### ISSUE THREAD

**Issue by xiaotianlongxing** [apache/incubator-shardingsphere#2531]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-jdbc-spring-namespace-4.0.0-RC1
sharding-jdbc-orchestration-spring-namespace-4.0.0-RC1
sharding-orchestration-reg-zookeeper-curator-4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
I want to Modify actual-data-nodes from zookeeper

### Actual behavior
not used,my zookeeper version is 3.5.5,and i try the version 3.4.13 too

### Reason analyze (If you can)
I modify configuration from zk，No error in the process，and i sure my sharding-jdbc has received it.but the actual query table (actual-data-nodes) not changed  when i query again

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

    My datasource is com.alibaba.druid.pool.DruidDataSource

    <orchestraion:registry-center id="regCenter" type="zookeeper" server-lists="localhost:2182" namespace="pay-sharding-orchestration" operation-timeout-milliseconds="1000" max-retries="3" />
    <orchestraion:sharding-data-source id="shardingOrchestration" data-source-ref="shardingDataSource" registry-center-ref="regCenter" />
	
 	<bean id="tableShardingAlgorithmByMonth" class="com.yobit.business.utils.sharding.TableShardingAlgorithmByMonth"></bean>
  	<sharding:standard-strategy id="payOrderPreciseAlgorithm" sharding-column="create_date" precise-algorithm-ref="tableShardingAlgorithmByMonth"></sharding:standard-strategy>
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="dataSource">
            <sharding:table-rules>
		
            	<sharding:table-rule logic-table="pay_order" actual-data-nodes="dataSource.pay_order_20190$->{5..6}" table-strategy-ref="payOrderPreciseAlgorithm"  />
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="pay_order"/>
            </sharding:binding-table-rules>
        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>

**Comment by xiaotianlongxing** [comment]
any changes on the zookeeper will not take effect  when I try again 。For example，update the  "sql.show: 'false'"

**Comment by xiaotianlongxing** [comment]
I check the source code. The property shardingContext of ShardingDataSource has changed ,but the shardingContext of getConnection method  hasn't changed.

**Comment by tristaZero** [comment]
@xiaotianlongxing 
Can you use [incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/orchestration-example/orchestration-spring-namespace-example/src/main/java/org/apache/shardingsphere/example/orchestration/spring/namespace/SpringNamespaceExample.java) to have a try？
When i change "sql.show: 'false'" in zk using this exmaple, i find everything is ok.

**Comment by tristaZero** [comment]
I change  [incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/orchestration-example/orchestration-spring-namespace-example/src/main/java/org/apache/shardingsphere/example/orchestration/spring/namespace/SpringNamespaceExample.java) a little to do test, the code changed is as follows:
```
public static void main(final String[] args) {
        try (ConfigurableApplicationContext applicationContext = new ClassPathXmlApplicationContext(getApplicationFile())) {
            SpringPojoService commonService = applicationContext.getBean(SpringPojoService.class);
            commonService.initEnvironment();
            commonService.processSuccess();
            Thread.sleep(120000);
            System.out.println("clear");
            commonService.cleanEnvironment();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

**Comment by xiaotianlongxing** [comment]
@tristaZero 
think you .I use the example to do test. it is ok. 
but I find registry center configurations did not overwrite local configurations when each initialization.
namespace as follows:
`<orchestraion:sharding-data-source id="shardingDatabasesTablesDataSource" data-source-ref="realShardingDatabasesTablesDataSource" registry-center-ref="regCenter" overwrite="false" />`
or
`<orchestraion:sharding-data-source id="shardingDatabasesTablesDataSource" data-source-ref="realShardingDatabasesTablesDataSource" registry-center-ref="regCenter"  />`

**Comment by tristaZero** [comment]
The setting of `overwrite` means whether  the configuration on registry will be overwritten by local configuration.

**Comment by xiaotianlongxing** [comment]
I see. 
But what to do if I want to load the configuration from zk every time I initialize

**Comment by tristaZero** [comment]
To make your local configuration only contain the zookeeper's setting after first startup. Because we need fisrt startup pushes the local configuration to zk.
@xiaotianlongxing

**Comment by xiaotianlongxing** [comment]
I see , think you very much @tristaZero
