### ISSUE TITLE
ParsingRuleRegistry初始化bug

### ISSUE THREAD

**Issue by solderAlex** [apache/incubator-shardingsphere#2537]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Expected behavior

在我公司使用的sharding-jdbc中，之前使用一直正常，直到在某次发布时，其中一台机器在执行一条count语句时报错，错误内容如下。
![image](https://user-images.githubusercontent.com/14837116/59261408-fae3c380-8c6f-11e9-9439-a99e7f3d30f5.png)

在应用重启后，不再报错。

我公司用的版本为3.1.0。 在最新的4.0.0-RC版本，应该也存在类似问题

### Reason analyze (If you can)

应用启动后，并发的线程执行同一条sql，有可能线程会拿到一个未初始化完成的ParsingRuleRegistry。从而导致sql解析得到SqlStatement出现问题。如果SqlStatement被缓存下来，会导致接下来的sql执行都会错误。问题代码片段

    /**
     * Get singleton instance of parsing rule registry.
     * 
     * @return instance of parsing rule registry
     */
    public static ParsingRuleRegistry getInstance() {
        // 如果第一个线程，在init。第二个线程进入，会拿到一个可能不完整的instance。解析sql
        if (null == instance) {
            synchronized (ParsingRuleRegistry.class) {
                if (null == instance) {
                    instance = new ParsingRuleRegistry();
                    instance.init();
                }
            }
        }
        return instance;
    }

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by Ah39** [comment]
mark @solderAlex 是哪一个类啊，图中代码

**Comment by Ah39** [comment]
@terrymanu 这个代码确实是有问题的，会拿到没有舒适化的类

**Comment by lafaso** [comment]
@solderAlex hello，how did you solve this question?
