### ISSUE TITLE
use druid sql monitor error

### ISSUE THREAD

**Issue by roneywei** [apache/incubator-shardingsphere#2544]
## Question

use druid sql monitor error

config ：

spring.shardingsphere.datasource.master0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.master0.password=
spring.shardingsphere.datasource.master0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master0.url=
spring.shardingsphere.datasource.master0.username=
spring.shardingsphere.datasource.master0.druid.filters=stat,wall,log4j
spring.shardingsphere.datasource.master0.druid.initial-size=3
spring.shardingsphere.datasource.master0.druid.log-abandoned=true
spring.shardingsphere.datasource.master0.druid.max-active=80
spring.shardingsphere.datasource.master0.druid.max-wait=10000
spring.shardingsphere.datasource.master0.druid.min-idle=3
spring.shardingsphere.datasource.master0.druid.remove-abandoned=true
spring.shardingsphere.datasource.master0.druid.remove-abandoned-timeout=180
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.allow=
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.deny=
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.enabled=true
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.login-password=
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.login-username=
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.reset-enable=
spring.shardingsphere.datasource.master0.druid.stat-view-servlet.url-pattern=/druid/*
spring.shardingsphere.datasource.master0.druid.test-on-borrow=false
spring.shardingsphere.datasource.master0.druid.test-on-return=false
spring.shardingsphere.datasource.master0.druid.test-while-idle=true
spring.shardingsphere.datasource.master0.druid.validation-query=select 1 from dual
spring.shardingsphere.datasource.master0.druid.web-stat-filter.enabled=true
spring.shardingsphere.datasource.master0.druid.web-stat-filter.exclusions=/druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
spring.shardingsphere.datasource.master0.druid.web-stat-filter.principal-cookie-name=
spring.shardingsphere.datasource.master0.druid.web-stat-filter.principal-session-name=
spring.shardingsphere.datasource.master0.druid.web-stat-filter.profile-enable=
spring.shardingsphere.datasource.master0.druid.web-stat-filter.session-stat-enable=
spring.shardingsphere.datasource.master0.druid.web-stat-filter.session-stat-max-count=
spring.shardingsphere.datasource.master0.druid.web-stat-filter.url-pattern=/*
spring.shardingsphere.datasource.master0slave0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.master0slave0.password=
spring.shardingsphere.datasource.master0slave0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master0slave0.url=
spring.shardingsphere.datasource.master0slave0.username=
spring.shardingsphere.datasource.master0slave0.druid.filters=stat,wall,log4j
spring.shardingsphere.datasource.master0slave0.druid.initial-size=3
spring.shardingsphere.datasource.master0slave0.druid.log-abandoned=true
spring.shardingsphere.datasource.master0slave0.druid.max-active=80
spring.shardingsphere.datasource.master0slave0.druid.max-wait=10000
spring.shardingsphere.datasource.master0slave0.druid.min-idle=3
spring.shardingsphere.datasource.master0slave0.druid.remove-abandoned=true
spring.shardingsphere.datasource.master0slave0.druid.remove-abandoned-timeout=180
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.allow=
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.deny=
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.enabled=true
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.login-password=
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.login-username=
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.reset-enable=
spring.shardingsphere.datasource.master0slave0.druid.stat-view-servlet.url-pattern=/druid/*
spring.shardingsphere.datasource.master0slave0.druid.test-on-borrow=false
spring.shardingsphere.datasource.master0slave0.druid.test-on-return=false
spring.shardingsphere.datasource.master0slave0.druid.test-while-idle=true
spring.shardingsphere.datasource.master0slave0.druid.validation-query=select 1 from dual
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.enabled=true
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.exclusions=/druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.principal-cookie-name=
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.principal-session-name=
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.profile-enable=
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.session-stat-enable=
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.session-stat-max-count=
spring.shardingsphere.datasource.master0slave0.druid.web-stat-filter.url-pattern=/*

error 

![image](https://user-images.githubusercontent.com/5858867/59341423-65f9cc80-8d3a-11e9-8e03-a9fac806d21c.png)

**Comment by terrymanu** [comment]
Does anyone want to investigate this issue?

**Comment by hqq2023623** [comment]
@roneywei 
I think there is something wrong with your props key 
Yours:
`
spring.shardingsphere.datasource.master0.druid.filters=stat,wall,log4j
`
Mine: there is no druid between master0 and filters
`
spring.shardingsphere.datasource.master0.filters=stat,wall,log4j
`

You can try the props below
```

spring.shardingsphere.datasource.names=master0,master0slave0

spring.shardingsphere.datasource.master0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.master0.password=
spring.shardingsphere.datasource.master0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master0.url=jdbc:mysql://localhost:3306/ds0?useSSL=FALSE&serverTimezone=GMT%2B8
spring.shardingsphere.datasource.master0.username=root
spring.shardingsphere.datasource.master0.filters=stat,wall,logback
spring.shardingsphere.datasource.master0.initial-size=3
spring.shardingsphere.datasource.master0.log-abandoned=true
spring.shardingsphere.datasource.master0.max-active=80
spring.shardingsphere.datasource.master0.max-wait=10000
spring.shardingsphere.datasource.master0.min-idle=3
spring.shardingsphere.datasource.master0.remove-abandoned=true
spring.shardingsphere.datasource.master0.remove-abandoned-timeout=180
spring.shardingsphere.datasource.master0.test-on-borrow=false
spring.shardingsphere.datasource.master0.test-on-return=false
spring.shardingsphere.datasource.master0.test-while-idle=true
spring.shardingsphere.datasource.master0.validation-query=select 1 from dual
spring.shardingsphere.datasource.master0.useGlobalDataSourceStat=true

spring.shardingsphere.datasource.master0slave0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.master0slave0.password=
spring.shardingsphere.datasource.master0slave0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master0slave0.url=jdbc:mysql://localhost:3306/ds1?useSSL=FALSE&serverTimezone=GMT%2B8
spring.shardingsphere.datasource.master0slave0.username=root
spring.shardingsphere.datasource.master0slave0.filters=stat,wall,logback
spring.shardingsphere.datasource.master0slave0.initial-size=3
spring.shardingsphere.datasource.master0slave0.log-abandoned=true
spring.shardingsphere.datasource.master0slave0.max-active=80
spring.shardingsphere.datasource.master0slave0.max-wait=10000
spring.shardingsphere.datasource.master0slave0.min-idle=3
spring.shardingsphere.datasource.master0slave0.remove-abandoned=true
spring.shardingsphere.datasource.master0slave0.remove-abandoned-timeout=180
spring.shardingsphere.datasource.master0slave0.test-on-return=false
spring.shardingsphere.datasource.master0slave0.test-while-idle=true
spring.shardingsphere.datasource.master0slave0.validation-query=select 1 from dual
spring.shardingsphere.datasource.master0slave0.useGlobalDataSourceStat=true


mybatis.mapper-locations=classpath:/mapper/*Mapper.xml

spring.shardingsphere.props.sql.show=true

```

**Comment by roneywei** [comment]
thanks. use your props key.sql monitor success.
