### ISSUE TITLE
Cause: org.apache.shardingsphere.core.parse.old.parser.exception.SQLParsingUnsupportedException: Not supported token 'LEFT_PAREN'.

### ISSUE THREAD

**Issue by offSwitch** [apache/incubator-shardingsphere#2545]
### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
Cause: org.apache.shardingsphere.core.parse.old.parser.exception.SQLParsingUnsupportedException: Not supported token 'LEFT_PAREN'.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
no sharding,not work correctly,mysql 5.6
(select *from stu where id = 1)  
union all 
(select *from where id = 3) -> exception

select *from ((select *from stu where id = 1)  
union all 
(select *from where id = 3)) A -> work correctly

**Comment by terrymanu** [comment]
We remove old parse engine on 4.0.0-RC2, so I just close this issue.
