### ISSUE TITLE
When I use SHARDING-JDBC, I can't insert data properly

### ISSUE THREAD

**Issue by mrlinjun** [apache/incubator-shardingsphere#2551]
## Question

**I found that once insert generated two transactions in MySQL and generated deadlocks.**

![image](https://user-images.githubusercontent.com/34928452/59424603-dcfc9700-8e06-11e9-96d5-5fa49c74651b.png)
![image](https://user-images.githubusercontent.com/34928452/59424648-f1409400-8e06-11e9-85c5-d0878b56bb97.png)
![image](https://user-images.githubusercontent.com/34928452/59424656-f9003880-8e06-11e9-9bda-cf0f9e7cb8ca.png)

**Comment by mrlinjun** [comment]
my project use mysql database.

**Comment by mrlinjun** [comment]
and use springboot and mybatis

**Comment by terrymanu** [comment]
Can you describe how to cause deadlock?

**Comment by mrlinjun** [comment]
this is my config
![image](https://user-images.githubusercontent.com/34928452/59488129-420cc700-8eb1-11e9-974d-f7d2e38b34f6.png)

**Comment by mrlinjun** [comment]
> Can you describe how to cause deadlock?

this is my config
![image](https://user-images.githubusercontent.com/34928452/59488177-67013a00-8eb1-11e9-8f4a-77150d40fae7.png)

**Comment by terrymanu** [comment]
For this issue, it is hard to reproduce it. 
Can you provide codes on github?

**Comment by terrymanu** [comment]
Closed because no response anymore
