### ISSUE TITLE
mysql use function  errror o viable alternative at input 

### ISSUE THREAD

**Issue by jueyue** [apache/incubator-shardingsphere#2564]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.00.RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
update success
### Actual behavior
line 3:86 no viable alternative at input 'SUBSTRING(UPPER(MD5(CONCAT(balance,account_no,'LOVECHINA'))),'
line 3:70 mismatched input ',' expecting '='
line 3:83 mismatched input ')' expecting '='
line 3:90 mismatched input ')' expecting '='
line 5:88 no viable alternative at input 'SUBSTRING(UPPER(MD5(CONCAT(balance,account_no,'LOVECHINA'))),'
### Reason analyze (If you can)
can not support UPPER,MD5,CONCAT function
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

UPDATE test
        SET balance   = balance - 1,
            bal_check = SUBSTRING(UPPER(MD5(CONCAT(balance, account_no, 'LOVECHINA'))), 16)
        WHERE account_No = 1234 AND
              bal_check = SUBSTRING(UPPER(MD5(CONCAT(balance, account_no, 'LOVECHINA'))), 16)
              AND  balance - 1 >= 0

**Comment by jueyue** [comment]
@terrymanu  @tuohai666  four function ,but add one?  UPPER,MD5,CONCAT are you sure? i not find in rule

**Comment by tuohai666** [comment]
SUBSTRING is the point, just have a try.
