### ISSUE TITLE
How to read the configuration from ZK every time the service is restarted

### ISSUE THREAD

**Issue by xiaotianlongxing** [apache/incubator-shardingsphere#2565]
When I see the [configuration link](https://shardingsphere.apache.org/document/legacy/3.x/document/cn/manual/sharding-jdbc/usage/orchestration/) (也可以只通过注册中心读取配置) . I thought the sharding jdbc
can read the configuration from ZK every time the service is restarted.But it is a mistake, as I saw in that [issues2531](https://github.com/apache/incubator-shardingsphere/issues/2531) and [issues1924](https://github.com/apache/incubator-shardingsphere/issues/1924)
 But now,I want to read the configuration from ZK every time the service is restarted, how can I do?

**Comment by KomachiSion** [comment]
Remove datasource configuration in local properties file or yaml file, Sharding-jdbc will load configuration from registry center.

For example, configuration #2531 you provided can change to 
```
<orchestraion:registry-center id="regCenter" type="zookeeper" server-lists="localhost:2182" namespace="pay-sharding-orchestration" operation-timeout-milliseconds="1000" max-retries="3" />
<orchestraion:sharding-data-source id="shardingOrchestration" registry-center-ref="regCenter" />
```

**Comment by KomachiSion** [comment]
Also you can see other example in [incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/orchestration-example/orchestration-spring-namespace-example)

Remember to change mod to `cloud`

```
public class SpringNamespaceExample {
    
    private static ShardingType shardingType = ShardingType.SHARDING_DATABASES_AND_TABLES;
//    private static ShardingType shardingType = ShardingType.MASTER_SLAVE;
//    private static ShardingType shardingType = ShardingType.ENCRYPT;
    
//    private static boolean loadConfigFromRegCenter = false;
    private static boolean loadConfigFromRegCenter = true;

    ....

}
```

**Comment by xiaotianlongxing** [comment]
@KomachiSion oh, I see. Thank you very much
