### ISSUE TITLE
SQL syntax error, expected token is 'EQ', actual token is 'BANG_EQ', literals is '!='."

### ISSUE THREAD

**Issue by Liuwanwu** [apache/incubator-shardingsphere#2578]
left join 后添加条件，先是等于条件，然后是!=条件 ，解析失败

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by Liuwanwu** [comment]
execute sql:"from clyj_goods_order_info as a LEFT JOIN clyj_goods_order_details as b on a.p_trade_no = b.p_trade_no" is not error.But add "and b.order_source != 6" After this statement
