### ISSUE TITLE
Executing a left join statement does not equal a condition exception

### ISSUE THREAD

**Issue by Liuwanwu** [apache/incubator-shardingsphere#2580]
Just started executing this sql “from clyj_goods_order_info as a LEFT JOIN clyj_goods_order_details as b on a.p_trade_no = b.p_trade_no” is no problem。
But in this statement only added "and b.order_source != 6" is error
The Exception is “Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: io.shardingjdbc.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'EQ', actual token is 'BANG_EQ', literals is '!='.”
my version is <version>2.0.3<version>
Executed in the database is no error。
Is the syntax parsing error?

**Comment by terrymanu** [comment]
The version is too old, could you try to use new version?

**Comment by terrymanu** [comment]
No response anymore, closed for now
