### ISSUE TITLE
Dynamically modify the configuration

### ISSUE THREAD

**Issue by itsccn** [apache/incubator-shardingsphere#2585]
I don't want to use zookeeper and etcd, how do I dynamically modify actualDataNodes and other configurations? For example, I read the settings from the database to the StandardShardingStrategyConfiguration, is there a related api?

**Comment by terrymanu** [comment]
Use SPI to implement new reg center

FIY: https://shardingsphere.apache.org/document/current/en/features/spi/

**Comment by jast90** [comment]
Can I directly modify the metadata in zookeepe and will it take effect? @terrymanu
