### ISSUE TITLE
SpringBoot 2.1.1.RELEASE 自动配置数据源与Sharding自动配置冲突

### ISSUE THREAD

**Issue by weweibuy** [apache/incubator-shardingsphere#2588]
SpringBoot版本2.1.1.RELEASE; sharding-jdbc-spring-boot-starter 版本4.0.0-RC1; 
spring:
    shardingsphere:
      enabled: true
      datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/webuy_learning_0?useUnicode=true&characterEncoding=UTF-8
        username: user01
        password: user01
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/webuy_learning_1?useUnicode=true&characterEncoding=UTF-8
        username: user01
        password: user01
    sharding:
      default-data-source-name: ds
      tables:
        jit_time_order_header:
          actual-data-nodes: ds$->{0..1}.jit_time_order_header_$->{0..1}
          database-strategy:
            inline:
              shardingColumn: time_order_no
              algorithm-expression: ds$->{Math.abs(time_order_no.hashCode()) % 2}
          table-strategy:
            inline:
              sharding-column: time_order_no
              algorithm-expression: jit_time_order_header_$->{Math.abs(com.weweibuy.webuy.learning.sharing.utils.HashUtil.FNVHash1(time_order_no)) % 2}

项目启动报错:
The bean 'dataSource', defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class] and overriding is disabled.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by zuoanguo** [comment]
Has it been solved? @weweibuy
