### ISSUE TITLE
how to set all tables hint database and tables algorithmClassName

### ISSUE THREAD

**Issue by 1397649957** [apache/incubator-shardingsphere#2594]
hello ,in 4.0.0-RC1 how to set all tables hint database and tables algorithmClassName

**Comment by 1397649957** [comment]
all tables  , one  hint  algorithmClassName

**Comment by terrymanu** [comment]
I cannot get your point, maybe you need explain more. For hint, you may reference example: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/hint-example

**Comment by terrymanu** [comment]
I cannot get your point, maybe you need explain more. For hint, you may reference example: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/hint-example

**Comment by terrymanu** [comment]
Any update? Or can I close this issue soon?

**Comment by terrymanu** [comment]
Can you explain why close this issue without any reason to update?
We hope every issue have their value which should include enough information to let other user search and reference.
