### ISSUE TITLE
why can't we see 4.0.0-RC2 on search.maven.org？

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#2600]
Thanks

**Comment by terrymanu** [comment]
Not release yet, you can see https://github.com/apache/incubator-shardingsphere/releases to find release info

**Comment by AlbertTao** [comment]
Still could not find 4.0.0-RC2 on search.maven.org

**Comment by sunbufu** [comment]
> @terrymanu Still could not find 4.0.0-RC2 on search.maven.org

Still not release, please focus on  [sharding sphere releases](https://github.com/apache/incubator-shardingsphere/releases), or watch sharding sphere on gitlab.

![image](https://user-images.githubusercontent.com/14866067/60779391-2376b480-a16d-11e9-8a09-4e52cecc1794.png)

**Comment by AlbertTao** [comment]
![image](https://user-images.githubusercontent.com/6252580/60780123-c3354200-a16f-11e9-91af-e41a6e473aa2.png)
Does it's no means 4.0.0-RC2 relase alreay ?

**Comment by AlbertTao** [comment]
Oh, it's only a tag. That's confuse me at first.

**Comment by AlbertTao** [comment]
But I found some tags also publish to maven repository.
![image](https://user-images.githubusercontent.com/6252580/60780919-ead9d980-a172-11e9-839f-559bef59c7bb.png)
So when will a version be published to the maven repository?
