### ISSUE TITLE
Verify the shardingRule at the beginning

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#2601]
### Is your feature request related to a problem?
Yes. Please refer to https://github.com/apache/incubator-shardingsphere/issues/2597
### Describe the feature you would like.
It's not friendly to fire a NullPointerException in this senario.
We'd better verify the shardingRule when the application start. If the **actualDataNodes** don't match the **algorithmExpression**, the application will stop and print some meaningful information.

**Comment by sunbufu** [comment]
Hi, I can do something about verify shrding rule and print some information. But I need specific rules. Can you help me ?

**Comment by tuohai666** [comment]
Of course, please go through #2597 first, after that let's discuss the rules.

**Comment by sunbufu** [comment]
HI, I read the issue, and I replied it. Can you look at my reply <https://github.com/apache/incubator-shardingsphere/issues/2597#issuecomment-511165646> ？

**Comment by tuohai666** [comment]
@sunbufu Would you still like to enhance the verification of the shardingRule? 
The #2597 is mainly about routing to a not exist node. I think the basic verification is that the routing result should not exceed the actualDataNodes.

**Comment by sunbufu** [comment]
> @sunbufu Would you still like to enhance the verification of the shardingRule?
> The #2597 is mainly about routing to a not exist node. I think the basic verification is that the routing result should not exceed the actualDataNodes.

Yep, I can try it.

**Comment by sunbufu** [comment]
Hello, I was blocked by the way to get exact routing result. And routing grovvy expression some time like `book_${book_id % 3}`. Can you give me some advice?

**Comment by tuohai666** [comment]
I thinks you can study groovy script first and try to use the script to calculate the routing result.

**Comment by sunbufu** [comment]
> I thinks you can study groovy script first and try to use the script to calculate the routing result.

Sorry, I have no idea yet. Can you give me some advice?

**Comment by tuohai666** [comment]
It's really hard to predicate all routing results depends on the sharding rule. That is the key problem need to be resolved. I don't have available solution yet.

Please note that not all issues taged volunteer have available solutions. I suggest contributors get one or more ideas before they reply the issues, instead of just reply I have no idea.

**Comment by sunbufu** [comment]
I think the difficulty is not on groovy script, It's on how to get the case to prove sharding rule is wrong, but we can not try with each case. Maybe we can change the way of thinking, just let user input the case, like developer write unit test.

**Comment by tuohai666** [comment]
Yes, just as I said just now. It's really hard to predicate all routing results depends on the sharding rule. 

I don't think let the user input the case is a good idea. Suppose I am the user, I prefer get a NullPointerException rather than provide a set of tests in case my config is wrong.

**Comment by sunbufu** [comment]
Or we don't check it at beginning, but throw an exception with detail message when . Such as "execute shardingRule=[order_id % 3] with order_id=[3] but get an absent dataNode=[db_3], please check rule and data node in your configuration".

**Comment by tuohai666** [comment]
This prompt is OK. 
But please go through #2597 first, and find out can we recognize the exception is caused by an absent node?

**Comment by sunbufu** [comment]
I think we should add judgment in `ShardingRouter.route()`.

**Comment by tuohai666** [comment]
Look forward to you pr.

**Comment by sunbufu** [comment]
```
org.apache.shardingsphere.core.exception.ShardingException: get absent DataNode(s)=[ds_2.t_order_0], databaseStrategyMsg=[ds_${order_id % 3}], tableStrategyMsg=[t_order_${order_id % 2}], with [t_order.order_id = 2], please check rule and data node in your configuration.
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.checkRoutingResult(ParsingSQLRouter.java:157)
......
```
Can I use this error message?

**Comment by sunbufu** [comment]
I think we should check dataNode's dataSourceName and tableName to judge dataNode is legal or not. For dataSourceName, we can try to get dataSourceMeta from `DataSourceMetas.dataSourceMetaDataMap` with `RoutingUnit.dataSourceName`. For tableName, can i call `TableMetas.containsTable()` with `RoutingUnit.tableUnits.actualTableName` ?

**Comment by tuohai666** [comment]
Sounds good. I'd like to see your pr to judge whether there's performance issue.

**Comment by sunbufu** [comment]
Hello, I am almost finished it, but I am blocked by `sharding-jdbc-spring-namespace`'s unit test. 
We know SS will load MetaData on application starting. In this case, this unit test will create some table after SS load MetaData. so my code get a wrong result with outdated MetaData. Can I add a `reInitMetaData()` method in `ShardingRuntimeContext` for this?

**Comment by tuohai666** [comment]
If your codes are right, you'd better modify test cases instead of modify existing codes.

**Comment by sunbufu** [comment]
I send a PR, can U take a look? We can dicuss at here. 😁
