### ISSUE TITLE
Supported JDK question

### ISSUE THREAD

**Issue by WillWei1983** [apache/incubator-shardingsphere#2602]
## Question
If the compilation only support the Oracle jdk?
I am using the ubuntu and openJdk 8. when compile the this project from source, it encounter issue as folllows:
Failed to execute goal on project sharding-transaction-xa-narayana: Could not resolve dependencies for project org.apache.shardingsphere:sharding-transaction-xa-narayana:pom:4.0.0-RC2-SNAPSHOT: Could not find artifact sun.jdk:jconsole:jar:jdk at specified path /usr/lib/jvm/java-8-openjdk-amd64/jre/../lib/jconsole.jar
due to the jdk.

**Comment by terrymanu** [comment]
I think this is your environment's problem
