### ISSUE TITLE
org.hibernate.HibernateException: More than one row with the given identifier was found

### ISSUE THREAD

**Issue by iamzxj** [apache/incubator-shardingsphere#2603]
version：4.0
description：
In the case of sub-libraries, JPA's ManyToOne is associated with foreign key entities under multiple data sources.
![QQ图片20190624160631](https://user-images.githubusercontent.com/11895528/60001891-156b6300-969a-11e9-9133-be5061192686.png)

**Comment by terrymanu** [comment]
Maybe you should learn or understand how to use hibernate, or submit this issue to hibernate's github repo
