### ISSUE TITLE
4.0.0-RC1 源码缺少文件？

### ISSUE THREAD

**Issue by yongtaoChen** [apache/incubator-shardingsphere#2605]
`package org.apache.shardingsphere.core.parse;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.apache.shardingsphere.core.parse.antlr.autogen.PostgreSQLStatementLexer;
import org.apache.shardingsphere.core.parse.spi.ShardingParseEngine;

/**
 * Sharding parse engine for PostgreSQL.
 *
 * @author zhangliang
 */
public final class PostgreSQLShardingParseEngine implements ShardingParseEngine {
    
    @Override
    public String getDatabaseType() {
        return "PostgreSQL";
    }
    
    @Override
    public PostgreSQLParser createSQLParser(final String sql) {
        return new PostgreSQLParser(new CommonTokenStream(new PostgreSQLStatementLexer(CharStreams.fromString(sql))));
    }
}`
源码中没有找到该路径：org.apache.shardingsphere.core.parse.antlr.autogen
整个项目中也没有找到该路径下的类，如SQLServerStatementParser、PostgreSQLStatementLexer等

**Comment by karlhell** [comment]
解决了吗？我今天拉代码，也没有SQLServerStatementParser这个类，请问怎么解决的？

**Comment by yongtaoChen** [comment]
编译后自动生成了




------------------ 原始邮件 ------------------
发件人: "karlhell"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 下午4:33
收件人: "apache/incubator-shardingsphere"<incubator-shardingsphere@noreply.github.com>;
抄送: "南柯一梦"<674885281@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [apache/incubator-shardingsphere] 4.0.0-RC1 源码缺少文件？ (#2605)




解决了吗？我今天拉代码，也没有SQLServerStatementParser这个类，请问怎么解决的？

**Comment by THMAIL** [comment]
You may execute `mvn install` to generate source codes under the package autogen.
