### ISSUE TITLE
The implementation of "toString()" method of Interface "Alterable" in "TablePlaceholder" related questions?

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#2606]
## Question
The "toString(final RoutingUnit routingUnit, final Map<String, String> logicAndActualTables)" method in "TablePlaceholder". "routingUnit" is not used in the method definition. The "routingUnit" is useful for another two implementation classes : IndexPlaceHolder,InsertValuePlaceHolder. So, in order to keep the "Alterable" is suitable for the method caller and make the code in "TablePlaceHolder" more meaningful. My suggestion is below:
original code is

```java
    @Override
    public String toString(final RoutingUnit routingUnit, final Map<String, String> logicAndActualTables) {
        String actualTableName = logicAndActualTables.get(logicTableName);
        actualTableName = null == actualTableName ? logicTableName : actualTableName;
        return Joiner.on("").join(quoteCharacter.getStartDelimiter(), actualTableName, quoteCharacter.getEndDelimiter());
    }
```

Then ,split the method into two pieces.

```java
   @Override
    public String toString(final RoutingUnit routingUnit, final Map<String, String> logicAndActualTables) {
             return toString(logicAndActualTables);
    }
```

```java
private String toString(final Map<String, String> logicAndActualTables){
        String actualTableName = logicAndActualTables.get(logicTableName);
        actualTableName = null == actualTableName ? logicTableName : actualTableName;
        return Joiner.on("").join(quoteCharacter.getStartDelimiter(), actualTableName, quoteCharacter.getEndDelimiter());
}
```

This will make clearly that the "routingUnit" is not used.And the reason why use it, is only for adaptable to "Alterable" Interface. 
It is just an immature suggestion, I'd like to discuss this question with you.
Thanks a lot.

**Comment by tristaZero** [comment]
Hi, it is great suggestion, but placeholder will be combined with token object, so maybe those toString() functions will be changed afterwards. I think maybe it's better to do those optimizations after we finish the combination of placeholder object and token object. What do you think?

**Comment by wgy8283335** [comment]
@tristaZero. Thank you. I agree with you. So, shall I close this issue?
