### ISSUE TITLE
It throw NullException which use the tk-mapper's selectByPrimaryKey

### ISSUE THREAD

**Issue by tutuerhao** [apache/incubator-shardingsphere#2609]
## Bug Report
![image](https://user-images.githubusercontent.com/29938085/60146152-09e37d80-97fb-11e9-8700-aae14781dfba.png)
![image](https://user-images.githubusercontent.com/29938085/60146154-0c45d780-97fb-11e9-8b1c-17f6d617e362.png)

### Which version of ShardingSphere did you use?
3.1.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

**Comment by terrymanu** [comment]
the version 3.1.0 is never released, please choose a release one.
FIY: https://github.com/apache/incubator-shardingsphere/releases
