### ISSUE TITLE
Support for SQL interception is recommended

### ISSUE THREAD

**Issue by keji94** [apache/incubator-shardingsphere#2610]
## Feature Request
Support for SQL interception
### Is your feature request related to a problem?
no
### Describe the feature you would like.
I recommend support for intercepting SQL without sharding keys.

for example:
table:t_order    sharding key : order_id

for the sql: select * from t_order where id = 123 

i hope ShardingSphere cound intercept this SQL

**Comment by terrymanu** [comment]
I prefer no, because route without sharding key is a normal function which to route to all data nodes for OLAP

**Comment by keji94** [comment]
support t

> I prefer no, because route without sharding key is a normal function which to route to all data nodes for OLAP

support taht,not means must do that。maybe someone does not need route without sharding key。SharidingSphere need give devloper a choose

**Comment by terrymanu** [comment]
As a product manager, I prefer make ShardingSphere simple. 
The better rule is like SQL without sharding key just route to all data nodes; SQL with sharding key route to correct data nodes for now.
User can control their SQL by themselves if they want.

**Comment by terrymanu** [comment]
May I close this issue?

**Comment by keji94** [comment]
> May I close this issue?

yeah! thx
