### ISSUE TITLE
Does Oracle's analysis function "keep(dense_rank first/last)" support?

### ISSUE THREAD

**Issue by lthaoshao** [apache/incubator-shardingsphere#2611]
Version: 4.0.0-RC1
Database type: Oracle 11g

Problem Description:
We used Oracle's analytic function "keep(dense_rank first/last)" in the application, but in the use of sharding-jdbc, it does not seem to give the correct result. 
I tracked the code. When parsing "where", the parser didn't find the "where" field, which caused the fragmentation condition in "where" to be unrecognizable, which invalidated the sharding. The database found was random and did not work. The operation of "sharding-tables" directly uses the original table in SQL.

SQL:
`        select
            sum(case when status = 'DID' then 1 else 0 end) FINISHED,
            sum(case when hit_source = 'LIB' then 1 else 0 end) LIB,
            sum(case when hit_source = 'EXTCHAL' then 1 else 0 end) EXTCHAL,
            sum(case when merchant_fee is null then 0 else to_number(merchant_fee,'999999.99') end) MERCHANT_FEE,
            sum(case when channel_fee is null then 0 else to_number(channel_fee,'999999.99')  end) CHANNEL_FEE,
            max(case when merchant_fee is null then 0 else to_number(merchant_fee,'999999.99') end) KEEP (DENSE_RANK FIRST order by out_request_no) max_fee
        from  TB_ORDER d
        where 1=1
        and gmt_create between #{startTime,jdbcType=TIMESTAMP}
        and #{endTime, jdbcType=TIMESTAMP}`

**Comment by terrymanu** [comment]
Not yet, oracle is not a mainly support for us, so we have already open spi for oracle parse. If somebody interested with oracle, please pr on oracle module.

**Comment by lthaoshao** [comment]
> Not yet, oracle is not a mainly support for us, so we have already open spi for oracle parse. If somebody interested with oracle, please pr on oracle module.

Thanks, I will.
