### ISSUE TITLE
Query is more slowly after using sharding-jdbc

### ISSUE THREAD

**Issue by fdlzp** [apache/incubator-shardingsphere#2612]
### Description：
Query becomes more slowly after using sharding-jdbc （MYSQL）.
(Oracle：query is more quickly，just in exception.)

### My environment：

springboot + JPA + MySQL+sharding-jbdc    VS    **_springboot + JPA + MySQL_**（control group）

**mysql：_8.0.16_**
cpu:  G4560 3.5GHz
RAM:  8G
win10 x64

### Which version of ShardingSphere did you use?
 4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Data Node Configuration：
spring.shardingsphere.sharding.tables.t_basic_up_msg.actual-data-nodes=
sharding-test.t_basic_up_msg_20190${1..9}_${1..2},sharding-test.t_basic_up_msg_2019${10..12}_${1..2}

Sharding_test（the amount of data：20million）
├── t_basic_up_msg_201901_1
├── t_basic_up_msg_201901_2
├── t_basic_up_msg_201902_1
├── t_basic_up_msg_201902_2
├── t_basic_up_msg_201903_1
├── t_basic_up_msg_201903_2
..........
├── t_basic_up_msg_201911_1
├── t_basic_up_msg_201911_2
├── t_basic_up_msg_201912_1
├── t_basic_up_msg_201912_2

（There are 24 tables in total.  **1 table each  half month**）

**VS**

（database of control group）
Sharding_test1（another database，nosharding，the amount of data：20million）
├── t_basic_up_msg_

### Entity
![图片](https://user-images.githubusercontent.com/44960833/60313674-9d9b8200-9992-11e9-83ff-e1342d2ecee5.png)

### Sharding Key
_receipt_time (type :datetime)_

### type of primary key
_UUID_

### configuration

`#Single` Database ，multiple tables

spring.shardingsphere.datasource.names=sharding-test,sharding-test1

spring.shardingsphere.datasource.sharding-test.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.sharding-test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.sharding-test.jdbc-url=jdbc:mysql://localhost:3306/sharding_test?useSSL=false&serverTimezone=CTT&characterEncoding=utf-8
spring.shardingsphere.datasource.sharding-test.username=root
spring.shardingsphere.datasource.sharding-test.password=root

spring.shardingsphere.datasource.sharding-test1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.sharding-test1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.sharding-test1.jdbc-url=jdbc:mysql://localhost:3306/sharding_test?useSSL=false&serverTimezone=CTT&characterEncoding=utf-8
spring.shardingsphere.datasource.sharding-test1.username=root
spring.shardingsphere.datasource.sharding-test1.password=root

spring.shardingsphere.sharding.tables.t_basic_up_msg.actual-data-nodes=\
  sharding-test.t_basic_up_msg_20190${1..9}_${1..2},sharding-test.t_basic_up_msg_2019${10..12}_${1..2}

spring.shardingsphere.sharding.tables.t_basic_up_msg.table-strategy.standard.sharding-column=receipt_time

spring.shardingsphere.sharding.tables.t_basic_up_msg.table-strategy.standard.precise-algorithm-class-name=com.bd.demo.algorithm.MyPreciseShardingTableAlgorithm

spring.shardingsphere.sharding.tables.t_basic_up_msg.table-strategy.standard.range-algorithm-class-name=com.bd.demo.algorithm.MyRangeShardingTableAlgorithm

`#spring.shardingsphere.props.sql.show=true`

### sharding rule
`public final class MyPreciseShardingTableAlgorithm implements PreciseShardingAlgorithm<Date> {
   @Override
     public String doSharding(final Collection<String> tableNames, final PreciseShardingValue<Date> preciseShardingValue) {
   //System.out.println("tableNames:" + tableNames + ",preciseShardingValue:" + preciseShardingValue);
        StringBuffer table_name = new StringBuffer("t_basic_up_msg");

        String year = String.format("%tY", preciseShardingValue.getValue());
        String mon = String.format("%tm", preciseShardingValue.getValue());

        table_name.append("_");
        table_name.append(year);
        table_name.append(mon);

        String day =String.format("%td",preciseShardingValue.getValue());
        String firstHalfMon = "_1";
        String secondHalfMon = "_2";
        int dayInt = Integer.parseInt(day);
        if(dayInt<=15){
            table_name.append(firstHalfMon);

        }else{
            table_name.append(secondHalfMon);

        }

        for (String each : tableNames) {
            if (each.equals(table_name.toString())){
                return each;
            }
        }

        throw new UnsupportedOperationException();

    }
}`

### API
/test/findByReceiptTime
`@RequestMapping("/findByReceiptTime")
    @ResponseBody
    public List<TBasicUpMsg> findByReceiptTime() throws Exception{

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date formatDate = null;

        formatDate = sdf.parse("2019-01-01 00:04:10");

        List<TBasicUpMsg> cs=  tBasicUpMsgService.findByReceiptTime(formatDate);

        return cs;

    }

sercice:
   public List<TBasicUpMsg> findByReceiptTime(Date receiptTime) {

        List<TBasicUpMsg> tBasicUpMsgs= tBasicUpMsgRepository.findByReceiptTime(receiptTime);
        return tBasicUpMsgs;
    }

repository:
@Repository
public interface TBasicUpMsgRepository extends JpaRepository<TBasicUpMsg, String>,JpaSpecificationExecutor<TBasicUpMsg> {

    public List<TBasicUpMsg> findByReceiptTime(Date receiptTime);
   
}`

### Expected behavior

query more quickly

### Actual behavior
query more slowly
insert more quickly

### Reason analyze
don't know.

if I Execute SQL separately，the speed is almost the same（Whether sharding-jdbc is used or not ）.

May be the amount of data is too small（20million）.
（But the amount of oracle is only 800w，the improvement is obvious.）

My expection:
Is this normal?
It would be better if you can give me some suggestions.

Thank you!

**Comment by fdlzp** [comment]
**result:
sharding:**
![图片](https://user-images.githubusercontent.com/44960833/60169053-8ba5cc00-9838-11e9-87ae-7f47ea6bb20a.png)
**noshading:**
![图片](https://user-images.githubusercontent.com/44960833/60169111-ac6e2180-9838-11e9-824d-773f1c97af99.png)

**Comment by fdlzp** [comment]
from https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/stress-test/
![图片](https://user-images.githubusercontent.com/44960833/60170208-98c3ba80-983a-11e9-8d54-f0684a4290d6.png)

**Comment by terrymanu** [comment]
please translate Chinese word to english first

**Comment by fdlzp** [comment]
It's done.

**Comment by tuohai666** [comment]
@fdlzp Where's the SQLs? Please show me the SQLs in a very precise way, like `select * from t_order;`

**Comment by fdlzp** [comment]
> 
> 
> @fdlzp Where's the SQLs? Please show me the SQLs in a very precise way, like `select * from t_order;`
**sharing**
`select tbasicupms0_.basic_up_msg_id as basic_up1_0_, tbasicupms0_.basic_up_msg_no as basic_up2_0_, tbasicupms0_.cust_sender_ic as cust_sen3_0_, tbasicupms0_.data_source as data_sou4_0_, tbasicupms0_.data_type as data_typ5_0_, tbasicupms0_.forward_number as forward_6_0_, tbasicupms0_.hex_sms as hex_sms7_0_, tbasicupms0_.is_del as is_del8_0_, tbasicupms0_.palt_receive_ic as palt_rec9_0_, tbasicupms0_.process_status as process10_0_, tbasicupms0_.process_time as process11_0_, tbasicupms0_.project_id as project12_0_, tbasicupms0_.receipt_time as receipt13_0_ from t_basic_up_msg_201901_1 tbasicupms0_ where tbasicupms0_.receipt_time='2019-01-01 00:04:10.0'`
    
    range
`select tbasicupms0_.basic_up_msg_id as basic_up1_0_, tbasicupms0_.basic_up_msg_no as basic_up2_0_, tbasicupms0_.cust_sender_ic as cust_sen3_0_, tbasicupms0_.data_source as data_sou4_0_, tbasicupms0_.data_type as data_typ5_0_, tbasicupms0_.forward_number as forward_6_0_, tbasicupms0_.hex_sms as hex_sms7_0_, tbasicupms0_.is_del as is_del8_0_, tbasicupms0_.palt_receive_ic as palt_rec9_0_, tbasicupms0_.process_status as process10_0_, tbasicupms0_.process_time as process11_0_, tbasicupms0_.project_id as project12_0_, tbasicupms0_.receipt_time as receipt13_0_ from t_basic_up_msg_201911_1 tbasicupms0_ where tbasicupms0_.receipt_time between  '2019-11-01 00:00:00.0' and '2019-11-03 00:00:00.0'`

**nosharding**
`select tbasicupms0_.basic_up_msg_id as basic_up1_0_, tbasicupms0_.basic_up_msg_no as basic_up2_0_, tbasicupms0_.cust_sender_ic as cust_sen3_0_, tbasicupms0_.data_source as data_sou4_0_, tbasicupms0_.data_type as data_typ5_0_, tbasicupms0_.forward_number as forward_6_0_, tbasicupms0_.hex_sms as hex_sms7_0_, tbasicupms0_.is_del as is_del8_0_, tbasicupms0_.palt_receive_ic as palt_rec9_0_, tbasicupms0_.process_status as process10_0_, tbasicupms0_.process_time as process11_0_, tbasicupms0_.project_id as project12_0_, tbasicupms0_.receipt_time as receipt13_0_ from t_basic_up_msg tbasicupms0_ where tbasicupms0_.receipt_time='2019-01-01 00:04:10.0'`

      range
`select tbasicupms0_.basic_up_msg_id as basic_up1_0_, tbasicupms0_.basic_up_msg_no as basic_up2_0_, tbasicupms0_.cust_sender_ic as cust_sen3_0_, tbasicupms0_.data_source as data_sou4_0_, tbasicupms0_.data_type as data_typ5_0_, tbasicupms0_.forward_number as forward_6_0_, tbasicupms0_.hex_sms as hex_sms7_0_, tbasicupms0_.is_del as is_del8_0_, tbasicupms0_.palt_receive_ic as palt_rec9_0_, tbasicupms0_.process_status as process10_0_, tbasicupms0_.process_time as process11_0_, tbasicupms0_.project_id as project12_0_, tbasicupms0_.receipt_time as receipt13_0_ from t_basic_up_msg tbasicupms0_ where tbasicupms0_.receipt_time between '2019-11-01 00:00:00.0' and '2019-11-03 00:00:00.0'`

**Comment by fdlzp** [comment]
Now it's normal after I created another index and then droppd it.
It's really puzzling！！！
I’m looking for the root cause.(I don‘t know if it is related to the version of MySQL
)

**Comment by tuohai666** [comment]
I am thinking for a while. I guess, the samples are too few. and the test results are not stable.
You can increase the querys to 5 million, maybe you will find something.

**Comment by fdlzp** [comment]
I‘ll try it later.
I can confirm that the index cause the problem. Because the improvement is obvious now.
Thank you for your time.

**Comment by fdlzp** [comment]
Another question:
 How do we create indexes after using sharding? 
after

**Comment by fdlzp** [comment]
Hello I hava a new question.
**How should we create index after using sharding-jdbc？**
The sharding key is named receipt_time (type :datetime).
I just create an index like `ALTER TABLE t_basic_up_msg ADD INDEX idx_upmsg_receiptTime(receipt_time);`

and then
query become more slowly(It's obvious，slower 3 times).

Any suggestion?

**Comment by tuohai666** [comment]
You can open a new issue for the new question.

**Comment by fdlzp** [comment]
ok
