### ISSUE TITLE
mysql in查询，列表大于1000+时，预编译parseInCondition耗时2.5s+

### ISSUE THREAD

**Issue by inobaby** [apache/incubator-shardingsphere#2616]
**问题背景：** 
线上报警->接口响应超时->in大列表查询导致->查询mysql慢日志sql执行并不慢->于是开始看源码

 **问题重现条件：** 
in查询列表大于1000，必现；我本机in条件1000个耗时2.5s+

 **问题原因：** 
1.最初定位到io.shardingsphere.core.parsing.parser.clause.WhereClauseParser#parseInCondition方法执行过久
2.继续定位到io.shardingsphere.core.parsing.lexer.analyzer.Tokenizer#scanSymbol这个方法，在while循环中会有substring操作，且执行频率很高
 **我测试in列表中数量1200个时，substring执行次数近300万次，已作出了优化方案，请看下图** 
![输入图片说明](https://images.gitee.com/uploads/images/2019/0627/110543_ba00692b_524795.png "sharding-sphere-tokenizer-fix.png")
![输入图片说明](https://images.gitee.com/uploads/images/2019/0627/104942_059190a1_524795.png "sharding-sphere-symbol-fix.png")

 **版本信息：** 
sharding-sphere版本：3.0.0.M3
对比了3.1.0.M3和master两个版本，该处逻辑没有改动

 **我的问题：** 
通过梳理源码找到了问题的原因，并给出了最小改动的逻辑优化方案，对作者的设计思路没有任何改动，想征求一下作者的意见，这种优化的影响面有多大，适不适合线上使用？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by Ah39** [comment]
关注中
