### ISSUE TITLE
insert null key error

### ISSUE THREAD

**Issue by M-make** [apache/incubator-shardingsphere#2622]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
![image](https://user-images.githubusercontent.com/35563513/60314879-d50c2d80-9996-11e9-933a-ff225661b11d.png)
insert success
### Actual behavior
![image](https://user-images.githubusercontent.com/35563513/60314841-b0b05100-9996-11e9-95ac-5d389e0a8e5e.png)
insert error
### Reason analyze (If you can)
unknown
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
insert primary key null will report exception
### Example codes for reproduce this issue (such as a github link).
https://github.com/M-make/jnote   -> com.jdbc.sharding.TestSharding#testSharding

**Comment by M-make** [comment]
![image](https://user-images.githubusercontent.com/35563513/60317282-f114cc80-99a0-11e9-9d2a-a8f0a1fa14fe.png)

Here, the sql parser parses the first null of values ​​into SQLTextExpression, causing the final SQL to become insert into pes_cs (shop_id,name) value ('null','ee')

**Comment by tuohai666** [comment]
Duplicate with https://github.com/apache/incubator-shardingsphere/issues/2538.
Please try 4.0.0-RC2-SNAPSHOT.

**Comment by M-make** [comment]
I can't find 4.0.0-RC2-SNAPSHOT jar from maven repository

**Comment by tuohai666** [comment]
You can build it in local.
