### ISSUE TITLE
How should we add index after using sharding-jdbc？

### ISSUE THREAD

**Issue by fdlzp** [apache/incubator-shardingsphere#2624]
**Description：**

Query becomes more slowly after create **index**.（sharding VS nosharing） 

**My environment：**

springboot + JPA + MySQL+sharding-jbdc VS springboot + JPA + MySQL（control group）

mysql：8.0.16

**Which version of ShardingSphere did you use?**

4.0.0-RC1

**Which project did you use? Sharding-JDBC or Sharding-Proxy?**

Sharding-JDBC

**Data Node Configuration：**

spring.shardingsphere.sharding.tables.t_basic_up_msg.actual-data-nodes=
sharding-test.t_basic_up_msg_20190${1..9}${1..2},sharding-test.t_basic_up_msg_2019${10..12}${1..2}

Sharding_test（the amount of data：20million）
├── t_basic_up_msg_201901_1
├── t_basic_up_msg_201901_2
..........
├── t_basic_up_msg_201911_1
├── t_basic_up_msg_201911_2
├── t_basic_up_msg_201912_1
├── t_basic_up_msg_201912_2

（There are 24 tables in total. 1 table each half month）

VS

（database of control group）
Sharding_test1（another database，nosharding，the amount of data：20million）
├── t_basic_up_msg_

**Entity**
![图片](https://user-images.githubusercontent.com/44960833/60333494-cbe98380-99cb-11e9-82e2-118ace509cc0.png)

### Sharding Key

receipt_time **(type :datetime)**

type of primary key：UUID

### create index sql
**sharidng :**
`ALTER TABLE t_basic_up_msg_201901_1 ADD INDEX idx_upmsg011_receiptTime(RECEIPT_TIME); ALTER TABLE t_basic_up_msg_201901_2 ADD INDEX idx_upmsg012_receiptTime(RECEIPT_TIME); ....... 
ALTER TABLE t_basic_up_msg_201912_1 ADD INDEX idx_upmsg121_receiptTime(RECEIPT_TIME); ALTER TABLE t_basic_up_msg_201912_2 ADD INDEX idx_upmsg122_receiptTime(RECEIPT_TIME);`
**nosharding:**
`ALTER TABLE t_basic_up_msg ADD INDEX idx_upmsg_receiptTime(receipt_time);`

### query sql
`select basic_up_msg_id , basic_up_msg_no ,cust_sender_ic,data_source, data_type, forward_number, hex_sms,is_del,palt_receive_ic, process_status, process_time , project_id , receipt_time from t_basic_up_msg where receipt_time='2019-01-01 00:04:10.0'`

### Expected behavior

query more quickly

### Actual behavior

query more slowly
insert more quickly

### Reason analyze
not clear
the type of sharding key and my index is datetime

**My expection:**
It would be better if you can give me some suggestions.

Thank you!

**Comment by tristaZero** [comment]
> The question is how should we add index after using sharding-jdbc？

`ALTER TABLE t_basic_up_msg ADD INDEX idx_upmsg(RECEIPT_TIME);` can be executed through Sharding-JDBC?
@fdlzp

**Comment by fdlzp** [comment]
> 
> 
> > The question is how should we add index after using sharding-jdbc？
> 
> `ALTER TABLE t_basic_up_msg ADD INDEX idx_upmsg(RECEIPT_TIME);` can be executed through Sharding-JDBC?
> @fdlzp

I just execute it through navicat

**Comment by fdlzp** [comment]
the amount of data：20million
query sql： above

**Average Response Time**
sharding： 2s      nosharding：20s

    after add index
   sharding： 700ms    nosharding：250ms

 **if it is possible ：**

Sharding-jdbc needs fixed time to parse/optimize..../merge SQL.
But the amount of data is not large enough.
The response time is too  short after add index.
This cause we need more time to query after using sharding-jdbc.

Do you have any other ideas? or any suggestions?

I'm increasing the amount of data.But it needs time.

**Comment by fdlzp** [comment]
the amount of data：120million
query sql： above

Average Response Time
sharding    <  nosharding

after add index

sharding： 700ms nosharding：200ms

and
![图片](https://user-images.githubusercontent.com/44960833/60479555-d4d2a180-9cb8-11e9-916e-b14cf70cef03.png)

Is it normal? (Single Database ，multiple tables)

**Comment by tristaZero** [comment]
Hi, i am confused with your question, let us make ie clearer.
You want to improve the query speed for per query, right?
After you add index for sharding tables and table without sharding rule, you find the query on no-sharding table is faster than sharding tables?
But the situation is just on the contrary before adding index for sharding tables and table without sharding rule?
Your expectation is to make queries on sharding tables much faster than no-sharding table after adding index?

**Comment by fdlzp** [comment]
> 
> 
> Hi, i am confused with your question, let us make it clearer.
> You want to improve the query speed for per query, right?
> After you add index for sharding tables and table without sharding rule, you find the query on no-sharding table is faster than sharding tables?
> But the situation is just on the contrary before adding index for sharding tables and table without sharding rule?
> Your expectation is to make queries on sharding tables much faster than no-sharding table after adding index?

Sorry for the late reply.
 sharding tables VS one table .
YES.

**Comment by tristaZero** [comment]
Actually, queries with indexes should be faster thant ones without indexes. We need more tests and information to judge whether it is shardingjdbc's problem or not.
Firsty, can you compare query time on sharding tables with index and sharding tables without index? Query time on one table with index and ones without index?

Second, when you execute one query, can you get the query time that shardingjdbc uses and database uses respectively?

**Comment by tristaZero** [comment]
Sorry, we can not get your reply.
> If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
