### ISSUE TITLE
Which transaction type should in sharding-proxy

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2625]
Hello, I used sharding-proxy, which transaction type should i configure in the server.yaml, Local ? BASE or XA ? whats the difference about this three types ?
I encountered a problem when i use proxy to connect mysql. if I open a trancation in the programn code, start transaction and then insert into test_update(uname,addr) values('Daixin','Jiaxing') and then select * from test_update where uname='Daixin', you know i can't get the desired result before  commit(end the transaction), why ? but if i dont use proxy connect to mysql directly, it works.

eg.
start transaction;
insert into test_update(uname,addr) values('Daixin','Jiaxing');
select * from test_update where uname='Daixin';
commit;
before the "commit;"， you cant get result by "select * from test_update where uname='Daixin';"

In this case, i configed transaction type to be "LOCAL"  and also try "BASE" in server.yaml.

**Comment by cherrylzhao** [comment]
hi, please tell us your proxy version, and which client your program use? python or java?

**Comment by Myshiner** [comment]
Hi, thx for ur reply, we use java , i think i get the reason. It maybe due to the master-slave configure, coz if i start a transaction in the program including insert and select operation, the insert route to master node and the select route to slave node, but u cant get any results by selecting until the transaction end.
Anyway, thank u.

**Comment by cherrylzhao** [comment]
yes, distribute transaction will not effect in master-slave configuration.
would you please close this issue?
