### ISSUE TITLE
使用 分布式事务引入 shardingsphere-spi-impl项目对应4.0.0.RC2的代码问题

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#2630]
io.shardingsphere.transaction.base.hook.revert.executor.SQLRevertExecutorContext
这个类中找不到import org.apache.shardingsphere.core.optimize.result.OptimizeResult;这个类，如若版本是gitee中shrding-core 2048中，这个类是有的，但在github中2548版本中这个类没有。引入这两个任何一个，都会造成有些类提示找不到。

**Comment by mygitdds** [comment]
项目比较急需要解决这个问题。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
