### ISSUE TITLE
Sharing-transaction-base-saga is an official example in the process of implementing-Saga with Sharing Distributed Transaction BASE. There are many kinds of hints that can not be found in the process of introducing Shardingsphere 4.0.0-RC2 SNAPSHOT.

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#2631]
Using GitHub to provide the latest version of Shardingsphere 4.0.0-RC2 prompts io. shardingsphere. transaction. base. hook. revert. executor can not find the entity class Optimize Result, and other prompts can not find the entity class. If using Shardingsphere 4.0.0-RC2 in gitee, more classes can not be found.

**Comment by cherrylzhao** [comment]
hi, saga implementation have not merge into ShardingSphere branch.
you should package it from our [spi-impl](https://github.com/OpenSharding/shardingsphere-spi-impl) project.

**Comment by mygitdds** [comment]
What I saw did not solve the problem I saw. Let me bring it up together, because I can only run here with mavean install. I don't know if there are any problems below.
package io.shardingsphere.transaction.base.hook.revert.executor.insert Class name InsertSQLRevertContext InsertOptimizeResult and InsertOptimizeResultUnit no find  

OptimizeResult cannot be found in the entity class SQLRevertExecutorContext  sqlRouteResult.getSqlStatement() and sqlRouteResult.getOptimizeResult(); Method Tips Not Found

**Comment by mygitdds** [comment]
gitee Edition package org.apache.shardingsphere.core.optimize.result.insert  is  sharding-transaction-base-saga  project  package io.shardingsphere.transaction.base.hook.revert Necessary

**Comment by mygitdds** [comment]
@cherrylzhao What I saw did not solve the problem I saw. Let me bring it up together, because I can only run here with mavean install. I don't know if there are any problems below.
package io.shardingsphere.transaction.base.hook.revert.executor.insert Class name InsertSQLRevertContext InsertOptimizeResult and InsertOptimizeResultUnit no find

OptimizeResult cannot be found in the entity class SQLRevertExecutorContext sqlRouteResult.getSqlStatement() and sqlRouteResult.getOptimizeResult(); Method Tips Not Found

gitee Edition package org.apache.shardingsphere.core.optimize.result.insert is sharding-transaction-base-saga project package io.shardingsphere.transaction.base.hook.revert Necessary

**Comment by cherrylzhao** [comment]
we have not update gitee for several months, please use GitHub source.
you can have a try for 4.0.0-RC1 for saga as we have not tag 4.0.0-RC2 in spi-impl

**Comment by mygitdds** [comment]
@cherrylzhao  ok I'll try

**Comment by mygitdds** [comment]
@cherrylzhao  I tried as if I couldn't.

**Comment by mygitdds** [comment]
@cherrylzhao I found that some of the contents are classes in the current version. 4.0.0-RC1 I changed to this version, and more class hints could not be found.

**Comment by cherrylzhao** [comment]
please try to solve the problem by following order.
  1. git clone https://github.com/OpenSharding/shardingsphere-spi-impl.git
  2. git checkout 4.0.0-RC1 for spi, then do mvn clean install -DskipTests
  3. git checkout 4.0.0-RC1 for shardingsphere-example, then run saga transaction.

**Comment by mygitdds** [comment]
@cherrylzhao Thank you

**Comment by cherrylzhao** [comment]
would you please close this issue if possible.
