### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [apache/incubator-shardingsphere#2644]
Hi
The following lines have cryptographic API misuses. <br> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 65: API name => Cipher:<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 58: API name => Cipher:<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 72: API name => SecretKeySpec:<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 71: API name => Cipher:First parameter (with value "AES") should be any of AES/{CBC, GCM, PCBC, CTR, CTS, CFB, OFB}<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 65: API name => Cipher:<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 72: API name => SecretKeySpec:<BR> File name => sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java: Line number => 58: API name => Cipher:<BR>

**Comment by terrymanu** [comment]
duplicate with #2643
