### ISSUE TITLE
API has no documentation comment and does not know how to use it

### ISSUE THREAD

**Issue by shihzenq** [apache/incubator-shardingsphere#2647]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/manual/
