### ISSUE TITLE
When using @Transactional , How can I choose the datasource (master or slave) in the transaction??

### ISSUE THREAD

**Issue by yufan022** [apache/incubator-shardingsphere#2649]
---
sharding-jdbc-spring-boot-starter 3.1.0
---

Hi:
  I hava a question. When i use spring annotation '@Transactional' .
  How can I choose the datasource (master or slave) in the transaction?

in transaction example:
  select -- slave
  insert -- master
  select -- master
  select -- master
but i want the result like this :
  select -- slave
  insert -- master
  select -- master
  Sometimes , I want change the datasource to slave .
  select -- slave <------ so how can i do this?

**Comment by terrymanu** [comment]
ShardingSphere design as: If there is write operation in the same thread and database connection, all the following read operations are from the master database to ensure data consistency.

So if you using ShardingSphere, you can not query from slave after updated.

FYI: https://shardingsphere.apache.org/document/current/en/features/read-write-split/core-features/

**Comment by yufan022** [comment]
> ShardingSphere design as: If there is write operation in the same thread and database connection, all the following read operations are from the master database to ensure data consistency.
> 
> So if you using ShardingSphere, you can not query from slave after updated.
> 
> FYI: https://shardingsphere.apache.org/document/current/en/features/read-write-split/core-features/

I know this is for data consistency.
sometimes i need switch datasource to slave in transaction, can i do this from some api?

**Comment by yufan022** [comment]
@terrymanu

**Comment by terrymanu** [comment]
No, the API is unnecessary for most scenario. 
As a product manager, I prefer do not add this API, because do not consider about data consistency is incorrect behaviour.

If some special scenario you needed, you may fork and do it by yourself.

**Comment by yufan022** [comment]
> No, the API is unnecessary for most scenario.
> As a product manager, I prefer do not add this API, because do not consider about data consistency is incorrect behaviour.
> 
> If some special scenario you needed, you may fork and do it by yourself.

l got it.  thank you very much.

**Comment by nimo10050** [comment]
> ShardingSphere design as: If there is write operation in the same thread and database connection, all the following read operations are from the master database to ensure data consistency.
> 
> So if you using ShardingSphere, you can not query from slave after updated.
> 
> FYI: https://shardingsphere.apache.org/document/current/en/features/read-write-split/core-features/

In my use case, the above description is incorrect。


case：

```java
public class AccountService {
    @Transactional
    public void test(String userId, BigDecimal num) {
        // step1,  in current transaction,  insert a data
        accountMapper.insertAccount(new Account(userId, num));

        // step 2,  start a new transaction,  query all data
        accountService2.test();

        // step3, query all again.
        accountMapper.selectAll();
    }
}

public class AccountService2 {
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void test() {
        accountMapper.selectAll();
    }

}
```

result：

step1：insert data to master db
step2：data from master db
step3： query data from slave db

when step1 and step2 in the same connection，step2  dose not query data from master db。

why？ it is bug？
