### ISSUE TITLE
Integrating  sharding-transaction-base-saga 4.0.0-RC1

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#2651]
Integrating sharding-transaction-base-saga to configure saga. properties file with saga. persistence. enabled = true, and then configuring saga. persistence. ds. content, resulting in SpringBootConfiguration. dataSource () method creating dataSource error subsequently leading to

Java.util.Service Configuration Error: org.apache.shardingsphere.transaction.spi.ShardingTransaction Manager: Provider.shardingsphere.transaction.saga.SagaShardingTransaction Manager can not be instantiated

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by cherrylzhao** [comment]
@mygitdds please make sure saga-example runnable in your local environment.

**Comment by mygitdds** [comment]
If you don't configure saga. persistence. enabled = true and  saga. persistence. ds. my project, you can run.

**Comment by mygitdds** [comment]
@If you don't configure saga. persistence. enabled = true and saga. persistence. ds. my project, you can run.

**Comment by mygitdds** [comment]
@cherrylzhao  Saga-example is not configured persistence I have referred to, if not configured persistence, the project can run.

**Comment by cherrylzhao** [comment]
your project means our example? or your test project?

**Comment by mygitdds** [comment]
@cherrylzhao It's my development project.

**Comment by mygitdds** [comment]
@cherrylzhao  Sharing-transaction-base-saga source code has been read and it feels OK. I am not quite sure what caused the SpringBootConfiguration. dataSource () method error in org. apache. shardingsphere. shardingjdbc. spring. boot.

**Comment by mygitdds** [comment]
@cherrylzhao  When I used to do this dome, I didn't do business, so now I have this problem.

**Comment by cherrylzhao** [comment]
how can I reproduce your problem? can you push your test-project to GitHub?

**Comment by mygitdds** [comment]
@cherrylzhao  ok  My project is on gitee. I'll give you a project address.

**Comment by mygitdds** [comment]
@cherrylzhao  https://gitee.com/shengnong_1/swallowBird.git

**Comment by mygitdds** [comment]
@cherrylzhao  I've modified the code, which is available. This is a spring cloud project, and you start the Eureka project and the BusinessSystem.

**Comment by cherrylzhao** [comment]
ok, I'll check it later.

**Comment by mygitdds** [comment]
@cherrylzhao Thank you

**Comment by cherrylzhao** [comment]
which branch should I checkout, master?

**Comment by mygitdds** [comment]
@cherrylzhao  Direct in master

**Comment by mygitdds** [comment]
@cherrylzhao You pull down the code. I just had two configuration files not submitted.

**Comment by mygitdds** [comment]
@cherrylzhao 
I looked at the source code of saga-4.0.0RC1 and reasonably configured saga. persistence. ds. The data source was instantiated directly in the process of instantiating the SagaSharingTransaction Manager object, but I don't know why it affected. Sharing failed in the project of creating a dataSource into a container，（org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.dataSource()）. It shouldn't have anything to do with it

**Comment by cherrylzhao** [comment]
ok, I have got the same error in my environment, I think you should just paste the full exception stack log next time.

**Comment by mygitdds** [comment]
@cherrylzhao  Sorry, I found the problem. I configure the SQL according to the official document. When I first create the object of SagaSharing Transaction Manager, I automatically create sql. It fails in the process of executing sql, which leads to subsequent failure.

**Comment by cherrylzhao** [comment]
you have resolved the problem?

**Comment by mygitdds** [comment]
@cherrylzhao yes

**Comment by mygitdds** [comment]
@cherrylzhao  I went to modify the sharding-transaction-base-saga source code to print the log, and dug into each execution method to find the execution SQL error.

**Comment by mygitdds** [comment]
@cherrylzhao I followed the official SQL and created the file schema-init.sql, but there was a problem when the SQL was executed in the framework.

**Comment by cherrylzhao** [comment]
how did you resolve the error, create table SQL is wrong from official site?

**Comment by mygitdds** [comment]
@cherrylzhao Create SQL and files to https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/transaction/

Where will the source code go to the schema-init.sql file under the resources of the project? If it is not found, the logic of creating SQL will not be executed. I deleted the schema-init.sql from my project and the project started successfully.

**Comment by cherrylzhao** [comment]
execute schema-init.sql behavior is right, we should find the root cause why execute SQL throw exception.

**Comment by mygitdds** [comment]
@cherrylzhao  Official SQL is no problem. When I dug, I saw that the execution of SQL seemed to be no problem. But execution is, fail

**Comment by mygitdds** [comment]
@cherrylzhao  I duplicated the SQL executed in the framework and found that when two SQL statements were created in the file and read out, the first statement seemed to be all right, but when it was copied out to the SQL tool to execute, it made a mistake, a little similar. The key word "use" appeared in the field of table building.

**Comment by cherrylzhao** [comment]
@mygitdds your schema-init.sql contains a `\uFEE` in the head. when I create a new file, the problem was resolved.

**Comment by mygitdds** [comment]
@cherrylzhao Thank you
