### ISSUE TITLE
ResultSetUtil cant't process the boolean value:Unsupported data type:boolean exceptions

### ISSUE THREAD

**Issue by linghushaoxia** [apache/incubator-shardingsphere#2654]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
The method ResultSetUtil.convertValue(final Object value, final Class<?> convertType) can process boolean value.
### Actual behavior
when the  convertType is boolan or Boolean and value is not null ,the method will throw ShardingException.
### Reason analyze (If you can)
In general ,when we convert a value to a boolean ,the type of the value is String or Number ; the  value is "true" or "false" or number.
So the code:
[ResultSetUtil.zip](https://github.com/apache/incubator-shardingsphere/files/3357428/ResultSetUtil.zip)

**Comment by tuohai666** [comment]
This problem is more complicated than you expected. Please go through #2604.

**Comment by linghushaoxia** [comment]
> 
> 
> This problem is more complicated than you expected. Please go through #2604.
emmm, I browsed it again, it is really complicated.

**Comment by tuohai666** [comment]
Duplicate with #2604.
