### ISSUE TITLE
one sharding database is down will cause the whole sharding data source can not be inited

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#2657]
## Bug Report

one sharding database is down will cause the whole sharding database can not be inited.
this will cause the web application can not be started.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
one sharding database is down will not cause the whole sharding data source can not be inited.
and then we can start new web app.

### Actual behavior
one sharding database is down -> sharding data source init error

### Reason analyze (If you can)
the  sharding data source will get the connection of actual database and init the metadata.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sharding table in multi database and shutdown one database.

**Comment by terrymanu** [comment]
what is your expected behavior if one sharding database is down? 
Throw exception and halt startup the application or ignore exception and continue to startup the application? I prefer the 1st solution.

So I just label this issue as invalid, any feedback?

**Comment by lalicw** [comment]
can we just do not get connection when we init the sharding data source,  or we can lazy init the sharding data source when we invoke get connection method of sharding data source (like druid data source, if we set InitialSize= 0, it will not actual init connections, and init the druid data source when we invoke get connection method ), any request to that one sharding database which is down throw exception, but the request the the other database is ok.

**Comment by terrymanu** [comment]
I prefer design as fail fast. Check necessary information is better than first time to use.

If lazy load, the first call is very slow and will cause all requests piled up, it can not be acceptance on high concurrent.

So I just close this discussion.
