### ISSUE TITLE
the risk of Updating all table when SQL without sharding-key 

### ISSUE THREAD

**Issue by qhj348770376** [apache/incubator-shardingsphere#2658]
As I know,when we execute update SQL without sharding-key ,Sharding-JDBC will update all the table . I think this is not safe for production environment. I want throw en exception when update without sharding-key, Sharding-JDBC can help me do it ?

**Comment by terrymanu** [comment]
User should use SQL to control risk. If update without sharding key is a risk, how about truncate?

**Comment by terrymanu** [comment]
duplicate with #2610
