### ISSUE TITLE
4.0.0-RC1版本 遇到问题反馈

### ISSUE THREAD

**Issue by F191919** [apache/incubator-shardingsphere#2660]
4.0.0-RC1版本中ShardingRule类中 
![image](https://user-images.githubusercontent.com/11403274/60701782-76632880-9f2f-11e9-8083-b4437f87cda5.png) 82行中的createBindingTableRules下面有用到broadcastTables
属性 即isBroadcastTable(final String logicTableName) 方法
![image](https://user-images.githubusercontent.com/11403274/60701912-deb20a00-9f2f-11e9-86d5-632029028ce9.png) 而此时broadcastTables为空 所以会报空指针异常

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
