### ISSUE TITLE
强制路由到单表或者单库不能分页

### ISSUE THREAD

**Issue by lyndonChen** [apache/incubator-shardingsphere#2661]
3.1.0 版本 单库单表分页失败，降到3.0.0可以
项目使用sharding-jdbc-spring-boot-starter
配置：
![image](https://user-images.githubusercontent.com/3940524/60706659-87666680-9f3c-11e9-8c74-004d1a8cb225.png)

**Comment by lyndonChen** [comment]
3.1.0是否需要特殊配置

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
