### ISSUE TITLE
how to set datasource readonly

### ISSUE THREAD

**Issue by penghuiy** [apache/incubator-shardingsphere#2663]
## Question

I have a data node with read-only permissions. I want to use sharding-proxy. , I found the Hikari pool called jdbc's setReadOnly method default. I got an exception. 
```
Exception in thread "main" org.apache.shardingsphere.core.exception.ShardingException: Can not build data source, name is `ds1`.
xxx
xxx
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: read-only mode can not be disabled.
```
Did not find any place to configure datasource readonly

**Comment by terrymanu** [comment]
Please transfer this issue to HikariPool

**Comment by penghuiy** [comment]
@terrymanu 
I have found a discussion about the hikari pool(https://github.com/brettwooldridge/HikariCP/issues/1116). 
Based on the results of the discussion, I think I should explicitly specify isReadOnly. If not specified, the jdbc driver will throw an exception unpredictably, resulting in a connection not being established properly.

If improvements are made, I think
YamlDataSourceParameter should add the isReadOnly parameter, then
config.setReadOnly(dataSourceParameter.isReadOnly());

Please let me know if there are other objections.

**Comment by penghuiy** [comment]
@terrymanu 
Can you give me some guidance? thank you

**Comment by penghuiy** [comment]
@terrymanu please help me？

**Comment by terrymanu** [comment]
Yes, maybe we should add this parameter, anybody want to do this feature?

**Comment by sunbufu** [comment]
Hello, I have been thinking for a long time about the readonly parameter, and I cloud't found any scenario. 
1. If we use readonly for sharding, we will get many problems, such as which datasource should we use for DML or DQL, but It won't bring us any benefits.
2. If we use readonly for master-slave, I think readonly is redundant, because master must be writeable and slave must be readable.
3. If we use readonly for encrypt, I think it's redundant too.
So, I think maybe we don't need readonly parameter in sharding-sphere.

**Comment by penghuiy** [comment]
According to the JDBC specs, this setting is only a hint to the database to enable optimizations - it does not cause writes to be prohibited.
I think this parameter is needed mainly to control the default behavior of the HikariPool. Of course, it can be set to false by default.

**Comment by sunbufu** [comment]
sorry, I dont know that. Can you give me some examples?

**Comment by penghuiy** [comment]
> sorry, I dont know that. Can you give me some examples?

https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java

https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/jdbc/JdbcConnection.java

Their setReadonly method has nothing

**Comment by sunbufu** [comment]
The readonly parameter is useless for sharding-sphere, but is used for JDBC. Can I understand that ?

**Comment by penghuiy** [comment]
> The readonly parameter is useless for sharding-sphere, but is used for JDBC. Can I understand that ?

Right
