### ISSUE TITLE
Can not reinitialize ShardingDataSource 

### ISSUE THREAD

**Issue by liweiboy** [apache/incubator-shardingsphere#2672]
Hi,I meet a problem when updating sharding-jdbc from 2.0.3 to 4.0.0.RC version. I want to reinitialize the ShardingDataSource by calling renew method in ShardingDataSource class instead of restarting the project.But I can not find renew method in 4.0.0.RC version which could found in 2.0.3 version.

**Comment by tristaZero** [comment]
`renew()` is in OrchestrationShardingDataSource in 4.0.0.RC for updating the properties of datasource and sharding rule. Why do you want to use `renew()` of ShardingDataSource?
@liweiboy

**Comment by liweiboy** [comment]
Because sharding tables are not configured in YML or xml, but stored in mysql table.When I insert a record in the table,the sharding rule added.Then I push a message to MQ to notify my service to reinitialize.In a word,my sharding tables are not static which can be changed in my orchestration.

![1](https://user-images.githubusercontent.com/37232258/61031172-85dfe700-a3f1-11e9-98ba-ca1ea1463169.png)
![2](https://user-images.githubusercontent.com/37232258/61031177-89736e00-a3f1-11e9-90a9-0e8ca0c06d4a.png)
@tristaZero

**Comment by liweiboy** [comment]
I can not find OrchestrationShardingDataSource class.Can you tell me the package which OrchestrationShardingDataSource class is in.
@tristaZero

**Comment by tristaZero** [comment]
Good idea, but you can consider to use ShardingOrchestration which uses zk or other registries, instead of db to do orchestration. Meanwhile, we will put all changed settings to online and renew your datasources automatically. :)
> OrchestrationShardingDataSource is in package org.apache.shardingsphere.shardingjdbc.orchestration.internal.datasource

@liweiboy

**Comment by liweiboy** [comment]
@tristaZero Thank you.
