### ISSUE TITLE
与spring boot 集成后启动报错

### ISSUE THREAD

**Issue by dahaian** [apache/incubator-shardingsphere#2689]
我使用的是目前最新的版本，4.0.0-RC1，我根据官方文档给的配置，配置了spring boot集成sharding jdbc，具体的配置如下：
![QQ截图20190710172415](https://user-images.githubusercontent.com/9957813/60957651-916ed780-a337-11e9-9208-d4c310f8adfc.png)
我是只想配置分表不分库的，不过官方好像没有给出单独的分表配置，所以我按照以上的配置启动spring，以下是测试代码：
![image](https://user-images.githubusercontent.com/9957813/60957756-c418d000-a337-11e9-896f-3fba99ce8280.png)
启动spring后报以下错误：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testC': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Type is required.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Type is required.

以下是spring 的依赖引用：
![image](https://user-images.githubusercontent.com/9957813/60958320-bf085080-a338-11e9-9e94-a736c6d24670.png)
![image](https://user-images.githubusercontent.com/9957813/60958294-b6177f00-a338-11e9-9eb7-a940c1c99087.png)

**Comment by jimforcode** [comment]
springboot 版本号贴一下

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by dahaian** [comment]
@jimforcode  spring boot 2.1.6.RELEASE

**Comment by jaychang9** [comment]
I use the springboot 2.1.6.RELEASE. I already exclude the JtaAutoConfiguration.class 
`@SpringBootApplication(exclude = {JtaAutoConfiguration.class})`
But it doesn't affect.

**The following is the error info:**
Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

Disconnected from the target VM, address: '127.0.0.1:52709', transport: 'socket'

Process finished with exit code 1

**then my application.properties:**

spring.shardingsphere.datasource.names=ds_0,ds_1

spring.shardingsphere.datasource.ds_0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds_0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds_0.jdbc-url=jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds_0.username=root
spring.shardingsphere.datasource.ds_0.password=

spring.shardingsphere.datasource.ds_1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds_1.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds_1.jdbc-url=jdbc:mysql://localhost:3306/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds_1.username=root
spring.shardingsphere.datasource.ds_1.password=

spring.shardingsphere.sharding.default-database-strategy.inline.sharding-column=user_id
spring.shardingsphere.sharding.default-database-strategy.inline.algorithm-expression=ds_$->{user_id % 2}

spring.shardingsphere.sharding.tables.t_order.actual-data-nodes=ds$->{0..1}.t_order
spring.shardingsphere.sharding.tables.t_order.key-generator.column=order_id
spring.shardingsphere.sharding.tables.t_order.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.t_order.key-generator.props.worker.id=123
spring.shardingsphere.sharding.tables.t_order_item.actual-data-nodes=ds$->{0..3}.t_order_item
spring.shardingsphere.sharding.tables.t_order_item.key-generator.column=order_item_id
spring.shardingsphere.sharding.tables.t_order_item.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.t_order_item.key-generator.props.worker.id=123

spring.shardingsphere.props.sql.show=true
