### ISSUE TITLE
我的sql中有row字段，用sharding自定义分片失效，也不报错，默认选了一个数据源

### ISSUE THREAD

**Issue by maverickPIG** [apache/incubator-shardingsphere#2690]
这是我的sql：SELECT row,id FROM T_TEST WHERE id = 101 
这是提示信息：
line 1:10 no viable alternative at input 'row,'
为什么不报错，默认一个数据源，不走我自定义分片规则

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
