### ISSUE TITLE
不能用中文提issue,干嘛要写中文文档?

### ISSUE THREAD

**Issue by shenmimoon** [apache/incubator-shardingsphere#2691]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by shenmimoon** [comment]
https://github.com/apache/incubator-shardingsphere/issues/59

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
