### ISSUE TITLE
do not found  4.0.0-RC1 version in mvnrepository 

### ISSUE THREAD

**Issue by chenkuig** [apache/incubator-shardingsphere#2692]
do not found  4.0.0-RC1 version in mvnrepository 
![image](https://user-images.githubusercontent.com/40064877/60972662-48c81600-a359-11e9-9474-de3ec8b925b6.png)

**Comment by terrymanu** [comment]
FYI: https://mvnrepository.com/artifact/org.apache.shardingsphere

**Comment by chenkuig** [comment]
我想问一下：shardingsphere那个版本比较成熟，4.0.0-RC1可以作为RTM版本使用吗，作为公司的技术选型，想主要使用的是，它的分库分表与分布式事务；麻烦给点建议，Thanks!

**Comment by chenkuig** [comment]
老兄， <artifactId>sharding-transaction-spring-boot-starter</artifactId>这个jar包是真的没找到，sharding-sphere-example工程没有编译过

**Comment by chenkuig** [comment]
我是按照你这个sharding-sphere-example工程下的sharding-spring-boot-mybatis-example，transaction-saga-spring-boot-example，transaction-xa-spring-boot-example这三个工程引得依赖，搭了一个环境，可以加你钉钉私聊么？

**Comment by chenkuig** [comment]
Caused by: io.shardingsphere.core.exception.ShardingException: Switching transaction Type is unsupported for transaction manager org.springframework.transaction.jta.JtaTransactionManager
springboot version :2.1.0 版本
![image](https://user-images.githubusercontent.com/40064877/61040400-0fe47b80-a403-11e9-920b-aff7e1f11e96.png)

**Comment by chenkuig** [comment]
springboot:2.1.0版本
这种配置是错误的：@SpringBootApplication(exclude = JtaAutoConfiguration.class)
改成这样就不在注入JTA事物
@EnableAutoConfiguration(exclude={JtaAutoConfiguration.class})

**Comment by chenkuig** [comment]
TransactionalDataSourceConverterSPILoader 这个怎么配置，初始化的时候这个是datasourceMap是空的，事物该怎么配置；

**Comment by chenkuig** [comment]
TransactionalDataSourceConverterSPILoader 这个怎么配置，初始化事物XA类型数据源时候这个datasourceMap是空的，官网文档不是说Druid不用配置么，那这个事物该怎么配置使用；
