### ISSUE TITLE
The method "ShardingInsertOptimizedStatement.addUnit()" has done more than one thing

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#2693]
## The method "ShardingInsertOptimizedStatement.addUnit()" has done more than one thing

The method "ShardingInsertOptimizedStatement.addUnit()" has done more than one thing:create InsertOptimizeResult Object and add it to the member 'units'. I think it is better to split the method into two parts. One method creates InsertOptimizeResult and Another use this InsertOptimizeResult Object as input to add it in the member 'units'.

**Comment by tristaZero** [comment]
Can you provide the java file and the line number of this method?
@wgy8283335

**Comment by wgy8283335** [comment]
The file is org.apache.shardingsphere.core.optimize.statement.sharding.dml.insert.ShardingInsertOptimizedStatement.java. And the line number is 62.

**Comment by tristaZero** [comment]
Got it, how bout raising a Pull Request to make it better?
@wgy8283335

**Comment by wgy8283335** [comment]
@tristaZero. OK.
