### ISSUE TITLE
Throw java.lang.IllegalArgumentException: Type is required when Integrating spring boot with sharding jdbc

### ISSUE THREAD

**Issue by dahaian** [apache/incubator-shardingsphere#2694]
I use 4.0.0-RC1 sharding jdbc and 2.1.6.RELEASE spring boot.
My config file is:
![image](https://user-images.githubusercontent.com/9957813/61032072-5500b180-a3f3-11e9-8651-04daa4e99b6b.png)

And My test code is :
![image](https://user-images.githubusercontent.com/9957813/61032151-719ce980-a3f3-11e9-8843-8a88735910d4.png)

I got a error when I run the application.The error is:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testC': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Type is required.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Type is required.

My spring boot pom.xml is 
![image](https://user-images.githubusercontent.com/9957813/61032248-a610a580-a3f3-11e9-9f76-c5c29ad3a014.png)
![image](https://user-images.githubusercontent.com/9957813/61032269-b032a400-a3f3-11e9-9f4a-d47e2e22b90a.png)

**Comment by KomachiSion** [comment]
Please add `spring.shardingsphere.sharding.tables.t_order.key-generator.type=SNOWFLAKE` and retry.

**Comment by dahaian** [comment]
@KomachiSion  I follow you add spring.shardingsphere.sharding.tables.t_order.key-generator.type=SNOWFLAKE or spring.shardingsphere.sharding.tables.t_order.key-generator.type=UUID and retry. But I got a error is:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testC': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.NullPointerException

My config file is：
![image](https://user-images.githubusercontent.com/9957813/61034228-76639c80-a3f7-11e9-8e7b-aa6438cbfa80.png)

**Comment by KomachiSion** [comment]
Remove `spring.shardingsphere.sharding.binding-tables` and retry.

You can take a look example [sharding-jdbc-example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example).
Use `application-sharding-tables.properties`

**Comment by KomachiSion** [comment]
Hi @dahaian, If no more question, We will close this issue.
