### ISSUE TITLE
data not decrypted in sharding-tables scenario

### ISSUE THREAD

**Issue by yishenghuang** [apache/incubator-shardingsphere#2695]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
data should be decrypted when <sharding:encrypt-rules> correctly configured (sharding-tables scenario)
### Actual behavior
1. data decrypted when selecting all records 
2. data not decrypted when selecting records with sharding-key specified

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
configuratoin:
     <sharding:data-source id="dataSource">
        <sharding:sharding-rule data-source-names="sharding_ds">
            <sharding:table-rules>
                <sharding:table-rule logic-table="card_info" actual-data-nodes="sharding_ds.card_info_${0..1}" table-strategy-ref="preTableShardingStrategy"/>
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="card_info"/>
            </sharding:binding-table-rules>
            <sharding:encrypt-rules>
				<sharding:encryptor-rule id="card_encryptor" qualified-columns="card_info.card_pwd" type="AES" props-ref="props" />
			</sharding:encrypt-rules>
        </sharding:sharding-rule>
        <sharding:props>
			<prop key="sql.show">true</prop>
		</sharding:props>
    </sharding:data-source>

1. data decrypted
[ShardingSphere-SQL] - Logic SQL: SELECT 	 
		a.batch_no AS "batchNo",
		a.type_id AS "cardType.id",
		a.card_no AS "cardNo",
		a.card_pwd AS "cardPwd",		
		b.name as "cardType.name",
		FROM card_info a
		left join card_type b on a.type_id = b.id limit 30

2. data not decrypted
[ShardingSphere-SQL] - Logic SQL: SELECT 	 
		a.batch_no AS "batchNo",
		a.type_id AS "cardType.id",
		a.card_no AS "cardNo",
		a.card_pwd AS "cardPwd",		
		b.name as "cardType.name",
		FROM card_info a
		left join card_type b on a.type_id = b.id
		 WHERE  a.batch_no = ? limit 30

**Comment by tristaZero** [comment]
Can you use 4.0.0-RC2 to test?
I test your sceniro in 4.0.0-RC2, and it is ok

**Comment by yishenghuang** [comment]
cannot find 4.0.0-RC2 at maven mvnrepository, where can i get 4.0.0-RC2

**Comment by yishenghuang** [comment]
can you help share you test case? 
i can still reproduce this issue when using 4.0.0-RC3-SNAPSHOT (build at local). I configure shardingsphere in spring namespace.

**Comment by tristaZero** [comment]
Thanks for your reply, if possible, can u upload your easy example to gitHub, can give me the url of your example? So i can detect the issue quickly.
@yishenghuang

**Comment by tristaZero** [comment]
Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
