### ISSUE TITLE
SNOWFLAKE kegenGenerator  column index was wrong

### ISSUE THREAD

**Issue by core1942** [apache/incubator-shardingsphere#2697]
String sql = " INSERT INTO `customer_account`(`group_id`, `customer_id`, `channel`, `recharge_balance`, `gift_balance`, `total_recharge_amount`, `total_gift_amount`, `version`, `query_password`, `query_salt`, `query_hash_type`, `pay_password`, `pay_salt`, `pay_hash_type`, `extra`,`deleted_at`) VALUES " +
				"('0', '9223372036854775801', 'default', 0, 0, 0, 0, 0, '', '', 0, '', '', 0, '',?);";
		try (Connection conn = dataSource.getConnection();
		     PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
			preparedStatement.setDate(1,null);
			preparedStatement.execute();
		}

Logic SQL:  INSERT INTO `customer_account`(`group_id`, `customer_id`, `channel`, `recharge_balance`, `gift_balance`, `total_recharge_amount`, `total_gift_amount`, `version`, `query_password`, `query_salt`, `query_hash_type`, `pay_password`, `pay_salt`, `pay_hash_type`, `extra`,`deleted_at`) VALUES ('0', '9223372036854775801', 'default', 0, 0, 0, 0, 0, '', '', 0, '', '', 0, '',?);
10:43:59.853 [main] INFO ShardingSphere-SQL - SQLStatement: InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=customer_account, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=customer_id, tableName=customer_account), operator=EQUAL, compareOperator=null, positionValueMap={0=9223372036854775801}, positionIndexMap={})])])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=customer_account, quoteCharacter=BACK_QUOTE, schemaNameLength=0), SQLToken(startIndex=31)], parametersIndex=1, logicSQL= INSERT INTO `customer_account`(`group_id`, `customer_id`, `channel`, `recharge_balance`, `gift_balance`, `total_recharge_amount`, `total_gift_amount`, `version`, `query_password`, `query_salt`, `query_hash_type`, `pay_password`, `pay_salt`, `pay_hash_type`, `extra`,`deleted_at`) VALUES ('0', '9223372036854775801', 'default', 0, 0, 0, 0, 0, '', '', 0, '', '', 0, '',?);), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[group_id, customer_id, channel, recharge_balance, gift_balance, total_recharge_amount, total_gift_amount, version, query_password, query_salt, query_hash_type, pay_password, pay_salt, pay_hash_type, extra, deleted_at], values=[InsertValue(columnValues=[org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@32177fa5, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@a96d56c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@6ab4a5b, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@2abe9173, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@235d29d6, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@1fdca564, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@43f9dd56, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@1d12e953, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@57cb70be, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@2d4608a6, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@20d87335, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@2a8a4e0c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@26c89563, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@3bd6ba24, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@58f437b0, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@20f6f88c])])
10:43:59.854 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 :::  INSERT INTO `customer_account_0` (group_id, customer_id, channel, recharge_balance, gift_balance, total_recharge_amount, total_gift_amount, version, query_password, query_salt, query_hash_type, pay_password, pay_salt, pay_hash_type, extra, deleted_at, id) VALUES ('0', '9223372036854775801', 'default', 0, 0, 0, 0, 0, '', '', 0, '', '', 0, '', ?, ?) ::: [356389339120271361, null]

**Comment by tristaZero** [comment]
Which version do you use?
Do you think [this one](https://github.com/apache/incubator-shardingsphere/issues/2401) which has been fixed already is similar with your question？

**Comment by tristaZero** [comment]
Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
