### ISSUE TITLE
事物怎么配置，3.1.0版本

### ISSUE THREAD

**Issue by chenkuig** [apache/incubator-shardingsphere#2698]
我用的Druid，spring-boot-starter-data-jpa添加了JPA事物，在初始化XA事物数据源时报的错，服务器起起来了，但是已使用 @ShardingTransactionType(TransactionType.XA)没有数据源，
io.shardingsphere.core.exception.ShardingException: Failed to load [com.mysql.jdbc.jdbc2.optional.MysqlXADataSource]，怎么解决，在线等，急急急！

**Comment by chenkuig** [comment]
这是配置文件
spring.main.allow-bean-definition-overriding=true
sharding.jdbc.datasource.names=ds0,ds1

sharding.jdbc.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds0.url=jdbc:mysql://127.0.0.1:3306/ds0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds0.username=root
sharding.jdbc.datasource.ds0.password=
sharding.jdbc.datasource.ds0.initial-size=1
sharding.jdbc.datasource.ds0.min-idle=1
sharding.jdbc.datasource.ds0.max-active=20
sharding.jdbc.datasource.ds0.filter.stat.log-slow-sql=true
sharding.jdbc.datasource.ds0.filter.wall.enabled=true

sharding.jdbc.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds1.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds1.url=jdbc:mysql://127.0.0.1:3306/ds1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds1.username=root
sharding.jdbc.datasource.ds1.password=
sharding.jdbc.datasource.ds1.initial-size=1
sharding.jdbc.datasource.ds1.min-idle=1
sharding.jdbc.datasource.ds1.max-active=20
sharding.jdbc.datasource.ds1.filter.stat.log-slow-sql=true
sharding.jdbc.datasource.ds1.filter.wall.enabled=true

sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=ds$->{order_id % 2}

sharding.jdbc.config.sharding.tables.b_split_order.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.b_split_order.actual-data-nodes=ds$->{0..1}.b_split_order$->{0..1}
sharding.jdbc.config.sharding.tables.b_split_order.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.b_split_order.table-strategy.inline.algorithm-expression=b_split_order$->{order_id % 2}
#sharding.jdbc.config.sharding.tables.b_split_order.key-generator.type=SNOWFLAKE

sharding.jdbc.config.sharding.tables.b_split_order_items.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.b_split_order_items.actual-data-nodes=ds$->{0..1}.b_split_order_items$->{0..1}
sharding.jdbc.config.sharding.tables.b_split_order_items.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.b_split_order_items.table-strategy.inline.algorithm-expression=b_split_order_items$->{order_id % 2}
#sharding.jdbc.config.sharding.tables.b_split_order_items.key-generator.type=SNOWFLAKE
sharding.jdbc.config.sharding.binding-tables=b_split_order,b_split_order_items
sharding.jdbc.config.props.sql.show=true

spring.jpa.database=MYSQL
spring.jpa.show-sql=false

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
