### ISSUE TITLE
How to config XA-TYPE Transaction

### ISSUE THREAD

**Issue by chenkuig** [apache/incubator-shardingsphere#2699]
start server is normal . spring-boot-starter-data-jpa jar is added in pom config, is not XA-mapping datasource in using @ShardingTransactionType(TransactionType.XA)  annotation ;
is the error :io.shardingsphere.core.exception.ShardingException: Failed to load [com.mysql.jdbc.jdbc2.optional.MysqlXADataSource]

this is my config:
spring.main.allow-bean-definition-overriding=true
sharding.jdbc.datasource.names=ds0,ds1

sharding.jdbc.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds0.url=jdbc:mysql://127.0.0.1:3306/ds0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds0.username=root
sharding.jdbc.datasource.ds0.password=
sharding.jdbc.datasource.ds0.initial-size=1
sharding.jdbc.datasource.ds0.min-idle=1
sharding.jdbc.datasource.ds0.max-active=20
sharding.jdbc.datasource.ds0.filter.stat.log-slow-sql=true
sharding.jdbc.datasource.ds0.filter.wall.enabled=true

sharding.jdbc.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds1.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds1.url=jdbc:mysql://127.0.0.1:3306/ds1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds1.username=root
sharding.jdbc.datasource.ds1.password=
sharding.jdbc.datasource.ds1.initial-size=1
sharding.jdbc.datasource.ds1.min-idle=1
sharding.jdbc.datasource.ds1.max-active=20
sharding.jdbc.datasource.ds1.filter.stat.log-slow-sql=true
sharding.jdbc.datasource.ds1.filter.wall.enabled=true

sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=ds$->{order_id % 2}

sharding.jdbc.config.sharding.tables.b_split_order.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.b_split_order.actual-data-nodes=ds$->{0..1}.b_split_order$->{0..1}
sharding.jdbc.config.sharding.tables.b_split_order.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.b_split_order.table-strategy.inline.algorithm-expression=b_split_order$->{order_id % 2}
#sharding.jdbc.config.sharding.tables.b_split_order.key-generator.type=SNOWFLAKE

sharding.jdbc.config.sharding.tables.b_split_order_items.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.b_split_order_items.actual-data-nodes=ds$->{0..1}.b_split_order_items$->{0..1}
sharding.jdbc.config.sharding.tables.b_split_order_items.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.b_split_order_items.table-strategy.inline.algorithm-expression=b_split_order_items$->{order_id % 2}
#sharding.jdbc.config.sharding.tables.b_split_order_items.key-generator.type=SNOWFLAKE
sharding.jdbc.config.sharding.binding-tables=b_split_order,b_split_order_items
sharding.jdbc.config.props.sql.show=true

spring.jpa.database=MYSQL
spring.jpa.show-sql=false

**Comment by chenkuig** [comment]
init XA datasourceMap is null ,version userd  is 3.1.0 
![image](https://user-images.githubusercontent.com/40064877/61104298-72438780-a4a8-11e9-9d29-60a252bd645e.png)

**Comment by chenkuig** [comment]
![image](https://user-images.githubusercontent.com/40064877/61106156-c05b8980-a4ae-11e9-8122-158b1a6a590e.png)

**Comment by cherrylzhao** [comment]
hi, please verify the jdbc-driver version, 3.1.0 don't support mysql8. we have enhanced it in 4.x version.

**Comment by chenkuig** [comment]
add all dependency , spring-boot-starter-data-jpa is removd, I want to the confg is correct？

        <dependency>
			 <groupId>com.shsc.plugin.mybatisplus</groupId>
			 <artifactId>com-shsc-plugin-mybatisplus</artifactId>
			 <version>${project.version}</version>
		</dependency>
		<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-spring</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-2pc-xa</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-spring-boot-starter</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
        </dependency>

**Comment by cherrylzhao** [comment]
it seems ok.

**Comment by chenkuig** [comment]
Thanks !

**Comment by cherrylzhao** [comment]
you can close this issue if problem have been resolved.

**Comment by chenkuig** [comment]
Give it a try,  and  Iit is that error in AbstractConnectionAdapter.class,not found xa-datasource
![image](https://user-images.githubusercontent.com/40064877/61109929-b2ab0180-a4b8-11e9-96fc-9917f183482a.png)

**Comment by cherrylzhao** [comment]
you should check the JDBC-driver version, not mysql-server version.

**Comment by chenkuig** [comment]
3.1.0 tag  official demo : dirver is 8.0.11 version , change  to 5.xxx version , is ok;   :)

**Comment by cherrylzhao** [comment]
I have checked the example, it is 5.1.42
![image](https://user-images.githubusercontent.com/8317649/61112787-41228180-a4bf-11e9-8bac-96d7961584d3.png)

**Comment by chenkuig** [comment]
you win , I read that it's probably a fake document in incubator-shardingsphere-example-3.1.0 project,  :)
![image](https://user-images.githubusercontent.com/40064877/61113306-8bf0c900-a4c0-11e9-9e77-0ba694baec51.png)
