### ISSUE TITLE
does the sharding-proxy support multiple proxy users and can filter the source ip addr ?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2700]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by Myshiner** [comment]
Hello, two questions.
1. I wonder if the sharding-proxy support multi-users that so i can connect the proxy using different user. As i noticed that the user & password can just set to one in the server.yaml file as following.
authentication:
  username: proxyuser
  password: *****
And it does not distinguish permissions between read and write.

2. How can i filter the source ip which forbidden to connect the proxy?  And the proxy logs doesnt include the source ip, sometimes maybe useful in troubleshooting.

**Comment by tristaZero** [comment]
which version do you use for testing?
The function of multiple users and access control is supported in our version 4.0.0+.
Please refer to [user document](https://shardingsphere.apache.org/document/current/cn/manual/sharding-proxy/configuration/).

**Comment by Myshiner** [comment]
we use v3.1.0, and thanks for ur reply.

**Comment by Myshiner** [comment]
Hi, thx, we use v3.1.0 now for testing, and will update to v4.0.0 later, thank you.

发送自 Windows 10 版邮件应用

发件人: panjuan
发送时间: 2019年7月17日 10:53
收件人: apache/incubator-shardingsphere
抄送: Myshiner; Author
主题: Re: [apache/incubator-shardingsphere] does the sharding-proxy supportmultiple proxy users and can filter the source ip addr ? (#2700)

which version do you use for testing?
The function of multiple users and access control is supported in our version 4.0.0+.
Please refer to user document.

**Comment by Myshiner** [comment]
Hello, i got version updated to v4.0, and i noticed  it included multiple proxy users configure availible, and limit to authorized schemas , but i wonder if the user can be set to read-only privilege.
