### ISSUE TITLE
How to use primary key of self  without "key-generator.type=SNOWFLAKE" config

### ISSUE THREAD

**Issue by chenkuig** [apache/incubator-shardingsphere#2704]
#2694 question , you fixed it  that add "key-generator.type=SNOWFLAKE" config .   I  want to use primary key of self  based on redis ,and is it  available without  "key-generator.type=SNOWFLAKE" config？it is necessary to be  configured?  how to configure it  based on  primary key of self ? Which version of the production environment is better,  either 3.1.0 version or 4.0.0-RC1 version?

**Comment by terrymanu** [comment]
Can you change title of issue to make it more clear?

**Comment by KomachiSion** [comment]
you can implement `ShardingKeyGenerator` interface to generate primary key by yourself. 
The example can see `LeafSegmentKeyGenerator`, `SnowflakeShardingKeyGenerator` or `UUIDShardingKeyGenerator`.

**Comment by KomachiSion** [comment]
About the versions question, I can't answer it exactly because I don't know your environment detail.
But I suggest you use 4.0.0-RC1 first.

**Comment by chenkuig** [comment]
ok, I'll give it a try.

**Comment by chenkuig** [comment]
I defined key type ="PRIMARYKEY-SELF",  how to make DistributeKeyGenerator class effective?
![image](https://user-images.githubusercontent.com/40064877/61199649-45de7400-a711-11e9-8da8-d55459ff2536.png)

![image](https://user-images.githubusercontent.com/40064877/61199603-1f203d80-a711-11e9-8a69-342d45811eaf.png)

**Comment by chenkuig** [comment]
please give me  an answer for the error?  how to load  the DistributeKeyGenerator class

**Comment by KomachiSion** [comment]
Please add `DistributeKeyGenerator` to SPI.
If don't know how to add, please search for it.

**Comment by chenkuig** [comment]
You know you can tell directly me ，I have searched for it , reference documentation is readed, There is  no about the spi instructions， https://shardingsphere.apache.org/document/current/cn/features/spi/ or others doc ，don't get me wrong, it's my first time to use it

**Comment by KomachiSion** [comment]
I means you search `How to use SPI` in google or Baidu.

SPI official document: [https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html)

**Comment by chenkuig** [comment]
Most of the problems have been solved. Thank you for your help！：）
