### ISSUE TITLE
Java Configuration example compile failure, field "column" no setter of class KeyGeneratorConfiguration

### ISSUE THREAD

**Issue by komawei** [apache/incubator-shardingsphere#2707]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.RC-1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Compile success
### Actual behavior
Compile failure.
### Reason analyze (If you can)
1. 
According to Java Configuration example below,
[Java Configuration](https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-java/)

```
private static KeyGeneratorConfiguration getKeyGeneratorConfiguration() {
        KeyGeneratorConfiguration result = new KeyGeneratorConfiguration();
        result.setColumn("order_id");
        return result;
    }
```

the compilation is failed, cause KeyGeneratorConfiguration doesn't have the "column" setter at ver 4.0.0-RC1, and KeyGeneratorConfiguration doesn't have default constructor.

2. method signature of ShardingDataSourceFactory@createDataSource not match Java Configuration example.

example:
return ShardingDataSourceFactory.createDataSource(createDataSourceMap(), shardingRuleConfig);

acutal:
```
public static DataSource createDataSource(Map<String, DataSource> dataSourceMap, ShardingRuleConfiguration shardingRuleConfig, Properties props) throws SQLException {
        return new ShardingDataSource(dataSourceMap, new ShardingRule(shardingRuleConfig, dataSourceMap.keySet()), props);
    }
```

3. TableRuleConfiguration does not have default constructor.

maybe some other classes have the same bug.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
just copy codes into IDE.

**Comment by terrymanu** [comment]
What is your example version?

**Comment by komawei** [comment]
I use version 4.0.0.RC-1.

**Comment by terrymanu** [comment]
For official example, the compilation is fine, do you using official example?

**Comment by komawei** [comment]
yes, I use official example.
```
private static KeyGeneratorConfiguration getKeyGeneratorConfiguration() {
     KeyGeneratorConfiguration result = new KeyGeneratorConfiguration();
     result.setColumn("order_id");
     return result;
}
```
this code fragment above is copied from offical example ---> [HERE](https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-java/)

but this class  **KeyGeneratorConfiguration** of version 4.0.0.RC-1 does not have default constructor, but have constructor with two or three parameters.

current source code of class KeyGeneratorConfiguration in github -->
[KeyGeneratorConfiguration](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-api/src/main/java/org/apache/shardingsphere/api/config/sharding/KeyGeneratorConfiguration.java)

**Comment by tristaZero** [comment]
@komawei 
Hi, sorry, the official document give a bad example, can you fix this bug and raise a pr for [official ducument](https://github.com/apache/incubator-shardingsphere-doc)?
The correct way to initialize KeyGeneratorConfiguration is
```
public final class KeyGeneratorConfiguration extends TypeBasedSPIConfiguration {
    
    private final String column;
    
    public KeyGeneratorConfiguration(final String type, final String column) {
        super(type);
        Preconditions.checkArgument(!Strings.isNullOrEmpty(column), "Column is required.");
        this.column = column;
    }
    
    public KeyGeneratorConfiguration(final String type, final String column, final Properties properties) {
        super(type, properties);
        Preconditions.checkArgument(!Strings.isNullOrEmpty(column), "Column is required.");
        this.column = column;
    }
```

**Comment by komawei** [comment]
> @komawei
> Hi, sorry, the official document give a bad example, can you fix this bug and raise a pr for [official ducument](https://github.com/apache/incubator-shardingsphere-doc)?
> The correct way to initialize KeyGeneratorConfiguration is
> 
> ```
> public final class KeyGeneratorConfiguration extends TypeBasedSPIConfiguration {
>     
>     private final String column;
>     
>     public KeyGeneratorConfiguration(final String type, final String column) {
>         super(type);
>         Preconditions.checkArgument(!Strings.isNullOrEmpty(column), "Column is required.");
>         this.column = column;
>     }
>     
>     public KeyGeneratorConfiguration(final String type, final String column, final Properties properties) {
>         super(type, properties);
>         Preconditions.checkArgument(!Strings.isNullOrEmpty(column), "Column is required.");
>         this.column = column;
>     }
> ```

My pleasure to fix this bug.  I'll create the pr soon.

**Comment by tristaZero** [comment]
@komawei Thanks very much ,waiting for u.

**Comment by terrymanu** [comment]
Anybody wants to update document as a pr for this issue?

**Comment by tristaZero** [comment]
Ref [NEW Configuration](https://github.com/apache/incubator-shardingsphere-doc/pull/211)
