### ISSUE TITLE
How can i set one log file per day in sharding-proxy ?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2709]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by Myshiner** [comment]
Hello, can i set one log file per day in sharding-proxy ? I dont know how to set in the file "logback.xml". Or does it write all logs into a log file ?

Thx.

**Comment by terrymanu** [comment]
Could you transfer this issue to logback?
