### ISSUE TITLE
SQL Statement Support

### ISSUE THREAD

**Issue by zhuangdr** [apache/incubator-shardingsphere#2711]
version:4.0.0.RC1
Unsupported SQL statement: load data local infile ? into table
-------------------------------------------------------------------------------------------
### Error updating database.  Cause: org.apache.shardingsphere.core.parse.old.parser.exception.SQLParsingException: 
Unsupported SQL statement: 
[
    load data local infile ? into table  pes_jd_sub_01.pes_order_filter
    fields terminated by '``MYPES`' optionally enclosed by ''
    escaped by ''
    lines terminated by '`MYPES`\n'
    (order_id,shop_id,sku_id,price,created,date,buyer_nick,num);
]

**Comment by terrymanu** [comment]
sharding sphere is a middleware, support load  data local doesn't make sense.
