### ISSUE TITLE
load-balance-algorithm-class-name is not working

### ISSUE THREAD

**Issue by yangfqCode** [apache/incubator-shardingsphere#2713]
配置了load-balance-algorithm-class-name这个属性，但是并没有生效，看了源码里面也没有这个属性啊，但是文档里面写了这个属性，而且我急需要这个属性
文档地址：https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
