### ISSUE TITLE
load-balance-algorithm-class-name is not working

### ISSUE THREAD

**Issue by yangfqCode** [apache/incubator-shardingsphere#2714]
I used 4.0.0-RC1,
The document recommend load-balance-algorithm-class-name attribute ， I want to use this attribute but it dos not work .
this attribute is very important to me,
thank you

the doc is ：https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/

**Comment by KomachiSion** [comment]
Hi @yangfqCode, can you provide your full configuration file?

**Comment by yangfqCode** [comment]
spring:
   shardingsphere:
      datasource:
         names: master,slave
         slave:
            password: cxm_db_test_123456
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://127.0.0.1:3306/cxm_business_stat?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
            username: root
         master:
            password: cxm_db_test_123456
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://127.0.0.1:3306/cxm_service_data_base?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
            username: root
      masterslave:
         load-balance-algorithm-class-name: com.cxm.LoadBalanceAlgorithm
         load-balance-algorithm-type: RANDOM1
         slave-data-source-names: slave
         name: ms
         master-data-source-name: master
      props:
         sql:
            show: true

**Comment by KomachiSion** [comment]
Has `com.cxm.LoadBalanceAlgorithm` been added to SPI?
If you use self-developed load balance algorithm, the algorithm should be added to SPI.

**Comment by yangfqCode** [comment]
how can I add com.cxm.LoadBalanceAlgorithm to SPI？
thank you !!

**Comment by KomachiSion** [comment]
I suggest you search it in google or Baidu.

It's a java feature, official document: [https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html)
