### ISSUE TITLE
Make SQL parse module as an open public API

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#2722]
SQL parse module is the basic module of ShardingSphere. This module served sharding, encrypt and masterslave.
We want to make this module as an open public module, and provide clear API to let enduser use SQL parse result to do more customized business logics, such as: SQL audit, SQL APM statistics etc.

- [x] Remove dependency of ShardingRule, EncryptRule, MasterSlaveRule from parse module
- [x] Remove dependency of ShardingMetaData from parse module
- [x] Unify parse rule configuration file
- [x] Redesign SQLParseEngine API
- [x] Provide clear and generic API for  SQLStatement
- [x] Move hook usage inside into parse module

**Comment by lalicw** [comment]
This is really an usable and impressive optimization that can help end users a lot，thank you for your efforts
