### ISSUE TITLE
 hint  subquery question 

### ISSUE THREAD

**Issue by lyy2002** [apache/incubator-shardingsphere#2724]
When using hint routing mode, if SQL statement is a sub-query, it cannot execute hintShardingAlgorithm code .   3.1.0

**Comment by terrymanu** [comment]
What is error message?

**Comment by lyy2002** [comment]
@terrymanu #

> What is error message?

Without error message, I found that I could not enter the breakpoint in the implementation class of "HintSharingAlgorithms". If it was not for sub-queries, it would enter normally.

**Comment by terrymanu** [comment]
Can you try to run example first and make sure example has correct behavior?

**Comment by terrymanu** [comment]
I will close this issue soon if no response any more
