### ISSUE TITLE
limit offset doesn't work when using the fullText search match against in boolean mode

### ISSUE THREAD

**Issue by WillWei1983** [apache/incubator-shardingsphere#2726]
### Which version of ShardingSphere did you use?
I am using the 4.0.0-RC2 build by myself from the source
【BTW】the build fail in openjdk, success only in Oracle jdk. it seems the build use a tool only available in Oracle jdk
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
return the limit record when using the match against in boolean mode
### Actual behavior
return all the records when using the match against in boolean mode, but for natural language mode ,it works well.
### Reason analyze (If you can)
May be in the boolean mode, the proxy didn't send the limit  offset to the real db?
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
`SELECT * FROM SMS_SIGN_MISS_REPORT
WHERE FINAL_STATUS_ID = 'SignUndefine' and ASSIGN_TO_USER_ID ='_NA_'
  and MATCH(SIGN_TEXT) AGAINST('+韵达 *快递' in boolean mode )
limit 5 offset 0;`
when I execute this in the real db like 
```
SELECT * FROM SMS_SIGN_MISS_REPORT_0
WHERE FINAL_STATUS_ID = 'SignUndefine' and ASSIGN_TO_USER_ID ='_NA_'
  and MATCH(SIGN_TEXT) AGAINST('+韵达 *快递' in boolean mode )
limit 5 offset 0;
```
it works as expected

**Comment by WillWei1983** [comment]
I got 49 real table for the sharding proxy. For the limit 5 offset 0 statement, the proxy return 5*49 records but not only 5 records, if this is the expected behavior ???

**Comment by terrymanu** [comment]
What database do you use?

**Comment by WillWei1983** [comment]
5.7.25 MySQL Community Server (GPL) on Ubuntu

**Comment by terrymanu** [comment]
do not support fullText search for now, does anybody interest to add this feature?

**Comment by WillWei1983** [comment]
Hi Terry,

**Comment by WillWei1983** [comment]
Hi Terry
I got a question not related to this issue. I haven't go into the detail of the source code, I am wondering how you handle the count(*) and the like statement in proxy? Because I got a lot of data in db , so I try to use this proxy, but the count and like sql still to be slow, is it muti thread to handle  or just loop the real tables to count or like? from the total time it used, it seems to be the sum of single table time used. sorry for my Chinese english^_^ hope you can understand what I mean...

**Comment by terrymanu** [comment]
For new question, please open a new issue.
We need make every issue title and content for search friendly.

**Comment by terrymanu** [comment]
Will close soon if nobody interesting this feature for now.

**Comment by terrymanu** [comment]
close for now

**Comment by hongshunanhai** [comment]
> do not support fullText search for now, does anybody interest to add this feature?

does shardingsphere jdbc 4.1.1 support  match() against('' in boolean mode) ?

**Comment by wz2cool** [comment]
we meet same problem. any update about this issue
