### ISSUE TITLE
Distributed transaction

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#2729]
Can I use other distributed transactions? I use sofa in my framework because the modularization of sofa framework is to use the context of spring independently for each module. Using official distributed transactions, saga, I feel that it is not possible.

**Comment by terrymanu** [comment]
Please try example.

FYI: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example

**Comment by mygitdds** [comment]
I use sofa modularization, each module is a separate spring context, which means that it's a bit like dealing with transactions between multiple projects. I feel that saga is not dealing with transactions in this area. Saga is dealing with sub-tables in a single project.

**Comment by mygitdds** [comment]
@terrymanu I use sofa modularization, each module is a separate spring context, which means that it's a bit similar to dealing with transactions between multiple projects. I feel that saga is not dealing with transactions in this area. Saga is dealing with sub-database and sub-table in a single project. Now I'm thinking about using seata's distributed transaction.

**Comment by mygitdds** [comment]
@terrymanu I saw in the article on Ant Golden Clothes that Seata supported sharding, and I found the answer to that question.
