### ISSUE TITLE
In query problem

### ISSUE THREAD

**Issue by wanggang931111** [apache/incubator-shardingsphere#2739]
![image](https://user-images.githubusercontent.com/51226924/61615961-d7ae2a00-ac99-11e9-86db-90c9f93a0704.png)
Is it not supported in (select....) sql? Seek help

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/

**Comment by wanggang931111** [comment]
> FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/

![image](https://user-images.githubusercontent.com/51226924/61621116-dc2c1000-aca4-11e9-8828-9ea98784ce92.png)

According to the official website, the same mistake，The subtable is not supported?
