### ISSUE TITLE
How the count and like sql statement handled in the sharding proxy

### ISSUE THREAD

**Issue by WillWei1983** [apache/incubator-shardingsphere#2744]
I have lots of data in a table then I try to use the proxy to sharding the data with 49 tables. the 'equals' where conditions with an index runs fast as expected. but for the count and like query, the execution time seems to be the total sum of the single real table execution time. I am wondering if the proxy is to loop all the 49 tables to execute the sql for count,like sql statement? no some kind of the so call working pool, like future style 'handler' to execute the sql concurrently? or there is a configuration that can config this?

**Comment by terrymanu** [comment]
you may config `max.connections.size.per.query`
FYI: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-java/

**Comment by terrymanu** [comment]
I will close this soon if no further question.
