### ISSUE TITLE
add Java Microbenchmark Harness to our project

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-shardingsphere#2746]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
add Java Microbenchmark Harness to our project，In the future, our code commit optimization will be more convincing.

**Comment by terrymanu** [comment]
Yes, it is a good idea, any suggestion to do it?

**Comment by CalvinKirs** [comment]
> Yes, it is a good idea, any suggestion to do it?
#2747
Create a model separately here, or we can create the ShardingSphere-benchmark directory under the Apache community. I prefer the former, so it is more clearly visible to all committers, and does not need to re-clone project submission project. For example, netty is doing this.

**Comment by terrymanu** [comment]
@CalvinKirs Just as @nancyzrh said, this PR only add a maven dependency for jmh, but does not add any test cases yet, so I think you need add test cases for that.

As my understanding, jmh only can print benchmark info to console which is not very make sense, we have already use jmeter to test benchmark.

The precondition for introduce jmh to ShardingSphere is we need to auto assert if benchmark is under threshold.

**Comment by terrymanu** [comment]
It is duplicated with #2747, I just close this issue
