### ISSUE TITLE
ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte

### ISSUE THREAD

**Issue by FujiwaraTakumi** [apache/incubator-shardingsphere#2749]
### Which version of ShardingSphere did you use?
build from 4.0.0 RC2 dev branch
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
work properly
### Actual behavior
Before #2703 merged, ss will throw ClassCastException that can't convert Byte Array value to Byte.
but now, it throws ClassCastException like below:
![image](https://user-images.githubusercontent.com/1940468/61697724-71dda300-ad6a-11e9-9fb3-10f81313bd9b.png)

### Reason analyze (If you can)
It will be work well after I add 'Types.BIT' in QueryResultUtil.getValueByColumnType().
Could you help me to explain that?

**Comment by FujiwaraTakumi** [comment]
Add table structure
![image](https://user-images.githubusercontent.com/1940468/61707139-5c717480-ad7c-11e9-9cb7-a4ec79c4661d.png)

**Comment by tuohai666** [comment]
@FujiwaraTakumi What's the SQL?
@Saisimon Can you take a look?

**Comment by tuohai666** [comment]
@FujiwaraTakumi Can you put up your code completely?

**Comment by FujiwaraTakumi** [comment]
Logic SQL like this:

_SELECT
	nodeethern0_.ID AS ID1_4_,
	nodeethern0_.XXX_DATE AS XXX_D2_4_,
	nodeethern0_.XXX_DATE AS XXX_D3_4_,
	nodeethern0_.DELETED AS DELETED4_4_,
	nodeethern0_.GRP AS GRP5_4_,
	nodeethern0_.LINKED AS LINKED6_4_,
	nodeethern0_.XXX AS XXX7_4_,
	nodeethern0_.NAME AS NAME8_4_,
	nodeethern0_.SN AS SN9_4_,
	nodeethern0_.XXX AS XXX10_4_ 
FROM
	node_ethernet nodeethern0_ 
WHERE
	nodeethern0_.SN =?_

**Comment by Saisimon** [comment]
According to [MySQL Connector/J 5.1](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html) and [MySQL Connector/J 8.0](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html) documentations
> java.lang.Boolean if the configuration property tinyInt1isBit is set to true (the default) and the storage size is 1, or java.lang.Integer if not.

Two ways can fix it.
1.  change tinyint(1) to tinyint(2)
2. datasource url add tinyInt1isBit=false, like jdbc:mysql://dbserver:3306/d0?tinyInt1isBit=false

**Comment by FujiwaraTakumi** [comment]
I see, thanks for your patience.

**Comment by tuohai666** [comment]
@Saisimon Can you add my WeChat or call me directly any time when you are free? My phone number is 15810310987.

**Comment by tuohai666** [comment]
@Saisimon Can you explicitly point out whether it's a problem of ShardingSphere or not. We need more discussion

**Comment by Saisimon** [comment]
MySQL driver determines whether to convert the TINYINT(1) type to  byte or to boolean according to the tinyInt1isBit parameter. The default is to convert it to boolean type, but the user wants the character type, the user needs to control the behavior of the mysql driver.

**Comment by tuohai666** [comment]
@FujiwaraTakumi Will you meet the same problem if you use raw jdbc?

**Comment by FujiwaraTakumi** [comment]
I use hibernate + druid to connect db directly without ss haven't meet this problem.

**Comment by tuohai666** [comment]
After deep discussion with @Saisimon , It make sense that the particular usage should set tinyInt1isBit=false.
