### ISSUE TITLE
How to make shardingsphere support Sybase database? 

### ISSUE THREAD

**Issue by maekko** [apache/incubator-shardingsphere#2750]
I need to use Sybase database,how to make shardingsphere support it? Please give me some advice.Thank you

**Comment by terrymanu** [comment]
I think it is not a very simple question to answer.
You may study source code of ShardingSphere and know SQL parser first.

**Comment by maekko** [comment]
OK,and what changes do I probably need to make?

**Comment by terrymanu** [comment]
you need do SQL parse via antlr g4 file

**Comment by terrymanu** [comment]
I will close this issue soon if no further question.
