### ISSUE TITLE
When sharding-proxy can support transparent mode totally？

### ISSUE THREAD

**Issue by jintonghuoya** [apache/incubator-shardingsphere#2751]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
Not yet, we will update document when transparent mode ready.

**Comment by jintonghuoya** [comment]
ok
