### ISSUE TITLE
Class ModuloShardingTableAlgorithm & ModuloShardingDatabaseAlgorithm missing in V4.0.0-RC1

### ISSUE THREAD

**Issue by komawei** [apache/incubator-shardingsphere#2754]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
V4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Java config example compile success.
### Actual behavior
Java config example compile success due to these two file missing, ModuloShardingTableAlgorithm and ModuloShardingDatabaseAlgorithm.
### Reason analyze (If you can)
[In this java config example page](https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-java/)
, you take this code fragment below for example:
```
DataSource getDataSource() throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTableRuleConfigs().add(getOrderTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(getOrderItemTableRuleConfiguration());
        shardingRuleConfig.getBindingTableGroups().add("t_order, t_order_item");
        shardingRuleConfig.getBroadcastTables().add("t_config");
        shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new StandardShardingStrategyConfiguration("user_id", new ModuloShardingDatabaseAlgorithm()));
        shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("order_id", new ModuloShardingTableAlgorithm()));
        shardingRuleConfig.setMasterSlaveRuleConfigs(getMasterSlaveRuleConfigurations());
        return ShardingDataSourceFactory.createDataSource(createDataSourceMap(), shardingRuleConfig, new HashMap<String, Object>(), new Properties());
    }
```
but these two classes do not exist in the jar file. Maybe just moving these two files from legacy version can solve this issue.

**Comment by KomachiSion** [comment]
Hi @komawei ,
Sorry for late reply, the `ModuloShardingTableAlgorithm` and `ModuloShardingDatabaseAlgorithm` is an example custom sharding algorithm in [apache/incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example)

And in 4.0.X example project, they have been subdivided into `precise` and `range`.

I suggest you clone example project and try to run example first.

**Comment by komawei** [comment]
> Hi @komawei ,
> Sorry for late reply, the `ModuloShardingTableAlgorithm` and `ModuloShardingDatabaseAlgorithm` is an example custom sharding algorithm in [apache/incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example)
> 
> And in 4.0.X example project, they have been subdivided into `precise` and `range`.
> 
> I suggest you clone example project and try to run example first.

Hi, I've customized my own sharding algorithm. What I want to point out are the errors on the example page. Maybe it's easier and more friendly to somone who begins to learn sharding-sphere.

**Comment by KomachiSion** [comment]
Thanks for your correction and advice, we will update document soon.
