### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by wanglichao1** [apache/incubator-shardingsphere#2757]
I use the version 4.0.0-RC2. When select result convert bit to boolean throw exception:
`Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.Boolean
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.getBoolean(ShardingResultSet.java:71) ~[sharding-jdbc-core-4.0.0-RC2.jar!/:4.0.0-RC2]
	at org.hibernate.type.descriptor.sql.BooleanTypeDescriptor$2.doExtract(BooleanTypeDescriptor.java:59) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3012) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
`
my table：
CREATE TABLE `topic` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_date` datetime NOT NULL,
  `modify_date` datetime DEFAULT NULL,
  `order_list` bigint(20) DEFAULT NULL,
  `clazz_id` bigint(20) NOT NULL,
  `collect_count` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `content` varchar(500) NOT NULL,
  `istop` bit(1) DEFAULT NULL,
  `like_count` int(11) DEFAULT NULL,
  `organization_id` bigint(20) NOT NULL,
  `picture_batch_id` bigint(20) DEFAULT NULL,
  `user_id` bigint(20) NOT NULL,
  `weight` bigint(20) DEFAULT NULL,
  `ext_object_id` bigint(20) DEFAULT NULL,
  `ext_type` varchar(255) DEFAULT NULL,
  `video_batch_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_clazzid_orderlist` (`clazz_id`,`order_list`) USING BTREE,
  KEY `idx_userid` (`user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2811 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

The column "istop" is Boolean in my entity,The table is auto created by hibernate5.3.

**Comment by tuohai666** [comment]
@Saisimon Is this the same problem as https://github.com/apache/incubator-shardingsphere/issues/2749?

**Comment by tuohai666** [comment]
@wanglichao1 Have you tried 4.0.0-RC1? Is there any problem in RC1?

**Comment by wanglichao1** [comment]
the RC1 is no problem

**Comment by Saisimon** [comment]
Can you give some example codes for reproduce this issue? @wanglichao1

**Comment by wanglichao1** [comment]
the demo url: https://github.com/wanglichao1/shardingsphere-demo
update the db info，run the demo , visit twice  http://localhost:8080/get

**Comment by wanglichao1** [comment]
org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ResultSetUtil
`    public static Object convertValue(final Object value, final Class<?> convertType) {
        if (null == value) {
            return convertNullValue(convertType);
        } 
        if (value.getClass() == convertType) {
            return value;
        }
        if (value instanceof Number) {
            return convertNumberValue(value, convertType);
        }
        if (value instanceof Date) {
            return convertDateValue(value, convertType);
        }
        if (String.class.equals(convertType)) {
            return value.toString();
        } else {
            return value;
        }
    }`

this method can not convert 'byte' to 'boolean'

**Comment by Saisimon** [comment]
shardingsphere-demo works fine, same with #2604, 4.0.0-RC2-SNAPSHOT version has fixed this issue. @wanglichao1

**Comment by tuohai666** [comment]
> org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ResultSetUtil
> ` public static Object convertValue(final Object value, final Class<?> convertType) { if (null == value) { return convertNullValue(convertType); } if (value.getClass() == convertType) { return value; } if (value instanceof Number) { return convertNumberValue(value, convertType); } if (value instanceof Date) { return convertDateValue(value, convertType); } if (String.class.equals(convertType)) { return value.toString(); } else { return value; } }`
> 
> this method can not convert 'byte' to 'boolean'

This code is out of date if you are using 4.0.0-RC2. Please update the code to 4.0.0-RC2-SNAPSHOT head  and try again.

**Comment by wanglichao1** [comment]
4.0.0-RC2-SNAPSHOT is OK

**Comment by tuohai666** [comment]
Good.
