### ISSUE TITLE
sharding-proxy not support replace into clause and also have no format sql clause with Comment like /**/

### ISSUE THREAD

**Issue by jintonghuoya** [apache/incubator-shardingsphere#2764]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Actual behavior
not support replace into clause and also have no format sql clause with Comment like /**/
### Reason analyze (If you can)
sql parser is not supported replace into clause and  filter comment

**Comment by terrymanu** [comment]
Can you fill the template?

**Comment by jintonghuoya** [comment]
> Can you fill the template?

already fill the template

**Comment by terrymanu** [comment]
Replace has supported at 4.0.0-RC2, but not released yet, can you try on that version (in dev branch)?

**Comment by jintonghuoya** [comment]
ok
