### ISSUE TITLE
version 4.* configuration guide doc?

### ISSUE THREAD

**Issue by hello-zhengzq** [apache/incubator-shardingsphere#2766]
seems version 3.* configuration doc about yaml is not work for 4.*, is there any docs for version 4.*

**Comment by terrymanu** [comment]
The document is for 4.x:
https://shardingsphere.apache.org/document/current/en/overview/

The document is for 3.x:
https://shardingsphere.apache.org/document/legacy/3.x/document/en/overview/

What's is question for details?

**Comment by hello-zhengzq** [comment]
solved, i used springboot starter v3.1.0, some problems happened after updating to v4.0.0-RC1, some configuration prefixs changed caused the system could not read the right configuration.

**Comment by terrymanu** [comment]
Is it document for 4.x incorrect, which part of document do we need to update?

**Comment by terrymanu** [comment]
Will close soon if no response anymore.

**Comment by hello-zhengzq** [comment]
Document is correct, problem was solved.
