### ISSUE TITLE
how to get primary key.

### ISSUE THREAD

**Issue by yangweixin** [apache/incubator-shardingsphere#2781]
when i insert a new row, and use key-generator to create a distributed primary key, i can`t get the primary key by `LAST_INSERT_ID()` or mybatis, but i need to get the key to continue the service. 
i read through the document and issue, but still can`t find a solution. i wonder whether there is a way to get the key directly?

**Comment by terrymanu** [comment]
Not support `LAST_INSERT_ID()`, does anybody want to do this feature?

**Comment by liulipengju** [comment]
I think it needs, for example, a table is a foreign key of another table, you need to get the ID, and the distributed primary key that comes with it does not need to configure the workid. Is there any problem with multiple microservices inserting data at the same time?

**Comment by terrymanu** [comment]
I understand someone need this feature. but we have no plan to do this for now.
So I just open this issue for serval days, if anybody interesting this feature, we can discuss more details.

**Comment by terrymanu** [comment]
close for now

**Comment by riyun1989** [comment]
I think it needs too.
