### ISSUE TITLE
Does sharding-jdbc support multiple data source configurations?

### ISSUE THREAD

**Issue by uzdz** [apache/incubator-shardingsphere#2785]
More read-write separation, sub-database and sub-table, support multi-data sources at present?

The ORM framework uses mybatis.

**Comment by terrymanu** [comment]
I can't get your point, what's mean for multi-data sources? such as sharding?

**Comment by uzdz** [comment]
For example, in one of my projects, I need to configure multiple database links. How can I switch data sources between multiple libraries through sharding-jdbc?

**Comment by terrymanu** [comment]
I still cannot understand.

> I need to configure multiple database links.

do you mean database connections?

How can I switch data sources between multiple libraries through sharding-jdbc?

What is multiple libraries? for example, MySQL driver or PostgreSQL driver?

**Comment by uzdz** [comment]
Yes, it is database connection, because the business in the project is scattered in different databases. At this time, it is necessary to dynamically switch the database connection according to the requirements to achieve the effect of accessing different databases at the same time. Then how to switch through sharding-jdbc?

**Comment by terrymanu** [comment]
No, ShardingSphere is recommend for horizontal sharding for now. horizontal sharding mean's every sharding datanode has same structure and save database type.

**Comment by terrymanu** [comment]
For search friendly, I just change title of this issue
