### ISSUE TITLE
how to make a main/sub table rule

### ISSUE THREAD

**Issue by jscene** [apache/incubator-shardingsphere#2787]
## Question
my bussiness like that  t_order and t_order_item is father-son relationship with the order_id column.
but I want to sharding t_order with another column like customer_id . how can I do for this?

t_order 和 t_order_item 是主子表关系，通过order_id关联，但是现在想通过客户id(customer_id)去分库，且子表没有该字段，请问应该怎么实现该效果？有没有类似mycat的主子表关系设置？

**Comment by terrymanu** [comment]
Concept FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sql/
Configuration FYI: 
https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/

search `Binding Table`
