### ISSUE TITLE
Exception occur:  java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11)

### ISSUE THREAD

**Issue by bskllzh** [apache/incubator-shardingsphere#2792]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
Read data correctly from the ByteBuf of sharding-proxy。

source code  of  sharding-proxy：
org.apache.shardingsphere.shardingproxy.transport.mysql.payload.MySQLPacketPayload.readInt1(MySQLPacketPayload.java:49)

MySQLPacketPayload.java： 
public int readInt1() {
        return byteBuf.readByte() & 0xff;
    }

### Actual behavior
[ERROR] 16:43:08.056 [ShardingSphere-Command-6] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): PooledSlicedByteBuf(ridx: 11, widx: 11, ca
p: 11/11, unwrapped: PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 64))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
        at org.apache.shardingsphere.shardingproxy.transport.mysql.payload.MySQLPacketPayload.readInt1(MySQLPacketPayload.java:49)
        at org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.query.binary.execute.MySQLComStmtExecutePacket.<in
it>(MySQLComStmtExecutePacket.java:79)
        at org.apache.shardingsphere.shardingproxy.transport.mysql.packet.command.MySQLCommandPacketFactory.newInstance(MySQLCommand
PacketFactory.java:66)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExe
cuteEngine.java:55)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExe
cuteEngine.java:46)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:84)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
This exception occur  when i make a benchmark test of mysql master-slave that is configed read-write spliting with sysbench 1.0.17。 
benchmark test script ( Sharding-Proxy node ):
sysbench /usr/local/share/sysbench/oltp_read_write.lua 
--time=300 
--mysql-host=XX.XX.XX.XX
--mysql-port=3307 
--mysql-user=XX 
--mysql-password=XX
--mysql-db=db01
--table-size=1000000 
--tables=10 
--threads=100 
--report-interval=10 run 

I have only configed config-master_slave.yaml file that used  read-write spliting in mysql master-slave cluster。

config-master_slave.yaml
######################################################################################################
#
# If you want to connect to MySQL, you should manually copy MySQL driver to lib directory.
#
######################################################################################################

schemaName: db01

dataSources:
  master_ds:
    url: jdbc:mysql://XX.XX.XX.XX:3306/db01?serverTimezone=UTC&useSSL=false
    username: xxxx
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave_ds_0:
    url: jdbc:mysql://XX.XX.XX.XX:3306/db01?serverTimezone=UTC&useSSL=false
    username: xxxx
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave_ds_1:
    url: jdbc:mysql://XX.XX.XX.XX:3306/db01?serverTimezone=UTC&useSSL=false
    username: xxxx
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

masterSlaveRule:
  name: ms_ds
  masterDataSourceName: master_ds
  slaveDataSourceNames:
    - slave_ds_0
    - slave_ds_1

### Example codes for reproduce this issue (such as a github link).

This exception occur  when i make a benchmark test of mysql master-slave that is configed read-write spliting with sysbench 1.0.17。 
benchmark test script ( Sharding-Proxy node ):
sysbench /usr/local/share/sysbench/oltp_read_write.lua 
--time=300 
--mysql-host=XX.XX.XX.XX 
--mysql-port=3307 
--mysql-user=XX 
--mysql-password=XX
--mysql-db=db01
--table-size=1000000 
--tables=10 
--threads=100 
--report-interval=10 run

**Comment by tuohai666** [comment]
Can you point out the SQL, or at least the MySQLCommand?
Can you build 4.0.0-RC2-SNAPSHOT and try with it? We have already tested with sysbench successfully on 4.0.0-RC2-SNAPSHOT.

**Comment by bskllzh** [comment]
1、I think i find the problem.  I check this error that is reported by the sysbench, and i foud this exception occur when the sysbench execute a query ( SQLCommand  BEGIN)  by calling oltp_common.lua script.  And  i think it should be sysbench enable prepared statements by default beginning with sysbench 1.0,  so i am to disable prepared statements with --db-ps-mode=disable in sysbench script.  After these changes, this exception  issues did not occur.

sysbench 1.0.17 benchmark test error report:
FATAL: mysql_stmt_execute() returned error 10002 (2Unknown exception: [readerIndex(11) + length(1) exceeds writerIndex(11): PooledSlicedByteBuf(ridx: 11, widx: 11, cap: 11/11, unwrapped: PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 64))]) for query 'BEGIN'
FATAL: `thread_run' function failed: /usr/local/share/sysbench/oltp_common.lua:405: SQL error, errno = 10002, state = 'C1000': 2Unknown exception: [readerIndex(11) + length(1) exceeds writerIndex(11): PooledSlicedByteBuf(ridx: 11, widx: 11, cap: 11/11, unwrapped: PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 64))]

But i do this change in sysbench script and make a benchmark test again, sysbench output result( tps :0 ):
....
[ 10s ] thds: 100 tps: 0.00 qps: 5.30 (r/w/o: 0.00/0.00/5.30) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
...
I don't know what is reason for this. Thanks a lot.

2、I'm not sure how to compile it, because i am not a programer.  But i try to get developers in our department to help.  By the way, which version of sysbench do you use?   Thx.

**Comment by tuohai666** [comment]
We use 1.1.0, can you have a try?

**Comment by bskllzh** [comment]
1、Not yet. I just asked the developers in our department to build 4.0.0-RC2.   Is it the same for the source code of sharding-proxy  for version 4.0.0-RC2-SNAPSHOT that you above say  and  4.0.0-RC2 of github?  
2、And this morning,  i try to make a benchmark test again for sharding-proxy 4.0.0-RC1 + mysql master-slave.  The sysbench still report exception(tps:0, qps:0) when i make several times test.

**Comment by tuohai666** [comment]
Did I ever say 4.0.0-RC2? There's no 4.0.0-RC2 yet. There's only 4.0.0-RC2-SNAPSHOT.
You can use wireshark to capture SQLs and find out which one get a error response.

**Comment by bskllzh** [comment]
I get source code for version 4.0.0-RC2 from this address(https://github.com/apache/incubator-shardingsphere/releases/tag/4.0.0-RC2).   If this is not , where do i get source code for version 4.0.0-RC2-SNAPSHOT?  Can you provide the download url?

**Comment by tuohai666** [comment]
Please checkout the dev branch and build. (https://github.com/apache/incubator-shardingsphere.git)
That tag is temporary for releasing procedure. The offical release can be found in download page: https://shardingsphere.apache.org/document/current/en/downloads/

**Comment by bskllzh** [comment]
Ok, thanks.

**Comment by tuohai666** [comment]
No response for more than 7 days.
