### ISSUE TITLE
first sql query is very slow , may need  more than 1 secord, may cause by AntlrParsingEngine.parse()

### ISSUE THREAD

**Issue by Ah39** [apache/incubator-shardingsphere#2793]
version 3.1.0 
###  **io.shardingsphere.core.parsing.antlr.AntlrParsingEngine.parse()**
 cost many time 
here is jprofile result
![image](https://user-images.githubusercontent.com/2367243/62128104-4593ca80-b306-11e9-841f-d319f5083f1b.png)

here is the another case 
https://github.com/apache/incubator-shardingsphere/issues/1731

**Comment by terrymanu** [comment]
First time to parse SQL need use ANTLR, ANLTR is pretty slow, from second times, ShardingSphere will cache them and make it faster.

**Comment by zcjhwl** [comment]
Is there any way to avoid this? Such as preheating
