### ISSUE TITLE
Read and write splitting  supports multiple master, each master contains many slaves

### ISSUE THREAD

**Issue by denofiend** [apache/incubator-shardingsphere#2794]
Read and write splitting  supports multiple master, each master contains many slaves

**Comment by terrymanu** [comment]
We have no plan to do this, I just open this issue for serval days, if anybody interesting this feature, we can discuss more details.

**Comment by terrymanu** [comment]
Will close soon if nobody interesting this feature for now.

**Comment by terrymanu** [comment]
close for now
