### ISSUE TITLE
sharding-orchestration-reg-zookeeper-curator and spring-cloud-starter-zookeeper-discovery are not compatible

### ISSUE THREAD

**Issue by Saisimon** [apache/incubator-shardingsphere#2806]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes. 
Spring Cloud: Finchley.RELEASE
Sharding-sphere: 4.0.0-RC1 or 4.0.0-RC2-SNAPSHOT
### Describe the feature you would like.
Can sharding-sphere upgrade the version of Apache Curator?

**Comment by terrymanu** [comment]
No.
The curator version is the last version that JDK 7 supported.
ShardingSphere will upgrade JDK version after version 4.0.0 release.
