### ISSUE TITLE
how to deal between and sql when we use ComplexKeysShardingAlgorithm in 4.0.0-RC1 version

### ISSUE THREAD

**Issue by yangjwInRiver** [apache/incubator-shardingsphere#2808]

**Comment by terrymanu** [comment]
ComplexKeysShardingAlgorithm is to process the sharding case in which multiple sharding keys are used; ComplexShardingStrategy needs to be used together. It has a relatively complex logic that requires developers to deal by themselves.

FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sharding/

**Comment by yangjwInRiver** [comment]
> ComplexKeysShardingAlgorithm is to process the sharding case in which multiple sharding keys are used; ComplexShardingStrategy needs to be used together. It has a relatively complex logic that requires developers to deal by themselves.
> 
> FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sharding/

I know how to use it . 
I mean i use ComplexShardingStrategy with two colums , and one colums is datetime type.
when i execute this sql
   select * from table_a where colum_a='' and colum_b between time1 and time2
will throw  exception like this :
org.apache.shardingsphere.core.strategy.route.value.BetweenRouteValue cannot be cast to org.apache.shardingsphere.core.strategy.route.value.ListRouteValue

I find other issue the same with me , and i known it is a bug in 4.0.0-RC1 version. 
I just want to avoid it in my projection.

3Q for you answer.

**Comment by yangjwInRiver** [comment]
I use equal replace between and .and i hope this bug can be fixed next version
