### ISSUE TITLE
There is a problem with using hint in in spring-boot-starter-data-jpa

### ISSUE THREAD

**Issue by windlikeman** [apache/incubator-shardingsphere#2809]
## Question
There is a problem with using hint in in spring-boot-starter-data-jpa
sharding version：4.0.0-RC1
spring-boot-starter-data-jpa version：2.0.1

database config：
spring.shardingsphere.sharding.tables.da_hua_uid.actual-data-nodes=ds-$->{2..4}.da_hua_uid
spring.shardingsphere.sharding.tables.da_hua_uid.key-generator.column=id
spring.shardingsphere.sharding.tables.da_hua_uid.key-generator.type=SNOWFLAKE

when i test:

2019-08-05 14:38:02.235  WARN 9720 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23502
2019-08-05 14:38:02.235 ERROR 9720 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: null value in column "id" violates not-null constraint
  detailed：Failing row contains (null, 7778, 4, 2019-08-05 14:38:02.15, 2019-08-05 14:38:02.15, null).

can you help me? please!

**Comment by terrymanu** [comment]
Please read error message: `ERROR: null value in column "id" violates not-null constraint` and try to understander it fist before submit an issue.

**Comment by 291277058** [comment]
Is that mean key-generator will not generator key for column id. @terrymanu When i use the jpa+key-generator ,i found the id is correct in DTO,but error hanpened when inster into db.
Here is the sql
`
insert into order_item20201  
(app_id, create_date, orderno, original_price, pay_date, pay_source, price, product_list, source_orderno, status, user_id, id) 
VALUES 
(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ::: 
[null, 2020-07-10 15:38:05.945, uoI0H, 0.0, null, 488372535331651584, 0.0, null, null, 0, null, null]
`
488372535331651584 is key generator by SNOWFLAKE algorithm.
