### ISSUE TITLE
why shardingJDBC change my now() function to a string when I insert a data

### ISSUE THREAD

**Issue by Shj451148969** [apache/incubator-shardingsphere#2812]
like sql: insert into table(ctime) values(now());
this sql while get an error, because the value now() will be changed to a string 'now()' by shardingshpere
how to fix it?

**Comment by terrymanu** [comment]
Duplicate with #1497, #2225, #2745 and #2810

**Comment by yogaling** [comment]
how can i use for instead?

**Comment by xiaoyuge** [comment]
Is this problem fixed?
