### ISSUE TITLE
For ComplexKeysShardingAlgorithm override behaviour for `databaseShardingValues` empty

### ISSUE THREAD

**Issue by rimal** [apache/incubator-shardingsphere#2815]
## Question
In case of `ComplexKeysShardingAlgorithm`, if `databaseShardingValues` is empty, the custom algorithm configured in application.properties is not called at all and all available target names are returned from the `StandardRoutingEngine`.
Is there anyway to override this behaviour? May be, some method in `StandardRoutingEngine` which can be overriden or some hook which can be configured.

**Comment by KomachiSion** [comment]
Hi @rimal, if `databaseShardingValues ` is empty means that there are no sharding column in your SQL. In this case, ShardingSphere will do full routing in design.
The behaviour can't be overrode whether in `ComplexKeysShardingAlgorithm ` or `ComplexKeysShardingAlgorithm `.

**Comment by rimal** [comment]
Thanks for the reply @KomachiSion . I have a use case where if sharding column is not there in the SQL, I want to get the value from a thread local (on basis of which I will be able to decide the target name). Is there anyway possible to do this?

**Comment by KomachiSion** [comment]
> Thanks for the reply @KomachiSion . I have a use case where if sharding column is not there in the SQL, I want to get the value from a thread local (on basis of which I will be able to decide the target name). Is there anyway possible to do this?

Only modify the source code to achieve this use case.
We can discuss in your new reference issue.
