### ISSUE TITLE
support explain or show keyword sql

### ISSUE THREAD

**Issue by copyshop** [apache/incubator-shardingsphere#2816]
for example:

broad table: t_test;

mysql terminate: 

mysql> explain insert into t_test(id,name) values(2,"test1")
or
mysql> show insert into t_test(id,name) values(2,"test1")

print:
	Actual SQL: ds_0 ::: insert into t_test(id,name) values(2, "test1")
	Actual SQL: ds_1 ::: insert into t_test(id,name) values(2, "test1")
	
it is convenient for us to view sharding route information when we route config is wrong,It's just a suggestion.This is project is very beautiful.

**Comment by cherrylzhao** [comment]
hi, sharding-proxy support `sctl:explain insert into t_test(id,name) values(2,"test1")
 `

**Comment by cherrylzhao** [comment]
we will update the document later.

**Comment by copyshop** [comment]
think you，that's great.

**Comment by terrymanu** [comment]
I create a new issue on document repo
FYI: https://github.com/apache/incubator-shardingsphere-doc/issues/217
