### ISSUE TITLE
Too many keys are generated. There are only 1 target objects. You either specified a wrong 'keyProperty' or encountered a driver bug like #1523.

### ISSUE THREAD

**Issue by azkoss** [apache/incubator-shardingsphere#2825]
MyBatis 3.5.2
sharding-jdbc-spring-boot-starter-4.0.0-RC1
mysql-driver:8.0.17

<insert id="batchSave" parameterType="java.util.List" useGeneratedKeys="true" keyColumn="id" keyProperty="id">
        insert into sys_barcodes      
		 (`code`,`name`,`brand`,`spec`,`price`)
         values ('1111','2222','','',0.09), ('1111','2222','','',0.09), ('1111','2222','','',0.09), ('1111','2222','','',0.09);

</insert>

org.apache.ibatis.executor.ExecutorException: Too many keys are generated. There are only 1 target objects. You either specified a wrong 'keyProperty' or encountered a driver bug like #1523.
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.assignKeysToParam(Jdbc3KeyGenerator.java:117)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.assignKeys(Jdbc3KeyGenerator.java:100)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:81)

**Comment by tristaZero** [comment]
Sorry, but can you set `sql.show` =true, can provide logic SQLs and actual SQLs in log file?
@azkoss 
Or, you can try 4.0.0-RC2. I can not get the detail of your issue, but we actually fix a bug about generatedKey, so you can give a try for 4.0.0.RC2

**Comment by tristaZero** [comment]
Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by SeniorBoy** [comment]
version.4.1.1    Too many keys are generated.

**Comment by SeniorBoy** [comment]
private void prepare() {
        executionContext = prepareEngine.prepare(sql, getParameters());
        findGeneratedKey().ifPresent(generatedKey -> generatedValues.add(generatedKey.getGeneratedValues().getLast()));
    }

generatedValues size() > 1
