### ISSUE TITLE
The same transaction executes the following two sqls, and the last one is not the result of the current transaction change.

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#2827]
The same transaction executes the following two sqls, and the last one is not the result of the current transaction change.The query result is 0 instead of 10，Should be 10

 UPDATE user
  SET cusum_of_month = cusum_of_month + 10
  where   
     sku= '99985463'
     AND warehouse_code = '0013'
     AND first = '300800'
     AND second = '0';

    SELECT sku ,first ,second ,IFNULL(SUM(cusum_of_month),0) as cusum_of_month
         FROM user
        WHERE is_deleted = 0 and 
            (sku = '99985463'
			AND first = '300800' 
			and second = '0')
        GROUP BY sku,first ,second ;

**Comment by cherrylzhao** [comment]
sorry fo late response.
would you please tell us following information

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

**Comment by xfyang1989** [comment]
4.0.0_RC1

发自我的 iPhone

**Comment by cherrylzhao** [comment]
did you use sharding-transaction in your project? Local , XA, or Base? you should make your question more clear.

**Comment by xfyang1989** [comment]
Spring's own transaction，@Transactional(readOnly = false, isolation = Isolation.READ_COMMITTED, rollbackFor = Exception.class)

**Comment by cherrylzhao** [comment]
this is a local transaction, ShardingSphere will support it beyond your spring setting.
would you please push your example in GitHub to let me reproduce it.

**Comment by terrymanu** [comment]
It is really too long time for waiting response. 
I just close it.
