### ISSUE TITLE
SQL where include (, report "Missing right paren."

### ISSUE THREAD

**Issue by liutwv** [apache/incubator-shardingsphere#2831]
### Which version of ShardingSphere did you use?
4.0.0-RC1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
where my application run sql like this: 
select * from tb_xxx where xxx = ? and (xxx like '%' #{fuzzyName} '%'）
whatever the table tb_xxx using sharding or not
the sql is no problem. where I don't use sharding-jdbc, the sql runs fine. 
### Actual behavior
when I use sharding-jdbc, the sql can't run successful. 
the error message is : 
Caused by: java.lang.IllegalStateException: Missing right paren.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:459)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionForParen(PredicateExtractor.java:108)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionInternal(PredicateExtractor.java:79)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionInternal(PredicateExtractor.java:73)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extract(PredicateExtractor.java:60)

### Reason analyze (If you can)
PredicateExtractor.java: 
    private Optional<OrConditionSegment> extractConditionForParen(Map<ParserRuleContext, Integer> placeholderIndexes, ParserRuleContext exprNode) {
        int index = -1;

        for(int i = 0; i < exprNode.getChildCount(); ++i) {
            if (Paren.isLeftParen(exprNode.getChild(i).getText())) {
                index = i;
                break;
            }
        }

        if (-1 != index) {
            Preconditions.checkState(Paren.match(exprNode.getChild(index).getText(), exprNode.getChild(index + 2).getText()), "Missing right paren.");
            return RuleName.EXPR.getName().equals(exprNode.getChild(index + 1).getClass().getSimpleName()) ? this.extractConditionInternal(placeholderIndexes, (ParserRuleContext)exprNode.getChild(index + 1)) : Optional.absent();
        } else {
            Optional<ConditionSegment> condition = this.buildCondition(placeholderIndexes, exprNode);
            if (!condition.isPresent()) {
                return Optional.absent();
            } else {
                OrConditionSegment result = new OrConditionSegment();
                AndConditionSegment newAndCondition = new AndConditionSegment();
                newAndCondition.getConditions().add(condition.get());
                result.getAndConditions().add(newAndCondition);
                return Optional.of(result);
            }
        }
    }

就是我执行where条件中带括号的sql语句时，不管对应的表是否分表，都会报缺少右括号。
源码里
Preconditions.checkState(Paren.match(exprNode.getChild(index).getText(), exprNode.getChild(index + 2).getText()), "Missing right paren.");
似乎是处理函数时对括号的处理吧？为什么会不支持条件中的括号呢？
select count(*) from tb_customer where company_id = ? and (hospital_name  like '%' #{fuzzyName} '%');

我也尝试退到3.1.0版本，但同样的sql语句又报了空指针异常

**Comment by liutwv** [comment]
知道了，是like写法问题导致的括号识别，改成这种就可以了：'%${fuzzyName}%'

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by sanmusee** [comment]
wo ye yu dao le zhe ge bug: "missing right paren",  but sql ming ming jiu shi zheng que de.
