### ISSUE TITLE
sharding proxy  “select * into outfile”  fail

### ISSUE THREAD

**Issue by wangshiyu-love** [apache/incubator-shardingsphere#2834]
5.6.0-Sharding-Proxy 4.0.0-RC2  execute  【select * into outfile 】fail：
errorReason：【The MySQL server is running with the --secure-file-priv option so it cannot execute this statement】   How do I change the configuration for have export permissions

**Comment by terrymanu** [comment]
We have no plan to do this, I just open this issue for serval days, if anybody interesting this feature, we can discuss more details.

**Comment by terrymanu** [comment]
Will close soon if no volunteer interested

**Comment by terrymanu** [comment]
Closed for now
