### ISSUE TITLE
复合分片是否能和强制分片一起使用

### ISSUE THREAD

**Issue by 780910739** [apache/incubator-shardingsphere#2836]
![1565320157(1)](https://user-images.githubusercontent.com/44565795/62751406-2f200880-ba96-11e9-97c9-49a116d527c0.jpg)
![1565320198(1)](https://user-images.githubusercontent.com/44565795/62751441-43640580-ba96-11e9-9fc3-f7b99f2dd24f.jpg)
如图，当打开复合分片注释时，强制路由不生效

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
