### ISSUE TITLE
LimitDecoratorMergedResult in subquery problem

### ISSUE THREAD

**Issue by lyy2002** [apache/incubator-shardingsphere#2839]
sql :
`SELECT
	*
FROM
	(
		SELECT
			*
		FROM
			'order'
		ORDER BY
			id DESC
		LIMIT 0,
		10
	) AS o
LEFT JOIN order_item item ON item.order_id = o.id`

Expectations are 20 results, and 10 results due to limit restrictions

version:3.1.0

**Comment by tristaZero** [comment]
Please try 4.0.0-RC1 or RC2-SNAPSHOT.
There's known issue in 3.1.0 about LIMIT.
@lyy2002

**Comment by terrymanu** [comment]
No response any more, I just close it
