### ISSUE TITLE
How to update actualDataNodes?

### ISSUE THREAD

**Issue by 83945105** [apache/incubator-shardingsphere#2844]
I need to change the sharding rules without restarting the server,but the actualDataNodes are written to death,so how do I update actualDataNodes dynamically?

**Comment by 83945105** [comment]
I'm using java configuration.

**Comment by terrymanu** [comment]
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

FYI: https://shardingsphere.apache.org/document/current/en/features/orchestration/config-center/

**Comment by 83945105** [comment]
我是一名中国开发者，我英文不好就不写蹩脚的英文了，如果没有人能看懂我说的就请无视我下面的话。
我知道开发维护一个开源项目需要耗费很大的时间及精力，因此我十分钦佩ShardingSphere的作者们。
但是经过我这几天的摸索与使用（4.0.0-RC1），想提几个意见：
1、官网文档错误，明明从4.x入口进入的文档，但是文档给予的示例代码明显与4.x版本不符，对此我通过阅读源码已经解决了大部分配置问题。
2、文档过于简单，读起来感觉什么都说了，但是实际操作起来又发现很多细节没讲。
3、官方可否提供或者说对中国用户提供一些实时交流的讨论渠道。
另外，对于该issues的问题，我目前已经解决了一部分，我不想使用Zookeeper，我只想简单的实现动态管理actualDataNodes，因此我重写了RegistryCenter接口，由于代码注释很简单，且官网没有该功能详细的文档描述，我花费了几个小时摸索到这里，并测试了相关功能，终于成功实现了动态修改sql.show，但是目前我还没有找到如何修改自定义的分库分表规则方法，我在尝试修改"/orchestration-sharding-data-source/config/schema/logic_db/rule"这个配置，但是我看value是个String类型，我不知道要传什么格式的value过去，text？json？我试过将yml内容读取后传过去，但是出现了yml格式异常，目前正在摸索解决办法，假如这一步通过了，接下来还有一个关键点，我的分库分表规则是使用Hint相关实现，yml文件方式无法满足我的业务逻辑。我不知道如何将一段复杂的java逻辑通过yml方式或字符串方式传递给更新事件。
以上是我这几天尝试使用ShardingSphere相关功能的经历和感想，希望该项目能越做越好。

**Comment by 83945105** [comment]
问题已解决，奉上解决方案，以便需要的用户参考：https://blog.csdn.net/qq_32588349/article/details/99440985

**Comment by vipchenwei** [comment]
最近也在研究这个，官网的文档不知道是我打开方式不对还是怎么的，感觉很多地方描述不对，一些用法也没有说明，楼上的牛b呀

**Comment by vipchenwei** [comment]
> 问题已解决，奉上解决方案，以便需要的用户参考：https://blog.csdn.net/qq_32588349/article/details/99440985

顶顶顶
