### ISSUE TITLE
table doesn't exist

### ISSUE THREAD

**Issue by wqy960504** [apache/incubator-shardingsphere#2850]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-jdbc-core 3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharing-JDBC
### Expected behavior
when I search table , date will be return.
### Actual behavior
when I search table , It have table desen't exist error.
### Reason analyze (If you can)
I don't know.
In my program. EveryDay will create some tables.when I search the table's data, it have a error.
error message is :
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'frxs_fund_clearing.t_fund_platform_clearing_detail' doesn't exist

when I restart my jvm process.The erros is disappear.

In my program. I used ComplexKeysShardingAlgorithm. In this search , it will take shardingKey in parametes and use shardingKey to find table.But actually , if I dosen't restart jvm process. It is not in used.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

select * from table where shardingKey = 'some' and date = 'someDay';

**Comment by terrymanu** [comment]
I don't think this is a bug
Please read the document and try to understand example first

**Comment by terrymanu** [comment]
Can you explain why close this issue without any reason to update?
We hope every issue have their value which should include enough information to let other user search and reference.
