### ISSUE TITLE
ComplexKeysShardingAlgorithm example

### ISSUE THREAD

**Issue by ghost0224** [apache/incubator-shardingsphere#2851]
## Question
Is there any ComplexKeysShardingAlgorithm example? I didn't find it in the document: https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sharding/

**Comment by terrymanu** [comment]
Not yet, anybody want add a example for ComplexKeysShardingAlgorithm?

**Comment by DongJigong** [comment]
> Not yet, dose anybody want add a example for ComplexKeysShardingAlgorithm?

 https://github.com/DongJigong/shardingsphere-issues-issue2865.git  This example hope can help you

**Comment by terrymanu** [comment]
Can you consider about submit a pull request for example? @DongJigong

**Comment by DongJigong** [comment]
> Can you consider about submit a pull request for example? @DongJigong

Ok, I will do submit a pull request.

**Comment by terrymanu** [comment]
@DongJigong Hi, any update on this issue?

**Comment by terrymanu** [comment]
Closed for no response any more.
