### ISSUE TITLE
The dml/dql operation in the same thread don't route to master database.

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2855]
As the official doc said "If there is write operation in the same thread and database connection, all the following read operations must be from the master database to ensure data consistency.", but when i test insert and select operation in the same thread, it didn't route to the master database but slave node. 

version: v.3.1.0
project: sharding-proxy

**Comment by terrymanu** [comment]
Could you try example first and make sure the example is ok or not

**Comment by terrymanu** [comment]
Will close soon if no response any more.

**Comment by terrymanu** [comment]
I just close this issue and set as invalid because of no response any more.
