### ISSUE TITLE
Can I change DataSourceMetaData's pattern ?

### ISSUE THREAD

**Issue by fennykk** [apache/incubator-shardingsphere#2863]
**i have 128 databases**, if i use druid for database pool, it will create **256 threads** for these databases, but these threads are useless, maybe 2 threads is enough.

so i use my company database pool called "caelus", it can change the database dynamic, and its core call like this:

`String jdbcUrl = "jdbc:mysql://127.0.0.1:3306?useUnicode=true";`
`Connection connection = DriverManager.getDriver(jdbcUrl).connect(jdbcUrl, driverProperties);`
`connection.setCatalog("database001");`

caelus use setCatalog to change the actual database 

when i use druid , the connection may like this

`String jdbcUrl = "jdbc:mysql://127.0.0.1:3306/database001?useUnicode=true";`
`Connection connection = DriverManager.getDriver(jdbcUrl).connect(jdbcUrl, driverProperties);`

at lastest shardingsphere version , MySQLDataSourceMetaData will check the jdbcUrl the pattern like

`private final Pattern pattern = Pattern.compile("jdbc:mysql:(\\w*:)?//([\\w\\-\\.]+):?([0-9]*)/([\\w\\-]+);?\\S*", Pattern.CASE_INSENSITIVE);`

so when i use the lastest version , my jdbcUrl is invalid because the metaData url is 

`jdbc:mysql://127.0.0.1:3306?useUnicode=true`

finally i found no way to change this pattern , so i can only use the old version 2.0.3

**Comment by terrymanu** [comment]
ShardingSphere just ref MySQL's official URL format, FYI: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html

So URL without database name is invalid.
If you want do your customized feature, please change the code as you want, but please note, we will not merge un-official URL format into ShardingSphere

**Comment by fennykk** [comment]
OK,
i means can i set the pattern in code as i want ? or maybe ShardingSphere can provide a setting to uncheck this pattern ?
thank you
