### ISSUE TITLE
4.0.0-RC1 replace into (columns) values (xx),(xx),(xx)... not working!

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2864]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
  </dependency>

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

sharding-jdbc

**Comment by terrymanu** [comment]
What is the error message

**Comment by DongJigong** [comment]
> What is the error message?

line 1:0 mismatched input 'REPLACE' expecting {SET, WITH, ALTER, COMMIT, CREATE, DELETE, DROP, GRANT, REVOKE, ROLLBACK, START, TRUNCATE, BEGIN, INSERT, RENAME, SAVEPOINT, SELECT, UPDATE}

**Comment by terrymanu** [comment]
duplicate with #2315
