### ISSUE TITLE
4.0.0-RC1 jpa select result change some values and save shoud update Row Data rather then insert 

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2865]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

Jpa save data which has a primary key should update rather than insert a new row data.
I am using jpa saveAll method to save multiple row data.

**Comment by KomachiSion** [comment]
@DongJigong, can you provide a example code which can reproduce this issue?

**Comment by DongJigong** [comment]
> @DongJigong, can you provide a example code which can reproduce this issue?

I have tracked my code, I found sharding sql log show that sharding-jdbc will select one row with id  and insert it. I have 24 rows data. sharding iterate 24 times.

**Comment by KomachiSion** [comment]
> I have tracked my code, I found sharding sql log show that sharding-jdbc will select one row with id and insert it. I have 24 rows data. sharding iterate 24 times.

Sorry, I can't understand your situation accurately. You means that you have found the reason?

**Comment by DongJigong** [comment]
> > I have tracked my code, I found sharding sql log show that sharding-jdbc will select one row with id and insert it. I have 24 rows data. sharding iterate 24 times.
> 
> Sorry, I can't understand your situation accurately. You means that you have found the reason?

**Comment by DongJigong** [comment]
This is a very common situation,I think you could reproduce it easily

**Comment by KomachiSion** [comment]
OK, I will try to reproduce.

**Comment by DongJigong** [comment]
> OK, I will try to reproduce.

![image](https://user-images.githubusercontent.com/8855265/62989204-b0eaaa00-be79-11e9-9b0e-6060317188de.png)
This table has a complex column slices. All my descriptions depend on operating this table

**Comment by KomachiSion** [comment]
> > OK, I will try to reproduce.
> 
> ![image](https://user-images.githubusercontent.com/8855265/62989204-b0eaaa00-be79-11e9-9b0e-6060317188de.png)
> This table has a complex column slices. All my descriptions depend on operating this table

Can you provide full sharding configuration?

I still think that if there is a example code will be better, which can avoid our meaningless intelligence exchange and improve efficiency.

**Comment by DongJigong** [comment]
Ok,I will checkout this problem myself,if I have a conlusion,I will reply you,thanks

**Comment by KomachiSion** [comment]
@DongJigong, I try to reproduce your problem, but failed. 
I create a sharding table `t_order` with three column.
configuration following:
```
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.show_sql=true

spring.shardingsphere.enabled=true
spring.shardingsphere.datasource.names=ds0, ds1

spring.shardingsphere.datasource.ds0.type=org.apache.commons.dbcp2.BasicDataSource
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://localhost:3306/demo_ds_0
spring.shardingsphere.datasource.ds0.username=root
spring.shardingsphere.datasource.ds0.password=

spring.shardingsphere.datasource.ds1.type=org.apache.commons.dbcp2.BasicDataSource
spring.shardingsphere.datasource.ds1.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds1.url=jdbc:mysql://localhost:3306/demo_ds_1
spring.shardingsphere.datasource.ds1.username=root
spring.shardingsphere.datasource.ds1.password=

spring.shardingsphere.sharding.default-data-source-name=ds0
spring.shardingsphere.sharding.tables.t_order.actual-data-nodes=ds$->{0..1}.t_order_$->{0..1}
spring.shardingsphere.sharding.tables.t_order.database-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.t_order.database-strategy.inline.algorithm-expression=ds$->{id % 2}
spring.shardingsphere.sharding.tables.t_order.table-strategy.inline.sharding-column=order_id
spring.shardingsphere.sharding.tables.t_order.table-strategy.inline.algorithm-expression=t_order_$->{order_id % 2}

spring.shardingsphere.props.sql.show=true
```

Insert 24 row to `t_order` as init data. Then use `saveAll` to change column `status`:
```
        OrderRepo repo = applicationContext.getBean(OrderRepo.class);
        List<Order> list = new ArrayList<>();
        for (int i = 1; i <= 24; i++) {
            Order order = new Order();
            order.setId(i);
            order.setOrderId(i);
            order.setStatus("TEST");
            list.add(order);
        }
        repo.saveAll(list);
```

It can update, not insert new row:
```
Hibernate: select order0_.id as id1_0_0_, order0_.order_id as order_id2_0_0_, order0_.status as status3_0_0_ from t_order order0_ where order0_.id=?
2019-08-14 10:42:21.713  INFO 1581 --- [           main] ShardingSphere-SQL                       : Rule Type: sharding
2019-08-14 10:42:21.713  INFO 1581 --- [           main] ShardingSphere-SQL                       : Logic SQL: select order0_.id as id1_0_0_, order0_.order_id as order_id2_0_0_, order0_.status as status3_0_0_ from t_order order0_ where order0_.id=?
2019-08-14 10:42:21.713  INFO 1581 --- [           main] ShardingSphere-SQL                       : SQLStatement: ShardingSelectOptimizedStatement(tables=Tables(tables=[Table(name=t_order, alias=Optional.of(order0_))], schema=Optional.absent()), groupBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.groupby.GroupBy@12214f2f, orderBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderBy@756c67cd, selectItems=SelectItems(startIndex=7, stopIndex=96, distinctRow=false, items=[ColumnSelectItem(owner=order0_, name=id, alias=Optional.of(id1_0_0_)), ColumnSelectItem(owner=order0_, name=order_id, alias=Optional.of(order_id2_0_0_)), ColumnSelectItem(owner=order0_, name=status, alias=Optional.of(status3_0_0_))], tables=[TableSegment(startIndex=103, stopIndex=109, name=t_order, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.of(order0_))]), pagination=org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination@50de907a, containsSubquery=false)
2019-08-14 10:42:21.713  INFO 1581 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: select order0_.id as id1_0_0_, order0_.order_id as order_id2_0_0_, order0_.status as status3_0_0_ from t_order_0 order0_ where order0_.id=? ::: [24]
2019-08-14 10:42:21.713  INFO 1581 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: select order0_.id as id1_0_0_, order0_.order_id as order_id2_0_0_, order0_.status as status3_0_0_ from t_order_1 order0_ where order0_.id=? ::: [24]

...

Hibernate: update t_order set order_id=?, status=? where id=?
2019-08-14 10:42:22.158  INFO 1581 --- [           main] ShardingSphere-SQL                       : Rule Type: sharding
2019-08-14 10:42:22.159  INFO 1581 --- [           main] ShardingSphere-SQL                       : Logic SQL: update t_order set order_id=?, status=? where id=?
2019-08-14 10:42:22.159  INFO 1581 --- [           main] ShardingSphere-SQL                       : SQLStatement: ShardingConditionOptimizedStatement(tables=Tables(tables=[Table(name=t_order, alias=Optional.absent())], schema=Optional.absent()), shardingConditions=ShardingConditions(conditions=[ShardingCondition(routeValues=[ListRouteValue(columnName=id, tableName=t_order, values=[24])])]), encryptConditions=EncryptConditions(conditions=[]))
2019-08-14 10:42:22.159  INFO 1581 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: update t_order_0 set order_id=?, status=? where id=? ::: [24, TEST, 24]
2019-08-14 10:42:22.162  INFO 1581 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: update t_order_1 set order_id=?, status=? where id=? ::: [24, TEST, 24]
```

**Comment by KomachiSion** [comment]
My example code : https://github.com/KomachiSion/shardingsphere-issues/tree/master/issue2865

**Comment by DongJigong** [comment]
I am afraid this example is not match my situation. I will use your example change some config and code to check out if this could reproduce my problem，thanks

**Comment by DongJigong** [comment]
> My example code : https://github.com/KomachiSion/shardingsphere-issues/tree/master/issue2865

I have track the sql excution and I found that Jpa saveAll method using ProxyConnection(Hikari) instead of AbstractConnectionAdapter(sharding)

**Comment by KomachiSion** [comment]
Of course, the stack is your application -> jpa -> sharding -> hikari pool -> origin jdbc

**Comment by DongJigong** [comment]
> Of course, the stack is your application -> jpa -> sharding -> hikari pool -> origin jdbc

I found that every row data will select by id then insert it.But insert row data without my primary auto increment ID. I think this is the place where error happened.

**Comment by KomachiSion** [comment]
I don't know, the information you provide is so isolation, I can't locate where or what problem caused.

1. What's your sharding configuration?
2. What's your logic SQL?
3. What's the actual SQL after shardingsphere rewrite?
4. Primary is auto increment ID, Make sure whether JPA/Hibernate cached the entity you select by ID.

I suggest you provide enough information let us reproduce your problem, or example code which can reproduce so that we can help you find the reason.

**Comment by DongJigong** [comment]
> I don't know, the information you provide is so dispersed, I can't locate where or what problem caused.
> 
> 1. What's your sharding configuration?
> 2. What's your logic SQL?
> 3. What's the actual SQL after shardingsphere rewrite?
> 4. Primary is auto increment ID, Make sure whether JPA/Hibernate cached the entity you select by ID.
> 
> I suggest you provide enough information let us reproduce your problem, or example code which can reproduce so that we can help you find the reason.

https://gitter.im  I have send a message to you. I hope could have a talk privately

**Comment by KomachiSion** [comment]
Sorry, I don't have full time to talk privately, I suggest you provide a the simplest example code without your business information or full configuration/entity,repo/SQL.
We will reply after reproducing and finding the reason.

**Comment by DongJigong** [comment]
> Sorry, I don't have full time to talk privately, I suggest you provide a the simplest example code without your business information or full configuration/entity,repo/SQL.
> We will reply after reproducing and finding the reason.
> 
> And if you provide them in issue can help others understand the problem and context.

https://github.com/DongJigong/shardingsphere-issues-issue2865.git

**Comment by KomachiSion** [comment]
> It turns out that the saveAll method changed nothing which also is a problem.

It looks like other problem, please open a new issue to describe it. Thanks.

> but not reproduce my situation.

Please tell me **related information which can reproduce the problem about this issue**.

BTW, the link your provide only has a `README.md`

**Comment by DongJigong** [comment]
> > It turns out that the saveAll method changed nothing which also is a problem.
> 
> It looks like other problem, please open a new issue to describe it. Thanks.
> 
> > but not reproduce my situation.
> 
> Please tell me **related information which can reproduce the problem about this issue**.
> 
> BTW, the link your provide only has a `README.md`

So sorry, I have pushed code now. you can check out it. I think this problem maybe has a connection to my issue. After all，it changes nothing on this data.

**Comment by KomachiSion** [comment]
From your example code, I find you do not config `actual_node`, it will cause can not find data with full-routing.

After add `spring.shardingsphere.sharding.tables.t_order.actual-data-nodes=ds0.t_order_100_201908`, the problem solved.

**Comment by DongJigong** [comment]
> From your example code, I find you do not config `actual_node`, it will cause can not find data with full-routing.
> 
> After add `spring.shardingsphere.sharding.tables.t_order.actual-data-nodes=ds0.t_order_100_201908`, the problem solved.

Obviously, I need a table slice . I cannot config like this way

**Comment by KomachiSion** [comment]
It can config as groovy program, like `ds0.t_order_${0..100}_${201901..201912}`, it means t_order_0_201901, t_order_0_201902 ..... t_order_100_ 201911, t_order_100_201912.

**Comment by KomachiSion** [comment]
Other solution, I think, is add where clause with sharding column to query SQL, it can route SQL to actual node and find data.

**Comment by DongJigong** [comment]
> Other solution, I think, is add where clause with sharding column to query SQL, it can route SQL to actual node and find data.

I have understood what you mean. many thanks

**Comment by DongJigong** [comment]
> > Other solution, I think, is add where clause with sharding column to query SQL, it can route SQL to actual node and find data.
> 
> I have understood what you mean. many thanks. But I think according to my data columns, the actual node should be found.

I have changed some code and my problem appeared, please recheck.
https://github.com/DongJigong/shardingsphere-issues-issue2865.git

**Comment by DongJigong** [comment]
> > > Other solution, I think, is add where clause with sharding column to query SQL, it can route SQL to actual node and find data.
> > 
> > 
> > I have understood what you mean. many thanks. But I think according to my data columns, the actual node should be found.
> 
> I have changed some code and my problem appeared, please recheck.
> https://github.com/DongJigong/shardingsphere-issues-issue2865.git

I add actual nodes then everything works fine. so the actual nodes must be configured finally.
