### ISSUE TITLE
How to get the results of the database sharding algorithm in the table sharding algorithm

### ISSUE THREAD

**Issue by ningyu1** [apache/incubator-shardingsphere#2873]
## How to get the results of the database fragmentation algorithm in the table fragmentation algorithm

Partition key format: `YYYYMM`, for example: 201908

Database actualDataNodes: ds${2017..2019}

Table actualDataNodes: ds${2017..2019}

Now I am experiencing the following problem.

When implementing the RangeShardingAlgorithm interface, when the 'between and' is processed, the condition is 'between 201801 and 201908'. In fact, you should go to the order1 to order12 table of the ds2018 library and the order1 to order8 table of the ds2019 library for query.

In the algorithm class of the table, how to obtain the routedDataSources value in the current loop, and determine whether to cross the year according to routedDataSources, thereby determining the range of the table.

The current status quo is that the database algorithm returns 'ds2018, ds2019', and then calls the table 'dosharding' method according to the number of sub-database results, but the table 'dosharding' method cannot get the routedDataSources of the current loop, so it is impossible to know. What database is the current loop, so it is impossible to handle the exact range of table values.

This problem is bothering me and I hope to get help.

**Comment by KomachiSion** [comment]
The problem is similar to #2193. We plan to fix it in 4.0.0-RC3

**Comment by ningyu1** [comment]
@KomachiSion tks.

**Comment by ningyu1** [comment]
@KomachiSion 
Different from question #2193 
The problem is that need to pass the value of 'routedDataSources' in the ‘algorithm’ implementation class.

**Comment by KomachiSion** [comment]
Sorry @ningyu1,  is the problem your table algorithm don't know what datasource is?

For current route design, the datasource and the table algorithm is separated, they should calculate Independently. The algorithm is designed to get the route datasource or table only by the condition values. So your situation may cause route to more data nodes.

**Comment by KomachiSion** [comment]
No response more than 7 days, close issue
