### ISSUE TITLE
How can I get a distribution package/release/bin from source code?

### ISSUE THREAD

**Issue by reynaldliu** [apache/incubator-shardingsphere#2874]
How can I get a distribution package/release/bin from source code?

mvn clean install -Prelease   

Only three jar files can be obtained. How to store the jar files of other lib directories, how can I get a complete runable bin/release package with start.sh?

last update at 

https://www.apache.org/dyn/closer.cgi?path=incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin.tar.gz

how can get a 4.0.0-RC2 -xxx-bin.tar.gz     download?

**Comment by terrymanu** [comment]
4.0.0-RC2 has not released yet
