### ISSUE TITLE
ComplexKeysShardingAlgorithm  sql  between and suport

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2880]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes
### Describe the feature you would like.
![image](https://user-images.githubusercontent.com/8855265/63086219-fd211180-bf81-11e9-846d-d3f955fc9133.png)
need to add RangeAlgorithm to ComplexShardingStrategyConfiguration.

**Comment by KomachiSion** [comment]
duplicate with #2613
