### ISSUE TITLE
shardingsphere+seata+dubbo No Rollback

### ISSUE THREAD

**Issue by huangjian888** [apache/incubator-shardingsphere#2881]
I have consulted relevant documents and issues,but no solution has been found.
The project uses shardingsphere + Seata + Dubbo，but does not roll back using Dubbo

Dubbo provider Code:
import com.alibaba.dubbo.config.annotation.Service;
import com.baomidou.mybatisplus.service.impl.ServiceImpl;
import com.company.spring.boot.shardingsphere.seata.modules.entity.OrderEntity;
import com.company.spring.boot.shardingsphere.seata.modules.mapper.OrderMapper;
import com.company.spring.boot.shardingsphere.seata.modules.service.IOrderService;
import io.seata.core.context.RootContext;
import io.seata.spring.annotation.GlobalTransactional;

@Service
public class OrderServiceImpl extends ServiceImpl<OrderMapper, OrderEntity> implements IOrderService {

    @Override
    public void insertOrder(OrderEntity orderEntity) {
        System.out.println("XID:"+ RootContext.getXID());
        baseMapper.insert(orderEntity);
    }
}
Dubbo consumer Code:
import com.alibaba.dubbo.config.annotation.Reference;
import com.company.spring.boot.shardingsphere.seata.modules.entity.OrderEntity;
import com.company.spring.boot.shardingsphere.seata.modules.service.IBusinessService;
import com.company.spring.boot.shardingsphere.seata.modules.service.IOrderService;
import io.seata.core.context.RootContext;
import io.seata.spring.annotation.GlobalTransactional;
import org.apache.shardingsphere.transaction.annotation.ShardingTransactionType;
import org.apache.shardingsphere.transaction.core.TransactionType;
import org.apache.shardingsphere.transaction.core.TransactionTypeHolder;
import org.springframework.stereotype.Service;

@Service
public class BusinessServiceImpl implements IBusinessService {

    @Reference(check = false,mock = "com.company.spring.boot.shardingsphere.seata.modules.mock.IOrderServiceMock")
    IOrderService orderService;

    @Override
    @GlobalTransactional(name = "dubbo-purchase")
    public void purchase(){
        TransactionTypeHolder.set(TransactionType.BASE);
        OrderEntity orderEntity = new OrderEntity();
        orderEntity.setOrderId(123);
        orderEntity.setStatus("seata");
        orderEntity.setUserId(123);
        orderService.insertOrder(orderEntity);
        System.out.println("XID:"+ RootContext.getXID());
        throw new RuntimeException("回滚测试");
    }
}

@GlobalTransactional 
![image](https://user-images.githubusercontent.com/15086151/63149520-028c6380-c037-11e9-9456-2402ab918e77.png)
GlobalTransactionScanner Class has been delete initClient Function

The query log found that consumer had printed 
![image](https://user-images.githubusercontent.com/15086151/63149281-32873700-c036-11e9-8d73-34feecda6d73.png)

But the provider did not roll back the message

**Comment by cherrylzhao** [comment]
hi，we only support integrate with seata-at using sharding-transaction-base-seata-at, did you have integrated it in your project?

**Comment by huangjian888** [comment]
I have integrated sharding-transaction-base-seata-at in my project，But when I use the Dubbo service,  no roll back. Because sharding-transaction-base-seata-at currently does not support Dubbo？

**Comment by huangjian888** [comment]
> hi，we only support integrate with seata-at using sharding-transaction-base-seata-at, did you have integrated it in your project?
I have integrated sharding-transaction-base-seata-at in my project，But when I use the Dubbo service, no roll back. Because sharding-transaction-base-seata-at currently does not support Dubbo？

**Comment by cherrylzhao** [comment]
sharding-transaction-base-seata only support transaction in  sharding-connection.
it does not support transaction between micro-services.

**Comment by cherrylzhao** [comment]
if you have further question, you can push your example in GitHub to let me reproduce it.

**Comment by huangjian888** [comment]
> if you have further question, you can push your example in GitHub to let me reproduce it.

I have submitted example to GitHub,The link address is 
https://github.com/huangjian888/x-spring-boot-seata

**Comment by huangjian888** [comment]
> sharding-transaction-base-seata only support transaction in sharding-connection.
> it does not support transaction between micro-services.

If I want to use micro-services,such as Dubbo, does sharding-transaction-base-seata need to be adapted?

**Comment by cherrylzhao** [comment]
> > sharding-transaction-base-seata only support transaction in sharding-connection.
> > it does not support transaction between micro-services.
> 
> If I want to use micro-services,such as Dubbo, does sharding-transaction-base-seata need to be adapted?

I think you can use seata directly. you can wrap DataSourceProxy in ShardingDataSource

**Comment by cherrylzhao** [comment]
> > if you have further question, you can push your example in GitHub to let me reproduce it.
> 
> I have submitted example to GitHub,The link address is
> https://github.com/huangjian888/x-spring-boot-seata

thanks, I'd like to check it later today.

**Comment by huangjian888** [comment]
> > > sharding-transaction-base-seata only support transaction in sharding-connection.
> > > it does not support transaction between micro-services.
> > 
> > 
> > If I want to use micro-services,such as Dubbo, does sharding-transaction-base-seata need to be adapted?
> 
> I think you can use seata directly. you can wrap DataSourceProxy in ShardingDataSource.
> sharding-transaction-base-seata don't need to integrated.
Simply understand, do you mean that in micro services, such as Dubbo A service, I need to wrap DataSource Proxy by iterating through SharingDataSource? Sharding-transaction-base-seata-at module is only used to open Seata Global Transaction?

**Comment by huangjian888** [comment]
I override getDataSource in the SpringBootConfiguration configuration in the simplest way, using Seata DataSourceProxy。which is not friendly, but is currently feasible.
![image](https://user-images.githubusercontent.com/15086151/63313778-336ee000-c338-11e9-9586-dc3c26d39146.png)

**Comment by cherrylzhao** [comment]
sorry for late response, I'm very busy recently.
I mean you should config DataSourceProxy instead of DruidDataSource in ShardingSphere.
ShardingDataSource works on sharding and DataSourceProxy works on seata-transaction.
in fact, we haven't verify it in this way, you may face on some problems during integration.

**Comment by cherrylzhao** [comment]
have you resolve your problem yet?

**Comment by huangjian888** [comment]
> have you resolve your problem yet?
Yes, I override getDataSource in the SpringBootConfiguration configuration，No problems were found after testing.
Thank you for your reply！

**Comment by cherrylzhao** [comment]
ok, have a good day~

**Comment by cherrylzhao** [comment]
enhanced it #4991, you can use original ShardingDataSource to integrate with Seata in micro-service transaction now
