### ISSUE TITLE
4.0.0-RC1-sharding-proxy-bin bolb  write Error

### ISSUE THREAD

**Issue by xriqyu** [apache/incubator-shardingsphere#2885]
springboot+mybatis+ starter-jdbc
mysqlDB is ok，use proxy error.
byte[] armyInfo =[1,0,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,113,117,101,115,-12,49,48,46,48,46,52,46,49,-75,75,74,65,104,115,100,97,107,100,104,97,115,107,-28,115,101,116,68,97,116,-31,1,1,91,76,106,97,118,97,46,108,97,110,103,46,79,98,106,101,99,116,-69,6,9,-64,-39,-86,20,3,115,100,104,98,115,97,104,100,98,115,-31,1,2,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,115,112,111,110,115,-27,0,0,0,1,3,108,115,46,115,101,114,118,101,114,46,119,111,114,108,100,46,109,111,100,101,108,46,87,111,114,108,100,77,97,114,99,-24,-128,0,0,-128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-128,0,-128,-128,-128,0,-128,0,0,0,0,0,0,0,0,0,0,-128,0,0,0,0,0,-128,10,66,61,-8,-5,108,25,0,0,3,2,0,3,0,0]

java:
 private byte[] armyInfo;

mybatis mapper useType 
result column="armyInfo" property="armyInfo" jdbcType="LONGVARBINARY"

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\0com.ls.rpc.server.RpcReques?10.0.4.1?KJAhsdakdhask?setDat?[Ljava.lang.Objec' at line 2
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\0com.ls.rpc.server.RpcReques?10.0.4.1?KJAhsdakdhask?setDat?[Ljava.lang.Objec' at line 2

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy64.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy80.insert(Unknown Source)
	at ls.server.world.lsserverworld.LsWorldServerApplicationTests.testBlobByShardProxy(LsWorldServerApplicationTests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

**Comment by xriqyu** [comment]
why?
sql end is two ))

logicSQL=insert into world_march
        (
        uuid,serverId, ownerUid, ownerId,
        ownerName, allianceId, teamId,
        parentUuid, armyInfo,
        type, targetId, targetType,
        targetUid, marchStartTime, marchTime, marchArrivalTime,
        arrivalTime, exploreTime, collectSpd, resLevel, plunderRes, state, blackLandMarchTime,
        monsterArmyCount, monsterLevel, monsterInfo, hasLeader, discoveryInfo, resLoad, speedUpTimes, speedUpLimit,extraParam,playerType
        )
        values
        (
        '5dd16ff3-82a6-47d8-83f3-3f8af1bf5604',1, null, 0,
        null, null, null,
        null, _binary'\0com.ls.rpc.server.RpcReques�10.0.4.1�KJAhsdakdhask�setDat�[Ljava.lang.Object�	�٪sdhbsahdbs�com.ls.rpc.server.RpcRespons�\0\0\0ls.server.world.model.WorldMarc�\0\0�\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0�\0���\0�\0\0\0\0\0\0\0\0\0\0�\0\0\0\0\0�
B=��l\0\0\0\0\0',
        0, 0, 0,
        0, 0,0,
        0,
        0, 0, '0.0',
        0, null, 0, null,
        0, 0, null,
        0, 0, 0,
        0, 0, 0,
        0
        )), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[uuid, serverId, ownerUid, ownerId, ownerName, allianceId, teamId, parentUuid, armyInfo, type, targetId, targetType, targetUid, marchStartTime, marchTime, marchArrivalTime, arrivalTime, exploreTime, collectSpd, resLevel, plunderRes, state, blackLandMarchTime, monsterArmyCount, monsterLevel, monsterInfo, hasLeader, discoveryInfo, resLoad, speedUpTimes, speedUpLimit, extraParam, playerType], values=[InsertValue(columnValues=[org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@72acd894, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@aa4cd30, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@3c7ec526, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@6d676dbc, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@791b60fc, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@557affa2, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@1fe757de, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@493bc313, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@6b055648, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@69003365, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@4cfcd03c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5b48a1eb, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@1abe1bdc, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@72cd88f5, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@581acba0, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@46c36eb1, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@2cc9fd4e, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@325d5202, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@3c14d822, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@61ff8ff7, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@2bf2d0b, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5aaaa21c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@40e5a4a3, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5df81b7f, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@26d4a2be, org.apache.shardingsphere.core.parse.old.parser.expression.SQLTextExpression@29e15e3a, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@444c3719, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5972ef0c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5a3067ce, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@7983f23c, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@5cd2e6ea, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@129668f3, org.apache.shardingsphere.core.parse.old.parser.expression.SQLNumberExpression@4b417378])])

**Comment by xriqyu** [comment]
sharding-proxy 居然是号称面向DBA 真的是 把DBA 气死再气活
一个blob字段都处理不好

经过各种尝试，我这里提供一种编码方式可以绕过此bug
第一步
把db 表的字段改成text
armyInfo	text	

第二部 java 使用 base64 转一下就好
代码大致写一下
public String getInfo() {
        if(armyInfo!=null){
           return java.util.Base64.getEncoder().encodeToString(info);
        }
        return null;
    }

    public void setData(String info) {
        if(StringUtils.isNotBlank(info)){
            this.armyInfo = java.util.Base64.getDecoder().decode(armyInfo);
        }
    }

 public void setInfoData(byte[] data){
    this.info = data;
}
public byte[] getnfoData(byte[] data){
   return  this.info ;
}

测试代码
 byte[] oriData = {
                1,0,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,113,117,101,115,-12,49,48,46,48,46,52,46,49,-75,75,74,65,104,115,100,97,107,100,104,97,115,107,-28,115,101,116,68,97,116,-31,1,1,91,76,106,97,118,97,46,108,97,110,103,46,79,98,106,101,99,116,-69,6,9,-64,-39,-86,20,3,115,100,104,98,115,97,104,100,98,115,-31,1,2,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,115,112,111,110,115,-27,0,0,0,1,3,108,115,46,115,101,114,118,101,114,46,119,111,114,108,100,46,109,111,100,101,108,46,87,111,114,108,100,77,97,114,99,-24,-128,-128,0,-128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-128,0,-128,-128,-128,0,-128,0,0,0,0,0,0,0,0,0,0,-128,0,0,0,0,0,-128,10,66,61,-8,-5,108,25,0,0,3,2,0,3,0,0
        };
march.setInfoData(oriData);
mapper.insert(march);
byte[] dbReadArray  = mapper.selectBykey(march.getUUid()).getInfoData();
System.out.println("equals result : "+Arrays.equals(oriArray,dbReadArray));

运行结果
equals result : true

希望能帮助同样被坑到的朋友
如果实在忍不了这种多余性能消耗 考虑换其他的代理

**Comment by tuohai666** [comment]
This problem had been fixed in 4.0.0-RC2-SNAPSHOT. You can build the project in dev branch and have a try.
Please refer to https://github.com/apache/incubator-shardingsphere/issues/1567 and https://github.com/apache/incubator-shardingsphere/issues/1910 for reference.

**Comment by xriqyu** [comment]
Thanks.
