### ISSUE TITLE
Missing data source name: 'Master0' / 'Master-0'

### ISSUE THREAD

**Issue by hyochan-Kim** [apache/incubator-shardingsphere#2887]
### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
insert successfully

### Actual behavior
my datasources' name are master0/master1/...
when i insert queries,(not only one / only one is OK)
it make error - Missing the data source name: 'master-0' (or master-1 ...)

so change datasources' name to master-0/master-1/...
it make error - Missing the data source name: 'master0' (or master1 ...)

so i make datasources' name master0/master-0 (<- they are same url,type ...)
/master1/master-1 .... 
it makes no error. and work done.
i don't know exact reason.
i guess it has datasource name parsing error.

sorry my english.

**Comment by terrymanu** [comment]
Can you try example and make sure example is correct first?
And then you may check the diff from example and your change.

**Comment by terrymanu** [comment]
Will close soon if no response any more
