### ISSUE TITLE
When is the RC2 docker image available? Where can I find the dockerfile?

### ISSUE THREAD

**Issue by ningyu1** [apache/incubator-shardingsphere#2889]
## Question

When is the RC2 docker image available?

RC1 docker image has many problems
1. Cannot be overwritten with -e JVM parameters
2. Character encoding is not UTF-8

Where can I find the dockerfile? Let me build the image myself for testing

**Comment by terrymanu** [comment]
4.0.0-RC2 is not released yet, FYI: https://github.com/apache/incubator-shardingsphere/releases

**Comment by ningyu1** [comment]
@terrymanu 
Where can I find the dockerfile?  Let me build the image myself for testing
或者我在哪里能看到dockerfile，让我可以自己本机打一个镜像进行测试。
