### ISSUE TITLE
RC1 proxy docker image, Chinese garbled

### ISSUE THREAD

**Issue by ningyu1** [apache/incubator-shardingsphere#2890]
## Bug Report

environment： hub.docker sharding-proxy:4.0.0-RC1

## problem

Query result Chinese garbled. log print sql normal.
Real database encoding: UTF8MB4.
Real database executes insert, select, and the result character is correct. Garbled after proxy.

## Screen
![image](https://user-images.githubusercontent.com/3387548/63243185-5fcd2280-c28c-11e9-9b37-4ddba33510b8.png)
![image](https://user-images.githubusercontent.com/3387548/63243197-665b9a00-c28c-11e9-973d-b1b5fed2919e.png)
![image](https://user-images.githubusercontent.com/3387548/63243224-812e0e80-c28c-11e9-9105-69071fcd5647.png)

**Comment by tuohai666** [comment]
Can you show me the mysqld configuration?

What if you execute these SQLs directly to MySQL?

**Comment by ningyu1** [comment]
@tuohai666 
>What if you execute these SQLs directly to MySQL? 
yes

mvn clean install -Prelease -> build RC2 windows testing ,The same problem

**Comment by ningyu1** [comment]
![image](https://user-images.githubusercontent.com/3387548/63249919-0de0c880-c29d-11e9-8c26-b7696f2ab279.png)

**Comment by tuohai666** [comment]
I mean what will happen if you execute these SQLs directly to MySQL?

**Comment by tuohai666** [comment]
If these SQLs are executed correctly, please add these parameters in jdbcurl of Sharding-Proxy's conf file:
useUnicode=true&characterEncoding=UTF-8&character_set_server=utf8mb4

**Comment by ningyu1** [comment]
@tuohai666 tks
The problem is the problem with the mysql service character set
RC2 has been tested and passed
RC1 test it later

**Comment by tuohai666** [comment]
Right. At first I doubt the mysql service conf.
More information about the character set please refer to: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html.

**Comment by ningyu1** [comment]
@tuohai666  thanks.
this 'issue' I closed
