### ISSUE TITLE
When use mybatis recent version how to use executeQuery()

### ISSUE THREAD

**Issue by yunzhongshu** [apache/incubator-shardingsphere#2891]
## Question
When using mybatis3.4.x for query. It will invoke PreparedStatementHandler.query, it's code is :
```
  public <E> List<E> query(Statement statement, ResultHandler resultHandler) throws SQLException {
    PreparedStatement ps = (PreparedStatement) statement;
    ps.execute();
    return resultSetHandler.<E> handleResultSets(ps);
  }
``` 
It will invoke the PreparedStatement.execute() not the PreparedStatement.executeQuery(), so it can't invoke the ShardingPrepareStatement.executeQuery() too.
So How Can i invoke的executeQuery() when use Mybatis?

Thanks a lot!

**Comment by terrymanu** [comment]
ShardingSphere is faced on JDBC layer, it doesn't care about ORM.
Do you find some error during your program?
Can you provide error message?

**Comment by yunzhongshu** [comment]
No error,  execute() don't merge the result,  but it processLimit before (When limit=10, offset=100, it will set the limit=0, offset=110), last the execute() will return the page result of 0 to 110, not 10 offset 100.

**Comment by terrymanu** [comment]
There is no relationship with mybatis and its version.
Can you try example first and make example is correct, and compare what is the diff with your code?

**Comment by yunzhongshu** [comment]
Yes, I have tried.
When I use sql :  ...  limit #{offset},#{limit}, it will replace the rowCount and offset, the code in the Limit.java:
```
    private void rewrite(final List<Object> parameters, final boolean isFetchAll, final DatabaseType databaseType) {
        int rewriteOffset = 0;
        int rewriteRowCount;
        if (isFetchAll) {
            rewriteRowCount = Integer.MAX_VALUE;
        } else if (isNeedRewriteRowCount(databaseType)) {
            rewriteRowCount = null == rowCount ? -1 : getOffsetValue() + rowCount.getValue();
        } else {
            rewriteRowCount = rowCount.getValue();
        }
        if (null != offset && offset.getIndex() > -1) {
            parameters.set(offset.getIndex(), rewriteOffset);
        }
        if (null != rowCount && rowCount.getIndex() > -1) {
            parameters.set(rowCount.getIndex(), rewriteRowCount);
        }
    }
```

**Comment by yunzhongshu** [comment]
supplement: sharding version is 3.1.0

**Comment by tuohai666** [comment]
Duplicate with #2062 #1759 #1722 #1672 #1643
