### ISSUE TITLE
4.0.0-RC1-sharding-proxy-bin  insert Column null  bug

### ISSUE THREAD

**Issue by xriqyu** [apache/incubator-shardingsphere#2893]
write null,but proxy write 'null' String to db;

private String pointItem = null;
change to
private String pointItem = 'null';

proxyLog 

[INFO ] 18:29:41.404 [ShardingSphere-Command-7] ShardingSphere-SQL - Logic SQL: INSERT INTO point
        VALUES
          
            (765041,
            800,
            3,
            637,
            2,
            0,
            0,
            null,
            11,
            13,
            32,
            0,
            0,
            null,
            0,
            0,
            0,
            0
            )
         , 
            (766242,
            800,
            3,
            638,
            2,
            0,
            0,
            null,
            11,
            13,
            32,
            0,
            0,
            null,
            0,
            0,
            0,
            0
            )

 ShardingSphere-SQL - Actual SQL: world_0 ::: INSERT INTO point  VALUES (72061, 800, 0, 60, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (73262, 800, 0, 61, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (74463, 800, 0, 62, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (75664, 800, 0, 63, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (76865, 800, 0, 64, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (78066, 800, 0, 65, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (79267, 800, 0, 66, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (80468, 800, 0, 67, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (81669, 800, 0, 68, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (82870, 800, 0, 69, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (84071, 800, 0, 70, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (85272, 800, 0, 71, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (86473, 800, 0, 72, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (87674, 800, 0, 73, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (88875, 800, 0, 74, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (90076, 800, 0, 75, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (91277, 800, 0, 76, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (92478, 800, 0, 77, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (93679, 800, 0, 78, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0), (94880, 800, 0, 79, 2, 0, 0, 'null', 2, 2, 4, 0, 0, 'null', 0, 0, 0, 0)

**Comment by tuohai666** [comment]
Duplicate with #2622 and #2538.
