### ISSUE TITLE
SS 3.1.0 single db sharding table throw [Table 'db.table' doesn't exist]

### ISSUE THREAD

**Issue by mrathena** [apache/incubator-shardingsphere#2894]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere-3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
route to correct table
### Actual behavior
throw table doesn't exist exception
### Reason analyze (If you can)
concurrent problem
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Single database sharding two tables
2. Creating a concurrent sharding table sql execution environment when the first SQL is executed after app runs
### Example codes for reproduce this issue (such as a github link).
https://github.com/mrathena/sharding-sphere

**Comment by KomachiSion** [comment]
The problem has been fixed by refactor parseEngine.
Please update version upper 4.0.0-RC1

**Comment by mrathena** [comment]
Get, thank you
