### ISSUE TITLE
the dev branch compile not pass

### ISSUE THREAD

**Issue by jsbxyyx** [apache/incubator-shardingsphere#2895]
## Question

I clone shardingsphere from github, branch is dev, execute mvn clean install.
appears follows error

![image](https://user-images.githubusercontent.com/26616196/63310970-3ca77f00-c32f-11e9-9159-3ac02b3190a0.png)

I not found 3181 port on my os started.
![image](https://user-images.githubusercontent.com/26616196/63311630-4cc05e00-c331-11e9-8161-0ca402fb3475.png)

os: ubuntu
jdk: 1.8

**Comment by terrymanu** [comment]
We have ci to compile every commit.
FYI: https://travis-ci.org/apache/incubator-shardingsphere
