### ISSUE TITLE
字段值为空时，分布式主键id赋值错误

### ISSUE THREAD

**Issue by 1071746754** [apache/incubator-shardingsphere#2896]
现象：
4.0.0-RC1版本，当我插入的数据中，有一个字段是null的时候，自动生成的主键id赋值到了其他字段。例如我要插入INSERT INTO user (name, remark, age)  VALUES ("test", null, 18),经过sharding处理之后变成了INSERT INTO user (name, remark, age, id)  VALUES ("test", 18, "自动生成的主键id", null)

分析：
InsertOptimizeResultUnit类中的getCurrentIndex方法有问题，当获取当前index下标的时候判断有问题。这里感觉不需要在重新计算一次当前下表了，根据前面的字段数量即可知道当前下标量了

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
