### ISSUE TITLE
Distributed primary key ID assignment error when field value is empty

### ISSUE THREAD

**Issue by 1071746754** [apache/incubator-shardingsphere#2897]
Phenomena:

In version 4.0.0-RC1, when one field in the data I inserted was null, the automatically generated primary key ID was assigned to other fields. For example, I want to insert INSERT INTO user (name, remark, age) VALUES ("test", "null, 18"), after sharding, it becomes INSERT INTO user (name, remark, age, id) VALUES ("test", "18", "automatically generated primary key id", null)

Analysis:

The **getCurrentIndex** method in the **InsertOptimizeResultUnit** class has problems, and judgment is problematic when obtaining the current index subscript. There is no need to recalculate the current table below. The current scale is known by the number of fields in front of it.

**Comment by tristaZero** [comment]
Hi, thanks for your issue, we have fixed this bug in our 4.0.0.RC2 which will be released recently. This issue is dulplicated with [this one](https://github.com/apache/incubator-shardingsphere/issues/2252).

**Comment by 1071746754** [comment]
ok,Thank you for your reply
