### ISSUE TITLE
Can you deploy 4.0.0-RC2 to 'mvnrepository.com',  I cannot import this version in my project @terrymanu

### ISSUE THREAD

**Issue by RSDS** [apache/incubator-shardingsphere#2899]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
No, they are not released yet
