### ISSUE TITLE
How about performance and usage of sharding-proxy when it comes to mysql cluster and cloud mysql service

### ISSUE THREAD

**Issue by Moriadry** [apache/incubator-shardingsphere#2901]
## Question

I am wondering how to use sharding-proxy as the entrance  proxy of my mysql-cluster, which is started by tencent cloud. If I open a new port, and execute sql statement through this new port,  will it  cover my business logic?  Will it reduce the performance of my service?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Can you change title to make it to more search friendly?

**Comment by Moriadry** [comment]
@terrymanu  yes, sure. Could you please give some advice? Many thanks!

**Comment by terrymanu** [comment]
Hello, there are 2 questions need to be answered:

1. How to use Sharding-Proxy to control your MySQL-cluster?

Sharding-Proxy is just like a normal MySQL, it implement MySQL protocol, end-user do not need separate Sharding-Proxy and MySQL. End-user just use port which Sharding-Proxy exposed to execute SQL, Sharding-Proxy will sent to SQL to correct backend MySQL instances.

2. How about the performance?

We are doing a task which is show the performance test with Sharding-Proxy and connection MySQL directly. The task will finish in few week. Please keep focus on this task, we will update new information in future.

**Comment by Moriadry** [comment]
@terrymanu That is just so fantastic! Thank you very much terry.

So I just need start one Sharding-Proxy `Bootstrap` server, with correct port and other configuration, then everything will be ready. Is that true?
