### ISSUE TITLE
When shardingjdbc is integrated with spring, it‘s not compatible with the declarative transactions.

### ISSUE THREAD

**Issue by liuyangming** [apache/incubator-shardingsphere#2902]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
In the scenario of declarative transaction, when the service throws a RuntimeException, the transaction should be rolled back.

### Actual behavior
In fact, the transaction was committed.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Please refer to the description of README.md in this project: [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902)

### Example codes for reproduce this issue (such as a github link).
[https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902)

**Comment by cherrylzhao** [comment]
I have reviewed your demo, I think you should forget JTA configuration in sharding-transaciton.
sharding transaction can simply integrate within spring DataSourceTransactionManager.
we have developed a experimental spring starter before, you can refer it in [sharding-transaction-spring](https://github.com/OpenSharding/shardingsphere-spi-impl/tree/master/sharding-spring), and [here](https://github.com/OpenSharding/shardingsphere-spi-impl-example/tree/master/transaction-example/transaction-2pc-xa-example) is example 

hope this will help you.

**Comment by liuyangming** [comment]
> I have reviewed your demo, I think you should forget JTA configuration in sharding-transaciton.
> sharding transaction can simply integrate with spring DataSourceTransactionManager.
> we have developed a experimental spring starter before, you can refer it in [sharding-transaction-spring](https://github.com/OpenSharding/shardingsphere-spi-impl/tree/master/sharding-spring), and [here](https://github.com/OpenSharding/shardingsphere-spi-impl-example/tree/master/transaction-example/transaction-2pc-xa-example) is example
> 
> hope this will help you.

The [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) does not use the JTA configuration. The GenericConfiguration(the class with JTA configuration) is not added the @Configuration annotation, and is not imported by ShardingJdbcSampleBootstrap(the main class). In fact, it does not take effect in the default scenario(only ShardingConfiguration is effect), you can ignore it. The [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) keep it just to do a comparison with a standard xa-data-source when needed.

**Comment by liuyangming** [comment]
> > I have reviewed your demo, I think you should forget JTA configuration in sharding-transaciton.
> > sharding transaction can simply integrate with spring DataSourceTransactionManager.
> > we have developed a experimental spring starter before, you can refer it in [sharding-transaction-spring](https://github.com/OpenSharding/shardingsphere-spi-impl/tree/master/sharding-spring), and [here](https://github.com/OpenSharding/shardingsphere-spi-impl-example/tree/master/transaction-example/transaction-2pc-xa-example) is example
> > hope this will help you.
> 
> The [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) does not use the JTA configuration. The GenericConfiguration(the class with JTA configuration) is not added the @configuration annotation, and is not imported by ShardingJdbcSampleBootstrap(the main class). In fact, it does not take effect in the default scenario(only ShardingConfiguration is effect), you can ignore it. The [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) keep it just to do a comparison with a standard xa-data-source when needed.

In fact, the [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) is written with reference to [transaction-sample](https://github.com/apache/incubator-shardingsphere-example). The only difference between them is that it didn't add the @ShardingTransactionType(TransactionType.XA) annotation in the service, and even if this annotation is added, it is also incompatible with the declarative transaction.

**Comment by liuyangming** [comment]
Well, in order to make this sample( [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902) ) looks simple, I have deleted all the classes that are not related to shardingjdbc, and at your request, the transaction manager is also explicitly changed to DataSourceTransactionManager, but it is still not compatible with the declaration Transaction.

**Comment by cherrylzhao** [comment]
OK, let me check it again.

**Comment by cherrylzhao** [comment]
I have got some hints from your example.

1. `@Transactional` annotation only hold the connection managed by `DataSourceTransactionMananger`, it will not see the connection created from your biz code. so after completing `doCreateOrder`, the connection has been auto committed.
 
2. `@ShardingTransactionType` only take effect when your include `sharding-transaction-jdbc-spring` dependency in your project. since we have not deploy it in maven center repository, you should install the `shardingsphere-spi-impl` by yourself. 

3. in your example, transaction type is Local instead of XA, so transaction manager will not execute rollback.

**Comment by cherrylzhao** [comment]
and you can use `DataSourceUtils.getConnection(shardingDataSource)` in your biz code to get the connection managed by @Transactional, I have tested it.

**Comment by liuyangming** [comment]
> and you can use `DataSourceUtils.getConnection(shardingDataSource)` in your biz code to get the connection managed by @transactional, I have tested it.

I have added the sharding-transaction-jdbc-spring dependency and solved the problem after getting the connection through DataSourceUtils.getConnection(DataSource). However, I still think that the operation of getting the connection through DataSourceUtils should be encapsulated by shardingjdbc instead of the business system. Of course, this is my personal opinion and is for reference only.

Another problem is that the support for transaction propagation level REQUIREDS_NEW of declarative transactions is still incorrect. I have updated to the [shardingjdbc-sample](https://github.com/liuyangming/shardingjdbc-sample/tree/issue-2902), the latest code can reproduce this problem. The DataSourceTransactionManager has no problem with the begin & commit/rollback control of the transaction. However, the completion of the two transactions involved is confusing.

**Comment by cherrylzhao** [comment]
it's just my advice for your example code to use `DataSourceUtils.getConnection`. in fact, mybatis-spring, or jpa will invoke this method in their framework, biz code will not consider about it.

**Comment by cherrylzhao** [comment]
about REQUIRED_NEW of XA, we have discussed in #2854, it can't be supported now.
enlisted resources was hold in threadLocal, it seems we should hold it in a Map(key was transaction), you can try to push a PR for it.

**Comment by cherrylzhao** [comment]
also If you have some ideas of spring-sharding-transaction, we can optimize it together.

**Comment by liuyangming** [comment]
> it's just my advice for your example code to use `DataSourceUtils.getConnection`. in fact, mybatis-spring, or jpa will invoke this method in their framework, biz code will not consider about it.

Relative to shardingjdbc, the mybatis-spring and jpa are upper-level frameworks. It is not very suitable for shardingjdbc to rely on them. Furthermore, there are some business systems that use the raw DataSources directly, and shardingjdbc should also support them. 

Again, this is just my personal opinion, think about it, if you want.

**Comment by liuyangming** [comment]
> about REQUIRED_NEW of XA, we have discussed in #2854, it can't be supported now.
> enlisted resources was hold in threadLocal, it seems we should hold it in a Map(key was transaction), you can try to push a PR for it.

I will consider trying to fix this problem.

**Comment by liuyangming** [comment]
> also If you have some ideas of spring-sharding-transaction, we can optimize it together.

I do have some ideas, and I have great expectations for it. shardingjdbc is an excellent open source project, my company is currently considering it, of course, I hope that it can be more standardized.

**Comment by cherrylzhao** [comment]
look forward to your contribution！

**Comment by cherrylzhao** [comment]
just close this issue for no response for a long time.
we consider about creating another issue for refactor swarding-transaction module

**Comment by cherrylzhao** [comment]
fixed it at #3552
