### ISSUE TITLE
ComplexCustomAlgorithm will load every single row by id 

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2903]
```
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
</dependency>
```
I am using complex colums slice to my single db multiple tables. But I found that every time I findAll data with jpa and update them, sharding will query every row data which in this data again to all 
slice tables, then do update. I do not quite understand if I make a mistake. please reply ,thanks/.

**Comment by KomachiSion** [comment]
Please provide your full sharding configuration and SQLs. If possible, provide example code which can reproduce your problem will be better.

**Comment by DongJigong** [comment]
> Please provide your full sharding configuration and SQLs. If possible, provide example code which can reproduce your problem will be better.

https://github.com/DongJigong/shardingsphere-issues-issue2865/tree/master/issue2903

**Comment by KomachiSion** [comment]
@DongJigong ,  your question is not problem caused by ShardingSphere.
JPA will do query before persisting, if the entity has existed, the entity will not persist and return directly.

you can try to use original JDBC. it also query your table before update.

If you ask why the query will route to all actual node, the reason is the query generated by JPA without sharding column, it will cause full-routing.

**Comment by DongJigong** [comment]
> @DongJigong , your question is not problem caused by ShardingSphere.
> JPA will do query before persisting, if the entity has existed, the entity will not persist and return directly.
> 
> you can try to use original JDBC. it also query your table before update.
> 
> If you ask why the query will route to all actual node, the reason is the query generated by JPA without sharding column, it will cause full-routing.

I have got your point. If I use JPA with Hsql, it could avoid a full-routing query?

**Comment by KomachiSion** [comment]
This will be depend on your HSQL, if your HSQL still generate without sharding column, it will do full-routing again.

**Comment by DongJigong** [comment]
> This will depend on your HSQL, if your HSQL still generate without sharding column, it will do full-routing again.
thanks.
