### ISSUE TITLE
 not support “show full tables from `sharding_db` like't_test1'”

### ISSUE THREAD

**Issue by gaodesen163** [apache/incubator-shardingsphere#2904]
sharding proxy version
https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz

(1)
create table tbname1 (id int primary key,key_price decimal(16,2) DEFAULT NULL);

(2)
mysql> show full tables from `sharding_db` like 'tbname1'
no return value
受影响的行: 0
https://user-images.githubusercontent.com/13394604/63440944-48945d80-c463-11e9-9b5a-13b8e492a043.png)

but sharding-proxy-3.1.0.tar.gz It supports this function.

thanks

**Comment by gaodesen163** [comment]
> 分片代理版本
> https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz
> 
> （1）
> 创建表tbname1（id int主键，key_price decimal（16,2）DEFAULT NULL）;
> 
> （2）
> mysql>显示来自`sharding_db`'tbname1'的完整表格
> https://user-images.githubusercontent.com/13394604/63440944-48945d80-c463-11e9-9b5a-13b8e492a043.png）
> 
> 谢谢

**Comment by gaodesen163** [comment]
> 分片代理版本
> https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz
> 
> （1）
> 创建表tbname1（id int主键，key_price decimal（16,2）DEFAULT NULL）;
> 
> （2）
> mysql>显示来自`sharding_db`'tbname1'的完整表格
> https://user-images.githubusercontent.com/13394604/63440944-48945d80-c463-11e9-9b5a-13b8e492a043.png）
> 
> 谢谢

**Comment by gaodesen163** [comment]
This allows you to query all of them. “show full tables from  'tbname1 '”
![image](https://user-images.githubusercontent.com/13394604/63484774-67323d00-c4d3-11e9-8c17-e38a10636d68.png)
It just doesn't support it. ‘like’   
https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz

**Comment by sunbufu** [comment]
I send a [PR](https://github.com/apache/incubator-shardingsphere/pull/2921) for this, can you take a view ?

**Comment by terrymanu** [comment]
Just pending because sharding-jdbc's merge engine cannot support.

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/79186614-bd7e3280-7e4c-11ea-85ca-1cfd033fdd09.png)

It's okay now.
