### ISSUE TITLE
Jpa table model  @Version @PreUpdate columns not work sometimes

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#2905]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
version columns should auto increment, update_time should have a value when doing update
### Actual behavior
all not work

**Comment by terrymanu** [comment]
Can you explain the reason to close issue?

**Comment by DongJigong** [comment]
I suppose that sharding will cache the query result if result column values not change, sharding will not do the update. I think this is not a good way in order to achieve performance losing real business.

**Comment by DongJigong** [comment]
I suppose that sharding will cache the query result if result column values not change, sharding will not do the update. I think this is not a good way in order to achieve performance losing real business.

**Comment by terrymanu** [comment]
I don't think shardingsphere is a all-in-one product.

**Comment by DongJigong** [comment]
> I don't think shardingsphere should be a all-in-one product.
