### ISSUE TITLE
Does the sharding-proxy on version 4.0.0-RC2 support zookeeper dynamic register center ?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2906]
## Question

I wonder if sharding-proxy v4.0.0-RC2 or later version support dynamic register center with zookeeper ? coz i got errors when i config with zookeeper .

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Please show your error info

**Comment by Myshiner** [comment]
Please refer to the error info.
**Exception in thread "main" java.lang.IllegalArgumentException: Type is required.**
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at org.apache.shardingsphere.api.config.TypeBasedSPIConfiguration.<init>(TypeBasedSPIConfiguration.java:43)
        at org.apache.shardingsphere.orchestration.reg.api.RegistryCenterConfiguration.<init>(RegistryCenterConfiguration.java:76)
        at org.apache.shardingsphere.orchestration.yaml.swapper.RegistryCenterConfigurationYamlSwapper.swap(RegistryCenterConfigurationYamlSwapper.java:48)
        at org.apache.shardingsphere.orchestration.yaml.swapper.OrchestrationConfigurationYamlSwapper.swap(OrchestrationConfigurationYamlSwapper.java:46)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:100)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:75)
17:04:32,414 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:04:32,414 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:04:32,414 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/xdfapp/sharding-proxy4.0.0RC1/conf/logback.xml]
17:04:32,415 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
17:04:32,415 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/xdfapp/sharding-proxy4.0.0RC1/lib/sharding-proxy-bootstrap-4.0.0-RC1.jar!/logback.xml]
17:04:32,415 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/xdfapp/sharding-proxy4.0.0RC1/lib/sharding-proxy-distribution-4.0.0-RC1.jar!/logback.xml]
17:04:32,415 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/xdfapp/sharding-proxy4.0.0RC1/conf/logback.xml]
17:04:32,508 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:04:32,522 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:04:32,527 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:04:32,535 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:04:32,564 |-**ERROR in ch.qos.logback.classic.PatternLayout("null") - Empty or null pattern.**
17:04:32,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
17:04:32,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
17:04:32,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
17:04:32,600 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:04:32,605 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
17:04:32,607 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:04:32,607 |-ERROR in ch.qos.logback.classic.PatternLayout("null") - Empty or null pattern.

**Comment by coolos** [comment]
> Please refer to the error info.
> **Exception in thread "main" java.lang.IllegalArgumentException: Type is required.**
.

@Myshiner  I met the same error msg.  May be you could adjust  server.yaml conf file in the "orchestration" section like this:

orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    type: zookeeper
    namespace: orchestration
    serverLists: 127.0.0.1:2181

At least, it made my sharding-proxy started and push data into ZK successfully. 
Hope help you!

**Comment by Myshiner** [comment]
Yup, it works, thx. but one more question, as the official doc said "If there is write operation in the same thread and database connection, all the following read operations are from the master database to ensure data consistency.", but i have tested all the versions v3.0.0 & v3.1.0 & v4.0.0, it didn't work, in the same thread, i try to insert firstly and then get select operation immediately, but it did read-write split. Any suggests ?

**Comment by Myshiner** [comment]
please refer to the following test logs.
In the same thread, firstly I create a table and then insert some datas and then do select query.

2019-08-23 10:30:13.316 [ShardingSphere-Command-0] INFO  ShardingSphere-SQL - SQL: **create table pm(id int unsigned not null auto_increment primary key comment 'ID', gender tinyint(2) not null default 0 comment '0-默认, 1-男, 2-女') engine=innodb default charset=utf8mb4 comment='测试表'** ::: DataSources: neworiental_v3
2019-08-23 10:30:55.103 [ShardingSphere-Command-1] INFO  ShardingSphere-SQL - Rule Type: master-slave
2019-08-23 10:30:55.103 [ShardingSphere-Command-1] INFO  ShardingSphere-SQL - SQL: **insert into pm(gender) values(0),(2),(2),(1)** ::: DataSources: neworiental_v3
2019-08-23 10:31:17.883 [ShardingSphere-Command-2] INFO  ShardingSphere-SQL - Rule Type: master-slave
2019-08-23 10:31:17.884 [ShardingSphere-Command-2] INFO  ShardingSphere-SQL - SQL: **select * from pm where gender=2** ::: DataSources: slave_v3_0

**Note:** neworiental_v3 is master node and slave_v3_0 is slave node.

**Comment by terrymanu** [comment]
This is document issue, reg center's api has changed, but document does not update in time.

**Comment by terrymanu** [comment]
Already created an issue on document repo.

FYI: https://github.com/apache/incubator-shardingsphere-doc/issues/225

**Comment by Myshiner** [comment]
Thx. Any suggestion to the additional question above about "If there is write operation in the same thread and database connection, all the following read operations are from the master database". In my case, the write operation is routed to master database and the following read operations are routed to slave database in the same thread, why ?

And whats more, can i config a read-only user in the authentication center ? just like following.
authentication:
  users:
    root:
      password: root
    reader:    /* read only user */
      password: reader
      authorizedSchemas: sharding_db

**Comment by terrymanu** [comment]
If there are different questions, you may create a new issue

**Comment by terrymanu** [comment]
fixed document by apache/incubator-shardingsphere-doc#225
