### ISSUE TITLE
mysql insert decimal 'null' error

### ISSUE THREAD

**Issue by gaodesen163** [apache/incubator-shardingsphere#2907]
https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC1-sharding-proxy-bin.tar.gz

(1)
create table t_test1(id int primary key,amount decimal(16,2));

(2)
[SQL]insert into t_test1(id,amount) VALUES(1212,null)

[Err] 10002 - 2Unknown exception: [java.sql.SQLException: Incorrect decimal value: 'null' for column 'amount' at row 1]

thanks

**Comment by tuohai666** [comment]
Duplicate with #2622 and #2538.
