### ISSUE TITLE
 Support for visualization of ShardingSphere performance

### ISSUE THREAD

**Issue by nancyzrh** [apache/incubator-shardingsphere#2908]
### Describe the feature you would like.
we want to provide the perfomance data of shardingsphere with different scenarios. To implement this, different performance test scenarios which can be treated as benchmarks will be designed, and then we will submit performance data to jenkins daily, so that performance data can be achieved when shardingsphere is updated. As our design, the performance comparison of mysql, shardingsphere 4.0 and 3.0 will be provided depending on the scenarios as well.

**Comment by tuohai666** [comment]
I think the scenarios should include:

```
Access:
Raw-JDBC
Sharding-JDBC
Sharding-Proxy

Mode:
Single routing
Database routing
Table routing
Full routing
MasterSlave
MasterSlave + Single routing
MasterSlave + Database routing
MasterSlave + Table routing
MasterSlave + Full routing
Encryption
Encryption + Single routing
Encryption + Database routing
Encryption + Table routing
Encryption + Full routing

SQL:
INSERT
UPDATE
SELECT
DELETE
```

Access(3) * Mode(14) * SQL(4) = 168 secnarios

For the 3.x don't support encryption, we can't show the comparison of this part.

Besides, I suggest that we illustrate the performance promotion to user by using ShardingSphere.

```
Access:
Raw-JDBC
Sharding-JDBC
Sharding-Proxy

Mode:
Database routing

SQL:
INSERT
UPDATE
SELECT
DELETE
```

Access(3) * Mode(1) * SQL(4) = 12 secnarios

When the database is under significant stress, horizontally shard data into more databases will improve the performance.

**Comment by terrymanu** [comment]
We can push benchmark data to https://github.com/OpenSharding/shardingsphere-benchmark

**Comment by nancyzrh** [comment]
demo: https://builds.apache.org/job/shardingsphere-perf/shardingsphere_20performance_20report/

**Comment by tuohai666** [comment]
I have created an offical Apache repo https://github.com/apache/incubator-shardingsphere-benchmark 
I suggest push data to this new repo because ShardingSphere is Apache trademark.

**Comment by terrymanu** [comment]
Jenkins only can upload a simple picture which is not enough to display performance.
We may do it in our own website (asf-site), there are some tasks we should do:

Frontend：

1. Display most recently 30 days performance data which is load from github directly (https://github.com/apache/incubator-shardingsphere-benchmark)
2. Display native MySQL, Sharding-JDBC and Sharding-Proxy's performance in same screen.
3. Do not display performance data of 3.x by default, can use a parameter flag to display it.
4. Adjust display details, such as rename calm to normal word and try to reduce text description.
5. Add navigation page for performance test scenario.
6. During data accumulation, consider about display  most recently 90 days and most recently year's sampling display.

Backend：

1. Complete all performance test scenarios.
2. Push performance test data to github (https://github.com/apache/incubator-shardingsphere-benchmark) every day automatically.
3. Tracing performance data and try to analyze performance issue.

**Comment by wqzwh** [comment]
@terrymanu  according to your idea, we will optimize it.

**Comment by wqzwh** [comment]
add ajax gets data，Just update the data to avoid repackaging the build。https://github.com/apache/incubator-shardingsphere-benchmark/pull/4

**Comment by wqzwh** [comment]
add overview page，For better page switching, so I added navigation

![image](https://user-images.githubusercontent.com/16662470/66395493-1c7c6e00-ea0a-11e9-8ea1-a48362b31a0b.png)

https://github.com/apache/incubator-shardingsphere-benchmark/pull/5

**Comment by wqzwh** [comment]
add new scenarios

- [x] shardingjdbc_vs_shardingproxy_encrypt
- [x] shardingjdbc_vs_shardingproxy_sharding_encrypt

https://github.com/apache/incubator-shardingsphere-benchmark/pull/6

**Comment by wqzwh** [comment]
Optimize details:

https://github.com/apache/incubator-shardingsphere-benchmark/pull/7

![image](https://user-images.githubusercontent.com/16662470/66811892-775f1980-ef64-11e9-8bf4-3b5ca8c67d4b.png)

![image](https://user-images.githubusercontent.com/16662470/66811918-82b24500-ef64-11e9-9553-556eab392c8e.png)
