### ISSUE TITLE
Use data source ID and table ID to force routing is required. There is no Value in some situation. 

### ISSUE THREAD

**Issue by wy-coder** [apache/incubator-shardingsphere#2910]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Full table paging sanning is what we need!

### Describe the feature you would like.
In core banking system , there are so many process we called "batch process" which need "Full table paging sanning". 

We need to split the data to segments. like this： 
db01: table01: 0-10000 . App node1 process;
db01: table01: 10001-20000 . App node2 process;
……
db02: table11: 10001-20000 . App node22 process;

so when we split the data and paging ,We need to execute segmented SQL force to a specified database' s table. we have the data source id and table name , but no value.

**Comment by terrymanu** [comment]
Can you change title to make it easier to understand?

**Comment by leehom** [comment]
can you show your set hint code , when using hint sharding, you need to set the hint by HintManager by
yourself

**Comment by wy-coder** [comment]
I just want this SQL to be executed in the data source name (or ID) and table name (or ID) I specify.

HintShardingStrategy does not to be configured.

**Comment by leehom** [comment]
hint sharding must use hint sharind Strategy, just like flowing code:
**conf.setDatabaseShardingStrategyConfig(
	        new HintShardingStrategyConfiguration(hintShardingDatabaseAlgorithm));
conf.setTableShardingStrategyConfig(
	        new HintShardingStrategyConfiguration(hintShardingTableAlgorithm));**
and, hintShardingDatabaseAlgorithm is the implementation of ShardingAlgorithm

StandardShardingStrategyConfiguration is **standard** **sharding** **Strategy**, not hint

**Comment by wy-coder** [comment]
> hint sharding must use hint sharind Strategy, just like flowing code:
> **conf.setDatabaseShardingStrategyConfig( new HintShardingStrategyConfiguration(hintShardingDatabaseAlgorithm)); conf.setTableShardingStrategyConfig( new HintShardingStrategyConfiguration(hintShardingTableAlgorithm));**
> and, hintShardingDatabaseAlgorithm is the implementation of ShardingAlgorithm
> 
> StandardShardingStrategyConfiguration is **standard** **sharding** **Strategy**, not hint

I know. But this table already has one PreciseShardingAlgorithm.
In most cases, this table is used PreciseShardingAlgorithm.
but as the paging case.his table is used Hint sharding Strategy.

I just want this SQL to be executed in the data source name (or ID) and table name (or ID) I specify.
It has nothing to do with the table's sharding strategy.

**Comment by wy-coder** [comment]
Why is forced routing bound with a table's sharding strategy？

This is ridiculous.

```
/** dbname='db01' tablemane='clinet_info05' **/
select  min(xx),max(xx),count(*) from clinet_info where xx=xx group by floor(rownum / 200000)；
```
This is good！

**Comment by wy-coder** [comment]
I calculated the sub-table myself and solved the problem with SQL injection.

**Comment by terrymanu** [comment]
Can you explain how to do SQL injection?

**Comment by terrymanu** [comment]
Closed for no response anymore
