### ISSUE TITLE
 4.0.0-RC2 does not support Oracle 12C connection configuration

### ISSUE THREAD

**Issue by timchan1011** [apache/incubator-shardingsphere#2911]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
When using Oracle 12c, the URL configuration is as follows:
Jdbc: oracle: thin:@127.0.0.1:11521/camp2.xxx.com
ShemaName gets the error value camp2

### Reason analyze (If you can)
The OracleDataSourceMetaData class needs to be modified to support the configuration of oracle12c service name

### Example codes for reproduce this issue (such as a github link).
private final Pattern pattern = Pattern.compile("jdbc:oracle:(thin|oci|kprb):@(//)?([\\w\\-\\.]+):?([0-9]*)[:/]([\\w\\-\\.]+)", Pattern.CASE_INSENSITIVE);

**Comment by terrymanu** [comment]
@timchan1011 Can you submit a pull request?

**Comment by terrymanu** [comment]
@timchan1011  This pr is related with #2949. We can discuss there.

**Comment by timchan1011** [comment]
你好：
    由于之前在github上没提交过代码，很多操作不熟悉，希望多指导下。

    我在本地编译是没问题的


为什么push上去就报错呢？




 




------------------ 原始邮件 ------------------
发件人: "Liang Zhang"<notifications@github.com>;
发送时间: 2019年9月1日(星期天) 下午5:14
收件人: "apache/incubator-shardingsphere"<incubator-shardingsphere@noreply.github.com>;
抄送: "陈悌宇"<147312525@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [apache/incubator-shardingsphere]  4.0.0-RC2 does not supportOracle 12C connection configuration (#2911)




@timchan1011  This pr is related with #2949. We can discuss there.

**Comment by terrymanu** [comment]
For english only @timchan1011

**Comment by terrymanu** [comment]
Expired
