### ISSUE TITLE
"RegistryCenter" interface has many different methonds, shall we split them into two parts?

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#2912]
### There are some lock related methods in "RegistryCenter" interface, these methods are only used by leaf key generator. And other methods are configuration related methods. So maybe we should split these into two parts. For example:
```
public final class CuratorZookeeperRegistryCenter implements RegistryCenter{
}
```
After RegistryCenter is split into two parts: RegistryCenter and LeafLock. Lock related methods will be moved into LeafLock.
```
public final class CuratorZookeeperRegistryCenter implements RegistryCenter,LeafLock{
}
```
```
public interface RegistryCenter extends TypeBasedSPI {
    
    /**
     * Initialize registry center.
     * 
     * @param config registry center configuration
     */
    void init(RegistryCenterConfiguration config);
    
    /**
     * Get data from registry center.
     * 
     * <p>Maybe use cache if existed.</p>
     * 
     * @param key key of data
     * @return value of data
     */
    String get(String key);
    
    /**
     * Get data from registry center directly.
     * 
     * <p>Cannot use cache.</p>
     *
     * @param key key of data
     * @return value of data
     */
    String getDirectly(String key);
    
    /**
     * Judge data is existed or not.
     * 
     * @param key key of data
     * @return data is existed or not
     */
    boolean isExisted(String key);
    
    /**
     * Get node's sub-nodes list.
     *
     * @param key key of data
     * @return sub-nodes name list
     */
    List<String> getChildrenKeys(String key);
    
    /**
     * Persist data.
     * 
     * @param key key of data
     * @param value value of data
     */
    void persist(String key, String value);
    
    /**
     * Update data.
     *
     * @param key key of data
     * @param value value of data
     */
    void update(String key, String value);
    
    /**
     * Persist ephemeral data.
     *
     * @param key key of data
     * @param value value of data
     */
    void persistEphemeral(String key, String value);
    
    /**
     * Watch key or path of the registry.
     *
     * @param key key of data
     * @param dataChangedEventListener data changed event listener
     */
    void watch(String key, DataChangedEventListener dataChangedEventListener);
    
    /**
     * Close.
      */
    void close();
}
```

```
public interface LeafLock extends TypeBasedSPI {

    void initLock(String key);

    boolean tryLock();

    void tryRelease();
}

```

**Comment by terrymanu** [comment]
Split Reg center to config center and orchestration center is a good idea. We can talk about more details to how to split them

**Comment by terrymanu** [comment]
We can define 2 interface for config center and orchestration center, the example code `LeafLock ` may a interface of orchestration center.
Some reg center like zookeeper, they can implement both interface of config center and orchestration center, but some 3rd party lib may implement one of interface, such as config center

**Comment by wgy8283335** [comment]
And another concern is that if zookeeper implements two interfaces, which type should be used to declare a variable. 
LeafSnowflakeKeyGenerator Class has the attribute `RegistryCenter leafRegistryCenter`. But after RegistryCenter split into two interfaces, which type should be used to declare `leafRegistryCenter`. As config center related methods and orchestration related methods are needed by leafRegistryCenter.
So, do we need a third interface to extend the config center and the orchestration center?

**Comment by wgy8283335** [comment]
@terrymanu

**Comment by terrymanu** [comment]
Maybe is not `leafRegistryCenter`, it just `RegistryCenter`, we can use it for orchestration, `ConfigCenter` just for config.
I am not sure we need type or not, maybe use the interface's type is fine for config and orchestration situations.
We do not need a third interface to extend `configCenter` and the `regCenter`, they are totally split, but zookeeper just implements both.
