### ISSUE TITLE
The write operation is routed to master database and the following read operations are routed to slave database in the same thread

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2914]
Version: sharding-proxy 4.0.0-RC1 and 3.1.0
 The official document said  that if there is write operation in the same thread and database connection, all the following read operations are from the master database. In my case, the write operation is routed to master database and the following read operations are routed to slave database in the same thread, Any suggestions ?
I am sure i did follow the offical document configuration and here is the configure code.
-------------------------------------
schemaName: neworiental_v3
dataSources:
  neworiental_v3:
    url: jdbc:mysql://192.168.10.11:3406/neworiental_v3?serverTimezone=UTC&useSSL=false
    username: writer
    password: 1a2s3dQWE~
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave_v3_0:
    url: jdbc:mysql://192.168.10.11:4406/neworiental_v3?serverTimezone=UTC&useSSL=false
    username: reader
    password: 1a2s3dQWE~
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
masterSlaveRule:
  name: ms_v3
  masterDataSourceName: neworiental_v3
  slaveDataSourceNames:
    - slave_v3_0

**Comment by Myshiner** [comment]
Any suggestions ?

**Comment by cherrylzhao** [comment]
I have reviewed the source, this is only supported by sharding-jdbc.
for sharding-proxy, you can try make transaction_type=XA, it seems this feature will be supported from source.

**Comment by Myshiner** [comment]
Thx for ur reply, i put this issue coz it didn't distinguish in the official doc between sharding-jdbc and sharding-proxy. Anyway i will close the ticket, and i will take your advise to test by setting XA type in proxy. Thanks !

**Comment by terrymanu** [comment]
This issue is not resolve, why close it?

**Comment by cherrylzhao** [comment]
we have supported hint in proxy. #2979, this issue also can be resolved by configuration `proxy.hint.enabled: true` in server.yaml

**Comment by Myshiner** [comment]
In version 4.0.0-RC2 ?Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [apache/incubator-shardingsphere] The write operation is routed to master database and the following read operations are routed to slave database in the same thread (#2914)From: zhaojun To: apache/incubator-shardingsphere CC: Myshiner ,State change we have supported hint in proxy. #2979, this issue also can be resolved by configuration proxy.hint.enabled: true in server.yaml

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-shardingsphere/issues/2914?email_source=notifications\u0026email_token=ALQCBEKX5LR46SUE3ZN2GVDQLA3HHA5CNFSM4IO4TJZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JXFOA#issuecomment-533951160",
"url": "https://github.com/apache/incubator-shardingsphere/issues/2914?email_source=notifications\u0026email_token=ALQCBEKX5LR46SUE3ZN2GVDQLA3HHA5CNFSM4IO4TJZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JXFOA#issuecomment-533951160",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Myshiner** [comment]
In sharding-proxy v4.0.0-RC2 now i have changed the server.yaml with "proxy.hint.enabled: true", but it didn't work. please see the following configure for your reference.
![image](https://user-images.githubusercontent.com/48242833/65576556-cab4fc00-dfa4-11e9-84f5-77bfb0bc1e9f.png)
![image](https://user-images.githubusercontent.com/48242833/65576583-ddc7cc00-dfa4-11e9-88f3-ded574b5ec7b.png)
![image](https://user-images.githubusercontent.com/48242833/65576653-f33cf600-dfa4-11e9-9a5f-6d2d854a9dc7.png)
