### ISSUE TITLE
sharding-proxy mysql  varchar can not complete display

### ISSUE THREAD

**Issue by wangzhengxi** [apache/incubator-shardingsphere#2915]
![image](https://user-images.githubusercontent.com/8328270/63583895-72b65e80-c5ce-11e9-96c7-647b4773c068.png)
![image](https://user-images.githubusercontent.com/8328270/63583910-7ba73000-c5ce-11e9-803b-a43d5ac1ec2b.png)
![image](https://user-images.githubusercontent.com/8328270/63583956-94174a80-c5ce-11e9-833d-607d279a12a0.png)
![image](https://user-images.githubusercontent.com/8328270/63584016-b741fa00-c5ce-11e9-855a-521f507c055b.png)
mysql varchar(30)  

with shrading proxy ,this `waybill_no` varchar(30)   field  can not complete display

**Comment by fireflyhoo** [comment]
Please provide a version of sharding-proxy ,It would be nice if you could provide configuration and table structure statements for the test

**Comment by terrymanu** [comment]
@wangzhengxi Any new for this issue? do you test it again?

**Comment by wangzhengxi** [comment]
shardingRule:
  tables:
    ops_pick_task:
      actualDataNodes: yl-ops-0${1..9}.ops_pick_task_${0..31},yl-ops-1${0..2}.ops_pick_task_${0..31}
      databaseStrategy:
        standard:
          shardingColumn: order_id
          preciseAlgorithmClassName: com.yl.sharding.spi.MyPreciseShardingAlgorithm
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: ops_pick_task_$->{Math.abs(order_id.hashCode()) % 32}

**Comment by wangzhengxi** [comment]
sharding-proxy4.0.0-RC1

**Comment by wangzhengxi** [comment]
i find the answer。when  use navicat 11.1.13 Enterprise Edition，some field can not complete display。but when i use navicat 12.0.29 Enterprise Edition, it complete display .

**Comment by wangzhengxi** [comment]
the existing application's compatibility also needs to be handled

**Comment by terrymanu** [comment]
> i find the answer。when use navicat 11.1.13 Enterprise Edition，some field can not complete display。but when i use navicat 12.0.29 Enterprise Edition, it complete display .

Is it a navicat's issue?

**Comment by terrymanu** [comment]
Closed for no response any more, please create a new issue if it still existed.
