### ISSUE TITLE
why InsertValue rewrite the parameters?

### ISSUE THREAD

**Issue by yogaling** [apache/incubator-shardingsphere#2916]
## Question
the method InsertValue.getParameters use parametersCount to subList the parameters。but when counting the paramCount just accept ParameterMarkerExpressionSegment. so that when my insert sql has parameters like ifnull(?,1)  , the value of paramCount is uncorrected 。finally 
throw a java.sql.SqlException： No value specified for parameter 。

**Comment by yogaling** [comment]
Why need to rewrite statements when there are no tables to sharding?

**Comment by terrymanu** [comment]
This part is still in refactoring.
