### ISSUE TITLE
NullPointerException will occur when bindingtable have no tablerule but have a default datasource

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2917]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
the dev branch
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
can work and not occur NullPointerException
### Actual behavior
occur a NullPointerException
### Reason analyze (If you can)
the initialization of bindingTableRules of ShardingRule use broadcastTables when broadcastTables have not been initialized

### Example codes for reproduce this issue (such as a github link).

> Map<String, DataSource> dataSourceMap = new HashMap<>();
        dataSourceMap.put("master_0", getMysqlDatasource("demo_ds_master_0"));
        ShardingRuleConfiguration configuration = new ShardingRuleConfiguration();
        configuration.setBindingTableGroups(Arrays.asList("user","user_detail"));
        configuration.setDefaultDataSourceName("master_0");
        ShardingDataSourceFactory.createDataSource(dataSourceMap,configuration,new Properties());

**Comment by terrymanu** [comment]
> the initialization of bindingTableRules of ShardingRule use broadcastTables when broadcastTables have not been initialized

I can't find relationship of `bindingTableRules ` and `broadcastTables `.
Can you provide error message and let me know where is the code to cause this issue?

**Comment by betterjava** [comment]
<img width="1037" alt="sharing-bug" src="https://user-images.githubusercontent.com/4453100/63631640-4564c180-c65d-11e9-80a7-55df938f4223.png">

**Comment by copyshop** [comment]
Can you show your config file from project.

**Comment by betterjava** [comment]
@copyshop see my example code in the top of this issue.

**Comment by terrymanu** [comment]
@betterjava Yes, I found the dependency of `bindingTableRules` and `broadcastTables`.
The pull request is correct, I will merge it soon, thank you for contribute codes.
