### ISSUE TITLE
When association query，table name of join table is changed to lowercase, but the first is not unchanged

### ISSUE THREAD

**Issue by ustbyjy** [apache/incubator-shardingsphere#2920]
### Which version of ShardingSphere did you use?
4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
`select COLUMNS_V2.* from COLUMNS_V2 left join SDS ON SDS.CD_ID = COLUMNS_V2.CD_ID left join TBLS ON TBLS.TBL_ID = SDS.SD_ID;`

### Actual behavior
`select COLUMNS_V2.* from COLUMNS_V2 left join sds ON sds.CD_ID = COLUMNS_V2.CD_ID left join tbls ON tbls.TBL_ID = sds.SD_ID`

**Comment by ustbyjy** [comment]
Reason analyze：
BindingTableRule.java, Line 78
`return each.getActualDataNodes().get(index).getTableName().toLowerCase();`
the mothod of toLowerCase caused it.

**Comment by terrymanu** [comment]
Could you submit a pull request to fix it?

**Comment by sluk3r** [comment]
@ustbyjy Hi, I try to reproduce the issue, but failed. So, the my reproduce code, let us discuss the exact way to reproduce the issue, and my reproduce code link is: https://github.com/apache/incubator-shardingsphere-example, branch is ss_issue_2920, the code is based on incubator-shardingsphere-example. 

the sql is "SELECT i.* FROM **T_ORDER** o left join **t_order_item** i on o.order_id = i.order_id", which is in class of OrderItemRepositoryImpl, in package of "org.apache.shardingsphere.example.core.jdbc.repository",  in method of "selectAll"

And when I run the JavaConfigurationExampleMain class, in debug mode,  I saw the rewrote sql is "SELECT i.* FROM **t_order_0** o left join **t_order_item_0** i on o.order_id = i.order_id", shown in the following pic:

![image](https://user-images.githubusercontent.com/6405801/67288460-97b44880-f50f-11e9-8085-63ea11004652.png)

As we see, there is no case-related problems:  both t_order_0 and t_order_item_0 are in lowercase.

So, I want to know more info to reproduce the issue. 
Tks.

**Comment by ustbyjy** [comment]
1.I use Sharding-Proxy 4.0.0-RC2, which is downloaded from [https://shardingsphere.apache.org/document/current/en/downloads/](shardingsphere.apache.org).

2.The config-sharding.yaml file is shown below: 
`
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://vhost1:3306/metastore?useSSL=false
    username: root
    password: root123..
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://vhost1:3306/holmes?useSSL=false
    username: root
    password: root123..
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    DBS:
      actualDataNodes: ds_0.DBS
    TBLS:
      actualDataNodes: ds_0.TBLS
    TABLE_PARAMS:
      actualDataNodes: ds_0.TABLE_PARAMS 
    SDS:
      actualDataNodes: ds_0.SDS
    COLUMNS_V2:
      actualDataNodes: ds_0.COLUMNS_V2

    board:
      actualDataNodes: ds_1.board
    common:
      actualDataNodes: ds_1.common
    event:
      actualDataNodes: ds_1.event
    event_filter:
      actualDataNodes: ds_1.event_filter
    filter:
      actualDataNodes: ds_1.filter
    graph:
      actualDataNodes: ds_1.graph
    graph_group:
      actualDataNodes: ds_1.graph_group
    project_db:
      actualDataNodes: ds_1.project_db
    report:
      actualDataNodes: ds_1.report
    table_info:
      actualDataNodes: ds_1.table_info
  bindingTables:
    - DBS,TBLS,TABLE_PARAMS,SDS,COLUMNS_V2,board,common,event,event_filter,filter,graph,graph_group,project_db,report,table_info
  defaultDataSourceName:
    ds_1
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
`

3.The SQL is `select COLUMNS_V2.* from COLUMNS_V2 left join SDS ON SDS.CD_ID = COLUMNS_V2.CD_ID left join TBLS ON TBLS.TBL_ID = SDS.SD_ID`

4.The running log is as follows:
`
[INFO ] 10:44:38.822 [ShardingSphere-Command-6] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 10:44:38.823 [ShardingSphere-Command-6] ShardingSphere-SQL - Logic SQL: SET PROFILING = 1
[INFO ] 10:44:38.823 [ShardingSphere-Command-6] ShardingSphere-SQL - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
[INFO ] 10:44:38.824 [ShardingSphere-Command-6] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET PROFILING = 1
[INFO ] 10:44:38.824 [ShardingSphere-Command-6] ShardingSphere-SQL - Actual SQL: ds_1 ::: SET PROFILING = 1
[INFO ] 10:44:38.858 [ShardingSphere-Command-7] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 10:44:38.858 [ShardingSphere-Command-7] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 10:44:38.858 [ShardingSphere-Command-7] ShardingSphere-SQL - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
[INFO ] 10:44:38.858 [ShardingSphere-Command-7] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[INFO ] 10:44:38.859 [ShardingSphere-Command-7] ShardingSphere-SQL - Actual SQL: ds_1 ::: SHOW STATUS
[INFO ] 10:44:38.901 [ShardingSphere-Command-8] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 10:44:38.901 [ShardingSphere-Command-8] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 10:44:38.901 [ShardingSphere-Command-8] ShardingSphere-SQL - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
[INFO ] 10:44:38.901 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[INFO ] 10:44:38.901 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_1 ::: SHOW STATUS
[INFO ] 10:44:38.965 [ShardingSphere-Command-9] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 10:44:38.965 [ShardingSphere-Command-9] ShardingSphere-SQL - Logic SQL: select COLUMNS_V2.* from COLUMNS_V2 left join SDS ON SDS.CD_ID = COLUMNS_V2.CD_ID left join TBLS ON TBLS.TBL_ID = SDS.SD_ID
[INFO ] 10:44:38.965 [ShardingSphere-Command-9] ShardingSphere-SQL - SQLStatement: ShardingSelectOptimizedStatement(tables=Tables(tables=[Table(name=COLUMNS_V2, alias=Optional.absent()), Table(name=SDS, alias=Optional.absent()), Table(name=TBLS, alias=Optional.absent())], schema=Optional.absent()), groupBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.groupby.GroupBy@7de19913, orderBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderBy@732668df, selectItems=SelectItems(startIndex=7, stopIndex=18, distinctRow=false, items=[ShorthandSelectItem(owner=Optional.of(COLUMNS_V2))], tables=[TableSegment(startIndex=25, stopIndex=34, name=COLUMNS_V2, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.absent()), TableSegment(startIndex=46, stopIndex=48, name=SDS, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.absent()), TableSegment(startIndex=92, stopIndex=95, name=TBLS, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.absent())]), pagination=org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination@7719f263, containsSubquery=false)
[INFO ] 10:44:38.966 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_0 ::: select COLUMNS_V2.* from COLUMNS_V2 left join sds ON sds.CD_ID = COLUMNS_V2.CD_ID left join tbls ON tbls.TBL_ID = sds.SD_ID
`

**Comment by sluk3r** [comment]
@ustbyjy  Hi, would you please give the schema of the tables, in order to reproduce the issue.

**Comment by ustbyjy** [comment]
[metastore.txt](https://github.com/apache/incubator-shardingsphere/files/3777779/metastore.txt)

**Comment by sluk3r** [comment]
@ustbyjy  would you like to add my wechat accout, in order to chat for this issue. 
And my email is sluk3r@qq.com, you can drop an email for my wechat accout, if you like.

**Comment by sluk3r** [comment]
@ustbyjy  Hi, with your [config file](https://github.com/apache/incubator-shardingsphere/files/3759821/config-sharding.txt)， when I get DataSource, there is an error concerning with parsing yaml content, that is:

![image](https://user-images.githubusercontent.com/6405801/67687836-d9dbff00-f9d3-11e9-8070-f0fa6cb52755.png)

the reproduce code is YamlIssue2920Main.java, as in https://github.com/sluk3r/incubator-shardingsphere-example/tree/ss_issue_2920

**Comment by sluk3r** [comment]
Reproduced

**Comment by sluk3r** [comment]
@terrymanu @ustbyjy  I am not sure which table name is correct. the table name of "SDS" should not be lowercased?

**Comment by ustbyjy** [comment]
SDS and TBLS.

In my opinion, the table name should't be lowercased, because table name may be case-sensitive in db.

**Comment by sluk3r** [comment]
Sorry， I have no time to fix this bug. 
and, It is recommended to forward this issue to others.

**Comment by terrymanu** [comment]
Ok, i just set the label as `volunteer wanted` again.

**Comment by terrymanu** [comment]
Closed until somebody interesting about this issue
