### ISSUE TITLE
IllegalArgumentException will occur when execute 'show databases' use sharding-jdbc

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2922]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
the dev branch
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
no Exception
### Actual behavior
occur an IllegalArgumentException
### Reason analyze (If you can)
initialization of AbstractResultSetAdapter check resultSets whether empty ，but resultSets will empty when you show databases
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
<img width="981" alt="testBugShow" src="https://user-images.githubusercontent.com/4453100/63668150-d88e2a80-c808-11e9-9e6f-bdb9adba5a44.png">

### Example codes for reproduce this issue (such as a github link).
<img width="1072" alt="bugdetail" src="https://user-images.githubusercontent.com/4453100/63668160-e2179280-c808-11e9-9c8f-b6d269138184.png">

**Comment by wowojyc** [comment]
I have met the same question, did you solve it?

**Comment by betterjava** [comment]
I am not sure whether it is a solution by remove the check.I will pull a request later.

**Comment by wowojyc** [comment]
> I am not sure whether it is a solution by remove the check.I will pull a request later.

No, I try this solution. It will throw new exception ArrayIndexOutOfBoundsException, because the following method will call resultsets.get(0). If the resultsets in empty, these exception happened

**Comment by wowojyc** [comment]
I think this problem has some thing with RouteEngineFactory and UnicastRoutingEngine.

I found out this code script by git history, it is different now version. But I do not know why.

![image](https://user-images.githubusercontent.com/9378228/63826286-e4a4f400-c990-11e9-9f39-48e34db17d43.png)

**Comment by cherrylzhao** [comment]
I think we should consider about adding a new resultSet to adapter `show databases` statement if necessary, what's your opinion?  @terrymanu

**Comment by terrymanu** [comment]
Yes, we need add a new type of resultSet to merge
