### ISSUE TITLE
MasterSlave can not work well 

### ISSUE THREAD

**Issue by betterjava** [apache/incubator-shardingsphere#2931]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
dev branch
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
can work and no exception
### Actual behavior
throw an exception
### Reason analyze (If you can)
My code can work well few days ago.But today It can not work.I saw there is some commits 
in nearly days. The key change is from the class TableMetaDataLoader. It seems something 
between logicTable and actualTable was mess up.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

<img width="1422" alt="bugfile" src="https://user-images.githubusercontent.com/4453100/63752792-70147b80-c8e4-11e9-9ac1-e27db5780b8b.png">

### Example codes for reproduce this issue (such as a github link).

<img width="1328" alt="bugdetailnow" src="https://user-images.githubusercontent.com/4453100/63752811-773b8980-c8e4-11e9-88df-fd8192ca4ac0.png">

**Comment by betterjava** [comment]
@terrymanu  My code can work well before I merged new changes from dev branch to local, so I think maybe it  is a problem made by nearly refactor,but I am not sure about it.

**Comment by tuohai666** [comment]
Can you open sql.show and show me the log?
And check the database to find out whether admin.user_0 exists?

**Comment by betterjava** [comment]
@tuohai666 This is no relationship between admin and user. I open sql.show,but nothings change in log.
![image](https://user-images.githubusercontent.com/4453100/64087474-dd565f80-cd6f-11e9-8f07-0f1de90cfcd7.png)

**Comment by betterjava** [comment]
If I turn it to old version,it can work well.
![image](https://user-images.githubusercontent.com/4453100/64087627-708f9500-cd70-11e9-8fda-107f05655b76.png)

**Comment by betterjava** [comment]
Here is the sql for craete table.
CREATE TABLE `user_0` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `ex_id` int(11) DEFAULT NULL,
  `pre_name` varchar(100) DEFAULT NULL,
  `name_assisted` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_1` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `ex_id` int(11) DEFAULT NULL,
  `pre_name` varchar(100) DEFAULT NULL,
  `name_assisted` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE DATABASE IF NOT EXISTS demo_ds_master_0 default charset utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS demo_ds_master_0_slave_0 default charset utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS demo_ds_master_0_slave_1 default charset utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS demo_ds_master_1 default charset utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS demo_ds_master_1_slave_0 default charset utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS demo_ds_master_1_slave_1 default charset utf8 COLLATE utf8_general_ci;

**Comment by tuohai666** [comment]
You don't need to know whether there's relationship between admin and user. If you just answer my question instead of think what I think, things may become easier.

I want to see logical SQL and actual SQL by open sql.show, is it the full log in the picture?

**Comment by tuohai666** [comment]
Can you point out which version is the "old version"?

**Comment by betterjava** [comment]
Yes,it is the full log. And the "old version" is 4.0.0-RC2-release.

**Comment by tuohai666** [comment]
Can you check the database to find out whether admin.user_0 exists? Is 'admin' your database?

**Comment by betterjava** [comment]
admin.user_0 not exists.

**Comment by tuohai666** [comment]
Can you show me your url in datasource config? For example:
jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false

**Comment by betterjava** [comment]
![image](https://user-images.githubusercontent.com/4453100/64090824-cf103f80-cd7f-11e9-8276-c53bb3d58b93.png)

**Comment by tuohai666** [comment]
datasourceName is the key. I guess the datasourceName will be "admin" under certain contain. Can you debug to find all datasourceNames?

**Comment by betterjava** [comment]
OK I will try.

**Comment by betterjava** [comment]
I think I found the reason of this problem. Let me show my analysis.
TableMetaDataLoader.java in dev branch:

![image](https://user-images.githubusercontent.com/4453100/64092420-52815f00-cd87-11e9-9140-092302ace85f.png)

TableMetaDataLoader.java in 4.0.0-RC2-release:

![image](https://user-images.githubusercontent.com/4453100/64092513-b4da5f80-cd87-11e9-95b0-08082e8bfbac.png)

In the dev branch,the masterSlave DataSourceName can not match the original DataSourceName in dataSourceMetaDataMap of DataSourceMetas.java. Some logic of masterSlave was removed in DataSourceMetas. 

If that can not match, catalog will be null. If catalog will be null then the mysql will find the first datasource to search table,in my mysql,the first datasource is admin.

**Comment by tuohai666** [comment]
Nice analysis! Thanks. I'll check it.

**Comment by tuohai666** [comment]
@betterjava What's the version of your connector/j?

**Comment by betterjava** [comment]
8.0.13

**Comment by tuohai666** [comment]
I have tried 5.1.47 & 8.0.17 but can't reproduce this Exception although the catalog is null.

**Comment by tuohai666** [comment]
> 8.0.13

As expected, this version throws Exception. I think this is a bug of connector/j. I will try to find it in release notes later.

I want to say the change in TableMetaDataLoader is right. This change will not cause issues if we use a proper version of connector/j

**Comment by tuohai666** [comment]
You can have a try with 8.0.17.

**Comment by betterjava** [comment]
I tried 8.0.17 and it is work well. I will debug for find something different between 8.0.17 and 8.0.13.

**Comment by betterjava** [comment]
I think you are right.
But in my opinion  It is very strange for using masterSlave DatasourceName to match  original DatasourceName in DataSourceMetas.
I test it for mysql-connector-java:**8.0.11、8.0.12、8.0.13、8.0.14、8.0.15、8.0.16**. It is all failed in dev version and all works well in 4.0.0-RC2-release.
Thanks for your help again.

**Comment by tuohai666** [comment]
This bug does not exist in the release notes: 
https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-17.html
Any way, they have already fixed it.
Thanks for your report.
