### ISSUE TITLE
Do you need to configure tables without Sharding into sharding rules, if you only have partial databases or tables for Sharding?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2933]
## Question
Do you need to configure tables without Sharding into sharding rules, if you only have partial databases or tables for Sharding?
The official doc gave a method that just config a default data source. Yes i do config default-data -source. But do i need to config those tables without sharding to the "bindingTables" list ?

**Comment by Myshiner** [comment]
Project: sharding-proxy
Version: v3.1.0

Thank you !

**Comment by wowojyc** [comment]
> ## Question
> Do you need to configure tables without Sharding into sharding rules, if you only have partial databases or tables for Sharding?
> The official doc gave a method that just config a default data source. Yes i do config default-data -source. But do i need to config those tables without sharding to the "bindingTables" list ?

I have the same question

**Comment by sunbufu** [comment]
Same like this [issue](https://github.com/apache/incubator-shardingsphere/issues/2935). 
SS should shield out the actual table, user can only execute sql which table is logic table or table in default datasource in SS.

**Comment by Myshiner** [comment]
I have tested in proxy, just config a default-data-source and then without those non-sharding tables to be configed to the "bingingTables" list and "Tables" list, it did work. Thank you!
