### ISSUE TITLE
SpringBoot 1.5.x how to use ?

### ISSUE THREAD

**Issue by TravelEngineers** [apache/incubator-shardingsphere#2938]
### No1. 无法根据操作手册使用
例如SpringBoot1.5.x与SpringBoot2.x的配置文件是有差异的， ShardingSphere 中的用户手册建议分开来写。例如数据库的驱动类，现在使用SpringBoot 1.5.x版本然后再使用手册中给出的配置，会出现如下错误：
Description:
Cannot determine embedded database driver class for database type NONE
还是说ShardingSphere 目前不考虑支持SpringBoot1.5.x版本的了，如果是的话可以做一下适配吗？
#### SpringBoot use Yaml
现在已经习惯使用yml来作为SpringBoot的首选配置，此处建议增加相关说明。
#### Maven add last version config
Maven建议使用使用SpringBoot官方文档中的介绍，直接写出样例的最新版本的配置，而不是让使用的小伙伴去自己找哇。
eg:
```
      <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>
```
For English:
### No1 Cannot be used according to operation manual
For example, the configuration files of SpringBoot 1.5.x and SpringBoot 2.x are different, and the user manual in SharingSphere suggests writing them separately. For example, the database driver class, now using SpringBoot version 1.5.x and then using the configuration given in the manual, will make the following mistakes:

Description:

Cannot determine embedded database driver class for database type NONE

Or is ShardingSphere currently not considering support for SpringBoot version 1.5. x? If so, can you do some adaptation?
#### SpringBoot use Yaml
Now that you're used to using YML as the preferred configuration for SpringBoot, it's recommended to add a description here.
#### Maven add last version config
Maven suggests using the introduction in SpringBoot's official documentation to write out the latest version of the configuration of the sample directly, rather than letting the little buddies use it to find out for themselves.
eg:
```
         <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>
```

**Comment by TravelEngineers** [comment]
##SpringBoot 2.1.7 user config 
```
spring.shardingsphere.datasource.name=ds

spring.shardingsphere.datasource.ds.type=org.apache.commons.dbcp2.BasicDataSource
spring.shardingsphere.datasource.ds.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds.url=jdbc:mysql://127.0.0.1:3306/encrypt?serverTimezone=UTC&useSSL=false
spring.shardingsphere.datasource.ds.username=root
spring.shardingsphere.datasource.ds.password=
spring.shardingsphere.datasource.ds.max-total=100

spring.shardingsphere.encrypt.encryptors.encryptor_aes.type=aes
spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value=123456
spring.shardingsphere.encrypt.tables.t_order.columns.user_id.plainColumn=user_decrypt
spring.shardingsphere.encrypt.tables.t_order.columns.user_id.cipherColumn=user_encrypt
spring.shardingsphere.encrypt.tables.t_order.columns.user_id.assistedQueryColumn=user_assisted
spring.shardingsphere.encrypt.tables.t_order.columns.user_id.encryptor=encryptor_aes

spring.shardingsphere.props.sql.show=true
spring.shardingsphere.props.query.with.cipher.comlum=true
```
Error msg:
```
Description:
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class
Action:
Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
