### ISSUE TITLE
not support “show full tables from `sharding_db` like't_test1'”

### ISSUE THREAD

**Issue by gaodesen163** [apache/incubator-shardingsphere#2939]
sharding proxy version
https://dist.apache.org/repos/dist/dev/incubator/shardingsphere/4.0.0-RC1/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz

(1)
create table tbname1 (id int primary key,key_price decimal(16,2) DEFAULT NULL);

(2)
mysql> show full tables from sharding_db like 'tbname1'
no return value
受影响的行: 0
https://user-images.githubusercontent.com/13394604/63440944-48945d80-c463-11e9-9b5a-13b8e492a043.png)

but sharding-proxy-3.1.0.tar.gz It supports this function.

thanks

**Comment by sunbufu** [comment]
Duplicate with this issue <https://github.com/apache/incubator-shardingsphere/issues/2904>.
Please do not create duplicated issue.
