### ISSUE TITLE
Would it be a problem to separate tables in a single database without setting actualTables?

### ISSUE THREAD

**Issue by 2417796669** [apache/incubator-shardingsphere#2940]
进行分表的时候，需要根据租户ID进行分表，但是租户Id是随着业务增长不断增加的。所以实现如下
` ShardingRuleConfiguration ruleConfiguration = new ShardingRuleConfiguration();
        String[] tables = properties.getTables();
        Arrays.asList(tables).stream().forEach(table -> {
            TableRuleConfiguration rule = new TableRuleConfiguration(table);
            ruleConfiguration.getTableRuleConfigs().add(rule);
        });
        ruleConfiguration.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration(properties.getShardingColumn(),
                new ExclusivePreciseShardingAlgorithm()));`
分片算法的实现：
`public String doSharding(Collection<String> collection, PreciseShardingValue<String> preciseShardingValue) {
        for (String table : collection) {
            if (table.equals(preciseShardingValue.getLogicTableName())) {
                return new StringBuilder(table).append("_SHARD_").append(preciseShardingValue.getValue()).toString();
            }
        }
        return preciseShardingValue.getLogicTableName();
    }`
简单测试之后发现是可以正常进行分表，请问会不会造成其他的问题呢？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
