### ISSUE TITLE
nested exception is java.sql.SQLException: sql injection violation, multi-statement not allow : update

### ISSUE THREAD

**Issue by dunzung** [apache/incubator-shardingsphere#2942]
mybatisplus:2.0.8
druid:1.1.3
sharding-jdbc：2.0.3
异常更新sql语句：
`<select id="updateStatusBatch">
   UPDATE
   sys_dept
   SET
   del_flag = #{status}
   WHERE dept_id in
   <foreach collection="deptIdList" index="index" item="item" open="(" separator="," close=")">
      #{item}
   </foreach>
</select>`
此语句会导致系统卡死，整个服务出现“假死状态”。默认情况下不使用sharding-jdbc，用mybatisplus加druid运行正常

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
