### ISSUE TITLE
User's manual data desensitization section parameter error

### ISSUE THREAD

**Issue by TravelEngineers** [apache/incubator-shardingsphere#2945]
## Question
When using version 4.0.0-RC1, the configuration parameters of the data desensitization part of SpringBoot cannot be started, and the latest version of the document can only use version 4.0.0-RC2. Please add a compatibility note for different versions.

**Comment by TravelEngineers** [comment]
SpringBoot use 2.1,x version

**Comment by TravelEngineers** [comment]
It is suggested to add a full configuration parameter introduction of different versions, some of which are not fully annotated according to the chapter.

**Comment by sunbufu** [comment]
Can you show some configuration?

**Comment by TravelEngineers** [comment]
> Can you show some configuration?

I have find anawer,think you.

must to use last version ,old version is error by 4.0.0-RC1,you can try ti by youselef
