### ISSUE TITLE
My database table names are all uppercase , how to config ?

### ISSUE THREAD

**Issue by wyt1128** [apache/incubator-shardingsphere#2948]
I track the source code  , find that 

public TableRule(final TableRuleConfiguration tableRuleConfig, final ShardingDataSourceNames shardingDataSourceNames, final String defaultGenerateKeyColumn) {
        logicTable = tableRuleConfig.getLogicTable().toLowerCase();
.....
}

why the logicTable need   toLowerCase?

**Comment by copyshop** [comment]
I guess it doesn't mean much. it's only ignore case-sensitive.

**Comment by copyshop** [comment]
for example
broadcastTables:
    - t_config
    - T_TEST
it can run correctly.

**Comment by taojintianxia** [comment]
> In MySQL, databases correspond to directories within the data directory. Each table within a database corresponds to at least one file within the database directory (and possibly more, depending on the storage engine). Triggers also correspond to files. Consequently, the case sensitivity of the underlying operating system plays a part in the case sensitivity of database, table, and trigger names. This means such names are not case-sensitive in Windows, but are case-sensitive in most varieties of Unix. One notable exception is macOS, which is Unix-based but uses a default file system type (HFS+) that is not case-sensitive. However, macOS also supports UFS volumes, which are case-sensitive just as on any Unix.

https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

maybe just for ignoring the negative effects of case sensitive
