### ISSUE TITLE
Error happened when compiling 4.0.0-RC2 source code

### ISSUE THREAD

**Issue by timchan1011** [apache/incubator-shardingsphere#2952]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2-Release
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
Error happend when compiling 4.0.0-RC2 source code. Error message is as follows:
Error:(22,52) java: package org.apache.shardingsphere.core.parse.autogen does not exist
Error:(29,44) java: No symbols found
Symbol: Class SQL Server Statement Parser

### Reason analyze (If you can)
Class SQLServerStatementLexer could not be found

**Comment by terrymanu** [comment]
Can you explain the reason to close this issue?

**Comment by DesperateL** [comment]
how did you solve this problem? @timchan1011
