### ISSUE TITLE
About Transaction

### ISSUE THREAD

**Issue by M-make** [apache/incubator-shardingsphere#2955]
Can this be only XA? How do I set it to LOCAL?

![image](https://user-images.githubusercontent.com/35563513/64005994-02668a80-cb44-11e9-821f-88c31ec4eee8.png)

shardingTransactionManager is always null

**Comment by cherrylzhao** [comment]
default is local, we hope you write a issue more serious, please tell us ShardingSphere version, example code

**Comment by M-make** [comment]
i report new issues in https://github.com/apache/incubator-shardingsphere/issues/2957
