### ISSUE TITLE
Sharding-JDBC  can not convert LONGTEXT data in MySql  to java.sql.Clob

### ISSUE THREAD

**Issue by lianqiuye** [apache/incubator-shardingsphere#2956]
Sharding-JDBC Version: 4.0.0-RC2

org.apache.shardingsphere.core.execute.sql.execute.result.QueryResultUtil convert column data to crossponding java Object by ResultSetMetaData, but the target data type may be a compatible java type.

Suggestion:
Mysql driver restore LONGTEXT as String as default, but if caller ask for java.sql.Clob type, the driver will convert to clob silently. The QueryResultUtil  should consider the target type and ask the driver  to convert to the target type.

**Comment by sunbufu** [comment]
Thank you for your suggestion. Can you give me more details? Some configuration, code and exception will help me.

**Comment by terrymanu** [comment]
Closed for no response any more.
