### ISSUE TITLE
How to switch check.table.metadata.enabled:false

### ISSUE THREAD

**Issue by siweizuse** [apache/incubator-shardingsphere#2959]
its start slowly
cause by load the matedata from all of sharding tables and check
when to optimize this issue

**Comment by taojintianxia** [comment]
just like the configuration for sql.show, put the following config into your sharding-xx.yaml

```
props:
  sql.show: true
  check.table.metadata.enabled: true
```

**Comment by taojintianxia** [comment]
however , *check.table.metadata.enabled* is a boolean value,  the default value for this config is false , I'm not sure if we set explicitly *check.table.metadata.enabled: true* will change anything.

**Comment by siweizuse** [comment]
> just like the configuration for sql.show, put the following config into your sharding-xx.yaml
> 
> ```yaml
> props:
>   sql.show: true
>   check.table.metadata.enabled: true
> ```

thinks
