### ISSUE TITLE
Delete with alias error

### ISSUE THREAD

**Issue by wowojyc** [apache/incubator-shardingsphere#2961]
Sharding-jdbc
version:4.0.0-RC1
my logical sql 
delete Goods from goods AS Goods WHERE Goods.goods_id   <=   ?

However sharding-jdbc replace alias and the table name totally, just like this
delete goods_1 from goods_1 AS Goods WHERE Goods.goods_id   <=   ?
this will execute error in mysql 5.6

One solution is to change to another alias different table name, but this may difficult for me. What else should I do?

**Comment by wowojyc** [comment]
version 4.0.0.-RC1 and 4.0.0.RC2 have different error.

delete goos_s from goods as goods_s where good_s.goods_id< 10 will execute successfully under RC1, but will execute error under RC2

**Comment by sunbufu** [comment]
Can you show some exception?

**Comment by wowojyc** [comment]
> Can you show some exception?
Here is the exception trace, but if i change to 4.0.0.RC1, it will execute normally.
![image](https://user-images.githubusercontent.com/9378228/64146969-6c877400-ce51-11e9-9323-3cde2f341cb1.png)

**Comment by sunbufu** [comment]
Consider supporting DML for Multiple-Table with low ROI, SS can't support it for now.

**Comment by wowojyc** [comment]
> Consider supporting DML for Multiple-Table with low ROI, SS can't support it for now.

No, it is not multiple table.

It is just add the table alias for delete operation.

And it runs well under 4.0.0-RC1, and it can not support now, is it reasonable?

**Comment by sunbufu** [comment]
Thanks for your issue. I'll look at it.

**Comment by strawhat925** [comment]
just saw this piece of source code, is to parse sql bug

**Comment by strawhat925** [comment]
Should take tableReferences this node to resolve table name

**Comment by wowojyc** [comment]
> just saw this piece of source code, is to parse sql bug

Thank you for your help. But I can not see your picture, could you reply me again?

**Comment by strawhat925** [comment]
sql-statement-rule-definition.xml file
<sql-statement-rule context="delete" sql-statement-class="org.apache.shardingsphere.core.parse.sql.statement.dml.DeleteStatement" extractor-rule-refs="tables, columns, where, predicate " />
Tables changed to tableReferences, can be executed normally

**Comment by strawhat925** [comment]
<sql-statement-rule context="delete" sql-statement-class="org.apache.shardingsphere.core.parse.sql.statement.dml.DeleteStatement" extractor-rule-refs="tables, columns, where, predicate " />
Tables changed to tableReferences, can be executed normally

**Comment by strawhat925** [comment]
`<sql-statement-rule context="delete" sql-statement-class="org.apache.shardingsphere.core.parse.sql.statement.dml.DeleteStatement" extractor-rule-refs="tables, columns, where, predicate " />`
Tables changed to tableReferences, can be executed normally

**Comment by wowojyc** [comment]
> `<sql-statement-rule context="delete" sql-statement-class="org.apache.shardingsphere.core.parse.sql.statement.dml.DeleteStatement" extractor-rule-refs="tables, columns, where, predicate " />`
> Tables changed to tableReferences, can be executed normally

Thank you very much. This solution does really work.

Is it a bug or not?
@sunbufu

**Comment by strawhat925** [comment]
I think it is a bug, but the single table does not support it. Need to judge the data node

**Comment by strawhat925** [comment]
I think it is a bug, but the single table does not support it. Need to judge the data node
Maybe ss did not consider this grammar

**Comment by sunbufu** [comment]
It's looks like a bug, and I will work on it tomorrow. Please let me know if you have any advice.

**Comment by wowojyc** [comment]
> It's looks like a bug, and I will work on it tomorrow. Please let me know if you have any advice.

I follow strawhat925's advice.

Download the source code, then change the xml in mysql-parser module. At the end, I run maven install locally to generate the jar package.

In my application, i replace mysql parser with maven system scope.

It really works.

**Comment by strawhat925** [comment]
> I follow strawhat925's advice.
> 
> Download the source code, then change the xml in mysql-parser module. At the end, I run maven install locally to generate the jar package.
> 
> In my application, i replace mysql parser with maven system scope.
> 
> It really works.

Need to consider no aliases, I did not consider

**Comment by wowojyc** [comment]
> > I follow strawhat925's advice.
> > Download the source code, then change the xml in mysql-parser module. At the end, I run maven install locally to generate the jar package.
> > In my application, i replace mysql parser with maven system scope.
> > It really works.
> 
> Need to consider no aliases, I did not consider

Thank you very much. In my application, I will add alias default.

**Comment by strawhat925** [comment]
> Thank you very much. In my application, I will add alias default.

ss only supports single table deletion, so you don't have much meaning with aliases.

**Comment by wowojyc** [comment]
> > Thank you very much. In my application, I will add alias default.
> 
> ss only supports single table deletion, so you don't have much meaning with aliases.
For example this sql,
delete Goods from goods AS Goods WHERE Goods.goods_id <= ?
My where condition is from the other sql parser engine, it's pattern is `alias.column`. So my delete sql must add alias as well. Otherwise, it will not run in mysql.
