### ISSUE TITLE
antlr4 version 4.7.1 report an error

### ISSUE THREAD

**Issue by sunjiabo** [apache/incubator-shardingsphere#2963]
When I use 
"mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true"
An error was reported here. 
The error message is 
“A required class was missing while executing org.antlr:antlr4-maven-plugin:4.7.1:antlr4: org/antlr/v4/Tool”

When I update the version of **antlr4** to 4.7.2   evething is ok.

**Comment by terrymanu** [comment]
Can you submit a pull request to fix this issue?

**Comment by terrymanu** [comment]
Closed for no response any more, if the issue still existed, please create a new issue
