### ISSUE TITLE
The document is not up to date

### ISSUE THREAD

**Issue by sunjiabo** [apache/incubator-shardingsphere#2966]
https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/sharding/

	    TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration();
	    orderTableRuleConfig.setLogicTable("t_order");
	    orderTableRuleConfig.setActualDataNodes("ds${0..1}.t_order${0..1}");

But, these two properties are final.

**Comment by terrymanu** [comment]
Can you submit a pull request?

**Comment by haetao** [comment]
I have already pulled request this question, please pay attention to the latest example of the official website.
https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/sharding/
