### ISSUE TITLE
when using sharding master-slave-rules,the encryptRule is not worked for result,but is wored for param

### ISSUE THREAD

**Issue by Keanhua** [apache/incubator-shardingsphere#2972]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
the query result is decrypt

### Actual behavior
the query result is still encrypt

### Reason analyze (If you can)
thie query result not use the encryptRule to decrypt

**this question is not dupe! I use the master-slave-rules! I want the master-slave-rules and the encrpt can combine use!**

### Example codes for reproduce this issue (such as a github link).
spring:
shardingsphere:
datasource:
names: master,slave0
master:
type: com.alibaba.druid.pool.DruidDataSource
driver-class-name: org.h2.Driver
url: jdbc:h2:mem:dbtest:public;DB_CLOSE_DELAY=-1;MODE=MySQL
slave0:
type: com.alibaba.druid.pool.DruidDataSource
driver-class-name: org.h2.Driver
url: jdbc:h2:mem:dbtest:public;DB_CLOSE_DELAY=-1;MODE=MySQL
sharding:
defaultDataSourceName: dataSource
master-slave-rules:
dataSource:
master-data-source-name: master
slave-data-source-names[0]: slave0
load-balance-algorithm-type: ROUND_ROBIN
encryptRule:
encryptors:
encryptor_aes:
type: AES
props:
aes.key.value: 123456
tables:
company:
columns:
address:
cipherColumn: address
encryptor: encryptor_aes
full_name:
cipherColumn: full_name
encryptor: encryptor_aes
props:
sql.show: true

**Comment by betterjava** [comment]
@Keanhua I test this and it works well. My version is 4.0.0-RC2-release.
Here is my config yaml in spring boot:

![image](https://user-images.githubusercontent.com/4453100/64257737-70ea8480-cf58-11e9-816b-859ae079b0b0.png)

**Comment by betterjava** [comment]
@Keanhua I test that,and it works well,my version is 4.0.0-RC2-release.
Here is my config:

![image](https://user-images.githubusercontent.com/4453100/64260406-5ff04200-cf5d-11e9-9b68-cea03b9a12ac.png)

**Comment by Keanhua** [comment]
@betterjava the queryresult is not decrypt yet.
i use the config jusi not have the sharding like the follow pic shows
![image](https://user-images.githubusercontent.com/31396902/64306891-d5dcc380-cfc6-11e9-83ae-335a10094092.png)

![image](https://user-images.githubusercontent.com/31396902/64306657-1f78de80-cfc6-11e9-8c2e-b745310b541a.png)
![image](https://user-images.githubusercontent.com/31396902/64306750-6666d400-cfc6-11e9-8fb4-2b9700d27d64.png)
![image](https://user-images.githubusercontent.com/31396902/64306807-8eeece00-cfc6-11e9-824f-b646f3f68fd2.png)

**Comment by betterjava** [comment]
@Keanhua according to my understanding, master-slave and encrpt  can not combine used if then are not in a same sharding config.
See Three important config class below:

ShardingRuleConfiguration.java:
![image](https://user-images.githubusercontent.com/4453100/64308066-acbe3200-cfca-11e9-9c81-5a28cd6aaa60.png)

MasterSlaveRuleConfiguration.java:
![image](https://user-images.githubusercontent.com/4453100/64308103-c0699880-cfca-11e9-9d4a-97505d780ede.png)

EncryptRuleConfiguration:
![image](https://user-images.githubusercontent.com/4453100/64308126-d24b3b80-cfca-11e9-8f2c-36eb56c9c917.png)

ShardingRuleConfiguration can contain MasterSlaveRuleConfiguration and EncryptRuleConfiguration.  So a datasource from shardingsphere just in these situations:

- master-slave only
- encrypt only
- shard only
- shard + master-slave
- shard + encrypt
- shard + master-slave + encrypt

**Comment by betterjava** [comment]
@Keanhua you  can config like this,I test that and it works well:
![image](https://user-images.githubusercontent.com/4453100/64308840-3bcc4980-cfcd-11e9-864e-5405040e1fc1.png)

**Comment by Keanhua** [comment]
@betterjava 
sorry, i just show the pic is error ,i delete the sharding tag wrong.

I actually use the config like this (you show me). but the queryresult is not decrypt yet.
![image](https://user-images.githubusercontent.com/31396902/64310768-0f67fb80-cfd4-11e9-8a5d-bfba355b7801.png)

**Comment by Keanhua** [comment]
shading tag i not forget
![image](https://user-images.githubusercontent.com/31396902/64310883-93ba7e80-cfd4-11e9-86c4-c29a654ac917.png)

**Comment by betterjava** [comment]
please show your log in console like below:

![image](https://user-images.githubusercontent.com/4453100/64311120-733ef400-cfd5-11e9-9a1e-1db61c0898f8.png)

**Comment by Keanhua** [comment]
@betterjava 
![image](https://user-images.githubusercontent.com/31396902/64312796-18f56180-cfdc-11e9-80d4-ee9220aed790.png)

**Comment by betterjava** [comment]
@Keanhua 
is it correct?
![image](https://user-images.githubusercontent.com/4453100/64313729-2a8c3880-cfdf-11e9-8770-fa328a89d49e.png)

**Comment by Keanhua** [comment]
@betterjava 
this is the tablename. have anything wrong?
**when i insert data ,the column i config can encrypt to the table 
but when i query data, the column i config can not decrypt**
![image](https://user-images.githubusercontent.com/31396902/64315670-485c9c00-cfe5-11e9-878f-3d7fd4388e0e.png)

**Comment by betterjava** [comment]
@Keanhua  I thought you spell table name wrong,that is my fault.
Can you show your code how to query data?

**Comment by Keanhua** [comment]
@betterjava  yes ,the table name is wrong...........
this is mycode by use mybatis plus！
![image](https://user-images.githubusercontent.com/31396902/64323525-3e439900-cff7-11e9-8a51-74cc5714ef66.png)

you can see the detail in 
https://github.com/apache/incubator-shardingsphere/issues/2972#issuecomment-528167681

**Comment by betterjava** [comment]
@Keanhua can you test this code in your environment？
```
    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    public void testJdbc() {
        List<Map<String, Object>> result = jdbcTemplate.queryForList("select * from settlment_company where id = 2193");
        for(Map<String,Object> map:result){
            for(Map.Entry<String,Object> entry:map.entrySet()){
                System.out.println(entry.getKey()+":"+entry.getValue());
            }
        }
    }
```

I need whether it is a problem when use mybatis-plus.

**Comment by Keanhua** [comment]
@betterjava 
it looks like no problem 
![image](https://user-images.githubusercontent.com/31396902/64326446-9204b100-cffc-11e9-945c-2020620918cb.png)

**Comment by betterjava** [comment]
it seems like problem will happen when use mybatis-plus. I will check it.

**Comment by Keanhua** [comment]
@betterjava thank you so much

**Comment by betterjava** [comment]
@Keanhua which mybatis-plus version  you used?

**Comment by Keanhua** [comment]
@betterjava 
3.1.0
