### ISSUE TITLE
when set two column to encrypt, one of the cipher-column is plain data, the other is correct

### ISSUE THREAD

**Issue by SAMARITAN2046** [apache/incubator-shardingsphere#2974]
Sharding-encript
version:4.0.0-RC2-SNAPSHOT
my logical sql
SQL: update cf_application_info
set phone=?,idNo=?
where applyNum = ?
the question is when i set phone and idN is the cipher column,and alter my table by adding phone_cipher,idNo_cipher column,i update my data,the result is phone_cipher has the plain data,and the phone column has the cipher data,this is strange and i think this is a bug.

**Comment by tristaZero** [comment]
Thanks for your feedback, we will fix it soon
