### ISSUE TITLE
support hint in sharding-proxy

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#2979]
hint was supported by sharding-jdbc by thread-local. but it can't work in sharding-proxy.
we can extend [sctl](https://shardingsphere.apache.org/document/current/cn/manual/sharding-proxy/usage/#sctl-sharding-proxy-control-language) to support it in sharding-proxy. it looks like that 

- sctl:hint set MASTER_ONLY=true
- sctl:hint set DatabaseShardingValue=xx.     ## xx: sharding value
- sctl:hint addTableShardingValue xx=yy         ## xx: logicTableName，yy:sharding value
- sctl:hint addDatabaseShardingValue xx=yy. ## xx: logicTableName，yy:sharding value

sctl:hint command can be sent to proxy through JDBC, e.g. `connection.createStatement("stcl:hint set xxxx")`, after proxy received the request, it should be dispatched to `HintSCTLCommandHander` like `ShardingCTLSetBackendHandler`, then stored the hint content in current channel(`BackendConnection`)

**Comment by betterjava** [comment]
I think the pivotal problem is how the shardingEngine get hint value.Because different BackendConnection may in the same thread,so the ThradLoacal can not use. Can we use parameters to transport hint value or make every BackendConnection in a single Thread? Maybe Both solutions are not suitable. I think we can discuss here.

**Comment by cherrylzhao** [comment]
you are right, proxy should ensure the working thread is same for one client JDBC request, in fact XA and PostgreSQL of Proxy was implemented like that, we can refer to these. based on this condition，we should consider about how to transport hint value
1. transport hint value in every sql wrapped with `/** **/` grammer
    I think this is hard to implement, it should let user wrap every sql, or we provide a proxy client sdk to parse the user sql.
2. transport hint value using sctl grammar 
   it only need to send an additional stcl sql, it is easy to implement.

**Comment by betterjava** [comment]
I agree with you.
We can make every frontendConnection in a single thread by default or wen can provide  a hint switch to user,if users open the switch we do things like that.
What is your opinion?

**Comment by cherrylzhao** [comment]
it is better to make hint switch congfiguration，appreciate that you have a try for this feature.

**Comment by betterjava** [comment]
Aggree.
I am woring on it.

**Comment by cherrylzhao** [comment]
@betterjava I have verified the function, it's OK except database_only.
since database_only have not been supported after PR #3050.
next step is we should add doc and example for proxy-hint.

- https://github.com/apache/incubator-shardingsphere-doc/issues/247
- https://github.com/apache/incubator-shardingsphere-example/issues/179

have a good day~

**Comment by betterjava** [comment]
Ok,it sounds good.
I will try my best to complete the next thing.Before that I have some questions:
- Do we need support hint query for sharding-proxy?

**Comment by cherrylzhao** [comment]
it sounds good, you can create another issue for supporting query hint context for sharding-proxy

**Comment by cherrylzhao** [comment]
command looks like this, stcl:hint show status

**Comment by cherrylzhao** [comment]
close this issue, will discuss query context function in #3057
