### ISSUE TITLE
The Long type parameters of Pagination are incompatible

### ISSUE THREAD

**Issue by liaoxianrong** [apache/incubator-shardingsphere#2980]
When I using Mybatis-plus PaginationInterceptor plugin, shardingsphere does not work, something wrong has happend. Track it down and find an error at here:
org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination
```
private int getValue(final PaginationValueSegment paginationValueSegment, final List<Object> parameters) {
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? (int) parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex())
                : ((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue();
    }
```
The Long type parameters of Pagination, such as Long total, Long pageNum, Long pageSize. and then throw an exception at "(int) parameters.get(((ParameterMarkerPaginationValueSegment)  ".
Can someone help with that?

**Comment by KomachiSion** [comment]
duplicate with #2926
