### ISSUE TITLE
Merge OpenShardingUI features

### ISSUE THREAD

**Issue by beckhampu** [apache/incubator-shardingsphere#2986]
OpenShardingUI is a simple and useful web administration console for ShardingSphere. It provides ability of registry center management, dynamic configuration management, database orchestration, etc.It is designed to help users more easily use ShardingSphere. So we want to merge it into ShardingSphere。We have completed the following work：
- [x] Check OpenShardingUI License.
- [x] Add sharding-ui module for code.
- [x] Add sharding-ui-distribution module for release，including Scripts, License, Notice, etc.

**Comment by terrymanu** [comment]
The proposal is: https://cwiki.apache.org/confluence/display/SHARDINGSPHERE/OpenShardingUI+Donation+Proposal

Vote thread is: https://lists.apache.org/thread.html/1452a62e16f9b70d95e20c6b69f1090b8da895c568f561ddb3066113@%3Cdev.shardingsphere.apache.org%3E
