### ISSUE TITLE
Data does not decrypt

### ISSUE THREAD

**Issue by shuohao** [apache/incubator-shardingsphere#2992]
encryptRule:
  encryptors:
    aes_encryptor:
      props:
        aes.key.value: zqAvW0yEdH
      type: AES
  tables:
    task:
      columns:
        phone:
          cipherColumn: phone_cipher
          encryptor: aes_encryptor
          plainColumn: phone

![image](https://user-images.githubusercontent.com/4637107/64430682-5eed1b00-d0eb-11e9-89b3-77991af8039f.png)

insert  is well, it worked.
but when I select this record  the phone is null,  I used mybatis.
![image](https://user-images.githubusercontent.com/4637107/64430901-d458eb80-d0eb-11e9-8448-e9e049dec15e.png)

![image](https://user-images.githubusercontent.com/4637107/64430949-f5b9d780-d0eb-11e9-9ac7-2e1d29d112a4.png)
when I insert  it use encrypt method, but when i select  it dosen't call decrypt method.

**Comment by betterjava** [comment]
@shuohao is that your complete shardingsphere config? if not,please show your complete shardingsphere config.

**Comment by shuohao** [comment]
spring:
  profiles:
    active: test
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://${db.host}:${db.port}/my_task?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
        username: ${db.user}
        password: ${db.pwd}
        connectionTimeout: 5000
        maximumPoolSize: 200
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.cachePrepStmts: true
        dataSource.useServerPrepStmts: true
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://${dbRead.host}:${dbRead.port}/my_task?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
        username: ${dbRead.user}
        password: ${dbRead.pwd}
        connectionTimeout: 5000
        maximumPoolSize: 200
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.cachePrepStmts: true
        dataSource.useServerPrepStmts: true
    sharding:
      tables:
        task:
          actualDataNodes: ds.task,ds.task_clue
          tableStrategy:
            standard:
              shardingColumn: project
              preciseAlgorithmClassName: com.lianjia.sinan.task.dao.sharding.ManualShardingAlgorithm
        task_biz_field:
          actualDataNodes: ds.task_biz_field,ds.task_biz_field_clue
          tableStrategy:
            standard:
              shardingColumn: project
              preciseAlgorithmClassName: com.lianjia.sinan.task.dao.sharding.ManualShardingAlgorithm
      binding-tables:
        - task,task_biz_field
      master-slave-rules:
        ds.masterDataSourceName: master
        ds.slaveDataSourceNames: slave
      encrypt-rule:
        encryptors:
          aes_encryptor:
            type: AES
            props:
              aes.key.value: zqAvW0yEdH
        tables:
          task:
            columns:
              phone:
                plainColumn: phone
                cipherColumn: phone_cipher
                encryptor: aes_encryptor
    props:
      sql.show: true
      query.with.cipher.column: true

**Comment by shuohao** [comment]
> @shuohao is that your complete shardingsphere config? if not,please show your complete shardingsphere config.

spring:
  profiles:
    active: test
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://${db.host}:${db.port}/my_task?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
        username: ${db.user}
        password: ${db.pwd}
        connectionTimeout: 5000
        maximumPoolSize: 200
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.cachePrepStmts: true
        dataSource.useServerPrepStmts: true
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://${dbRead.host}:${dbRead.port}/my_task?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
        username: ${dbRead.user}
        password: ${dbRead.pwd}
        connectionTimeout: 5000
        maximumPoolSize: 200
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.cachePrepStmts: true
        dataSource.useServerPrepStmts: true
    sharding:
      tables:
        task:
          actualDataNodes: ds.task,ds.task_clue
          tableStrategy:
            standard:
              shardingColumn: project
              preciseAlgorithmClassName: com.lianjia.sinan.task.dao.sharding.ManualShardingAlgorithm
        task_biz_field:
          actualDataNodes: ds.task_biz_field,ds.task_biz_field_clue
          tableStrategy:
            standard:
              shardingColumn: project
              preciseAlgorithmClassName: com.lianjia.sinan.task.dao.sharding.ManualShardingAlgorithm
      binding-tables:
        - task,task_biz_field
      master-slave-rules:
        ds.masterDataSourceName: master
        ds.slaveDataSourceNames: slave
      encrypt-rule:
        encryptors:
          aes_encryptor:
            type: AES
            props:
              aes.key.value: zqAvW0yEdH
        tables:
          task:
            columns:
              phone:
                plainColumn: phone
                cipherColumn: phone_cipher
                encryptor: aes_encryptor
    props:
      sql.show: true
      query.with.cipher.column: true

**Comment by shuohao** [comment]
> @shuohao is that your complete shardingsphere config? if not,please show your complete shardingsphere config.

![image](https://user-images.githubusercontent.com/4637107/64435557-484bc180-d0f5-11e9-8776-233e2d12a08f.png)
![image](https://user-images.githubusercontent.com/4637107/64435595-56014700-d0f5-11e9-80ca-4eb71bf40a78.png)

**Comment by betterjava** [comment]
@shuohao see #2972,I have pull a request #2983 ,but not have been merged.

**Comment by shuohao** [comment]
> @shuohao see #2972,I have pull a request #2983 ,but not have been merged.

tks, I tested use your branch code and It worked!

**Comment by betterjava** [comment]
@shuohao my pull has been merged ,you can close the issue.:blush:
