### ISSUE TITLE
Sharding-JDBC 跨库查询合并结果数据类型转换异常

### ISSUE THREAD

**Issue by liboyan1992** [apache/incubator-shardingsphere#2998]
您使用的是哪个版本的ShardingSphere？
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.0.0-RC2</version>
		</dependency>

预期的行为
夸库查询返回合并结果集

实际行为
跨库查询合并结果数据类型转换异常

原因分析（如果可以的话）
1、单库的情况下能够正常转换mysql text 类型
2、跨库报：java.lang.ClassCastException: java.lang.String cannot be cast to java.sql.Clob

DataBase 
两个mysql数据库，两个库每个都有一张表：t_message。

DATAS 
数据库：ds_0,ds_1
ds_0.t_message有数据，ds_1.t_messag没有数据。
create schema ds_0;
create `ds_0`.`table t_message`
(
  id                  varchar(32)          not null comment '主键',
  content             text                 null comment '消息内容'

);
create schema ds_1;
create `ds_1`.`table t_message`
(
  id                  varchar(32)          not null comment '主键',
  content             text                 null comment '消息内容'

);
insert into `ds_1`.`table t_message`('id','content') values('1','{"key":"zj+d1VeWLaEtv8D8W1fDmQ\u003d\u003d"}'); 

![image](https://user-images.githubusercontent.com/25739554/64468917-ac55a080-d15c-11e9-94c8-72f14bf89ea5.png)

![image](https://user-images.githubusercontent.com/25739554/64468946-08202980-d15d-11e9-9517-43126179d80d.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by yesidu** [comment]
我也遇到了这个问题
