### ISSUE TITLE
Detail implementation of AES Data Masking is not documented.

### ISSUE THREAD

**Issue by skyoxZ** [apache/incubator-shardingsphere#3003]
After some research I find the AES masking algorithm (MySQL):
`UPDATE _table_ SET _cipherColumn_ = to_base64(aes_encrypt(_plainColumn_, unhex(left(sha('_key_'), 32))))`

It would be great if it is brought in document.

**Comment by tristaZero** [comment]
Hi @skyoxZ 
[Here](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/encrypt/impl/AESShardingEncryptor.java) is the implementation of AESShardingEncryptor. 
Other than that, please read [this article](https://www.infoq.cn/article/tk9gMjP6geOKOy-BTisX) to learn the solution of Data masking of ShardingShpere.

**Comment by tristaZero** [comment]
This issue is closed, for there is no reply from author more than 7 days.
