### ISSUE TITLE
error "There is no primary key here. Update will only use exact matching of the old values of the columns here. Thus, it may update more than one record."

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3005]
project: sharding-proxy
version: v3.1.0 & v4.0.0-RC2

question:
when i use navicate to connect sharding-proxy, and do double-click the table(any table), it can load all the datas but just threw the errors like "There is no primary key here. Update will only use exact matching of the old values of the columns here. Thus, it may update more than one record."

**Comment by Myshiner** [comment]
All the tables do have primary key.

**Comment by dongzl** [comment]
I am glad to finish it.

**Comment by dongzl** [comment]
I get the network packet through `Wireshark` software, and find some problem.

**When MySQL transfer data to Sharding-Proxy:**

<img width="701" alt="MySQL实际抓包" src="https://user-images.githubusercontent.com/5917359/67348495-b3ebd000-f577-11e9-9fcc-cf75af161498.png">
 
**When Sharding-Proxy transfer data to Navicat:**

<img width="670" alt="Sharding-Proxy_to_Navicat" src="https://user-images.githubusercontent.com/5917359/67348554-d7167f80-f577-11e9-80bb-46a60a2e18a5.png">

the two byte data `03 50` is missing, it is the table Primary Key flag.

I think this make the mistake.

**Comment by dongzl** [comment]
I debug Sharding-Proxy source code, when execute a query SQL, it should return column metadata.
But in `MySQLColumnDefinition41Packet` class, the `this.flags = 0` : 

![image](https://user-images.githubusercontent.com/5917359/67453652-e53ccc80-f659-11e9-9cdc-ef217c35e485.png)

this is the table column primary key flag, so the Navicat prompt a error message.

the `MySQLColumnDefinition41Packet` build by ResultSetMetadata, but ResultSetMetadata don't have primary key info, we can find primary key info in DatabaseMetadata, but it will be a huge change.

Is this a good way?
