### ISSUE TITLE
4.0.0-RC2 ResultSetMetaData  data was lost

### ISSUE THREAD

**Issue by kalvan2019** [apache/incubator-shardingsphere#3006]
###  question

***codes***

org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.EncryptResultSetMetaData#getLogicColumn

org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSetMetaData#getLogicColumn
```
 private String getLogicColumn(final String actualColumn) throws SQLException {
        for (Entry<String, String> entry : logicAndActualColumns.entrySet()) {
            if (entry.getValue().contains(actualColumn)) {
                return entry.getKey();
            }
        }
        throw new SQLException(String.format("Can not get logic column by %s.", actualColumn));
    }
```

```
entry.getValue().contains(actualColumn)  
``` 

***desc***

When there are two fields in a table, one field is the content of another field, such as

address

certificate_address

It is possible to match the columnName of certificate_address when looking up the columnName of the field address again, which results in the loss of the address field in the result set.

**Comment by tswstarplanet** [comment]
I will try to solve the problem

**Comment by terrymanu** [comment]
How to understand `one field is the content of another field` ?

**Comment by terrymanu** [comment]
Closed for no response any more.
