### ISSUE TITLE
Update table cannot support multiple-table.

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3007]
Project: sharding-proxy
Version: v3.1.0

**Question:**
when update two tables in a sql, will got the errors.
1. excuted sql context:
UPDATE entity_topic t,entity_teaching_directory d SET t.directory_id=d.id WHERE
t.stage_id=d.stage_id AND t.subject_id=d.subject_id AND d.`system_type` = '2' AND t.directory_id=0
2. throw errors:
3054 - Unknown exception: Cannot support Multiple-Table.

**Comment by sunbufu** [comment]
Yes, SS can not support Multiple-Table for some DML. Because this feature's ROI is relatively low.
