### ISSUE TITLE
Non-sub-database and sub-table, page query limit Bug

### ISSUE THREAD

**Issue by FelixLiuSheng** [apache/incubator-shardingsphere#3008]
for example:
from table xxx ,xxx Non-sub-database and sub-table

exec query “select * from xxx limit 10,5”

result parse  "select * from xxx limit 0,15";

expect parse "select * from xxx limit 10,5"

fix point :
![image](https://user-images.githubusercontent.com/18569549/64533439-11201f00-d346-11e9-80ff-daec6b16c91b.png)

if  Non-sub-database and sub-table then continue

**Comment by terrymanu** [comment]
Can you provide your version of shardingsphere?

**Comment by terrymanu** [comment]
Closed for no response any more.
