### ISSUE TITLE
Define variable in sql

### ISSUE THREAD

**Issue by yjjqrqqq** [apache/incubator-shardingsphere#3009]
### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
I found that if define variable in my sql, it will throw a exception .  "Error querying database. Cause: java.sql.SQLSyntaxErrorException: Table 'xx.xxxx doesn't exist"
`<select id="testSelect" resultType="map">
  SET @maxId = 100;
  SELECT * from xxxx where id <@maxId;
</select>`
### Reason analyze (If you can)
Dose ShardingSphere think  mysql variable should not be define in program sql ?

**Comment by terrymanu** [comment]
The ROI of support variable is pretty low, no plan to do this for now

**Comment by yjjqrqqq** [comment]
@terrymanu  Thanks,我已经解决了。 分库的几张表使用ShardingSphere， 其它的还是用普通的数据源
