### ISSUE TITLE
By using sharding column , it's still full scan

### ISSUE THREAD

**Issue by kofkyobsa** [apache/incubator-shardingsphere#3012]
### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
SQL: select
    bu_id,trade_id, trade_no, parent_trade_id, out_trade_id, shop_id, supply_id,store_id, parent_shop_id,
    user_id,buyer_user_id, open_id, third_order_time, trade_type, trade_source, trade_status, pay_amount,
    hide, logistic_amount, logistic_pay_type,  trade_remark,
    shop_remark, clerk_name, clerk_phone, address_id, area_id, city_area_id, province_area_id, 
    delivery_name, delivery_phone, detail_address, customer_id, customer_id_card, customer_name, 
    customer_phone, tags, is_cart, end_time,pay_time,has_parent, is_deleted, creator, editor, create_time,
    edit_time,attribute, promotion_attr
    from    
     pt_trade_shop  where is_deleted=0 and bu_id=? and hide in (0,1)
    and parent_trade_id = ?
    and shop_id=?
    order by id desc;

parms:  bu_id='0' ,parent_trade_id = '10000008496045', 
              shop_id='35f8ddbb04ff4038b2efd633c3a0474c'

sharding column : shop_id

when i used spring+mybatis online, some how it's still do table full scan，
but i can't debug online。
so which condition could cause this bug？

**Comment by terrymanu** [comment]
Can you try to version 4.0.0-RC2?

**Comment by terrymanu** [comment]
Because 3.1.0 is not apache release, so we suggest you try to 4.x for apache release.
I just close this issue, if 4.x has same issue, please create a new issue
