### ISSUE TITLE
By Use EncryptDataSource the query with text column occurs error

### ISSUE THREAD

**Issue by Keanhua** [apache/incubator-shardingsphere#3017]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
By Use EncryptDataSource the query with text column can return correct result

### Actual behavior
By Use EncryptDataSource the query with text column occurs error

### Reason analyze (If you can)
By Use EncryptDataSource the query with text column is not convert correctly

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/31396902/64663070-2ba8e400-d47d-11e9-8fbb-a0f5867132b4.png)
![image](https://user-images.githubusercontent.com/31396902/64663314-f6e95c80-d47d-11e9-9fa1-6669272ee011.png)
![image](https://user-images.githubusercontent.com/31396902/64663327-036db500-d47e-11e9-8eee-fd30f260859a.png)
![image](https://user-images.githubusercontent.com/31396902/64663362-20a28380-d47e-11e9-83c3-b08233eca033.png)
![image](https://user-images.githubusercontent.com/31396902/64663380-2bf5af00-d47e-11e9-924b-b980aca06d78.png)

**Comment by Keanhua** [comment]
this is my ddl sql ，with text column it occurs error
![image](https://user-images.githubusercontent.com/31396902/64746849-c0741600-d53f-11e9-9c39-131a9db57dc7.png)

**Comment by sunbufu** [comment]
Can you give me an github example repository to find this issue's reason？

**Comment by tristaZero** [comment]
@Keanhua Hi, to make your issue recurred, i did some tests, but i can not get your exception.
Here some detail of my test, is it similar with yours?
#### Table description:
```
CREATE TABLE `t_encrypt` (
  `id` int(11) NOT NULL,
  `pwd` text,
  `pwd_query` varchar(255) DEFAULT NULL,
  `name` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
#### Encrypt rule
```
encryptRule:
  encryptors:
    encryptor_aes:
      type: AES
      props:
        aes.key.value: 1111
  tables:
    t_encrypt:
      columns:
        name:
          cipherColumn: name
          encryptor: encryptor_aes
```

#### SQL
> private static final String SELECT_SQL = "select pwd, name from t_encrypt ";
```
@Test
    public void testSelect() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery(SELECT_SQL);
            while (resultSet.next()) {
                System.out.println(resultSet.getString(1));
                System.out.println(resultSet.getString(2));
            }
        }
    }
```

**Comment by Keanhua** [comment]
@sunbufu @tristaZero 
this is the demo link:https://github.com/Keanhua/sharding-bug-demo
you can run the testCase directly, the error will occured。the sql is also in it.
if you change the longText cloumn type to json, it also occured

**Comment by tristaZero** [comment]
thanks for your demo, which gives us more chances to find the bug.
@Keanhua

**Comment by tristaZero** [comment]
@sunbufu Hi, are you interested in this issue? If it is available, the demo would be a good start. :)

**Comment by sunbufu** [comment]
@tristaZero Yes, I am interested in this. @Keanhua Thank you, I will try your demo later.

**Comment by KomachiSion** [comment]
The reason caused this problem is ShardingResultSet/EncryptResultSet get value accroding to the metadata. So we need to get value accroding to target type in StreamQueryResult.

But for MemoryQueryResult, ShardingSphere need to get value before users call getXXX method, so maybe transfer the value to target type in ShardingResultSet/EncryptResultSet.
