### ISSUE TITLE
maven build errors

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3019]
## Question
Got errors to build the project using maven followed the steps.
git clone https://github.com/apache/incubator-shardingsphere.git
mvn clean install -Prelease

errors:
![image](https://user-images.githubusercontent.com/48242833/64681235-e6eb7000-d4b1-11e9-84da-6ede85720c7b.png)

Is it due to the network problem  ?

**Comment by Keanhua** [comment]
i think you need to install the node.js environment

**Comment by beckhampu** [comment]
Hi @Myshiner , can you run 'npm install -X'  and show me the full debug logs ?

**Comment by beckhampu** [comment]
@Keanhua ，no need to install the Node  environment manually. We use the frontend-maven-plugin, and it can downloads/installs Node and NPM locally.

**Comment by Myshiner** [comment]
@beckhampu thx, please refer to the 'npm install -X' logs, yup it seems permission problem, but i run with root.
![image](https://user-images.githubusercontent.com/48242833/64752295-9fb4bc00-d551-11e9-83fd-c7a165d61904.png)

**Comment by Myshiner** [comment]
@beckhampu it's ok now, i just adjusted the directory permissions.
![image](https://user-images.githubusercontent.com/48242833/64753443-d68cd100-d555-11e9-93e2-91ebc3749762.png)

but the maven build still hang of.
[INFO] Running 'npm install' in C:\documents\ShardingSphere\incubator-shardingsphere\sharding-ui\sharding-ui-frontend

**Comment by beckhampu** [comment]
@Myshiner , sorry , it's my fault !  Run 'mvn clean install -Dmaven.test.skip=true -Prelease -X ' , not 'npm install -X'.

**Comment by beckhampu** [comment]
Hi @Myshiner , is there any progress ?

**Comment by Myshiner** [comment]
The previous process still running，and for now no error return, i will reply if get any error logs.
Thx.

**Comment by beckhampu** [comment]
@Myshiner , has your problem been solved? Can you give me some feedback? Thx！

**Comment by Myshiner** [comment]
trying to rebuild one more time, will let you know if finished .Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [apache/incubator-shardingsphere] maven build errors (#3019)From: chenqy To: apache/incubator-shardingsphere CC: Myshiner ,Mention @Myshiner , has your problem been solved? Can you give me some feedback? Thx！



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/apache/incubator-shardingsphere/issues/3019?email_source=notifications\u0026email_token=ALQCBEIBZSTN3FYOB6SF3YLQLBLYDA5CNFSM4IVQ5TN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7J3QYA#issuecomment-533968992",

"url": "https://github.com/apache/incubator-shardingsphere/issues/3019?email_source=notifications\u0026email_token=ALQCBEIBZSTN3FYOB6SF3YLQLBLYDA5CNFSM4IVQ5TN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7J3QYA#issuecomment-533968992",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by beckhampu** [comment]
@Myshiner ，Thx! Look forward to your results!

**Comment by terrymanu** [comment]
The CI can display all status for every build, it is ok now.
Closed for no response any more.
