### ISSUE TITLE
Error when using Clob type schema definitions

### ISSUE THREAD

**Issue by wangh09** [apache/incubator-shardingsphere#3022]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Successfully read from tables with columns of clob types ( with @Lob annotation).
### Actual behavior
Got the following error:
org.springframework.dao.InvalidDataAccessApiUsageException: java.lang.String cannot be cast to java.sql.Clob; nested exception is java.lang.IllegalArgumentException: java.lang.String cannot be cast to java.sql.Clob

The same code works for original DataSource from springboot.

**Comment by tuohai666** [comment]
Duplicate with #2956.
