### ISSUE TITLE
Default setting for KeyGenerator ColumnName and algorithm

### ISSUE THREAD

**Issue by rimal** [apache/incubator-shardingsphere#3031]
## Question

In my application, I am only doing database level sharding. There is no table level sharding. So, only setting the `DefaultDatabaseShardingStrategyConfig` works fine. But, if I want to use `snowflake` for key generation for my tables, I need to add `TableRuleConfiguration` for all my tables to specify the algorithm and the column name.

Is there anyway to set a default key generation config as well?

**Comment by rimal** [comment]
@terrymanu is there any current setting for this?

**Comment by geomonlin** [comment]
You can see the official documents carefully. There are detailed descriptions 
e.g:defaultKeyGenerator、keyGenerator https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-yaml/

**Comment by rimal** [comment]
@geomonlin Thanks for your reply. I found the setting in the doc but actually I am looking for a way in io.shardingsphere v3.1.0 . My bad, I should have mentioned this earlier.

**Comment by geomonlin** [comment]
> @geomonlin Thanks for your reply. I found the setting in the doc but actually I am looking for a way in io.shardingsphere v3.1.0 . My bad, I should have mentioned this earlier.

This is the official website.
https://shardingsphere.apache.org/
