### ISSUE TITLE
Can not find the table while the sharding key not transmit

### ISSUE THREAD

**Issue by harry-lianghairui** [apache/incubator-shardingsphere#3041]
the table user_buy  is shared into 16 tables as user_buy_{0..15}， sharding key is uid， the version:4.0.0-RC1  can not word while uid not transmit.
UserBuy db = new UserBuy();
db.setBuyOrderId(4902l);
db.setUid(11587537l); //transmit uid has no problem， but don't work while not transmit
List userBuys = userBuyDao.findList(db);

### problem:
com.duowan.udb.exception.DataAccessException: get SQLException error
--- The error occurred while applying a parameter map.
--- Check the UserBuy.findList-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'hq_goods.user_buy' doesn't exist

but it works at the version 1.4.1 when use in the groupId com.dangdang
version：·
	    <dependency>  
	        <groupId>com.dangdang</groupId>  
		        <artifactId>sharding-jdbc-config-spring</artifactId>  
		        <version>1.4.1</version>  
		    </dependency>  
	     <dependency>  
		        <groupId>com.dangdang</groupId>  
		        <artifactId>sharding-jdbc-config-common</artifactId>  
		        <version>1.4.1</version>  
	      </dependency>
		<dependency>
			<groupId>commons-dbcp</groupId>
			<artifactId>commons-dbcp</artifactId>
			<version>1.4</version>
		</dependency>

**Comment by harry-lianghairui** [comment]
Thank you so much!   I have solve the proble by the follow way:
it must config the attribute actual-data-nodes when do not transmit the sharding key

**Comment by sunbufu** [comment]
Can you try it with the last version (4.0.0-RC3-SNAPSHOT).

**Comment by sunbufu** [comment]
Oh, please try 4.0.0-RC2.

**Comment by terrymanu** [comment]
The version 1.x is too old, please update version 4.x
