### ISSUE TITLE
Can ShardingSphere only parse the specified subtables? Because there are INSERT...INTO statements in other tables

### ISSUE THREAD

**Issue by vulgar-cd** [apache/incubator-shardingsphere#3044]
Can ShardingSphere only parse the specified subtables? Because there are INSERT...INTO statements in other tables

**Comment by terrymanu** [comment]
Can you give a example for the SQL?

**Comment by geomonlin** [comment]
> ShardingSphere只能解析指定的子表吗？因为在其他表中有INSERT ... INTO语句
According to your routing rules to parse subtables.

**Comment by vulgar-cd** [comment]
> Can you give a example for the SQL?

I use two datasource to scan different mappers to let it work.
