### ISSUE TITLE
.net sharding-proxy 写报错

### ISSUE THREAD

**Issue by chenweihua** [apache/incubator-shardingsphere#3051]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### 环境配置如下：
schemaName: logistics_aftersales 

dataSources:
  ds_0:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_101?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_2:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_102?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_3:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_103?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_4:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_104?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_5:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_105?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_6:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_106?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_7:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_107?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_8:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_108?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_9:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_109?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_10:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_110?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_11:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_111?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_12:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_112?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_13:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_113?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_14:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_114?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_15:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_115?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_16:
    url: jdbc:mysql://172.16.7.15:3306/logistics_aftersales_116?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useSSL=false
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
shardingRule:
  tables:
    saleback_orderreturn:
      actualDataNodes: ds_${1..16}.saleback_orderreturn
    saleback_orderintercept:
      actualDataNodes: ds_${1..16}.saleback_orderintercept
    saleback_picklog:
      actualDataNodes: ds_${1..16}.saleback_picklog
    #salebacktask:
    #  actualDataNodes: ds_0.salebacktask
    #sequencebaseware:
    #  actualDataNodes: ds_0.sequencebaseware
  bindingTables:
    - saleback_picklog,saleback_orderintercept,saleback_orderreturn
  broadcastTables:
    - salebacktask,sequencebaseware
  defaultDataSourceName: ds_0
  defaultDatabaseStrategy:
    inline:
      shardingColumn: OpAreaId
      algorithmExpression: ds_${OpAreaId % 100}
  defaultTableStrategy:
    none:

数据库配置：
symbolic-links=0
character-set-client-handshake = FALSE
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
character_set_server=utf8mb4
init_connect='SET NAMES utf8mb4'
collation-server =  utf8mb4_general_ci

应用配置：
server=172.16.10.201;database=logistics_aftersales;uid=root;pwd=test;Pooling=true;Connection Lifetime=120;Connection Timeout=120;Character Set=utf8;Port=3307;Allow User Variables=True

错误：
The given key '33' was not present in the dictonary

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
