### ISSUE TITLE
How to execute "insert into on duplicate key update"

### ISSUE THREAD

**Issue by AndreyUS** [apache/incubator-shardingsphere#3074]
Hello.
Currently I have a problem with a query "insert into on duplicate key update".
The values in "on duplicate key update" section are ignored and exception thrown as I understated it will be fixed in RC3. 
For workaround I want to use procedure. 
Does library support calling procedure or function that will be executed on particular shard?

**Comment by terrymanu** [comment]
No, sharding with store procedure is too complicated and it is not a good practice on sharding databases. We have no plan to do that
