### ISSUE TITLE
Sharding  some tables, but don't sharding some other tables

### ISSUE THREAD

**Issue by xiangkaiy** [apache/incubator-shardingsphere#3078]
## Feature Request
All the example show how to do sharding tables to one db, or to several db, 
In some case, I need sharding some tables, but for some other tables, I don't need to sharding.
How do I configure in this case?

**Comment by dongzl** [comment]
Hi @xiangkaiy , I think you can describe your problem in more detail to help you solve it.

I understand only config the sharding tables in xml file, the other table don't need any configuration, use it directly.

**Comment by terrymanu** [comment]
Can you change the title more meaningful for search friendly?

**Comment by betterjava** [comment]
@xiangkaiy see my config for sharding-proxy below:
![image](https://user-images.githubusercontent.com/4453100/65575719-11a1f200-dfa3-11e9-8585-af201781cf93.png)

- user_shard: you can config a shard table like it.
- user_no_shard: you can config a no shard table like it.
- defaultDataSourceName:  tables have not been configed will use defaultDataSourceName.

**Comment by terrymanu** [comment]
Closed until change title to more meaningful.
