### ISSUE TITLE
After the service restarts, the request is time-consuming in a short time

### ISSUE THREAD

**Issue by zcjhwl** [apache/incubator-shardingsphere#3083]
I am using sharding-jdbc  4.0.0-RC1.
```
      <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
        <version>4.0.0-RC1</version>
      </dependency>
```
question
      Online problem, every time you restart the project, after a successful restart, a request will appear in the persistence layer for a short time, such as 20 seconds. It takes a long time to appear, and then it will return to normal. At that time, the QPS is stable and the database connection is sufficient.

configuration
- spring.shardingsphere.datasource.ds0.type = com.zaxxer.hikari.HikariDataSource
- spring.shardingsphere.datasource.ds0.driver-class-name = com.mysql.jdbc.Driver
- spring.shardingsphere.datasource.ds0.maximum-pool-size = 100
- spring.shardingsphere.datasource.ds0.minimum-idle = 50
- spring.shardingsphere.datasource.ds0.connection-init-sql = SET NAMES utf8mb4

 help

**Comment by terrymanu** [comment]
Can you change the title to search friendly?

**Comment by zcjhwl** [comment]
I'm sorry

**Comment by zcjhwl** [comment]
> Can you change the title more meaningful for search friendly?

I'm sorry

**Comment by terrymanu** [comment]
Title may describe the problem summary. For this title, reader also can not get point of title. 
Help to something should as a type of the issue, maybe you can use label to mark it, and change the title more meaning for real problem description.

**Comment by Ah39** [comment]
https://github.com/apache/incubator-shardingsphere/issues/2793
may because the parse progress

**Comment by zcjhwl** [comment]
> #2793
> may because the parse progress
> AntlrParsingEngine.parse()

thank you

**Comment by beiwangnull** [comment]
@terrymanu @zcjhwl   It's going to be faster

@Component
public class PreHeating implements InitializingBean {
    @Override
    public void afterPropertiesSet() throws Exception {
        Collection<DatabaseType> databaseTypes = SQLParserFactory.getAddOnDatabaseTypes();
        for (DatabaseType databaseType:databaseTypes){
            if("MySQL".equals(databaseType.getName())){
                SQLParseEngine parseEngine = SQLParseEngineFactory.getSQLParseEngine(databaseType);
                parseEngine.parse("select 'X'",true);
                MySQLParser mySQLParser = (MySQLParser)SQLParserFactory.newInstance(databaseType,"select 'X'");
                mySQLParser.execute();
            }
        }
    }

**Comment by codingIsCrazy** [comment]
> @terrymanu @zcjhwl It's going to be faster
> 
> @component
> public class PreHeating implements InitializingBean {
> @override
> public void afterPropertiesSet() throws Exception {
> Collection databaseTypes = SQLParserFactory.getAddOnDatabaseTypes();
> for (DatabaseType databaseType:databaseTypes){
> if("MySQL".equals(databaseType.getName())){
> SQLParseEngine parseEngine = SQLParseEngineFactory.getSQLParseEngine(databaseType);
> parseEngine.parse("select 'X'",true);
> MySQLParser mySQLParser = (MySQLParser)SQLParserFactory.newInstance(databaseType,"select 'X'");
> mySQLParser.execute();
> }
> }
> }

this "getAddOnDatabaseTypes" is not exist
