### ISSUE TITLE
Question regarding reference tables

### ISSUE THREAD

**Issue by jdeegan** [apache/incubator-shardingsphere#3094]
I am trying test how reference (broadcast) tables operate with Sharding-JDBC. 

More specifically, I want to test if a record is inserted into one reference table, will it automatically update all the reference tables in all the shards, or does each shard have to be manipulated separately when it comes to broadcast tables.

**Comment by betterjava** [comment]
If you execute insert sql for broadcast tables with Sharding-JDBC,this sql will execute in each shard node. Execute in each shard, not sync one shard to others.
Is this the answer you want?

**Comment by terrymanu** [comment]
Closed for no response any more.
