### ISSUE TITLE
ConfigCenter should replace RegistryCenter in some places.

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#3095]
### These class should be modified.

- org.apache.shardingsphere.shardingjdbc.orchestration.util.TestRegistryCenter
- org.apache.shardingsphere.shardingjdbc.orchestration.spring.boot.registry.TestRegistryCenter
- org.apache.shardingsphere.shardingjdbc.orchestration.spring.registry.TestRegistryCenter
- org.apache.shardingsphere.ui.servcie.RegistryCenterService
- org.apache.shardingsphere.ui.servcie.impl.RegistryCenterServiceImpl
- org.apache.shardingsphere.ui.util.RegistryCenterFactory

### Some of these class should be modified.

- org.apache.shardingsphere.orchestration.internal.registry.config.listener.AuthenticationChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.ConfigurationChangedListenerManager
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.PropertiesChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.SchemaChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.service.ConfigurationService
- org.apache.shardingsphere.orchestration.internal.registry.listener.PostShardingOrchestrationEventListener
- org.apache.shardingsphere.orchestration.internal.registry.listener.ShardingOrchestrationListenerManager
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.DataSourceStateChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.InstanceStateChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.StateChangedListenerManager
- org.apache.shardingsphere.orchestration.internal.registry.state.service.StateService
 
#### These five classes should be modified.
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.AuthenticationChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.ConfigurationChangedListenerManager
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.PropertiesChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.listener.SchemaChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.config.service.ConfigurationService
#### These two may be I should copy a new one for ConfigCenter.
- org.apache.shardingsphere.orchestration.internal.registry.listener.PostShardingOrchestrationEventListener
- org.apache.shardingsphere.orchestration.internal.registry.listener.ShardingOrchestrationListenerManager
#### These four will be kept , not change.
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.DataSourceStateChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.InstanceStateChangedListener
- org.apache.shardingsphere.orchestration.internal.registry.state.listener.StateChangedListenerManager
- org.apache.shardingsphere.orchestration.internal.registry.state.service.StateService

**Comment by wgy8283335** [comment]
@terrymanu.As this modification is complicated. After class is modified, code in the caller of the class may need to be modified. In case of modification causing errors, I'd like to commit modified class one by one, that means there will be about 10 merge requests for this issue. Do you agree with me?

**Comment by terrymanu** [comment]
yes, it is better to decrease risk for huge pull request.

**Comment by dongzl** [comment]
Hi @wgy8283335 , I want to integrate Apollo into ShadingSphere as a config center implemention, the issue is #3162 .

I want to konw that the interface definition about `org.apache.shardingsphere.orchestration.config.api.ConfigCenter` refactor completed?

will the interface definition have a huge change or not ?

**Comment by wgy8283335** [comment]
@dongzl ，Hi, the definition of the config center interface has been completed. But, the related function has been modifing yet, such as:
`org.apache.shardingsphere.orchestration.internal.registry.config.listener.AuthenticationChangedListener`,
`org.apache.shardingsphere.orchestration.internal.registry.config.listener.ConfigurationChangedListenerManager`, and so on.
I suggest that you could start to code the implemention class and unit tests. But, you can't use the class in the appliaction until the
whole "sharding-orchestration" module has been modified.

**Comment by dongzl** [comment]
@wgy8283335 Hi, I have a question about `org.apache.shardingsphere.orchestration.config.api.ConfigCenter` interface, and want to discuss with you.

I think some method about this interface is not defined for a common configuration system, eg: getChildrenKeys()、close(), a common configuration system dose not provide relationship between keys and don't need close, of course, we can throw `UnsupportedOperationException`. 

But I think these methods are only suitable for ZooKeeper, so dose this interface define properly?

**Comment by wgy8283335** [comment]
@dongzl  Ok, could you explain the definition of the interface?  Which method is suggested to be deleted, and which should be modified or kept?

**Comment by dongzl** [comment]
Hi @wgy8283335 , Although some methods don't need implemention for other configuration system, but they are suitable for ZooKeeper. So I don't know how to fix this interface definition properly. Maybe `throw UnsupportedOperationException` is the best way.

Do we open a new issue to discuss this question or in WeChat?

**Comment by wgy8283335** [comment]
Thank you. @dongzl you could open a new issue. And provide implementation class of config center, such as : apollo and any other implementation. List method of the class, and then we could discuss which method  is common used and which is only for a particular implementation class. Will you? It's a good time to make config center better.

**Comment by dongzl** [comment]
> Thank you. @dongzl you could open a new issue. And provide implementation class of config center, such as : apollo and any other implementation. List method of the class, and then we could discuss which method is common used and which is only for a particular implementation class. Will you? It's a good time to make config center better.

Hi @wgy8283335 , OK, I will do it.

I just submit a PR to ShardingSphere a moment ago, and I am waiting the code review, when ShardingSphere give me a feedback, I will open a issue to discuss this question according to the feedback.
