### ISSUE TITLE
Springboot condition bug

### ISSUE THREAD

**Issue by xin497668869** [apache/incubator-shardingsphere#3096]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
branch dev 
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 

### Expected behavior
in class 
org.apache.shardingsphere.shardingjdbc.spring.boot.sharding.ShardingRuleCondition

it should be 
```
    return isMasterSlaveRule || isEncryptRule ? ConditionOutcome.match("Have found master-slave or encrypt rule in environment") : ConditionOutcome.noMatch();
```
### Actual behavior
```
    return isMasterSlaveRule || isEncryptRule ? ConditionOutcome.noMatch("Have found master-slave or encrypt rule in environment") : ConditionOutcome.match();
```

**Comment by terrymanu** [comment]
Any reason for close this issue?
