### ISSUE TITLE
Got 8 hours offset due to the serverTimezone setting in sharding-proxy is different from the mysql server timezone

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3105]
project: sharding-proxy
version: v3.1.0
question:
The serverTimezone is set to UTC in sharding-proxy, and the variable system_time_zone is set to CST and time_zone is SYSTEM in mysql server, i have a table which include a timestamp column by default value current_timestamp, when i insert a value by default from sharing-proxy, i got the value is 8 hours offset. But this case didn't appear inevitably.
example:
table structure: create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP

the sharding-proxy serverTimezone: 
url: jdbc:mysql://10.10.0.193:4306/neworiental_user?serverTimezone=UTC&useSSL=false
the timezone in mysql server:
![image](https://user-images.githubusercontent.com/48242833/65507345-545ebe00-df00-11e9-98fe-fc20213fd51b.png)

**Comment by Myshiner** [comment]
Do i need set to a same timezone both in sharding-proxy and mysql server ?

**Comment by dongzl** [comment]
Hi @Myshiner , I use the lastest version sharding-proxy, not found this problem, you can upgrade and try it.

**Comment by Myshiner** [comment]
I mean if the mysql server system_time_zone is set to CST, the sharding-proxy serverTimezone also have been set to CST ? coz now the configure is UTC for sharding-proxy.

**Comment by dongzl** [comment]
> I mean if the mysql server system_time_zone is set to CST, the sharding-proxy serverTimezone also have been set to CST ? coz now the configure is UTC for sharding-proxy.

my environment, MySQL: CST, sharding-proxy url parameter: UTC, sharding-proxy version: lastest version, not found this problem.

**Comment by terrymanu** [comment]
@Myshiner Can you try version 4.x? Because 3.x is not apache release, we won't maintenance anymore.
