### ISSUE TITLE
配置绑定表报错

### ISSUE THREAD

**Issue by liubo-tech** [apache/incubator-shardingsphere#3118]
配置绑定表后，报空指针错误

![image](https://user-images.githubusercontent.com/16205161/65665485-3747fd80-e06e-11e9-90c7-af344e1701f0.png)
应先加载 广播表，  再加载绑定表，   
判断绑定表是否为广播表时， 加上非空判断。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
