### ISSUE TITLE
HintManager Of Version 4.0.0.RC2 Can‘t Work Under Multi DataSource Scenes

### ISSUE THREAD

**Issue by zdmwww** [apache/incubator-shardingsphere#3119]
### Which version of ShardingSphere did you use?
4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 

### Expected behavior
HintManager Of Version 4.0.0.RC2 Can Work Under Multi DataSource Scenes

### Actual behavior

```java
    public void setDatabaseShardingValue(Comparable<?> value) {
        this.databaseShardingValues.clear();
        this.databaseShardingValues.put("", value);
        this.databaseShardingOnly = true;
    }
```
 
Firstly, Can't Set Mutiti DataSource With method，because  this.databaseShardingValues.clear(); will cear the last value.

for example,I write this:
hintManager.setDatabaseShardingValue("shard-1");
hintManager.setDatabaseShardingValue("shard-2");

the "shard-1" will be cleared.

Sencondly, When I was implements HintShardingAlgorithm<String> By 
Manual setting the availableTargetNames With multi datasource，It doesn't work correctly。

For example ，I have four  sharding datasources:shard-1,shard-2,shard-3,shard-4;
When I write this hint sharing algorithm :

```java
@Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<String> shardingValue) {

     //TODO  for muti datasource test
     Collection<String> result = new HashSet<>();
     result.add("shard-1");
     result.add("shard-2");
    return result;
}
```

A record XXXX is  shard-1 but not in  shard-2, But the shardinjdbc query result is empty。
SQLLog print both shard-1 and shard-2 route result but without no correct query result.

Looking forward to your answer ， Thanks！！！

### Reason analyze (If you can)

I try this in  3.1.0 version , it can works 。

**Comment by zdmwww** [comment]
from the source code,
In version 3.1.0, ShardingPreparedStatement.getResultSet() has the code:


```
 if (this.routeResult.getSqlStatement() instanceof **SelectStatement** || this.routeResult.getSqlStatement() instanceof DALStatement) {
                MergeEngine mergeEngine = MergeEngineFactory.newInstance(this.connection.getShardingContext().getDatabaseType(), this.connection.getShardingContext().getShardingRule(), this.routeResult.getSqlStatement(), this.connection.getShardingContext().getMetaData().getTable(), queryResults);

                this.currentResultSet = new ShardingResultSet(resultSets, mergeEngine.merge(), this);
            }
```

But in version 4.0.0-RC2, the code  is like this:
 
```
 if (this.sqlRouteResult.getOptimizedStatement() instanceof **ShardingSelectOptimizedStatement** || this.sqlRouteResult.getOptimizedStatement().getSQLStatement() instanceof DALStatement) {
                MergeEngine mergeEngine = MergeEngineFactory.newInstance(this.connection.getRuntimeContext().getDatabaseType(), (ShardingRule)this.connection.getRuntimeContext().getRule(), this.sqlRouteResult, this.connection.getRuntimeContext().getMetaData().getTable(), queryResults);
                this.currentResultSet = this.getCurrentResultSet(resultSets, mergeEngine);
            }
```

ShardingSelectOptimizedStatement  in 4.0.0-RC2 is different from SelectStatement In version 3.1.0, May  be this is problem.

In version 4.0.0-RC2, The ShardingRouterFactory   is Like this:

```
public final class ShardingRouterFactory {
    public static ShardingRouter newInstance(ShardingRule shardingRule, ShardingMetaData shardingMetaData, DatabaseType databaseType, boolean showSQL) {
        return (ShardingRouter)(HintManagerHolder.isDatabaseShardingOnly() ? new DatabaseHintSQLRouter(shardingRule, showSQL) : new ParsingSQLRouter(shardingRule, shardingMetaData, databaseType, showSQL));
    }

    private ShardingRouterFactory() {
    }
}
```

When use the HintManager set shardingvalue, the isDatabaseShardingOnly has been set to true,
So will create DatabaseHintSQLRouter and  the sqlStatement is TransparentOptimizedStatement ,So the result can't be merged ，So HintManger can't support multi datasource In version 4.0.0-RC2。

DatabaseHintSQLRouter.Java:

```
    public SQLRouteResult route(String logicSQL, List<Object> parameters, SQLStatement sqlStatement) {
        SQLRouteResult result = new SQLRouteResult(new **TransparentOptimizedStatement**(sqlStatement));
        RoutingResult routingResult = (new DatabaseHintRoutingEngine(this.shardingRule.getShardingDataSourceNames().getDataSourceNames(), (HintShardingStrategy)this.shardingRule.getDefaultDatabaseShardingStrategy())).route();
        result.setRoutingResult(routingResult);
        return result;
    }
```

**Comment by terrymanu** [comment]
During your code fragment is hard to know what happened, can you provide source code?

**Comment by sunbufu** [comment]
Sorry, I didn't get your point. Why not just set `hintManager.setDatabaseShardingValue("shard-1");` If you want to use `shard-1`.

**Comment by zdmwww** [comment]
> Sorry, I didn't get your point. Why not just set `hintManager.setDatabaseShardingValue("shard-1");` If you want to use `shard-1`.

But if I wan to use both `shard-1` and  `shard-2`  at the same time, hintManager doesn't surport this?
I means that a sql will route to two databases and  merge the results correctly。

**Comment by sunbufu** [comment]
Maybe you should look at [hint example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/other-feature-example/hint-example) first. In sharding, `HintManager` work with `HintShardingAlgorithm` interface, and you can implement it with your algorithm same like [ModuloHintShardingAlgorithm.java](https://github.com/apache/incubator-shardingsphere-example/blob/dev/sharding-jdbc-example/other-feature-example/hint-example/hint-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/hint/raw/jdbc/ModuloHintShardingAlgorithm.java).

**Comment by zdmwww** [comment]
I has read the hint example and write code like ModuloHintShardingAlgorithm.java.But when the 

> 
doSharding() 
> 
method return more than one databases，the query result is not correct, It will not be paged correctly and sort correctly.

**Comment by sunbufu** [comment]
Can you create a git repository and show your issue?

**Comment by terrymanu** [comment]
No response anymore, let me close this issue
