### ISSUE TITLE
I found an error in the official document

### ISSUE THREAD

**Issue by HongJinFeng** [apache/incubator-shardingsphere#3126]
Document link:https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/encrypt/
![image](https://user-images.githubusercontent.com/33616750/65734877-a160b100-e107-11e9-9240-31681e84fee3.png)
This word should be column but not comlum.

**Comment by terrymanu** [comment]
Can you pull request?

**Comment by haetao** [comment]
we fixed this error.

**Comment by haetao** [comment]
fixed it. issue link:  https://github.com/apache/incubator-shardingsphere/issues/3126
document link:  https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/encrypt/
