### ISSUE TITLE
Is it possible to use data masking feature with all sql statement supported in shardless scenario? 

### ISSUE THREAD

**Issue by airarara** [apache/incubator-shardingsphere#3130]
It's very appreciated for providing data masking feature to security sensitive application! 
But after reading the documents and sources, I'm a little bit curious.
It seems that applications of which adopted data masking could not get all sql statement supported even they don't use any of sharding features.
e.g. in SELECT X union SELECT Y pattern, the secondary statement is parsed but not get executed at all.
Could you clarify if it is ture? 
And is it possible that you would provide a full sql supported masking feature to shardless application?

Thank you very much.

**Comment by terrymanu** [comment]
Not yet, the SQL parse module need to understand subquery first.
Right now the SQL parse module only can pass subquery

**Comment by terrymanu** [comment]
We will continuously improve SQL parse module, it is not a short goal, so I just close this issue.
