### ISSUE TITLE
java.sql.SQLException: No value specified for parameter

### ISSUE THREAD

**Issue by niuniu9631** [apache/incubator-shardingsphere#3136]
version:shardingJDBC(4.0.0-RC2)  
execute SQL with function(UNIX_TIMESTAMP) 
insert into tb_user (id, name, add_time_unix)  values (?, ?,UNIX_TIMESTAMP(?));
java.sql.SQLException: No value specified for parameter 3
set sql.show configuration is true. I see the Actual SQL 
insert into tb_user (id, login_name, add_time_unix)  values (?, ?);

**Comment by niuniu9631** [comment]
used UNIX_TIMESTAMP(now()) is ok

**Comment by terrymanu** [comment]
The issue caused by parse parameter marker from complicated expression error.

**Comment by terrymanu** [comment]
Does anybody want to do it?

**Comment by SteNicholas** [comment]
@terrymanu I want do this issue.

**Comment by SteNicholas** [comment]
@niuniu9631 Your issue exception has already solved in PR#3331.You can refer to this pull request.
