### ISSUE TITLE
sharding-jdbc batch insert Native memory allocation (mmap) failed to map 

### ISSUE THREAD

**Issue by Zhangkaiqiang** [apache/incubator-shardingsphere#3140]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by Zhangkaiqiang** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:sharding="http://shardingsphere.apache.org/schema/shardingsphere/sharding"
       xmlns:bean="http://www.springframework.org/schema/util"
       xmlns:mvc="http://www.springframework.org/schema/mvc"  
       xmlns:aop="http://www.springframework.org/schema/aop"  
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                        http://www.springframework.org/schema/beans/spring-beans.xsd 
                        http://www.springframework.org/schema/tx 
                        http://www.springframework.org/schema/tx/spring-tx.xsd
                        http://www.springframework.org/schema/context 
                        http://www.springframework.org/schema/context/spring-context.xsd
                        http://shardingsphere.apache.org/schema/shardingsphere/sharding
                        http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd
                        http://www.springframework.org/schema/mvc    
                        http://www.springframework.org/schema/mvc/spring-mvc-4.0.xsd
                        http://www.springframework.org/schema/aop 
                        http://www.springframework.org/schema/aop/spring-aop.xsd">
	
	<context:component-scan base-package="com.douyin" />
	
	<bean
		class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="locations">
			<list>
				<value>classpath:jdbc.properties</value>
				<value>classpath:redis.properties</value>
				<value>classpath:mq.properties</value>
			</list>
		</property>
	</bean>
	    
    <bean:properties id="properties">
        <prop key="worker.id">123</prop>
    </bean:properties>
    <bean id="recordIdStandardStrategy" class="com.douyin.table.split.strategy.DateStandardStrategy"/>
    <sharding:complex-strategy algorithm-ref="recordIdStandardStrategy" sharding-columns="record_time" id="complexStrategy"/>
    <sharding:standard-strategy id="shardingRecordIdStandardStrategy" precise-algorithm-ref="recordIdStandardStrategy" sharding-column="record_id" range-algorithm-ref=""/>
    <sharding:standard-strategy  id="shardingDateStandardStrategy" range-algorithm-ref="recordIdStandardStrategy" precise-algorithm-ref="recordIdStandardStrategy" sharding-column="create_time"/>
    <sharding:key-generator id="orderKeyGenerator" type="SNOWFLAKE" column="create_time" props-ref="properties" />
     <sharding:inline-strategy id="orderTableStrategy" sharding-column="create_time" algorithm-expression="pb_import_info_$->{order_id % 2}" />
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="demo_ds">
            <sharding:table-rules>
            	<sharding:table-rule logic-table="pb_import_info" actual-data-nodes="demo_ds.pb_import_info_$->{0..11}" table-strategy-ref="complexStrategy" key-generator-ref="orderKeyGenerator" />
            	
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="pb_import_info"/>
            </sharding:binding-table-rules>

        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>
	
    <bean id="demo_ds" class="com.alibaba.druid.pool.DruidDataSource"
          init-method="init" destroy-method="close">
        <property name="driverClassName" value="${jdbc.driver}" />
        <property name="url" value="${jdbc.url}" />
        <property name="username" value="${jdbc.username}" />
        <property name="password" value="${jdbc.password}" />
        
        <property name="initialSize" value="5" />
        <property name="maxActive" value="200" />
        
        <property name="minIdle" value="3" />
        <property name="testWhileIdle" value="true" />
        <property name="testOnBorrow" value="false" />
        <property name="testOnReturn" value="false" />
        <property name="validationQuery" value="select 1" />
        <property name="timeBetweenEvictionRunsMillis" value="20000" />
        <property name="numTestsPerEvictionRun" value="100" />
        <property name="filters" value="stat" /> 
    	 
    	   <property name="proxyFilters">
            <list>
                <ref bean="stat-filter"/>
            </list>
        </property>
        </bean>
     <bean id="stat-filter" class="com.alibaba.druid.filter.stat.StatFilter">
        
        <property name="slowSqlMillis" value="200"/>
        <property name="logSlowSql" value="true"/>
    </bean>

	
	<bean id="transactionManager"
		class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="shardingDataSource" />
	</bean>

	
	<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="shardingDataSource" />
		
		<property name="mapperLocations" value="classpath:com/douyin/mapping/*.xml"></property>
	</bean>

	<bean id="sqlSession" class="org.mybatis.spring.SqlSessionTemplate">
		<constructor-arg index="0" ref="sqlSessionFactory" />
	</bean>

	
	<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="basePackage" value="com.douyin.dao" />
		<property name="sqlSessionFactoryBeanName" value="sqlSessionFactory"></property>
	</bean>

	<bean id="SpringApplicationContext" class="com.douyin.util.ApplicationContextHelper"></bean>

	
	<tx:annotation-driven />



</beans>


@Override
	public Collection<String> doSharding(Collection<String> availableTargetNames,
			ComplexKeysShardingValue<String> shardingValue) {
		// TODO Auto-generated method stub
		Map<String,Collection<String>> map = shardingValue.getColumnNameAndShardingValuesMap();
		Map<String,Range<String>> rangeMap = shardingValue.getColumnNameAndRangeValuesMap();
		Collection<String> result = Lists.newArrayList();
		Calendar calendar = Calendar.getInstance();
		if(!MapUtils.isEmpty(map)) {
			for(String key : map.keySet()) {
				if("record_time".equals(key)) {
					Collection<String> recordTimeSet = map.get(key);
					for(String recordTime : recordTimeSet) {
						Date date = DateUtil.parse(recordTime);
						result.add(TableConstants.PB_IMPORT_INFO.concat(getTableByRecordTime(date).toString()));
					}
					
				}
			}
		}
		if(!MapUtils.isEmpty(rangeMap)) {
			for(String key : rangeMap.keySet()) {
				if("record_time".equals(key)){
					Range<String> range =  rangeMap.get(key);
					Date startTime = DateUtil.parse(range.lowerEndpoint());
					Date endTime = DateUtil.parse(range.upperEndpoint());
					if(startTime.equals(endTime)) {
						result.add(TableConstants.PB_IMPORT_INFO.concat(getTableByRecordTime(startTime).toString()));
					}else {
						while(startTime.before(endTime)) {
							result.add(TableConstants.PB_IMPORT_INFO.concat(getTableByRecordTime(startTime).toString()));
							calendar.setTime(startTime);
							calendar.add(Calendar.DAY_OF_WEEK, 1);
							startTime = calendar.getTime();
						}
					}

				}
			}
		}
		return result;
	}

**Comment by Zhangkaiqiang** [comment]
pom文件
	
	<dependency>
	    <groupId>io.shardingjdbc</groupId>
	    <artifactId>sharding-jdbc-core</artifactId>
	    <version>2.0.0.M1</version>
	</dependency>
      <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC2</version>
        </dependency>

**Comment by Zhangkaiqiang** [comment]
<insert id="insertInfoList" parameterType="map">
    	insert into pb_import_info (user_id,user_code,user_nick,time_long,day,get_point,record_id,create_time,admin_id,record_time)
        values
        <foreach collection ="list" item="info" separator="," >
            (#{info.userId},#{info.userCode},#{info.userNick},#{info.timeLong},
            #{info.day}, #{info.getPoint}, #{info.recordId},#{info.createTime},#{info.adminId},#{info.recordTime}
            )
        </foreach>
    </insert>

**Comment by terrymanu** [comment]
Did you mean you use `sharding-jdbc-core` as version `2.0.0.M1`, but use `sharding-jdbc-spring-namespace` as version `4.0.0-RC2`?

**Comment by Zhangkaiqiang** [comment]
> Did you mean you use `sharding-jdbc-core` as version `2.0.0.M1`, but use `sharding-jdbc-spring-namespace` as version `4.0.0-RC2`?
I don't mean that.above is my project configuration,when i batch insert records ,the memory corruption(2G-40000records) ,I don‘t whats wrong with me

**Comment by Zhangkaiqiang** [comment]
> Did you mean you use `sharding-jdbc-core` as version `2.0.0.M1`, but use `sharding-jdbc-spring-namespace` as version `4.0.0-RC2`?

I don't mean that.above is my project configuration,when i batch insert records ,the memory corruption(2G-40000records) ,I don‘t whats wrong with me

**Comment by Zhangkaiqiang** [comment]
done change pom
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-core</artifactId>
    <version>4.0.0-RC2</version>
</dependency>
      <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.0-RC2</version>
        </dependency>
