### ISSUE TITLE
Failover Support

### ISSUE THREAD

**Issue by KennyQiao** [apache/incubator-shardingsphere#3141]
@terrymanu @tristaZero 

**Do you guys have any development plan on supporting failover?**

I saw an old comment [here](https://github.com/apache/incubator-shardingsphere/issues/874#issuecomment-391936668), but it has been more than one year.

Any feedback will be greatly appreciate.

**Comment by terrymanu** [comment]
No plan for us. Any body want as volunteer to do it?

**Comment by KennyQiao** [comment]
Fine, thanks for your comment. 😢

**Comment by tristaZero** [comment]
Hi,
Failover automatically is a practical feature i think.

Currently, any changes on zk will be synchronized to apps online. So the key point is `who` can tell the zk all the new rules, e.g new ip and port.
What's more, Monitoring the status of dbs is another topic.


If anyone is interested in them, i hope you can join us to help community. Thanks :)






 Juan Pan


panjuan@apache.org
Juan Pan(Trista), Apache ShardingSphere
On 09/27/2019 16:53, Kenny Qiao wrote:

Fine, thanks for your comment. 😢

**Comment by terrymanu** [comment]
Closed for now. If somebody want do this feature, please talk with mailing-list or reopen this issue.
