### ISSUE TITLE
It show me "Can not update sharding key"， but my sharding key does not update, the sharding key value does not change, only just appears in the updated clause.

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#3144]
## Bug Report

It show me "Can not update sharding key"， but my sharding key does not update, the sharding key value does not change, only just appears in the updated clause.

### Which version of ShardingSphere did you use?
4.0.0-RC3-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 

### Expected behavior

Cause: org.apache.shardingsphere.core.exception.ShardingException: Can not update sharding key, logic table: [cust_contact_sharding], column: [org.apache.shardingsphere.core.parse.sql.segment.dml.assignment.AssignmentSegment...

### Actual behavior
no exception and update successfully

### Reason analyze (If you can)

If the value of the sharding key does not really changed, such sql execution should be allowed

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

**sharding key is unique_id**
sql：
update cust_contact_sharding **SET unique_id = ?**, contact_name = ?  where id = ? and **unique_id = ?** 
param:
Parameters: **a538e445280443e997f76b5657dd3f27**(String), 钳(String),  104501(Long), **a538e445280443e997f76b5657dd3f27**(String)

### Example codes for reproduce this issue (such as a github link).

![image](https://user-images.githubusercontent.com/8772975/65763922-01327880-e157-11e9-944b-dd326ab58cf9.png)

**Comment by betterjava** [comment]
Hi, @xiyelife According to my understanding, this is not a problem, still thank you for actively submitting the issue.

**Comment by xiyelife** [comment]
@betterjava  yeah , I can solve this problem by modifying my sql. but for mybatis framework generated sqls  could have this problem

**Comment by betterjava** [comment]
I understand, you are right, maybe this requires more discussion.

**Comment by wanghaichao2195** [comment]
I have the same issue [https://github.com/apache/shardingsphere/issues/5596](url)
please take a look, thanks a lot!
