### ISSUE TITLE
help for mock static method when unit test

### ISSUE THREAD

**Issue by sluk3r** [apache/incubator-shardingsphere#3149]
Hi, all. would you help me with that problem: how can I mock static method when unit test. 

I try to unit test the following code: 

```java 
public LogicSchema(final String name, final Map<String, YamlDataSourceParameter> dataSources) {
        this.name = name;
        parseEngine = SQLParseEngineFactory.getSQLParseEngine(LogicSchemas.getInstance().getDatabaseType());
        backendDataSource = new JDBCBackendDataSource(dataSources);
        ShardingOrchestrationEventBus.getInstance().register(this);
}
```

And find that there are two static method invocation, mockito doesn't support static method mock. 

after some google, I found Powermock can mock static method easily, example is: https://java2blog.com/mockito-mock-static-method/

So, should I import Powermock into ss？ Or is there some mature  experience  for mock static method?

**Comment by terrymanu** [comment]
For my understanding, use lots of static fields should be avoid for design reason.

If you want focus unit test, how about add test cases without static fields?

**Comment by sunbufu** [comment]
If you must do it, maybe reflection is a good choice.
