### ISSUE TITLE
Data masking: the name of logicColumn is case sensitive

### ISSUE THREAD

**Issue by skyoxZ** [apache/incubator-shardingsphere#3154]
Is it possible to configure this behavior?

**Comment by skyoxZ** [comment]
> Hi @skyoxZ ,I'm not sure what problems you encountered, could you describe them in more detail?

For example, when the logicColumn is configured as "id_card", a business SQL with column "ID_CARD" will not work.

**Comment by yanyzy** [comment]
Hi @skyoxZ  
I think the logical column case should be consistent with sql. because some databases are case sensitive, such as mysql. plaintext columns and ciphertext columns are real columns,  maintaining the unification of the three may be clearer.

**Comment by skyoxZ** [comment]
@yanyzy Sometimes there's no guarantee about the column case in SQLs so that it's hard to keep the logical column case consistent. If other components of Sharding support case-insensitive situation, why Data Masking not?

**Comment by gaoguanghai** [comment]
Hi @yanyzy ,Before data masking, the user can use the column name a or A to operate the database to get the correct result, but it will not work with data masking, and the user will be surprised why not, so I personally think whether case-sensitive should be consistent with the database.

**Comment by terrymanu** [comment]
this issue is a minor changes, I closed because nobody want to collect this issue.
