### ISSUE TITLE
Postgres errorCode error message no response JDBC and CLI client. PostgreSQLErrorResponsePacket no response error Info

### ISSUE THREAD

**Issue by bxvs888** [apache/incubator-shardingsphere#3156]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

Postgres errorCode error message no response JDBC and CLI client. PostgreSQLErrorResponsePacket no response error Info

**Comment by terrymanu** [comment]
Which version of ShardingSphere did you use?

**Comment by bxvs888** [comment]
> Which version of ShardingSphere did you use?
ShardingSphere proxy RC2

**Comment by sluk3r** [comment]
I am glad to handle this issue

**Comment by sluk3r** [comment]
@bxvs888   could you please give the example codes for reproduce this issue, or main point. 
and the related logs

**Comment by sluk3r** [comment]
@bxvs888  and the version of Postgres

**Comment by bxvs888** [comment]
Postgres 10 ,11

**Comment by avalon566** [comment]
Duplicate with #3129 , I've fixed CLI no response issue, I am glad to fix other no error response issue.
