### ISSUE TITLE
ShardingSphere Config Center implemention for Apollo.

### ISSUE THREAD

**Issue by dongzl** [apache/incubator-shardingsphere#3162]
## Feature Request
I want to integrate Apollo to ShardingSphere，for another registry center implemention. 

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
I want to integrate Apollo into ShardingSphere，for another registry center implemention. Now I  am working for this work and already completed some functions, but I meet some problem and want to discuss in this issue.
**First:**
Apollo provide two ways to integrate：**apollo-client** and **apollo-openapi**
**apollo-client** can get value data with key, and monitor keys change. But it don't provide interface for modify data with key.
 **apollo-openapi** is Apollo's Restful style interface, it can get and modify data with key, but not  monitor keys change.
so I want to integrate **apollo-client** and **apollo-openapi** into ShardingSphere together.
Does this is a good way to complete this work.

**Second:**
I understand Apollo only a distributed configuration center, it don't like ZooKeeper, not provide lock implementation, so some method about lock in `RegistryCenter` interface, I don't have a good way to implement them.
How can I implement these method with a good way?

**Comment by terrymanu** [comment]
Thank you for pay attention for this feature.

For Question 1: 

I never use Apollo before, it sounds strange about `apollo-client` and `apollo-openapi` which only provide part of core features. Can you talk with Apollo team first to make sure what is the best practice of Apollo?

For Question 2:

We have already split `RegistryCenter` and  `ConfigCenter`, Apollo is suitable for `ConfigCenter` only. You can find `ConfigCenter` by full class name  `org.apache.shardingsphere.orchestration.config.api.ConfigCenter`

**Comment by terrymanu** [comment]
The config center do not finish yet, please have a look at: https://github.com/apache/incubator-shardingsphere/issues/3095

**Comment by dongzl** [comment]
Hi @terrymanu , Thank you very much.
I will discuss with Apollo team and find more details, and will pay attention to `ConfigCenter`.

**Comment by dongzl** [comment]
Hi @terrymanu, I have communicated with Apollo team, they think read config and modify config design for different roles, so they split the Apollo API.

For read config API design for application system, it is high availability, and it is not any limit.

But for modify config API design for other config system to sync configuration to Apollo, it need token validation and must have modify config rights, they think modify config must be very careful, if operate error, it make a mistake for application system.

So they split the Apollo API. 
`apollo-client` is for application system，it provide read config API and monitor config change API;
`apollo-openapi` is for other config system, it provide read config API and modify config API.

This is the discuss issue: https://github.com/ctripcorp/apollo/issues/2635

In ShardingSphere `org.apache.shardingsphere.orchestration.config.api.ConfigCenter` interface have read and modify API. I think we still have to integrate the two client API. Do you have other suggestions?

**Comment by terrymanu** [comment]
We can throw UnsupportedException if user call update method with Apollo
