### ISSUE TITLE
如何配置全库中所有表一样的分库规则

### ISSUE THREAD

**Issue by zhuyaoming** [apache/incubator-shardingsphere#3179]
我在使用shardingjdbc的过程中,库中几百+表,每个表中都包含我的sharding-column,而且我每个表的分片规则都是一样的.是否我需要每个表去独立配置呢. 
如果后续我新增表也得同步去配置这些一样的分片规则么?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
