### ISSUE TITLE
Method of dynamically adding data sources

### ISSUE THREAD

**Issue by zhuyaoming** [apache/incubator-shardingsphere#3180]
Fragment 3 libraries, this time need to add to 5 libraries, this time you must modify the code to achieve it? Can you add it dynamically, do not need to restart the application.
      分片3个库,这个时候需要添加到5个库,这个时候必须修改代码才能实现么?能否动态添加呢,不需要重启应用呢.

**Comment by terrymanu** [comment]
Can you make English more understanding and remove Chinese words?

**Comment by terrymanu** [comment]
Please create new issue if you want discuss and make sure English can be understand, thank you.

**Comment by 852675742** [comment]
i have the same question,now because our datasource config is dead write in config yaml file,can program dynamic config the datasource by listener outside order？
