### ISSUE TITLE
<sharding:standard-strategy /> sharding-column is must  but I want to split the db by table name。not column 

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-shardingsphere#3190]
<sharding:standard-strategy />  sharding-column is must

but I want to split the db by table name。not column 。What I need to do?

**Comment by terrymanu** [comment]
Can you change the title more meaningful for search friendly? Title may describe the problem summary.

**Comment by terrymanu** [comment]
How to split the db by table name?

**Comment by lonyee1989** [comment]
It is recommended to divide the database through the table content identification field. If the database is divided according to the table name, it should be multi-database, rather than the shard of the database.
