### ISSUE TITLE
Data masking or encryption for Oracle can not work well.

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#3194]
Please see this thread for more detail. 
This thread explains the reason and gives the solution. 
If anyone is interested in this bugfix, please reply this thread or this issue. Hope see your Pr later. 😃 
> https://lists.apache.org/thread.html/b040322a2bbddd4994ab0829b85ed79b94036e5d82716d81993d0d4f@%3Cdev.shardingsphere.apache.org%3E

**Comment by tianbin1001** [comment]
add dcl createUser parse #4119
