### ISSUE TITLE
Do you support spring boot 1.2?

### ISSUE THREAD

**Issue by songwb** [apache/incubator-shardingsphere#3195]
## Do you support spring boot 1.2?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Can you try to example first?

**Comment by songwb** [comment]
ok. thanks . I will give it a try.
