### ISSUE TITLE
jar dependency conflict

### ISSUE THREAD

**Issue by zhiyoucai** [apache/incubator-shardingsphere#3196]
I find that some jar package conflict.

I solve this problem like the configuration below:

```groovy
compile('org.apache.shardingsphere:sharding-jdbc-orchestration-spring-boot-starter:4.0.0-RC2') {
        exclude group: 'org.apache.curator', module: 'curator-framework'
  }
compile('org.apache.shardingsphere:sharding-orchestration-reg-zookeeper-curator:4.0.0-RC2') {
        exclude group: 'org.apache.curator', module: 'curator-framework'
        exclude group: 'org.apache.curator', module: 'curator-recipes'
        exclude group: 'org.apache.curator', module: 'curator-client'
}
compile group: 'org.apache.curator', name: 'curator-framework', version: '2.10.0'
compile group: 'org.apache.curator', name: 'curator-recipes', version: '2.10.0'
```

something wrong with orchestration

**Comment by RaigorJiang** [comment]
let me try to fix it.

**Comment by RaigorJiang** [comment]
Hi， @zhiyoucai, @terrymanu 
I studied with SS 4.0.0-RC2 and 4.0.0-RC3-SNAPSHOT,  but I did not find any package-related conflicts for Curator (there are some duplicate dependencies, and they are automatically omitted). 
Can you describe the conflicting scenes?   

<img width="934" alt="WX20191021-154714@2x" src="https://user-images.githubusercontent.com/5668787/67186228-3bbbc800-f41a-11e9-9d5e-51bcf3cbb38f.png">

**Comment by terrymanu** [comment]
It seems @zhiyoucai use gradle to handle dependency.
Maybe you can try with gradle

**Comment by RaigorJiang** [comment]
OK, I will try.

**Comment by RaigorJiang** [comment]
Hi, terrymanu,
I used gradle to test compilation with 'sharding-orchestration-reg-zookeeper-curator' (RC2 & RC3) witch based on spring-boot 1.5.16 and 2.1.0 respectively,  all of them can be  builded successful and no conflicts are there.

![WX20191022-163823](https://user-images.githubusercontent.com/5668787/67271092-77bf5d80-f4ec-11e9-87a0-d540676d1af1.png)

![WX20191022-164513](https://user-images.githubusercontent.com/5668787/67271126-84dc4c80-f4ec-11e9-8e0f-1f3b5c265a3e.png)

I think that may be @zhiyoucai  his other dependencies brought conflicts.
