### ISSUE TITLE
Statement "SELECT GET_LOCK('lock10086')" doesn't work as  expected

### ISSUE THREAD

**Issue by liusf1993** [apache/incubator-shardingsphere#3211]
```
SELECT GET_LOCK('lock10086',1000);
SELECT RELEASE_LOCK('lock10086');
```
while executing two statements above, UnicastRoutingEngine was chosen because not logic tables is empty.
And the first statement may be executed on database db1, second on database db2, resulting that the lock is not freed.
Can you support an option for using DefaultDatabaseRoutingEngine while no logic table exists.

**Comment by terrymanu** [comment]
What is your version?

**Comment by liusf1993** [comment]
> What is your version?

shardingsphere : 4.0.0-RC2
mysql: mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
java: java version "1.8.0_201"

**Comment by terrymanu** [comment]
What is your expected action to using lock in a sharding databases? just lock all of the table?

**Comment by liusf1993** [comment]
> What is your expected action to using lock in a sharding databases? just lock all of the table?
> 
> Using lock with ShardingSphere is not a good practice, because ShardingSphere on Sharding is for horizontal split. If you want use distribute lock, maybe you can try zookeeper.

I'm integrating Shardingsphere into an old application. The lock is worked in another dependent jar related to db, and it's just a distributed lock for intializing. To keep the jar pure, we don't want to introduce another jar like zookeeper or redis for a distribute lock in the jar at moment.  Keeping the lock and release work on the same database is just ok for us at moment.

**Comment by terrymanu** [comment]
Distribute solution is not Silver Bullet, please refactor old system towards distribute solution.

**Comment by liusf1993** [comment]
> Distribute solution is not Silver Bullet, please refactor old system towards distribute solution.

Firstly, I don't think db lock on the same database is not a distribute solution, although it may not be the best solution in most cases.


Then, let's skip the distribute lock.
The case that database partition is only required for some special tables exists, which means all other tables being in a default or primary database, sql with no tables is the same. `default-data-source-name` is worked for the case on other tables,  if support for no table is added,  the function of `default-data-source-name` can be better.

**Comment by terrymanu** [comment]
Do we talk about horizontal sharding?

**Comment by liusf1993** [comment]
> Do we talk about horizontal sharding?

I'm sorry for using inappropriatethe case, which made us be involed into distributed lock.
Let me describle my case agnin:
I have two db `db1` and `db2`.  `db1` ows table `t1`,`t2`,`t3`, function `f1`,  and  `db2` only onws `t2`. 
Only table  `t2` was in partition, so I want sql related to  `t1` , `t3`, `f1` to be executed on db1, only `t2` be executed on `db1` and `db2` according to it's condition. I use the configuration `spring.shardingsphere.sharding.default-data-source-name`, now sql related to  `t1` or 't3` was executed on `d1` as expected, but `f2`'s execution was in random.
My point is on adding default database support for sql without tables.

**Comment by terrymanu** [comment]
This is make sense, can you close this issue and open a new issue to talk about it?
Because the title and content of this issue is mismatched.

**Comment by liusf1993** [comment]
> This is make sense, can you close this issue and open a new issue to talk about it?
> Because the title and content of this issue is mismatched.

Okay!

**Comment by liusf1993** [comment]
> > This is make sense, can you close this issue and open a new issue to talk about it?
> > Because the title and content of this issue is mismatched.
> 
> Okay!
New issue #3273
