### ISSUE TITLE
how to use all table in one db use the same sharding rule

### ISSUE THREAD

**Issue by zhuyaoming** [apache/incubator-shardingsphere#3212]
need to config ervery tables? if my tables have 100+  its so difficult to config. can use common config?

**Comment by terrymanu** [comment]
100+ tables may not very difficult to config, it is only config one time.

**Comment by zhuyaoming** [comment]
> 100+ tables may not very difficult to config, it is only config one time.
every table to config? all table have the same rule.

**Comment by terrymanu** [comment]
The question is same as: 

`
I have 100+ tables and all structure of tables are same, but they just have different table names.
Can I use one DDL SQL to create all this 100+ tables?
`

So I just close this issue and label it as invalid.

**Comment by zhuyaoming** [comment]
> 100+ tables may not very difficult to config, it is only config one time.


> The question is same as:
> 
> `I have 100+ tables and all structure of tables are same, but they just have different table names. Can I use one DDL SQL to create all this 100+ tables?`
> 
> So I just close this issue and label it as invalid.

The table structure is different, but the sharding rule is the same as a field sharding.
