### ISSUE TITLE
SQL execution is slow under sub-database sub-table

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#3215]
The following SQL sub-database sub-table query is very slow, nearly 1.5s, why? But it only takes a few milliseconds to execute in mysql.

Ic_sku_channel_inventory unique index(`sku_code`,`warehouse_code`,`first_channel`,`second_channel`),

`select id,first_channel, sku_code, version,second_channel,warehouse_code,warehouse_type, 
inventory_num, normal_inventory_num, damage_inventory_num, locked_num, normal_locked_num, damage_locked_num, 
transit_num,is_disable,is_deleted 
from ic_sku_channel_inventory 
where ( (sku_code in ( '1131378',
'724351', 
'724350', 
'724595', 
'724239', 
'721764', 
'721761', 
'724358', 
'719607', 
'717306', 
'717307', 
'717305', 
'723692', 
'721192', 
'721394',
'723693', 
'724544', 
'721743', 
'717299', 
'719757', 
'1134588', 
'1134584', 
'724334', 
'721582', 
'724298', 
'1133778', 
'721544', 
'724335', 
'724654', 
'1145841', 
'724606', 
'724528', 
'724605', 
'717881', 
'724526', 
'724603', 
'726788', 
'724288', 
'721411', 
'724602', 
'724601', 
'724600', 
'721377', 
'724319', 
'723427', 
'724516', 
'721007', 
'721128', 
'721766', 
'721528')
         AND warehouse_code = 'jtwlhz' AND first_channel='909900' AND second_channel = '0' ) 
       or (sku_code in ( '721745' ) AND warehouse_code = 'jtwlhz' AND first_channel='909900' AND second_channel = '909902') );
`
![AA7DCE78-5A00-4043-8636-1EC407E9138B](https://user-images.githubusercontent.com/25191518/66575472-8b8fc900-eba8-11e9-978a-d2324d1394eb.png)

**Comment by terrymanu** [comment]
What is `sub-database`?

**Comment by terrymanu** [comment]
What is your configuration and log with sql.slow?

**Comment by xfyang1989** [comment]
the version 4.0.0-RC2,  The parameter (sql.slow)  is set to false.
A lot of similar SQL is slow, causing severe performance degradation, I suspect that the trackingspehere SQL parsing is very slow

**Comment by xfyang1989** [comment]
This is mysql execution time
![{89392B63-E470-46F0-9F18-4344EBF28009}_20191011093803](https://user-images.githubusercontent.com/25191518/66618301-346f1000-ec0b-11e9-8133-01a53841aa3c.jpg)

**Comment by terrymanu** [comment]
If care about performance, please use parameter marker instead of inline literals.

**Comment by xfyang1989** [comment]
> If care about performance, please use parameter marker instead of inline literals.

Is there a sample, for example? Now many online queries are two or three seconds? Is there a better way?

**Comment by terrymanu** [comment]
Using SQL like this way:

```sql
select id,first_channel, sku_code, version,second_channel,warehouse_code,warehouse_type, inventory_num, normal_inventory_num, damage_inventory_num, locked_num, normal_locked_num, damage_locked_num, transit_num,is_disable,is_deleted from ic_sku_channel_inventory where ( (sku_code in ( ?, ?) AND warehouse_code = ? AND first_channel=? AND second_channel = ?) or (sku_code in ( ?) AND warehouse_code = ? AND first_channel=? AND second_channel = ?) );
```

**Comment by xfyang1989** [comment]
Every time the first query like this SQL is very slow, the second time may be due to the underlying cache.
I am using parameter marker ,like this :
![{EB7BA170-E110-4782-B4FC-4FF116E55A77}_20191011135554](https://user-images.githubusercontent.com/25191518/66627656-00a5e180-ec2f-11e9-862e-81a97c0b257c.jpg)

![{8412DF94-06B8-4516-8BB4-3639BD8E3C4C}_20191011135735](https://user-images.githubusercontent.com/25191518/66627757-406cc900-ec2f-11e9-983e-30cef1cefea9.jpg)

**Comment by xfyang1989** [comment]
Database connection pool is HikariCP

**Comment by xfyang1989** [comment]
I understand, it may be my sql dynamic, causing the sharingspehere to think that every time the new sql will be initialized and loaded once, no previous cache is used.

**Comment by terrymanu** [comment]
Yes, you get the point
