### ISSUE TITLE
use Hit  insert exception 

### ISSUE THREAD

**Issue by fangxianhlhh** [apache/incubator-shardingsphere#3219]
## Question
when user Hit  insert has exception,
No problem with other database operations

java.lang.ClassCastException: org.apache.shardingsphere.core.optimize.transparent.statement.TransparentOptimizedStatement cannot be cast to org.apache.shardingsphere.core.optimize.sharding.statement.dml.ShardingInsertOptimizedStatement

Why？ How to solve it?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
What is your version? What is your configuration and log with sql.slow?

**Comment by terrymanu** [comment]
Did you mean Hint? Can you change fix the typo?

**Comment by betterjava** [comment]
> What is your version? What is your configuration and log with sql.slow?

What is your version? What is your configuration and log with sql.**show**?

**Comment by fangxianhlhh** [comment]
Thank you for your reply. I use  shardingsphere  version 4.0.0-RC2，mybatisplus version3.1.0,springBoot version 2.1.3.

The problem has been solved. The table primary key uses self-increasing primary key and is modified to “SNOWFLAKE” algorithm generation. The problem has been solved.

Thank you!
