### ISSUE TITLE
shardingsphere proxy 4.0.0-RC3-SNAPSHOT   JDBC execute SQL report org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask - Exception occur:  java.lang.IndexOutOfBoundsException: readerIndex(22) + length(2) exceeds writerIndex(23): PooledSlicedByteBuf(ridx: 22, widx: 23, cap: 23/23, unwrapped: 

### ISSUE THREAD

**Issue by bxvs888** [apache/incubator-shardingsphere#3233]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

10:26:19.032 [pool-5-thread-1] ERROR org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask - Exception occur: 
java.lang.IndexOutOfBoundsException: readerIndex(22) + length(2) exceeds writerIndex(23): PooledSlicedByteBuf(ridx: 22, widx: 23, cap: 23/23, unwrapped: PooledUnsafeDirectByteBuf(ridx: 94, widx: 94, cap: 496))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:726) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at org.apache.shardingsphere.shardingproxy.transport.postgresql.payload.PostgreSQLPacketPayload.readInt2(PostgreSQLPacketPayload.java:62) ~[sharding-proxy-transport-postgresql-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.transport.postgresql.packet.command.query.binary.bind.PostgreSQLComBindPacket.<init>(PostgreSQLComBindPacket.java:64) ~[sharding-proxy-transport-postgresql-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.transport.postgresql.packet.command.PostgreSQLCommandPacketFactory.newInstance(PostgreSQLCommandPacketFactory.java:59) ~[sharding-proxy-transport-postgresql-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.PostgreSQLCommandExecuteEngine.getCommandPacket(PostgreSQLCommandExecuteEngine.java:56) ~[sharding-proxy-frontend-postgresql-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.PostgreSQLCommandExecuteEngine.getCommandPacket(PostgreSQLCommandExecuteEngine.java:47) ~[sharding-proxy-frontend-postgresql-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:84) ~[sharding-proxy-frontend-core-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66) [sharding-proxy-frontend-core-4.0.0-RC3-SNAPSHOT.jar:4.0.0-RC3-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by dongzl** [comment]
Hi @bxvs888 , can you provide more details, such as  your configuration、SQL、code and so on.

**Comment by bxvs888** [comment]
@dongzl 
spring jdbc  postgres 
driver: postgresql-42.2.8.jar
jdbc config:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:3307/CHL_WS_CMD
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: ACMHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

execute SQL : SELECT ID,NAME, dict_code  FROM API_DICT WHERE ID=? OR ID=?  

ShardingSphere  rule config:
bindingTables:
- api_dict
masterSlaveRules:
  DS_01:
    loadBalanceAlgorithmType: ROUND_ROBIN
    masterDataSourceName: DS_00_01
    slaveDataSourceNames:
    - DS_00_02
  DS_02:
    loadBalanceAlgorithmType: ROUND_ROBIN
    masterDataSourceName: DS_01_02
    slaveDataSourceNames:
    - DS_01_01
tables:
  api_dict:
    actualDataNodes: DS_01.api_dict,DS_02.api_dict
    databaseStrategy:
      standard:
        preciseAlgorithmClassName: com.apsaras.shardingsphere.algorithm.HashRangeAlgorithm
        shardingColumn: dict_code

**Comment by bxvs888** [comment]
public final class PostgreSQLComBindPacket extends PostgreSQLCommandPacket {
    
    private final String statementId;
    
    private final String sql;
    
    private final List<Object> parameters;
    
    private final boolean binaryRowData;
    
    public PostgreSQLComBindPacket(final PostgreSQLPacketPayload payload, final int connectionId) throws SQLException {
        payload.readInt4();
        payload.readStringNul();
        statementId = payload.readStringNul();
        int parameterFormatsLength = payload.readInt2();
        for (int i = 0; i < parameterFormatsLength; i++) {
            payload.readInt2();
        }
        PostgreSQLBinaryStatement binaryStatement = BinaryStatementRegistry.getInstance().get(connectionId).getBinaryStatement(statementId);
        sql = null == binaryStatement ? null : binaryStatement.getSql();
        parameters = null == sql ? Collections.emptyList() : getParameters(payload, binaryStatement.getParameterTypes());

      //经排查，这里少了一字节，不知道被那里吃掉了。
        int resultFormatsLength = payload.readInt2();
        binaryRowData = resultFormatsLength > 0;
        for (int i = 0; i < resultFormatsLength; i++) {
            payload.readInt2();
        }
    }

**Comment by bxvs888** [comment]
ERROR this method ,read Parameter first parameter OK , read two Parametr err.  

private List<Object> getParameters(final PostgreSQLPacketPayload payload, final List<PostgreSQLBinaryStatementParameterType> parameterTypes) throws SQLException {
        int parametersCount = payload.readInt2();
        List<Object> result = new ArrayList<>(parametersCount);
        for (int parameterIndex = 0; parameterIndex < parametersCount; parameterIndex++) {
           int m= payload.readInt4();
             System.out.println("parameter:="+m);
            PostgreSQLBinaryProtocolValue binaryProtocolValue = PostgreSQLBinaryProtocolValueFactory.getBinaryProtocolValue(parameterTypes.get(parameterIndex).getColumnType());
            result.add(binaryProtocolValue.read(payload));
        }
        return result;
    }

**Comment by bxvs888** [comment]
public final class PostgreSQLStringBinaryProtocolValue implements PostgreSQLBinaryProtocolValue {
    
    @Override
    public int getColumnLength(final Object value) {
        return value.toString().length();
    }
    
    @Override
    public Object read(final PostgreSQLPacketPayload payload) {
//错在这里，读时没有指定长度。
        return payload.readStringNul();
    }

    //public final class PostgreSQLStringBinaryProtocolValue implements PostgreSQLBinaryProtocolValue {
    
    @Override
    public int getColumnLength(final Object value) {
        return value.toString().length();
    }
    
    @Override
    public Object read(final PostgreSQLPacketPayload payload) {
        return payload.readStringNul();
    }

     @Override
     public Object read(PostgreSQLPacketPayload payload, int len) throws SQLException {
         byte[] result = new byte[len];
         payload.getByteBuf().readBytes(result);
        return  new String(result);
    }
    @Override
    public void write(final PostgreSQLPacketPayload payload, final Object value) {
        if (value instanceof byte[]) {
            payload.writeBytes((byte[]) value);
        } else {
            payload.writeStringEOF(value.toString());
        }
    }
}
   //加入新的方法。
     @Override
     public Object read(PostgreSQLPacketPayload payload, int len) throws SQLException {
         byte[] result = new byte[len];
         payload.getByteBuf().readBytes(result);
        return  new String(result);
    }
    @Override
    public void write(final PostgreSQLPacketPayload payload, final Object value) {
        if (value instanceof byte[]) {
            payload.writeBytes((byte[]) value);
        } else {
            payload.writeStringEOF(value.toString());
        }
    }
}

**Comment by dongzl** [comment]
Hi @bxvs888 , I think you can submit PR to ShardingSphere. ^_^

**Comment by bxvs888** [comment]
@dongzl  ^_^  submited

**Comment by terrymanu** [comment]
@bxvs888 Can you have a look on your pull request and try to solve the code review suggestion?

**Comment by terrymanu** [comment]
Fixed at #3344
