### ISSUE TITLE
When insert by mybatis, the parameters were still found to be out of ordered. 

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#3234]
### Which version of ShardingSphere did you use?
4.0.0-RC3-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
insert correct
### Actual behavior
When insert by mybatis, the parameters were still found to be out of ordered. 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

==> Preparing: insert into cust_contact_sharding (id,cust_id, unique_id, contact_name, contact_relation, contact_mobile, contact_address, time_inst, time_upd) values (?,?, ?, ?, ?, ?, ?, now() , ?)
==> Parameters: 117001(Long), 4(Long), 84719733d69047eba078e914c49488c7(String), 歉(String), TEST(String), 15907200513(String), 测试地址(String), null

sharding value 84719733d69047eba078e914c49488c7,value after sharding cust_contact_6
Rule Type: sharding
Logic SQL: insert into cust_contact_sharding (id,cust_id, unique_id, contact_name,
contact_relation, contact_mobile, contact_address,
time_inst, time_upd)
values (?,?, ?, ?,
?, ?, ?,
now() , ?)
ShardingSphere-SQL: SQLStatement: InsertSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.core.parse.sql.statement.dml.InsertStatement@1723c231, tablesContext=TablesContext(tables=[Table(name=cust_contact_sharding, alias=Optional.absent())], schema=Optional.absent())), columnNames=[id, cust_id, unique_id, contact_name, contact_relation, contact_mobile, contact_address, time_inst, time_upd], insertValueContexts=[InsertValueContext(parametersCount=8, valueExpressions=[ParameterMarkerExpressionSegment(startIndex=170, stopIndex=170, parameterMarkerIndex=0), ParameterMarkerExpressionSegment(startIndex=172, stopIndex=172, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=175, stopIndex=175, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=178, stopIndex=178, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=188, stopIndex=188, parameterMarkerIndex=4), ParameterMarkerExpressionSegment(startIndex=191, stopIndex=191, parameterMarkerIndex=5), ParameterMarkerExpressionSegment(startIndex=194, stopIndex=194, parameterMarkerIndex=6), CommonExpressionSegment(startIndex=205, stopIndex=209, text=now()), ParameterMarkerExpressionSegment(startIndex=213, stopIndex=213, parameterMarkerIndex=7), DerivedParameterMarkerExpressionSegment(super=ParameterMarkerExpressionSegment(startIndex=0, stopIndex=0, parameterMarkerIndex=8)), DerivedParameterMarkerExpressionSegment(super=ParameterMarkerExpressionSegment(startIndex=0, stopIndex=0, parameterMarkerIndex=9)), DerivedParameterMarkerExpressionSegment(super=ParameterMarkerExpressionSegment(startIndex=0, stopIndex=0, parameterMarkerIndex=10))], parameters=[117001, 4, 84719733d69047eba078e914c49488c7, 歉, TEST, 15907200513, 测试地址, null])])

Actual SQL: ds0
::: insert into cust_contact_6 (id,cust_id, unique_id, contact_name_enc,
contact_relation, contact_mobile_enc, contact_address_enc,
time_inst, time_upd, contact_name, **contact_mobile, contact_address**)
values (?, ?, ?, ?, ?, ?, ?, now(), ?, ?, ?, ?)
::: [117001, 4, 84719733d69047eba078e914c49488c7, *n08ZSeAE+q5GlnThhlUqhAg==,
TEST, *mJeSoexiPoMJYtc6tM8/Ggw==, *aBNIM+OZDMbR9FRHMUYeej7zfTz0WMhaq0pJfT0voBt2wpN0malEcyYDjuA18AO84GkUjtoaMHXEdfyLQZ5fo/g==,
null, 歉, **测试地址, 15907200513**]

_the follow parameter has been inverse:_
**contact_mobile, contact_address
测试地址, 15907200513**

**Comment by terrymanu** [comment]
Can you make sure your 4.0.0-RC3 is newest version?

**Comment by xiyelife** [comment]
@terrymanu  yes, I sync from apache/dev yesterday
the vesion is: https://github.com/xiyelife/incubator-shardingsphere
I will try to use the latest version ， thanks！

**Comment by terrymanu** [comment]
The test cases of encrypt are still combing, they are in 
https://github.com/terrymanu/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-rewrite/src/test/java/org/apache/shardingsphere/core/rewrite/feature/encrypt/EncryptSQLRewriteEngineTest.java

I will fix all encrypt's test cases on next pull request.

**Comment by xiyelife** [comment]
I just tested the latest version. I still have that problem.
yeah, this would be very good.

**Comment by terrymanu** [comment]
All test cases of encrypt are in `incubator-shardingsphere/sharding-core/sharding-core-rewrite/src/test/resources/encrypt`

This case is in `insert.xml` case id is `insert_values_for_parameters`

**Comment by terrymanu** [comment]
All test cases are related #1548

**Comment by xiyelife** [comment]
@terrymanu 
By using the latest version, I still find that the order of the parameters is wrong:
The generating logic for encrypting rewriting sql is to replace the original field with an encrypted fields，then append the original fields to the end of the sql
now，The sql is generated in sqltoken order in the inserted column like this:
[name_encrypt, ident_encrypt, mobile_encrypt, , **mobile, ident, name**, SQLToken(startIndex=269)]
**the order  in insert segment  is mobile、ident、name**
but the parameters are generated from high to low in the treeMap order(descendingMap) of addedIndexAndParameters
the original addedIndexAndParameters is:
** mobile、ident、name**
{17=[13505347525], 18=[600232419893887186], 19=[卓镂格]}
after desc ordered and calculated is：
13505347525, 卓镂格, 600232419893887186]
**mobile、name、ident**

**Original SQL:**
insert into user_info (cust_id, unique_id, name, 
      ident, mobile, password, 
      reg_time, modify_time, reg_source, 
      reg_app_channel, reg_device_info, status, 
      is_mobile_authed, complate_cust_info, time_inst, 
      time_upd, has_checked)
    values (?, ?, ?, 
      ?, ?, ?, 
      ?, ?, ?, 
      ?, ?, ?, 
      ?, ?,  ? , 
      ?, ?)
**Rewrited SQL:**
insert into user_info (cust_id, unique_id, name_encrypt, 
      ident_encrypt, mobile_encrypt, password, 
      reg_time, modify_time, reg_source, 
      reg_app_channel, reg_device_info, status, 
      is_mobile_authed, complate_cust_info, time_inst, 
      time_upd, has_checked, **mobile, ident, name**)
  values (?, ?, ?, 
?, ?, ?,
?, ?, ?,
?, ?, ?, 
?, ?, ?, 
?, ?, ?, ?, ?)

Rewrited Parametes:
**...mobile，name，ident**
...15000886422, 堵禊嚼, 600232419893631035]

I think, this causes the values stored in the database to be disordered!

code:
org.apache.shardingsphere.core.rewrite.parameter.builder.impl.StandardParameterBuilder
![image](https://user-images.githubusercontent.com/8772975/66743433-74a0ed80-eeac-11e9-8a15-3cf751896651.png)

**Comment by xiyelife** [comment]
he update still has this problem, too

**Comment by xiyelife** [comment]
when updating, the original value is replaced for the first time, the original value parameter is added to the new parameter list, the index of the encryption field and the original field is changed, and the parameter index of the next encryption field should be obtained from the changed parameters, instead of continuing to get it from the original list of parameters

**Comment by terrymanu** [comment]
Do we miss some test cases? can you add the test case into the xml?

If the test case can not run correctly, you can just comment it and label it as `FIXME`

**Comment by xiyelife** [comment]
The order of the field columns in the configured encryption rules must be consistent with the order in which the books are written in SQL, otherwise the SQL parameters rewite at the time of insertion will in disorded.

**Comment by xiyelife** [comment]
After checking and testing the code, I found that the problem was like this：
The order of the field columns in the configured encryption rules must be consistent with the order in which the code are written in SQL, otherwise the SQL parameters rewite at the time of insertion will be disordered.
**configured encryption rule:**
![image](https://user-images.githubusercontent.com/8772975/66805515-d36f7100-ef57-11e9-8181-a14d57973591.png)
**SQL:**:
input: the order is  password、 amout
INSERT INTO t_account(account_id, password, amount, status) VALUES (?, ?, ?, 'OK')
1, aaa, 1000
Actual:
INSERT INTO t_account(account_id, cipher_password, cipher_amount, status, password, amount) VALUES (?, ?, ?, 'OK', ?, ?)
[1, encrypt_aaa, encrypt_1000, 1000, aaa]
Expected:
INSERT INTO t_account(account_id, cipher_password, cipher_amount, status, password, amount) VALUES (?, ?, ?, 'OK', ?, ?)
[1, encrypt_aaa, encrypt_1000, aaa, 1000]

**Comment by xiyelife** [comment]
I recommend adding encryption tests for more than three fields.

**Comment by xiyelife** [comment]
@tristaZero  
I find that tristaZero has been fixed the insert without columns issue. Can you fix the columns together if the parameters of three or more columns are disordered?  And add three or more cipher colunms scenarios unit tests?
@terrymanu
I'll close my PR, because it involves the core logic, and I'am afraid that l make some new problem.

**Comment by terrymanu** [comment]
@xiyelife OK, I will add 3 columns for encrypt before finish this issue

**Comment by xiyelife** [comment]
@terrymanu 

INSERT INTO t_account(account_id, certificate_number, password, amount, status) VALUES...
the order ins sql is certificate_number、password、amount
![image](https://user-images.githubusercontent.com/8772975/67289292-f4fcc980-f510-11e9-88fd-f978a6e6ffb1.png)
the order in encryption rules is certificate_number、password、amount

**this case is ok!  
if the order ins sql is not 'certificate_number、password、amount' ， the order of this case is not ok!
We can not  guarantee that the order of columns in sql is consistent with the data in encryption rules.**
