### ISSUE TITLE
sharding-proxy 4.0 not support mysql 8.0?

### ISSUE THREAD

**Issue by dreamingo88** [apache/incubator-shardingsphere#3236]
we test sharding-proxy 4.0 rc2 with mysql 5.7 (1*master + 2*slaver), it works well.

but not works with mysql 8.0 (1*master + 2*slaver), our app (spring boot 2.x) always report error: "Unknown system variable 'query_cache_size‘“ when use mysql driver 5.1.4x. if upgrade mysql driver to 8.0.1x, it always report "cannot connection database".

is there any plan to support mysql 8.0?

**Comment by terrymanu** [comment]
Is it duplicate with #3097?

**Comment by tuohai666** [comment]
Duplicate with #3097.
