### ISSUE TITLE
SQL92 parse or expression have problem

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#3240]
When using sql92 to parse sql, the expression is error, but MySQL dialect is ok.

```sql
DELETE FROM t_cipher_assisted_query_plain WHERE encrypt_1 = ? or encrypt_2 IN (?,?,?)
```

It maybe cause by `OR`, we need to investigate it.

**Comment by tuohai666** [comment]
Yes, you are right, the problem is caused by OR.
The OR keyword should not appear in simpleExpr.
