### ISSUE TITLE
DATA MASKING--  Encrypt-JDBC couldn't not get decrypt information after execute select method

### ISSUE THREAD

**Issue by zzy97092236** [apache/incubator-shardingsphere#3255]
Properties props = new Properties();
        props.setProperty("aes.key.value", "123456");
        EncryptorRuleConfiguration encryptorConfig = new EncryptorRuleConfiguration("GMS", props);
        EncryptColumnRuleConfiguration columnConfig = new EncryptColumnRuleConfiguration("", "id_number_encypt", "", "aes");
        EncryptTableRuleConfiguration tableConfig = new EncryptTableRuleConfiguration(Collections.singletonMap("id_number", columnConfig));
        EncryptRuleConfiguration encryptRuleConfig = new EncryptRuleConfiguration();
        encryptRuleConfig.getEncryptors().put("aes", encryptorConfig);
        encryptRuleConfig.getTables().put("zzy_test_2018", tableConfig);

Is there anything else to configure?

**Comment by terrymanu** [comment]
What is your version and SQL?

**Comment by zzy97092236** [comment]
1、version
<version>4.0.0-RC2</version>
2、sql with SpringDataJPA
 2019-10-14 21:42:39.938  INFO 10868 --- [nio-9002-exec-1] ShardingSphere-SQL                       : SQL: select zzyinfo0_.id as id1_1_0_, zzyinfo0_.create_time as create_time2_1_0_, zzyinfo0_.create_user_id as create_user_id3_1_0_, zzyinfo0_.id_number_encypt as id_number4_1_0_, zzyinfo0_.update_time as update_time5_1_0_, zzyinfo0_.update_user_id as update_user_id6_1_0_, zzyinfo0_.user_name as user_name7_1_0_ from zzy_test_2018 zzyinfo0_ where zzyinfo0_.id=?
--
3、return with a Proxy
Method threw 'org.hibernate.HibernateException' exception. Cannot evaluate com.zm.update.jpa.domain.first.ZzyInfo$HibernateProxy$6kUWeQhC.toString() 

4、
![a](https://user-images.githubusercontent.com/56537799/66756491-b93c8100-eecc-11e9-8e73-2b41a2920420.png)
![b](https://user-images.githubusercontent.com/56537799/66756505-c2c5e900-eecc-11e9-9f24-8780f8e2dddd.png)

**Comment by terrymanu** [comment]
Can you provide full stack trace?
It seems like hibernate's exception

**Comment by zzy97092236** [comment]
it's now doesn't have any Exception,but the return value is still encrypted and a proxy. and the mybatis framework has the same problem.
![a](https://user-images.githubusercontent.com/56537799/66997223-a57b5f80-f104-11e9-9e6e-d0323dc7fa20.png)
![b](https://user-images.githubusercontent.com/56537799/66997227-a613f600-f104-11e9-994b-fcec933e9b70.png)

**Comment by yanyzy** [comment]
Hi @zzy97092236 ,
i tested it with `AES` ShardingEncryptor, and didn’t reproduce your situation. so is it possible that your `GMS` spi didn’t work well?

**Comment by zzy97092236** [comment]
> Hi @zzy97092236 ,
> i tested it with `AES` ShardingEncryptor, and didn’t reproduce your situation. so is it possible that your `GMS` spi didn’t work well?

 I also tested it with AES ShardingEncryptor ,could you share you code ?

**Comment by yanyzy** [comment]
@zzy97092236 
My demo is here [sharding-jdbc-demo](https://github.com/yanyzy/sharding-jdbc-demo), 
if you use it differently, you can also give me an example.

**Comment by terrymanu** [comment]
I just set label of this issue as invalid because it seems cannot reproduce.
We can keep focus on this issue until we make sure it is really cannot reproduce.

**Comment by zzy97092236** [comment]
version as follwo:
<version>4.0.0-RC2</version>
oracle 11.2.0.4.0  com.oracle.weblogic ojdbc7 12.1.3-0-0

**Comment by zzy97092236** [comment]
about this question,The query result should be plaintext. Now it is ciphertext. Is it normal?

![66756505-c2c5e900-eecc-11e9-9f24-8780f8e2dddd](https://user-images.githubusercontent.com/56537799/67374933-78232b80-f5b4-11e9-9e05-9c754859d14c.png)
![aHR0cHM6Ly9vc2NpbWcub3NjaGluYS5uZXQvb3NjbmV0LzM3NTczMThkZmJjM2M0OWY0N2UzOGZiMjA1YWZkZDRmOGQyLmpwZw](https://user-images.githubusercontent.com/56537799/67374942-7a858580-f5b4-11e9-8ceb-927d0bd4dcf4.png)

**Comment by yanyzy** [comment]
@zzy97092236 
The 4.0.0-RC2 version does have this problem for oracle, and it has been fixed. you can wait for the release of 4.0.0-RC3, or build source code to use 4.0.0-RC3-SNAPSHOT.
