### ISSUE TITLE
Provider Scaling out Interface

### ISSUE THREAD

**Issue by avalon566** [apache/incubator-shardingsphere#3256]
## Sequence diagram

![sequence diagram](http://www.plantuml.com/plantuml/svg/hP0nJiOm38NtdCBgpWKOq7y19jG3cCHjBQLsiHr1EJsHkaH8PMBpyBxdJ-_XWHPjhsbsCdXwWUajOsLPuHKzo2Pu1gEFHXv0NvHR47XF46YBz3jyK-2dvCrK-9kWO62ggWSq2QxmZiuTgEUGmc2L133DVb_QdMo420o34ab90tTTNU6J8szWX4MbFzkrqAWnzYmix1kL_p6utzD3Zn7_mziTiih2QxDhd0T9QNlz0G00)

## Feature
- [x] Create/Start Scaling job interface
- [x] Query Scaling job interface
    - [x] List all Scaling job interface
    - [x] Show scaling progress and detail #3617 
- [x] Stop/Delete Scaling job interface

**Comment by KomachiSion** [comment]
Reference #3077.

**Comment by ssxlulu** [comment]
In my opinion, Here are the http request apis:
1. `POST http://127.0.0.1:8080/shardingscaling/start` for starting jobs;
2. `GET http://127.0.0.1:8080/shardingscaling/progress/{job_id}` for query job progresses;
3. `DELETE http://127.0.0.1:8080/shardingscaling/stop/{job_Id}` for stopping jobs.

**Comment by KomachiSion** [comment]
In my opinion, the `stop` interface should not use DELETE method, because this interface only stop the scaling job.

What's more all interface can add `/job/` prefix like 
```
/shardingscaling/job/start [POST]
/shardingscaling/job/progress/${jobId} [GET]
/shardingscaling/job/stop [POST]
```

**Comment by ssxlulu** [comment]
> In my opinion, the `stop` interface should not use DELETE method, because this interface only stop the scaling job.
> 
> What's more all interface can add `/job/` prefix like
> 
> ```
> /shardingscaling/job/start [POST]
> /shardingscaling/job/progress/${jobId} [GET]
> /shardingscaling/job/stop [POST]
> ```

Agree. The apis will be these.

**Comment by ssxlulu** [comment]
Talk about the response body:
1. Start action's reponse body: 
```
{
    "message":"start job success!",
    "content":{
        "id":"0"
    }
}
```
2. Query progress's response body:
```
{
  "message": "get progress of the job success!",
  "content": {
    "id": "0",
    "job_name": "",
    "data_node_progress": [
      {
        "id": "{host}-{port}-{schema}",
        "stage": "prepare/history_data/realtime_data/stopped",
        "history_data_progress": [
          {
            "id": "{schema}-{table}-split#0",
            "expected_rows": 0,
            "sycned_rows": 0
          }
        ],
        "realtime_data_progress": {
          "id": "{schema}-realtime",
          "log_positon": 0,
          "delay_second": 0
        }
      }
    ]
  }
}
```
3. Stop action's response body:
```
{
    "message":"stop job success!",
    "content":""
}
```

**Comment by wqzwh** [comment]
In order to keep the interface data format unified, the following structure is recommended

```js
{
  errorCode: 0,
  errorMsg: null,
  model: {} // 主体数据
  success: true
}
```

**Comment by ssxlulu** [comment]
add interface for list all jobs:
```
/shardingscaling/job/list [GET]
```

**Comment by wqzwh** [comment]
UI hand drawing

![image](https://user-images.githubusercontent.com/16662470/71077765-084fac80-21c3-11ea-9345-a85eedfdf460.png)
![image](https://user-images.githubusercontent.com/16662470/71077484-78116780-21c2-11ea-8297-d7eba123d31e.png)
![image](https://user-images.githubusercontent.com/16662470/71077501-82336600-21c2-11ea-8240-ab6f4770d3cd.png)
