### ISSUE TITLE
 java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Intege

### ISSUE THREAD

**Issue by zbj1986** [apache/incubator-shardingsphere#3257]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
org.apache.shardingsphere
### Expected behavior
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? Integer.valueOf(parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex()).toString())
                :Integer.valueOf(((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue());
(ps: i have tested successfully)
### Actual behavior
return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment
                ? (int) parameters.get(((ParameterMarkerPaginationValueSegment) paginationValueSegment).getParameterIndex())
                : ((NumberLiteralPaginationValueSegment) paginationValueSegment).getValue();

the result is:
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination.getValue(Pagination.java:60)
	at org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination.<init>(Pagination.java:54)

### Reason analyze (If you can)
     I have used mybaitsplus ，and the parameters in the class of com.baomidou.mybatisplus.extension.plugins.pagination.Page  are all the type of long

**Comment by dongzl** [comment]
Hi @zbj1986 , I read ShardingSphere source code about pagination, I think this problem has already  been fixed, it will be include 4.0.0-RC3 version. You can focus on the RC3‘s release.

![image](https://user-images.githubusercontent.com/5917359/66794587-a6f62d80-ef34-11e9-8b21-8ca0dfca4f7a.png)

**Comment by alterhu2020** [comment]
@dongzl when this new version been release? It affects current project? thanks

**Comment by alwyngo** [comment]
All of the paging operations can't be used now, when the new version will be released?

**Comment by dongzl** [comment]
Hi @alterhu2020 @alwyngo , the RC3's release is under way, I think it will be released a few days later.

**Comment by Zakariyya** [comment]
Today, you can update the version to 4.1.0. It's working.
