### ISSUE TITLE
sharding-ui-frontend config file problem

### ISSUE THREAD

**Issue by wqzwh** [apache/incubator-shardingsphere#3265]
- [ ] 1. Allow the creation of new config. But when activated, you must check whether you can connect to ZK and whether there is a node on zk.

- [ ] 2. When multiple configs exist, one of them cannot be edited and must be deleted and recreated.

**Comment by wqzwh** [comment]
@beckhampu Can you provide mock service? if can debugging will be very convenient

**Comment by menghaoranss** [comment]
@wqzwh 
1. The latest version of sharding-ui already supports adding new config and registry centers, and when trying to activate the centers, it will check if zk connection is ok .
2. The function of editing an existing center, we will follow up.
3. what's the meaning of mock service that you mentioned above?

**Comment by wqzwh** [comment]
@menghaoranss 

1. Mock server is mainly for the convenience of front-end development and debugging

2. I can cooperate with you to finish the second task
