### ISSUE TITLE
Default database doesn't work on sql without tables

### ISSUE THREAD

**Issue by liusf1993** [apache/incubator-shardingsphere#3273]
My case is like this:
I have two db `db1` and `db2`.  `db1` ows table `t1`,`t2`,`t3`, function `f1`, and `db2` only onws `t2`. Only table `t2` was in partition, so I want sql related to `t1` , `t3`, `f1` to be executed on `db1`, only `t2` be executed on `db1` and `db2` according to it's condition value. I use the configuration `spring.shardingsphere.sharding.default-data-source-name`, now sql related to `t1` or `t3` was executed on `d1` as expected, but `f1`'s execution database was in random.  

The result I **expected** is like this,
```select 1 from t1;``` on db1
```select 1 from t3;``` on db1
**``` select f1;``` on db1**
```select 1 from t2;``` on db1,db2

The **actual** result is like this:
```select 1 from t1;``` on db1
```select 1 from t3;``` on db1
**``` select f1;``` on (db1 or db2 in random)**
```select 1 from t2;``` on db1,db2

**Comment by yhsmy** [comment]
paste your f1 sql here. 
maybe the function f1 you use can not be parse exactly.
I have just opened a issue yesterday.
https://github.com/apache/incubator-shardingsphere/issues/3247

**Comment by liusf1993** [comment]
> paste your f1 sql here.
> maybe the function f1 you use can not be parse exactly.
> I have just opened a issue yesterday.
> #3247

My case is a little different.
`f1` is just like `select now();`, 
There is no table in the sql, but I want the sql executed on default database `db1` instead of  a random db.

**Comment by yanickxia** [comment]
this seem should add  `perfect database` 🤔

**Comment by RaigorJiang** [comment]
I think it should be like this:
when the SQL dosn't have a table name
1:  in sharding,   route to the defaultDataSource;
2:  in master-slave, route to master or a slave which configred.

If you agree it , I can try to do this.

**Comment by terrymanu** [comment]
+1 for me. We can discuss more details.

1. Sharding
  1.1 With default data source, route to default data source
  1.2 Without default data source, unicast route(stay the same)
2. Master-slave
  2.1 route to master database (because slave is readonly, so route to slave maybe unnecessary)

**Comment by RaigorJiang** [comment]
OK,  I am about to do it.    @terrymanu

**Comment by terrymanu** [comment]
@RaigorJiang Thank you, assigned.
