### ISSUE TITLE
 sharding-proxy 能否通过直接修改sql语句的方式达到数据脱敏，不在数据源表添加加密字段

### ISSUE THREAD

**Issue by dynamohuang** [apache/incubator-shardingsphere#3274]
rt： sharding-proxy 能否通过直接修改sql语句的方式达到数据脱敏，不在数据源表添加加密字段
如
原生语句 ：select name from customer；
脱敏处理语句：select CONCAT(SUBSTRING(name,1,1),'O', SUBSTRING(name,3)) as name from customer；

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
