### ISSUE TITLE
shardingjdbc 在执行update语句报错

### ISSUE THREAD

**Issue by zhumaoliang** [apache/incubator-shardingsphere#3278]
[我配置了读写分离，在执行update] 语句时候出错，该语句中包含case when ，比如UPDATE
        OTS_ORDER
        SET
        UPDATE_DATE = now(),
        <if test="entity.updateBy!=null and entity.updateBy != ''">
            UPDATE_BY=#{entity.updateBy},
        </if>
		<![CDATA[ STATE = ((CASE WHEN (STATE is null) THEN 1 ELSE STATE+1 END)) ]]>
错误信息如下:
org.antlr.v4.runtime.tree.TerminalNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext

**Comment by dongzl** [comment]
Hi @zhumaoliang , **For English only**, other languages will not accept.

You should describe your problem in English again.
