### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3285]
Project: Sharding-proxy
Version: V3.1.0

## Question
Sharding-proxy always hung and then the application cant connect to it. And I can get some errors like following:
2019-10-16 02:10:11.486 [ ShardingSphere-Command-14 ] - [ INFO  ] [ ShardingSphere-SQL : 71 ] - SQL: set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_US
ER,NO_ENGINE_SUBSTITUTION' ::: DataSources: neworiental_okay_bi
2019-10-16 02:20:04.398 [ ShardingSphere-Command-5 ] - [ INFO  ] [ ShardingSphere-SQL : 71 ] - SQL: set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USE
R,NO_ENGINE_SUBSTITUTION' ::: DataSources: neworiental_okay_bi
**io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer**

Any advise ?

**Comment by Myshiner** [comment]
And sometimes its very slowly to connect to the sharding-proxy, but its fast when connect mysql, and the sharding-proxy & mysql running on the same machine.

**Comment by terrymanu** [comment]
Hello, version 3.x is out of service, please try to 4.x
