### ISSUE TITLE
How to compute the max pool size of sharding-proxy ?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3294]
Project: Sharding-proxy
Version: v3.1.0 & v4.x
## Question
How can i count the total connections of sharding-proxy ? should I use "netstat -an|grep :3307|wc -l" to compute on the server ? 
And what's more, what's the max pool size of sharding-proxy ? Does it equal to total of "MaxPoolSize" in the config-master_salve.yaml and config-sharding.yaml ? For example, if i set MaxPoolSize to 50 with master node and 40 with slave node in config-sharding.yaml, and the MaxPoolSize be set to 100 with master node and 100 with slave node in config-sharding.yaml, then the total MaxPoolSize is 290 ?

Thank you !

**Comment by yanickxia** [comment]
try [SCTL (Sharding-Proxy control language)](https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/usage/)


sctl:show cached_connections | Query the number of cached physical database connections in the current TCP connection

**Comment by Myshiner** [comment]
I got the result.
mysql> sctl:show cached_connections;
+--------------------+
| CACHED_CONNECTIONS |
+--------------------+
| 0                  |
+--------------------+
1 row in set (0.00 sec)

I wonder what's the max connection of sharding-proxy, just like the "max_connections" and "max_user_connections" of mysql. Bcoz there are so many config files like "config-master_slave.yaml" and "config-sharding_yaml", and every config file include at lest two "maxPoolSize" parameters by default value 50, maybe i have 5 logic schemas to use master-slave, and 2 logic schemas to use sharding, so i have 5 config files named config-master_slave*.yaml and 2 files named config-sharding*.yaml, so what's the total pool size ?
By the way, can i set the parameter maxPoolSize with different value to different schema ?

**Comment by Myshiner** [comment]
And sharding-proxy dont support "sctl:hint show status" and "sctl:hint show table status;"
mysql> sctl:hint show status;
ERROR 11001 (S1100): 1Could not support sctl type [sctl:hint show status].
mysql> sctl:hint show table status;
ERROR 11001 (S1100): 1Could not support sctl type [sctl:hint show table status].

**Comment by Myshiner** [comment]
@yanickxia same sctl:hint command can not be supported in sharding-proxy even configurated "proxy.hint.enabled: true".
mysql> sctl:hint show status;
**ERROR 11001 (S1100): 1Could not support sctl type [sctl:hint show status].**

  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  **proxy.hint.enabled: true**
  query.with.cipher.column: true
  sql.show: true

**Comment by terrymanu** [comment]
It is related with your application's TPS.
This is the same question for ask connection pool.
