### ISSUE TITLE
Enhancement about the benchmark site

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#3296]
Our benchmark site is available right now: https://shardingsphere.apache.org/benchmark/

Great progress has been made in presentation than the previous one.

We have reviewed the site and found several issues need to be resolved:

For text:

- [ ] All **mysql** change to **MySQL**.

- [ ] Modules can be **sharding-jdbc/sharding-proxy** while can not be **sharding/sharding proxy/shardingproxy/sharding_proxy/sharding jdbc/shardingjdbc/sharding_jdbc**.

- [ ] Explicit point out this(https://shardingsphere.apache.org/benchmark/#/mysql-vs-sharding) is a **loss test**.

- [ ] There's no **VS** statement in:
https://shardingsphere.apache.org/benchmark/#/sharding-proxy-master-slave
https://shardingsphere.apache.org/benchmark/#/sharding-proxy-master-slave-sharding
https://shardingsphere.apache.org/benchmark/#/sharding-proxy-single-database-single-table
Compared with:
https://shardingsphere.apache.org/benchmark/#/shardingjdbc-vs-shardingproxy-encrypt
https://shardingsphere.apache.org/benchmark/#/shardingjdbc-vs-shardingproxy-sharding-encrypt
Please find a way to describe who vs who clearly.

For data:

- [ ] The general order of the TPS in a compared performance is: MySQL > sharding-jdbc > sharding-proxy. But we can find several exceptions like the UPDATE case in https://shardingsphere.apache.org/benchmark/#/sharding-proxy-master-slave-sharding. I this case sharding-proxy > sharding-jdbc. We need to check the test environment and find the root cause. Of course, it does not meen there's no bugs in sharding-jdbc or sharding-proxy.

- [ ] For the case SELECT in https://shardingsphere.apache.org/benchmark/#/mysql-vs-sharding, the TPS of sharding-proxy is much lower than MySQL. We need to find out whether the case is reasonable or not. Or the performance of sharding-proxy need to be improved.

**Comment by terrymanu** [comment]
Maybe we should move this issue to https://github.com/apache/incubator-shardingsphere-benchmark

**Comment by tuohai666** [comment]
Yes, you are right.

The issues module for incubator-shardingsphere-benchmark is not available for now, I have asked INFRA to enable it: https://issues.apache.org/jira/browse/INFRA-19288.
I'll transport this issue to benchmark repo as soon as INFRA-19288 is fixed.
