### ISSUE TITLE
namespace(xml),SNOWFLAKE,we can't use random?

### ISSUE THREAD

**Issue by childewuque** [apache/incubator-shardingsphere#3300]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Invalid bean definition with name 'properties' defined in null: Could not resolve placeholder 'random.int(1000)'
### Actual behavior
    <bean:properties id="properties">
        <prop key="worker.id">${random.int(1000)}</prop>
    </bean:properties>
  <sharding:key-generator id="libKeyGenerator" type="SNOWFLAKE" column="id" props-ref="properties" />

### Reason analyze (If you can)
format error?

**Comment by terrymanu** [comment]
I have 2 suggestions:
1. prop cannot support inline expression.
2. using random as snowflake's work_id is not correct. work_id should be a static value of one node.

So I just close this issue and label it as invalid.

**Comment by childewuque** [comment]
...,but RANDOM in SNOWFLAKE  is very useful ,This makes deployment easier and simpler。
YAML can use it，XML should use it。In this way, SHARDING-JDBC is the unified and consistent usage.
