### ISSUE TITLE
"max.connections.size.per.query" relationship with "group by "

### ISSUE THREAD

**Issue by zhouzhendao123456** [apache/incubator-shardingsphere#3302]
db:mysql 5.7.19-17-log
sharding-proxy:4.0.0-rc2
select a.x,b.y from a left join b on a.key=b.key where a.key in ('111','222') group by b.z
When I set max.connections.size.per.query = 1, the appeal code can execute normally, but when this parameter is greater than 1, there is SQL output error free information in the sharding log, but MySQL does not receive any SQL query

**Comment by zhouzhendao123456** [comment]
sharding column is a.key and b.key
if sql is
select a.x,b.y from a left join b on a.key=b.key where a.key in ('111') group by b.z
Everything is OK

**Comment by terrymanu** [comment]
Can you provide log of exception?

**Comment by zhouzhendao123456** [comment]
没有任何异常日志，就是sql只在sharding的日志里出现，mysql里没有任何消息






At 2019-10-17 16:21:34, "Liang Zhang" <notifications@github.com> wrote:


Can you provide log of exception?

**Comment by terrymanu** [comment]
For English only

**Comment by zhouzhendao123456** [comment]
No log of exception, SQL only shows up in sharding log, no any info in mysql

**Comment by terrymanu** [comment]
> there is SQL output error free information in the sharding log, but MySQL does not receive any SQL query

I cannot understand, what is `SQL output error free information`? 
How do you know MySQL does not receive any SQL query? Do you use wireshark to catch MySQL packet? What is the SQL packet sent to MySQL?

**Comment by terrymanu** [comment]
Can you fix the typo in title of this issue?

**Comment by zhouzhendao123456** [comment]
show PROCESSLIST
for the mysql, is nohting

**Comment by terrymanu** [comment]
Please provide log of sql.show

**Comment by zhouzhendao123456** [comment]
new error:

[Err] 10002 - 2Unknown exception: [Can't find index: org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderByItem@385e99e9]

**Comment by terrymanu** [comment]
> new error:
> 
> [Err] 10002 - 2Unknown exception: [Can't find index: org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderByItem@385e99e9]

Can you provide context? What will cause this exception? Is it same problem with previous one?

**Comment by zhouzhendao123456** [comment]
==**info**==2019-10-24 14:36:05.185 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ: [id: 0xca03f220, L:/192.168.1.52:3307 - R:/192.168.1.53:52960]
==**info**==2019-10-24 14:36:05.186 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ COMPLETE
==**info**==2019-10-24 14:36:05.194 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.195 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: /* mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'init_connect'
==**info**==2019-10-24 14:36:05.195 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:05.195 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: /* mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'init_connect'
==**info**==2019-10-24 14:36:05.195 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: /* mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'init_connect'
==**info**==2019-10-24 14:36:05.208 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.208 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: /* mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c ) */SELECT @@session.auto_increment_increment
==**info**==2019-10-24 14:36:05.208 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: ShardingSelectOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()), groupBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.groupby.GroupBy@717c951d, orderBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderBy@42db1de1, selectItems=SelectItems(startIndex=116, stopIndex=149, distinctRow=false, items=[ExpressionSelectItem(expression=@@session.auto_increment_increment, alias=Optional.absent())], tables=[]), pagination=org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination@20ca795d, containsSubquery=false)
==**info**==2019-10-24 14:36:05.208 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: /* mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c ) */SELECT @@session.auto_increment_increment
==**info**==2019-10-24 14:36:05.210 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.210 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8
==**info**==2019-10-24 14:36:05.210 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:05.210 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET NAMES utf8
==**info**==2019-10-24 14:36:05.212 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.212 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8
==**info**==2019-10-24 14:36:05.212 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:05.212 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SET NAMES utf8
==**info**==2019-10-24 14:36:05.212 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SET NAMES utf8
==**info**==2019-10-24 14:36:05.214 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.214 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET character_set_results = NULL
==**info**==2019-10-24 14:36:05.215 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:05.215 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET character_set_results = NULL
==**info**==2019-10-24 14:36:05.216 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:05.216 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET character_set_results = NULL
==**info**==2019-10-24 14:36:05.216 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:05.216 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SET character_set_results = NULL
==**info**==2019-10-24 14:36:05.216 INFO  [pool-8-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SET character_set_results = NULL
==**info**==2019-10-24 14:36:08.460 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ: [id: 0xd1b0e815, L:/192.168.1.52:3307 - R:/192.168.1.111:59476]
==**info**==2019-10-24 14:36:08.461 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ COMPLETE
==**info**==2019-10-24 14:36:08.470 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:08.470 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:08.471 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:08.471 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:08.474 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:08.475 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:08.475 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:08.475 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:08.475 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:08.603 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:08.603 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SHOW FULL TABLES FROM `sharding_db2` WHERE Table_type != 'VIEW'
==**info**==2019-10-24 14:36:08.603 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:08.603 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SHOW FULL TABLES  WHERE Table_type != 'VIEW'
==**info**==2019-10-24 14:36:08.603 INFO  [pool-9-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SHOW FULL TABLES  WHERE Table_type != 'VIEW'
==**info**==2019-10-24 14:36:10.329 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ: [id: 0xc796e812, L:/192.168.1.52:3307 - R:/192.168.1.111:59477]
==**info**==2019-10-24 14:36:10.330 INFO  [epollEventLoopGroup-2-1] io.netty.handler.logging.LoggingHandler Line:101 - [id: 0x532b5ab0, L:/0.0.0.0:3307] READ COMPLETE
==**info**==2019-10-24 14:36:10.341 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.342 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:10.342 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.342 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:10.345 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.345 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:10.345 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.345 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:10.345 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SET NAMES utf8mb4
==**info**==2019-10-24 14:36:10.355 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.355 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET PROFILING=1;
==**info**==2019-10-24 14:36:10.355 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.355 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: SET PROFILING=1;
==**info**==2019-10-24 14:36:10.356 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.356 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SET PROFILING=1;
==**info**==2019-10-24 14:36:10.356 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.357 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SET PROFILING=1;
==**info**==2019-10-24 14:36:10.357 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SET PROFILING=1;
==**info**==2019-10-24 14:36:10.364 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.364 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SHOW STATUS
==**info**==2019-10-24 14:36:10.364 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.364 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SHOW STATUS
==**info**==2019-10-24 14:36:10.364 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SHOW STATUS
==**info**==2019-10-24 14:36:10.373 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.373 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: SHOW STATUS
==**info**==2019-10-24 14:36:10.373 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: TransparentOptimizedStatement(tables=Tables(tables=[], schema=Optional.absent()))
==**info**==2019-10-24 14:36:10.373 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_1 ::: SHOW STATUS
==**info**==2019-10-24 14:36:10.373 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: def ::: SHOW STATUS
==**info**==2019-10-24 14:36:10.447 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Rule Type: sharding
==**info**==2019-10-24 14:36:10.448 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Logic SQL: select SUM(usage_right_asset),SUM(accumulated_depreciation) from (^M
SELECT^M
        (^M
                CASE^M
                WHEN a.terminal_date IS NULL THEN^M
                        a.lease_end_date^M
                ELSE^M
                        a.terminal_date^M
                END^M
        ) AS newdate,b.usage_right_asset,b.accumulated_depreciation^M
FROM^M
        app1_contract_object_info a join app1_contract_forecast_detail b on a.sys_contract_id=b.sys_contract_id and a.is_open_max=1 and b.account_date<='2019-09-30'^M
group by b.gaap,b.cf_usage^M
) as aa^M
where ^M
aa.newdate<='2020-09-30'




it's over

**Comment by zhouzhendao123456** [comment]
==**info**==2019-10-24 14:36:10.448 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - SQLStatement: ShardingSelectOptimizedStatement(tables=Tables(tables=[Table(name=app1_contract_object_info, alias=Optional.of(a)), Table(name=app1_contract_forecast_detail, alias=Optional.of(b))], schema=Optional.absent()), groupBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.groupby.GroupBy@4975dd26, orderBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderBy@63ea171b, selectItems=SelectItems(startIndex=77, stopIndex=240, distinctRow=false, items=[ExpressionSelectItem(expression=CASEWHENa.terminal_dateISNULLTHENa.lease_end_dateELSEa.terminal_dateEND)ASnewdat, alias=Optional.of(newdate)), ColumnSelectItem(owner=b, name=usage_right_asset, alias=Optional.absent()), ColumnSelectItem(owner=b, name=accumulated_depreciation, alias=Optional.absent()), DerivedSelectItem(expression=b.gaap, alias=Optional.of(GROUP_BY_DERIVED_0)), DerivedSelectItem(expression=b.cf_usage, alias=Optional.of(GROUP_BY_DERIVED_1))], tables=[TableSegment(startIndex=250, stopIndex=274, name=app1_contract_object_info, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.of(a)), TableSegment(startIndex=283, stopIndex=311, name=app1_contract_forecast_detail, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.of(b))]), pagination=org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination@5adcdbcd, containsSubquery=false)
==**info**==2019-10-24 14:36:10.448 INFO  [pool-10-thread-1] ShardingSphere-SQL Line:99  - Actual SQL: ds_0 ::: select SUM(usage_right_asset),SUM(accumulated_depreciation) from (^M
SELECT^M
        (^M
                CASE^M
                WHEN a.terminal_date IS NULL THEN^M
                        a.lease_end_date^M
                ELSE^M
                        a.terminal_date^M
                END^M
        ) AS newdate,b.usage_right_asset,b.accumulated_depreciation^M, b.gaap AS GROUP_BY_DERIVED_0 , b.cf_usage AS GROUP_BY_DERIVED_1
FROM^M
        app1_contract_object_info_0 a join app1_contract_forecast_detail_0 b on a.sys_contract_id=b.sys_contract_id and a.is_open_max=1 and b.account_date<='2019-09-30'^M
group by b.gaap,b.cf_usage ORDER BY b.gaap ASC,b.cf_usage ASC ^M
) as aa^M
where ^M
aa.newdate<='2020-09-30'

**Comment by terrymanu** [comment]
Sorry, ShardingSphere cannot support such complicated subquery, we will keep on enhance the competition in future.
I just close this issue because it is not a concentrate bug.
More details on SQL supported please see: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/
