### ISSUE TITLE
How config sharding (No master salve) and master slave(no sharding) together with Sharding-jdbc

### ISSUE THREAD

**Issue by swcumt** [apache/incubator-shardingsphere#3306]
## Question
for example

>  sharding database(no master_slave):
     ds0:
           table_0
           table_1
     ds1:
           table_0
           table_1
master slave database(no sharding):
     ds:
          table1
          table2
          ....

**Comment by terrymanu** [comment]
If the scenario is 2 unrelated data sources, you may create one sharding-datasource for sharding only, and create masterslave-datasource  for masterslave only

**Comment by swcumt** [comment]
> If the scenario is 2 unrelated data sources, you may create one sharding-datasource for sharding only, and create masterslave-datasource for masterslave only

are you mean create 2 sharding-jdbc datasorces,  change use in program? sharding-jdbc not support?

**Comment by terrymanu** [comment]
Yes, if they are two different datasource totally.

**Comment by terrymanu** [comment]
I am not saying ShardingSphere do not support, but the first thing is perhaps you need to design your business logic.

**Comment by terrymanu** [comment]
I just set this issue as invalid for now, we can discuss further about this issue.
