### ISSUE TITLE
4.0.0-RC2 max.connections.size.per.query >1 query use order by/group by not result.

### ISSUE THREAD

**Issue by ryan8926** [apache/incubator-shardingsphere#3307]
servel.yaml : max.connections.size.per.query >1 and Large amount of data queried
sql :
SELECT
aci.sys_contract_id,
 aci.contract_no,
 aci.contract_name,
 aci.sys_contract_id,
acoi.sys_contract_id,
 acoi.object_name,
 acoi.sys_object_id,
 aci.progress_status,
 aci.journal_progress_status
FROM
 app1_contract_info aci
LEFT JOIN app1_contract_object_info acoi ON aci.sys_contract_id = acoi.sys_contract_id
where 
aci.contract_name = 'sample1' and aci.sys_contract_id not in ('15679933204395H')
 group BY/order by 
 acoi.sys_object_id 

sys_contract_id is sharding coloum.

result: no result and mysql can not receive.

but this sql is successd ：
SELECT
aci.sys_contract_id,
 aci.contract_no,
 aci.contract_name,
 aci.sys_contract_id,
acoi.sys_contract_id,
 acoi.object_name,
 acoi.sys_object_id,
 aci.progress_status,
 aci.journal_progress_status
FROM
 app1_contract_info aci
LEFT JOIN app1_contract_object_info acoi ON aci.sys_contract_id = acoi.sys_contract_id
where 
aci.contract_name = 'sample1' and aci.sys_contract_id not in ('15679933204395H')

**Comment by terrymanu** [comment]
Is it the duplicate one with #3302?
Can you change the title to summary your question? The current title is not helpful for user to find it.

**Comment by terrymanu** [comment]
Because of no response, I just close it and label as duplicate with #3302.
