### ISSUE TITLE
[ERROR-1146] Table 'db.triggers' doesn't exist

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3310]
Project: Sharding-proxy
Version: v4.0.0-RC3

## Question
Connect to sharding-proxy using navicate tool, and query data by double clicking table, got error.

![微信图片_20191017162105](https://user-images.githubusercontent.com/48242833/66991220-37ca3600-f0fa-11e9-8ea4-c8167a8b3d56.png)

**Comment by terrymanu** [comment]
Hi, the information you provided is not enough. Please follow the issue template and fill necessary information.

**Comment by terrymanu** [comment]
Will close soon if no response any more

**Comment by Myshiner** [comment]
@terrymanu I just want to get the table's ddl information from navicate tool by clicking table. it's equal to that "show create table test_update", but it's ok from sharding-proxy CLI.

**Comment by terrymanu** [comment]
Can you change title for this, I think the problem is not `Table 'db.triggers' doesn't exist`, `navicate cannot show table structure if xxx` maybe better

**Comment by terrymanu** [comment]
Is your database include trigger?

**Comment by Myshiner** [comment]
no, it doesnt include trigger.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [apache/incubator-shardingsphere] [ERROR-1146] Table 'db.triggers' doesn't exist (#3310)From: Liang Zhang To: apache/incubator-shardingsphere CC: Myshiner ,Author Is your database include trigger?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-shardingsphere/issues/3310?email_source=notifications\u0026email_token=ALQCBELV4HLAXW3TVAI6M5DQQFAATA5CNFSM4JBWBHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECD4WTI#issuecomment-545770317",
"url": "https://github.com/apache/incubator-shardingsphere/issues/3310?email_source=notifications\u0026email_token=ALQCBELV4HLAXW3TVAI6M5DQQFAATA5CNFSM4JBWBHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECD4WTI#issuecomment-545770317",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by terrymanu** [comment]
Can you change title for this, I think the problem is not `Table 'db.triggers' doesn't exist`, `navicate cannot show table structure if xxx` maybe better

**Comment by terrymanu** [comment]
Closed for not change title
