### ISSUE TITLE
Hope set a read-only user in sharding-proxy, all requests from this user will route to slave node.

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#3316]
## Feature Request
Hope set a read-only user in sharding-proxy, all requests which from this read-only user will be routed to slave node. Coz sometimes the RD members need a user read-only to query data without any risk.

**Comment by terrymanu** [comment]
This feature request has a little strange. Does any similar database middleware or database has this feature?

**Comment by terrymanu** [comment]
Because for slave database, whatever how to set with ShardingSphere, DBA should set readonly. The scope of ShardingSphere is control databases.
So I just close this issue.
