### ISSUE TITLE
[Propose] add editorconfig

### ISSUE THREAD

**Issue by yanickxia** [apache/incubator-shardingsphere#3320]
## Feature Request

Add [editorconfig](https://editorconfig.org/)

### Describe the feature you would like.
helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs

**Comment by terrymanu** [comment]
This is a interesting tool, I really expect to use it for code format.

**Comment by yanickxia** [comment]
not support `keep indents on empty lines`, not good for us...
