### ISSUE TITLE
nested exception is org.postgresql.util.PSQLException: 未设定参数值 5 的内容。

### ISSUE THREAD

**Issue by kevinLuan** [apache/incubator-shardingsphere#3321]
## Bug Report
Postgresql database + ShardingSphere using the following SQL times wrong:  nested exception is org.postgresql.util.PSQLException: 未设定参数值 5 的内容。

The sample：
INSERT INTO xxx(c1,c2,c3,c4,c5)VALUES (#{c1},#{c2},#{c3},#{c4},lower(#{c5}))
 ON conflict(id) DO 
UPDATE SET c1=#{c1},appdes=#{c2},c4=lower(#{c5})

Through the debug code, is a postgresql parse SQL syntax tree, unable to properly resolve the insert at the back of the parameters, lead to the JDBC insert data, tip missing parameters

**Comment by kevinLuan** [comment]
Directly using one of the most common insert statement, when setting the Value, the database used to own function can also lead to the same error
The sample:
INSERT INTO xxx(c1,c2)VALUES(#{c1},lower(#{c2}))

**Comment by terrymanu** [comment]
duplicate with #3136
