### ISSUE TITLE
Caching rule profiles for spring namespaces

### ISSUE THREAD

**Issue by shuaiqingli** [apache/incubator-shardingsphere#3324]
When I configure through the rules of spring namespace, the spring application will load http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd

Http://shardingsphere.apache.org/schema/shardingsphere/master slave/master-slave.xsd

These specification documents. When my network is bad, the app can't start. I hope these files can be packed into jar, just like spring.

**Comment by terrymanu** [comment]
They have already in the jar: `sharding-spring/sharding-jdbc-spring/sharding-jdbc-spring-namespace/src/main/resources/META-INF/namespace`
