### ISSUE TITLE
4.0.0-RC2  select SQL doesn't work on only database-strategy

### ISSUE THREAD

**Issue by masankin** [apache/incubator-shardingsphere#3325]
table t_user no table-strategy , only database-strategy
when execute  insert SQL can doSharding
but select SQL choose a random database

**Comment by masankin** [comment]
4.0.0-RC1 works ok under the same situation

**Comment by terrymanu** [comment]
Can you provide your config, SQL and log of sql.show?

**Comment by terrymanu** [comment]
Will close soon if no response anymore
