### ISSUE TITLE
Unable to use double quotes in mapper

### ISSUE THREAD

**Issue by yeaicc** [apache/incubator-shardingsphere#3345]
### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
work

### Actual behavior
Appendeded escape character '\' before double quotes

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
select * from table1 
join table2 on table1.id=table2.id and JSON_CONTAINS_PATH(table2.json_info,\"one\",?)=1
```

**Comment by terrymanu** [comment]
Hi, what is the reason for close this issue?

**Comment by yeaicc** [comment]
> Hi, what is the reason for close this issue?

日志里打印的原因罢了，怪我没看清楚
