### ISSUE TITLE
 Encrypt-JDBC couldn't not get decrypt information

### ISSUE THREAD

**Issue by zzy97092236** [apache/incubator-shardingsphere#3346]
https://github.com/apache/incubator-shardingsphere/issues/3255
![66756505-c2c5e900-eecc-11e9-9f24-8780f8e2dddd](https://user-images.githubusercontent.com/56537799/67366311-d268c000-f5a5-11e9-8b7c-06bdad7acfd1.png)

![aHR0cHM6Ly9vc2NpbWcub3NjaGluYS5uZXQvb3NjbmV0LzM3NTczMThkZmJjM2M0OWY0N2UzOGZiMjA1YWZkZDRmOGQyLmpwZw](https://user-images.githubusercontent.com/56537799/67366644-76eb0200-f5a6-11e9-8908-4e45ccade42d.png)

about this question,The query result should be plaintext. Now it is ciphertext. Is it normal?

**Comment by terrymanu** [comment]
What is your version?

**Comment by terrymanu** [comment]
If this issue is same with #3255, please talk in that issue

**Comment by zzy97092236** [comment]
<version&gt;4.0.0-RC2</version&gt;oracle 11.2.0.4.0  com.oracle.weblogic ojdbc7 12.1.3-0-0 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liang Zhang"<notifications@github.com&gt;; 
发送时间: 2019年10月23日(星期三) 下午3:57
收件人: "apache/incubator-shardingsphere"<incubator-shardingsphere@noreply.github.com&gt;; 
抄送: "xpy"<97092236@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-shardingsphere]  Encrypt-JDBC couldn&#39;t not get decrypt information (#3346)




What is your version?
