### ISSUE TITLE
Using the default database, it takes nearly 3 seconds to insert 200 in batches? Why

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#3351]
Using the default database, it takes nearly 3 seconds to insert 200 in batches? Why？
Is there any good way to handle it?
1、shardingsphere version is 4.0.0-RC2,
2、mysql  version is mysql-connector-java-8.0.17,
3、The data source is hikariCP

![{237F3A1B-9264-4B9E-A596-6DA9C524BF61}_20191024104336](https://user-images.githubusercontent.com/25191518/67448946-27124680-f64b-11e9-8c3c-b0f845f64bb6.jpg)

**Comment by xfyang1989** [comment]
![{46570F2B-BF39-478D-ADA9-C2147C191B93}_20191024111103](https://user-images.githubusercontent.com/25191518/67450126-ff24e200-f64e-11e9-9491-9bfc77cbe23b.jpg)

**Comment by xfyang1989** [comment]
If you are using the default data source, for example, the default-data-source-name is configured.

**Comment by xfyang1989** [comment]
Sharingspehere configuration does not parse SQL

**Comment by terrymanu** [comment]
Can you provide `sql.show` and sharding rule config?

**Comment by xfyang1989** [comment]
![{0F295807-8F16-465F-855D-2D85A6C93BD1}_20191024150756](https://user-images.githubusercontent.com/25191518/67461557-335cca80-f670-11e9-8bc8-60aa14d13ccb.jpg)
![{76ABED5F-1D7A-4130-ACF4-135548ADB157}_20191024150814](https://user-images.githubusercontent.com/25191518/67461559-33f56100-f670-11e9-9159-dce9cb051144.jpg)
![{C540EDA1-6863-49A8-B0F8-EA11AB4DA5DB}_20191024150834](https://user-images.githubusercontent.com/25191518/67461560-33f56100-f670-11e9-8ce0-27055adab388.jpg)

**Comment by xfyang1989** [comment]
The table sharingspehere using the "default-data-source-name" parameter will also parse the SQL. If you do not use the sharingspehere to parse the SQL, how to deal with it?

**Comment by xfyang1989** [comment]
I have the same SQL comparison 4.0.0-RC1 version than the 4.0.0-RC2 performance to improve hundreds of milliseconds, the default database bulk insert

**Comment by xfyang1989** [comment]
I am back to the 4.0.0-RC1 version.

**Comment by zhuobinchan** [comment]
4.0.0-RC1 version can fix this problem？？

**Comment by xfyang1989** [comment]
It takes time to insert 200 pieces of RC1 and RC2 in batches, sometimes nearly 4S

**Comment by tuohai666** [comment]
The root cause is straightforward: the parser takes too much time when parsing long SQL first time. Execute the SQL again will not cost time. 
BTW, what's the time cost if execute this SQL directly from MySQL server?

**Comment by xfyang1989** [comment]
> The root cause is straightforward: the parser takes too much time when parsing long SQL first time. Execute the SQL again will not cost time.
> BTW, what's the time cost if execute this SQL directly from MySQL server?

I am using the default data source, he should not be parsed by SQL。If it is directly executed by the MySQL server, it only takes less than 100 milliseconds.
