### ISSUE TITLE
using data encrypt,logicColums is an automatic hump naming rule mapping

### ISSUE THREAD

**Issue by miniygq** [apache/incubator-shardingsphere#3353]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
using data encrypt,logicColums is an automatic hump naming rule mapping,Data desensitization will generate anomalies.

**Comment by terrymanu** [comment]
I can't get the point, can you give an example?

**Comment by terrymanu** [comment]
Hi, what is the reason for close this issue?
