### ISSUE TITLE
The dataSourceProperties property of the HikariDataSource is not correctly written.

### ISSUE THREAD

**Issue by suikenungleung** [apache/incubator-shardingsphere#3365]
Spring Boot 2.1.9
ShardingSphere 4.0.0-RC2

application.yml：
master:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc-url: jdbc:mysql://192.168.177.128:3306/atom?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf-8
  username: root
  password: 123456
  auto-commit: true
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000
  maximum-pool-size: 10
  data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}

There is another：
data-source-properties:
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

The dataSourceProperties property of HikariDataSource is not correctly written. Debug is empty

**Comment by yanickxia** [comment]
@terrymanu  this is bug, i will fix it..  [HikariCP-Mysql](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration).

**Comment by terrymanu** [comment]
@yanickxia OK, thank you. assigned.

**Comment by suikenungleung** [comment]
@yanickxia How to properly configure data-source-properties in version 4.0.0-RC3, what I want is to configure the implementation in the yml file.
