### ISSUE TITLE
oracle load meta data get index info user schema error

### ISSUE THREAD

**Issue by 54chenjian** [apache/incubator-shardingsphere#3370]
### Which version of ShardingSphere did you use?

4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Reason analyze (If you can)
```java
 private Collection<String> getLogicIndexes(final Connection connection, final String catalog, final String actualTableName) throws SQLException {
        Collection<String> result = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getIndexInfo(catalog, catalog, actualTableName, false, false)) {
            while (resultSet.next()) {
                Optional<String> logicIndex = getLogicIndex(resultSet.getString("INDEX_NAME"), actualTableName);
                if (logicIndex.isPresent()) {
                    result.add(logicIndex.get());
                }
            }
        }
        return result;
    }
```
```java
   ResultSet getIndexInfo(String catalog, String schema, String table, boolean unique, boolean approximate)
        throws SQLException;
```
oracle catalog is sid ，the second param is scheam，is not sid

**Comment by tristaZero** [comment]
Hi, it is a easy issue, if anyone is interested in it, please raise a PR. Thanks
### How to solve it?
If null == resultSet.getString(INDEX_NAME), then return Optional.<String>absent() in `getLogicIndex(final String actualIndexName, final String actualTableName)`.

**Comment by beijing-penguin** [comment]
I read the pssql、mysql and oracle jdbc source code，about catalog and schema method parameter，the result is :
1、All database's catalog  equal database name
2、oracle's schema equal username ,but other database's schema equal null.

**Comment by tristaZero** [comment]
> I read the pgsql、mysql and oracle jdbc source code，about catalog and schema method parameter，the result is :
> 1、All database's catalog equal database name
> 2、oracle's schema equal username ,but other database's schema equal null.

Hi penguin, Appreciated your investigation, if available, we welcome your contribution. :)

**Comment by tristaZero** [comment]
> I read the pgsql、mysql and oracle jdbc source code，about catalog and schema method parameter，the result is :
> 1、All database's catalog equal database name
> 2、oracle's schema equal username ,but other database's schema equal null.

It is great. Your detail investigation inspired us how to solve this issue!
