### ISSUE TITLE
Can you change the sharding routing engine to a property of a ShardingStatement?

### ISSUE THREAD

**Issue by ezzuodp** [apache/incubator-shardingsphere#3376]
## Feature Request
In a project, we need to use the instance of table splitting routing engine in sharding statement.
Can you make the following adjustments to shardingstatement?

![3](https://user-images.githubusercontent.com/4951767/67616385-94200a80-f80a-11e9-8e19-83fac696b4e8.png)

**Comment by terrymanu** [comment]
Can you change title for search friendly?

**Comment by ezzuodp** [comment]
> Can you change title for search friendly?

Sorry, the title is not clearly written.

**Comment by terrymanu** [comment]
This is the internal implementation. I suggest your coding don't depend on it, the refactor always occur for internal implementation without guarantee.

**Comment by terrymanu** [comment]
I suggest do not change it because of the `SimpleQueryShardingEngine` can lazy initialized. If user create statement, but do not call execute create `SimpleQueryShardingEngine` instance is unnecessary. 

So what is the actual benefit to refactor this?

**Comment by terrymanu** [comment]
If no update, I will close this soon
