### ISSUE TITLE
mybatis-plus call the baseMapper.saveBatch(List<User> list) can't return the database auto increment id to the User entity

### ISSUE THREAD

**Issue by alwyngo** [apache/incubator-shardingsphere#3386]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Just as described on the title, when call `baseMapper.saveBath` method, it can't set the database auto increment id to the List entity, which still null.  But when I don't use the Shardingsphere，`baseMapper.saveBath` method works well

**Comment by yanickxia** [comment]
Sharding-JDBC: 4.0 - RC3 
SPRING Boot： 1.5.22.RELEASE

![image](https://user-images.githubusercontent.com/6848593/67669679-5c04fd00-f9ad-11e9-8ee8-9499812ea3a4.png)
it's work...

can you show your git repo??

PS:  insure ` useGeneratedKeys="true"` is setted.

**Comment by alwyngo** [comment]
@yanickxia Hi, the `baseMapper.saveBatch` method is provided by the mybatis-plus framework, i can't config the  useGeneratedKeys

**Comment by xr2117** [comment]
After inserting data, savebatch is split into one insert instead of batch insert
