### ISSUE TITLE
springboot 2.1.x + shardingsphere 4.0.0-RC2 can't run

### ISSUE THREAD

**Issue by forachange** [apache/incubator-shardingsphere#3387]
BUG
-  springboot 2.1.9.RELEASE 
- shardingsphere 4.0.0-RC 
- mybatis-spring-boot-starter 2.0.1

I can't run the application.

The following is the error info:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field userRepository in xxx.service.impl.UserServiceImpl required a bean of type 'xxx.mapper.UserRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'xxx.mapper.UserRepository' in your configuration.
```

Then I change the springboot version and shardingsphere version. it's ok.
- springboot 2.0.9.RELEASE
- mybatis 2.0.1
- shardingsphere 4.0.0-RC1

**Comment by yanickxia** [comment]
can you take a demo git repo?  it seem like not init mybatis

**Comment by terrymanu** [comment]
@forachange for Can you try example first?

**Comment by beijing-penguin** [comment]
Simple configuration，you can create a ShardingDataSource object...like this "
		DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new Properties());"        then replace mybatis datasource.

**Comment by harvies** [comment]
I will provide an example.

**Comment by harvies** [comment]
You need to add @MapperScan(basePackages = "xxx.mapper") to the Application.

**Comment by harvies** [comment]
The example address is at "https://raw.githubusercontent.com/harvies/codes/master/db/sharding-sphere/sharding-jdbc-example/sharding-jdbc-sharding-example/sharding-jdbc-spring-boot-mybatis- Example/src/main/java/io/github/harvies/codes/sharding/jdbc/spring/boot/mybatis/ShardingJdbcSpringBootMybatisExampleMain.java”.

**Comment by harvies** [comment]
The example address is at "https://github.com/harvies/codes/blob/master/db/sharding-sphere/sharding-jdbc-example/sharding-jdbc-sharding-example/sharding-jdbc-spring-boot-mybatis-example/src/main/java/io/github/harvies/codes/sharding/jdbc/spring/boot/mybatis/ShardingJdbcSpringBootMybatisExampleMain.java”.

**Comment by terrymanu** [comment]
Will close soon if no response anymore for the issue author
