### ISSUE TITLE
The issue of Saga distributed transaction using jar package

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#3388]
When my project is packaged as jar to run, when saga transaction reads the configuration file saga.properties, it will report an error \ swallowplatformbusiness. Jar! \ boot-inf \ classes! \ saga.properties (incorrect file name, directory name or volume label syntax). ）The way I look for Baidu is that when the project is packaged into jar to run, sagaconfigurationloader. Class. Getclassloader(). Getresource (configuration_file); the reading method is wrong.

**Comment by terrymanu** [comment]
Can you change the title to more make sense?

**Comment by mygitdds** [comment]
@terrymanu 这样应该可以吧。

**Comment by mygitdds** [comment]
@terrymanu It should be ok

**Comment by KomachiSion** [comment]
@mygitdds , `saga.properties` should be located in root classpath. I am not clear for your environment, So I think that your `saga.properties` file is it in the wrong place.

**Comment by mygitdds** [comment]
@KomachiSion I put it in the same level as the path's and the springboot's propertis file. I can deploy the project as a war package, but there is no problem.

**Comment by mygitdds** [comment]
@KomachiSion The saga of version 4.0.0-rc2 that I used has many similar situations on Baidu, because after the project is packaged into jar package, the path cannot be obtained.

**Comment by KomachiSion** [comment]
> @KomachiSion The saga of version 4.0.0-rc2 that I used has many similar situations on Baidu, because after the project is packaged into jar package, the path cannot be obtained.

You can try add `saga.properties` to classpath by `-classpath` java properties like 

`java -classpath .:${yourClassPath}:${saga.propertiesPath} ${MAINCLASS}`
