### ISSUE TITLE
sharding-ui-backend support spring-boot-maven-plugin plugin

### ISSUE THREAD

**Issue by yanickxia** [apache/incubator-shardingsphere#3393]
### Describe the feature you would like.

durating develop, if want run a sharding-ui-backend must be package then `java -jar` run. maybe add a `spring-boot-maven-plugin` then `spring-boot:run` more easy...

**Comment by beijing-penguin** [comment]
@terrymanu Is this need appropriate?  I can do it...

**Comment by terrymanu** [comment]
@beijing-penguin Thank you, the pull request has merged, maybe next time.
