### ISSUE TITLE
Compatibility of reading saga.properties from a jar package in the sagaconfigurationloader.loadconfigurationproperties method of Saga

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#3398]
In sagaconfigurationloader.loadconfigurationproperties method of distributed transaction saga, sagaconfigurationloader. Class. Getclassloader(). Getresource (configuration_file) is used to read saga.properties. When the project runs as a jar package, it will report the wrong path and cannot find the file. A policy can be added to use sagaconfiguration when it cannot be read. Load. Class. Getclassloader(). Getresourceasstream (configuration file); to read

**Comment by terrymanu** [comment]
Hi, what is the reason for close this issue?
