### ISSUE TITLE
 Compatibility of reading saga.properties from a jar package in the sagaconfigurationloader.loadconfigurationproperties method of Saga

### ISSUE THREAD

**Issue by mygitdds** [apache/incubator-shardingsphere#3399]
In sagaconfigurationloader.loadconfigurationproperties method of distributed transaction saga, sagaconfigurationloader. Class. Getclassloader(). Getresource (configuration_file) is used to read saga.properties. When the project runs as a jar package, it will report the wrong path and cannot find the file. A policy can be added to use sagaconfiguration when it cannot be read. Load. Class. Getclassloader(). Getresourceasstream (configuration file); to read

**Comment by harvies** [comment]
Can you provide an example?

**Comment by mygitdds** [comment]
@harvies I use saga in my project. When my project is packaged into jar package to run, there is an error reading saga.propertis in Saga transaction. The reason for the error is that the path obtained is not correct, because after jar package is printed, it is not a folder. I changed the source code, added a way to read through the stream, and then run it successfully.

**Comment by harvies** [comment]
You can use Spring @PropertySource and @Value to get the configuration file.

@Configuration
@PropertySource(value="classpath:config.properties")
public class ProperySourceDemo {
 
    @Value("${jdbc.url}")
    private String url;
 
}

Or you can provide an example project.

**Comment by mygitdds** [comment]
@harvies I'll give you a code that I used to branch. You pull it down, type it into a jar package, and then run it. Wait a moment.

**Comment by mygitdds** [comment]
@harvies Use DDS branch code https://gitee.com/shengnong_1/dashboard/programs/12247/projects/shengnong_1/SwallowPlatformBusiness/tree/dds_20190809

**Comment by mygitdds** [comment]
@harvies 
Using sharding saga, the project runs as a jar package, and an error will be reported when the project starts. The path cannot be found. The error code is the method new FileInputStream (new file (configurationfile. Getpath())) in the sagaconfigurationloader class. In this way, the saga.propertis file cannot be obtained,

**Comment by harvies** [comment]
> @harvies
> Using sharding saga, the project runs as a jar package, and an error will be reported when the project starts. The path cannot be found. The error code is the method new FileInputStream (new file (configurationfile. Getpath())) in the sagaconfigurationloader class. In this way, the saga.propertis file cannot be obtained,
Permission denied.

**Comment by KomachiSion** [comment]
@mygitdds , I remember that you have premised this problem #3388 .

The problem is you do not put the saga.properties into your root class path.
For springboot jar model, you can package a `conf` dir, and put all of the properties into there.

Then you put the `conf` dir into your root class path like `-classpath .:${yourClassPath}:${parentPath}/conf/* `

**Comment by KomachiSion** [comment]
> @harvies Use DDS branch code https://gitee.com/shengnong_1/dashboard/programs/12247/projects/shengnong_1/SwallowPlatformBusiness/tree/dds_20190809

Can you push these example code to GitHub?

**Comment by KomachiSion** [comment]
@mygitdds, The saga.properties we designed is for users can config it independently. 
We think the `properties` file should be out from the jar package install by yourself so that you can modify configurations easier. And there is no nessary to support reading it from jar.

**Comment by KomachiSion** [comment]
No response more 7days. I will close this issue.
