### ISSUE TITLE
multi schema query error

### ISSUE THREAD

**Issue by hugo980521** [apache/incubator-shardingsphere#3405]
bug ：version 4.0.0-RC1 
mysql database has three schemas: ds0, ds1, test

at ds0 create table test_a,sql follow:
CREATE TABLE `test_a` (
  `name` varchar(20) DEFAULT NULL COMMENT '名称',
  `code` varchar(20) DEFAULT NULL COMMENT '编码',  
  `id` varchar(36) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;

at ds1 create table test_b,sql follow:

CREATE TABLE `test_b` (
  `name` varchar(20) DEFAULT NULL COMMENT '名称',
  `code` varchar(20) DEFAULT NULL COMMENT '编码',  
  `id` varchar(36) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;

at test execute query:
select e.* from (
		SELECT
		c.`id` AS idStr,
		c.`code` AS `code`,
		c.`name` AS `name`
		FROM
		`ds0`.`test_a` c
		UNION ALL
		SELECT
		`a`.`id` AS idStr,
		`a`.`code` AS `code`,
		`a`.`name` AS `name`
		FROM
		 `ds1`.`test_b` a
		) e

then error:
2019-10-30 14:31:55.464  INFO 8800 --- [nio-8084-exec-1] ShardingSphere-SQL                       : Actual SQL: test ::: 
		select e.* from (
		SELECT
		c.`id` AS idStr,
		c.`code` AS `code`,
		c.`name` AS `name`
		FROM
		`test_a` c
		UNION ALL
		SELECT
		`a`.`id` AS idStr,
		`a`.`code` AS `code`,
		`a`.`name` AS `name`
		FROM
		 `test_b` a
		) e

### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.test_a' doesn't exist

but at the 3.1.0 version is ok.

**Comment by terrymanu** [comment]
Can not support union and subquery

**Comment by hugo980521** [comment]
at version 3.1.0 is ok。 all tables are not sharding tables, so shuld be executed normally.
