### ISSUE TITLE
When have a lot of data sources ,CreateDataSource It's very slow....

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shardingsphere#3406]
Sharding-JDBC 3.0.0

We are using version 3.0.0，Now we have 128 datasourcs, which are database and table。

We found that as the number of data sources increased, our application started very slowly,

The reason is this code ：

ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, shardingProperties.getConfigMap(), shardingProperties.getProps());

  private final Map<String, DataSource> dataSourceMap = new LinkedHashMap<>();

this dataSourceMap  has 128.

i want to know  createDataSource do what.?

If there are many data sources, can we use multithreading to initialize them?

can you help me other solutions?

**Comment by terrymanu** [comment]
Version 3.x is out of service, can you try 4.x?

**Comment by yu199195** [comment]
Our company can't upgrade. We have too much business

**Comment by terrymanu** [comment]
Then maybe I will close this issue, because of the version is before enter to apache incubator.
