### ISSUE TITLE
Is there redundant code in ShardingProperties class？

### ISSUE THREAD

**Issue by zjcnb** [apache/incubator-shardingsphere#3408]
Hi everyone，
     I hava a suggestion，validate() methond in ShardingProperties class。 Part of code can remove？Because，Is there no long.class in ShardingPropertiesConstant 。The following code：

       String value = props.getProperty(each);
            if (type == boolean.class && !StringUtil.isBooleanValue(value)) {
                errorMessages.add(getErrorMessage(shardingPropertiesConstant, value));
            } else if (type == int.class && !StringUtil.isIntValue(value)) {
                errorMessages.add(getErrorMessage(shardingPropertiesConstant, value));
            } else if (type == long.class && !StringUtil.isLongValue(value)) {
                errorMessages.add(getErrorMessage(shardingPropertiesConstant, value));
            }

**Comment by terrymanu** [comment]
Can you submit a pull request?

**Comment by zjcnb** [comment]
yes，i can



---Original---
