### ISSUE TITLE
batch insert sql can improve efficiency?

### ISSUE THREAD

**Issue by zhuobinchan** [apache/incubator-shardingsphere#3427]
## Question
batch insert 10000 record by default  just need 2~3 second，but use sharding-jdbc insert need more than 2 minutes。
how to optimize it to improve efficiency？

maven version：
![image](https://user-images.githubusercontent.com/15796879/67942417-bce13f00-fc12-11e9-9f23-e0a46f4fa8bb.png)

test case result：
![image](https://user-images.githubusercontent.com/15796879/67942458-cf5b7880-fc12-11e9-806e-ff061ec17cdb.png)

database：Mysql 5.7

**Comment by yanickxia** [comment]
What Type? 
`Master/Slave` almost without any reduce.
`sharding tables` seem half speed of raw insert.

**Comment by zhuobinchan** [comment]
without any reduce

my sharding config：
![image](https://user-images.githubusercontent.com/15796879/67944782-3e879b80-fc18-11e9-95bb-1493fa8eb8e0.png)

**Comment by yanickxia** [comment]
the same configuration.  
`Raw Insert` insert 10,000 rows data use 1.759s
`Sharding table` insert 10,000 rows data use  10.42s

**Comment by terrymanu** [comment]
duplicate with #3351

**Comment by zhuobinchan** [comment]
> the same configuration.
> `Raw Insert` insert 10,000 rows data use 1.759s
> `Sharding table` insert 10,000 rows data use 10.42s

I found sharding table insert 10000 rows in one sql slower than 500 rows in 20 sql，because sql longer parsing sql slower？

**Comment by xfyang1989** [comment]
This question is raised by me. Now, the performance of this batch insert has a great impact, both RC1 and RC2 have a great impact

**Comment by zhuobinchan** [comment]
> #3351 This question is raised by me. Now, the performance of this batch insert has a great impact, both RC1 and RC2 have a great impact。
> I mainly use the default data source, which is inserted in batches. 200 days, nearly 4 seconds, what other good way to avoid this problem

I read your question，and now i fix this question by config two data sources like this：
default data source config：
![image](https://user-images.githubusercontent.com/15796879/68133633-bd077480-ff5b-11e9-8cdd-16ede0c181a1.png)
sharding data source config：
![image](https://user-images.githubusercontent.com/15796879/68133713-e1635100-ff5b-11e9-8e55-09ca3921b56a.png)

if i do not need operate sharding table ，i user default data source to operate database

**Comment by xfyang1989** [comment]
I know the way you said, but this one is in the same transaction with the sharing table - two data sources can't control the transaction

发自我的 iPhone
