### ISSUE TITLE
JDBC and workbench and navicat are not logged in

### ISSUE THREAD

**Issue by xxx1204** [apache/incubator-shardingsphere#3431]
I can't connect with a Java program, proxy.No error reported.You can't log in the UI tools, you can only log in using the mysql command

**Comment by terrymanu** [comment]
what is your version?

**Comment by yanickxia** [comment]
@xxx1204 

MySQL Workbench `6.3.10` is work...
`8.X` not working. beacuse driver is change.. but Workbench not any driver version select. 

so, i think you can try old version, such like `6.3.10`

**Comment by xxx1204** [comment]
> 您的版本是？

4.0.0-RC2

**Comment by xxx1204** [comment]
> 您的版本是？

SPRING2 connect  4.0.0-RC2

**Comment by terrymanu** [comment]
What is the reason for close this issue?

**Comment by xxx1204** [comment]
I can't connect with a Java program, proxy.No error reported.You can't log in the UI tools, you can only log in using the mysql command

**Comment by terrymanu** [comment]
Can you provide the full logs of application startup?

**Comment by xxx1204** [comment]
> 关闭此问题的原因是什么？
There is no error in the log

**Comment by terrymanu** [comment]
Even there is no error log, I still need the log to find some hint

**Comment by terrymanu** [comment]
I will close soon if no response anymore
