### ISSUE TITLE
can we push log to Cat?

### ISSUE THREAD

**Issue by jinjim** [apache/incubator-shardingsphere#3432]
## Feature Request

**For English only**, other languages will not accept.
how can we push log to Cat?

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by yanickxia** [comment]
Try [Cat with Logback](https://github.com/dianping/cat/blob/master/integration/logback/README.md)

**Comment by terrymanu** [comment]
@jinjim Can you follow @yanickxia 's suggestion and try it?

**Comment by jinjim** [comment]
I have tried to implement druid filter to get sql log!3q
