### ISSUE TITLE
springboot2 connnect proxy error

### ISSUE THREAD

**Issue by maybeclold** [apache/incubator-shardingsphere#3436]
How spring boot2 connects mysql8 through proxy？
my connectis error 。

mysql is 8.0
proxy is 4.0.0-RC1

<img width="656" alt="error" src="https://user-images.githubusercontent.com/42229515/68065345-f5902e00-fd62-11e9-9045-ed045d1bf1f7.png">

**Comment by terrymanu** [comment]
Hi, can you change the title for search friendly?

**Comment by terrymanu** [comment]
I just set this issue as invalid until title change. And I will close later if title do not change.

**Comment by maybeclold** [comment]
I've changed it.soryy!!!




At 2019-11-02 16:30:11, "Liang Zhang" <notifications@github.com> wrote:


Hi, can you change the title for search friendly?

**Comment by maybeclold** [comment]
> 我只是将此问题设置为无效，直到标题更改为止。如果标题没有更改，我将在稍后关闭。

oh  I'm sorry.I've changed it

**Comment by geomonlin** [comment]
First you can reduce your mysql version.
Secondly What is your proxy version?

**Comment by maybeclold** [comment]
> 首先，您可以减少mysql版本。
> 其次，您的代理版本是什么？

thx

**Comment by maybeclold** [comment]
> > 首先，您可以减少mysql版本。
> > 其次，您的代理版本是什么？
> 
> 谢谢

mysql is 8.0
poxy is 4.0.0-RC1

**Comment by yanickxia** [comment]
@maybeclold  the mysql driver too higher.. try 5.X or 6.X

**Comment by terrymanu** [comment]
@maybeclold Hi, any update? Or may I close this issue?

**Comment by cherrylzhao** [comment]
enhance it #5218, mysql8-client will be supported in 4.1.0 release
