### ISSUE TITLE
Not compatible with mybatisplus

### ISSUE THREAD

**Issue by xr2117** [apache/incubator-shardingsphere#3439]
I am Chinese, English is not very good.

Sharding-jdbc JDBC latest version

Mybatisplus latest version

problem
The page method of the mybatisplus Page object accepts a long argument.
And sharding-jdbc receives the int type

In source
Package org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination;
getValue method convert to int
Throw a conversion exception

recurrent
Use the MybatisPlus Page object to page through the query to reproduce

hope
Integrated mybatisplus compatible

**Comment by terrymanu** [comment]
What is your actual version?

**Comment by xr2117** [comment]
MybatisPlus 3.2.0 version  
ShardingJDBC 4.0.0-RC2 version

**Comment by terrymanu** [comment]
Can you provide exception stack trace?

**Comment by xr2117** [comment]
It's not convenient to contact here. You are also Chinese. Can I contact QQ in other ways?

The reason for the exception is that the mybatisplus page is of long type, shardingjdbc is of int type, and the conversion exception occurs

**Comment by dongzl** [comment]
> It's not convenient to contact here. You are also Chinese. Can I contact QQ in other ways?
> 
> The reason for the exception is that the mybatisplus page is of long type, shardingjdbc is of int type, and the conversion exception occurs

This bug has already fixed in 4.0.0-RC3 version, you can focus on RC3's release.

you can reference this issue. #3257 .

**Comment by xr2117** [comment]
When will the 4.0.0-rc3 release be released

**Comment by dongzl** [comment]
Very quickly, The RC3's release is in process.

**Comment by xr2117** [comment]
Can I be your friend? I'm in Beijing。

**Comment by terrymanu** [comment]
> It's not convenient to contact here. You are also Chinese. Can I contact QQ in other ways?
> 
> The reason for the exception is that the mybatisplus page is of long type, shardingjdbc is of int type, and the conversion exception occurs

Sorry, we are apache project, we need follow apache way to make all discuss public in github or mailing list.
it is nothing happen if your request is not in a public area.
