### ISSUE TITLE
ResultSetUtil convert bool column with '0' will get error

### ISSUE THREAD

**Issue by DongJigong** [apache/incubator-shardingsphere#3440]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc-spring-boot-starter 4.0.0-rc2
### Expected behavior
convert to false or true
### Actual behavior
return cast type exception
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/8855265/68097394-c52aca00-fef1-11e9-8812-95788469dda0.png)
![image](https://user-images.githubusercontent.com/8855265/68097404-ce1b9b80-fef1-11e9-8893-a4da2252b025.png)

**Comment by DongJigong** [comment]
![image](https://user-images.githubusercontent.com/8855265/68097675-61090580-fef3-11e9-9268-3a3c2b8feaa1.png)

**Comment by jiang2015** [comment]
you should provide your sql,and project configure？

**Comment by DongJigong** [comment]
After I changed my mysql table varchar column  to a bit column . It works fine again.
