### ISSUE TITLE
present table not exist when start application

### ISSUE THREAD

**Issue by bofale** [apache/incubator-shardingsphere#3446]
### Which version of ShardingSphere did you use?
org.apache.shardingsphere sharding-jdbc-core 4.0.0-RC2

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Oracle info
Oracle 11g

### DataSource
HikariDataSource com.zaxxer.HikariCP 3.4.1

### Expected behavior
find table info

### Actual behavior
ORA-00942: Table or view does not exist

### Reason analyze (If you can)
I view source code and know this issue reason. Shardingsphere will get table info with schema.table in db when start application.The schema originate from setup dataSource url.The url as below is my project:
jdbc:oracle:thin:@//localhost:1522/XE ,

I find OracleDataSourceMetaData.class will parse oracle configuration and the code is get schema code as below:
`this.schemaName = matcher.group(5);`

Finally, this will be combined with the table name to query the table information in the database.
Like this: XE.table.
I don't set a schema for the . My login user name is regarded as default schema.
I try to use this method,

`HikariDataSource.setSchema`
,but i got an exception.
Caused by: java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V

So i think it should be username.table or provide a method to set schema.

BR!

**Comment by zjcnb** [comment]
i want to do it ,Do we provide a setup entry？

**Comment by terrymanu** [comment]
@zjcnb Thank you, I just assign this issue to you.
You mean do we need a demo code to reproduce this issue?

**Comment by bofale** [comment]
> i want to do it ,Do we provide a setup entry？

thanks for @zjcnb ,I will  create a project on github in weekend , and paste project url in new comment

**Comment by zjcnb** [comment]
@bofale ok！

**Comment by zjcnb** [comment]
@terrymanu @bofale I've got the problem, Submit the pr tomorrow.

**Comment by tristaZero** [comment]
@bofale  Hi, CatalogName is `username`, not `XE` which is ServiceName,right?

**Comment by tristaZero** [comment]
Actually, another contributor is handling this similar issue, please refer to #3516 .

**Comment by tristaZero** [comment]
Please wait for #3541

**Comment by bofale** [comment]
> @bofale Hi, CatalogName is `username`, not `XE` which is ServiceName,right?

yes, you're right!
So sorry,i 'm a little busy recently,so i forgot  reply this issue,and i  go to #3516  see this issue has fixed.
Thanks.
