### ISSUE TITLE
Proxy occurs NullPointerException when the SQL is empty String

### ISSUE THREAD

**Issue by RaigorJiang** [apache/incubator-shardingsphere#3449]
### Which version of ShardingSphere did you use?
Sharding-Proxy 4.0.0-RC3-SNAPSHOT

### Expected behavior
When we use IDE, such as Navicat, we can execute the selected SQL by clicking 'Run Selected', but if nothing is selected at the time, the proxy will occur NullPointerException.

As Expected, it should not go wrong

### Reason analyze (If you can)
In SQLParserEngine.parse() method, when the SQL is empty, the ParseTree will be null, and then 
occurs the exception.

**Comment by RaigorJiang** [comment]
The ERROR log is like the following:

> [ERROR]  [ShardingSphere-Command-3] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.core.parse.core.parser.SQLParserEngine.parse(SQLParserEngine.java:59)
	at org.apache.shardingsphere.core.parse.core.SQLParseKernel.parse(SQLParseKernel.java:61)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:68)

**Comment by RaigorJiang** [comment]
I suggest adding an empty judgment in the TextProtocolBackendHandlerFactory, I will submit a PR later.

**Comment by terrymanu** [comment]
Thank you, assign this issue to you.
