### ISSUE TITLE
 How to confirm that the read query goes to the slave database

### ISSUE THREAD

**Issue by zhumaoliang** [apache/incubator-shardingsphere#3452]
It is configured with read-write separation. How to confirm that the read query goes to the slave database and the write operation goes to the master database

**Comment by RaigorJiang** [comment]
You can use the configuration:  
`sql.show: true` 
to show the Actual SQL

**Comment by zhumaoliang** [comment]
Configured, but it doesn't work，as follows  <prop key="sql.show">true</prop>

**Comment by RaigorJiang** [comment]
@zhumaoliang  Can you show your configuration?

**Comment by zhumaoliang** [comment]
OK，![图片](https://user-images.githubusercontent.com/15760871/68200074-22aa3e00-fffa-11e9-96c3-92e39bd0cb35.png)

**Comment by RaigorJiang** [comment]
Ok. It looks the same as the documentation.
Do you use the 4.0.0-RC2 version?

If the problem persists after reading the documentation, could you provide a sample project to github?

**Comment by terrymanu** [comment]
@zhumaoliang any update?
