### ISSUE TITLE
Sharding JDBC paging operations for different data sources？

### ISSUE THREAD

**Issue by Joe192168** [apache/incubator-shardingsphere#3455]
How does sharding JDBC page? Is there a detailed demo

**Comment by RaigorJiang** [comment]
Pagination queries  is Supported,  there is almost no difference from a single data source when using multiple data sources. 
Please read:
https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/pagination/
or in Chinese:
https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/pagination/

**Comment by RaigorJiang** [comment]
One Notice: ORDER BY is required for Pagination queries.

**Comment by Joe192168** [comment]
ok，try
