### ISSUE TITLE
Getting started is hard! The documentation is unclear and incomplete, resulting in some unclear functions

### ISSUE THREAD

**Issue by zhangChaoWrecked** [apache/incubator-shardingsphere#3457]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
Can you show the details?

**Comment by RaigorJiang** [comment]
You can read these practical articles:
https://github.com/apache/incubator-shardingsphere/issues/650

**Comment by terrymanu** [comment]
Will close soon if no response anymore by author
