### ISSUE TITLE
use sharding when value typel is LONGVARCHAR have some problems

### ISSUE THREAD

**Issue by zhuyaoming** [apache/incubator-shardingsphere#3458]
i use mybatis to insert table, but when field type is LONGVARCHAR .
sharding have not to covert the value to string but io.

#{ruleResult,jdbcType=LONGVARCHAR},

Cause: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
; Invalid argument value: java.io.NotSerializableException; nested exception is java.sql.SQLException: Invalid argument value: java.io.NotSerializableException

**Comment by zhuyaoming** [comment]
but if i remove the tpye isok 
like #{ruleResult}

**Comment by terrymanu** [comment]
What is your ShradingSphere's version?

**Comment by zhuyaoming** [comment]
> What is your ShradingSphere's version?

my version is 3.1.0

**Comment by terrymanu** [comment]
Can you update to version 4.x and try again?

**Comment by tuohai666** [comment]
Duplicate with [#1567](https://github.com/apache/incubator-shardingsphere/issues/1567).
And Fixed via [#2388](https://github.com/apache/incubator-shardingsphere/pull/2388).
