### ISSUE TITLE
Sharding JDBC package differences

### ISSUE THREAD

**Issue by Joe192168** [apache/incubator-shardingsphere#3461]
Hi,
1、
<groupId>org.apache.shardingsphere</groupId>
 <artifactId>sharding-jdbc-core</artifactId>
2、
<groupId>com.dangdang</groupId>
<artifactId>sharding-jdbc-core</artifactId>

What does 1 have to do with 2

**Comment by RaigorJiang** [comment]
They are diffenent version.    Please use the new version with `org.apache` package name.

**Comment by Joe192168** [comment]
But the org.apache package is not compatible with com.dangdang's package？

**Comment by RaigorJiang** [comment]
Yes, they are not compatible,  That  `com.dangdang`  is a very old version.
The new version fixes a lot of issues and provides new features,  you can try.

**Comment by Joe192168** [comment]
How to upgrade the org.apache program with the com.dangdang package?

For example: 
Shardingrule shardingrule = Shardingrule. Builder(). Datasourcerrule (datasourcerrule). Tablerules (newtablerule). Databaseshardingstrategy (New databaseshardingstrategy ("create time", new modulodatabaseshardingalgorithm()). Tableshardingstrategy (New tableshardingstrategy ("create time", new modulotableshardingalgorithm()). Build();

**Comment by terrymanu** [comment]
You can reference document and example

**Comment by Joe192168** [comment]
Compared the old source code with the latest one, it's not good at all. I can't think about the examples at all

Can't the government offer an upgrade plan？
