### ISSUE TITLE
Is it necessary to add check duplicate

### ISSUE THREAD

**Issue by zjcnb** [apache/incubator-shardingsphere#3463]
hi，
     ShardingSphere Is there no check duplicate classes，Is it necessary to add it！ like rpc framework dubbo！

**Comment by terrymanu** [comment]
ok, we can start to optimized the duplicated class, do you want to do it?

**Comment by zjcnb** [comment]
yes，i do

**Comment by terrymanu** [comment]
Great, assigned to you.

**Comment by zjcnb** [comment]
Which module is suitable to write to

**Comment by zjcnb** [comment]
I will add it in sharding-core module, path: sharding-core/sharding-core-common。because this module is basics module, You think how？

**Comment by terrymanu** [comment]
We discuss at the pull request
