### ISSUE TITLE
本地事务必须要在方法上加@Transactional才能生效吗？

### ISSUE THREAD

**Issue by wjwei** [apache/incubator-shardingsphere#3464]
配置了本地事务，发现只能在方法上加@Transactional才能生效，导致工程里有一些单个更新操作的方法也要加上@Transactional注解，感觉很麻烦。不知道是不是自己没有配置好，还是说shardingsphere的本地事务就必须要在方法上加@Transactional注解才能生效？

**Comment by yanickxia** [comment]
Only for English..
