### ISSUE TITLE
Local transactions must be @Transactional on the method to take effect?

### ISSUE THREAD

**Issue by wjwei** [apache/incubator-shardingsphere#3465]
Configured a local transaction, found that only @transactional can be added to the method to take effect, resulting in some single update operation in the project plus @transactional annotation, it feels very troublesome. I don't know if I haven't configured it myself, or does the local transaction of shardingsphere have to add @transactional annotation to the method to take effect?

**Comment by terrymanu** [comment]
What is your version of shardingsphere?

**Comment by terrymanu** [comment]
Will close soon if no response anymore
