### ISSUE TITLE
Bug Report, java.lang.ClassCastException. 

### ISSUE THREAD

**Issue by HongJinFeng** [apache/incubator-shardingsphere#3466]
## Bug Report

1. Bug occur when jdbcType is tinyint(1) and java type is Integer, but sharding-jdbc convert the value to boolean.
2. Here is the core position.
org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.EncryptResultSet.getInt(final String columnLabel)

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Reason analyze (If you can)
In MySql ,tinyInt(1) is same with boolean type, it probable sharding-sphere make an error value cover here.

**Comment by yanickxia** [comment]
Seem 4.0.0-RC3 fixed it. ![#3311](https://github.com/apache/incubator-shardingsphere/commit/22f3d49f18b8a91487c095a9676bf40e3129f131)

**Comment by HongJinFeng** [comment]
Got it. It worked after config my datasource 'tinyInt1isBit=false'. In addition, When 4.0.0-RC3 can be found in maven central repository?
