### ISSUE TITLE
Query the column information of the table through SQL statement

### ISSUE THREAD

**Issue by waterMeteors** [apache/incubator-shardingsphere#3472]
I query the field infromation of the table with the "select COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_NAME='goods'" statement,but result is null.
the "goods" is the source table of subtable. 

I found through debug that the reason is that the information stored in the mysql database is 
the subtable information ,so it cannot be obtained.

if I want query the column information of the table by source table names,what  to do .

**Comment by terrymanu** [comment]
duplicate with #1176
