### ISSUE TITLE
Establish SQL parser module development document adapt to various databases

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-shardingsphere#3475]
## Question

According to the current situation, incubator-shardingsphere SQL parser module already supports many databases like MySQL, Oracle etc, which module some bugs or issues exists. Development document is very important for SQL parser modules, which facilitate community developers to participate faster.About development document, I think it needs to include the following points:
- How to add SQL parse grammar?
- How to design g4 file?
- How to bug troubleshooting？
- How to write test case for modified grammar？

**Comment by terrymanu** [comment]
Yes, the document is really important. We can improve the document continually.

**Comment by tianbin1001** [comment]
@terrymanu  Assign to Me

**Comment by terrymanu** [comment]
@tianbin1001 OK, welcome to contribute together.

**Comment by tianbin1001** [comment]
Parser is changing, unable to write the document for the time being,
