### ISSUE TITLE
Sharding-JDBC "inline.algorithm-expression"  capital letter bug

### ISSUE THREAD

**Issue by ityy** [apache/incubator-shardingsphere#3480]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```java
    @Column(name = "USER_ID", nullable = false)
    private Long userId;
```

`sharding.jdbc.config.sharding.tables.MY_FRIEND.table-strategy.inline.algorithm-expression=test.MY_FRIEND_$->{USER_ID % 10}`

The precise-algorithm-class-name is good, but inline.algorithm-expression is error: **can't mod() null object**

**Comment by terrymanu** [comment]
Is your USER_ID `null`?

**Comment by ityy** [comment]
> Is your USER_ID `null`?

it's not null.
if you use "@Column(name = "USER_ID", nullable = false)",  then 'MY_FRIEND_$->{USER_ID % 10}' or 'MY_FRIEND_$->{user_id % 10}' all error.
if you use "@Column(name = "user_id", nullable = false)", then 'MY_FRIEND_$->{USER_ID % 10}' is error, but 'MY_FRIEND_$->{user_id % 10}' is ok.
if you use 'precise-algorithm-class-name', all is ok.
The reason for the submission is lack of uniformity,'@Column' and 'inline expression'.

**Comment by terrymanu** [comment]
Can you provide your sharding rule configuration?

**Comment by ityy** [comment]
> Can you provide your sharding rule configuration?

I didn't describe it clearly, Now I think I'm clear. I'm sorry.
```java
 @Column(name = "USER_ID")
private Long userId;
```
```xml
spring.shardingsphere.sharding.tables.my_friend.table-strategy.inline.sharding-column=USER_ID
spring.shardingsphere.sharding.tables.my_friend.table-strategy.inline.algorithm-expression=my_friend_$->{USER_ID % 10}
```
Looks ok, but error:
`java.lang.NullPointerException: Cannot invoke method mod() on null object`

Now let's change that:
```xml
spring.shardingsphere.sharding.tables.my_friend.table-strategy.inline.sharding-column=USER_ID
spring.shardingsphere.sharding.tables.my_friend.table-strategy.inline.algorithm-expression=my_friend_$->{user_id % 10}
```
run well.

The issues is simply that inline.algorithm-expression don't support uppercase.

It's a minor problem, It just doesn't look consistent.

**Comment by terrymanu** [comment]
the algorithm-expression may support uppercase, the `USER_ID` is just a variable name of groovy expression, so the algorithm-expression should match the variable which user defined and in the inline expressions.

**Comment by terrymanu** [comment]
The problem caused by ShardingSphere transform the sharding column to lowercase to case insensitive reason.
I think this is a bug, we can keep it open and let some one fix it.
