### ISSUE TITLE
no table rout info 

### ISSUE THREAD

**Issue by WatchLucky** [apache/incubator-shardingsphere#3481]
## Question

there is a propleam when   I insert one record by sharding-proxy :   no . table  rout info

configuration : 

    t_rpm_sharejrn:
      actualDataNodes: db_gsdbil0.t_rpm_sharejrn${0..31},db_gsdbil1.t_rpm_sharejrn${32..63},db_gsdbil2.t_rpm_sharejrn${64..95},db_gsdbil3.t_rpm_sharejrn${96..127},db_gsdbil4.t_rpm_sharejrn${128..159},db_gsdbil5.t_rpm_sharejrn${160..191},db_gsdbil6.t_rpm_sharejrn${192..223},db_gsdbil7.t_rpm_sharejrn${224..255},db_gsdbil8.t_rpm_sharejrn${256..287},db_gsdbil9.t_rpm_sharejrn${288..319},db_gsdbil10.t_rpm_sharejrn${320..351},db_gsdbil11.t_rpm_sharejrn${352..383},db_gsdbil12.t_rpm_sharejrn${384..415},db_gsdbil13.t_rpm_sharejrn${416..447},db_gsdbil14.t_rpm_sharejrn${448..479},db_gsdbil15.t_rpm_sharejrn${480..511},db_gsdbil16.t_rpm_sharejrn${512..543},db_gsdbil17.t_rpm_sharejrn${544..575},db_gsdbil18.t_rpm_sharejrn${576..607},db_gsdbil19.t_rpm_sharejrn${608..639},db_gsdbil20.t_rpm_sharejrn${640..671},db_gsdbil21.t_rpm_sharejrn${672..703},db_gsdbil22.t_rpm_sharejrn${704..735},db_gsdbil23.t_rpm_sharejrn${736..767},db_gsdbil24.t_rpm_sharejrn${768..799},db_gsdbil25.t_rpm_sharejrn${800..831},db_gsdbil26.t_rpm_sharejrn${832..863},db_gsdbil27.t_rpm_sharejrn${864..895},db_gsdbil28.t_rpm_sharejrn${896..927},db_gsdbil29.t_rpm_sharejrn${928..959},db_gsdbil30.t_rpm_sharejrn${960..991},db_gsdbil31.t_rpm_sharejrn${992..1023}
      databaseStrategy:
        complex:
          shardingColumns: merc_id,cre_dt   
          algorithmClassName: com.murong.ecp.bp.shardingjdbc.algorithm.Mr32DbAlgorithmC
      tableStrategy:
        complex:
          shardingColumns: merc_id,cre_dt        
          algorithmClassName: com.murong.ecp.bp.shardingjdbc.algorithm.Mr1024TbAlgorithmC

I can create table  and drop table  through proxy  

and my sql  contains . shardingColumns .

**Comment by WatchLucky** [comment]
Server version: 5.6.0-Sharding-Proxy 3.1.0

**Comment by terrymanu** [comment]
What is your SQL?

**Comment by terrymanu** [comment]
Will close soon if no response anymore
