### ISSUE TITLE
Encrypt-JDBC Rewrite SQL paramters with the wrong column order

### ISSUE THREAD

**Issue by HongJinFeng** [apache/incubator-shardingsphere#3483]
##
Run an insert sql with more than one encrypt column, and some of columns are null, encrypt-jdbc rewrite a wrong sql which plain columns are out of order.But if I set the null columns to "". it rewrite an correct sql.

sharding-sphere version 4.0.0-RC2

##
And then i update my sharding-sphere version to 4.0.0-RC3-SNAPSHOT, run the same sql as before, another bug occur.
![image](https://user-images.githubusercontent.com/33616750/68462165-f33c4100-0246-11ea-8061-af648d48e6be.png)

**Comment by terrymanu** [comment]
Fixed at 4.0.0-RC3

**Comment by terrymanu** [comment]
duplicate with #3374
