### ISSUE TITLE
Paging subquery problem

### ISSUE THREAD

**Issue by lyricsqq** [apache/incubator-shardingsphere#3496]
Version number  4.0.0-RC2：
When I execute the following SQL：
select  count(0) from (         select devId         from t_check_task where status=1                                           and executeTime BETWEEN '2018' and '2019'                    ) b

我发现只要我使用 BETWEEN and  他有问题
I find that as long as I use between and he has problems

他会抛出如下异常
it will throw the following exception：
The exception is generated in the parsingsqlrouter class  in isSameShardingCondition 
Cause: java.lang.ClassCastException: org.apache.shardingsphere.core.strategy.route.value.RangeRouteValue cannot be cast to org.apache.shardingsphere.core.strategy.route.value.ListRouteValue]

我发下 使用范围 查找 他产生的是 RangeRouteValue 对象 而不是 ListRouteValue 。那么在这个地方进行强制转型合理吗
I sent to use range to find out that what he generated was rangeroutevalue object instead of listroutevalue. Is it reasonable to carry out compulsory transformation in this place

**Comment by lyricsqq** [comment]
Does it not support between and. It is clear that the description on the document does not support it

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
