### ISSUE TITLE
UUID. Randomuuid() causes a large number of database operation threads to lock (DQL & & non DQL)

### ISSUE THREAD

**Issue by BigBoss812** [apache/incubator-shardingsphere#3499]
### Which version of ShardingSphere did you use?

2.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

sharding-jdbc-core-spring-boot-starter Sharding-JDBC

### Expected behavior

Generate application and perform DQL or  non DQL data operation for 500 threads concurrently

### Actual behavior

Use the jstack command to export the thread stack and repeat the operation many times. It is found that about 60% of the 500 threads are blocked

### Reason analyze (If you can)

It's speculated that the performance of UUID. Randomuuid() in io.shardingjdbc.core.executor.event.abstractexecutionevent will cause the class constant ID

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
The version is out of service, please try to newer version

**Comment by canglang1973** [comment]
Yes , you can user the last version of Sharding-jdbc ,your version is too old to good use.
