### ISSUE TITLE
Can we add key-value to hint?

### ISSUE THREAD

**Issue by ityy** [apache/incubator-shardingsphere#3504]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
See the following code, HintShardingValue only values without keys. If I want to customize external parameters, I can only use the following method. 
Can we add key-value to hint? Thanks.

```java
    public void testHintInsert() {
        HintManager instance = HintManager.getInstance();
        instance.addTableShardingValue("my_friend", "prefix_my_friend");
        instance.addTableShardingValue("my_friend", "suffix_8");
        MyFriendEntity friendEntity = new MyFriendEntity();
        friendEntity.setMyFriendId(new MyFriendEntityId(3L, 5L));
        friendEntity.setAddDate(LocalDateTime.now());
        myFriendDao.save(friendEntity);
    }
```

 ```java
public Collection<String> doSharding(Collection availableTargetNames, HintShardingValue shardingValue) {
        Collection values = shardingValue.getValues(); //There are only values and no names
                                               // i have to  concatenate strings
                                               // like the following code
        String prefix = null;
        String suffix = null;
        for (Object value : values) {
            String s = value.toString();
            if (s.charAt(0) == 'p') {
                prefix = s.substring(7);
            } else if (s.charAt(0) == 's') {
                suffix = s.substring(7);
            }
        }
        StringBuilder sb = new StringBuilder();
        sb.append(prefix);
        sb.append("_");
        sb.append(suffix);
        Collection<String> result = new HashSet<>();
        result.add(sb.toString()); // my_friend_8
        return result;
    }
```

**Comment by terrymanu** [comment]
ShardingSphere is a database middle, this feature is like sdk side, but shardingsphere has proxy side too, how to deal with the feature on proxy side?

**Comment by ityy** [comment]
> ShardingSphere is a database middle, this feature is like sdk side, but shardingsphere has proxy side too, how to deal with the feature on proxy side?

You are right. this feature is sdk side, I can assemble value before addTableShardingValue().  
I don't think I need key-value in doSharding().
Thank you very much!
