### ISSUE TITLE
Encrypt jdbc bug occur when cipher column value is not from method parameter.

### ISSUE THREAD

**Issue by HongJinFeng** [apache/incubator-shardingsphere#3509]
1.Below cases work normally.

```sql
UPDATE t_demo SET username = CONCAT('xxx','xxxx') WHERE id in (#{id1},#{id2},#{id3})
UPDATE t_demo SET username = ‘xxx’ WHERE id in (#{id1},#{id2},#{id3})
UPDATE t_demo SET username = #{username} WHERE id in (#{id1},#{id2},#{id3})
```

2.But in these cases, exception occurs.
Using encrypt-jdbc, and username is one of encrypt column.

```sql
create t_demo{
   id int,
    username varchar(20),
    username_encrypt(64)
};

UPDATE t_demo SET username = CONCAT(username,'xxx') WHERE id in (#{id1},#{id2},#{id3})
UPDATE t_demo SET username = CONCAT(username,'xxx',UNIX_TIMESTAMP()) WHERE id in (#{id1},#{id2},#{id3})
UPDATE t_demo SET username = CONCAT(username,UNIX_TIMESTAMP()) WHERE id in (#{id1},#{id2},#{id3})
UPDATE t_demo SET username = username WHERE id in (#{id1},#{id2},#{id3})
```
encrypt rule configuration:
spring.shardingsphere.datasource.name = ds
spring.shardingsphere.datasource.ds.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds.driver-class-name = com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds.url = xxx
spring.shardingsphere.datasource.ds.username = xxx
spring.shardingsphere.datasource.ds.password = xxx
spring.shardingsphere.encrypt.encryptors.encryptor_aes.type = AES
spring.shardingsphere.encrypt.encryptors.encryptor_aes.props.aes.key.value =
spring.shardingsphere.encrypt.tables.t_demo.columns.username.plainColumn = username
spring.shardingsphere.encrypt.tables.t_demo.columns.username.cipherColumn = username_encrypt
spring.shardingsphere.encrypt.tables.t_demo.columns.username.encryptor = encryptor_aes

All Update SQL throw exception.

3.Here is one of the rewrite SQL:

```sql
update t_demo set username = ?, username_encrypt = ? where resourceid in (?,?,?) 
```

![image](https://user-images.githubusercontent.com/33616750/68661614-33b4fb00-0576-11ea-8179-3751c59c2f9a.png)

4.Version
sharding-sphere 4.0.0-RC2

5.Personal view
The exception throw might because the plain column's value is from MySQL but not method parameters, and encrypt jdbc can not get the cipher column value in core. It may cause this exception. In my opinion, encrypt jdbc can just omit this cipher column, but not throws an exception,  or It is maybe exist a better way to handle with it.

**Comment by terrymanu** [comment]
Can you describe the summary in title for search friendly?

**Comment by terrymanu** [comment]
What' mean of `core parameter`?
I saw your SQL


```sql
update seewo_sys_users set username = ?, username_encrypt = ? where resourceid in (?,?,?)
```
what is the table `seewo_sys_users`, what is different with previous table `t_demo`?

**Comment by terrymanu** [comment]
Will close soon if no response anymore

**Comment by HongJinFeng** [comment]
1. It is method parameter.
2. Not seewo_sys_users,It is t_demo.

**Comment by terrymanu** [comment]
What is your encrypt rule configuration?

**Comment by terrymanu** [comment]
Can you fix the title about `core parameter`?

**Comment by terrymanu** [comment]
Hi, will close soon if no response anymore

**Comment by HongJinFeng** [comment]
Hi, mabey you can try my sql. But note to this:
![image](https://user-images.githubusercontent.com/33616750/69511340-aeb8e100-0f7a-11ea-81fd-1d45cfc4f174.png)

**Comment by terrymanu** [comment]
I have 2 suggestions, maybe you can have try:

1. Version 4.0.0-RC3 is released, some of encrypt bugs are fixed, you can try to this version
2. If the issue still existed, please provide the log of `sql.show`.

Another suggestion is could you use code to instead of screenshot? Screenshot cannot search by other people.

**Comment by HongJinFeng** [comment]
The new Version fixed this bugs.
