### ISSUE TITLE
Full GC occured Frequently in production environment

### ISSUE THREAD

**Issue by lcx1989210** [apache/incubator-shardingsphere#3515]
server details:
-Xms10g -Xmx10g -Xmn8g -Xss1024K

java version "1.8.0_66"

sharding version:
 <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-core</artifactId>
            <version>3.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>3.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>3.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-orchestration-spring-namespace</artifactId>
            <version>3.1.0</version>
        </dependency>

database info：
db0: order0 ~ order255
db1: order256 ~ order 512

 after I restart the application server， and got some client request. the server`s mem will not enough,and it will be occured Full gc frequently .such as:
     S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
  0.00   0.00 100.00  66.72  98.49  97.35     15   12.833    12   90.565  103.398
  0.00   0.00 100.00  66.72  98.49  97.35     15   12.833    12   90.565  103.398
  0.00   0.00 100.00  66.72  98.49  97.35     15   12.833    12   90.565  103.398
  0.00   0.00 100.00  66.72  98.49  97.35     15   12.833    12   90.565  103.398
  0.00   0.00 100.00  67.12  98.50  97.35     16   12.833    14  102.344  115.178
  0.00   0.00 100.00  67.12  98.50  97.35     16   12.833    14  102.344  115.178
  0.00   0.00 100.00  67.12  98.50  97.35     16   12.833    14  102.344  115.178
  0.00   0.00 100.00  67.12  98.50  97.35     16   12.833    14  102.344  115.178
  0.00   0.00 100.00  67.12  98.50  97.35     16   12.833    14  102.344  115.178

 then i dump the memory info and analyse it by MAT, it shows there are 12048024  io.shardingsphere.core.routing.type.TableUnit in the mem,and it occupy much mem.

I want to know what cause this full gc where process client request,Please give me a hand!! 
thanks...

**Comment by terrymanu** [comment]
What is your SQL, sharding rule configuration and log of `sql.show`?

**Comment by lcx1989210** [comment]
This problem makes me very  confused. After I restart the application server, The first few requests may cause this problem(full gc ),after which the request will be normal，and the memory normal. 

My  SQL, sharding rule configuration as follows：
![QQ图片20191114144910](https://user-images.githubusercontent.com/21120592/68833664-ffb11580-06ee-11ea-9cb6-62920ca26700.png)


and my sql is :

 select 
        o.id id, o.source_order_code source_order_code, o.user_id user_id, o.source_order_type source_order_type,  o.price price,o.created_at created_at, o.modified_at modified_at, o.mer_id mer_id, o.pay_id pay_id,o.extension1 extension1,o.extension2 extension2,
        b.status status,b.begin_at begin_at, b.end_at end_at, b.amount amount, b.amount_left amount_left, b.product_code product_code, b.categorys categorys, b.citys citys, b.owner_id owner_id,b.is_city is_city,b.is_cate is_cate,b.priority priority
        from order o
        inner join balance b
        on o.id = b.order_id
        where o.user_id = ?
        and b.user_id = ?
        and b.user_type = ?
        and o.user_type = ?
        and b.product_code= ?
        and b.status = ?       
        and b.is_city = ?
        and    b.begin_at < unix_timestamp(current_timestamp(3))*1000  
        and    b.end_at > unix_timestamp(current_timestamp(3))*1000  
        and    b.amount_left > 0  

To solve this problem, what should I do now?

**Comment by terrymanu** [comment]
What is the table configuration for `balance`?

**Comment by lcx1989210** [comment]
![image](https://user-images.githubusercontent.com/21120592/68842898-1d3baa80-0702-11ea-9be5-4b54ebcd46d4.png)

You can see  the table configuration for balance  from the picture above

**Comment by lcx1989210** [comment]
During my testing today,I found some userId have no sharding-rule.

![0VN E8L ~X{6(HP(%EC4 8D](https://user-images.githubusercontent.com/21120592/68856151-cabab800-071a-11ea-944f-bd25c1ae4a5a.png)

This userId 62498484925194  query all table order and balance, It seems that the sharding rule does not work. So, When is the sharding  rule not working?

**Comment by terrymanu** [comment]
It is not good for screenshot for coding, it is hard to search or try to reproduce

**Comment by lcx1989210** [comment]
the main configuration as follows:

  <bean id="randomStrategy" class="io.shardingsphere.api.algorithm.masterslave.RandomMasterSlaveLoadBalanceAlgorithm" />
    <bean id="dataBaseAlgorithm" class="com.resource.algorithm.PreciseModuloDatabaseShardingAlgorithm" />
    <bean id="tableAlgorithm" class="com.resource.algorithm.PreciseModuloTableShardingAlgorithm" /> 
 <sharding:standard-strategy id="databaseShardingStrategy" sharding-column="user_id" precise-algorithm-ref ="dataBaseAlgorithm"/>
    
    <sharding:standard-strategy id="tableShardingStrategy" sharding-column="user_id"  precise-algorithm-ref ="tableAlgorithm"/>

    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule
                data-source-names="resourceWriteDataSource_0,resourceWriteDataSource_1,resourceReadDataSource_0,resourceReadDataSource_1">
            <sharding:master-slave-rules>
                <sharding:master-slave-rule id="masterSlaveDataSource_0"
                                            master-data-source-name="resourceWriteDataSource_0"
                                            slave-data-source-names="resourceReadDataSource_0"
                                            strategy-ref="randomStrategy"/>
                <sharding:master-slave-rule id="masterSlaveDataSource_1"
                                            master-data-source-name="resourceWriteDataSource_1"
                                            slave-data-source-names="resourceReadDataSource_1"
                                            strategy-ref="randomStrategy"/>
            </sharding:master-slave-rules>
            <sharding:table-rules>
                <sharding:table-rule logic-table="order"
                                     actual-data-nodes="masterSlaveDataSource_0.order_$->{0..255},masterSlaveDataSource_1.order_$->{256..511}"
                                     database-strategy-ref="databaseShardingStrategy"
                                     table-strategy-ref="tableShardingStrategy" generate-key-column-name="id"/>
                <sharding:table-rule logic-table="product"
                                     actual-data-nodes="masterSlaveDataSource_0.product_$->{0..255},masterSlaveDataSource_1.product_$->{256..511}"
                                     database-strategy-ref="databaseShardingStrategy"
                                     table-strategy-ref="tableShardingStrategy" generate-key-column-name="id"/>
                <sharding:table-rule logic-table="balance"
                                     actual-data-nodes="masterSlaveDataSource_0.balance_$->{0..255},masterSlaveDataSource_1.balance_$->{256..511}"
                                     database-strategy-ref="databaseShardingStrategy"
                                     table-strategy-ref="tableShardingStrategy" generate-key-column-name="id"/>
                <sharding:table-rule logic-table="consume"
                                     actual-data-nodes="masterSlaveDataSource_0.consume_$->{0..255},masterSlaveDataSource_1.consume_$->{256..511}"
                                     database-strategy-ref="databaseShardingStrategy"
                                     table-strategy-ref="tableShardingStrategy" generate-key-column-name="id"/>

                <sharding:table-rule logic-table="package_order"
                                     actual-data-nodes="masterSlaveDataSource_0.package_order_$->{0..255},masterSlaveDataSource_1.package_order_$->{256..511}"
                                     database-strategy-ref="databaseShardingStrategy"
                                     table-strategy-ref="tableShardingStrategy" generate-key-column-name="id"/>

                <sharding:table-rule logic-table="allocation"
                                     database-strategy-ref="databaseShardingStrategy"
                                     actual-data-nodes="masterSlaveDataSource_$->{0..1}.allocation"/>

                <sharding:table-rule logic-table="payment"
                                     database-strategy-ref="databaseShardingStrategy"
                                     actual-data-nodes="masterSlaveDataSource_$->{0..1}.payment"/>

                <sharding:table-rule logic-table="biz_consume_process_buffer"
                                     database-strategy-ref="databaseShardingStrategy"
                                     actual-data-nodes="masterSlaveDataSource_$->{0..1}.biz_consume_process_buffer"/>
            </sharding:table-rules>

            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="order, product" />
                <sharding:binding-table-rule logic-tables="order, product, balance" />
                <sharding:binding-table-rule logic-tables="order, balance" />
            </sharding:binding-table-rules>

            
                
                
            

        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">${sql.show}</prop>
            <prop key="check.table.metadata.enabled">false</prop>
        </sharding:props>
    </sharding:data-source>

The query sql as follows:
      select 
        o.id id, o.source_order_code source_order_code, o.user_id user_id, o.source_order_type source_order_type,  o.price price,o.created_at created_at, o.modified_at modified_at, o.mer_id mer_id, o.pay_id pay_id,o.extension1 extension1,o.extension2 extension2,
        b.status status,b.begin_at begin_at, b.end_at end_at, b.amount amount, b.amount_left amount_left, b.product_code product_code, b.categorys categorys, b.citys citys, b.owner_id owner_id,b.is_city is_city,b.is_cate is_cate,b.priority priority
        from order o
        inner join balance b
        on o.id = b.order_id
        where o.user_id = ?
        and b.user_id = ?
        and b.user_type = ?
        and o.user_type = ?
        and b.product_code= ?
        and b.status = ?       
        and b.is_city = ?
        and    b.begin_at < unix_timestamp(current_timestamp(3))*1000  
        and    b.end_at > unix_timestamp(current_timestamp(3))*1000  
        and    b.amount_left > 0

**Comment by lcx1989210** [comment]
This problem is very makes me confused。
There are a total of 100 test userId. When I used 10 thread test, the sharding rule not working on abount 5 userId, so they Full table sweep. The results of each test are different, There are always some userId does not go the sharding rule.If I test a few more times(or the server has been running for a while ), this problem will not exist.

**Comment by lcx1989210** [comment]
And I have your QQ number, may I  communicate with it. So I can give you more infomation.

**Comment by lcx1989210** [comment]
Hi, are u here ?
I continued the test this days and I should have found what case the problem.
The class io.shardingsphere.core.routing.type.standard.StandardRoutingEngine, I added some log printing to the method routeByShardingConditions.

![LNL40GA%UR~TW4R4V V U71](https://user-images.githubusercontent.com/21120592/69006862-727cf380-0970-11ea-9f9c-55e633d199db.png)

In some case ,  shardingConditions.getShardingConditions().isEmpty()=true.

![}XG$A@_TVVWW8}S~42`F02](https://user-images.githubusercontent.com/21120592/69006918-6a718380-0971-11ea-95a0-ae45e4665bec.png)

The  Collection<DataNode> will contains all 512 order tabls and all 512 balance tabls in this situation.

And in some case,shardingConditions.getShardingConditions().isEmpty()=false.
![O(IHM(~JOTCYB04WVAZTL}Q](https://user-images.githubusercontent.com/21120592/69006944-e5d33500-0971-11ea-80f3-7336311ad35e.png)
The  Collection<DataNode> will contains the order table and balance table sharding by userId  in this situation.

![43MLZTLBMARNEKCR@YN7_2E](https://user-images.githubusercontent.com/21120592/69006989-93464880-0972-11ea-953f-eed6642c8e5e.png)

So, does the   shardingConditions.getShardingConditions().isEmpty()   is not thread safety? 
In which case it return TRUE ? 
What can I do to avoid this Full GC problem?

**Comment by lcx1989210** [comment]
This problem bothers me really for a long time. Can you give me some suggestion?

**Comment by lcx1989210** [comment]
@terrymanu  @dongzl
Can  you give me some advice to help me solve this problem?

**Comment by dongzl** [comment]
Hi @lcx1989210 ,

First your version is 3.1.0, it is older version, you can try 4.0.0-RC2 version and found the same problem or not.

Second I found you define the `databaseShardingStrategy` and `tableShardingStrategy` yourself, 
can you provide their code?

Finally, can you provide a test project for this problem, we can reproduce it.

**Comment by lcx1989210** [comment]
First, may I use the version  4.0.0-RC2  in my production environment? Is it a stable version?

![O_(N%SFJ`0IC0S9(JRY~6N7](https://user-images.githubusercontent.com/21120592/69043623-5dff3080-0a2e-11ea-8382-b2d6a105f5e5.png)


![)QEH20{M3I~AHPS3_FJ~ SS](https://user-images.githubusercontent.com/21120592/69043730-90109280-0a2e-11ea-8881-7f96b18c9c4a.png)

![RVW PVJNOF_(XYU}@031S(1](https://user-images.githubusercontent.com/21120592/69044271-981d0200-0a2f-11ea-89d5-9339a221bf28.png)

You can see these code logic at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.
In my test, I found that shardingConditions.getShardingConditions().isEmpty() return a TRUE value in the method routeByShardingConditions(final TableRule tableRule),and the code will  get the method route(final TableRule tableRule, final List<ShardingValue> databaseShardingValues, final List<ShardingValue> tableShardingValues) . I found databaseShardingValues.isEmpty() will  return a TRUE value in the method   routeDataSources(final TableRule tableRule, final List<ShardingValue> databaseShardingValues). So that it can not call my sharding rule like databaseShardingStrategy and tableShardingStrategy.

I will give you a test case later.

**Comment by lcx1989210** [comment]
Hi, @dongzl,  Please give me a hand.
The class io.shardingsphere.core.parsing.antlr.AntlrParsingEngine and method parse().

![~_9LIP7DAA(TY7 8 T7}HRE](https://user-images.githubusercontent.com/21120592/69216030-1996a080-0ba6-11ea-9d19-6976afe474fa.png)

I met a problem，Some column have no tableName after the method  Collection<SQLSegment> sqlSegments = extractorEngine.extract(ast); .In which case ,the column have no tableName,
The code logic of  code block  is a little more complicated, I can't understand it。

![D96CW`LZQRH6$ZBYBO~XL`H](https://user-images.githubusercontent.com/21120592/69216713-d0dfe700-0ba7-11ea-8723-509b2b6ef606.png)


The query sql as follows:
select
o.id id, o.source_order_code source_order_code, o.user_id user_id, o.source_order_type source_order_type, o.price price,o.created_at created_at, o.modified_at modified_at, o.mer_id mer_id, o.pay_id pay_id,o.extension1 extension1,o.extension2 extension2,
b.status status,b.begin_at begin_at, b.end_at end_at, b.amount amount, b.amount_left amount_left, b.product_code product_code, b.categorys categorys, b.citys citys, b.owner_id owner_id,b.is_city is_city,b.is_cate is_cate,b.priority priority
from order o
inner join balance b
on o.id = b.order_id
where o.user_id = ?
and b.user_id = ?
and b.user_type = ?
and o.user_type = ?
and b.product_code= ?
and b.status = ?
and b.is_city = ?
and b.begin_at < unix_timestamp(current_timestamp(3))*1000
and b.end_at > unix_timestamp(current_timestamp(3))*1000
and b.amount_left > 0

**Comment by terrymanu** [comment]
Hi, there are lots of information, I cannot get the point.
Maybe we can start to discuss at describe the gc or unexpected behaviour, we can analyze code later.

Your question is `Why sometimes SQL execute into all tables without sharding route, right?`

**Comment by lcx1989210** [comment]
Yes. The main question is Why sometimes SQL execute into all tables without sharding route?
 The above information is my analysis. 
I found When the return value have no tableNmae in the method Collection sqlSegments = extractorEngine.extract(ast) ,then it will query  without sharding route.

Does the  method Collection sqlSegments = extractorEngine.extract(ast) use asyn when the server application just restart?

**Comment by terrymanu** [comment]
Can you provide the log of `sql.show`?

**Comment by terrymanu** [comment]
Closed because no response for long time.
