### ISSUE TITLE
How do I use user-defined sharding algorithms in sharding-proxy？

### ISSUE THREAD

**Issue by Kevy123** [apache/incubator-shardingsphere#3521]
## sql 
```
## table schema
db_1
   - user_info
db_2
  - user_info
db_3
  - user_info
```
the shardingColumn is `cid`; For example, the `cid=59` data will be in the db_1 ,the `cid=60` data will be in the db_2....

I just want database sharding. not table sharding

**Comment by terrymanu** [comment]
What is the reason for closing the issue?
