### ISSUE TITLE
With Oracle 11g: Tables or View does no exsit

### ISSUE THREAD

**Issue by pengleichen** [apache/incubator-shardingsphere#3524]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
With SpringBoot2.x and Oracle11g, We will get a SQLStntaxErrorException: table or view does no exsit. After research, we get the ShardingSphere will scan the all tables in the Oracle DB(XE) and analyze these tables, but the DB account can't be had all privileges. So, occurred error, the spring boot can't be startup.
### Reason analyze (If you can)
ShardingJDBC version 3.x don't scan the all table, so it can be startup, but 4.x does not start

**Comment by terrymanu** [comment]
Is it same with #3446?

**Comment by pengleichen** [comment]
Class: TableMetaDataInitializer
![image](https://user-images.githubusercontent.com/13282475/68915303-5f192f00-079c-11ea-9f57-d33a4d7459dd.png)
There will not exclude the all oracle system tables, e.g. 
![image](https://user-images.githubusercontent.com/13282475/68915346-9ab3f900-079c-11ea-9b04-82b84a94ab85.png)

When start the application, we get an error 
![image](https://user-images.githubusercontent.com/13282475/68915404-e9619300-079c-11ea-90b2-ac96e4e67b2b.png)

We track the issue for source code, 
![image](https://user-images.githubusercontent.com/13282475/68915547-83294000-079d-11ea-8a3e-df1ea37ffd47.png)
![image](https://user-images.githubusercontent.com/13282475/68915558-8ae8e480-079d-11ea-9656-a40164ff5381.png)

Do you have any good solution, thank you very much!

**Comment by tristaZero** [comment]
@pengleichen  Hi This issue seems to be fixed in #3541, can you install dev branch and give a test?

**Comment by tristaZero** [comment]
@beijing-penguin Please fix it, thanks.

**Comment by beijing-penguin** [comment]
@pengleichen I fix the issue，but unable to verify the changing code ，please you can change shardingsphere project git branch to my upstream/dev to rerun your code

①cmd run 
`git remote add upstream https://github.com/beijing-penguin/incubator-shardingsphere.git`
②idea git tools switch git branch   "upstream/dev branch"
