### ISSUE TITLE
Does shardingshpere have reload configuration function?

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#3530]
Does shardingshpere have reload configuration function?

If I reconfig my configuration, how could I make it valid besides restart the sharding-proxy?

**Comment by terrymanu** [comment]
Please FYI: https://shardingsphere.apache.org/document/current/en/features/orchestration/config-center/

**Comment by ssxlulu** [comment]
@terrymanu Should we add reload config command to valid configuration in local mode?

**Comment by terrymanu** [comment]
Just use Orchestration module to control your configuration dynamiclly

**Comment by ssxlulu** [comment]
> Just use Orchestration module to control your configuration dynamically

Yes, So I found it is not convenient for local mode, when I modified any configuration, I need restart the server. It may be not friendly for local debugging.

**Comment by dongzl** [comment]
Hi @ssxlulu , what's your meaning, do you want to fix configuration in local yaml file and make effective right now?

**Comment by dongzl** [comment]
the configuration will be loaded into Orchestration center, e.g ZooKeeper, fix the configuration in ZK directly?

**Comment by ssxlulu** [comment]
> Hi @ssxlulu , what's your meaning, do you want to fix configuration in local yaml file and make effective right now?

I mean, when I modify the configuration in local yaml file, we may have some command to reload the configuration rather than restart the server.

**Comment by dongzl** [comment]
> > Hi @ssxlulu , what's your meaning, do you want to fix configuration in local yaml file and make effective right now?
> 
> I mean, when I modify the configuration in local yaml file, we may have some command to reload the configuration rather than restart the server.

I think fix the configuration in ZooKeeper will be effective right now and meet your requirements.

`when modify the configuration in local yaml file,  execute some command to reload the configuration rather than restart the server.`

I think it doesn't support at present. Of course it's a good idea and we can develop it.

**Comment by dongzl** [comment]
Hi @ssxlulu , Do you have any other problems?

**Comment by ssxlulu** [comment]
Close this issue for no quesiton.
