### ISSUE TITLE
 Factory method 'dataSource' threw exception; nested exception is io.shardingsphere.core.exception.ShardingException: java.sql.SQLException: Column name pattern can not be NULL or empty.

### ISSUE THREAD

**Issue by Spacebody** [apache/incubator-shardingsphere#3532]
## Question
I have two database with 4 tables in each.
db0{tbl0,tbl1,xtbl0,xtbl1}
db1{tbl2,tbl3,xtbl2,xtbl3}

I have configure application.properties but no datasource configuration. Is this problem means I should manually implement the datasource configuration?

Sorry for no demo code provided since the code should be private.

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
What is your version, SQL and sharding rule configuration?

**Comment by Spacebody** [comment]
4.0.0.RC2，sql 5.6,  two databases with 4 tables in each. I want to check
that whether should I implement the datasource. Besides, I have other
databases in the same project such as mongodb, mysql, they are correctly
configured and being used already, I want to use sharding-jdbc to configure
another database in the same project.

Liang Zhang <notifications@github.com> 于2019年11月16日周六 上午10:58写道：

**Comment by dongzl** [comment]
According to this issue's title, `io.shardingsphere.core.exception.ShardingException` is very old version, not `4.0.0.RC2`, do I make misunderstanding?

**Comment by Spacebody** [comment]
Oh, sorry for forgetting my change of code. Originally I used
sharding-jdbc-spring-boot-starter 3.1.0, and I encountered this problem.

董宗磊 <notifications@github.com> 于2019年11月16日周六 下午9:05写道：
