### ISSUE TITLE
doc error

### ISSUE THREAD

**Issue by lwl888** [apache/incubator-shardingsphere#3540]
3.2 Read separation -3.2.3 does not support items
1. The data synchronization between the main library and the from the library.
2. Data inconsistencies caused by data synchronization delays between the primary and primary libraries.

The first item says that data synchronization between the primary and the store is not supported, and the second item says that data synchronization delay between the primary and the store is not supported.

It's a contradiction

**Comment by dongzl** [comment]
Hi @lwl888 ,
**For English only**, other languages will not accept.

I think you can submit a new issue in English on incubator-shardingsphere-doc's issue list.

https://github.com/apache/incubator-shardingsphere-doc/issues

**Comment by lwl888** [comment]
update commited

**Comment by lwl888** [comment]
Chinese doc error

**Comment by terrymanu** [comment]
Hi, Can you submit a pull request to fix this?

**Comment by lwl888** [comment]
This error appears in the official document, which appears to be without the document in the project

**Comment by terrymanu** [comment]
FIY: https://shardingsphere.apache.org/community/en/contribute/document-contributor/

**Comment by terrymanu** [comment]
Fixed https://github.com/apache/incubator-shardingsphere-doc/issues/360
