### ISSUE TITLE
Cound one disable some SQL in Sharding proxy for safety?

### ISSUE THREAD

**Issue by Anilople** [apache/incubator-shardingsphere#3542]
## Feature Request

Sometimes in production, we just need **SELECT**, other SQL will not needed. It is more safe to just use **SELECT**, disable other like **INSERT, UPDATE, DELETE** in production environment.

### Is your feature request related to a problem?

Yes. Make production more safety.

### Describe the feature you would like.

In config **server.yaml**，one can add white list to enable a user account just use these SQL.

**Comment by terrymanu** [comment]
It is a really big feature for SQL audit, we have no plan to do it now.
If somebody interest that, we can talk about the scope first.

**Comment by terrymanu** [comment]
May I close this issue because we have no plan to do SQL audit now?

**Comment by Anilople** [comment]
Sure. Thanks.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Liang Zhang <notifications@github.com>
发送时间: Tuesday, November 19, 2019 11:32:28 PM
收件人: apache/incubator-shardingsphere <incubator-shardingsphere@noreply.github.com>
抄送: Anilople <Anilople@outlook.com>; Author <author@noreply.github.com>
主题: Re: [apache/incubator-shardingsphere] Cound one disable some SQL in Sharding proxy for safety? (#3542)


May I close this issue because we have no plan to do SQL audit now?

―
