### ISSUE TITLE
NO PRIMARY KEY：when double click any table in shardng-proxy,warning:no primary key, update table_name SET ModifiedFiedDiedsAndValues WHERE AllFieldsAndOldValues LIMIT 1

### ISSUE THREAD

**Issue by hao110937733** [apache/incubator-shardingsphere#3544]
when I create table by sharding-proxy,open any table in sharidng-proxy,The system prompts that there is no primary key
this is my mysql:
CREATE TABLE PT_DM_PKG
(
   PKG_ID               VARCHAR(32) NOT NULL COMMENT '包ID',
   PKG_NAME             VARCHAR(64) NOT NULL COMMENT '包名称',
   PAR_PKG_ID           VARCHAR(32) COMMENT '父包ID',
   APP_ID               VARCHAR(32) NOT NULL COMMENT '应用ID',
   PKG_DESC             VARCHAR(256) COMMENT '描述',
   PKG_EXTOPT           VARCHAR(1024) COMMENT '扩展定义',
   PKG_DISPIDX          INT NOT NULL COMMENT '显示顺序',
   PKG_CTIME            TIMESTAMP NOT NULL COMMENT '创建时间',
   PKG_MTIME            TIMESTAMP NOT NULL COMMENT '最后修改时间',
   PRIMARY KEY (PKG_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

**Comment by dongzl** [comment]
Hi @hao110937733 ,  do you have the same problem with this issue #3005 ?

what's your Sharding-Proxy version? 

Can you provide you Configuration file?

**Comment by terrymanu** [comment]
@hao110937733  Can you describe the summary in title for search friendly?

**Comment by hao110937733** [comment]
@dongzl 
Sharding-Proxy version:4.0.0-RC2
Configuration file:
[sharding-ms_model.txt](https://github.com/apache/incubator-shardingsphere/files/3856996/sharding-ms_model.txt)

**Comment by dongzl** [comment]
> @dongzl
> Sharding-Proxy version:4.0.0-RC2
> Configuration file:
> [sharding-ms_model.txt](https://github.com/apache/incubator-shardingsphere/files/3856996/sharding-ms_model.txt)

Hi @hao110937733 , I have fixed it in 4.0.0-RC3, it will be released very soon, you can try it.
issue: #3005 
PR: #3379 

I think they are same problem.
