### ISSUE TITLE
XA failure of PostgreSQL

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#3545]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC3-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
XA transaction succeed for PostgreSQL
### Actual behavior
![pg_xa](https://user-images.githubusercontent.com/24643893/69022500-6e93b480-09f6-11ea-93ec-b86555e32644.png)

**Comment by cherrylzhao** [comment]
I have found the root cause. postgreSQL needs to config `max_prepared_transactions` in `postgresql.conf`.  since default value is zero, XA feature have been disabled.

**Comment by cherrylzhao** [comment]
when I test Sharding-JDBC using Postgresql XA, another problem have occurred. I will submit a PR to fix it as soon as possible

**Comment by cherrylzhao** [comment]
see #3825
