### ISSUE TITLE
Timestamp miss milliseconds

### ISSUE THREAD

**Issue by lightning-pro** [apache/incubator-shardingsphere#3550]
### Which version of ShardingSphere did you use?
shardingsphere-4.0.0-RC2-1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
insert a timestamp value into table with milliseconds

### Actual behavior
insert a timestamp value into table without milliseconds

### Reason analyze (If you can)
I think maybe related to the Timestamp long construtor in sharding-proxy ? or btm jdbc (but when insert to my db without proxy, it works perfect,so this should not be the cause)???
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I am using bitronix tm in my application, just a normal simple insert sql with timestamp value with milliseconds in PreparedStatement. and my client os is windows 10 with Zulu openjdk 1.8.0_232. And the sharding-proxy is in Ubuntu 18.04 with Oracle jdk 1.8.0_211 and MySQL5.7

### Example codes for reproduce this issue (such as a github link).
internal application,not available in github

**Comment by terrymanu** [comment]
Can you provide your INSERT and CREATE TABLE SQL?

**Comment by lightning-pro** [comment]
Well, the root cause is that in the Mysql jdbc PreparedStatement setTimestampInternal method,
there is a checking
 this.serverSupportsFracSecs 

which is to detect  the current connection agains the mysql's version 

but when connect to the sharding-proxy, the response of the checking detectFractionalSecondsSupport is false . and BTW, my MySQL server is 5.7.25 version and the jdbc driver is 5.1.43

------below is the code in the MySQL driver PreparedStatement for your reference-----
`
protected void detectFractionalSecondsSupport() throws SQLException {
        this.serverSupportsFracSecs = this.connection != null && this.connection.versionMeetsMinimum(5, 6, 4);
    }

private void setTimestampInternal(int parameterIndex, Timestamp x, Calendar targetCalendar, TimeZone tz, boolean rollForward) throws SQLException {
        if (x == null) {
            setNull(parameterIndex, java.sql.Types.TIMESTAMP);
        } else {
            checkClosed();

            if (!this.sendFractionalSeconds) {
                x = TimeUtil.truncateFractionalSeconds(x);
            }

            if (!this.useLegacyDatetimeCode) {
                newSetTimestampInternal(parameterIndex, x, targetCalendar);
            } else {
                Calendar sessionCalendar = this.connection.getUseJDBCCompliantTimezoneShift() ? this.connection.getUtcCalendar()
                        : getCalendarInstanceForSessionOrNew();

                x = TimeUtil.changeTimezone(this.connection, sessionCalendar, targetCalendar, x, tz, this.connection.getServerTimezoneTZ(), rollForward);

                if (this.connection.getUseSSPSCompatibleTimezoneShift()) {
                    doSSPSCompatibleTimezoneShift(parameterIndex, x);
                } else {
                    synchronized (this) {
                        if (this.tsdf == null) {
                            this.tsdf = new SimpleDateFormat("''yyyy-MM-dd HH:mm:ss", Locale.US);
                        }

                        StringBuffer buf = new StringBuffer();
                        buf.append(this.tsdf.format(x));

                        if (this.serverSupportsFracSecs) {
                            int nanos = x.getNanos();

                            if (nanos != 0) {
                                buf.append('.');
                                buf.append(TimeUtil.formatNanos(nanos, this.serverSupportsFracSecs, true));
                            }
                        }

                        buf.append('\'');

                        setInternal(parameterIndex, buf.toString()); // SimpleDateFormat is not
                                                                    // thread-safe
                    }
                }
            }

            this.parameterTypes[parameterIndex - 1 + getParameterIndexOffset()] = Types.TIMESTAMP;
        }
    }
`

**Comment by terrymanu** [comment]
What I mean is can you provide your INSERT and CREATE TABLE SQL, and we may talk about details.
ShardingSphere do not care concrete database driver.

**Comment by lightning-pro** [comment]
Well, my test table as follows

```
CREATE TABLE `TEST_SHARDING_ORDER` (
  `ORDER_ID` varchar(40) NOT NULL,
  `CUSTOMER` varchar(63) DEFAULT NULL,
  `SUPPLIER` varchar(63) DEFAULT NULL,
  `NOTE` varchar(63) DEFAULT NULL,
  `ORDER_DATE` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
```

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Timestamp;

public class Sharding {
    public static void main(String[] args) throws IOException {
        String idKeyValue = "100006";
        int sharding = Math.abs(String.valueOf(idKeyValue).hashCode() % 17);

        System.out.println("sharding is " + sharding);

        String jdbcUrl = "jdbc:mysql://192.168.101.24:3307/sharding_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false";
        String username = "root";
        String password = "root";
        try{
            Connection connection = DriverManager.getConnection(jdbcUrl,username,password);
            String sqlString = "INSERT INTO TEST_SHARDING_ORDER (ORDER_ID, CUSTOMER, SUPPLIER, NOTE, ORDER_DATE, LAST_UPDATED_STAMP) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sqlString);
            preparedStatement.setString(1,idKeyValue);
            preparedStatement.setString(2,"customer");
            preparedStatement.setString(3,"supplier");
            preparedStatement.setString(4,"timestamp miss the million seconds");
            Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
            System.out.println("currentTimestamp=="+currentTimestamp);
            preparedStatement.setTimestamp(5,currentTimestamp);//这里会因为MySQL jdbc driver this.connection.versionMeetsMinimum(5, 6, 4)数据库版本校验问题导致毫秒丢失
            preparedStatement.setTimestamp(6,currentTimestamp);//这里会因为MySQL jdbc driver this.connection.versionMeetsMinimum(5, 6, 4)数据库版本校验问题导致毫秒丢失
            preparedStatement.executeUpdate();

            preparedStatement.close();
            connection.close();
        }catch (Exception e){
            e.printStackTrace();
        }
    }
}
```
when run this test,out put would be 
sharding is 3
currentTimestamp==2019-11-23 14:29:01.588

and the timestamp in database is 2019-11-23 14:29:01.0

the insert sql statement itself works fine, but the insert value of the timestamp will miss the milliseconds because of the db version checking in the mysql jdbc driver.

I do think ShardingProxy should let the jdbc driver know the real database's version.
e.g.
this.connection.versionMeetsMinimum(5, 6, 4) in the mysql jdbc driver should be true because my MySQL version is 5.7.25

**Comment by lightning-pro** [comment]
Hello ,any updates on this? if any other information is needed ,please let me know.

**Comment by tuohai666** [comment]
Hi @lightning-pro, 

I just go through all the messages on this issue. You already have a lot of findings.
I need the clear and brief answers to the following questions:

1. Have you tested by connecting to MySQL directly? How about the result?
2. Have you tested by connecting to Sharding-Proxy with raw Connector/J? How about the result?
3. Is there a bug in Sharding-Proxy? Is the bug related with certain connection pool like bitronix ?
4. I think you have already found out the root cause, but I can't get the point. Can you figure it out?

**Comment by lightning-pro** [comment]
1.I have tested by connnecting to MySQL directly, it work perfect
2.Yes, my last response is the pure java main test demo,it purely use the DriverManager to get an connection from Connector/J.you can just copy it and run it from any ide you want
3,yes,there is a bug in sharding-proxy, the bug is not related with any connection pool,it is related to the version checking of mysql server version. 
4.Ｉ think i haved descript the root case is very clear.but let me describe it again in Chinese:|

原因就是mysql-connector-j里的com.mysql.jdbc.PreparedStatement的变量serverSupportsFracSecs在方法
`protected void detectFractionalSecondsSupport() throws SQLException {
        this.serverSupportsFracSecs = this.connection != null && this.connection.versionMeetsMinimum(5, 6, 4);
    }`
里设置的值为false。直接连数据库设置的值为true。之所以链接sharding-proxy的值为false，是因为this.connection.versionMeetsMinimum(5, 6, 4);这个条件比较满足不了。应该是sharding-proxy没返回版本号？
如果要进一步追踪，就是在MysqlIO.java里的doHandshake(String user, String password, String database)方法，第1043行 this.serverVersion = buf.readString("ASCII", getExceptionInterceptor());
读取到的值为 '5.6.0-Sharding-Proxy 4.0.0-RC2'。我想是sharding-proxy里hard code了版本号？？？。这里导致读取到的版本号为5.6.0，然而我真实的mysql数据库版本号应该是5.7.25.
sharding-proxy返回5.6.0的版本号满足不了mysql jdbc driver的5.6.4版本号的最低要求检查，导致时间戳毫秒数丢失。我想这里描述应该非常的清楚了吧？能否安排解决一下？

**Comment by tuohai666** [comment]
@lightning-pro I got it. Thanks for your patience.

I prefer to update the version from 5.6.0-Sharding-Proxy to 5.6.4-Sharding-Proxy.

**Comment by lightning-pro** [comment]
Hi,@tuohai666

> @lightning-pro I got it. Thanks for your patience.
> 
> I prefer to update the version from 5.6.0-Sharding-Proxy to 5.6.4-Sharding-Proxy.

I am wondering why you like to hardcode the version number... cause when I debug in the mysql driver, I found that there are a lot of different version checkings for different mysql functions.I am not sure if the 5.6.4 is the highest version number in all the driver source code, for timestamp format itself,it is 5.6.4,but for others, some lower, some maybe higher, I think the most safty way is to check the version agains the mysql server in the proxy startup and combine with your proxy version then set to your constant parameter?
maybe you have your own concern, this is just my opinion...

**Comment by tuohai666** [comment]
I understand your concern.

Actually, I checked all the versions as a condition in Connector/J, only 5.6.4 will cause critical troubles. That's why I chose this version.

To explain why hardcode the version number, here are the reasons:

1. Databases mananged by one Sharding-Proxy instance may have different versions, there's no restricted conditions of the version consistency. In the inconsistent condition, which version should we choose?

2. Sharding-Proxy does not have different behaviors under different versions. Although we support alterable versions this time, we can't support alterable behaviors. For example, Sharding-Proxy didn't support MySQL protocol before 4.1.

3. It is not worthy to announce 'Sharding-Proxy can't work if the database versions aren't consistent' just for this issue.

Anyway, I welcome you to submit a pull request, maybe your solution is better, we can discuss more there.

**Comment by lightning-pro** [comment]
ok, incase you have checked all the versions in Connector/J, it would be enough for this momenet.
Well, for the moment, I don't have a deep knowlege of this sharding product. I am only a new user to this and considering to use this proxy in production if all the test passed ^_^

**Comment by lightning-pro** [comment]
Hi,
After recompile the source code and test, the insert of the sql with timestamp works ok, I have check the value in the real table, it contains the milliseconds. but when read from the proxy, it miss the milliseconds again.
When I debug the mysql jdbc driver, I found that the value of the length of timestamp field in internalRowData of com.mysql.jdbc.ByteArrayRow are different when connnecting to proxy and database directly.
the length of the value of the timestamp field is 19 when connecting to sharding-proxy
the length of the value of the timestamp field is 23 when connecting to the database directly
I do think there is still a bug in the sharding-proxy for the timestamp value
