### ISSUE TITLE
(Proxy) Response num of update is Zero for postgres JDBC client

### ISSUE THREAD

**Issue by RaigorJiang** [apache/incubator-shardingsphere#3556]
Which version of ShardingSphere did you use?
sharding-proxy : 4.0.0-RC3-SNAPSHOT

Expected behavior
When update one record, update success and return response number '1'

Actual behavior
When update one record, update success and return response number '0'

My configure is the same as #3555, and update process is :
String sql_update ="UPDATE t_encrypt SET content = xxx where pwd = xxx";
int num = statement.executeUpdate(sql_update);

**Comment by RaigorJiang** [comment]
I am trying to fix this issue.

**Comment by SteNicholas** [comment]
@RaigorJiang Do you fix this issue?If not, I will fix this~

**Comment by RaigorJiang** [comment]
Hi @SteNicholas 
I have read the document and code,  but haven't found a solution yet. 
If you know how to fix it,  please do it, thank you!

**Comment by SteNicholas** [comment]
@RaigorJiang You can refer to EncryptStatementTest unit test~

**Comment by RaigorJiang** [comment]
@SteNicholas OK, thanks  👍

**Comment by RaigorJiang** [comment]
Hi, @SteNicholas 
I think the problem is how to get the client to get data according to the postgres protocol, so refer to the Statement is not very helpful.

**Comment by SteNicholas** [comment]
@RaigorJiang I mean that you can use EncryptStatementTest to validate client operation that gets data according to the postgres protocol.

**Comment by RaigorJiang** [comment]
Oh, let my try  :)

**Comment by RaigorJiang** [comment]
@SteNicholas  Sorry, I still have no idea, could you fix it?  And I'll learn from you, thanks for your help.

**Comment by tuohai666** [comment]
I'll fixed is soon.
