### ISSUE TITLE
mvnw build error

### ISSUE THREAD

**Issue by xiaobai022sdo** [apache/incubator-shardingsphere#3557]
Below in  /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/ not have api and spi talog。Problematic projects :  sharding-core-* exclude sharding-core-api 

The following is the wrong report：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sharding-core-common: Compilation failure: Compilation failure: 
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/yaml/swapper/impl/KeyGeneratorConfigurationYamlSwapper.java:[20,53] package org.apache.shardingsphere.api.config.sharding does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/yaml/swapper/impl/KeyGeneratorConfigurationYamlSwapper.java:[29,111] cannot find symbol
[ERROR]   symbol: class KeyGeneratorConfiguration
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/yaml/swapper/impl/KeyGeneratorConfigurationYamlSwapper.java:[32,53] cannot find symbol
[ERROR]   symbol:   class KeyGeneratorConfiguration
[ERROR]   location: class org.apache.shardingsphere.core.yaml.swapper.impl.KeyGeneratorConfigurationYamlSwapper
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/yaml/swapper/impl/KeyGeneratorConfigurationYamlSwapper.java:[41,12] cannot find symbol
[ERROR]   symbol:   class KeyGeneratorConfiguration
[ERROR]   location: class org.apache.shardingsphere.core.yaml.swapper.impl.KeyGeneratorConfigurationYamlSwapper
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/route/ShardingAlgorithmFactory.java:[23,46] package org.apache.shardingsphere.api.sharding does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/route/ShardingAlgorithmFactory.java:[44,30] cannot find symbol
[ERROR]   symbol:   class ShardingAlgorithm
[ERROR]   location: class org.apache.shardingsphere.core.strategy.route.ShardingAlgorithmFactory
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/keygen/SnowflakeShardingKeyGenerator.java:[24,44] package org.apache.shardingsphere.spi.keygen does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/strategy/keygen/SnowflakeShardingKeyGenerator.java:[54,61] cannot find symbol
[ERROR]   symbol: class ShardingKeyGenerator
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/spi/database/SQLServerDatabaseType.java:[21,46] package org.apache.shardingsphere.spi.database does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/spi/database/SQLServerDatabaseType.java:[22,46] package org.apache.shardingsphere.spi.database does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/spi/database/SQLServerDatabaseType.java:[32,53] cannot find symbol
[ERROR]   symbol: class DatabaseType
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/spi/database/SQLServerDatabaseType.java:[45,12] cannot find symbol
[ERROR]   symbol:   class DataSourceMetaData
[ERROR]   location: class org.apache.shardingsphere.core.spi.database.SQLServerDatabaseType
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/datasource/DataSourceMetas.java:[20,46] package org.apache.shardingsphere.spi.database does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/datasource/DataSourceMetas.java:[21,46] package org.apache.shardingsphere.spi.database does not exist
[ERROR] /data/sharding/incubator-shardingsphere-4.0.0-RC3/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/datasource/DataSourceMetas.java:[22,46] package org.apache.shardingsphere.spi.database does not exist

**Comment by terrymanu** [comment]
4.0.0-RC3 is not released for now
