### ISSUE TITLE
Transaction use master database,Any example?

### ISSUE THREAD

**Issue by bamboog** [apache/incubator-shardingsphere#3559]
## Question

Transaction use master database,Any example?
I've checked the document and found nothing I want；

**Comment by terrymanu** [comment]
read-write split do not support transaction

**Comment by zhp1254** [comment]
@Aspect
@Component
public class ShardingMasterInterceptor {
    private static final String POINT = "@annotation(org.springframework.transaction.annotation.Transactional)";

    @Before(POINT)
    public void before(){
 if(!HintManager.isMasterRouteOnly()) {
            HintManager.clear();
            HintManager.getInstance().setMasterRouteOnly();
        }
    }

    @AfterReturning(POINT)
    public void after(){
        HintManager.clear();
    }
}
@bamboog
