### ISSUE TITLE
all version don't support  this sql ( select .....A left jion B on a.id_ = b.id_ and b.splitkey=1 where ....)?

### ISSUE THREAD

**Issue by wanghaipeng1205** [apache/incubator-shardingsphere#3560]

**Comment by wanghaipeng1205** [comment]
now i am  using  this latest version ,but i don't know is that the latest version support ?

**Comment by terrymanu** [comment]
What is the error message?

**Comment by wanghaipeng1205** [comment]
no error  but route to all shards   my version is 
<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.0.0.M4</version>
        </dependency>
 sql:  select 。。。 A a left join  B b on b.id=a.id left join C  on a.id=c.id  and c.splitkey=1
where ....

**Comment by terrymanu** [comment]
Can you provide sharding rule configuration and log of `sql.show`?

**Comment by terrymanu** [comment]
Hi, will close soon if no response anymore
