### ISSUE TITLE
Create a foreign key using ddl，Execute twice version: 4.0.0-RC2

### ISSUE THREAD

**Issue by larry0592** [apache/incubator-shardingsphere#3562]
2019-11-20 17:13:50.349  INFO 17944 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds ::: alter table **_ACT_ID_MEMBERSHIP_** 
add constraint ACT_FK_MEMB_GROUP 
foreign key (GROUP_ID_) 
references act_id_group (ID_)
2019-11-20 17:13:50.349  INFO 17944 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds ::: alter table **_act_id_membership_** 
add constraint ACT_FK_MEMB_GROUP 
foreign key (GROUP_ID_) 
references ACT_ID_GROUP (ID_)
2019-11-20 17:13:51.461 ERROR 17944 --- [           main] .d.AbstractSqlScriptBasedDbSchemaManager : problem during schema create, statement alter table ACT_ID_MEMBERSHIP 
add constraint ACT_FK_MEMB_GROUP 
foreign key (GROUP_ID_) 
references ACT_ID_GROUP (ID_)

java.sql.SQLIntegrityConstraintViolationException: Can't write; duplicate key in table '#sql-78c_19a'

**Comment by terrymanu** [comment]
What is your sharding rule Configuration?

**Comment by larry0592** [comment]
This is application.properties 


#MySql配置
spring.shardingsphere.datasource.names=ds
spring.shardingsphere.datasource.ds.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds.url=jdbc:mysql://localhost:3306/larry-dev?characterEncoding=utf8&serverTimezone=GMT&nullCatalogMeansCurrent=true
spring.shardingsphere.datasource.ds.username=root
spring.shardingsphere.datasource.ds.password=sa123
spring.shardingsphere.datasource.ds.initial-size=8
spring.shardingsphere.datasource.ds.max-active=16

#JPA
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.show_sql=false

# 是否显示SQL语句
spring.shardingsphere.props.sql.show=true

#分表策略
spring.shardingsphere.sharding.tables.person.actual-data-nodes=ds.person_$->{0..99}
spring.shardingsphere.sharding.tables.person.table-strategy.inline.sharding-column=company_id
spring.shardingsphere.sharding.tables.person.table-strategy.inline.algorithm-expression=person_$->{Math.abs(company_id.hashCode())% 100 }
spring.shardingsphere.sharding.tables.person.key-generator.column=company_id
spring.shardingsphere.sharding.tables.person.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.person.key-generator.props.worker.id=123

**Comment by terrymanu** [comment]
Where is table `act_id_membership`, did you forget to config it?

**Comment by larry0592** [comment]
We perform table splitting on some large tables（such as: person）, and other tables do not need to.

**Comment by terrymanu** [comment]
If do not config `act_id_membership` and default data source, how shardingsphere to know which data source to be execute for this table?

**Comment by terrymanu** [comment]
Will close soon if no response anymore
