### ISSUE TITLE
Sharding-Proxy fuzzy query failed,Can't find any data

### ISSUE THREAD

**Issue by hao110937733** [apache/incubator-shardingsphere#3564]
sharding-proxy:4.0.0-RC2
when i use fuzzy query like"SHOW TABLES FROM `DS0` LIKE 'p%'",I can't get any data,but,this sql can work on my local library.
my config file and result of search:
[sharding-ms_model.txt](https://github.com/apache/incubator-shardingsphere/files/3872469/sharding-ms_model.txt)
![本地查询](https://user-images.githubusercontent.com/40648607/69298267-4b604380-0c48-11ea-9a0f-0cd5c49b6a36.png)
![代理查询](https://user-images.githubusercontent.com/40648607/69298279-52875180-0c48-11ea-9528-e58121b15d89.png)

**Comment by kimmking** [comment]
最新版本可以执行了。

**Comment by kimmking** [comment]
@terrymanu  
This sql is supported now, we can close this issue.

**Comment by terrymanu** [comment]
I don't know which pr resolved this issue. I just set label as invalid, please use stable version.
