### ISSUE TITLE
Why are exceptions missing

### ISSUE THREAD

**Issue by guchengyuxiang** [apache/incubator-shardingsphere#3565]
## Question
Why are exceptions missing

refreshTableMetaData(connection.getShardingContext(), routeResult.getSqlStatement());

@Override
    public boolean execute() throws SQLException {
        try {
            clearPrevious();
            sqlRoute();
            initPreparedStatementExecutor();
            return preparedStatementExecutor.execute();
        } finally {
        	// error missing
            refreshTableMetaData(connection.getShardingContext(), routeResult.getSqlStatement());
            clearBatch();
        }
version 3.1.0
jdk-version 11

Before asking a question, make sure you have:
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by guchengyuxiang** [comment]
jaxb-runtime

**Comment by terrymanu** [comment]
Can you try version 4.x? 3.x is out of service
