### ISSUE TITLE
Suggestions from incubator vote of Release Apache ShardingSphere (Incubating) 4.0.0-RC3

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#3566]
### Here are some suggetions for our next version release.

- [x] You might want to add a link the ASF code of conduct in your code of conduct.
- [x] You might want to update your version of the Mavin wrapper to be the latest.
- [x] Something been to have gone wrong with the footer in [1] where is says "Copyright © The Apache Software Foundation, Licensed under the Apache License, Version 4.0.0-RC3”. Do you mean Apache License version 2? 
**Please modify the footer to "Copyright © The Apache Software Foundation, Licensed under the Apache License 2"**

**Comment by tristaZero** [comment]
The first was fixed in [#366](https://github.com/apache/incubator-shardingsphere-doc/pull/366).

**Comment by JaredTan95** [comment]
Second: according to this https://mvnrepository.com/artifact/io.takari/maven-wrapper, the maven wrapper already to be the latest.

**Comment by tristaZero** [comment]
@JaredTan95 [What we used](https://github.com/apache/incubator-shardingsphere/blob/dev/mvnw#L215) is not the latest one, i.e 0.5.x, right?
