### ISSUE TITLE
设置默认数据源 应用启动失败 提示表或视图不存在

### ISSUE THREAD

**Issue by tucaoxingren** [apache/incubator-shardingsphere#3590]
<sharding:sharding-rule data-source-names="shardingsphere-sbj,shardingsphere-km,shardingsphere-spt" default-data-source-name="shardingsphere-spt" >

设置default-data-source-name后应用启动失败 提示表或视图不存在 删除default-data-source-name正常启动 正常使用

**Comment by dongzl** [comment]
Hi @tucaoxingren ,

**For English only**, other languages will not accept.

You can close this issue and submit a new issue in English again.

**Comment by tucaoxingren** [comment]
已解决 默认数据源中不能有分片的数据表
