### ISSUE TITLE
Can sharding strategy configuration files support Java？

### ISSUE THREAD

**Issue by lirengui** [apache/incubator-shardingsphere#3599]
What else does this fragmentation strategy support besides expressions? Does java code support it? If so, what should I pay attention to

**Comment by lirengui** [comment]
![a56247a02313a40ebdcf2da3860540f](https://user-images.githubusercontent.com/26484302/69597719-daeb6500-1041-11ea-9edb-7cb78d6f6be0.png)

**Comment by terrymanu** [comment]
Can you change title for search friendly?

**Comment by lirengui** [comment]
> 您可以更改标题以方便搜索吗？

ok

**Comment by terrymanu** [comment]
`fragmentation policy` should be `sharding strategy`, is it? Can you fix the title again?

**Comment by lirengui** [comment]
> `fragmentation policy` should be `sharding strategy`, is it? Can you fix the title again?

Oh, sorry, English is not very good. I tried to use hint to segment, but I implemented hintshardingalgorithm interface in API and rewritten doshading (), but I found that he didn't execute my implemented doshading (). What's the problem? Thank you

**Comment by betterjava** [comment]
Inline expressions use Groovy syntax.If you want futher information,please see 
https://shardingsphere.apache.org/document/current/en/features/sharding/other-features/inline-expression/  or
https://shardingsphere.apache.org/document/current/cn/features/sharding/other-features/inline-expression/

**Comment by terrymanu** [comment]
@lirengui, Hi, can we close this issue?

**Comment by lirengui** [comment]
> @lirengui, Hi, can we close this issue?

sure,thanks!
