### ISSUE TITLE
Add sharding-scaling-distribution module

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#3600]
Add sharding-scaling-distribution module.
@KomachiSion 
@avalon566 
@dongzl

**Comment by KomachiSion** [comment]
@ssxlulu Yes, We need move assembly from sharding-scaling-bootstrap to sharding-scaling-distribution

**Comment by KomachiSion** [comment]
@ssxlulu , The Pr has merged, should close this issue?
