### ISSUE TITLE
How to use hint sharding

### ISSUE THREAD

**Issue by lirengui** [apache/incubator-shardingsphere#3609]
If you use hint to segment, you must first use hintmanager to set shardingvalue prompt value on the business system, right

**Comment by betterjava** [comment]
Yes,  you are right. If you want further information,please see https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/hint/

**Comment by lirengui** [comment]
Mm-hmm. today we implemented and tested the hint sharding method. After evaluation, it seems that it is not good. If this sharding method is used in batch insertion, it will cause data sharding failure. Because it is an insert completed under the same connection, and the sharding value is only set once, so this batch of data can only be distributed in the database or table under the sharding value




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午4:52
收件人:&nbsp;"apache/incubator-shardingsphere"<incubator-shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"祈福科进软件李壬癸"<1023538544@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-shardingsphere] How to use hint sharding (#3609)




Yes,  you are right. If you want further information,please see https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/hint/

**Comment by betterjava** [comment]
Can you show how your code how to use hint? I don't understand you well.

**Comment by terrymanu** [comment]
Closed because no response for long time
