### ISSUE TITLE
Show scaling progress and detail

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#3617]
Show scaling progress and detail may include the following items:
1. Number of all tasks;
2. Number of remaining tasks;
3. Number of rows read;
4. Number of rows write;
5. Number of Abnormal rows;
6. Average read rate;
7. Average read rate;
8. statistics about the whole progress:
   (1) Number of schemas and tables;
   (2) Total time;
   (3) Total read rows and speed;
   (4) Total write rows and speed;
   (5) Total abnormal rows.

**Comment by ssxlulu** [comment]
@KomachiSion This is the issue about statistics of scaling progress.

**Comment by avalon566** [comment]
I think these statistics is for running metrics, scaling progress is use for determine when to switch.

**Comment by KomachiSion** [comment]
@ssxlulu , I think the scaling progress should include the progress information, such as rows number need to sync and how many rows has sync, or the delay of logs.

Most of items you lists is monitor data. I think we can add in future, not what we need now.

**Comment by ssxlulu** [comment]
> @ssxlulu , I think the scaling progress should include the progress information, such as rows number need to sync and how many rows has sync, or the delay of logs.
> 
> Most of items you lists is monitor data. I think we can add in future, not what we need now.

OK.

**Comment by KomachiSion** [comment]
I think Number of all tasks and Number of remaining tasks can be added to progress.
Rows need to synchronize and Rows have been synchronized should be included in history sync progress.
The log position and delay second should be included in real time sync progress.

**Comment by avalon566** [comment]
The progress data look like this
```
{
    "id": "0",
    "job_name": "",
    "data_node_progress": [{
        "id": "{host}-{port}-{schema}"
        "stage": "prepare/history_data/realtime_data/stopped",
        "history_data_progress": [{
            "id": "{schema}-{table}-split#0"
            "expected_rows": 0
            "sycned_rows": 0
        }],
        "realtime_data_progress": {
            "id": "{schema}-realtime"
            "log_positon": 0,
            "delay_second": 0
        }
    }]
}
```

**Comment by avalon566** [comment]
## About how to calculate realtime data sync delay second
1. Create a table with timestamp column in source database.
1. Sharding scaling timing update the timestamp column with current timestamp.
1. Read the timestamp value from log, use current timestamp subtract the value, result is the delay second.

This solution support MySQL and PostgreSQL.
