### ISSUE TITLE
java.lang.NumberFormatException: For input string: "YES"

### ISSUE THREAD

**Issue by chenshun131** [apache/incubator-shardingsphere#3623]
## Bug Report
Connecting to mysql using sharding-jdbc 4.0.0-rc3 always fails to start.

### Which version of ShardingSphere did you use?
ShardingSphere 4.0.0-RC1 4.0.0-RC2 4.0.0-RC3

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
Properly configured environment, the project can not start properly, the following error:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.lang.NumberFormatException: For input string: "YES"

### Actual behavior
At project startup

### Reason analyze (If you can)
In org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader#getColumnMetaDataList method and in
boolean isAutoIncrement = resultSet.getBoolean("IS_AUTOINCREMENT");
line,attempt to convert the string 'NO' or 'YES' to a Boolean

### Example codes for reproduce this issue (such as a github link).
Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.lang.NumberFormatException: For input string: "YES"

**Comment by dongzl** [comment]
Hi @chenshun131 , you can reference this issue #3582 .

**Comment by chenshun131** [comment]
ok

**Comment by beijing-penguin** [comment]
this problem is fixed at dev branch...now you can  reduce the mysql drive version

**Comment by KomachiSion** [comment]
duplicate with #3582
