### ISSUE TITLE
Best practice of using Sharding-Proxy for different business systems

### ISSUE THREAD

**Issue by skyoxZ** [apache/incubator-shardingsphere#3626]
For different business systems, is it better to deploy a unified Sharding-Proxy or individual Proxy for each business system? 

If it is designed to deploy a unified Sharding-Proxy, I'm suprised that some configs such as `query.with.cipher.column` are global.

**Comment by terrymanu** [comment]
We can talk about how to enhancement it

**Comment by skyoxZ** [comment]
I'm familiar with few config.

Maybe at least we can consider letting `query.with.cipher.column` be configured on every table (for both Sharding-JDBC and Sharding-Proxy) ?

**Comment by terrymanu** [comment]
Good idea, we can talk about how to change the java config and yaml to make it can use `query.with.cipher.column` for each table

**Comment by kimmking** [comment]
I will follow this issue.

**Comment by kimmking** [comment]
@skyoxZ Are you interested in this feature, let this parameter make effect to certain databases&tables?

**Comment by skyoxZ** [comment]
> @skyoxZ Are you interested in this feature, let this parameter make effect to certain databases&tables?

The migration process of data masking of some tables should not affect other tables that have been using data masking.
