### ISSUE TITLE
Problems in integrating MySQL 8.0.17

### ISSUE THREAD

**Issue by xr2117** [apache/incubator-shardingsphere#3630]
Problems in integrating MySQL 8.0.17

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.sql.SQLDataException: Cannot determine value type from string 'NO'

**Comment by dongzl** [comment]
Hi @xr2117 , you can reference this issue #3582 .
