### ISSUE TITLE
sharding-jdbc If the query does not have a sharding condition, then the full route is taken. Could this process be more flexible?

### ISSUE THREAD

**Issue by crazyrunner01** [apache/incubator-shardingsphere#3634]
i think If you choose sub-database and sub-table, then your business volume must be very large. If the business data of a single table in the transaction database exceeds 10 million, sub-tables will be used, and you also sub-database, the transaction data should exceed 100 million At this time, if it is a query without a partition key, such an access request should be rejected from the access middleware.

Once such a request is sent to the database, it may consume a lot of database resources and cause business damage.

**Comment by terrymanu** [comment]
If SQL without sharding key, what behaviour do you expect except route to all data nodes?

**Comment by crazyrunner01** [comment]
Hello, I wonder if I can add a property to control whether to take the full route, or throw an exception to abort such a request that no shard condition, or let the developer handle it.

**Comment by crazyrunner01** [comment]
This requirement is made because we do not want to make changes at the orm layer.

**Comment by terrymanu** [comment]
It is not a good idea to let user to handle by programing with SQL problem by themselves.
How many user can understand this feature?

**Comment by crazyrunner01** [comment]
hello ,I know that sharding-jdbc is not a orm,it is a enhanced version of a jdbc driver,I wonder if it is possible to abort the query at this level if SQL does not have a shard key，or let developer handle it that no shard key,more flexible,As my question above,route to all data nodes could consume a lot of database resources and cause business damage.

**Comment by terrymanu** [comment]
How to deal with in sharding-proxy？

**Comment by crazyrunner01** [comment]
oh ,with sharding-proxy as same as with sharding-jdbc,the process is the same ,I see some people have asked this question before

**Comment by terrymanu** [comment]
Did you mean if user use sharding-proxy and SQL without sharding value, then let user write java code to handle it?

**Comment by crazyrunner01** [comment]
nonono ,I did not consider the sharding-proxy ,I only considered the sharding-jdbc

**Comment by terrymanu** [comment]
ShardingSphere should like a database, not a java SDK. sharding-proxy and sharding-jdbc are 2 different access adaptor.
We don't consider about make them diff for the core feature.
Your feature request is for SQL audit.
We have no plan to do SQL audit for now.
