### ISSUE TITLE
Must the table name be lowercase when set by sharding conifg?

### ISSUE THREAD

**Issue by sunliangyu** [apache/incubator-shardingsphere#3635]
If my table name is set to uppercase.LogicTable is converted to lowercase when TableRule is generated. But ,When doing join query( ComplexRoutingEngine.route  ),The logical table passed in when StandardRoutingEngine was created is converted to lowercase.
result.add((new StandardRoutingEngine(this.shardingRule, ((TableRule)tableRule.get()).getLogicTable(), this.optimizedStatement)).route());
  -> StandardRoutingEngine.getShardingValuesFromShardingConditions() ->this.logicTableName.equals(each.getTableName()) always false .

**Comment by sunliangyu** [comment]
this.logicTableName  is lower case ，
each.getTableName  is upper case

**Comment by terrymanu** [comment]
What is your version, sql and config?

**Comment by HongJinFeng** [comment]
If add bug label, please assign me to solve this issue, it may the same reason with the issue #3309 @terrymanu

**Comment by terrymanu** [comment]
@HongJinFeng Thank you, assigned.

**Comment by HongJinFeng** [comment]
After my investigation, The constructor method of class TableRule convert logic table name to lower case, Can i ask the reason? What is the concern? It must has a reason that convert logic table to lower case. @terrymanu

**Comment by terrymanu** [comment]
The reason of convert logic table name to lower case is ShardingSphere should case insensitive of logic table name.

**Comment by HongJinFeng** [comment]
> The reason of convert logic table name to lower case is ShardingSphere should case insensitive of logic table name.

Got it.

**Comment by haetao** [comment]
@sunliangyu Hi ! Can you show your configurations? I cant reproduce.

**Comment by HongJinFeng** [comment]
Hi ! Can you show your configurations and version of sharding-sphere?

**Comment by terrymanu** [comment]
Closed because no response anymore
