### ISSUE TITLE
The result set obtained by the data desensitization query is not decrypted

### ISSUE THREAD

**Issue by dai-ych** [apache/incubator-shardingsphere#3637]
### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
"pwd": 123456,
"pwdCipher": "123456",
### Actual behavior
"pwd": 123456,
"pwdCipher": "uuSnOplnPkGpTRbSHgdNUQ==",
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
shardingsphere:
    props:
      sql.show: true
      query.with.cipher.comlum: true
    datasource:
      names: master, slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: 
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: 
    sharding:
      default-data-source-name: dbSourceDemo
      encrypt-rule:
        encryptors:
          aes_encryptror:
            type: aes
            props:
              aes.key.value: 123456
        tables:
          t_user:
            columns:
              pwd_cipher:
                cipherColumn: pwd_cipher
                encryptor: aes_encryptror
      master-slave-rules:
        dbSourceDemo:
          master-data-source-name: master
          slave-data-source-names: slave

2019-12-02 19:39:38.760  INFO 337200     --- [nio-8085-exec-1] ShardingSphere-SQL                       : Actual SQL: slave ::: select
    id, account, pwd, pwd_cipher, salt, create_time, update_time, validity
      from t_user
      where validity = 1

The returned pwd_cipher is "uuSnOplnPkGpTRbSHgdNUQ==", not "123456",
The encrypted field was not decrypted

**Comment by terrymanu** [comment]
Please try with 4.0.0-RC3

**Comment by dai-ych** [comment]
3Q
