### ISSUE TITLE
part of sharding key in multiple sharding strategy  can not null

### ISSUE THREAD

**Issue by zhuyaoming** [apache/incubator-shardingsphere#3644]
sharding column value cannot insert  null ,but '' is ok?

if my sharding column is id_number
insert into a(id,id_number)values(1,'');   √
insert into a(id,id_number)values(1,null);  ×

**Comment by terrymanu** [comment]
What is your expected behaviour if sharding value is null?

**Comment by zhuyaoming** [comment]
table have column  id, id_number,caseno,tenant_id,customer_id,sex,name ..... 
i use [id_number,tenant_id,customer_id ] sharding column   complex algorithm
some times i insert table  only have customer_id,tenant_id. i hope insert normally

**Comment by zhuyaoming** [comment]
now  i change my sql  ,   if sharding column is null ,donot insert. 

 i know  null is not a good design.  but  i want to known  why  sharing colomn cannot be null.

**Comment by zhuyaoming** [comment]
> What is your expected behaviour if sharding value is null?

table have column id, id_number,caseno,tenant_id,customer_id,sex,name .....
i use [id_number,tenant_id,customer_id ] sharding column complex algorithm
some times i insert table only have customer_id,tenant_id. i hope insert normally

**Comment by terrymanu** [comment]
> now i change my sql , if sharding column is null ,donot insert.

Is it a correct behaviour for regular database? For my understanding, only add a column constraint as `NOT NULL`, then database should not permit the tuple insert into the table.

**Comment by terrymanu** [comment]
> some times i insert table only have customer_id,tenant_id. i hope insert normally
So, I want to know what is the expected behaviour for insert normally?

**Comment by zhuyaoming** [comment]
> > some times i insert table only have customer_id,tenant_id. i hope insert normally
> 
> So, I want to know what is the expected behaviour for insert normally?

no error

**Comment by terrymanu** [comment]
> > > some times i insert table only have customer_id,tenant_id. i hope insert normally
> > 
> > 
> > So, I want to know what is the expected behaviour for insert normally?
> 
> no error

Which data node is the data inserted into?

**Comment by zhuyaoming** [comment]
> Which data node should the data inserted into?

i use ComplexShardingStrategy   , tenant_id and consumer_id can known data,  
and  tenant_id + consumer_id correspond only id_number.  i save Map when insert have id_number.

**Comment by terrymanu** [comment]
Maybe we do not need talk about business logic here, we just make sure if we permit `null` for sharding value, which data node should the data inserted into?

**Comment by zhuyaoming** [comment]
> Maybe we do not need talk about business logic here, we just make sure if we permit `null` for sharding value, which data node should the data inserted into?

other sharding column can known data node.

**Comment by lightning-pro** [comment]
Hi ,for un sharding fields, once a value of not the sharding fields with null , all the records after that will be set to null

**Comment by zhuyaoming** [comment]
> Hi ,for un sharding fields, once a value of not the sharding fields with null , all the records after that will be set to null

thank you for your reply, i will change my colum Field  cannot be null.

**Comment by terrymanu** [comment]
I get the point, it means part of sharding key in multiple sharding strategy can be null, is it?

**Comment by zhuyaoming** [comment]
> I get the point, it means part of sharding key in multiple sharding strategy can be null, is it?

yes

**Comment by terrymanu** [comment]
Ok, can you change the title? I can set label to volunteer wanted for this issue

**Comment by KomachiSion** [comment]
Hi @zhuyaoming, in my opinion, The sharding column in ShardingSphere is similar to the primary key, which should can locate the DataNode accurately.
Value `null` for sharding column may cause ambiguity, and it strongly depend on users implements, So ShardingSphere do not support `null` for sharding column in `Insert SQL`.

**Comment by terrymanu** [comment]
+1, I consider carefully, The constraint of `sharding value not be null` should be followed.
