### ISSUE TITLE
The data decrypt failure when I use mysql's blob field

### ISSUE THREAD

**Issue by minghu-zhang** [apache/incubator-shardingsphere#3647]
Sharding-encrypt doesn't work when I use Msql‘s blob field. There is a problem with the following code :

StreamQueryResult.java

    private String getCiphertext(final Object value) {
        return null == value ? null : value.toString();   //Blob.toString() ?
    }

Here is type convert code :

QueryResultUtil.java

   private static Object getValueByColumnType(final ResultSet resultSet, final int columnIndex) throws SQLException {
    ResultSetMetaData metaData = resultSet.getMetaData();
    switch (metaData.getColumnType(columnIndex)) {
    	...
        case Types.CLOB:
            return resultSet.getClob(columnIndex);
        case Types.BLOB:
        case Types.BINARY:
        case Types.VARBINARY:
        case Types.LONGVARBINARY:
            return resultSet.getBlob(columnIndex);
        default:
            return resultSet.getObject(columnIndex);
    }
}

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by minghu-zhang** [comment]
I have annother problem when use mybatis, mybatis need driver support jdbc's api  4.2, but sharding's EncryptResultSet doesn't support . the text field is handle by mybatis ClobTypeHandler, sharding‘s handler result is String， the following code :

EncryptResultSet.java:339

   @Override
    public Clob getClob(final String columnLabel) throws SQLException {
        return (Clob) resultSet.getValue(getActualColumnLabel(columnLabel), Clob.class);  
       //
    }

StreamQueryResult.java:74

    @Override
    public Object getValue(final String columnLabel, final Class<?> type) throws SQLException {
        // This type value is not used 
        return decrypt(columnLabel, QueryResultUtil.getValue(resultSet, queryResultMetaData.getColumnIndex(columnLabel)));
    }

**Comment by terrymanu** [comment]
We have no plan to add encrypt feature to type blob, do you want add this feature? @minghu-zhang

**Comment by minghu-zhang** [comment]
> We have no plan to add encrypt feature to type blob, do you want add this feature? @minghu-zhang

Ok,I'll try to add it

**Comment by minghu-zhang** [comment]
> We have no plan to add encrypt feature to type blob, do you want add this feature? @minghu-zhang

Thank you very much. These problems have been fixed when I download the latest code.
