### ISSUE TITLE
Identify database shard name by entity id

### ISSUE THREAD

**Issue by plazmdk** [apache/incubator-shardingsphere#3650]
I am using the Hint approach and only database sharding (no table sharding), where I basically ask another system of which shard I should put an entity into and select the shard accordingly. 

I now want to be able to determine myself which shard an entity has been stored in.
If I inject the entity manager and perform a .find(Entity.class, "EntityId") without a hint I will get the entity, but I am not able to determine which datasource it was fetched from - Is there a way of getting this information?

If not, is there a way of getting the configured datasources? I then could loop through each datasource by hinting.

Used version: 4.0.0-RC3

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by plazmdk** [comment]
> Can you change the title for search friendly?

I do not know if this was better?

**Comment by terrymanu** [comment]
Please reference example.
FIY: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/sharding-example/sharding-spring-namespace-jpa-example
