### ISSUE TITLE
select statement encouter error when using > comparation with strings

### ISSUE THREAD

**Issue by lightning-pro** [apache/incubator-shardingsphere#3651]
Which version of ShardingSphere did you use?
4.0.0-RC4 compile by myselft from the source code
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
select the records as expected
### Actual behavior
encounter error as belows
SQL 错误 [10002] [C1000]: 2Unknown exception: [Inline strategy cannot support range sharding.]
### Reason analyze (If you can)
have no idea
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT SMS_NUM_ID FROM CUSTOMER_SMS_NUM WHERE SMS_NUM_ID > '11'
### Example codes for reproduce this issue (such as a github link).
SELECT SMS_NUM_ID FROM CUSTOMER_SMS_NUM WHERE SMS_NUM_ID > '11'

SELECT SMS_NUM_ID FROM CUSTOMER_SMS_NUM WHERE SMS_NUM_ID > '11'
or
SELECT SMS_NUM_ID FROM CUSTOMER_SMS_NUM WHERE SMS_NUM_ID > 11
fail to execute,
but when connect to the db directly, both of these work fine

**Comment by lightning-pro** [comment]
BTW, when using the older version like RC2, the select as caption work perfect.

**Comment by terrymanu** [comment]
The exception tell you all necessary information:

[Inline strategy cannot support range sharding.]

**Comment by lightning-pro** [comment]
why you decide to remove this range select query in Inline strategy? it works when in 4.0.0-RC2. this break the convenience when using this product...
