### ISSUE TITLE
The work flow and roadmap of sharding-scaling

### ISSUE THREAD

**Issue by KomachiSion** [apache/incubator-shardingsphere#3655]
The work flow we design for sharding-scaling:
![workflow.png](https://raw.githubusercontent.com/apache/incubator-shardingsphere/sharding-scaling/sharding-scaling/src/resources/workflow.png)

The roadmap of sharding-scaling:
![roadmap.png](https://raw.githubusercontent.com/apache/incubator-shardingsphere/sharding-scaling/sharding-scaling/src/resources/roadmap.png)

The first milestone in roadmap is working, detail in #3598 .

**Comment by taojintianxia** [comment]
bravo ！ @KomachiSion :laughing:

I wonder how does shardingsphere writting data when migarating . 

Job...ennnn....so that's why there is a union meet up with dopoinescheduler at this Sunday.

**Comment by KomachiSion** [comment]
Thanks @taojintianxia , I hope we can have a happy and significant meet up with dolphinscheduler.

**Comment by betterjava** [comment]
@KomachiSion Should we consider cache preheating?

**Comment by KomachiSion** [comment]
I think there are no necessary for cache preheating. Because only when users change the shardingRule or datasource, the scaling out create and start. it's hard for us to predict users' new rule.

**Comment by KomachiSion** [comment]
I think there are no necessary for cache preheating. Because only when users change the shardingRule or datasource, the scaling out create and start. it's hard for us to predict users' new rule.

**Comment by betterjava** [comment]
Maybe you are right.
But consider this, after sync data done, user will switch query to new datasource,but new datasource have not been cache preheated,then there maybe many slow query  will happen (That's what I've been through).In the worst case, an avalanche may occur.

User can consider this by themself, or we can do something do help them?

**Comment by KomachiSion** [comment]
I am not sure other database, but if for mysql, the sync data ShardingScaling inserted will stay in buffer pool, newest data replace old data. So there is no need to preheated cache.

For other database, it may have some enhancement, but I think it's beyond the responsibility of ShardingScaling.

**Comment by betterjava** [comment]
Hot query data may not be newest  inserted  data.

But this feature maybe beyond the responsibility of ShardingScaling. We can discuss it after the main process is stable.

**Comment by KomachiSion** [comment]
> Hot query data may not be newest inserted data.

Yes, But we also do not know what's the `Hot query data`.  

> But this feature maybe beyond the responsibility of ShardingScaling. We can discuss it after the main process is stable.

I agree.

**Comment by KomachiSion** [comment]
Update in document https://shardingsphere.apache.org/document/current/en/features/sharding-scaling/
