### ISSUE TITLE
Can not create sharding table while table exist some with jpa

### ISSUE THREAD

**Issue by fenghuanfun** [apache/incubator-shardingsphere#3659]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-jdbc-core:4.0.0-RC2
spring-cloud.version:Greenwich.RELEASE
mysql:5.7
jpa:2.1.6
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
```
TableRuleConfiguration
before: ds.order_$->{19..19}0$->{1..9},ds.order_$->{19..19}1$->{0..2}
we have 12 tables already (1901,1902,,,1912)
these table was create by jpa 
```
i do not want to delete the table
```
after: ds.order_$->{19..20}0$->{1..9},ds.order_$->{19..20}1$->{0..2}
now we want 24 table (1901,1902,,,1912,2001,2002,,,2012)
```
### Actual behavior

it wont create new table while database exist any table whith name ds.order_19**

if i delete all 12 tables, i will get 24 tables while i start the application, but i do not want to delete the table existed because there are data in it

### Reason analyze (If you can)
exist any table has same name it wont create new ?
i guess

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

use TableRuleConfiguration ds.order_$->{19..19}0$->{1..9},ds.order_$->{19..19}1$->{0..2} 
to create 12 table

and then use TableRuleConfiguration ds.order_$->{19..20}0$->{1..9},ds.order_$->{19..20}1$->{0..2}
and it wont create new table

### Example codes for reproduce this issue (such as a github link).
if you still want example code after read this issue, i will write an example code later

**Comment by avalon566** [comment]
Do you want data migration?

**Comment by KomachiSion** [comment]
I think it can be solved by `create table if not exists`. Would you mind have a try?

**Comment by fenghuanfun** [comment]
> I think it can be solved by `create table if not exists`. Would you mind have a try?

I'm using spring-data-jpa, and it's  configuration is ddl-auto:update. that is ` create table if not exists `.
maybe the problem is jpa ?

**Comment by fenghuanfun** [comment]
> Do you want data migration?
> If You want to change sharding rule, it should use data migration.

I want to expand the table. our order's  sharding rule is one table one month.
and now it will 2020 soon

**Comment by avalon566** [comment]
You sharding rule is base on month, Historical data will not be affected. @KomachiSion advice will work for you.

**Comment by KomachiSion** [comment]
> > I think it can be solved by `create table if not exists`. Would you mind have a try?
> 
> I'm using spring-data-jpa, and it's configuration is ddl-auto:update. that is `create table if not exists`.
> maybe the problem is jpa ?

Can you open show.sql both of jpa and shardingsphere to restart your project, it can see the create table SQL generated by jpa and the actual routed SQL by shardingsphere.

**Comment by fenghuanfun** [comment]
OK!  Finally i find out the reason with debug

1. when JPA init, it find the table existing in database. and it comes into 
`org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.metadata.ResultSetReturnedDatabaseMetaData.getTables() `

```java
    @Override
    public final ResultSet getTables(final String catalog, final String schemaPattern, final String tableNamePattern, final String[] types) throws SQLException {
        String actualTableNamePattern = getActualTableNamePattern(tableNamePattern);
        try (Connection connection = getConnection()) {
            return new DatabaseMetaDataResultSet(connection.getMetaData().getTables(catalog, schemaPattern, actualTableNamePattern, types), shardingRule);
        }
    }
```
2. then coms into 
`org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.initIterator() ` --> ` generateDatabaseMetaDataObject()`
and we find the reason in line 104
```java
    private DatabaseMetaDataObject generateDatabaseMetaDataObject(final int tableNameColumnIndex, final int indexNameColumnIndex, final ResultSet resultSet) throws SQLException {
        DatabaseMetaDataObject result = new DatabaseMetaDataObject(resultSetMetaData.getColumnCount());
        for (int i = 1; i <= columnLabelIndexMap.size(); i++) {
            if (tableNameColumnIndex == i) {
                String tableName = resultSet.getString(i);
L:104           Collection<String> logicTableNames = null == shardingRule ? Collections.<String>emptyList() : shardingRule.getLogicTableNames(tableName);
                result.addObject(logicTableNames.isEmpty() ? tableName : logicTableNames.iterator().next());
            } else if (indexNameColumnIndex == i) {
                String tableName = resultSet.getString(tableNameColumnIndex);
                String indexName = resultSet.getString(i);
                result.addObject(indexName.endsWith(tableName) ? indexName.substring(0, indexName.indexOf(tableName) - 1) : indexName);
            } else {
                result.addObject(resultSet.getObject(i));
            }
        }
        return result;
    }
```
if `null == shardingRule ` is false, it will take the first logicTableName.

it's mean if  i change the shardingRule, it will not work for the new rule.

The question is whether to verify the existing tables suitable for rule here？

**Comment by KomachiSion** [comment]
> if null == shardingRule is false, it will take the first logicTableName.

> it's mean if i change the shardingRule, it will not work for the new rule.

if you change the logicTableName in shardingRule, or you change the actualNodes to other name, it may cause the `getTable` return the old actualTable name.

But in your configuration, your logicTable do not change, and the actualNode only add some node. so the `getTable` will return the same result-- your logicTableName

**Comment by fenghuanfun** [comment]
> > if null == shardingRule is false, it will take the first logicTableName.
> 
> > it's mean if i change the shardingRule, it will not work for the new rule.
> 
> if you change the logicTableName in shardingRule, or you change the actualNodes to other name, it may cause the `getTable` return the old actualTable name.
> 
> But in your configuration, your logicTable do not change, and the actualNode only add some node. so the `getTable` will return the same result-- your logicTableName

So it is non-scalable?

**Comment by KomachiSion** [comment]
The `getTable` want to map the actualTable to logicTable, so that JPA can get the tableInfo of logicTable. When you change your ShardingRule or actualNodes, it may cause the `getTable` return more information.

**Comment by KomachiSion** [comment]
I will close this issue due to **No response more than 7 days**
