### ISSUE TITLE
What is the best way to sharding just for a single key

### ISSUE THREAD

**Issue by lightning-pro** [apache/incubator-shardingsphere#3660]
I used to have a sharding rule like this
shardingRule:
  tables:
    CUSTOMER_SMS_NUM:
      actualDataNodes: SmsPubSign.CUSTOMER_SMS_NUM_${0..16}
      tableStrategy:
        inline:
          shardingColumn: SMS_NUM_ID
          algorithmExpression: CUSTOMER_SMS_NUM_${Math.abs(String.valueOf(SMS_NUM_ID).hashCode() % 17)}

which is the best way I think for sharding only for one key like SMS_NUM_ID.
when I select the record by the key, it work fine.but when I need to select like this 

`SELECT SMS_NUM_ID FROM CUSTOMER_SMS_NUM WHERE SMS_NUM_ID > 11 limit 0,20.`

when in the version of 4.0.0-RC2,this work good. 
but now from RC3 to RC4 ,this will encounter an error

SQL 错误 [10002] [C1000]: 2Unknown exception: [Inline strategy cannot support range sharding.]

Any suggestion on this? what should I do for this?

**Comment by terrymanu** [comment]
The exception is `[Inline strategy cannot support range sharding.]`

So please do not use Inline strategy with range sharding, you can use java strategy for your range sharding.
