### ISSUE TITLE
if null value is not supported?

### ISSUE THREAD

**Issue by lightning-pro** [apache/incubator-shardingsphere#3670]
## Question
For some reasons, the framework using in my company will use null for some none-mandatory fields.
When using the sharding-proxy-4.0.0-RC4, once a fileds contains null, all the values after it from the query will become null. Is this a bug or just a feature of sharidng-proxy that didn't support null value?
I think it is reasonable to support null values, because these fields are not sharding fields.

**Comment by terrymanu** [comment]
Can you show your sql here?

**Comment by lightning-pro** [comment]
my tables split to 17 tables from 0 to 16
when execute below sql, which the value of COMMENTS field is null
```
SELECT PRIM.SMS_NUM_ID, PRIM.PUBLIC_VIEW_ID,PRIM.COMMENTS
FROM CUSTOMER_SMS_NUM PRIM WHERE (PRIM.SMS_NUM_ID >= 1 AND PRIM.SMS_NUM_ID <= 18) order by PRIM.SMS_NUM_ID
```
the above sql work perfect

when execute like below, there will be a row with all null values and other rows ok
```
SELECT PRIM.SMS_NUM_ID, PRIM.PUBLIC_VIEW_ID,PRIM.COMMENTS
FROM CUSTOMER_SMS_NUM PRIM WHERE (PRIM.SMS_NUM_ID >= 1 AND PRIM.SMS_NUM_ID <= 19) order by PRIM.SMS_NUM_ID
```

while increase the bigger range with 20,21,22....the rows with null values will increase randomly.

but when I remove the PRIM.COMMENTS fields, everything is ok. return the expected records

the sharding field is SMS_NUM_ID with Integer value
 and my sharding algorithm as belows
RangeShardingAlgorithm

```
@Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Integer> shardingValue) {
        Collection<String> result = new HashSet<>();
        if(shardingValue.getValueRange().hasUpperBound()){
            for (int i = shardingValue.getValueRange().lowerEndpoint(); i <= shardingValue.getValueRange().upperEndpoint(); i++) {
                for (String each : availableTargetNames) {
                    if (each.endsWith(String.valueOf(i % availableTargetNames.size()))) {
                        result.add(each);
                    }
                }
            }
        }else {
            result = availableTargetNames;
        }

        return result;
    }
```
PreciseShardingAlgorithm
```
@Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<Integer> preciseShardingValue) {
        for (String each : collection) {
            if (each.endsWith(String.valueOf(preciseShardingValue.getValue() % collection.size()))) {
                return each;
            }
        }
        return null;
    }
```

**Comment by lightning-pro** [comment]
I have a tested with Sharding-Proxy-4.0.0-RC2 with my sharding algorithm jar, it works as expected, only the timestamp bug I raised few days ago. from RC2 to RC4, there were a big code changes or redesign in the sharding-proxy?

**Comment by lightning-pro** [comment]
how to get the source code of the version 4.0.0-RC2? I want to try to finx the timestamp bug base on it

**Comment by terrymanu** [comment]
FIY: https://github.com/apache/incubator-shardingsphere/tree/4.0.0-RC2

**Comment by terrymanu** [comment]
@lightning-pro  Can we close this issue?

**Comment by lightning-pro** [comment]
sure
