### ISSUE TITLE
sharding proxy how to support HA

### ISSUE THREAD

**Issue by qhj348770376** [apache/incubator-shardingsphere#3673]
as you know , HA is a very essential feature for a database middleware which will be used in production environment.I want to know the way that sharding proxy support HA.tks

**Comment by qhj348770376** [comment]
if sharding-proxy can not support HA well by itself right now,is there any compromising solution to avoid 
single-point riskment in production environment? How do you use sharding-proxy in JD?

**Comment by cherrylzhao** [comment]
I think you can use Nginx, HAProxy, LVS to handle load balance within TCP layer. use `keepalived` or `heartbeat` to support HA

**Comment by qhj348770376** [comment]
> I think you can use Nginx, HAProxy, LVS to handle load balance within TCP layer. use `keepalived` or `heartbeat` to support HA

do you mean I can set  Nginx or other middleware between application and sharding-proxy cluster to support HA ? @cherrylzhao

**Comment by cherrylzhao** [comment]
not yet, I have provided a way to build sharding-proxy cluster since sharding-proxy is stateless if you have not begin XA transaction

**Comment by qhj348770376** [comment]
> not yet, I have provided a way to build sharding-proxy cluster since sharding-proxy is stateless if you have not begin XA transaction

So I should build sharding-proxy cluster by myself to implement sharding-proxy's HA feature.
Is there any document to help me  build sharding-proxy cluster?

**Comment by cherrylzhao** [comment]
not yet now, you can goole it then contributing a PR for it :)

**Comment by duzhanfei** [comment]
hi ，is there any document to help me build sharding-proxy cluster?
 thanks.
.
