### ISSUE TITLE
Is there any good way to handle with parsing sql first time, which is taking too many time?

### ISSUE THREAD

**Issue by HongJinFeng** [apache/incubator-shardingsphere#3676]
Hi, we use encrypt-jdbc in our project, and last night we released it to production environment，when it started at the first time, our dubbo interface had many delay warings. After my investigation, it was because parse sql took too many time, most of them took more than one second, some beyond one second. And in this situation, our interface already time out, and it may cause dubbo interface be degraded(our project has more than 500 thousand requests per minute ). 

Although i had warm up some interface to cache sql statement, but the problem still exist. So, it there any good way to deal with it？I tell my leader if i can add the sql statement to redis,and every time the program start , i load it to local memory. But, he deny it, with the reason that the common module(which i package sharding-core, fix some bugs, and add some features) must with less dependencies. So i am very anxious, please help me, it there any good way to deal with this problem.
@terrymanu da lao，any suggestions?

**Comment by XuyangJava2E** [comment]
hi I am his boss, if he can not handle this problem until this week,he will be fired

**Comment by XuyangJava2E** [comment]
@terrymanu

**Comment by mengbieting** [comment]
Hi, I am his boss‘s boss, if they can not handle this problem until this week, they will be fired together.

**Comment by mengbieting** [comment]
Hi, I'm his boss's boss, if they can't handle this problem until this week, they will be fired together.

**Comment by terrymanu** [comment]
Because parse SQL by ANTLR is slow, and ShardingSphere save the 1st parse result into cache.
Please see details here: https://shardingsphere.apache.org/document/current/en/features/sharding/principle/parse/

I don't think we can enhance the performance before the AST into cache. If you want, you can consider about  preheat your SQL.

**Comment by HongJinFeng** [comment]
I have readed the document before and knew ANTLR is slow. Our project has hundreds SQL, and many SQL like 'select...in (...)' or 'insert...values(...)'，and the number of parameters is different, so it has thousands different situations. It is impractical to preheat so many SQL(preheat every SQL need serval seconds). so any other way to handle with it? 

I think if the SQL contain the table which need sharding or encrypt some column, it can parse SQL by ANTLR, but for other table,  maybe it is not need parse by ANTLR but with druid. But is there any elegant way complete it?

**Comment by terrymanu** [comment]
Only use preparedStatement can be cached, please use parameter marker to instead of parameter inline is your SQL

**Comment by terrymanu** [comment]
> I think if the SQL contain the table which need sharding or encrypt some column, it can parse SQL by ANTLR, but for other table, maybe it is not need parse by ANTLR but with druid, or others. Or is there any more elegant way complete it?

No one can afford take control two different SQL parser engine. If you interesting develop a new SQL parser engine, maybe we can talk about pull request.

**Comment by SteNicholas** [comment]
> I have readed the document before and knew ANTLR is slow. Our project has hundreds SQL, and many SQL like 'select...in (...)' or 'insert...values(...)'，and the number of parameters is different, so it has thousands different situations. It is impractical to preheat so many SQL (preheat every SQL need serval seconds). So any other way to handle with it?
> 
> I think if the SQL contain the table which need sharding or encrypt some column, it can parse SQL by ANTLR, but for other table, maybe it is not need parse by ANTLR but with druid, or others. Or is there any more elegant way complete it?

Why no need to parse by Antlr? Could you give the performance about the comparsion among the parse engine you mentioned above?

**Comment by HongJinFeng** [comment]
> > I think if the SQL contain the table which need sharding or encrypt some column, it can parse SQL by ANTLR, but for other table, maybe it is not need parse by ANTLR but with druid, or others. Or is there any more elegant way complete it?
> 
> No one can afford taking control two different SQL parser engines. If you interesting develop a new SQL parser engine, maybe we can talk about pull request.

It sounds that there is not better solution for this issue. I don't know is there any other effect if i change the soure core like this:  the logic sql is not contain the table which need sharding or encrypt some column, i create prepare statement by logic sql.
![image](https://user-images.githubusercontent.com/33616750/70400689-1dac3480-1a67-11ea-8ce0-f05e2cd9e1fc.png)

**Comment by xfyang1989** [comment]
> Because parse SQL by ANTLR is slow, and ShardingSphere save the 1st parse result into cache.
> Please see details here: https://shardingsphere.apache.org/document/current/en/features/sharding/principle/parse/
> 
> I don't think we can enhance the performance before the AST into cache. If you want, you can consider about preheat your SQL.

How to preheat SQL? Any examples?
