### ISSUE TITLE
multi-sharding key, when insert is excuted, one of the sharding keys is null and throws an exception

### ISSUE THREAD

**Issue by ErinDavid** [apache/incubator-shardingsphere#3677]
hi, i discover a question today
![image](https://user-images.githubusercontent.com/12891899/70315431-87082980-1854-11ea-9866-342589663a32.png)

![微信图片_20191206181539](https://user-images.githubusercontent.com/12891899/70315512-b6b73180-1854-11ea-842a-68e785ac14bc.png)

Suggestion: You need to add a judgment that result is not equal to null, and ignore result equal to null

**Comment by terrymanu** [comment]
duplicated with #3644
