### ISSUE TITLE
用namespace配置的方式，添加默认数据源后，启动很慢

### ISSUE THREAD

**Issue by CatDogZ** [apache/incubator-shardingsphere#3678]
**shardingjdbc 4.0版本的**
我用的spring命名空间的方式配置的。
有个order表，我进行分表分库了。但是其他剩余的表，我第一个版本不打算拆分，还是全部放在原来的数据源里面（大概有几百张表）。发现添加了default-data-source-name 这个配置后，项目启动很慢，大概要好几分钟。 我就去查看了源码，发现TableMetaDataInitializer这个类下面load方法，加载默认数据源信息的时候，要花费很长的时间。虽然定位到了问题，但是不知道如何解决，请问有人知道如何解决吗？
![image](https://user-images.githubusercontent.com/31087808/70318380-dfdac080-185a-11ea-8ef9-2cd4064bf54f.png)

**Comment by dongzl** [comment]
Hi @CatDogZ ,

**For English only**, other languages will not accept.
You can close this issue and submit a new issue in English again.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by cws1981** [comment]
是启动会加载数据库所有表的元数据，如果表比较多的化就很慢，我建议对分表的表单独放在一个 schme

**Comment by wonderfulxin** [comment]
有解决问题吗？  最后怎么处理的？

**Comment by wonderfulxin** [comment]
how to solve it？  hava you solve it？？

**Comment by wonderfulxin** [comment]
> 是启动会加载数据库所有表的元数据，如果表比较多的化就很慢，我建议对分表的表单独放在一个 schme

是怎么做的呢？  能否说明一下？感谢
