### ISSUE TITLE
Benchmark between Sharding-Proxy and MyCAT

### ISSUE THREAD

**Issue by kfchu** [apache/incubator-shardingsphere#3679]
Hi,

Is there any benchmark test or performance comparison between Sharding-Proxy and MyCAT, or some other database middleware.

Looking forward to your reply.

Thanks.

**Comment by dongzl** [comment]
https://shardingsphere.apache.org/benchmark

This is ShardingSphere' benchmark website, you can pay attention to it.

**Comment by terrymanu** [comment]
It is unconvincing if our community compare shardingSphere and other projects.
Please do it by yourself if you want
