### ISSUE TITLE
 tomcat start slowly with default datasource setting

### ISSUE THREAD

**Issue by CatDogZ** [apache/incubator-shardingsphere#3681]
use shardingjdbc 4.0 version.
i config shardingjdbc with spring-namespace.  and there are about two hundred tables that do not  participate in split database and table.  i use default-data-source configuration to set it. but i found that tomcat start is very slowly for about two minutes。i checked the shardingjdbc source code and found the class "TableMetaDataInitializer.java" "load" method cost a lot of time . here is the source code：
![image](https://user-images.githubusercontent.com/31087808/70370306-af4d6200-1900-11ea-8546-268090290812.png)。
the loadDefaultTables method will  load all the tables  info in default-data-source .but there are about two hundred tables,  that will caused the tomcat start slowly.   any idea?

**Comment by terrymanu** [comment]
What is your actual version? Actually, ShardingSphere do not have version 4.0

**Comment by CatDogZ** [comment]
> What is your actual version? Actually, ShardingSphere do not have version 4.0

Hi，the version is 4.0.0-RC2

**Comment by SteNicholas** [comment]
@CatDogZ You could modify `executor.size` configuration to speed loading default tables.

**Comment by CatDogZ** [comment]
@SteNicholas i modified the executor.size configuration in 4, 8 and 16 . but it still did not work.  Is there any other solution？ @terrymanu

**Comment by CatDogZ** [comment]
@terrymanu  emmmmm......is there any other solution? thanks a lot  。

**Comment by terrymanu** [comment]
ShardingSphere need to load table metadata. How many tables in your default data source?

**Comment by CatDogZ** [comment]
@terrymanu  about two hundred tables

**Comment by ma1562013338** [comment]
> ShardingSphere need to load table metadata. How many tables in your default data source?

My default data source has about a thousand tables because it contains split tables. It takes five or six minutes to start a project, which is very slow.

**Comment by ma1562013338** [comment]
> ShardingSphere need to load table metadata. How many tables in your default data source?
Will this problem be optimized in the future?

**Comment by ma1562013338** [comment]
@terrymanu Will this problem be optimized in the future?

**Comment by TracyBin** [comment]
We encountered the same problem and started very slowly. Solved after the database driver switched to the lower version

**Comment by terrymanu** [comment]
Can you provide the log of `sql.show`?

**Comment by terrymanu** [comment]
@CatDogZ > about two hundred tables

What is the time spend we you load two hundred tables without ShardingSphere?
We need to clarify the performance issue cause from huge tables count or just from ShardingSphere?

**Comment by CatDogZ** [comment]
@terrymanu if i don't config default source setting at application.properties(just only set sharding rules), tomcat start very fast. also, same as starting without  ShardingSphere. However,  when i set default database source,  the problem occured.

**Comment by beijing-penguin** [comment]
I think ShardingSphere should easy to expose loading interface,,,,so,The Users can customize the loading strategy

**Comment by wujiangyong** [comment]
I've been using `4.0.1` and I have the same problem, it took me 5-7 minutes to start up the app.

Then I google it, one way is to skip the method, which I haven't adopted. Copy the class `TableMetaDataInitializer` into your project, and remove `loadDefaultTables` method.

Then I looked into the code, I found when `findActualDefaultDataSourceName` returns `Optional.absent()`, it will not run into the actual loading. So I assume in some cases, `loadDefaultTables()` is not required, and I'v only used table sharding with sharding-jdbc, so there comes the second solution,  I configured two `<sharding:master-slave-rule>` in `<sharding:master-slave-rules>`, and actually the second one is a placeholder which I never used, and everything works fine for me, so far so good.

**Comment by TracyBin** [comment]
@wuqiaowu Could you paste your configuration?

**Comment by wuqiaowu** [comment]
> @wuqiaowu Could you paste your configuration?

In my cases, I only need table sharding (no database sharding).

```
<sharding:data-source id="shardingDataSource">
    <sharding:sharding-rule data-source-names="ds_master0, ds_master0_slave0" default-database-strategy-ref="noneShardingStrategy">
        <sharding:master-slave-rules>
            <sharding:master-slave-rule id="ds_ms0" master-data-source-name="ds_master0"
                                            slave-data-source-names="ds_master0_slave0" strategy-ref="randomStrategy"/>
            <!--   add another rule to skip "TableMetaDataInitializer.loadDefaultTables"’s executing  -->
            <sharding:master-slave-rule id="ds_ms1" master-data-source-name="ds_master0"
                                            slave-data-source-names="ds_master0_slave0" strategy-ref="randomStrategy"/>
        </sharding:master-slave-rules>
        <sharding:table-rules>
            <!--   use ds_ms0 explicitly -->
            <sharding:table-rule logic-table="table_a"
                                     actual-data-nodes="ds_ms0.table_a_$->{0..63}"
                                     table-strategy-ref="xxxxTableAStrategy"/>
            <sharding:table-rule logic-table="table_b"
                                     actual-data-nodes="ds_ms0.table_b_$->{['2020']}${['01','02','03','04','05','06','07','08','09','10','11','12']}"
                                     table-strategy-ref="xxxxTableBStrategy"/>
        </sharding:table-rules>
    </sharding:sharding-rule>
</sharding:data-source>
```
