### ISSUE TITLE
How to import sharding-proxy to idea if I want to do some debugging ?

### ISSUE THREAD

**Issue by winson08Li** [apache/incubator-shardingsphere#3687]
How to import sharding-proxy to idea if I want to do some debugging ? Or is there any documents about this topic ?

**Comment by terrymanu** [comment]
You can just run `org.apache.shardingsphere.shardingproxy.Bootstrap` to startup the proxy in your IDEA.

**Comment by winson08Li** [comment]
ok, I got that
