### ISSUE TITLE
默认数据源的表和字典表关联查询报错

### ISSUE THREAD

**Issue by chyangxi** [apache/incubator-shardingsphere#3693]
## Question

（default-data-source-name）table join （broadcast-table） error

## Content
<bean id="dbShardingRule" class="com.aop.ShardingDatabaseRule" />

	<sharding:standard-strategy id="databaseStrategy" sharding-column="buss_num" precise-algorithm-ref="dbShardingRule" />
	
	<sharding:data-source id="shadingDataSource">
		<sharding:props>
   			<prop key="sql.show">true</prop>
  		</sharding:props>
		<sharding:sharding-rule data-source-names="ds0,ds1" default-data-source-name="ds0">
			<sharding:table-rules>
				<sharding:table-rule logic-table="user" actual-data-nodes="ds$->{0..1}.user"
				 database-strategy-ref="databaseStrategy" />
				<sharding:table-rule logic-table="classes" actual-data-nodes="ds$->{0..1}.classes"
				 database-strategy-ref="databaseStrategy" />
				 <sharding:table-rule logic-table="mark" actual-data-nodes="ds$->{0..1}.mark"
				 database-strategy-ref="databaseStrategy" />
			</sharding:table-rules>
			
			<sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="user,classes,mark" />
            </sharding:binding-table-rules>
            
			<sharding:broadcast-table-rules > 
				<sharding:broadcast-table-rule table="school_config"/>
			</sharding:broadcast-table-rules>
		</sharding:sharding-rule>
	</sharding:data-source>

exception:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.apache.shardingsphere.core.exception.ShardingException: Cannot find table rule and default data source with logic tables: '[inter_user , school_config ]'

version：
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-core</artifactId>
			<version>4.0.0-RC2</version>
</dependency>
麻烦指导一下，请问是我配置的不对，还是怎么样？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
