### ISSUE TITLE
Cannot find table rule and default data source with logic tables

### ISSUE THREAD

**Issue by chyangxi** [apache/incubator-shardingsphere#3697]
> ## Question
> （default-data-source-name）table join （broadcast-table） error
> 
> ## Content
> ```
> <sharding:standard-strategy id="databaseStrategy" sharding-column="buss_num" precise-algorithm-ref="dbShardingRule" />
> 
> <sharding:data-source id="shadingDataSource">
> 	<sharding:props>
> 		<prop key="sql.show">true</prop>
> 	</sharding:props>
> 	<sharding:sharding-rule data-source-names="ds0,ds1" default-data-source-name="ds0">
> 		<sharding:table-rules>
> 			<sharding:table-rule logic-table="user" actual-data-nodes="ds$->{0..1}.user"
> 			 database-strategy-ref="databaseStrategy" />
> 			<sharding:table-rule logic-table="classes" actual-data-nodes="ds$->{0..1}.classes"
> 			 database-strategy-ref="databaseStrategy" />
> 			 <sharding:table-rule logic-table="mark" actual-data-nodes="ds$->{0..1}.mark"
> 			 database-strategy-ref="databaseStrategy" />
> 		</sharding:table-rules>
> 		<sharding:binding-table-rules>
>             <sharding:binding-table-rule logic-tables="user,classes,mark" />
>         </sharding:binding-table-rules>
> 		<sharding:broadcast-table-rules > 
> 			<sharding:broadcast-table-rule table="school_config"/>
> 		</sharding:broadcast-table-rules>
> 	</sharding:sharding-rule>
> </sharding:data-source>
> 
> exception:
> org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error updating database. Cause: org.apache.shardingsphere.core.exception.ShardingException: Cannot find table rule and default data source with logic tables: '[inter_user , school_config]'
> ### The error may involve com.inter_user .deleteImportData-Inline
> ### The error occurred while setting parameters
> ### SQL: delete from inter_user where date = ? and school IN (SELECT SLAVE_ID FROM school_config WHERE PARENT_ID = ?)
> ### Cause: org.apache.shardingsphere.core.exception.ShardingException: Cannot find table rule and default data source with logic tables: '[inter_user , school_config ]'
> version：
> 
> org.apache.shardingsphere
> sharding-jdbc-core
> 4.0.0-RC2
> 
> how to configure？can you tell me the question?thank you!

**Comment by chyangxi** [comment]
@terrymanu If you have time, please analyze it for me. I'm lost

**Comment by SteNicholas** [comment]
@chyangxi Table `inter_user` and `school_config` don't exist in `<sharding:table-rules>`, please configure this.

**Comment by chyangxi** [comment]
> @chyangxi Table `inter_user` and `school_config` don't exist in `<sharding:table-rules>`, please configure this.

'inter_user' use defalt data source,don't sharding .'school_config' use broadcast rule,same in every database .i don't need sharding table,only some table data sharding database,'inter_user 'use defalt. i really don't how to configure ...help me,please,thank you.

**Comment by terrymanu** [comment]
Can you just paste your sharding rule here?

**Comment by chyangxi** [comment]
@terrymanu 
@Component
public class ShardingDatabaseRule implements PreciseShardingAlgorithm<String> {

	
	private Logger log = LoggerFactory.getLogger(ShardingDatabaseRule.class);
	@Override
	public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<String> shardingValue) {
		log.debug("sharding begin shardingValue:{}",shardingValue);
		int bussNumHash = shardingValue.getValue().hashCode();
		int targetValue =bussNumHash  % availableTargetNames.size();
		String valueOf = String.valueOf(targetValue);
		for (String targetDB : availableTargetNames) {
			if(targetDB.endsWith(valueOf)){
				log.debug("sharding end targetDB:{}",targetDB );
				return targetDB;
			}
		}
		log.info(" end no sharding");
		return null;
	}

**Comment by kimmking** [comment]
@menghaoranss
Is duplicated?

**Comment by menghaoranss** [comment]
> @menghaoranss
> Is duplicated?

This issue is similar to #4043 , namespace configuration should also support empty strategy.
I will try to fix it.

**Comment by menghaoranss** [comment]
@chyangxi 

You can modify the configuration of `<sharding-table-rules>` like this:
```
<sharding:sharding-rule data-source-names="ds0,ds1" default-data-source-name="ds0">
	<sharding:table-rules>
		<sharding:table-rule logic-table="user" actual-data-nodes="ds$->{0..1}.user"
			 database-strategy-ref="databaseStrategy" />
		<sharding:table-rule logic-table="classes" actual-data-nodes="ds$->{0..1}.classes"
			 database-strategy-ref="databaseStrategy" />
		<sharding:table-rule logic-table="mark" actual-data-nodes="ds$->{0..1}.mark"
			 database-strategy-ref="databaseStrategy" />
	</sharding:table-rules>
	<sharding:binding-table-rules>
            <sharding:binding-table-rule logic-tables="user,classes,mark" />
        </sharding:binding-table-rules>
        <!--
	<sharding:broadcast-table-rules > 
			<sharding:broadcast-table-rule table="school_config"/>
	</sharding:broadcast-table-rules>
        -->
</sharding:sharding-rule>
```
just don't configure broadcast-table-rules , then table inter_user and school_config will use 
default data source.

**Comment by kimmking** [comment]
Is this issue resolved now? if it is, we should close it now.
 @menghaoranss @chyangxi

**Comment by menghaoranss** [comment]
> Is this issue resolved now? if it is, we should close it now.
> @menghaoranss @chyangxi

@kimmking  I tried to run with the above configuration, I think it can solve this problem.
