### ISSUE TITLE
Character encoding bug

### ISSUE THREAD

**Issue by zhouzhendao123456** [apache/incubator-shardingsphere#3700]
Sharding-Proxy 4.0

insert into xxx (aaa) values ('chinese name')
chinese name is 
![image](https://user-images.githubusercontent.com/56668316/70498238-b8347280-1b50-11ea-91bb-a6ad1a6f69ea.png)

mysql content 
![image](https://user-images.githubusercontent.com/56668316/70498269-cedac980-1b50-11ea-8844-1cdd46db99af.png)

**Comment by dongzl** [comment]
what is your db & table character config？

you can try insert data directly, not via Sharding-Proxy, It is OK?

I think this is some uncommon characters, the DB doesn't support.

**Comment by terrymanu** [comment]
ShardingSphere nerver released version 4.0, can you provide the correct version number?

**Comment by zhouzhendao123456** [comment]
@terrymanu sharding-proxy 4 rc2
@dongzl mysql use utf8-mb4,no problem

**Comment by dongzl** [comment]
@zhouzhendao123456  I can not write the characters with my input method and test this problem, how do you finish it?

**Comment by zhouzhendao123456** [comment]
@dongzl 
use sharding
run insert sql

**Comment by dongzl** [comment]
How do you input the Chinese character and test insert?  I can not print the character with my input tools.

[](https://user-images.githubusercontent.com/56668316/70498238-b8347280-1b50-11ea-91bb-a6ad1a6f69ea.png)

**Comment by terrymanu** [comment]
Closed because no response anymore.
