### ISSUE TITLE
Could the loading default db table while application start be optimized?

### ISSUE THREAD

**Issue by CatDogZ** [apache/incubator-shardingsphere#3703]
my version is upgraded to  4.0.0-RC3.
and i still have the problem while shardingjdbc load all the default database table metadata info causing application start slowly.   i browsed all the questions commited on the git issues. i set "check.table.metadata.enabled" with false, i event set "executor.size" with 100。 but all of them do not work.   and no body can give  an correct answer。 is this question  an Unsolvable problem？ can someone tell me that whether the problem can be solved or not ?

**Comment by terrymanu** [comment]
Hi, let's talk about in the same issue, thank you.

**Comment by terrymanu** [comment]
duplicated #3681

**Comment by ma1562013338** [comment]
If the default data source has more tables, it's really slow.And set up the 'check.table.metadata.enabled: false' does not take effect.

**Comment by CatDogZ** [comment]
@ma1562013338  so.... is there any other solution?  currently i rewrited the class "TableMetaDataInitializer',  and skip the "loadDefaultTables' method。  then , it start quickly. but i don t  konw whether it has bad effect or not?

**Comment by huangqinghe** [comment]
How to rewrite the class "TableMetaDataInitializer"? Please give me some advice

**Comment by jxxyan** [comment]
> @ma1562013338 so.... is there any other solution? currently i rewrited the class "TableMetaDataInitializer', and skip the "loadDefaultTables' method。 then , it start quickly. but i don t konw whether it has bad effect or not?

how did you change the source code ,download the src and make a new module ?
