### ISSUE TITLE
sharding proxy4.0.x mysql8 How to connect the drive

### ISSUE THREAD

**Issue by Acumes** [apache/incubator-shardingsphere#3712]
I put MySQL driver package under lib, but how to modify the driver class? Directly under config-sharding.yaml, add driverclassname: com.mysql.cj.jdbc.driver, and an error will be reported when starting. Mysql5.7 is OK. I just want to know how to operate mysql8.

**Comment by dongzl** [comment]
Hi @Acumes , Please reference this issue #3097 .

**Comment by cherrylzhao** [comment]
enhance it #5218, mysql8-client will be supported in 4.1.0 release
