### ISSUE TITLE
How do you return the auto-generated id after inserting data?

### ISSUE THREAD

**Issue by peiyou** [apache/incubator-shardingsphere#3713]
How do you return the auto-generated id after inserting data?

My configuration:
spring.shardingsphere.sharding.tables.transaction.key-generator.column=id
spring.shardingsphere.sharding.tables.transaction.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.transaction.key-generator.props.worker.id=123

spring.shardingsphere.sharding.tables.transaction_item.key-generator.column=id
spring.shardingsphere.sharding.tables.transaction_item.key-generator.type=SNOWFLAKE
spring.shardingsphere.sharding.tables.transaction_item.key-generator.props.worker.id=124

LOG:
INSERT INTO transaction_201912  ( user_id,amount,created_time , id) VALUES(?, ?, ?, ?) ::: [1, 300, 2019-12-11 11:23:27.853, 411482226929676289]

I want to get the auto-generated id after inserting the data.

My code:
Transaction transaction = new Transaction();
        transaction.setUserId(userId);
        transaction.setAmount(amount);
        transaction.setCreatedTime(new Date());
        transactionService.insert(transaction);

        TransactionItem transactionItem = new TransactionItem();
        transactionItem.setTransactionId(transaction.getId());
        transactionItem.setNum(num);
        transactionItem.setGoodName("1");
        transactionItem.setPrice(price);
        transactionItem.setCreatedTime(new Date());

        transactionItemService.insert(transactionItem);
BUT:
transaction.getId() is null.   
What should I do?

**Comment by terrymanu** [comment]
Can you try to example first?

**Comment by peiyou** [comment]
> Can you try to example first?
There are table1 and table2, the table1_id of table2 is the ID of table1, and the table1 ID is generated automatically by the snowflake algorithm built in sharding-jdbc.
Now, I'm in the same transaction, I'm adding a piece of table1 data (the transaction didn't commit), and then I need to add table2 data, but I need the ID value of table1, the ID value of this table1, and I can't get that ID at this point.
In mybatis, if table1's ID is automatically generated, the generated ID is automatically injected into the inserted entity class. So I can get the generated ID value from the ID field in the entity class.

**Comment by huang-gz** [comment]
you can try shardingshpere-example org.apache.shardingsphere.example.core.jdbc.repository.OrderRepositoryImpl#insert()

**Comment by terrymanu** [comment]
Closed because no response anymore.
