### ISSUE TITLE
When can we expect GA release for version 4?

### ISSUE THREAD

**Issue by rimal** [apache/incubator-shardingsphere#3721]
## Question

Hello, I have been using version 3.1.0 on my production as per your team's suggestion as version 4 is still in RC stage. 
Since 4.0.0-RC3 is out now, do you have another RC planned or can we now expect version 4 to be released? I am want to integrate it to my production as the version 3.x is now out of service and there are some good changes in version 4 which I will want to adopt.

**Comment by terrymanu** [comment]
Hi, we talking about it at mailing list[1], please have a look.

[1] https://lists.apache.org/thread.html/befefeb3a81c940b51b5059e097e620dbdbef7cff4539fe1cb1f7902%40%3Cdev.shardingsphere.apache.org%3E
