### ISSUE TITLE
How to use nacos in sharingsphere

### ISSUE THREAD

**Issue by keven0706** [apache/incubator-shardingsphere#3722]
## Question
How to config in sharingsphere to support nacos? ths!

**Comment by dongzl** [comment]
Hi @keven0706 , 
now the nacos's support is not enough, ShardingSphere support ZooKeeper very well and you can try it.

Now we are refactoring the orchestration module, after refactor, it will support nacos very well, it will be released at 5.x version. Thanks.

**Comment by keven0706** [comment]
thanks，expectation！
