### ISSUE TITLE
SQL value with \"xx\"  parse error when use encrypt

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#3735]
### Which version of ShardingSphere did you use?
4.0.0-RC3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
insert error
### Actual behavior
![image](https://user-images.githubusercontent.com/8772975/70786677-2a62bc80-1dc8-11ea-9445-4988dc84c174.png)
### Reason analyze (If you can)
parse error for sql like this:
String sql = "insert into fix_test(`id`,`name`,`password`) values (4,\"you.wang@xxx.com\",'123456')";
![image](https://user-images.githubusercontent.com/8772975/70786729-41091380-1dc8-11ea-858c-f88166073ea5.png)

**Comment by SteNicholas** [comment]
@xiyelife `String sql = "insert into fix_test(id,name,password) values (4,"you.wang@xxx.com",'123456')";` SQL you provided is wrong. 
You can try to modify `INSERT_GENERATED_KEY_SQL` of `EncryptStatementTest` to `"INSERT INTO t_encrypt(pwd) VALUES ('\"you.wang@xxx.com\"')"` , and run the test method `assertInsertWithExecuteWithGeneratedKey`. This works well.

**Comment by xiyelife** [comment]
@SteNicholas the sql above has been formated by github, the sql is real like this in the code (idea)：
![image](https://user-images.githubusercontent.com/8772975/70873367-79873800-1fe8-11ea-8589-d1217028d018.png)
I think this writing should be right
