### ISSUE TITLE
Support parser module add Oracle, SQLServer and SQL92 DALStatement

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-shardingsphere#3739]
## Feature Request

Parser module add Oracle, SQLServer and SQL92 DALStatement like `SHOW DATABASE`, `DESC tableName` etc.

### Is your feature request related to a problem?

Yes.

### Describe the feature you would like.

Support Oracle, SQLServer and SQL92 DALStatement of parser module.

**Comment by terrymanu** [comment]
Closed until somebody interesting about this issue
