### ISSUE TITLE
ComplexKeysShardingAlgorithm<T extends Comparable<?>> Actual Use Suggestion

### ISSUE THREAD

**Issue by fenghuanfun** [apache/incubator-shardingsphere#3742]
### Is your feature request related to a problem?
 - I report a bug in an issue, and it's version is ` sharding-jdbc-core:4.0.0-RC1 `
[ComplexKeysShardingAlgorithm ClassCastException](https://github.com/apache/incubator-shardingsphere/issues/2613)
- now it hava been fixed in  ` sharding-jdbc-core:4.0.0-RC3 `
- However, i dont think it is the right way to resove this problem
- example, in this ` ShardingAlgorithm ` 
```java
public class BaseComplexKeysShardingAlgorithm implements ComplexKeysShardingAlgorithm<Timestamp> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Timestamp> shardingValue) {
        Range<Timestamp> range = shardingValue.getColumnNameAndRangeValuesMap().get("create_time");
        Timestamp timestamp = range.upperEndpoint();
        System.out.println(timestamp);
        return availableTargetNames;
    }
}
```
      the field 'create_time' type is datetime(6) in mysql, java.sql.Timestamp in Java Entity
- if the sql is ` select * from t_order where create_time = '2019-12-01 00:00:00.000000' ;`
 the `ShardingAlgorithm ` will receive a sharingValue that instance of Timestamp. 
No problem so far.
- However, if i use mysql function like `date_format`, the sql change to ` select * from t_order where date_fromat(create_time,'%Y-%m-%d') = '2019-12-01' ;` 
 it will receive ` ClassCastException` again when i try to get the sharding value. because the sharding value's type is `java.lang.String` indeed

### Describe the feature you would like.
- in this sample, i think this situation exist in other mysql function too
- so i suggest that `sharding-jdbc` should not just add a GenericType on `org.apache.shardingsphere.api.sharding.complex.ComplexKeysShardingAlgorithm<T extends Comparable<?>>`. 
- GenericType limit that one field only have one type in a `ShardingAlgorithm`
- Looking forward to your reply, thank you

**Comment by KomachiSion** [comment]
Sorry, @fenghuanfun , SQL like `select * from t_order where date_fromat(create_time,'%Y-%m-%d') = '2019-12-01'` is not supported now. The shardingColumn was covered by function will cause the route Algorithm can't execute correctly.

**Comment by SteNicholas** [comment]
@fenghuanfun The reason is that MySQLParser doesn't support function like `date_format`. Sharding column should be supported by the supported function.

**Comment by terrymanu** [comment]
`date_format` of sharding can not support, because all sharding values must parse from SQL. But the function `date_format` need calculate from database.
