### ISSUE TITLE
ShardingPreparedStatement.getGeneratedKey() 方法强转报错

### ISSUE THREAD

**Issue by ljyhust** [apache/incubator-shardingsphere#3744]
private Optional<GeneratedKey> getGeneratedKey() {
    return null != this.sqlRouteResult && this.sqlRouteResult.getOptimizedStatement().getSQLStatement() instanceof InsertStatement ? ((ShardingInsertOptimizedStatement)this.sqlRouteResult.getOptimizedStatement()).getGeneratedKey() : Optional.absent();
}

mybatis 插入返回自增主键封装到entity有问题，报错处代码如上。这个语句判断的类型是不是有点问题？通过接口看 找不到instanceof判断与后面 强转 的联系
版本  4.0.0-CR2

**Comment by ljyhust** [comment]
版本  4.0.0-RC2

**Comment by betterjava** [comment]
**for English only**
