### ISSUE TITLE
Sql parse - support MySQL `Mod` function

### ISSUE THREAD

**Issue by BearKid** [apache/incubator-shardingsphere#3748]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC3

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
sql that contains MySQL `Mod` function in WHERE clause shall work

### Actual behavior
- error log got : line 1:36 extraneous input 'MOD'
- inforamtation about `ORDER BY` and `LIMIT ` lost after sql parase

### Reason analyze (If you can)
maybe same as #3271 

### Example codes for reproduce this issue (such as a github link).
`
SELECT * FROM xxl_mq_message WHERE MOD(id, 3) = 2 ORDER BY id ASC LIMIT 0,2
`

**Comment by BearKid** [comment]
@tuohai666 excuse me, any idea to solve this `MOD`  sql function problem ? 
I will be appreciated with your help.

**Comment by tuohai666** [comment]
You can try to resolve just like #3271. I'll review your pr.

**Comment by SteNicholas** [comment]
@terrymanu @tuohai666 I will fix this bug. Please assign to me.

**Comment by terrymanu** [comment]
@SteNicholas Thank you, assigned

**Comment by tristaZero** [comment]
Hi @BearKid   this bug is fixed in [3753](https://github.com/apache/incubator-shardingsphere/pull/3753) by @SteNicholas, if possible, could give it a test?
