### ISSUE TITLE
Encounter "More than one table found in namespace" Error under rc2/rc3

### ISSUE THREAD

**Issue by freezingWu** [apache/incubator-shardingsphere#3755]
I am doing the testing  with JPA and sharding-jdbc-spring-boot-starter: 4.0.0-RC3(same issue under 4.0.0-RC2) by following steps:
1. create an Entity(table) with name "ENTITY_INFO"
2. mark hibernate.ddl-auto to update 
3. adding sharding as bellow: 
spring.shardingsphere.sharding.tables.ENTITY_INFO.table-strategy.actual-data-nodes=ds_master.ENTITY_INFO_${201901..201912}
spring.shardingsphere.sharding.tables.ENTITY_INFO.table-strategy.standard.sharding-column=CREATED_DATE
4. start the application , and the JPA will create the table "ENTITY_INFO" automatically as expected.
5. restart the application , and keep the aforementioned information as what it was. but at this time, i  hit the error "More than one table found in namespace" .

I checked the document from website, and seens there is no any precondition on settting hibernate.ddl-auto to "none" .

may i consider it's issue here ?

**Comment by terrymanu** [comment]
The exception `More than one table found in namespace` has thrown from hibernate.
Maybe can help you: https://stackoverflow.com/questions/36907095/more-than-one-table-found-in-namespace-schemaextractionexception
