### ISSUE TITLE
no viable alternative at input '(channel'

### ISSUE THREAD

**Issue by snakeeeeeeeee** [apache/incubator-shardingsphere#3757]
# Which version of ShardingSphere did you use?
4.0.0-RC3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
execute sql:
insert into demo(channel, name) values ('xx', 'xx') 
report error:
no viable alternative at input '(channel'
### Actual behavior
Insert record faild
### Reason analyze (If you can)
'channel' seems to be the keywords of sql parsing

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

sql:
insert into demo(channel, name) values ('xx', 'xx')

spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    props:
      sql:
        show: true
    sharding:
      tables:
        user:
          actual-data-nodes: ds0.demo_$->{0..1}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: demo_$->{id % 2}
              sharding-column: id

**Comment by SteNicholas** [comment]
@snakeeeeeeeee You are right, because this keyword isn't assigned to unreserved keywords. I will fix it. @terrymanu Please assign this to me.

**Comment by terrymanu** [comment]
@SteNicholas Thank you, assigned.

**Comment by freezingWu** [comment]
> @snakeeeeeeeee You are right, because this keyword isn't assigned to unreserved keywords. I will fix it. @terrymanu Please assign this to me.

HI team, I encounter the same issue also. 
May I know  is there any work around  approach to make it work ?

**Comment by snakeeeeeeeee** [comment]
@freezingWu  you can do this: 
 insert into name(`channel`) values('xxx')

**Comment by snakeeeeeeeee** [comment]
@freezingWu  
![image](https://user-images.githubusercontent.com/26361007/71079472-48fcf500-21c6-11ea-9f29-9da0b14ec57b.png)

**Comment by snakeeeeeeeee** [comment]
@freezingWu 
![image](https://user-images.githubusercontent.com/26361007/71079563-75187600-21c6-11ea-8628-1ee2571f7985.png)

**Comment by freezingWu** [comment]
@snakeeeeeeeee 
Here comes the workaround solution for JPA (refer to : https://vladmihalcea.com/escape-sql-reserved-keywords-jpa-hibernate/) when runing with sharding-jdbc.
And thanks for your kindly help.

**Comment by chenghao111** [comment]
> @freezingWu
> ![image](https://user-images.githubusercontent.com/26361007/71079563-75187600-21c6-11ea-8628-1ee2571f7985.png)

it does not works

**Comment by tristaZero** [comment]
Hi @chenghao111 
I suppose the 5.0.0.alpha has fixed this issue, please give it try.

**Comment by chenghao111** [comment]
> Hi @chenghao111
> I suppose the 5.0.0.alpha has fixed this issue, please give it try.

ok  thanks !
