### ISSUE TITLE
'UNION' sql  grammar not support

### ISSUE THREAD

**Issue by iamamaster** [apache/incubator-shardingsphere#3764]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC3</version>
        </dependency>

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support sql  grammar 'UNION' 

### Actual behavior
'UNION' sql  grammar not support
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
( SELECT
	`status`,
	final_time,
	card_id,
	pin,
	apply_id 
	FROM
		t_apply_info 
	WHERE
		1 = 1 
		AND pin = ? 
		AND card_id = ? 
		AND delete_flag = 1 
		AND `status` IN ( 3, 5, 7 ) 
	ORDER BY
		final_time DESC 
		LIMIT 0,1 
	) 
UNION
	(
	SELECT
		`status`,
		final_time,
		card_id,
		pin,
		apply_id 
	FROM
		t_apply_info 
	WHERE
		1 = 1 
		AND pin = ? 
		AND bank_no = ? 
		AND delete_flag = 1 
		AND `status` IN ( 7, 1 ) 
	ORDER BY
		final_time DESC 
		LIMIT 0,1 
	) 
ORDER BY
	final__time DESC

**Comment by SteNicholas** [comment]
@iamamaster Your SQL is something wrong that `UNOIN` both side select statements are unnecssary to add `()`.

**Comment by kimmking** [comment]
if you wanna sort your records after union, you should add a select to wrap the union and then with order clause.

**Comment by terrymanu** [comment]
`UNION` is not easy to support, beside parse, we need to do query engine too.
We have no plan to do union for now
