### ISSUE TITLE
When a columnName contains other columnName, one of the two column is decrypt fail

### ISSUE THREAD

**Issue by Keanhua** [apache/incubator-shardingsphere#3767]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
When a columnName contains other columnName, all the two column is decrypt correct
### Actual behavior
When a columnName contains other columnName, one of the two column is decrypt fail
### Reason analyze (If you can)
When the column to decrypt,i guess use the string.contains to find the column
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
you can config like this. the bug is always occured.
encrypt:
      encryptors:
        encryptor_aes:
          type: AES
          props:
            aes.key.value: eyHXCWAoB69&
      tables:
        sharding_test:
          columns:
            title:
              cipherColumn: title
              encryptor: encryptor_aes
            a_title:
              cipherColumn: a_title
              encryptor: encryptor_aes

**Comment by SteNicholas** [comment]
@terrymanu Please assign the bug to me for fixing the case @Keanhua mentioned above.

**Comment by terrymanu** [comment]
@SteNicholas Assigned.

**Comment by SteNicholas** [comment]
@Keanhua Could you please add my wechat 834031959 to give the exception detail?

**Comment by Keanhua** [comment]
can not reshow
