### ISSUE TITLE
how to route master special table name

### ISSUE THREAD

**Issue by zhp1254** [apache/incubator-shardingsphere#3769]
## Question

for special table we want use master db always
but others select with slave and update with master

we use springmvc + mybatis
how can i config <master-slave:data-source />

**Comment by terrymanu** [comment]
what is your special table name?

**Comment by zhp1254** [comment]
@terrymanu
such as  table `account` which storage user balance or score

**Comment by terrymanu** [comment]
What is different with `special` table name or `normal` table name?

**Comment by zhp1254** [comment]
There is no difference；these table is important in our system that we want route all the sql to master

**Comment by terrymanu** [comment]
Has your problem solved?
