### ISSUE TITLE
DataSource naming conflict between sharding-jdbc and druid

### ISSUE THREAD

**Issue by Z-J-Fei** [apache/incubator-shardingsphere#3773]
Description:
The bean 'dataSource', defined in class path resource [io/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class] and overriding is disabled.

druid-spring-boot-starter:1.1.20
sharding-jdbc-spring-boot-starter:3.1.0
springboot:2.2.2

what should I do？
Except (spring.main.allow-bean-definition-overriding = true)

**Comment by KomachiSion** [comment]
Would you tell me why do you use `druid-spring-boot-starter`, if only druid and shardingsphere, there are no necessary to use druid-spring-boot-starter.

If you want to use multiple Datasource in spring boot, the only way is using self-configuration to create Datasources by yourself.
