### ISSUE TITLE
How Can I config To Use DatabaseHintRoutingEngine

### ISSUE THREAD

**Issue by tmjGitAccount** [apache/incubator-shardingsphere#3774]
Sharding-Sphere Vsersion：4.0.0-RC3

I config 2 datasources in my project ,what i want is to use the hint route Strategy
Here is my properties 
```spring:
  shardingsphere:
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        hint:
          algorithm-class-name: a.b.c.OrderShardingAlgorithm
      default-data-source-name: ds1
    datasource:
      names: ds1,ds2
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: xxx
        username: xxx
        password: xxx
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl:xxx
        username: xxx
        password: xxx
```
Here is the code 
```
@Slf4j
@NoArgsConstructor
@Component("orderShardingAlgorithm")
public class OrderShardingAlgorithm implements HintShardingAlgorithm<String> {

    @Override
    public List<String> doSharding(final Collection<String> availableTargetNames, final HintShardingValue<String> shardingValue) {
        return Optional.ofNullable(SessionUtils.getAgency())
                .map(value -> availableTargetNames.stream().filter(v -> v.equals(value)).collect(Collectors.toList()))
                .filter(value -> !value.isEmpty())
                .orElse(new ArrayList<>(availableTargetNames));

    }
}
```
But it seems the  a.b.c.OrderShardingAlgorithm never take effect,I debug into the RoutingEngineFactory.newInstance() method, it always new  a **DefaultDatabaseRoutingEngine** rather than a **DatabaseHintRoutingEngine**, so did I miss some config? Or there is a bug here?

And Actually I didn't find  the code that  **RoutingEngineFactory.newInstance()**  can create a **DatabaseHintRoutingEngine** instance.

**Comment by SteNicholas** [comment]
@tmjGitAccount You are right. `DatabaseHintRoutingEngine` isn't used in `RoutingEngineFactory `. @terrymanu Could you please assign this to me for fixing?

**Comment by terrymanu** [comment]
@SteNicholas thank you, assigned.

**Comment by SteNicholas** [comment]
@tmjGitAccount Your understood exists mistake. `RoutingEngineFactory.newInstance()` should return `StandardRoutingEngine`, and call method `route()` to load your algorithm. Here isn't through DatabaseHintRoutingEngine.

**Comment by SteNicholas** [comment]
@tmjGitAccount What's more, `DatabaseHintRoutingEngine` isn't used in any routing case and modules. Therefore, the `DatabaseHintRoutingEngine` is necessary to remove. Where load your algorithm is that `StandardRoutingEngine` calls method `route()` to load user-defined algorithm.

**Comment by tmjGitAccount** [comment]
> @tmjGitAccount What's more, `DatabaseHintRoutingEngine` isn't used in any routing case and modules. Therefore, the `DatabaseHintRoutingEngine` is necessary to remove. Where load your algorithm is that `StandardRoutingEngine` calls method `route()` to load user-defined algorithm.

Thx For Your Reply, But there is still something wrong for me ,

**Comment by tmjGitAccount** [comment]
> @tmjGitAccount What's more, `DatabaseHintRoutingEngine` isn't used in any routing case and modules. Therefore, the `DatabaseHintRoutingEngine` is necessary to remove. Where load your algorithm is that `StandardRoutingEngine` calls method `route()` to load user-defined algorithm.

Thx for your reply, but there is still something wrong for me, 
As you can see My perpose is to get sth from session  to hint the datasource.

1. if my conf is like what i  offered before, it will new a DefaultDatabaseRoutingEngine as follows, it always hint my defaultDatabase.
RoutingEngineFactory:83
```
if (shardingRule.isAllInDefaultDataSource(tableNames)) {
            return new DefaultDatabaseRoutingEngine(shardingRule, tableNames);
        }
```
2.then i add  some confs for tables,confs are as follows: 
```
tables:
        my_table:
          database-strategy:
            hint:
              algorithm-class-name: a.b.c.OrderShardingAlgorithm
          table-strategy:
            hint:
              algorithm-class-name: a.b.c.OrderShardingAlgorithm
```
then  the  factory can  create a  StandardRoutingEngine  instance,  
and the codes  execute as 
**route()  ->  
getDataNodes() -> 
routeByHint() -> 
route0() -> 
getDatabaseShardingValuesFromHint() -> 
routeDataSources() ->
 myalgorithm.dosharding()**
i don't know if it's the correct way , but currently the method **getDatabaseShardingValuesFromHint()**  always retruns  an empty list  and then  the method **routeDataSources()** won't execute my algorithm, it returns directly.
```
public static Collection<Comparable<?>> getDatabaseShardingValues(final String logicTable) {
        return null == HINT_MANAGER_HOLDER.get() ? Collections.<Comparable<?>>emptyList() : HINT_MANAGER_HOLDER.get().databaseShardingValues.get(logicTable);
    }
```
this code compares my databases with table's name , so it always retruns empty.
```
HINT_MANAGER_HOLDER.get().databaseShardingValues.get(logicTable)
```
so i don't know if  i lost some conf or others , could u please help me for this. 😃

**Comment by SteNicholas** [comment]
@tmjGitAccount Because you didn't execute `HintAddDatabaseShardingValueCommand` command like `sctl:hint addDatabaseShardingValue xx=yy.`.

**Comment by tmjGitAccount** [comment]
> @tmjGitAccount Because you didn't execute `HintAddDatabaseShardingValueCommand` command like `sctl:hint addDatabaseShardingValue xx=yy.`.

@SteNicholas  doesn't this command only belongs to sharding-proxy?   can i use it in sharding-jdbc?

**Comment by SteNicholas** [comment]
@tmjGitAccount You only through `sctl:hint addDatabaseShardingValue xx=yy` to execute `HintAddDatabaseShardingValueCommand `, then `HintAddDatabaseShardingValueExecutor` will execute this command.

**Comment by tmjGitAccount** [comment]
😥  i mean i use **sharding-jdbc** rather than sharding-proxy, 
can't i use my self-defined algorithm in sharding-jdbc?

**Comment by gongguoyu** [comment]
in 4.1.1 shill have this problem.....

**Comment by cnlinjie** [comment]
in 4.1.1 shill have this problem.....

😔😔😔

**Comment by cnlinjie** [comment]
@SteNicholas
