### ISSUE TITLE
Does Sharding JDBC have "Consistent Hashing " default sharding table strategy?

### ISSUE THREAD

**Issue by yuboliang** [apache/incubator-shardingsphere#3778]
Does Sharding JDBC have "Consistent Hashing " sharding table strategy?
Or "Consistent Hashing " need myself to implement it?

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by yuboliang** [comment]
ok！I will try to change a friendly title，but my English is worst， please forgive me！


 
---Original---

**Comment by terrymanu** [comment]
No, all sharding strategy should written by developers.
