### ISSUE TITLE
spring boot 连接查询问题

### ISSUE THREAD

**Issue by itxiaole** [apache/incubator-shardingsphere#3784]
spring boot 项目 order一个库 表order_1 order_2  一个库 order_item 表 order_item_1 order_item2,连接查询  一直说mybatis 系统异常 然后是数据下表越界,这样的sql 不允许吗? 我分表对这两个表新增都是ok的,但是就是连接查询有问题,分别查询也没问题,求大佬解决一下,这样的查询是不允许,还是暂时不支持呢

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
