### ISSUE TITLE
Docker container unable to start

### ISSUE THREAD

**Issue by uffy** [apache/incubator-shardingsphere#3788]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
docker image: shardingsphere/sharding-proxy:latest 

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-Proxy

### Expected behavior

normally running

### Actual behavior

Immediately exit with status code 0 when I exec docker run command

### Reason analyze (If you can)

I guess there is a abnormal image in shardingsphere/sharding-proxy docker repository

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

RUN:
docker run -v /tmp/sharding-proxy-conf/:/opt/sharding-proxy/conf --rm -p13308:3307 apache/sharding-proxy:latest && echo $?

OUTPUT:
0

**Comment by terrymanu** [comment]
What is the error message log?

**Comment by topsale** [comment]
But is no message logs....

> What is the error message log?

But is no message logs .

**Comment by topsale** [comment]
My compose file is

version: '3.1'
services:
  sharding-proxy:
    image: apache/sharding-proxy:latest
    container_name: sharding-proxy
    ports:
      - 13308:3308

and running:

Starting sharding-proxy ... done
Attaching to sharding-proxy
sharding-proxy exited with code 0

But 4.0.0-RC2 do not have this problem .

**Comment by terrymanu** [comment]
You can check the log file first, it should be some hint in the log

**Comment by uffy** [comment]
These is no message logs, and I run docker inspect command for the exited container:
```
...
"Config": {
	"Cmd": [
		"/bin/sh"
	],
	"Entrypoint": null,
	...
}
...
```

this container seems only run a shell

**Comment by uffy** [comment]
@terrymanu 
I try to extract docker image as plain files, and found the official image is only contains a java environment without shardingsphere proxy execute file.

**Comment by haocao** [comment]
@uffy The docker image has been released again, please try the latest version again, thanks.

**Comment by haetao** [comment]
@uffy Hi! you use docker-compose.yaml to use sharding-proxy  ,why not try to use `docker-compose up`  to  build  sharding-proxy container? And the latest image of sharding-proxy 
 is not `shardingsphere/sharding-proxy:latest`  , it is `apache/sharding-proxy:latest`.

**Comment by uffy** [comment]
@haocao @haetao 

The problem seems still here, I'd try to build image myself and it work fine, but it is better for me if there is a working-fine official image.

-----

➜  ~ docker pull apache/sharding-proxy:latest
latest: Pulling from apache/sharding-proxy
Digest: sha256:ab8634da397da09807f913dc428baa01fbd6b4f9f38843423d909e06a5f0683d
Status: Image is up to date for apache/sharding-proxy:latest
docker.io/apache/sharding-proxy:latest
➜  ~ docker run -v /tmp/sharding-proxy-conf/:/opt/sharding-proxy/conf --env=PORT=3308 -p13308:3308 apache/sharding-proxy:latest
➜  ~ docker ps -n1
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS                     PORTS               NAMES
96399e4664d0        apache/sharding-proxy:latest   "/bin/sh"           3 seconds ago       Exited (0) 2 seconds ago                       focused_keldysh

**Comment by haocao** [comment]
@uffy 
Could you please remove your image firstly?After removed the local image and download the newest image, it could work.
➜  ~ docker rmi -f $(docker images -q)
Deleted: sha256:985d87dd0d089dfe55ddbc9a1dda77f536560b57d58c77e3a954228c4a7120d6
➜  ~ docker pull apache/sharding-proxy:latest
latest: Pulling from apache/sharding-proxy
5040bd298390: Already exists
fce5728aad85: Already exists
76610ec20bf5: Already exists
60170fec2151: Already exists
66b144b1d5b0: Already exists
6263baad4f89: Already exists
917299857928: Already exists
Digest: sha256:f542e7601228ccba883a0bf399af468d9aabfe92392da44fbc3b8c8ae7d17c80
Status: Downloaded newer image for apache/sharding-proxy:latest
docker.io/apache/sharding-proxy:latest
➜   ~ docker run -v /Users/caohao/sharding-proxy-conf/:/opt/sharding-proxy/conf --env=PORT=3308 -p13308:3308 apache/sharding-proxy:latest
Starting the Sharding-Proxy ...
The port is configured as 3308
Please check the STDOUT file: /opt/sharding-proxy/logs/stdout.log
➜  ~ docker ps -n1
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                     NAMES
b68c005028e2        apache/sharding-proxy:latest   "/bin/sh -c '/opt/sh…"   About a minute ago   Up About a minute   0.0.0.0:13308->3308/tcp   sharp_northcutt

**Comment by uffy** [comment]
I found it's a docker registry mirror's issue, it not up the image to date, but finally, it is working, thanks
