### ISSUE TITLE
Database profile password needs encryption

### ISSUE THREAD

**Issue by huskebi** [apache/incubator-shardingsphere#3789]
Password encryption of database configuration file is required. When starting the project，
I didn't find a solution

**Comment by terrymanu** [comment]
Apache ShardingSphere is not a all-in-one solution, just like MySQL do not support password encryption.
So, what do you think about Apache ShardingSphere's scope?

**Comment by ssxlulu** [comment]
Support password encryption in configuration file may meet safety requirements for some companys.

So will ss consider this feature later?

**Comment by terrymanu** [comment]
I prefer no. because every company has their own encrypt policy for database access. It is not a core scope of an OSS
