### ISSUE TITLE
error return :SHOW FULL TABLES FROM `sharding_db` LIKE 't_mail'

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#3791]
apache-shardingsphere-incubating-4.0.0-RC3-sharding-proxy-bin.tar.gz

query sql:SHOW FULL TABLES FROM `sharding_db` LIKE 't_mail'
return no record.
but mysql return 1 record.

**Comment by wangjing112** [comment]
but it work fine in sharding-jdbc 4.0.0-RC2

**Comment by terrymanu** [comment]
duplicate with #2904
