### ISSUE TITLE
how cfg defaultTableStrategy ?

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#3793]
if many tables use same column name like "id" sharding.
how can i use the cfg defaultTableStrategy ?
please give a example,thanks!

**Comment by terrymanu** [comment]
FIY: https://github.com/apache/incubator-shardingsphere-example

**Comment by wangjing112** [comment]
> FIY: https://github.com/apache/incubator-shardingsphere-example

all example the defaultTableStrategy is none.
