### ISSUE TITLE
Some question about HintManager in sharding-jdbc

### ISSUE THREAD

**Issue by songjiesdnu** [apache/incubator-shardingsphere#3806]
## I cannot achieve the HintManager instance twice in one thread
There is a case:
```java
A(){
    B();
}
```
In method A, we set a hint rule, and we also want to set another hint rule in method B.By reading the source code, we found that, we cannot achieve the same instance of HintManager again, thus we cannot set another rule in method B.
Is there some means we can use to meet our demand?

**Comment by huang-gz** [comment]
use org.apache.shardingsphere.api.hint.HintManager#clear(), Clear threadlocal for hint manager.

**Comment by terrymanu** [comment]
Hint should not call nested, if user do that, will throw exception: `Hint has previous value, please clear first.`

**Comment by songjiesdnu** [comment]
> Hint should not call nested, if user do that, will throw exception: `Hint has previous value, please clear first.`

the problem is that when i want to use HintManager in some place, i do not known HintManager has been set in other place or not.
what i need is HintManager can add a static method to check whether HintManager has been seted.

**Comment by cnlinjie** [comment]
@terrymanu 
You will only close
