### ISSUE TITLE
Can't parallel execute sql, when connection autoCommit is false, readOnly is ture,max.connections.size.per.query is greater than 1 

### ISSUE THREAD

**Issue by dxf2006** [apache/incubator-shardingsphere#3812]
SQLExecuteTemplate  serial exec sql by  connection.isHoldTransaction(),  if add connection.isReadOnly()  check , whether it will better, this scenario can parallel execute.

    SQLExecuteTemplate    sqlExecuteTemplate = new SQLExecuteTemplate(executeEngine, connection.isHoldTransaction() && !connection.isReadOnly());

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Can you provide your rule configuration and SQL?

**Comment by terrymanu** [comment]
Closed because no response anymore
