### ISSUE TITLE
Sharding JDBC does not support oracle insert all syntax

### ISSUE THREAD

**Issue by itxiaole** [apache/incubator-shardingsphere#3813]
The order insert all statement, which is fine in the database, does not seem to be supported by Shrding JDBC

       INSERT ALL
      
            into order_info_1 (
						ORDER_ID,
            ORDER_PRICE,
            ORDER_INVENTORY)
            VALUES
            (11,1,2)
        into order_info_1 (
						ORDER_ID,
            ORDER_PRICE,
            ORDER_INVENTORY)
            VALUES
            (12,1,2)
        SELECT 1 FROM DUAL
				

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

**Comment by itxiaole** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC1</version>
        </dependency>

**Comment by SteNicholas** [comment]
@itxiaole In current version, OracleParser doesn't support ALL syntax. @terrymanu Please assign to me to support this.

**Comment by terrymanu** [comment]
No plan to support more oracle dialect, I want leave it to volunteer.
Anybody who want to do this feature, we can talk about details, or just reference about MySQL's `insert values (), (), ()...`

**Comment by terrymanu** [comment]
Closed until somebody interesting about this issue

**Comment by figuewang** [comment]
i have test it, but have  one bug,when insert two data,it throw exception;
![image](https://user-images.githubusercontent.com/5305551/80551183-35c02880-89f5-11ea-93c2-3349701c94da.png)

**Comment by figuewang** [comment]
i have test it, but have one bug,when insert two data into oracle,it throw exception;
