### ISSUE TITLE
how to dynamic work.id for snowflake

### ISSUE THREAD

**Issue by toby1024** [apache/incubator-shardingsphere#3823]
In `SnowflakeShardingKeyGenerator.java:44` says 

>  
<p>
  Call @{@code SnowflakeShardingKeyGenerator.setWorkerId} to set worker id, default value is 0.
 </p>
 

but the the getWorkId method is private and there isn't have setWorkId method.
I need dynamic set it from the IP address, how can I setWorkId?

**Comment by dongzl** [comment]
Hi @toby1024 , You can try `org.apache.shardingsphere.orchestration.internal.keygen.LeafSnowflakeKeyGenerator`, it can init workId at `RegistryCenter`.

**Comment by toby1024** [comment]
> Hi @toby1024 , You can try `org.apache.shardingsphere.orchestration.internal.keygen.LeafSnowflakeKeyGenerator`, it can init workId at `RegistryCenter`.

It will introduce zookeeper，not the best way for me

**Comment by terrymanu** [comment]
FIY: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-java/
