### ISSUE TITLE
两张表通过相同字段进行分表后，进行连表查询，结果有误

### ISSUE THREAD

**Issue by simayi** [apache/incubator-shardingsphere#3833]
table1和table2都是通过TENANT_ID进行分表，table1和table2各分了8张表；
使用Springboot+Mybatis；
Mapper文件中的SQL为：
select
		distinct t.ITEM_ID T_ITEM_ID, t.*
		from table1 t inner join table2 r on t.TENANT_ID = r.TENANT_ID and t.ORG_ID = r.ORG_ID
		where r.TENANT_ID = 8
		and t.TENANT_ID = 8
		and r.ORG_ID = 12
		and t.ITEM_STATUS = 1
                and t.CATEGORY_ID = 1
启动后调用该SQL，打印的SQL日志中：
查询结果总数的SQL返回4条，正确，查询结果却返回0条；

**Comment by simayi** [comment]
111

**Comment by terrymanu** [comment]
For English only
