### ISSUE TITLE
广播表、绑定表配置无效 yml是否需要加spring:   shardingsphere:前缀

### ISSUE THREAD

**Issue by maojing123** [apache/incubator-shardingsphere#3839]
麻烦帮忙看看 如下对应的yML配置为什么没有生效

![image](https://user-images.githubusercontent.com/48919665/71591490-874fc800-2b67-11ea-8997-f82baa0af224.png)

官网的看yml对应广播表是broadcastTables
![image](https://user-images.githubusercontent.com/48919665/71591631-080ec400-2b68-11ea-80ec-bc45dd21d15c.png)

但是按照官网的配置不生效 请问 如何配置了 是否有相关的demo或者文章之类的（不看官网的 官网的真的和实际的配置不一样配置好久没生效）麻烦指点

2.广播表 我理解是 每个数据库db上都配置如字典表。 那么 A 库 修改了字典表 是会自动同步更新B c数据库吗？配置这个广播的作用是？ 如下只是介绍了广播表的作用。

广播表是指所有底层分片数据源中都存在的表，表结构和表中的数据在每个分库中完全一致。

这样在进行关联查询的时候，由于广播表在所有分库均存在，就避免了笛卡尔积关联查询以及跨库关联的情况。比较适用于数据量不大且需要与海量数据的表进行关联查询的场景，例如：字典表。

**Comment by maojing123** [comment]
不加spring:
  shardingsphere:好像按照官网的配置是dataSources：shardingRule：开头的 。是不是官网的少了部分没有写出来了？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
