### ISSUE TITLE
Why does the INSERT SQL have no routing

### ISSUE THREAD

**Issue by beijixi** [apache/incubator-shardingsphere#3840]
## Question

**sql:**  
`INSERT INTO LDPerson(PersonID,CustomerNo,Name,Sex,Birthday,IDType,IDNo,Password,NativePlace,Nationality,RgtAddress,Marriage,MarriageDate,Health,Stature,Avoirdupois,Degree,CreditGrade,OthIDType,OthIDNo,ICNo,GrpNo,JoinCompanyDate,StartWorkDate,Position,Salary,OccupationType,OccupationCode,WorkType,PluralityType,DeathDate,SmokeFlag,BlacklistFlag,Proterty,Remark,State,VIPValue,Operator,MakeDate,MakeTime,ModifyDate,ModifyTime,GrpName,License,LicenseType,IDValidate,Socialinsuno)
VALUES(101802,'12323123' ,'jason', 0 ,'1999-01-01',0, '22232223' , null , null , null , null , null , null , null , 0.0 , 0.0 , null , null , null , null , null , null , null , null , null , 0.0 , null , null , null , null , null , null , null , null , null , '1' , null , 'cbs' , '2019-12-30' , '18:26:52' , '2019-12-30' , '18:26:52' , null , null , null , null , null);`
**sharding-config:**
LDPerson:
&ensp;&ensp;actualDataNodes: ds${0..1}.LDPerson
 &ensp;&ensp;databaseStrategy:
&ensp;&ensp;&ensp;&ensp;inline:
   &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;shardingColumn: PersonID
 &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;algorithmExpression: ds${PersonID % 2}
   
**description:**
&ensp;&ensp;No matter which field is used as the route key,the data exists in ds0 and ds1

**Comment by terrymanu** [comment]
What is your version? Can you provide your `sql.show`?

**Comment by beijixi** [comment]
**version:**4.0.0-RC1

**sql.show:**
**Logic SQL:** INSERT INTO LDPerson(PersonID,CustomerNo,Name,Sex,Birthday,IDType,IDNo,Password,NativePlace,Nationality,RgtAddress,Marriage,MarriageDate,Health,Stature,Avoirdupois,Degree,CreditGrade,OthIDType,OthIDNo,ICNo,GrpNo,JoinCompanyDate,StartWorkDate,Position,Salary,OccupationType,OccupationCode,WorkType,PluralityType,DeathDate,SmokeFlag,BlacklistFlag,Proterty,Remark,State,VIPValue,Operator,MakeDate,MakeTime,ModifyDate,ModifyTime,GrpName,License,LicenseType,IDValidate,Socialinsuno) VALUES( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?)

**SQLStatement:** InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=LDPerson, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=LDPerson, quoteCharacter=NONE, schemaNameLength=0)], parametersIndex=0, logicSQL=INSERT INTO LDPerson(PersonID,CustomerNo,Name,Sex,Birthday,IDType,IDNo,Password,NativePlace,Nationality,RgtAddress,Marriage,MarriageDate,Health,Stature,Avoirdupois,Degree,CreditGrade,OthIDType,OthIDNo,ICNo,GrpNo,JoinCompanyDate,StartWorkDate,Position,Salary,OccupationType,OccupationCode,WorkType,PluralityType,DeathDate,SmokeFlag,BlacklistFlag,Proterty,Remark,State,VIPValue,Operator,MakeDate,MakeTime,ModifyDate,ModifyTime,GrpName,License,LicenseType,IDValidate,Socialinsuno) VALUES( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?)), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[], values=[])

**Actual SQL: ds0** ::: INSERT INTO LDPerson(PersonID,CustomerNo,Name,Sex,Birthday,IDType,IDNo,Password,NativePlace,Nationality,RgtAddress,Marriage,MarriageDate,Health,Stature,Avoirdupois,Degree,CreditGrade,OthIDType,OthIDNo,ICNo,GrpNo,JoinCompanyDate,StartWorkDate,Position,Salary,OccupationType,OccupationCode,WorkType,PluralityType,DeathDate,SmokeFlag,BlacklistFlag,Proterty,Remark,State,VIPValue,Operator,MakeDate,MakeTime,ModifyDate,ModifyTime,GrpName,License,LicenseType,IDValidate,Socialinsuno) VALUES( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) ::: [101901, 0000050380, Jason, 0, 1999-01-01T00:00:00.000+0800, 0, 212365432, null, null, null, null, null, null, null, 0.0, 0.0, null, null, null, null, null, null, null, null, null, 0.0, null, null, null, null, null, null, null, null, null, 1, null, cbs, 2019-12-31T00:00:00.000+0800, 12:14:10, 2019-12-31T00:00:00.000+0800, 12:14:10, null, null, null, null, null]

**Actual SQL: ds1** ::: INSERT INTO LDPerson(PersonID,CustomerNo,Name,Sex,Birthday,IDType,IDNo,Password,NativePlace,Nationality,RgtAddress,Marriage,MarriageDate,Health,Stature,Avoirdupois,Degree,CreditGrade,OthIDType,OthIDNo,ICNo,GrpNo,JoinCompanyDate,StartWorkDate,Position,Salary,OccupationType,OccupationCode,WorkType,PluralityType,DeathDate,SmokeFlag,BlacklistFlag,Proterty,Remark,State,VIPValue,Operator,MakeDate,MakeTime,ModifyDate,ModifyTime,GrpName,License,LicenseType,IDValidate,Socialinsuno) VALUES( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) ::: [101901, 0000050380, Jason, 0, 1999-01-01T00:00:00.000+0800, 0, 212365432, null, null, null, null, null, null, null, 0.0, 0.0, null, null, null, null, null, null, null, null, null, 0.0, null, null, null, null, null, null, null, null, null, 1, null, cbs, 2019-12-31T00:00:00.000+0800, 12:14:10, 2019-12-31T00:00:00.000+0800, 12:14:10, null, null, null, null, null]

**Comment by terrymanu** [comment]
Any exception occur?

**Comment by terrymanu** [comment]
I guess in your SQL have some keyword of MySQL, such as `password`, `Position`.
Because of 4.0.0-RC1 is not stable, so can you try 4.0.0-RC3?

**Comment by beijixi** [comment]
**Thanks**
I add the reference symbol to all the columns，It has been running normally.
