### ISSUE TITLE
use st_distance_sphere（mysql function）caused a bug

### ISSUE THREAD

**Issue by lybbyl** [apache/incubator-shardingsphere#3847]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-core</artifactId>
			<version>4.0.0-RC2</version>
</dependency>

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

sharding-jdbc-core

### Expected behavior
Hope to support mysql distance function -->st_distance_sphere

### Actual behavior
Will report an Exception

### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/20021575/71662660-35888700-2d8d-11ea-905b-a5f40d7dbd21.png)
I think some bugs caused this value to be wrong.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

SELECT
	dd.id 
FROM
	detailed_demand dd 
ORDER BY
	st_distance_sphere ( point ( 113.358772, 23.1273723 ), point ( dd.longitude, dd.latitude ) ) ASC 
	LIMIT 0,
	20

**Comment by SteNicholas** [comment]
@lybbyl I will support `st_distance_sphere ` function. @terrymanu Please assign to me for function support.

**Comment by dongzl** [comment]
@SteNicholas , assign to you. ^_^

**Comment by lybbyl** [comment]
Thank you so much for your response.
