### ISSUE TITLE
Add datasources check before start scaling job

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#3849]
Before starting a scaling job, we should test the connections of the source‘s and target's datasource.

- [ ] Check source's datasource
    - [x] Check the connection availability of source's datasource
    - [x] Check user's privileges of the source's datasource (MySQL)
    - [ ] Check user's privileges of the source's datasource (PostgreSQL)
- [x] Check target's datasource
    - [x] Check the connection availability of target's datasource

**Comment by KomachiSion** [comment]
Good idea, can you list what should do in issue?

**Comment by ssxlulu** [comment]
> Good idea, can you list what should do in issue?

Yes. Before starting a scaling job, we should do these things:
1. check the connection and user's privileges of the source's datasource;
2. check the connection and user's privileges of the target's datasource.

If all checks are ok, then start the job, otherwise, we should through the exception and the job start failed.

**Comment by ssxlulu** [comment]
Now, we haven't have good method for PostgreSQL's privilege check.
We need replication privilege for PostgreSQL's real-time data migration,which is defined in the pg_hba.conf, so we can't read the file for privilege checking via connection.

Anyone who has a good idea for the PostgreSQL's privilege checking, please reply to this issue.Thanks~

**Comment by KomachiSion** [comment]
If there no way to check the replication privilege for PostgreSQL, can we check the query privilege for PostgreSQL first?

It also need to check.

**Comment by ssxlulu** [comment]
> If there no way to check the replication privilege for PostgreSQL, can we check the query privilege for PostgreSQL first?
> 
> It also need to check.

Yes, We can check the query privilege, I will submit a PR to finish it.
