### ISSUE TITLE
自增ID算法LEAF_SNOWFLAKE的`service.id`使用疑问

### ISSUE THREAD

**Issue by xiaolongyuan** [apache/incubator-shardingsphere#3858]
版本 4.0.0.RC3

service.id | String | leaf_snowflake位于注册中心上的服务标识
-- | -- | --

如何设置 每个实例都不一样？

现在把这个设置成一样  并发下会出现重复ID问题

如果推荐做法是设置成一样 那么是否 如下 代码 判断存在BUG?

```
    private Long initializeWorkIdNodeIfNeed(final RegistryCenter leafRegistryCenter) {
        String workIdDirectory = getWorkIdDirectoryWithServiceId();
        if (leafRegistryCenter.isExisted(workIdDirectory)) {
            String workIdInString = leafRegistryCenter.getDirectly(workIdDirectory);
            return Long.parseLong(workIdInString);
        } else {
            Long result = updateCurrentMaxWorkIdInRegisterCenter();
            leafRegistryCenter.persist(workIdDirectory, String.valueOf(result));
            return result;
        }
    }
```

**Comment by xiaolongyuan** [comment]
![image](https://user-images.githubusercontent.com/3142363/71709180-ab91fa00-2e30-11ea-9102-20d413a1d077.png)


![image](https://user-images.githubusercontent.com/3142363/71709203-c3697e00-2e30-11ea-827a-35c5655349ea.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by xiaolongyuan** [comment]
有同样问题的小伙伴们 建议使用 美团的开源算法自定义实现

**Comment by xiaolongyuan** [comment]
地址 https://github.com/Meituan-Dianping/Leaf
