### ISSUE TITLE
Modify UI module for new orchestration.

### ISSUE THREAD

**Issue by sunbufu** [apache/incubator-shardingsphere#3873]
We are working on the last step of [issue 3185](https://github.com/apache/incubator-shardingsphere/issues/3185) for new orchestration. And now we should modify UI module to fit the new orchestration module.

- [ ] Add an orchestration type (config center and registry center) in 'Add a registry' view.
- [ ] Add an orchestration type in `sharding-ui-backend`'s api and `sharding-ui-configs.yaml` file.
- [ ] Add a button to make center instance active.
- [ ] Add an api to make center instance active.
- [ ] Rename `Rule Config`, `Runtime Status` in menu bar.

**Comment by kimmking** [comment]
I will follow this issue, complete its tasks with Menghaoranss after orchestration-refactoring.

**Comment by terrymanu** [comment]
@kimmking Sure, assigned

**Comment by menghaoranss** [comment]
please assign this issue to me.

**Comment by menghaoranss** [comment]
The current menu has been adjusted to :
```
/
├─Config Center
     ├─Config Server
     ├─Rule Config
├─Registry Center
     ├─Config Server
     ├─Runtime Status  
└─Data scaling 
```
And keep the name of `Rule Config` and `Runtime Status`，we can discuss whether these names are appropriate later.
