### ISSUE TITLE
Could XA Transaction guarantee consistent when server instance crashed and migrated?

### ISSUE THREAD

**Issue by wenweihu86** [apache/incubator-shardingsphere#3877]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by cherrylzhao** [comment]
If you config the location of XA log file to a cloud filesystem, it can be guaranteed.

**Comment by wenweihu86** [comment]
@cherrylzhao Could XA Transaction support save log to server, since business application doesn't writing log to the cloud file system most often?

**Comment by cherrylzhao** [comment]
`atomikos` & `bitronix `only support save the log to local machine by default. `Narayana` support save the log to database, but we have not verify it yet [example-143](https://github.com/apache/incubator-shardingsphere-example/issues/143) . `Seata` will plan to support XA in future. so our goal is to provide a variety options to integrate with ShardingSphere. you can extend the storage of underlying transaction manager to guarantee HA, it usually need to introduce another HA service to scale out the log and failover from crashed

**Comment by cherrylzhao** [comment]
just close it for no response more than 7 days
