### ISSUE TITLE
Refactor of datasourceFactory of shardingscaling

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#3878]
Now each synctask manager its own datasources, we should refactor the datasourceFactory to let each job to manage its all tasks's datasources.

**Comment by terrymanu** [comment]
DatasourceFactory is a public API, We need more discuss before refactor.

**Comment by ssxlulu** [comment]
> DatasourceFactory is a public API, We need more discuss before refactor.

Yes, of cource. More discuss will be needed before the refactor.

**Comment by KomachiSion** [comment]
I think `datasourceFactory` in shardingscaling now can be separated to two part.
The first part still call `datasourceFactory`, and just create datasource from configurations.
The other part refactor to `manager`, which stores and managers all datasources. Jobs or tasks should get their datasources from `manager`.

**Comment by kimmking** [comment]
Splitting Configure and Reference with a datasource sounds like a good idea.
