### ISSUE TITLE
4.0.0-rc3 version load table metadata error 

### ISSUE THREAD

**Issue by ma1562013338** [apache/incubator-shardingsphere#3880]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-rc3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Reason analyze (If you can)
resultSet.getBoolean("IS_AUTOINCREMENT")   returns a value as a string, converted to a Boolean value that was incorrectly timed

### Example codes for reproduce this issue (such as a github link).
![图片](https://user-images.githubusercontent.com/25915870/71815065-35ec8f00-30b9-11ea-9e79-6b3f35d55d64.png)

**Comment by dongzl** [comment]
Hi @ma1562013338 , reference this issue #3582 .
