### ISSUE TITLE
Is there any way optimizing "limit" in the following situation？  

### ISSUE THREAD

**Issue by alexkuku** [apache/incubator-shardingsphere#3881]
## Is there any way optimizing "limit" in the following situation？  
I have a table like this：
sign_time|other_fileds
---|---

I want to sharding this table by range strategy using sign_time field.There is a characteristic for the sharded tables is that the sign_time filed will absolutely bigger in the latter tables than before.  
##
Suppose there are two physical tables of the record table:  
***record_0: 2019's data***
sign_time|other_fileds
---|---
2019/01/01 12:23:21|
2019/04/01 11:23:21|
......|
2019/12/31 22:23:21|

***record_1: 2020's data***
sign_time|other_fileds
---|---
2020/01/01 12:23:21|
2020/04/01 11:23:21|
......|
2020/12/31 22:23:21|
```
SELECT sign_time, other_fileds FROM record WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 100000,10;
```

If I want to run the sql above.This sql will be runing like:  
```
1.SELECT sign_time, other_fileds FROM record_1 WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 0,100010;  
2.SELECT sign_time, other_fileds FROM record_2 WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 0,100010;   
3.Merge and get the result in (100000, 100010] 
```

But there is a better way:
```
1.SELECT count(*) FROM record WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 100000,10;  
2.
if the count_result >= 10  
    return SELECT sign_time, other_fileds FROM record WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 100000,10;
else
    return 
    SELECT sign_time, other_fileds FROM record WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 100000,count_result  
    +
    SELECT sign_time, other_fileds FROM record WHERE sign_time BETWEEN 2019/12/15 00:00:00 AND 2020/01/02 00:00:00 LIMIT 0,10-count_result;
 ```
 
Is there any way can I achieve the effect of the latter situation?

**Comment by terrymanu** [comment]
This is a good idea, but it only can use without order by, is it?

**Comment by alexkuku** [comment]
Thanks for your attention!
In this situation, I think we can use order by on the sign_time field, because the sign_time filed is the sharding field and  not absolutely ordered by time asc. But other fields, as you said, can not use order by.
This limit strategy are mainly used in log data,like record,attendance and so on,which can be easily range sharded by time dimension. Have I made myself clear?

**Comment by terrymanu** [comment]
the `order by` in SQL is up to user, how about is the `order by item` is not sharding key?

**Comment by alexkuku** [comment]
OK.Thank you!This is indeed a special situation.
It seems that I can only get that effect by optimizing my business code.

**Comment by terrymanu** [comment]
Maybe you can try to summary your idea and extract them as regular rules to implement the limit merge.

**Comment by kimmking** [comment]
@alexkuku  If this optimizing is efficient for your own system case, you can implement it in your project. 
Have fun and keep moving.
Look forward to your next idea about ShardingSphere.
