### ISSUE TITLE
ResultSet method not supported

### ISSUE THREAD

**Issue by qiqsa** [apache/incubator-shardingsphere#3896]
## Feature Request

Druid 1.1.20 have support  this two method:
    public final <T> T getObject(final int columnIndex, final Class<T> type) 
    public final <T> T getObject(final String columnLabel, final Class<T> type) 

but sharing not support this method ....

**Comment by terrymanu** [comment]
What is your version and which class do you indicate?

**Comment by kimmking** [comment]
@qiqsa 
Do you means two methods in java.sql.ResultSet:
```
public <T> T getObject(int columnIndex, Class<T> type) throws SQLException;
public <T> T getObject(String columnLabel, Class<T> type) throws SQLException;
```

**Comment by kimmking** [comment]
And you can see: 
https://github.com/kimmking/incubator-shardingsphere/tree/issue3896

https://github.com/kimmking/incubator-shardingsphere/commit/853ac638b99c60b577c4abaed1a4ee420a591e96

**Comment by qiqsa** [comment]
thank you  . but this class AbstractUnsupportedOperationResultSet  still exist this two method ,please see again

**Comment by kimmking** [comment]
I find h2database driver doesnt support this feature.

**Comment by qiqsa** [comment]
ok .thank you
