### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by sjssj** [apache/incubator-shardingsphere#3897]
Hi，i found a error on the document @https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/#数据分片-数据脱敏
When using sharding and encrypt function at the same time, the configuration should be
**spring.shardingsphere.sharding.encrypt-rule**.xxx
instead of
**spring.shardingsphere.encrypt**.xxx

**Comment by geomonlin** [comment]
yeah,you are right. The master branch has been updated, but has not been deployed to the official website. you can see [pr](https://github.com/apache/incubator-shardingsphere-doc/pull/416)

**Comment by geomonlin** [comment]
already update.
