### ISSUE TITLE
sql bug

### ISSUE THREAD

**Issue by zhouzhendao123456** [apache/incubator-shardingsphere#3900]
Sharding-Proxy rc4

SELECT aa.`journal_template_type` FROM `app1_journal_info` aa GROUP BY `journal_template_type`
SELECT aa.`journal_template_type` FROM `app1_journal_info` aa GROUP BY aa.journal_template_type
SELECT `journal_template_type` FROM `app1_journal_info` GROUP BY `journal_template_type`
it's ok

SELECT aa.`journal_template_type` FROM `app1_journal_info` aa GROUP BY aa.`journal_template_type`
[Err] 1054 - Unknown column 'aa.journal_template_type' in 'order clause'

**Comment by zhouzhendao123456** [comment]
Unable to submit issues properly

**Comment by terrymanu** [comment]
Hi, what is the reason to close this issue, did you solve the issue?
