### ISSUE TITLE
sql bug:about "`" 

### ISSUE THREAD

**Issue by zhouzhendao123456** [apache/incubator-shardingsphere#3901]
Sharding-Proxy rc4
![image](https://user-images.githubusercontent.com/56668316/71968128-49296700-323f-11ea-82b8-6a94d8e614ab.png)
[Err] 1054 - Unknown column 'aa.journal_template_type' in 'order clause'

![image](https://user-images.githubusercontent.com/56668316/71968192-6100eb00-323f-11ea-96ca-971dcdbcf9b4.png)
it's ok

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Closed by no response anymore
