### ISSUE TITLE
Adapt  db2

### ISSUE THREAD

**Issue by Fwenjie** [apache/incubator-shardingsphere#3908]
hi，i am a user with Shardingsphere，i just want to suggest that do you have thoughts to adapt db2.

**Comment by taojintianxia** [comment]
Hi Fwenjie 

I suggest you use the mailing-list to invoke more people to discuss your thoughts

take a look at [Subscribe Guide](https://shardingsphere.apache.org/community/en/contribute/subscribe/)

**Comment by terrymanu** [comment]
We have no plan to do this.
I can label the requirement as volunteer wanted for several days.
If someone interesting about it, please reply here.

**Comment by terrymanu** [comment]
Closed because no volunteer wanted for this feature now.
