### ISSUE TITLE
SQL should not be cached if it does not contain a  question mark

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#3916]
For now, SQLs will be cached when use a PreparedStatement regardless of the question mark. This may lead to all SQLs of a service be cached and performance declined.

**Comment by limingwei** [comment]
What dose the rules should be
rule A: SQL include a question mark ? cache it : no cache
rule B: Use jdbc.PreparedStatement -> cache it; Use jdbc.Statement -> no cache

**Comment by tuohai666** [comment]
I think the rule should be: Use PreparedStatement and contains question mark.
An SQL without question mark will never be hit in most scenarios.

**Comment by terrymanu** [comment]
We should not consider about whatever SQL contains parameter marker or not.
For PreparedStatement, we should cache the SQL parse result; for Statement, do not cache.

**Comment by limingwei** [comment]
However, this could be an extension point of our shardingsphere plugin system

**Comment by limingwei** [comment]
`
MyFactory extends DefaultShardingSpherePreparedStatementFactory {
	boolean cacheThePreparedStatement ( it ) {
		if ( not contains parameter marker ) {
			return false;
		}

		return super.cachePreparedStatement( it );
	}
}
`
