### ISSUE TITLE
config datasource dynamic by program or outside order？

### ISSUE THREAD

**Issue by 852675742** [apache/incubator-shardingsphere#3919]
## Question

**For English only**, other languages will not accept.

I have the question,now because our datasource config is dead write in config yaml file,can program dynamic config the datasource by listener outside order？

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
You can try to use java API.

FIY: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-java/
