### ISSUE TITLE
sharding-jdbc4 scan some tables in all_tab_columns.but the current user does not have permission.then throws the Exception:Table or view does not exist

### ISSUE THREAD

**Issue by yuxuejimo** [apache/incubator-shardingsphere#3930]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by kimmking** [comment]
can you try it directly by oracle-jdbc driver?

**Comment by yuxuejimo** [comment]
We've been using ojdbc6.jar (in jboss7). There was no error when using the sharding3 version, but there was an error when using the sharding4 version

**Comment by yuxuejimo** [comment]
The reason for this problem is that the T4CConnection in ojdbc7.jar does not implement the getSchema() method, so it scans the tables of other owners. Please show the version of ojdbc.jar used for testing. Thank you

**Comment by yexufeijun** [comment]
I have the same problem. I use ojdbc6.jar

**Comment by kimmking** [comment]
@yuxuejimo @yexufeijun 
Is this error block your usage?

**Comment by yuxuejimo** [comment]
yes. So we had to change the source code to make our application work. In addition to this exception, there is another exception. When there are too many business tables, analyzing the metadata of the business table can cause an application to get stuck. We also modified the source here the logic

**Comment by terrymanu** [comment]
Can you provide the sharding rule configuration and full stake trace?

**Comment by terrymanu** [comment]
Closed because no response anymore.
