### ISSUE TITLE
Proxy can't parse SQL "SHOW FULL TABLES FROM `test` LIKE '%'"

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#3946]
## Bug Report
When I start a proxy server in 4.0.0-RC3, and use DataGrip(A popular database&SQL IDE from JetBrains) to connect proxy via JDBC(modify options to use jdbc metadata) and database named `test`, then DataGrip will execute the SQL "SHOW FULL TABLES FROM `test` LIKE '%'" to find all tables in test database, but proxy return nothing.

Run "SHOW FULL TABLES FROM `test` LIKE '%'" in mysql cli directly connecting to mysql-server without proxy will return all tables info.

### Which version of ShardingSphere did you use?
4.0.0-RC3 and master

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
Sharding proxy server return tables info. And DataGrip show all tables in table views.

### Actual behavior
Sharding proxy server return nothing. DataGrip tables view has no results.

### Reason analyze (If you can)
Proxy Can't parse SQL "SHOW FULL TABLES FROM `test` LIKE '%'"

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

As above. "SHOW FULL TABLES FROM `test` LIKE '%'" doesn't work.
But I try in mysql cli via proxy:
- "SHOW FULL TABLES FROM `test`",  works well.
- "SHOW FULL TABLES", works well.

### Example codes for reproduce this issue (such as a github link).

Null.

**Comment by SteNicholas** [comment]
I have already tried the parser to parse SQL `SHOW FULL TABLES FROM sharding_db LIKE '%'`. The result of `MySQLParser` is success. I thought that the bug is in proxy.

**Comment by kimmking** [comment]
5.0.0 snapshot is ok now.

```
$ mysql -uroot -P3307 test
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.6.4-Sharding-Proxy 5.0.0-RC1 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
mysql> SHOW FULL TABLES FROM test LIKE '%';
+--------------------+------------+
| Tables_in_test (%) | Table_type |
+--------------------+------------+
| test               | BASE TABLE |
| zz                 | BASE TABLE |
+--------------------+------------+
2 rows in set (0.03 sec)
```
