### ISSUE TITLE
How to config the customize rule in sharding-proxy

### ISSUE THREAD

**Issue by longzhihun** [apache/incubator-shardingsphere#3948]
1. I have customized the sharding rule with java code.

> public class DbShardingAlgorithm implements PreciseShardingAlgorithm {

    private static Logger logger = LoggerFactory.getLogger(DbShardingAlgorithm.class);

    Map<String, String> dealerDSMap = ImmutableMap.of("d16df3743a", "ds0",
            "bc0ce9b058", "ds1",
            "85abb5f5d2", "ds2",
            "b563165232", "ds3",
            "f0f198b56d", "ds4");

    @Override
    public String doSharding(Collection collection, PreciseShardingValue preciseShardingValue) {

        if ("dealer_id".equals(preciseShardingValue.getColumnName())) {
            String dealerId = (String) preciseShardingValue.getValue();
            return dealerDSMap.get(dealerId);
        }
        return "ds0";
    }
}

when i set the class file to the proxy home dir. got a error message:

> java.lang.ClassNotFoundException: io.shardingsphere.api.algorithm.sharding.standard.PreciseShardingAlgorithm

I dont know how to handle it. please help me.

**Comment by longzhihun** [comment]
![image](https://user-images.githubusercontent.com/17509151/72231687-d3831980-35f7-11ea-8ab1-b96bb9a632a9.png)  add class path.

**Comment by dongzl** [comment]
@longzhihun what's your porxy version? package a jar file to lib directory, try it.

**Comment by longzhihun** [comment]
@dongzl the latest version! OK, I will try it, then feedback to you

**Comment by dongzl** [comment]
the latest version？which？4.0.0-RC3？

the latest version‘s package is `org.apache.shardingsphere.xxx.xxx`, but your exception is `io.shardingsphere`, this is a very old version.

Please make sure your version firstly.

**Comment by longzhihun** [comment]
@dongzl Yes, 4.0.0-RC3, but we can only find the "sharding-core:3.1.0" on maven central.  so which version sharding core should we depend on in my pom.xml,  we are trying to customize sharding with java code, please help me.

**Comment by dongzl** [comment]
<groupId>org.apache.shardingsphere</groupId>
<artifactId>sharding-jdbc-core</artifactId>
<version>4.0.0-RC3</version>

Does it work well?

**Comment by longzhihun** [comment]
will try it ASAP. @dongzl

**Comment by longzhihun** [comment]
@dongzl it works now, from my side, i think we'd better to add the information to our guildline, i have search many sites, got no useful message.
