### ISSUE TITLE
sharding with encrypt can not work well.

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#3949]
Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC4-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
sharding with encrypt can work well
### Actual behavior
only sharding , encrypt can not work well

**Comment by xiyelife** [comment]
Please assign it to me

**Comment by terrymanu** [comment]
@xiyelife Thank you, assigned
