### ISSUE TITLE
How to config sharding rule for dynamic capacity?

### ISSUE THREAD

**Issue by longzhihun** [apache/incubator-shardingsphere#3960]
In my scenario, the amount of my data is growing every day, we need to reshard the data by half a year, which algorithm we'd better use,  please give some opinions, thanks.

**Comment by ssxlulu** [comment]
In my opinion, reshard the data is a big work, and I think you should plan your data capacity in advance, like reserve storage for some years in advance.
What's more, sharding-scaling module will help you dynamic scaling you data in the future. Sharding-scaling will be release in 5.x.

**Comment by terrymanu** [comment]
Please waiting for Sharding-scaling release
