### ISSUE TITLE
Why does the encrypted table only judge the first one, maybe left join encrypt table, and then judge that there is no encrypted table

### ISSUE THREAD

**Issue by longjy** [apache/incubator-shardingsphere#3971]
org.apache.shardingsphere.encrypt.rewrite.token.generator.impl.EncryptProjectionTokenGenerator#generateSQLTokens

@Override
    public Collection<SubstitutableColumnNameToken> generateSQLTokens(final SQLStatementContext sqlStatementContext) {
        Collection<SubstitutableColumnNameToken> result = new LinkedList<>();
        Optional<SelectItemsSegment> selectItemsSegment = sqlStatementContext.getSqlStatement().findSQLSegment(SelectItemsSegment.class);
        Preconditions.checkState(selectItemsSegment.isPresent());
        String tableName = sqlStatementContext.getTablesContext().getSingleTableName();
        Optional<EncryptTable> encryptTable = getEncryptRule().findEncryptTable(tableName);
        if (!encryptTable.isPresent()) {
            return Collections.emptyList();
        }
        for (SelectItemSegment each : selectItemsSegment.get().getSelectItems()) {
            if (isEncryptLogicColumn(each, encryptTable.get())) {
                result.add(generateSQLToken((ColumnSelectItemSegment) each, tableName));
            }
        }
        return result;
    }

**Comment by longjy** [comment]
sqlStatementContext.getTablesContext().getSingleTableName()  maybe return non-encrypted table

**Comment by terrymanu** [comment]
Can you provide your SQL and encrypt rule configuration?

**Comment by terrymanu** [comment]
Closed because no response
