### ISSUE TITLE
How to handle JNDI datasource in spring namespace?

### ISSUE THREAD

**Issue by ette9844** [apache/incubator-shardingsphere#3987]
I understood that sharding-sphere supports JNDI datasource in spring-boot-starter.
But the project I'm working on is based on spring framework. So I should handle JNDI datasource in spring namespace.

How to handle JNDI datasource at spring namespace? I couldn't find about it on your documentation page.
If there's no features about it, I would like to know that there's any plan to make feature of it or not.

**Comment by terrymanu** [comment]
Can you write the reason to close issue?
