### ISSUE TITLE
4.0.0-RC1 join bug

### ISSUE THREAD

**Issue by huweidada** [apache/incubator-shardingsphere#3998]
SELECT 
	  COUNT(*) 
	FROM
	  sku_25 
	  INNER JOIN sku_code_25 
	  INNER JOIN sku_model_25 
	  INNER JOIN model_25 
	  INNER JOIN category_25 
	    ON sku_25.id = sku_code_25.sku_id 
	    AND sku_25.id = sku_model_25.sku_id 
	    AND sku_model_25.model_id = model_25.id 
	    AND model_25.category_id = category_25.id 
     
       
    
     WHERE (  sku_25.owner_org_id = ?
                
            
              
                  and sku_code_25.owner_org_id = ?
                
            
              
                  and sku_model_25.owner_org_id = ?
                
            
              
                  and model_25.owner_org_id = ?
                
            
              
                  and category_25.owner_org_id = ?
                
            
              
                  and sku.name like ? )
        
      
        
          or(  sku_25.owner_org_id = ?
                
            
              
                  and sku_code_25.owner_org_id = ?
                
            
              
                  and sku_model_25.owner_org_id = ?
                
            
              
                  and model_25.owner_org_id = ?
                
            
              
                  and category_25.owner_org_id = ?
                
            
              
                  and sku_code.tenant_uuid_code like ? )

sku.name rewrite fail

**Comment by huweidada** [comment]
SELECT 
	  COUNT(*) 
	FROM
	  sku 
	  INNER JOIN sku_code 
	  INNER JOIN sku_model 
	  INNER JOIN model 
	  INNER JOIN category 
	    ON sku.id = sku_code.sku_id 
	    AND sku.id = sku_model.sku_id 
	    AND sku_model.model_id = model.id 
	    AND model.category_id = category.id 
     
       
    
     WHERE (  sku.owner_org_id = ?
                
            
              
                  and sku_code.owner_org_id = ?
                
            
              
                  and sku_model.owner_org_id = ?
                
            
              
                  and model.owner_org_id = ?
                
            
              
                  and category.owner_org_id = ?
                
            
              
                  and sku.name like ? )
        
      
        
          or(  sku.owner_org_id = ?
                
            
              
                  and sku_code.owner_org_id = ?
                
            
              
                  and sku_model.owner_org_id = ?
                
            
              
                  and model.owner_org_id = ?
                
            
              
                  and category.owner_org_id = ?
                
            
              
                  and sku_code.tenant_uuid_code like ? )

**Comment by SteNicholas** [comment]
@huweidada Please use the latest version to confirm this bug.

**Comment by huweidada** [comment]
switch 4.0.0 version，the bug disappear.
thanks!
@SteNicholas

**Comment by SteNicholas** [comment]
@huweidada welcome to make any use issue.
