### ISSUE TITLE
sharding use mysql8

### ISSUE THREAD

**Issue by zhouzhendao123456** [apache/incubator-shardingsphere#4003]
sharding use mysql-connector-java version is too old,i hope use mysql 8.0.,mysql-connector-java need version 8
can i do it?

**Comment by SteNicholas** [comment]
Yes, please use 4.0.0 release version and then use version 8 of mysql-connector-java to connect MySQL8.0.

**Comment by cherrylzhao** [comment]
enhance it #5218
