### ISSUE TITLE
The insert statement reported an error

### ISSUE THREAD

**Issue by ma1562013338** [apache/incubator-shardingsphere#4008]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
![图片](https://user-images.githubusercontent.com/25915870/72594015-6cd86580-3941-11ea-8ee1-86b0f727d452.png)

### Actual behavior
The data was inserted successfully, but an exception was thrown

### Reason analyze (If you can)
﻿﻿﻿
![图片](https://user-images.githubusercontent.com/25915870/72594167-c771c180-3941-11ea-909d-5277bc47d8ad.png)

**Comment by terrymanu** [comment]
Hi, can you try to version 4.0.0?

**Comment by terrymanu** [comment]
Closed for no response anymore.
