### ISSUE TITLE
If not hint values are set what's the routing behavior for HintShardingAlgorithm

### ISSUE THREAD

**Issue by lightyear007** [apache/incubator-shardingsphere#4028]
According to sharding jdbc doc [https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/hint/], if we want to use the forced routing, we have to implement a HintShardingAlgorithm. My question is that if we have configured a sharding rule using HintShardingAlgorithm, but we didn't set any hint values using the HintManager, then how sharding jdbc can get a clue of how to route the query?

I tried this and found out, if no values are set, my HintShardingAlgorithm implementation code will not be executed. then i would what rule sharding jdbc is using in this case.

Thanks
Jacky

**Comment by KomachiSion** [comment]
Hi @lightyear007, There are two possible behavior for none-values hint strategy.

1. If the tables in your SQL is not a sharding table( which means you do not configure it in shardingRule), the SQL will be routed to your defaultDatasource. What's more, the defaultDatasource also miss, the SQL will be routed to one random datasource.
2. If the tables in your SQL is a sharding table, the SQL will be full-routed to all dataNodes you configured.

**Comment by KomachiSion** [comment]
@lightyear007 any response? If no response, we will close issue.
