### ISSUE TITLE
Duplicate entry '425919356283650049' for key 'PRIMARY'

### ISSUE THREAD

**Issue by wsad137** [apache/incubator-shardingsphere#4031]
![image](https://user-images.githubusercontent.com/3139878/72690554-66700680-3b58-11ea-8413-a641f107197e.png)
Error in decentralized deployment

**Comment by wsad137** [comment]
Is it caused by asynchronous concurrency?

**Comment by wsad137** [comment]
Can setting "Maximum Vibration Offset" or "Maximum Allowable Time Difference in Milliseconds" solve it?
Has anyone encountered this?

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Closed for no response anymore.
