### ISSUE TITLE
ResultSet miss the plain column because of using contains to get the logicColumn when using data mask（sharding+encrypt）

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#4044]
### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
return the all of table's columns.
### Actual behavior
resultSet miss the logic column because of using contains to get the logicColumn
### Reason analyze (If you can)
sharding+encrypt， the same issue with https://github.com/apache/incubator-shardingsphere/issues/3750.  

It should fix the class ShardingResultSetMetaData.java like EncryptResultSetMetaData.

**Comment by xiyelife** [comment]
Please assign it to me , tks.

**Comment by terrymanu** [comment]
@xiyelife  Thank you, assigned
