### ISSUE TITLE
ParameterMarkerExpressionSegment looks like a memory leak

### ISSUE THREAD

**Issue by liutaohua** [apache/incubator-shardingsphere#4179]
hi，
i'm use ` sharding-jdbc-core:4.0.0-RC3` to shard data in 10-tables .

table :
```
CREATE TABLE `t_message_0` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `message` varchar(255) DEFAULT NULL,
  `message_id` varchar(50) DEFAULT NULL,
  `params` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

and insert sql :
```
insert into t_message_{0...9} (message, message_id, params) values ( ?,?,? ),( ?,?,? ),( ?,?,? ),( ?,?,? )
```

The write speed of the database is about 25,000/s ,  and the test lasts about an hour.

I found the `simple.ParameterMarkerExpressionSegment` and  `dml.assignment.InsertValuesSegment`
The total number of classes is increasing, and `GC` does not reduce the number of instances.

So I guess it might be a memory leak. Did anyone else have the same problem as me? Or am I missing something?

**Comment by baimeng1758354676** [comment]
i have the same question

**Comment by baimeng1758354676** [comment]
> hi，
> i'm use ` sharding-jdbc-core:4.0.0-RC3` to shard data in 10-tables .
> 
> table :
> 
> ```
> CREATE TABLE `t_message_0` (
>   `id` bigint(20) NOT NULL AUTO_INCREMENT,
>   `message` varchar(255) DEFAULT NULL,
>   `message_id` varchar(50) DEFAULT NULL,
>   `params` varchar(255) DEFAULT NULL,
>   PRIMARY KEY (`id`),
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8
> ```
> 
> and insert sql :
> 
> ```
> insert into t_message_{0...9} (message, message_id, params) values ( ?,?,? ),( ?,?,? ),( ?,?,? ),( ?,?,? )
> ```
> 
> The write speed of the database is about 25,000/s , and the test lasts about an hour.
> 
> I found the `simple.ParameterMarkerExpressionSegment` and `dml.assignment.InsertValuesSegment`
> The total number of classes is increasing, and `GC` does not reduce the number of instances.
> 
> So I guess it might be a memory leak. Did anyone else have the same problem as me? Or am I missing something?

i got  the same questions,so  this will cause memory leak?
