### ISSUE TITLE
Inline strategy cannot support range sharding

### ISSUE THREAD

**Issue by succeo** [apache/incubator-shardingsphere#4180]
sharding-jdbc version  4.0.0

sql  select * from t_account where f_type = 1 and  f_id >= 10000 and f_code in ("500","604","685") group by f_code;

An exception occurred during the query.

**Comment by succeo** [comment]
Please help me solve this problem, thank you

**Comment by KomachiSion** [comment]
What's your sharding configuration?

BTW, Inline strategy only support `=` and in condition for sharding column.  If you want to use range sharding, you should use standard strategy.

More detail see documents

**Comment by succeo** [comment]
config:
shardingColumn: f_id 

If you have a query for the range of columns in a separate table, how will it be configured, such as f_id>= XXX

**Comment by KomachiSion** [comment]
You should code a `RangeShardingAlgorithm` and configure it as your range algorithm.

example like : https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example

use `sharding-databases-range.yaml`

**Comment by terrymanu** [comment]
No, Inline strategy cannot support range sharding. 
More details please reference document and example

**Comment by kimmking** [comment]
@succeo you can use latest version and turn on this feature like this in server.yaml:
```
allow.range.query.with.inline.sharding: true
```

**Comment by lishuo5263** [comment]
> @succeo you can use latest version and turn on this feature like this in server.yaml:
> 
> ```
> allow.range.query.with.inline.sharding: true
> ```

hi, KimmKing, I got same question, I fllow your way to try execute this sql (SELECT * FROM t_order WHERE order_id BETWEEN ? AND ?)
