### ISSUE TITLE
old DCL set default role test unit dose not pass

### ISSUE THREAD

**Issue by beijing-penguin** [apache/incubator-shardingsphere#4196]
i add set-default-role.xml case to incubator-shardingsphere\shardingsphere-sql-parser\shardingsphere-sql-parser-test\src\test\resources\sql,but run SQLParserParameterizedTest.java test unit error
```
java.lang.AssertionError: The count of SQL cases and SQL parser cases are mismatched, missing cases are: [set_default_role_to_user, set_default_all_role, set_default_none_role, set_default_roles_to_users]
 ```
the set-default-role.xml content is 
```xml
<sql-parser-test-cases>
    <set-default-role sql-case-id="set_default_none_role" />
    <set-default-role sql-case-id="set_default_all_role" />
    <set-default-role sql-case-id="set_default_role_to_user" />
    <set-default-role sql-case-id="set_default_roles_to_users" />
</sql-parser-test-cases>
```

**Comment by terrymanu** [comment]
This is not bug, it is a normal assert.
The failure reason just like the error message said:

```
The count of SQL cases and SQL parser cases are mismatched, missing cases are: [set_default_role_to_user, set_default_all_role, set_default_none_role, set_default_roles_to_users]
```

Please add parse test cases to sql parse test engine.

The test cases are composited by 2 parts: SQL cases and SQL parser cases.

Please make sure your SQL parser cases include the cases `set_default_role_to_user, set_default_all_role, set_default_none_role, set_default_roles_to_users`.

They should both include in new and old parser test engine.

More information about test engine please FIY: https://shardingsphere.apache.org/document/current/en/features/test-engine/
