### ISSUE TITLE
Code Optimization - Add filter classes Constructor to restrict the illegal class to be loaded when unmarshalling yaml as Map

### ISSUE THREAD

**Issue by beckhampu** [apache/incubator-shardingsphere#4199]
Now we use org.yaml.snakeyaml.Yaml.load() method to parse yaml as a Map. It is not good, can be loaded some illegal class. So i want to optimize it.
- [x] Add filter classes Constructor to restrict the illegal class to be loaded.

**Comment by kimmking** [comment]
for security issues？
