### ISSUE TITLE
mysqldump  file import sharding-proxy  insert speed slowly 

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#4231]
Sharding-proxy version: `4.0.0-RC3`

- Problems encountered：`It took 24 hours to import 10 million records into sharding-proxy.`

- Sharding-proxy Config: `start.sh -Xmx8g -Xms8g -Xmn4g,server.yaml use default parm`

**Comment by terrymanu** [comment]
Do you use PreparedStatement and ParameterMarker?

**Comment by lklkxcxc** [comment]
@terrymanu : I didn't used PreparedStatement and ParameterMarker. What are PreparedStatement and ParameterMarker?

**Comment by lklkxcxc** [comment]
@terrymanu Do you know why insert is so slow?

**Comment by terrymanu** [comment]
Because if you don't use PreparedStatement, it will parse SQL for every call which are very slow.
ShardingSphere will cache parse result if using PreparedStatement.

**Comment by lklkxcxc** [comment]
@terrymanu There is not much change ,I have used param:`serverTimezone=UTC&useSSL=false&characterEncoding=utf8&useServerPrepStmts=true&cachePrepStmts=true`

**Comment by kimmking** [comment]
Terry means you can use ‘insert into pku_influencing_factor VALUES (?,?,?,?)’ with PreparedStatement and put the parameters for every record. @lklkxcxc

**Comment by lklkxcxc** [comment]
@kimmking Can you give me a specific example? thank you！

**Comment by kimmking** [comment]
You can google or baidu PreparedStatement

**Comment by nevereverever** [comment]
> You can google or baidu PreparedStatement to find its usage.

@kimmking PreparedStatement can be use in sql scripts?
