### ISSUE TITLE
java.util.LinkedHashMap cannot be cast to org.apache.shardingsphere.orchestration.yaml.config.YamlDataSourceConfiguration

### ISSUE THREAD

**Issue by joinhappy81** [apache/incubator-shardingsphere#4240]
![image](https://user-images.githubusercontent.com/8109271/74227414-60092080-4cf9-11ea-8f97-2e1cce1f7e7f.png)

![image](https://user-images.githubusercontent.com/8109271/74227505-8f1f9200-4cf9-11ea-8ad4-9382c21490a8.png)

帮忙看看是什么问题，类型转换异常

**Comment by kimmking** [comment]
Can you show these messages with text format, thx.
I can't fetch the github images today, perhaps it's a network issue.

**Comment by joinhappy81** [comment]
> Your version is 4.0.1?
> And can you submit your config file here ?

![image](https://user-images.githubusercontent.com/8109271/74292917-3c36f080-4d74-11ea-8f15-9c8bf377da58.png)

![image](https://user-images.githubusercontent.com/8109271/74293099-c0897380-4d74-11ea-81cd-eb341b8c98e1.png)

version is 4.0.0

配置应该没有问题把，我看数据都已经显示了

**Comment by joinhappy81** [comment]
> Your version is 4.0.1?
> And can you submit your config file here ?

4.0.1 没有发布

**Comment by kimmking** [comment]
I need your config file to reproduce this bug.
Submit your config file to be useful for me to resolve it.
Thx.

**Comment by kimmking** [comment]
@joinhappy81 you can use: 
```
m1: !!org.apache.shardingsphere.orchestration.yaml.config.YamlDataSourceConfiguration
```
```
m2: !!org.apache.shardingsphere.orchestration.yaml.config.YamlDataSourceConfiguration
```

to explicitly specify YamlDataSourceConfiguration type.

We will add a default converter in next release version.

**Comment by kimmking** [comment]
And I find one thing:
If we start proxy with a yaml configuring datasources, proxy server will transform datasources with YamlDatasourceConfiguration object and marshal it to string with type, then send to zk.
Proxy server then use the config parameters from zk, so YamlDatasourceConfiguration type always here in datasource config string.

If you modify datasource config via zk-cli or ShardingSphere-UI, the type info must be preserved.
