### ISSUE TITLE
Move docs’s legacy html to https://github.com/apache/incubator-shardingsphere-doc repo

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4243]
We have already moved docs from https://github.com/apache/incubator-shardingsphere-doc to this repo.
But some legacy html files which generated by Hugo for previous version are not source code, the docs folder should only contains source code (the md files).
So we need to move all html files to `asf-site` branch of https://github.com/apache/incubator-shardingsphere-doc.
The remain tasks are:

- [x] Remove legacy folder
- [x] Remove homepage folder (to be decision, because even homepage is html file, but it is not generated by Hugo)
- [x] Move `docs/document/current` to `docs/document`
- [x] Revise build shell
- [x] Update readme

**Comment by tristaZero** [comment]
@terrymanu My suggestion is to remain homepace at current repo, since we may update it in future.

**Comment by terrymanu** [comment]
@tristaZero Sure, it is better to move homepage to asf-site branch
