### ISSUE TITLE
org.apache.shardingsphere.orchestration.reg.zookeeper.curator.CuratorZookeeperRegistryCenter.persistEphemeral

### ISSUE THREAD

**Issue by joinhappy81** [apache/incubator-shardingsphere#4263]
![image](https://user-images.githubusercontent.com/8109271/74313860-6eb20f00-4daf-11ea-824f-b693b5e916e8.png)

不知道问题出现再那里

**Comment by kimmking** [comment]
which version？

**Comment by kimmking** [comment]
In this project, curator-framework version is:
` <curator.version>2.10.0</curator.version>`

But your log show curator-framework is 4.0.1 in your project.
You should modify to 2.10.0 and retry.

**Comment by joinhappy81** [comment]
> In this project, curator-framework version is:
> ` <curator.version>2.10.0</curator.version>`
> 
> But your log show curator-framework is 4.0.1 in your project.
> You should modify to 2.10.0 and retry.

![image](https://user-images.githubusercontent.com/8109271/74323166-12a3b680-4dc0-11ea-89fd-4191c82000f4.png)


引入项目后，jar包就不对

**Comment by kimmking** [comment]
My project is normal.
You can use `mvn dependency:tree` and check your other pom config refer a 4.0.1 version curator.
