### ISSUE TITLE
Version conflict ：sharding-orchestration-reg-zookeeper-curator-4.0.0

### ISSUE THREAD

**Issue by joinhappy81** [apache/incubator-shardingsphere#4269]
![image](https://user-images.githubusercontent.com/8109271/74328477-f5271a80-4dc8-11ea-9d15-9caaca24b7c1.png)

curator-framework 
curator-recipes
curator-client

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/74353362-c58e0780-4df4-11ea-8248-4733cd13a987.png)

you should use `mvn dependency:tree` to see where the 4.0.1 version was referred.

**Comment by kimmking** [comment]
Hello @joinhappy81 
You should find which dependency importing the wrong curator and exclude it.
