### ISSUE TITLE
CuratorZookeeperInstance can't read server.yaml orchestration props config. 

### ISSUE THREAD

**Issue by dongzl** [apache/incubator-shardingsphere#4270]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC & Sharding-Proxy
### Expected behavior
can read props config and make the props effectively.
### Actual behavior
can't read props config.
### Reason analyze (If you can)
JDK Properties#getProperty method can't read other type data without String.

**Comment by kimmking** [comment]
We should check all properties access in project, avoid invalid props configuration.

**Comment by dongzl** [comment]
Fixes by #4320 .
