### ISSUE TITLE
Add log details for metadata load when app startup

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4278]
ShardingSphere need database and table metadata when app startup.
It will spend lots time if there are lots of amount databases and tables.
It is better to log more details about metadata load when app startup.

The log may include:

- [x] Start to load metadata.
- [x] Number of tables and details of each table name.
- [x] Finish to load metadata and log the total loading time.

**Comment by yuzel** [comment]
I want to try to do this.

**Comment by terrymanu** [comment]
Thank you, assigned

**Comment by yuzel** [comment]
> Verify sharding table or not.
Which link is this? As far as I know, the sharding is not checked for correctness at startup.
