### ISSUE TITLE
Why the readOnly filed in the ShardingConnection is true.

### ISSUE THREAD

**Issue by gxgmy521** [apache/incubator-shardingsphere#4280]
## Question
When get a shardingConnection , the `readOnly` filed is aways true,however ,the same filed in the pthysical datasource connection is false. Can you explain why in the `AbstractConnectionAdapter` class the readOnly is true

**Comment by terrymanu** [comment]
Any hints to reproduce it?

**Comment by gxgmy521** [comment]
You can see in the https://github.com/apache/incubator-shardingsphere/blob/master/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/adapter/AbstractConnectionAdapter.java
the ·`readOnly`value of  the AbstractConnectionAdapter  is set to true 
```
private boolean readOnly = true;
```
However when we get a connection from the Hikari or Druid. the default value is false。

**Comment by ssxlulu** [comment]
It may be a problem about readonly transaction, I will research it further.

**Comment by terrymanu** [comment]
Thank you, assigned @ssxlulu

**Comment by ssxlulu** [comment]
I have researched some documents. The default value of read only  in [MySQL](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_transaction_read_only) or [PostgreSQL](https://www.postgresql.org/docs/current/runtime-config-client.html) is false.Like the following pictures show:

MySQL:
![image](https://user-images.githubusercontent.com/14773179/75307158-fd319080-5885-11ea-9bc1-e5ee23dae6e4.png)

PostgreSQL:
![image](https://user-images.githubusercontent.com/14773179/75307197-1cc8b900-5886-11ea-99ee-5b9531e2006c.png)

So, I think the read only value in AbstractConnectionAdapter should be false as well by default.
