### ISSUE TITLE
Use hintManager.setDatabaseShardingValue can not skip the sql parse

### ISSUE THREAD

**Issue by gxgmy521** [apache/incubator-shardingsphere#4281]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
In the ShardingSphere Doc, it says that users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables. After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced.
I think that in version 4.0.0 ,the setDatabaseShardingValue can only sikp the sql rewrite ,can't skip the sql parse , am i wrong?

**Comment by KomachiSion** [comment]
In 4.0.0, All SQL will be parse. `setDatabaseShardingValue` is only set the hint value, which will be used in route step.

**Comment by KomachiSion** [comment]
No response, close issue.

**Comment by gongguoyu** [comment]
@KomachiSion Hello, if 4.0.0-rc2 cannot be skipped, which version can be skipped？
