### ISSUE TITLE
Use encrypt-raw-jdbc-example fails because of "Unsupport SQL of " error

### ISSUE THREAD

**Issue by ppourali** [apache/incubator-shardingsphere#4317]
## Question
Hi, I am trying to run the encrypt example from the github repo. The example uses encryption rules to insert rows in the table and then prints them. However, when I run the example I get the following error.
`
Exception in thread "main" org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `TRUNCATE TABLE t_user`
	at org.apache.shardingsphere.sql.parser.core.parser.SQLParserEngine.parse(SQLParserEngine.java:77)
	at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:58)
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse0(SQLParseEngine.java:70)
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse(SQLParseEngine.java:52)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.getRewriteSQL(EncryptStatement.java:106)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.executeUpdate(EncryptStatement.java:141)
	at org.apache.shardingsphere.example.core.jdbc.repository.UserRepositoryImpl.truncateTable(UserRepositoryImpl.java:64)
	at org.apache.shardingsphere.example.core.jdbc.service.UserServiceImpl.initEnvironment(UserServiceImpl.java:39)
	at org.apache.shardingsphere.example.core.api.ExampleExecuteTemplate.run(ExampleExecuteTemplate.java:28)
	at org.apache.shardingsphere.example.encrypt.table.raw.jdbc.JavaConfigurationExampleMain.main(JavaConfigurationExampleMain.java:37)
`

 This error is shown for every single sql statement (insert, update, create table, ...) and I don't understand why. The only thing that I changed in the example is that I changed it from Hikari to postgres driver:
`
BasicDataSource dataSource = new BasicDataSource();
dataSource.setDriverClassName("org.postgresql.Driver");
dataSource.setUrl("jdbc:postgresql://127.0.0.1:5432/" + dataSourceName);
dataSource.setUsername(USER);
dataSource.setPassword(PASS);
`

I can see that the connection is established successfully. I appreciate if you could kindly helo me with this. 

Thanks,
Parsa

**Comment by terrymanu** [comment]
What is your version of ShardingSphere?

**Comment by ppourali** [comment]
Hi terrymanu,

It's 4.0.0. I just cloned the master branch. As mentioned, only _select_ statements can be performed.

Thanks,
Parsa

**Comment by terrymanu** [comment]
Got it, it should be a bug, I will resolve this

**Comment by terrymanu** [comment]
Can you provide your rule configuration? It looks like using encrypt only?

**Comment by terrymanu** [comment]
Sorry, just ignore last message, you just the official example

**Comment by geomonlin** [comment]
Hi, Create SQL for table is different in MySQL and PG. Have you changed the SQL？Maybe you can see this acceptance test code as a guide for PG.

**Comment by geomonlin** [comment]
I follow your configuration,it‘s normal

**Comment by geomonlin** [comment]
I followed your configuration and modify the create table SQL statement `CREATE TABLE IF NOT EXISTS t_user (user_id BIGSERIAL NOT NULL, user_name VARCHAR(200), user_name_plain VARCHAR(200), pwd VARCHAR(200), assisted_query_pwd VARCHAR(200), PRIMARY KEY (user_id));
       ` It's successful execution. Maybe you can try it. Can you give more details to  reproduce this problem.

**Comment by ppourali** [comment]
Hi, 

It is very strange to me too. I feel I am doing something wrong! I cloned the repo, performed mvn eclpse:eclipse to make it for eclipse, then imported the projects as eclipse projects and ran my code. I did not change any thing else. However, when I run the sharding-proxy using "start.bat" and then perform the queries, it will work. So, I guess the problem might be the way the projects were built for eclipse. I can send you the whole workspace if you want though.

Thanks,
Parsa

**Comment by geomonlin** [comment]
> Hi,
> 
> It is very strange to me too. I feel I am doing something wrong! I cloned the repo, performed mvn eclpse:eclipse to make it for eclipse, then imported the projects as eclipse projects and ran my code. I did not change any thing else. However, when I run the sharding-proxy using "start.bat" and then perform the queries, it will work. So, I guess the problem might be the way the projects were built for eclipse. I can send you the whole workspace if you want though.
> 
> Thanks,
> Parsa

Sorry I didn't notice the message, that's good. You can put the whole workspace Revised on GitHub,  Your ShardingSphere version is sharding-jdbc 4.0.0. Right?

**Comment by geomonlin** [comment]
> Hi,
> 
> It is very strange to me too. I feel I am doing something wrong! I cloned the repo, performed mvn eclpse:eclipse to make it for eclipse, then imported the projects as eclipse projects and ran my code. I did not change any thing else. However, when I run the sharding-proxy using "start.bat" and then perform the queries, it will work. So, I guess the problem might be the way the projects were built for eclipse. I can send you the whole workspace if you want though.
> 
> Thanks,
> Parsa

And what is your postgres version？

**Comment by geomonlin** [comment]
@ppourali Hi, Have you solved it？

**Comment by ppourali** [comment]
Hi @geomonlin ,

Thanks for following up. I could run my code and it works on my code now. I have no idea why it didn't work on the example though. I'm good now, thanks!

Parsa

**Comment by geomonlin** [comment]
Ok, The example is using mysql. Some SQL statements are different, will be some impact.

**Comment by dongzl** [comment]
Hi @ppourali , I want to solve this problem, but I try the 4.0.0-RC3, 4.0.0, 4.0.1 and the newest code, They work very well, can you reproduce this problem, Thanks.

**Comment by ppourali** [comment]
Hi @dongzl 
Unfortunately, I don't have access to the machine on which this issue occurred. There must be something wrong on my side. Thanks for following up though. I think we can close this issue.
