### ISSUE TITLE
Add documents about ShardingScaling

### ISSUE THREAD

**Issue by ssxlulu** [apache/incubator-shardingsphere#4322]
Here are the documents I think should be writen:
- [x] Quick Start
- [x] Architecture of ShardingScaling
- [x] Admin Guide
- [x] ~~Performance of ShardingScaling~~
- [ ] Transalte to English version.

**Comment by KomachiSion** [comment]
I think performance document can supple before we release. Currently we may need to translate to English version first.

**Comment by KomachiSion** [comment]
@ssxlulu 

What do you think about changing task list to following?

- [ ] ~~Performance of ShardingScaling~~
- [ ] Transalte to English version.

**Comment by ssxlulu** [comment]
> @ssxlulu
> 
> What do you think about changing task list to following?
> 
> * [ ]  ~Performance of ShardingScaling~
> * [ ]  Transalte to English version.

Agree, I will translate the docs to English.
