### ISSUE TITLE
Sharding-Proxy output logs：readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#4338]
## Question
- Sharding-Proxy output logs：`[WARN ] 16:24:10.417 [epollEventLoopGroup-3-12] i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer`
- Sharding-proxy version: 4.0.0-RC3

**Comment by terrymanu** [comment]
It is a WARN log, any problem do you meet?

**Comment by kimmking** [comment]
When and what SQL operation cause this issue?
And which version of your mysql server and jdbc driver?

**Comment by lklkxcxc** [comment]
@kimmking mysql server version: 5.7.24
sharding-proxy jdbc driver: mysql-connector-java-5.1.48.jar 

@terrymanu The warn logs before and after are info levels. The current logging mode is info, which I'll change to debug later.

**Comment by lklkxcxc** [comment]
Change to debug post-log output：`tats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 13:03:17.237 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 13:03:18.446 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Pool stats (total=1, active=0, idle=1, waiting=0)
[WARN ] 13:03:26.641 [epollEventLoopGroup-3-3] i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
[DEBUG] 13:03:47.237 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 13:03:48.447 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Pool stats (total=1, active=0, idle=1, waiting=0)`
No SQL operation cause this issue.

**Comment by kimmking** [comment]
I think we can ignore this message.

**Comment by lklkxcxc** [comment]
@kimmking Thank you very much! Let me close this problem
