### ISSUE TITLE
shardingsphere  4.0.0 retrive very slow that sql script

### ISSUE THREAD

**Issue by ancientelves** [apache/incubator-shardingsphere#4341]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-core</artifactId>
			<version>4.0.0-RC1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-namespace</artifactId>
			<version>4.0.0-RC1</version>
		</dependency>

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
want to complete in 3s
### Actual behavior
14s
### Reason analyze (If you can)
When i debug into code:
class=SQLExecuteCallback
method:execute0
line:T result = this.executeSQL(routeUnit.getSqlUnit().getSql(), statementExecuteUnit.getStatement(), statementExecuteUnit.getConnectionMode());
I found spent long
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
init data->total size:1,0000,000
1.execute sql script:sql:SELECT SUM(size) as size_sum FROM table_test
spent: 26s
2.add properties:max.tolerate.time.difference.milliseconds:8 ->restart application
3.execute sql script:sql:SELECT SUM(size) as size_sum FROM table_test
spent:14s

**Comment by ancientelves** [comment]
also try the below version:
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-spring-namespace</artifactId>
    <version>4.0.0</version>
</dependency>
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-namespace</artifactId>
			<version>4.0.0</version>
</dependency>

The result is same as the above.

**Comment by terrymanu** [comment]
May duplicate with #4231

**Comment by ancientelves** [comment]
@terrymanu there is something different from  #4231,insert is normal only retrive with sharding very slow,under my test,insert 100million/hour and retrive is normal without using sharding,So could you pls help?

**Comment by ancientelves** [comment]
@terrymanu 
when i add:enablePrepareOnFirstPreparedStatementCall=true,it only has a little affect,but still slow

**Comment by kimmking** [comment]
@ancientelves  only one sql with a sum opr?

**Comment by ancientelves** [comment]
@kimmking 
yes,one sql.
for sharding:SELECT SUM(size) as size_sum FROM table_test_0 ......table_test_16
for single table:SELECT SUM(size) as size_sum FROM table_test
sharding performance is bad than single table 
total size:1,0000,000

**Comment by kimmking** [comment]
I got it and will try sooner.

**Comment by ancientelves** [comment]
@kimmking  
waitting your response,my program will go live soon,so pls.
Thanks in advance.

**Comment by kimmking** [comment]
I already run a demo for no sharding-jdbc to test 1M data for sum in a table or 16 tables with union, it takes both 170ms.
I will run sharding-jdbc case this afternoon. @ancientelves

**Comment by kimmking** [comment]
@ancientelves 
After discuss with @terrymanu , I find the key point about this issue.
The parameter `max.connections.size.per.query` in `server.yaml` is 1 by default. This means 16 sub query to each table one by one via a same connection.
In my case, the cost is 250ms by proxy sharding, and came down to 90ms by set the parameter to 8, better than only one table.

But a tip here : don't modify this parameter to a higher value in your production env, cause it maybe    exhausted your jdbc connections in datasource pool.

**Comment by ancientelves** [comment]
@kimmking 
Thanks for your suggestion.Then I will check my program and table again.
BTW,don't modify this parameter to a higher value in your production env,if I set the param to 8 as your above,is it ok? or I should do a lower setup?

**Comment by kimmking** [comment]
You can try 2.

**Comment by kimmking** [comment]
@ancientelves  Does it take effect now?

**Comment by ancientelves** [comment]
@kimmking 
Now it's normal.
Thanks for your help.

**Comment by ancientelves** [comment]
solved
