### ISSUE TITLE
sharding-proxy have been started,but the schema 'sharding_db' can not be seen in the navicat

### ISSUE THREAD

**Issue by ICanFlyFaraway** [apache/incubator-shardingsphere#4377]
sharding-proxy have been started,but the schema 'sharding_db' can not be seen in the navicat.And i have been checked my configure for many times.Any advice for me ? I can not put the picture , becasuse my company has security demands.And my English is so bad :)

**Comment by dongzl** [comment]
Hi @ICanFlyFaraway , Is there any exception? can you provide your config, remove your company's sensitive data?

**Comment by ICanFlyFaraway** [comment]
i just use the example config like follow  

#3697 config-sharding.yaml
schemaName: sharding_db

dataSources:
  ds0: 
    url: jdbc:mysql://localhost:3306/ds0
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65
  ds1:
    url: jdbc:postgresql://localhost:3306/ds1
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds${0..1}.t_order${0..1}
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds${user_id % 2}
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
    t_order_item:
      actualDataNodes: ds${0..1}.t_order_item${0..1}
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds${user_id % 2}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id
  bindingTables:
    - t_order,t_order_item
  defaultTableStrategy:
    none:

#server.yaml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: sharding_db

**Comment by ICanFlyFaraway** [comment]
and there is no any error in the log

**Comment by kimmking** [comment]
with master version: 
![image](https://user-images.githubusercontent.com/807508/74911956-ab59b800-53f8-11ea-942f-552c70b0909b.png)

```
schemaName: testproxy

dataSources:
  test:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false
    username: root
```

**Comment by kimmking** [comment]
4.0.0 is also ok as master 5.x.

![image](https://user-images.githubusercontent.com/807508/74912226-35098580-53f9-11ea-88af-2e5ed6f9bfa9.png)

**Comment by kimmking** [comment]
Navicat for mysql 11.1.13  windows version.

**Comment by kimmking** [comment]
@ICanFlyFaraway  can you show some log/error info in your proxy command line?

**Comment by manbo1987** [comment]
navicat (12.1.21) can not connect the Proxy db
navicat (11.1.13) is ok .
so  could ShardingProxy fix this issue in new version , if not  Please check this and inform navicat to fix it

**Comment by manbo1987** [comment]
> Hi @ICanFlyFaraway , Is there any exception? can you provide your config, remove your company's sensitive data?

navicat (12.1.21) can not connect the Proxy db
navicat (11.1.13) is ok .
so could ShardingProxy fix this issue in new version , if not Please check this and inform navicat to fix it

**Comment by manbo1987** [comment]
![image](https://user-images.githubusercontent.com/45955973/74930746-364aaa80-5419-11ea-8cb6-c3bb37a1109c.png)
navicat 11.1.13 is ok,   maybe the diff connector ?

**Comment by dongzl** [comment]
I use mac Navicat Premium 12.0.24, It's OK.

**Comment by ICanFlyFaraway** [comment]
@dongzl  my navicat (12.1.21) can not show the prxoy schema,but navicat (11.1.13) is ok .

**Comment by dongzl** [comment]
Hi @ICanFlyFaraway , you can use navicat (11.1.13).

Because SharingProxy support some mysql protocol packet imperfectly, so cause this problem.

We will support it in the future.

**Comment by kimmking** [comment]
@ICanFlyFaraway @manbo1987
Can you show some logs when it can't work here. thx.

**Comment by kimmking** [comment]
Hello,  @ICanFlyFaraway 
Could you show the proxy log when navicat can't work?
Or we close this issue later.

**Comment by kimmking** [comment]
We will close this issue soon.
