### ISSUE TITLE
I want to use the self growing primary key. Is there any scheme available？

### ISSUE THREAD

**Issue by ICanFlyFaraway** [apache/incubator-shardingsphere#4402]
I have looked up the src demo, there are only three default way :
1、Snowflake algorithm
2、timestamp
3、UUID
And in my program,when I insert a piece of data,i want get my primary key(ID) back.Thank you for your reply ：）。

**Comment by ICanFlyFaraway** [comment]
I just use sharding-proxy 4.0.0

**Comment by terrymanu** [comment]
Generated key can return via standard JDBC method.

**Comment by kimmking** [comment]
You can use autocrement id just like directly using jdbc, then sharding-proxy is a transparent proxy.

**Comment by ICanFlyFaraway** [comment]
OK，i have implements ShardingKeyGenerator.java，can I use the any interface of the shrding-proxy to excute the sql like “select max（id）...” to get current max id？Or i just use use the original jdbc to get it ？

**Comment by beckhampu** [comment]
@ICanFlyFaraway , i think you already know how to get the self-incrementing primary key. And  as you said,  now you can execute the SQL through jdbc to get the current maximum id.

**Comment by kimmking** [comment]
I guess max(id) is not nessesary and not exactly right.
If you use JDBC directly, use `select last_id()`  after insert a row in the same transaction to be better.
If you use mybatis, you can config mapper like this:
`<insert id="insert" keyProperty="id" useGeneratedKeys="true" ...`

**Comment by beckhampu** [comment]
@kimmking ，maybe you are right.  @ICanFlyFaraway ,  can you give us some more details ?

**Comment by kimmking** [comment]
I think we should close this issue now.

**Comment by beckhampu** [comment]
@kimmking , i think so. I  will close it.
