### ISSUE TITLE
Insert statements with subqueries do not generate SQL correctly.

### ISSUE THREAD

**Issue by kyllyang** [apache/incubator-shardingsphere#4403]
## Question

**insert into (c0, c1, c2) values (v0, (select max(o.v) from other o where o.id = ?), v2), subqueries like this do not generate the correct SQL statement.**

In my project I encountered the case of including subqueries in **insert** statements,

- Original statement: insert into order(c1, c2, c3, c4) values(1,'1',(select ifnull(max(t.s),0)+1 from t_seq t where t.k=1),'1')
- Generated statement: insert into order(c1, c2, c3, c4) values(1, '1', (selectifnull(max(t.s),0)+1 fromt_seqtwheret.k=1), '1')

In the generated statement, the Spaces in the subquery section are completely removed.
Is this SQL writing currently not supported?Or are there alternatives?

I am looking forward to your reply. Thanks to ShardingSphere!

**Comment by terrymanu** [comment]
Can not support subquery now.
We prepare create a new feature for subquery in future.
