### ISSUE TITLE
Integrate seata 1.0。

### ISSUE THREAD

**Issue by ChinaJeckXu** [apache/incubator-shardingsphere#4407]
When to integrate seata 1.0？

**Comment by terrymanu** [comment]
Can you integrate it with a pull request?

**Comment by kimmking** [comment]
@ChinaJeckXu  If you need some guides, we can discuss about this topic here or via email.

**Comment by cherrylzhao** [comment]
seata 1.0 is compatible with shardingsphere, you can see detail [transaction-base-seata-raw-jdbc-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-raw-jdbc-example), seata is `  <seata.version>1.0.0</seata.version>`

**Comment by cherrylzhao** [comment]
fixed it at #4735
