### ISSUE TITLE
Database routing by hint and table sharding by sql parse 

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#4427]
## Feature Request
If you use hint manager to do the database routing, you must set the sharding value to do table sharding. In this scenario the sql will not be parsed and we cannot use the sql to do the table sharding. So we expected to use the DatabaseHintSQLRouter ability and  the ParsingSQLRouter ability at the same time.
1.set the data base sharding only value in the hint manager
2.parse the sql and do table sharding in the specified database in step 1

that means we only use the table sharding in the specified database,  table sharding will not cross database

### Is your feature request related to a problem?
No
### Describe the feature you would like.
Database routing by hint and table sharding by sql parse

**Comment by KomachiSion** [comment]
Try to set the databaseStrategy as HintShardingStrategy and tableStrategy as Standard or Inline Strategy.

**Comment by KomachiSion** [comment]
@lalicw any response? If no response, we will close issue.

**Comment by lalicw** [comment]
ok, i'll try this solution, thanks.

**Comment by KomachiSion** [comment]
@lalicw Any new information?

**Comment by KomachiSion** [comment]
Close issue due to no response more than 7 days.
