### ISSUE TITLE
Unit test task list of orchestraion

### ISSUE THREAD

**Issue by menghaoranss** [apache/incubator-shardingsphere#4439]
The following items are the classes and unit test methods that the orchestration module may need to be covered.

We welcome developers who interested in this especially are not familiar with ShardingSphere but want to contribute to participate. Any questions or supplements, you can reply directly to this issue.

And in order to help new contributors to participate in the project faster, we have provided a unit test development guide,  please refer to this issue #4438 

#### sharding-orchestration-center-api (@llk984145406)

- `org.apache.shardingsphere.orchestration.center.yaml.config.YamlOrchestrationConfiguration`
  - [x] assertInstanceConfigurationMapWithConstructMethod
  - [x] assertInstanceConfigurationMapWithSetMethod

+ `org.apache.shardingsphere.orchestration.center.yaml.swapper.OrchestrationConfigurationYamlSwapper`
  - [x] assertSwapToYamlOrchestrationConfiguration 
  - [x] assertSwapToOrchestrationConfiguration 

#### sharding-orchestration-center-apollo (gongsiran)

+ `org.apache.shardingsphere.orchestration.center.instance.ApolloInstrance`
  + [x] assertGetWithNonExistentKey
  + [x] assertWatchUpdateChangedTypeWithExistedKey
  + [x] assertWatchDeletedChangedType
  + [x] assertWatchUpdateChangedTypeWithNotExistedKey

#### sharding-orchestration-center-nacos (@haetao )

+ `org.apache.shardingsphere.orchestration.center.instance.NacosConfigInstance`
  + [x] assertGetWithNonExistentKey 
  + [x] assertGetWhenThrowException 
  + [x] assertUpdate
  + [x] assertWatchUpdatedChangedType 
  + [x] assertWatchDeletedChangedType 

#### sharding-orchestration-center-zookeeper-curator 

+ `org.apache.shardingsphere.orchestration.center.instance.CuratorZookeeperInstance`
  + [x] assertWatchUpdatedChangedType 
  + [x] assertWatchDeletedChangedType
  + [x] assertWatchAddedChangedType 
  + [x] assertGetWithNonExistentKey 
  + [x] assertBuildCuratorClientWithCustomConfig 
  + [x] assertBuildCuratorClientWithTimeToLiveSecondsEqualsZero 
  + [x] assertBuildCuratorClientWithOperationTimeoutMillisecondsEqualsZero   
  + [x] assertBuildCuratorClientWithDigest 

#### sharding-orchestration-core (@zjcnb )

+ `org.apache.shardingsphere.orchestration.internal.registry.config.listener.SchemaChangedListener`

  + [x] assertCreateWithInvalidNodeChangedEvent 
  + [x] assertCreateWithNullShardingSchemaName 
  + [x] assertCreateAddedEventWithEncryptRuleConfigurationForNewSchema 
  + [x] assertCreateAddedEventWithShardingRuleConfigurationForNewSchema
  + [x] assertCreateAddedEventWithMasterSlaveRuleConfigurationForNewSchema 

+ `org.apache.shardingsphere.orchestration.internal.registry.listener.PostShardingConfigCenterEventListener`

  + [x] assertWatchMultipleKey

**Comment by huangyiminghappy** [comment]
Hi,sharding-orchestration-center-zookeeper-curator's item,i want to try it

**Comment by zjcnb** [comment]
hi, i want try to sharding-orchestration-core case

**Comment by gongsiran** [comment]
I want to try to  sharding-orchestration-core  task

**Comment by kimmking** [comment]
@menghaoranss update assign info to this issue content.

@huangyiminghappy @zjcnb @gongsiran 
You can create your own issue for your sub task.

**Comment by haetao** [comment]
Hi! I wanna try nacos's unit test case!

**Comment by haetao** [comment]
please assign to me

**Comment by kimmking** [comment]
Hi, welcome to contribute.
Everyone who is insterested in a certain sub task can comment in issues#4439, and create his/her own issue to track details util the task is done.
:  )

**Comment by zjcnb** [comment]
Your first five, my last five! What do you think? @gongsiran

**Comment by menghaoranss** [comment]
> Your first five, my last five! What do you think? @gongsiran

**Comment by menghaoranss** [comment]
> Your first five, my last five! What do you think? @gongsiran

@gongsiran , you can also try other modules.

**Comment by ganjx** [comment]
Which module is left, I can try

**Comment by gongsiran** [comment]
i try sharding-orchestration-center-apollo  task

**Comment by gongsiran** [comment]
thank you  @zjcnb

**Comment by gongsiran** [comment]
I want to try sharding-orchestration-center-apollo task  @menghaoranss

**Comment by llk984145406** [comment]
hi, i want try to   sharding-orchestration-center-api case

**Comment by menghaoranss** [comment]
> I want to try sharding-orchestration-center-apollo task @menghaoranss

you can create your issue  now.

**Comment by menghaoranss** [comment]
> hi, i want try to sharding-orchestration-center-api case

@llk984145406  ,  you can create your issue now.

**Comment by gongsiran** [comment]
> > I want to try sharding-orchestration-center-apollo task @menghaoranss
> 
> you can create your issue now.



> > I want to try sharding-orchestration-center-apollo task @menghaoranss
> 
> you can create your issue now.

my issue is  #4451

**Comment by gongsiran** [comment]
> > I want to try sharding-orchestration-center-apollo task @menghaoranss
> 
> you can create your issue now.

my issue is #4451

**Comment by cocodroid** [comment]
None left?

**Comment by menghaoranss** [comment]
@llk984145406
@gongsiran 
@huangyiminghappy
@zjcnb
Could you provide your wechat id or add me on Wechat with remark 'shardingsphere', my wechat id : `haorand003` , I will create a group to communicate and learn from each other.

**Comment by menghaoranss** [comment]
> Hi,sharding-orchestration-center-zookeeper-curator's item,i want to try it

@huangyiminghappy  hi, how about `sharding-orchestration-center-zookeeper-curator` going?

**Comment by menghaoranss** [comment]
hi, @huangyiminghappy 

It's been a week since you claimed the task of `sharding-orchestration-center-zookeeper-curator`, but there is no feedback. If there is still no response, we may consider reassigning the task. 

If you are continuing this task, please confirm as soon as possible. 

Thanks for your attention.

**Comment by kimmking** [comment]
Update tasklist to latest state.
And we need move foward now.

**Comment by menghaoranss** [comment]
@zjcnb @gongsiran @haetao @llk984145406 , thanks for your contribution.
