### ISSUE TITLE
insert operation ok but select operation return null point exception

### ISSUE THREAD

**Issue by leehan0617** [apache/incubator-shardingsphere#4447]
i make 2 datasources and 
partition by key ( modular 2)
insert operation success
but select by key return null pointer error

i config only databaseShardingStrategyConfig
how can i solve this problem? 
thank you for answer.

**Comment by yuzel** [comment]
Please provide information according to the Bug Report template, otherwise we don't know what your specific problem is.

**Comment by terrymanu** [comment]
What is your version, can you provide your SQL?
