### ISSUE TITLE
Add doc to describe read-write split can not support transaction and explain the reason shortly

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4455]
The proposal of read-write split is using data consistence to exchange performance improvement. Using transaction in write node only is OK, but using transaction with read and write together is not good practice.

We need to add the description to document for read-write split.

The files of document:

```
docs/document/content/features/read-write-split/unsupported-items.en.md
docs/document/content/features/read-write-split/unsupported-items.cn.md
```

Tasks are:

- [ ] Add a new item to describe can not supported transaction cross master and slave nodes.
- [ ] Explain the reason shortly for not support transaction cross master and slave nodes.
- [ ] Translate to Chinese.

Link to #4443

**Comment by ganjx** [comment]
I want try it, ths. @terrymanu 

我觉得应该分两个名词，读写事务一致性和主从事务一致性；
1、读写事务一致性是从业务场景看读写是否必须同在一个事务中，再从事务隔离级别的角度来决定；
2、主从事务一致性，主从数据库事务一致性需要牺牲性能来保证同步双写才可以。

**Comment by terrymanu** [comment]
@ganjx Welcome, can we talk with English?

**Comment by geomonlin** [comment]
This's a documents Contributor Guide. https://shardingsphere.apache.org/community/en/contribute/document-contributor/

**Comment by nevereverever** [comment]
I can not find the directory you mentioned.
Should I create a new one named "incubator-shardingsphere-doc/document/content/features/read-write-split/"?
Then commit?

**Comment by geomonlin** [comment]
> I can not find the directory you mentioned.
> Sharding-doc git link is "https://github.com/apache/incubator-shardingsphere-doc.git", that's right ?
> Should I create a new one named "incubator-shardingsphere-doc/document/content/features/read-write-split/"?
> Then commit?

you can see here https://github.com/apache/incubator-shardingsphere/tree/master/docs

**Comment by gongsiran** [comment]
i want to try  add   document

**Comment by nevereverever** [comment]
Sorry,I can't understand.
Write here,then you move it to these documents?
Or I fork shardingsphere then push it?

**Comment by geomonlin** [comment]
> Sorry,I can't understand.
> Write here,then you move it to these documents?
> Or I fork shardingsphere then push it?

yeah, you need fork shardingsphere then push it

**Comment by geomonlin** [comment]
> Sorry,I can't understand.
> Write here,then you move it to these documents?
> Or I fork shardingsphere then push it?

this is latest [ documents Contributor Guide](https://github.com/apache/incubator-shardingsphere/blob/master/docs/community/content/contribute/document-contributor.cn.md). you can see this

**Comment by terrymanu** [comment]
@gongsiran Welcome, assigned
