### ISSUE TITLE
Can ado.net connect sharding-proxy?

### ISSUE THREAD

**Issue by flzxsqcysyhljt** [apache/incubator-shardingsphere#4471]

**Comment by terrymanu** [comment]
Can you have a try with ado.net ?

**Comment by kimmking** [comment]
Yes, it can. Just like JDBC.

**Comment by flzxsqcysyhljt** [comment]
@terrymanu yes,but I ran into some trouble when I opened the link

**Comment by kimmking** [comment]
can you show the error log details?

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/75404008-3b8d8500-5944-11ea-8aca-8927a9a871aa.png)

@flzxsqcysyhljt  As the above image, ADO.NET for MySQL works well via Proxy.

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/75404936-09c9ed80-5947-11ea-8352-0b1e8c725bf0.png)

select/insert/update/delete  tests work well.

**Comment by flzxsqcysyhljt** [comment]
I used the postgres:latest test-_-!!!
I try again now

**Comment by kimmking** [comment]
Can you show your error log in proxy console?

**Comment by flzxsqcysyhljt** [comment]
@kimmking 
psql connect sharding-proxy is allright.

ado connect sharding-proxy:
【ado Exception】:“Received unexpected backend message CompletedResponse. Please file a bug.”
【sharding-proxy】：none

navicat connect sharding-proxy:
sharding-sphere-4-proxy | [INFO ] 03:15:59.533 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0xc01bccb9, L:/0.0.0.0:3308] READ: [id: 0xf95a48dc, L:/192.168.0.3:3308 - R:/172.16.219.142:53464]
sharding-sphere-4-proxy | [INFO ] 03:15:59.534 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0xc01bccb9, L:/0.0.0.0:3308] READ COMPLETE
sharding-sphere-4-proxy | [WARN ] 03:16:00.094 [ShardingSphere-0] c.zaxxer.hikari.pool.ProxyConnection - HikariPool-2 - Connection org.postgresql.jdbc.PgConnection@206fb381 marked as broken because of SQLSTATE(08006), ErrorCode(0)
sharding-sphere-4-proxy | org.postgresql.util.PSQLException: The server's client_encoding parameter was changed to UNICODE. The JDBC driver requires client_encoding to be UTF8 for correct operation.
sharding-sphere-4-proxy | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveParameterStatus(QueryExecutorImpl.java:2604)
sharding-sphere-4-proxy | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2219)
sharding-sphere-4-proxy | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
sharding-sphere-4-proxy | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:1168)
sharding-sphere-4-proxy | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:103)
sharding-sphere-4-proxy | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.executeSQL(StatementExecutorWrapper.java:126)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:78)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:73)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:45)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:79)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:61)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine$1.call(ShardingExecuteEngine.java:119)
sharding-sphere-4-proxy | 	at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine$1.call(ShardingExecuteEngine.java:115)
sharding-sphere-4-proxy | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
sharding-sphere-4-proxy | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
sharding-sphere-4-proxy | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
sharding-sphere-4-proxy | 	at java.lang.Thread.run(Thread.java:745)

**Comment by kimmking** [comment]
which version of pg server and npgsql lib?

**Comment by flzxsqcysyhljt** [comment]
pg:12.1 (Debian 12.1-1.pgdg100+1)
npgsql:4.1.3.1

**Comment by kimmking** [comment]
I reproduce this issue in Windows 10 now.

Env：
-------------------------------------------------------------
 PostgreSQL 10.11, compiled by Visual C++ build 1800, 64-bit
 Npgsql 4.1.3.1

**Comment by kimmking** [comment]
According to remote debug proxy，I get the sql proxy can't parse correctly.
It begin with a comment line:

```
-- Load field definitions for (free-standing) composite types
SELECT typ.oid, att.attname, att.atttypid
FROM pg_type AS typ
JOIN pg_namespace AS ns ON (ns.oid = typ.typnamespace)
JOIN pg_class AS cls ON (cls.oid = typ.typrelid)
JOIN pg_attribute AS att ON (att.attrelid = typ.typrelid)
WHERE
  (typ.typtype = 'c' AND cls.relkind='c') AND
  attnum > 0 AND     -- Don't load system attributes
  NOT attisdropped
ORDER BY typ.oid, att.attnum
```

**Comment by kimmking** [comment]
After debug, I find psql executing successfully cause psql remove the comment line and then send a simple sql to proxy.

**Comment by flzxsqcysyhljt** [comment]
thanks a lot @kimmking 
I try again now

**Comment by kimmking** [comment]
I found a description about the above comment in [pgsql doc site](https://www.postgresql.org/docs/current/catalog-pg-type.html) :

> 
If this is a composite type (see typtype), then this column points to the pg_class entry that defines the corresponding table. (For a free-standing composite type, the pg_class entry doesn't really represent a table, but it is needed anyway for the type's pg_attribute entries to link to.) Zero for non-composite types.

According to it, this query is not nessesary for ADO.NET of Npgsql Connection.
And now I find it had been imported to [ngpsql project](https://github.com/npgsql/npgsq) in file:
https://github.com/npgsql/npgsql/blob/2365e83a7b06aa9270ad6c01f573028383bc93f2/src/Npgsql/PostgresDatabaseInfo.cs

There is a parameter to turn it on/off : `ServerCompatibilityMode.NoTypeLoading`.

@flzxsqcysyhljt  You can retry with:
```
            string ConnectionString = "...............";  

            var conf = new NpgsqlConnectionStringBuilder(ConnectionString)
            {
                ServerCompatibilityMode = ServerCompatibilityMode.NoTypeLoading

            }.ToString();

            using (NpgsqlConnection conn = new NpgsqlConnection(conf))
            {
                conn.Open();
                ........
            }
```

**Comment by kimmking** [comment]
Another way is using my fork repo: https://gitee.com/kimmking/npgsql2

A npgsql.dll has already built under netcore3.1: 
https://gitee.com/kimmking/npgsql2/tree/master/bin/Release/netcoreapp3.1

Or you can make your own .net version builds.

**Comment by flzxsqcysyhljt** [comment]
thanks!
I will maintain my own version

**Comment by guochen2** [comment]
@kimmking 朋友您好，现在我用shardingsphere5.3.1和npgsql5.0.16时碰到问题，无法读取数据，请问您现在还可以正常使用shardingsphere么，我提交的[issues](https://github.com/npgsql/npgsql/issues/4942)

**Comment by kimmking** [comment]
@guochen2  you should start a new thread for your own question.
