### ISSUE TITLE
Shardingsphere takes a long time to parse simple SQL for the first time

### ISSUE THREAD

**Issue by xfyang1988** [apache/incubator-shardingsphere#4480]
Shardingsphere takes about 5S to parse simple SQL for the first time. I know that it takes a little time to parse SQL for the first time, but it feels too slow when the parsing reaches 3-5 seconds. I know that shardingsphere will cache the SQL after the first parsing. What's the reason for the slow first parsing? Is there a good solution

version：Shardingsphere-4.0.0-RC2

![{4693AB9E-3A1D-459C-8DCD-D56F464004EC}_20200226110705](https://user-images.githubusercontent.com/19721648/75308115-7df18c00-5888-11ea-9780-cc5079a3dee2.jpg)

**Comment by dongzl** [comment]
Hi @xfyang1988 , please reference this issue #3676 . Maybe they are same question.

**Comment by dongzl** [comment]
@xfyang1988  I suggest you can upgrade the version to 4.0.0 stable version.

**Comment by xfyang1988** [comment]
> @xfyang1988 I suggest you can upgrade the version to 4.0.0 stable version.

"sharding-core-parse-mysql" does not have version 4.0.0?

**Comment by dongzl** [comment]
> > @xfyang1988 I suggest you can upgrade the version to 4.0.0 stable version.
> 
> "sharding-core-parse-common" does not have version 4.0.0?

what‘s your mean? 4.0.0 is a release version, all module have 4.0.0 version.

**Comment by dongzl** [comment]
> sharding-core-parse-common

I understand your mean, **sharding-core-parse-common** doesn't have 4.0.0 version, because it maybe rename after project refactor.

**Comment by kimmking** [comment]
I'm not sure the parser cost 5s.
As the log show, 10:39:11->10:39:17，the operation log is masked, what does it do?

**Comment by terrymanu** [comment]
Your time cost maybe not SQL parse only, it seems like the cost of load metadata are added too.
Can you use skywalking or other OpenTracing supported project to trace your SQL parser time?

**Comment by xfyang1988** [comment]
> Your time cost maybe not SQL parse only, it seems like the cost of load metadata are added too.
> Can you use skywalking or other OpenTracing supported project to trace your SQL parser time?

OK, I also saw that the connection delay of MySQL is very small. It should not be caused by this problem. Can the metadata be preloaded?

**Comment by xfyang1988** [comment]
> I'm not sure the parser cost 5s.
> As the log show, 10:39:11->10:39:17，the operation log is masked, what does it do?

This is a simple SQL query with an index, which should be fast

**Comment by xfyang1988** [comment]
> Can you use skywalking or other OpenTracing supported project to trace your SQL parser time?

Skywalking is not currently configured to monitor SQL parsing time? 4.0.0 can be directly configured

**Comment by xfyang1988** [comment]
> Your time cost maybe not SQL parse only, it seems like the cost of load metadata are added too.
> Can you use skywalking or other OpenTracing supported project to trace your SQL parser time?

In the sharingsphere configuration item, I only see "check.table.metadata.enabled". The default is false. Is this configuration only checked without preloading?

**Comment by xfyang1988** [comment]
> > sharding-core-parse-common
> 
> I understand your mean, **sharding-core-parse-common** doesn't have 4.0.0 version, because it maybe rename after project refactor.
> 
> How does this matter to you?

It does n’t matter, just ask, it is wrong after upgrading, and it is OK to remove it.

**Comment by xfyang1988** [comment]
Is there any documentation for ShardingSphere and SkyWalking integration? I see the official website document is not very detailed

**Comment by terrymanu** [comment]
The document about SkyWalking, please read document of them

**Comment by terrymanu** [comment]
Any update about this issue?

**Comment by xfyang1988** [comment]
> Any update about this issue?

No, I hope there will be a better parser in the later version. Although ANTLR parser has been cached after the first parsing, it took a little time to parse for the first time. The average time is 1 to 3S, especially in the high concurrency scenario. The support is not very good. I will always pay attention to it. Thank you. You can turn it off

**Comment by terrymanu** [comment]
No plan to change SQL parser engine
