### ISSUE TITLE
Correct the `DataTypeName` for each DataBase

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4482]
The definition of `DataTypeName` in `RuleName.g4`(Antlr grammer file) of each DataBase is not correct so far, therefore this issue is created to correct them. The sub-task list is below,
- [x] Correct the `DataTypeName` for `MySQL`.
- [x] Correct the `DataTypeName` for `PostgreSQL`. 
- [x] Correct the `DataTypeName` for `SQLServer`. 
- [x] Correct the `DataTypeName` for `Oracle`. 
- [x] Correct the `DataTypeName` for `SQL92`. 

Q1: How to learn about the definition of `DataTypeName`?
A:
 - Official document of each DataBase, i.g [MySQL](https://dev.mysql.com/doc/refman/8.0/en/data-types.html).
- [Antlr SQL grammer](https://github.com/antlr/grammars-v4/tree/master/sql)
- Other related Website. (I am not sure. 😃 )

Q2: Which file of ShardingSphere does `DataTypeName` exist?
A: All files named with `RuleName.g4`

**Comment by yuzel** [comment]
Ok, i can support mysql and postgresql first.

**Comment by tristaZero** [comment]
Hi @yuzel You made a good start for this issue, good job. 👍

**Comment by yuzel** [comment]
> Hi @yuzel You made a good start for this issue, good job. 👍
> BTW, are you willing to go on with PostgreSQL or other ones?

Yes, I am going to continue to modify PostgreSQL.

**Comment by tristaZero** [comment]
@yuzel Your continual contribution helps this ISSUE complete. Very appreciated your effort. Hope see your interaction in community more. :)
