### ISSUE TITLE
I hope sharding-proxy supports "explain"

### ISSUE THREAD

**Issue by nevereverever** [apache/incubator-shardingsphere#4488]
version:4.0.0
sharding-proxy should has this function that we can use "explain" to tell us my sql execute in which real datasource.
I hope you can notice my expect.

**Comment by terrymanu** [comment]
Yes, it is. FIY: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/usage/

**Comment by nevereverever** [comment]
@terrymanu 
Thanks for your reply,I use your suggest,it works!
I have a another question,if it only supports simple explan at present, right?
Compare to "Ali drds",this function is not well now,do u considered that improve it in future versions?
