### ISSUE TITLE
add curl command to get the tag_dir in release guide document

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#4493]
we should make diff more detail in release guide, add following section before check source content.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/8317649/75599973-ea68c700-5ae4-11ea-9966-721e7ab8384b.png">

### compare release source with github tag
```
curl -Lo tag-${RELEASE.VERSION}.zip https://github.com/apache/incubator-shardingsphere/archive/${RELEASE.VERSION}.zip | unzip
unzip apache-shardingsphere-incubating-${RELEASE.VERSION}-src.zip
diff -r apache-shardingsphere-incubating-${RELEASE.VERSION}-src tag-${RELEASE.VERSION}
```

task lists is here

- [ ] add curl command in [release.cn](https://github.com/apache/incubator-shardingsphere/blob/master/docs/community/content/contribute/release.cn.md)
- [ ] add curl command in [release.en](https://github.com/apache/incubator-shardingsphere/blob/master/docs/community/content/contribute/release.en.md)

**Comment by JasonKing168** [comment]
I'd like to finish two tasks of this issue.
