### ISSUE TITLE
add git clone --branch xx command in release guide

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#4494]
we should add git clone command to download the release branch as below

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/8317649/75599452-eb4b2a00-5adf-11ea-9759-9d93745f1438.png">

```
git clone -b ${branch} https://github.com/apache/incubator-shardingsphere.git ~/incubator-shardingsphere
```

task is here
- [ ] add git clone command in [release.cn](https://github.com/apache/incubator-shardingsphere/blob/master/docs/community/content/contribute/release.cn.md)
- [ ] add git clone command in [release.en](https://github.com/apache/incubator-shardingsphere/blob/master/docs/community/content/contribute/release.en.md)

**Comment by 80904001** [comment]
could you please assign this issue's two tasks to me?

**Comment by terrymanu** [comment]
@JasonKing168  Welcome, assigned
