### ISSUE TITLE
Replace 'mvn install' by './mvnw install' in release guide

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#4496]
We'd better use './mvnw install' to check released source package.

The files of document:

```
docs\community\content\contribute\release.en.md
docs\community\content\contribute\release.cn.md
```

Task is:

- [ ] Replace 'mvn install' by './mvnw install'

**Comment by yunlibo** [comment]
I'm interested in it. May I try it on?

**Comment by geomonlin** [comment]
> I'm interested in it. May I try it on?

Welcome. If you have any questions, please ask us. Maybe can add your contact information.

**Comment by tuohai666** [comment]
@yunlibo Of  course.

**Comment by ranjeet-floyd** [comment]
@geomonlin  Can i take this ?.

**Comment by tuohai666** [comment]
Hi @ranjeet-floyd, @pseudobinary had submitted a pull request. Thanks.
