### ISSUE TITLE
"Select * From table" returns both plain and cipher columns in the resultset in Sharding-Proxy

### ISSUE THREAD

**Issue by ppourali** [apache/incubator-shardingsphere#4507]
Hello,

My questions is that, when we run SELECT * FROM Table1, it returns both plain column and cipher column , which is not a good idea because what would be the point of encryption then?! However, when we run SELECT column from Table1, it returns the encrypted column only. Are we doing anything wrong?

Thanks,
Parsa

**Comment by dongzl** [comment]
Hi @ppourali , can you show more details, what's your configuration and table structure and so on?

**Comment by ppourali** [comment]
Hi @dongzl ,

Thanks for the reply. 
**Here is my config-encrypt.yaml:**
`
schemaName: anonymized_db

dataSource:
  url: jdbc:postgresql://127.0.0.1:5432/database?serverTimezone=UTC&useSSL=false
  username: dbuser
  password: database
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50

encryptRule:
  encryptors:
    encryptor_aes:
      type: aes
      props:
        aes.key.value: 123456abc
    encryptor_md5:
      type: md5
  tables:
    test:
      columns:
        data:
          plainColumn: data
          cipherColumn: data_anonymized
          encryptor: encryptor_md5
`

**Here is the create script for my test table:**
`
create table public.test (
id INTEGER not null,
	name character varying (20),
	data text,
	data_anonymized text
)
`
The data column is what we want to be encrypted. When we run "SELECT * FROM test", it returns both the data and the data_anonymized column. But we expect to only return the data_anonymized column. We use psql shell to run the queries and connect to port 3307.

Please advise.

Thanks,
Parsa

**Comment by dongzl** [comment]
Hi @ppourali , what's your Sharding-Proxy's version?

I use Sharding-Proxy's lastest version and recurrent your problem.

Your expect to only return the `data_anonymized` column, not include `data ` column?

But what's your expect `data_anonymized`'s value?  `original encrypted data` or `data after decryption`？

**Comment by ppourali** [comment]
Hi @dongzl ,

My expectation is that,  when I do SELECT *, I *only* get the cipher column (we don't want to expose the plain column to the users). So. basically the expectation is that we get only the encrypted data. Let's say we never want to expose the plain (decrypted data to some users).

Thanks,
Parsa

**Comment by tristaZero** [comment]
@ppourali Hi, thanks for your feedback, and I got your point.
It is a bug obviously and we will fix this bug ASAP.

Cheers,
Trista

**Comment by terrymanu** [comment]
Fixed at #4637

**Comment by zhongjiajie** [comment]
> Hi @dongzl ,
> 
> My expectation is that, when I do SELECT *, I _only_ get the cipher column (we don't want to expose the plain column to the users). So. basically the expectation is that we get only the encrypted data. Let's say we never want to expose the plain (decrypted data to some users).
> 
> Thanks,
> Parsa

@terrymanu @tristaZero  So, do we support return only encrypt columns for now? And how
