### ISSUE TITLE
Do not use mock on regular test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4540]
Mock should only use to building difficult or slow objects.
We'd better avoid using mock on regular test cases, it is not a good way for guarantee for test.

The test cases need to rewrite are:

- [ ] ProjectionEngineTest
- [ ] ProjectionsContextEngineTest
- [ ] GroupByContextEngineTest
- [ ] OrderByContextEngineTest
- [ ] PaginationContextTest
- [ ] PaginationContextEngineTest
- [ ] RowNumberPaginationContextEngineTest
- [ ] TopPaginationContextEngineTest
- [ ] SQLStatementContextFactoryTest
- [ ] SelectStatementContextTest

**Comment by rohithbalaji123** [comment]
@terrymanu ,  I would like to give it a try. I shall cover as much as I can from the checklist of Tests mentioned by 4th March EOD(End Of Day), GMT.

**Comment by terrymanu** [comment]
@rohithbalaji123 Welcome, Rohith. I just assign this issue to you. Any question please feel free to contact me.

**Comment by rohithbalaji123** [comment]
@terrymanu , I have quite got the grasp of parser module while working on this issue. Please do assign me if anything pops up related to it or any other module. I'll keep a tab on the issues page as well. Thanks!
