### ISSUE TITLE
sharding-ui can't run well

### ISSUE THREAD

**Issue by nevereverever** [apache/incubator-shardingsphere#4567]
sharding-ui 4.0.0

only supports update,can not add new configuration.

**Comment by kimmking** [comment]
@nevereverever  hello,
What type configuration you want? 
A new zk? or a new orchestration? or a datasource or a group of table rules?

**Comment by nevereverever** [comment]
> @nevereverever hello,
> What type configuration you want?
> A new zk? or a new orchestration? or a datasource or a group of table rules?
@kimmking 
all of them.

**Comment by kimmking** [comment]
You can click Add button to config a new one of them.

**Comment by terrymanu** [comment]
can't run well maybe is not good issue enough, please describe the details next time.
I just colse this one
