### ISSUE TITLE
no viable alternative at input 'user_idinteger'

### ISSUE THREAD

**Issue by icuxika** [apache/incubator-shardingsphere#4575]
## Question

This problem occurred when the table field type is integer, but the table was created successfully

log: Hibernate: create table t_order (order_id bigint not null auto_increment, address_id bigint, status varchar(255), **user_id integer**, primary key (order_id)) engine=InnoDB

error: line 1:111 no viable alternative at input 'user_idinteger'

## Version
org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.0.0

## Code
From examples
[https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example](url)

**Comment by kimmking** [comment]
I try modify user_id type from int to Integer, no differences with the previous.
> Hibernate: create table t_address (address_id bigint not null, address_name varchar(255), primary key (address_id))
[INFO ] 2020-03-03 12:17:36,427 --main-- [ShardingSphere-MetaData] Loading table meta data catalog: demo_ds_0, table: t_address. 
Hibernate: create table t_order (order_id bigint not null auto_increment, address_id bigint, status varchar(255), user_id integer, primary key (order_id))

**Comment by kimmking** [comment]
maybe input incorrect.

**Comment by icuxika** [comment]
> maybe input incorrect.

**I created a new project for the problem.**
[https://github.com/icuxika/sharding-demo.git](url)

## MySQL version
8.0.17

## Console log

`Hibernate: create table t_address (address_id bigint not null, address_name varchar(255), primary key (address_id)) engine=InnoDB

Hibernate: create table t_order (order_id bigint not null auto_increment, address_id bigint, status varchar(255), user_id integer, primary key (order_id)) engine=InnoDB

**line 1:111 no viable alternative at input 'user_idinteger'**

Hibernate: create table t_order_item (order_item_id bigint not null auto_increment, order_id bigint, status varchar(255), user_id integer, primary key (order_item_id)) engine=InnoDB

**line 1:119 no viable alternative at input 'user_idinteger'**

Hibernate: create table t_user (user_id bigint not null auto_increment, assisted_query_pwd varchar(255), pwd varchar(255), user_name varchar(255), user_name_plain varchar(255), primary key (user_id)) engine=InnoDB`

**Comment by kimmking** [comment]
I will try it soon.

**Comment by tristaZero** [comment]
Hi @icuxika 
[Your ULR](https://github.com/apache/incubator-shardingsphere/issues/url) redirects me badly. Could you recheck it?

>line 1:119 no viable alternative at input 'user_idinteger'
Is this exception thrown when you execute the SQL below?
```
create table t_order_item (order_item_id bigint not null auto_increment, order_id bigint, status varchar(255), user_id integer, primary key (order_item_id)) engine=InnoDB
```

Can you configure `sql.show` valid to present more log detail?

**Comment by icuxika** [comment]
@tristaZero 
Maybe you need to copy this URL into your browser to open it or use git clone.
**The problem is strange that SQL is correct but the console will print out error message.**
It looks like it treats "user_id" and "integer" as a whole.

## SQL
Hibernate: `create table t_order (order_id bigint not null auto_increment, address_id bigint, status varchar(255), user_id integer, primary key (order_id)) engine=InnoDB`

## ERROR MESSAGE
line 1:111 no viable alternative at input 'user_idinteger'

**Comment by tristaZero** [comment]
> The problem is strange that SQL is correct but the console will print out an error message

@icuxika It means this is just a print-out error message, does not impact on the service running?

**Comment by icuxika** [comment]
@tristaZero Yes, but I haven't used it in depth.

**Comment by tristaZero** [comment]
Hi @icuxika Actually your reply confused me that I did not know how to handle this issue, maybe more log will help us discover something. What's your opinion? Wait for your further test or closed this one?

**Comment by vvvrbj** [comment]
> Hi @icuxika Actually your reply confused me that I did not know how to handle this issue, maybe more log will help us discover something. What's your opinion? Wait for your further test or closed this one?

I'm sorry for that I can't provide any more information about this problem for the time. You can close it now. Thanks for your answers.

**Comment by tristaZero** [comment]
@vvvrbj Got your point, thanks to your feedback and if possible, welcome to join the community and do something you like.

**Comment by dalaocu** [comment]
I met the same problem.
