### ISSUE TITLE
how can i implement the RegistryCenter???

### ISSUE THREAD

**Issue by beeant0512** [apache/incubator-shardingsphere#4576]
on the documents for SPI description :  

...
The registry center interface is used to regulate its initialization, data storage, data upgrade, monitoring and others.

Its main interface is `RegistryCenter` and built-in implementation types are Zookeeper.

Please refer to Available Registry Center for the introduction
...

but I can not find the `RegistryCenter` interface or class

**Comment by kimmking** [comment]
Hi, @beeant0512 
In master of 5.0.0, we refactor orchestration module to reorganize configcenter，registrycenter and upcoming metadatacenter.
If you prefer to implement a certain one, this may be a useful base project structure: 
https://github.com/apache/incubator-shardingsphere/tree/master/sharding-orchestration/sharding-orchestration-center/sharding-orchestration-center-zookeeper-curator

**Comment by terrymanu** [comment]
The SPI are still developing, so maybe we can discuss this problem after 2 month.

**Comment by terrymanu** [comment]
We will provide document after the feature finished, so I just close this issue.
