### ISSUE TITLE
Consider about new name for ShardingScaling's concept

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4595]
The scope of current concept names of ShardingScaling are too big.
`Reader` and `Writer` maybe not suitable names.
We need to consider about the new name of them, for exmaple: `Source` and `Sink`.

**Comment by KomachiSion** [comment]
What about using `Dumper` to replace `Reader`? 
In mysql, exporting inventory data can using `mysqldump`, subscribe binlog use `COM_BINLOG_DUMP` command, so I think `Dumper` may be better.

**Comment by KomachiSion** [comment]
About `Writer`, I think we can use `Importer` to replace.

In mysql we use `mysqlimport` to import data from dump file.
And in `Datagrip` which database tool by JetBrains, the behavior also is `import`.
