### ISSUE TITLE
Shardingsphere 3.1.0.m1: sharding.props. Sql.show =true configuration is invalid but useful in 3.0.0

### ISSUE THREAD

**Issue by EdwardWangYan** [apache/incubator-shardingsphere#4600]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by EdwardWangYan** [comment]
Print SQL invalid on 3.1.0.m1

**Comment by terrymanu** [comment]
The version is out of service. Can you try to version 4.0.0?
