### ISSUE TITLE
I suggest that sharding-proxy supports appoint divided items by "create table"

### ISSUE THREAD

**Issue by nevereverever** [apache/incubator-shardingsphere#4602]
version:4.0.0

such as 
```sql
create table test ( a int, b int, c char(20)) shardkey=a,shardingType=standard,shardingClass=xxx.xxx.xxx;
```

Will be a bright future.

**Comment by kimmking** [comment]
Now it can create all sharding tables according to your rules. 
Examples:
> sharding in test{0..2}

Executing by your code:
> create table test ....

Executing by shardingsphere:
> create table test0 ....
> create table test1 ....
> create table test2 ....


If you consider shardingClass syntax is helpful, you can try a go to submit a pull-request.

**Comment by kimmking** [comment]
@nevereverever should we close this issue？

**Comment by nevereverever** [comment]
I know what you mean.
I'm familiar with this.
Ok.I close it.
