### ISSUE TITLE
Too slow to load meta data when start up

### ISSUE THREAD

**Issue by dalong316** [apache/incubator-shardingsphere#4604]
At present, I have more than 3000 sub tables. It takes too long to load sharding at the start of the project. I have set the consistency check metadata to "false" and it takes effect, but the time is still very long. I have located the code part that takes a long time

private Map<String, TableMetaData> loadDefaultTables(final ShardingRule shardingRule) throws SQLException {
        Map<String, TableMetaData> result = new HashMap<>(shardingRule.getTableRules().size(), 1);
        Optional<String> actualDefaultDataSourceName = shardingRule.findActualDefaultDataSourceName();
        if (actualDefaultDataSourceName.isPresent()) {
            for (String each : getAllTableNames(actualDefaultDataSourceName.get())) {
                result.put(each, tableMetaDataLoader.load(each, shardingRule));
            }
        }
        return result;
    }
tableMetaDataLoader.load(each, shardingRule)
*This part is the main reason

**Comment by tristaZero** [comment]
@dalong316 
Hi much feedback from community concerning this issue make us give priority to this one. 

After it finishes, could you give us a hand to test it better or not?

**Comment by tristaZero** [comment]
@dalong316 Hi which version is your adoption?

**Comment by dalong316** [comment]
Okay, I'll test it now

**Comment by dalong316** [comment]
How many threads are open to use multithreading
@tristaZero

**Comment by dalong316** [comment]
I've compiled it several times and reported an error. When can I release the official version when I fix this problem
@tristaZero

**Comment by kimmking** [comment]
@dalong316  can you send me a 3000 table-ddl and sharding-rule, my wx is kimmking.

**Comment by dalong316** [comment]
@kimmking 
Can you give me your email address or WeChat?
Because there are a lot of things, I ca n’t write in it
This is my WeChat: 18811452212

**Comment by tristaZero** [comment]
> I've compiled it several times and reported an error. When can I release the official version when I fix this problem
> @tristaZero

What's the exception?

**Comment by tristaZero** [comment]
> How many threads are open to use multithreading
> @tristaZero

`max.connections.size.per.query` decides how many connections SS can use to execute SQL on one DB which represents the number of multiple threads.

**Comment by dalong316** [comment]
I compiled the master with ./mvnw clean install -Prelease, and then introduced the jar package into the project. As a result, the project could not find the corresponding class.
Later, I introduced the source code to my project and found that the situation is the same, and there are many external jar packages that cannot be referenced, such as some jars from Google, and many similar cases, basically the jar packages cannot be referenced.
@tristaZero

**Comment by tristaZero** [comment]
@dalong316 
How about your test report?

**Comment by kimmking** [comment]
@dalong316  aliyun maven mirror is good choice.

**Comment by dalong316** [comment]
Improve the loading efficiency by modifying the configuration of max.connections.size.per.query,
I now have 1100+ watches, 10 threads, about 120 seconds
100 threads about 60 seconds
But need to consider the situation of different connection pools

**Comment by tristaZero** [comment]
@dalong316 Thanks for your report.
Here is the summary to help speed up the metadata loading when service startups.
1. Update to 4.0.1 above, which helps speed up the process of loading table metadata from `the default dataSource`
2. Configure `max.connections.size.per.query`(Default value is 1) higher referring to connection pool you adopt.

**Comment by codingIsCrazy** [comment]
4.0.1 is ok?

**Comment by YX-GitH** [comment]
hi ,  I use  4.1.1  but it do not work， it also slow to load meta data when start up，Is there any other solution？

**Comment by tristaZero** [comment]
Hi @YX-GitH 
If possible, could you try the latest version 5.0.0-alpha, which carries a significant improvement on metadata loading?

**Comment by pototallxg** [comment]
i have the same problem,switch 5.0, error:
nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: java.lang.ClassCastException: org.apache.shardingsphere.sharding.api.config.strategy.sharding.HintShardingStrategyConfiguration cannot be cast to org.apache.shardingsphere.sharding.api.config.strategy.sharding.StandardShardingStrategyConfiguration\r\n### The error may exist in com/cunfang/house/mapper/maintenance/HSaleShiKanMapper.java (best guess)\r\n### The error may involve com.cunfang.house.mapper.maintenance.HSaleShiKanMapper.insert-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO HSale_ShiKan  ( shiKanTime, titleUrl, vrId, vrTitleUrl, city, houseId,  insertBid, insertUserName, insertTime,  status )  VALUES  ( ?, ?, ?, ?, ?, ?,  ?, ?, ?,  ? )\r\n### Cause: java.lang.ClassCastException: org.apache.shardingsphere.sharding.api.config.strategy.sharding.HintShardingStrategyConfiguration cannot be cast to org.apache.shardingsphere.sharding.api.config.strategy.sharding.StandardShardingStrategyConfiguration",

**Comment by pototallxg** [comment]
public DataSource shardingDataSource(Map<String, DataSource> dataSourceMap) throws SQLException {

        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();

        Collection<ShardingTableRuleConfiguration> tables = new ArrayList<>();
        tables.add(new ShardingTableRuleConfiguration("HSale_Key", "cunfang-slave0.HSale_Key"));
        tables.add(new ShardingTableRuleConfiguration("HSale_ShiKan", "cunfang-slave0.HSale_ShiKan"));

        ShardingStrategyConfiguration dbShardingConfig = new HintShardingStrategyConfiguration("dbShardingAlgorithm");
        Properties dbShardingAlgorithmrProps = new Properties();
        dbShardingAlgorithmrProps.setProperty("algorithm-class-name", "com.cunfang.house.dbengine.shardingconfig.dbsharding.DataSourceRoutingAlgorithm");
        shardingRuleConfig.getShardingAlgorithms().put("dbShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("INLINE", dbShardingAlgorithmrProps));

        ShardingStrategyConfiguration tableShardingConfig = new HintShardingStrategyConfiguration("tableShardingAlgorithm");
        Properties tableShardingAlgorithmrProps = new Properties();
        tableShardingAlgorithmrProps.setProperty("algorithm-class-name", "com.cunfang.house.dbengine.shardingconfig.tablesharding.TableKeyHintShardingAlgorithm");
        shardingRuleConfig.getShardingAlgorithms().put("dbShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("INLINE", tableShardingAlgorithmrProps));

        shardingRuleConfig.setDefaultDatabaseShardingStrategy(dbShardingConfig);
        shardingRuleConfig.setDefaultTableShardingStrategy(tableShardingConfig);
        shardingRuleConfig.setTables(tables);

        return ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton(shardingRuleConfig), new Properties());
    }
}

**Comment by tristaZero** [comment]
Hi,

> Cause: java.lang.ClassCastException: org.apache.shardingsphere.sharding.api.config.strategy.sharding.HintShardingStrategyConfiguration cannot be cast to org.apache.shardingsphere.sharding.api.config.strategy.sharding.StandardShardingStrategyConfiguration"

The error log shows obviously. Plus, [Examples](https://github.com/apache/shardingsphere/tree/5.0.0-alpha/examples) is a great guide.

**Comment by pototallxg** [comment]
i find the prop 'check-table-metadata-enabled =false'，not work in lowwer DB version.

**Comment by tristaZero** [comment]
>  'check-table-metadata-enabled =false' not work in lowwer DB version.

This property is in the range of `ShardingSphere`, so it definitely takes no effect on Databases.
