### ISSUE TITLE
Update download links

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4607]
As `https://www.apache.org/dist/` has been deprecated, we need to update our website as well.
- [ ] Update all URLs containing `https://www.apache.org/dist/` with `https://downloads.apache.org`
- [ ] Access all updated ULRs for checking.

The targets pages are 
- [EN](https://shardingsphere.apache.org/document/current/en/downloads/)
- [CN](https://shardingsphere.apache.org/document/current/cn/downloads/)

**Comment by geomonlin** [comment]
I'm interested
