### ISSUE TITLE
sharding-proxy doesn't support comment in first line: line 1:0 mismatched input '#'

### ISSUE THREAD

**Issue by adamswanglin** [apache/incubator-shardingsphere#4612]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-proxy docker image ：
shardingsphere/sharding-proxy:3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
return sql results
### Actual behavior
client: Unknown exception: Unsupported SQL of '#test'
sharding-proxy log: line 1:0 mismatched input '#' expecting {BEGIN, INSERT, RENAME, SAVEPOINT, SELECT, UPDATE, SET, WITH, ALTER, COMMIT, CREATE, DELETE, DROP, GRANT, REVOKE, ROLLBACK, START, TRUNCATE}
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
execute sql:
```
#test
select * from t_test limit 1;
```
t_test is sharded table.

**Comment by kimmking** [comment]
This is also the reason of the bug: 
- Npgsql in ADO.NET to connection to PostgreSQL server.

And one of reasons of the bug:
- mysqldump tool can't work. (another reason is that LOCK/UNLOCK not supported)

**Comment by kimmking** [comment]
BTW:  this case can't reproduced by mysql-cli, cause it cleverly remove comments and then send sql command to server.

**Comment by terrymanu** [comment]
Can you try to 4.x? the version 3.x is out of service
