### ISSUE TITLE
ComplexKeysShardingAlgorithm support different types of columns？

### ISSUE THREAD

**Issue by yuwei5380** [apache/incubator-shardingsphere#4622]
eg:
create table aaa (
no  int,
id   varchar2(10)
);
if  we need columns 'no' and 'id', how to write the code?

**Comment by geomonlin** [comment]
About Configuration description, you can see [Configuration Item Explanation](https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-yaml/#configuration-item-explanation). Maybe this a similar example,you can [read ](https://www.cnblogs.com/rinack/p/11241111.html).

**Comment by kimmking** [comment]
As @geomonlin referred:
At first config no and id in your config file:
> complex: #Complex sharding scenario for multiple sharding columns
            shardingColumns: #Names of sharding columns. Multiple columns separated with comma
            algorithmClassName: #Complex sharding algorithm class name. This class need to implements ComplexKeysShardingAlgorithm, and require a no argument constructor

And then, write a class  implements ComplexKeysShardingAlgorithm, the two colunms will retrieved in the second parameter of doSharding method.

**Comment by kimmking** [comment]
@yuwei5380 shall we close this issue？

**Comment by yuwei5380** [comment]
ComplexKeysShardingAlgorithm<String>, but The two columns are of different types

**Comment by grapeqin** [comment]
in 5.1.1 version ,please take the following steps：

1. implement ComplexKeysShardingAlgorithm<Comparable<?>> create my own ClassBasedShardingAlgorithm
2. override doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Comparable<?>> shardingValue) method
3. get each ColumnNameAndShardingValue from shardingValue
`Map<String, Collection<Comparable<?>>> shardingMap = shardingValue.getColumnNameAndShardingValuesMap();
Collection<Comparable<?>> uidCollection = shardingMap.get("no");
Collection<Comparable<?>> orderNoCollection = shardingMap.get("id");
`
