### ISSUE TITLE
rangeAlgorithmClassName can't work ?

### ISSUE THREAD

**Issue by brzone** [apache/incubator-shardingsphere#4629]
I use 4.0 proxy version.

here is config-sharding.yaml  :
![image](https://user-images.githubusercontent.com/7804031/76062241-47bab780-5fc0-11ea-904d-8e233451cfd0.png)

If i use = or in ,the preciseAlgorithmClassName can be work.
but i user >= & <= ,the rangeAlgorithmClassName can't be work, 

here is the sql excute:
![image](https://user-images.githubusercontent.com/7804031/76062407-9b2d0580-5fc0-11ea-804a-93a8e9309481.png)
![image](https://user-images.githubusercontent.com/7804031/76062450-b0a22f80-5fc0-11ea-8355-e1c3aff0d296.png)

but i really config rangeAlgorithmClassName , may be something is error ?

thanks .

**Comment by kimmking** [comment]
According the log, you config a inline strategy, plz check it.

**Comment by brzone** [comment]
yes，see the log must be config a inline strategy.
but the picture,  i really config stardard,  user myself RangeShardingAlgorithm

**Comment by brzone** [comment]
i know the truth,   because the databaseStrategy i use inline , so , the proxy think the table is inline ,but i set tableStrategy set standard 。
so  tableStrategy  is standard ,databaseStrategy  must be standard  ?

**Comment by kimmking** [comment]
Can you make a simple demo to reproduce this issue for me to profiling it ?

**Comment by brzone** [comment]
![image](https://user-images.githubusercontent.com/7804031/76412530-b936a380-63ce-11ea-93ad-3299611c2146.png)
this config throw : Inline strategy cannot suppory range sharding

![image](https://user-images.githubusercontent.com/7804031/76412696-00bd2f80-63cf-11ea-833d-2bc545090ccb.png)
no databaseStrategy  inline config can be ok .

i means ,  databaseStrategy of inline can affect tableStrategy's standard  .

**Comment by terrymanu** [comment]
Just the information said: Inline strategy cannot suppory range sharding

If you want use range sharding, please config range algorithm, please see example to get more information.
