### ISSUE TITLE
Use logic columns for ResultSetMetaData when execute query SQL

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4637]
Currently, the ResultSet's meta data for query is incorrect.
The sharding derived columns and actual encrypt columns will return with the rewrited SQL together. 
It is the time to enhance the query meta data, only column label with logic SQL should be returned.

The tasks are:

- [x] Add domain model for projection meta data
- [x] Rename encrypt column or plain column to logic column in query metadata
- [x] Remove derived columns for GROUP BY and ORDER BY for sharding module
- [x] Adapt for JDBC
- [x] Adapt for Proxy

**Comment by dongzl** [comment]
ref #3995 .

**Comment by tristaZero** [comment]
> ref #3995 .
@dongzl 
You did what I am gonna do. Good job.

**Comment by dongzl** [comment]
ref #4507 .

**Comment by dongzl** [comment]
ref #3932 .
