### ISSUE TITLE
How to connect to Microsoft SQL Server in the backend?

### ISSUE THREAD

**Issue by ppourali** [apache/incubator-shardingsphere#4638]
Hi I am trying to connect to MSSQL Server on my backend but I'm not able to make it work. My configuration is shown below. I don't have any issue with connecting to the Postgres though. I also found that it was complaining about not being able to find the MicrosoftSQLServer spi class. I then provided some fake class as my own spi implementation for the DatabaseProtocolFrontendEngine and sharding-proxy is able to run but still can't perform queries (probably because of my fake spi implementation). So the question is do I really need to write my own spi class? Because in the documentation it says that sharding-proxy can support any MSSQL Server as long as the front end is MySql/Postgres. Please advise.

Thanks. 

schemaName: mydatabase
dataSource:
  url: jdbc:sqlserver://127.0.0.1:1433;instance=sqlexpress;databaseName=mydatabase;
  username: postgres
  password: 12345678
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50

**Comment by dongzl** [comment]
Hi @ppourali , I understand you want to manage MSSQL database with Sharding-Proxy.

But Sharding-Proxy only support PostgresSQL and MySQL.

Only provide MicrosoftSQLServer spi class is not enough, we also need encapsulates MSSQL database binary protocol. 

You can reference this document：https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/

Encapsulates MSSQL database binary protocol is a huge work and It maybe not allowed for Microsoft Company.

**Comment by kimmking** [comment]
@ppourali 
> Because in the documentation it says that sharding-proxy can support any MSSQL Server as long as the front end is MySql/Postgres. 

I guess it's not referred in documents.
And now proxy haven't support the usage of this case.
But in actually principle, it shoud be adjust to fit this case, you may investigate the details and try a pull-request to fix it.

**Comment by terrymanu** [comment]
We never try to use SQLServer as a backend database.
But we just use JDBC to connect backend database, so it maybe works if you just config your database url to sqlserver.
But there maybe need change some source code to judge the url about database type. If it is not MySQL or PostgreSQL, the proxy may throw an exception

**Comment by terrymanu** [comment]
May I close this issue?
