### ISSUE TITLE
Use YAML configuration instead of java configuration for DataSource test

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4645]
YAML configuration is clear and easy to understand. 
Using YAML configuration to instead of java configuration for DataSource test is better.
The test cases need to be refactored:

- [ ] AbstractEncryptJDBCDatabaseAndTableTest for encrypt rule creation
- [ ] AbstractMasterSlaveJDBCDatabaseAndTableTest for master slave rule creation
- [ ] AbstractShardingJDBCDatabaseAndTableTest for sahrding rule creation

**Comment by HetaoWang** [comment]
I want to do it

**Comment by terrymanu** [comment]
@HetaoWang Welcome on board.

**Comment by ranjeet-floyd** [comment]
@terrymanu  Can i take this ?. Thanks

**Comment by terrymanu** [comment]
@ranjeet-floyd there are 3 sub-tasks, you can take the last one if you interest.

**Comment by ranjeet-floyd** [comment]
@terrymanu  ok  i will take   `AbstractShardingJDBCDatabaseAndTableTest for sahrding rule creation` Thanks

**Comment by ranjeet-floyd** [comment]
@terrymanu Raised PR for AbstractEncryptJDBCDatabaseAndTableTest.  https://github.com/apache/incubator-shardingsphere/pull/4871

Please let me if this is right way , then can will do others.
