### ISSUE TITLE
Throw correct SQLState and vendorCode with SQLException when out of index from ResultSetMetaData.getColumnName()

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4654]
The current ResultSetMetaData can throw SQLException without SQL State. Please fill the correct SQLState and vendorCode in SQLException.

Please fix on classes under `TODO fill correct SQL state` comment:

- [ ] ShardingResultSetMetaData
- [ ] EncryptResultSetMetaData

**Comment by zjcnb** [comment]
hi, i want to do it

**Comment by terrymanu** [comment]
@zjcnb Thank you, I just assigned to you.

**Comment by zjcnb** [comment]
hi, I tested it, 
state is S1002 (Invalid column number)
vendorCode is 0
