### ISSUE TITLE
can  sharding-integration-test  cover sharding-proxy ?

### ISSUE THREAD

**Issue by lvye351** [apache/incubator-shardingsphere#4660]
### Is your feature request related to a problem?
yes, its about sharding-proxy 's   black box testing  
### Describe the feature you would like.
can  sharding-integration-test  cover sharding-proxy ? it only cover sharding-jdbc now !

**Comment by terrymanu** [comment]
Not yet. current sharding-integration-test can cover sharding-jdbc only.
Do you interested for reuse the existed test case cover sharding-proxy? Use docker image to build  sharding-proxy and MySQL can help us setup the enviroment.

**Comment by terrymanu** [comment]
Closed because nobody interest with it for now.
