### ISSUE TITLE
关于proxy的高可用

### ISSUE THREAD

**Issue by juaihua** [apache/incubator-shardingsphere#4668]
Can I deploy several proxy instances with the same single zookeeper configure center to support a HA BD proxy?

**Comment by kimmking** [comment]
1.Can you modify the title to English.
2.You can deploy more than one proxy now, but a tip: if you modify db/table metadata, it can't automatically broadcast to other proxies now, you should reboot them manually.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by juaihua** [comment]
> 1.Can you modify the title to English.
> 2.You can deploy more than one proxy now, but a tip: if you modify db/table metadata, it can't automatically broadcast to other proxies now, you should reboot them manually.

ok  thank you , @kimmking
