### ISSUE TITLE
ComplexKeysShardingAlgorithm &&  HintShardingAlgorithm 

### ISSUE THREAD

**Issue by qwe123okd** [apache/incubator-shardingsphere#4669]
Usually I use ComplexKeysShardingAlgorithm
But in special cases HintShardingAlgorithm will be used
Can HintShardingAlgorithm and ComplexKeysShardingAlgorithm be used together？

**Comment by qwe123okd** [comment]
now I use HitManager in ComplexKeysShardingAlgorithm

**Comment by KomachiSion** [comment]
I can't understand your problem, please change your issue title and description.

**Comment by terrymanu** [comment]
Can you change the title for search firendly?

**Comment by terrymanu** [comment]
@qwe123okd Can I close this issue if no more update?
