### ISSUE TITLE
In version 4.0.1, hintmanager.setdatabaseshardingvalue cannot be used. When will this problem be fixed

### ISSUE THREAD

**Issue by joinhappy81** [apache/incubator-shardingsphere#4698]
In version 4.0.1, hintmanager.setdatabaseshardingvalue cannot be used. When will this problem be fixed

**Comment by kimmking** [comment]
Can you explain the details?

**Comment by kekerzzZ** [comment]
In version 4.0.1, you should use  `hintmanager.addDatabaseShardingValue()`  or use `spring.shardingsphere.sharding.tables.tablename.table-strategy.hint.algorithm-class-name=` configuration.   
The current version uses Hint, and you need to configure separate tables.

**Comment by KomachiSion** [comment]
@joinhappy81 please provide more information
like configuration, SQLs, table structure.

**Comment by KomachiSion** [comment]
I think the problem is duplicated with #3964 .
