### ISSUE TITLE
there is a "table doesn't exist" problem, even if i set the "defaultDataSourceName" property

### ISSUE THREAD

**Issue by mrnx2004** [apache/incubator-shardingsphere#4702]
## there is a "table doesn't exist" problem, even if i set the "defaultDataSourceName" property

I download the shardingSphere-proxy docker image by this command：
**docker pull apache/sharding-proxy**

Then, I put the "mysql-connector-java-5.1.47-bin.jar" into "/opt/sharding-proxy/lib".
According to the documentation, my container run successfully.
I use MySqlWorkbench to Connect ShardingSphere-Proxy.
I can innsert and search data from the table that have configured in shardingRule. 
But when I try to operate other table in "sharding_db"，there is a error like this:
**Error Code:1146.Table 'sharding_db.tableName' doesn't exist.**

But I have configured **defaultDataSourceName: ds0** in **config-sharding** file.
I can see all the table in MysqlWorkBanch under sharding_db, But I can only read and write to the table Which have sharding rule.

Here is my config-sharding.yaml content:
```
dataSources:
	ds0:
		url: jdbc:mysql://……?serverTimezone=UTC&useSSL=false&characterEnoding=utf8
		username：
		password:
		connectionTimeoutMilliseconds: 30000
		idleTimeoutMilliseconds: 60000
		maxLifetimeMilliseconds: 1800000
		maxPoolSize: 65
	ds1:
		url: jdbc:mysql://……?serverTimezone=UTC&useSSL=false&characterEnoding=utf8
		username：
		password:
		connectionTimeoutMilliseconds: 30000
		idleTimeoutMilliseconds: 60000
		maxLifetimeMilliseconds: 1800000
		maxPoolSize: 65
		
shardingRule:
	tables:
		suite:
			actualDataNodes: ds${0..1}.suite${0..1}
			tableStrategy:
				inline:
					shardingColumn: project_id
					algorithmExpression: suite${project_id % 2}
			keyGenerator:
				type: SNOWFLAKE
				column: directory_id
		testcase:
			actualDataNodes: ds{0..1}.testcase${0..1}
			tableStrategy:
				inline:
					shardingColumn: suite_id
					algorithmExpression: testcase${suite_id % 2}
			keyGenerator:
				type: SNOWFLAKE
				column: testcase_sequence
	bindingTables:
		- suite,testcase
	defaultDataSourceName: ds0
	defaultDatabaseStrategy:
		inline:
			shardingColumn: id
			algorithmExpression: ds${id % 2}
	defaultTableStrategy:
		none:
```
I don't konw why the default dataSource seems doesn't really work.

**Comment by menghaoranss** [comment]
@mrnx2004  i will try to reproduce the problem based on your configuration above.

**Comment by menghaoranss** [comment]
@mrnx2004 which version of workbench do you use?

**Comment by mrnx2004** [comment]
@menghaoranss Version 6.3.6 build 511CE(64 bits) Community

**Comment by mrnx2004** [comment]
I find out that if i use "select * from sharding_db.tableName"，it will report an error.
But if I use "select * from tableName", it works.
Is this a bug ?

**Comment by menghaoranss** [comment]
> I find out that if i use "select * from sharding_db.tableName"，it will report an error.
> But if I use "select * from tableName", it works.
> Is this a bug ?

@mrnx2004  i tried `select * from anyDatabase.tableName`, it also excuted successfully, just the tableName has been configured in sharding rule, i think this syntax has not well supported yet.

**Comment by mrnx2004** [comment]
@menghaoranss I got it , Thank you for your response to my inquiry.
