### ISSUE TITLE
OrchestrationShardingDataSource LOGIC_SCHEMA_NAME issue

### ISSUE THREAD

**Issue by odyssey1816** [apache/incubator-shardingsphere#4703]
English description:
When OrchestrationShardingDataSource is initialized, why did I go to zookeeper via ShardingConstant.LOGIC_SCHEMA_NAME to get the rules and data source instead of the name of the Add Schema I added in the sharding-ui management background?
Where can I specify the Schema Name created in the background?

中文描述: 
OrchestrationShardingDataSource 初始化时, 为什么是通过ShardingConstant.LOGIC_SCHEMA_NAME去zookeeper获取规则和数据源, 而不是我在sharding-ui管理后台Add Schema的名称?
我在哪里可以指定我自己创建的Schema Name?

**Comment by kimmking** [comment]
Is version 4.0.0 with sharding-jdbc?

**Comment by kimmking** [comment]
As discussing this topic with @odyssey1816  via wechat，maybe a bug that sharding-ui can't work well  in orchestration module with sharding-jdbc.

I will check it a bug or not.

**Comment by terrymanu** [comment]
@odyssey1816 Can I close this issue if no update any more?

**Comment by kimmking** [comment]
@odyssey1816 you can use  examples codes, 

org.apache.shardingsphere.example.orchestration.raw.jdbc.JavaConfigurationExampleMain
in incubator-shardingsphere\examples\sharding-jdbc-example\orchestration-example\orchestration-raw-jdbc-example

Set loadConfigFromRegCenter = true; // in line 51. And run it.
This jdbc-demo will write it's configuration to zk server, the zk node path is just the same with proxy.

![image](https://user-images.githubusercontent.com/807508/76856388-20040300-688e-11ea-8760-b99ebcec1336.png)
