### ISSUE TITLE
About sharding-proxy import & export

### ISSUE THREAD

**Issue by nevereverever** [apache/incubator-shardingsphere#4708]
version : sharding-proxy 4.0.0

How to import and export quickly in sharding-proxy？

Which tool is compatible？

Only mysqldump?

**Comment by kimmking** [comment]
Mysqldump is not supported now.  see https://github.com/apache/incubator-shardingsphere/issues/4612#issuecomment-595200837
You can make an investigation and try to fix it. 
: )

**Comment by terrymanu** [comment]
Proxy is not equals with MySQL, the data and binlog is not in proxy machine. dump from MySQL and export from proxy is not make sense.
