### ISSUE TITLE
proxy-4.0.1 can't view table design in DB tools like DBeaver

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#4709]
i can't view table's design in DBeaver
![image](https://user-images.githubusercontent.com/51982240/76397649-6fda5a00-63b6-11ea-8ff1-dde8d1af438a.png)

**Comment by kimmking** [comment]
Can you show the error log in proxy console?

**Comment by menghaoranss** [comment]
Here is log :
```
ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='demo_ds' AND TABLE_NAME='t_order' ORDER BY ORDINAL_POSITION
```
This is the actual SQL that is executed when viewing the columns in dbeaver, TABLE_SCHEMA and 
TABLE_NAME are not rewritten.

**Comment by terrymanu** [comment]
Duplicated with #3572
