### ISSUE TITLE
request for support tidb

### ISSUE THREAD

**Issue by yinkaihuang** [apache/incubator-shardingsphere#4711]
how long can sharding-proxy support tidb?

**Comment by kimmking** [comment]
There is no plan so far.
If you are insterested in this feature, you may try to make an investigation and post to community.

**Comment by tristaZero** [comment]
@yinkaihuang You know, TIDB can handle sharding tables, which is similar to ShardingSphere.
So I am curious why you want to adopt Sharding Proxy and TIDB together?

Actually, Sharding Proxy can understand the protocol of MySQL. Based on that, you can view TIDB as one MySQL server, which Sharding Proxy can visit.
I am not sure it is feasible or not, and welcome your opinion. But first of all, I'd like to listen to your idea about my first question. 

Thanks,
Trista

**Comment by SteNicholas** [comment]
@tristaZero TiDB is compatible with MySQL protocol. @yinkaihuang I recommend you to try sharding-sphere on TiDB.

**Comment by tristaZero** [comment]
@SteNicholas Hi I guessed so, however, what I concerned is why @yinkaihuang wants to do that, i.e., what problem he encountered.

**Comment by terrymanu** [comment]
@yinkaihuang  I will close this issue soon if no more update.

**Comment by tristaZero** [comment]
@yinkaihuang
Hi Sorry, this issue has not received any reply from you for more than 7 days. So we have to close it.
