### ISSUE TITLE
if columns has name "source"  will report error When update version from 4.0.0 to 4.0.1.  like select/insert/update. 

### ISSUE THREAD

**Issue by aqara** [apache/incubator-shardingsphere#4725]
Error querying database.  Cause: java.lang.ClassCastException: org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext
The error may exist in com/lumi/aiot/cloud/mapper/IotUserMappingMapper.java (best guess)
The error may involve com.lumi.aiot.cloud.mapper.IotUserMappingMapper.selectByExample-Inline
The error occurred while setting parameters

 SQL: SELECT  id,user_id,source,value,country_code,create_time,update_time  FROM iot_user_mapping  WHERE       (  source = ? )

Cause: java.lang.ClassCastException: org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext

When can fix this bug? Project Urgent

**Comment by terrymanu** [comment]
What is your version?

**Comment by SteNicholas** [comment]
@aqara The same issue to #4546 .I will close this issue and discuss in #4546 .
