### ISSUE TITLE
Update examples&documents for orchestration-refactoring

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#4736]
According to #4522/#4681/#4701 that refactor orchestration module, and then we should update our examples&documents now. 
We need several volunteers or contributors join us to compelete it. 
Anyone is welcome to get your own mission by replying here.

- [x] Update examples for orchestration-refactoring #4796 
- [x] Update documents for orchestration-refactoring #4942

**Comment by menghaoranss** [comment]
I will refactor the example synchronously when dealing with this issue #4778
