### ISSUE TITLE
When config sharding rule use UI, DatabaseStrategy and TableStrategy whether to support the Hint?

### ISSUE THREAD

**Issue by kekerzzZ** [apache/incubator-shardingsphere#4737]
version: shardingsphere-ui 5.0.0-RC1-SNAPSHOT

I want to use config center of Shardingsphere Orchestration,  now i have a problem. 
1.Following is my configuration.

![image](https://user-images.githubusercontent.com/20736319/76531603-67fee080-64b0-11ea-8662-74c2e53f98ab.png)

2.result

![image](https://user-images.githubusercontent.com/20736319/76531813-b4e2b700-64b0-11ea-87db-f8fd77002b43.png)

this MyHintShardingAlgorithm class is i customized.  
Whether I use wrong or does not support hint?

thanks for the reply

**Comment by KomachiSion** [comment]
@kekerzzZ Sorry,  pictures are hard to load, can you show your configuration and result by text?

**Comment by kekerzzZ** [comment]
1. My config

`defaultDatabaseStrategy:
  hint:
    algorithmClassName: com.my.testshardingsphere.MyHintShardingAlgorithm
defaultTableStrategy:
  hint:
    algorithmClassName: com.my.testshardingsphere.MyHintShardingAlgorithm`

2. Exception result 

`java.lang.ClassNotFoundException: com.my.testshardingsphere.MyHintShardingAlgorithm`

3. Code exception location
`ShardingAlgorithmFactory#newInstance`

4. My question
`MyHintShardingAlgorithm` class is my custom, when Instantiate appear  exception is `MyHintShardingAlgorithm` class is not found,  so  i want to know whether I use wrong or does not support hint.

Thanks for the reply!

**Comment by KomachiSion** [comment]
Obviously, your classloader of your application can't find your `MyHintShardingAlgorithm`, so make sure your custom algorithm is in classpath.

It's not problem of shardingsphere. I think we should close this issue.

**Comment by kekerzzZ** [comment]
ok thank you.
