### ISSUE TITLE
When Use Select * from with Mysql, Select One Record But return null 

### ISSUE THREAD

**Issue by phoema** [apache/incubator-shardingsphere#4746]
See Ref #4728
mybatis xml mapper

select * from ${prefix}ACT_GE_PROPERTY where NAME_ = #{name, jdbcType=VARCHAR} 
is return null

select NAME_, VALUE_, REV_ from ${prefix}ACT_GE_PROPERTY where NAME_ = #{name, jdbcType=VARCHAR}
is return one record

**Comment by kimmking** [comment]
Show the actual SQL show in console log, plz.

**Comment by phoema** [comment]
2020-03-12 16:41:14,173 INFO (ShardingSQLLogger.java:75)- Actual SQL: master ::: select * from ACT_GE_PROPERTY where NAME_ = ? ::: [cfg.execution-related-entities-count]
Actual SQL is write。
Version 4.0.1 is write
master branch of 2020-03-05 is write
but I do not know new code where is changed。

**Comment by phoema** [comment]
See Ref #4728

**Comment by phoema** [comment]
char *
is not supported in new code after 2020-03-05?

**Comment by phoema** [comment]
![image](https://user-images.githubusercontent.com/8730272/76592922-be5f3400-652f-11ea-891a-eb0f64df4e2d.png)

* is return null,  when change columns then return one record

**Comment by phoema** [comment]
I tried to changed  many sql from * to columns such as:
    <sql id="FiledNames">
        ID_, REV_, NAME_, BYTES_, DEPLOYMENT_ID_
    </sql>

then it works well.
but it is too many.

**Comment by terrymanu** [comment]
Did you mean version 4.0.1 and master is fine?
What's your version to meet the problem?

**Comment by phoema** [comment]
Version 4.0.1 is OK
my local code wiht master branch of 2020-03-05( 0ce016e13fd5ba42b5f6beba595d68e955f8dc1e [0ce016e]) is OK
when I got the new source code . 713ae319f45b4a97d3fe465c38071b2a29e3ebd2 [713ae31] \
not work well.

**Comment by phoema** [comment]
I changed My sql with 6 examples:
  1)  select NAME_, VALUE_, REV_ from ACT_GE_PROPERTY where NAME_ = #{name, jdbcType=VARCHAR}
 2)     select * from act_ge_property where NAME_ = #{name, jdbcType=VARCHAR}
 3)     select act_ge_property.* from act_ge_property where NAME_ = #{name, jdbcType=VARCHAR}
 4)     select t.* from act_ge_property as t where NAME_ = #{name, jdbcType=VARCHAR}
 5)     select * from ACT_GE_PROPERTY where NAME_ = #{name, jdbcType=VARCHAR}
 6)     select ACT_GE_PROPERTY.* from ACT_GE_PROPERTY where NAME_ = #{name, jdbcType=VARCHAR}

when I build with master branch of new source code . 713ae31 [713ae31] 
1/2/3/4 is works well
5/6 not well
may be when char * ,then find columns from metadata with tableName with not uppercase/lowercase ?

【MySql Database config I set
lower_case_table_names=1 means ingore upper/lower】

**Comment by phoema** [comment]
when I reset master branch with 0ce016e13fd5ba42b5f6beba595d68e955f8dc1e [0ce016e]
1/2/3/4/5/6 is works well

**Comment by terrymanu** [comment]
Thank you for the report. The problem is caused by #4651 and #4653 probably.
Maybe load metadata error in some cases. Do you use sharding and encrypt together? 
It is better to show your rule configuration may help us analyze this issue.

**Comment by phoema** [comment]
Only Using Hint
yaml.xml:

dataSources:
  master: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wise-master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
  test: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wise-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
  test2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wise-test2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
shardingRule:
  tables:
    v_info_case:
      databaseStrategy:
        hint: #Hint
          algorithmClassName: com.smarttree.manage.config.mybatis.HintShardingStrategy
    .........
    act_ge_property:
      databaseStrategy:
        hint: #Hint
          algorithmClassName: com.smarttree.manage.config.mybatis.HintShardingStrategy
    sys_tenant_info:
      actualDataNodes: master.sys_tenant_info
      databaseStrategy:
        none: #Hint
    sys_column_define:
      actualDataNodes: master.sys_column_define
      databaseStrategy:
        none: #Hint
  defaultDatabaseStrategy:
    hint: #Hint
      algorithmClassName: com.smarttree.manage.config.mybatis.HintShardingStrategy
  defaultTableStrategy:
    hint: #Hint
      algorithmClassName: com.smarttree.manage.config.mybatis.HintShardingStrategy
props:
  sql.show: true

**Comment by phoema** [comment]
not encrypt

**Comment by terrymanu** [comment]
The bug is caused by #4637. I just link to that issue.
It is not a bug because it is not cross the release, the fix progress is inside 5.0.0-SNAPSHOT.
