### ISSUE TITLE
Setting SQL timeout time in mybatis does not take effect after sharding- JDBC 4.0.0-RC2 is used

### ISSUE THREAD

**Issue by ma1562013338** [apache/incubator-shardingsphere#4760]
## Bug Report

Setting SQL timeout time in mybatis does not take effect after sharding- JDBC 4.0.0-RC2 is used

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding- JDBC 4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
The SQL setup timeout should take effect
### Actual behavior
The SQL timeout does not take effect after sharding- JDBC is used
### Example codes for reproduce this issue (such as a github link).
` <select id="testTimeout" resultType="int" timeout="3">
        select sleep(10);
    </select>`

**Comment by terrymanu** [comment]
We have no plan to support this. Does anybody interest about this issue?

**Comment by ma1562013338** [comment]
@terrymanu To prevent individual slow SQL from dragging down the entire database, it is necessary to set the SQL timeout time. I hope to be able to support mybatis to set the SQL timeout time.

**Comment by terrymanu** [comment]
@ma1562013338 Do you interesting this issue?

**Comment by ma1562013338** [comment]
Yes, I hope to add this feature, and I think it's useful.

**Comment by terrymanu** [comment]
@ma1562013338 Can you provide a design? Then we can discuss further.

**Comment by ma1562013338** [comment]
@terrymanu I hope the timeout time set by mybatis is valid. Such as:
`<configuration>
    <settings>
        <setting name="defaultStatementTimeout" value="20"/>
    </settings>
</configuration>

<select id="test" timeout="10" resultType="xxx">
        select * from tableName
    </select>
`

**Comment by terrymanu** [comment]
@ma1562013338  Hi, maybe we misunderstand each other.
What I mean is we have no plan to implement this feature (because it is not a major issue). So we need to find a  volunteer to do this feature. 

Do you interest to develop this feature?

**Comment by terrymanu** [comment]
Closed until somebody interesting about this issue
