### ISSUE TITLE
Add start-index and stop-index assertion for ParameterMarkerExpression

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4776]
This issue is to count the `start-index` and `stop-index` to assert `ParameterMarkerExpression `

### How to find the targets to be fixed?
1. Open class `ExpressionAssert` and clear the comment of `SQLSegmentAssert.assertIs(assertContext, actual, expected)` in `assertParameterMarkerExpression`.
2. run `SQLParserParameterizedTest`
3. All the SQL cases which have the error assertion results are our targets to be fixed.

### How to fix the above assertion results?
1. Look at the exception log and find the corresponding `SQL Case ID` and `SQL`.
2. Find out the `parsing result` of this `SQL Case ID` in `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml`
3. Calculate the correct `start-index` and `stop-index` of `parameter-marker-expression` segment (i.e., `?`) of this `SQL`.
4. Add the calculated `start-index` and `stop-index` labels of `parameter-marker-expression` segment to `parsing result` of this `SQL Case ID`, like
```
            <parameter-marker-expression value="2" start-index="10" stop-index="11" />
```
5. Run `SQLParserParameterizedTest` again to check whether this `SQL Case ID` does not stay in the list of `SQL` with  `bad assertion result`.

**Comment by tristaZero** [comment]
This issue is part of the `parsing assertion improvement` series which includes,
#4690

**Comment by geomonlin** [comment]
I‘ll do it.

**Comment by tristaZero** [comment]
@geomonlin Hi Any progress made?

**Comment by geomonlin** [comment]
> @geomonlin Hi Any progress made?

This is basically over. Will submit later.
