### ISSUE TITLE
Add start-index and stop-index assertion for LiteralExpressionSegment

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4781]
Hi, we are glad you can fix this issue to become a contributor to Apache Sharding Sphere. 
Welcome! 😃 

By doing this assignment, you can learn more about how a query SQL is parsed and how to verify the parsing result of a SQL in Apache ShardingSphere.

**This issue is to** add the parsing assertion for `LiteralExpressionSegment ` by adding the `start-index` and `stop-index` attributes in `parsing-result.xml`.

It is not difficult, and the following comment also gives you the detailed instruction. BTW, if you need any help, please be free to reply this one.

**Comment by tristaZero** [comment]
### How to find the targets to be fixed?
1. Open class `ExpressionAssert` and clear the comment of `SQLSegmentAssert.assertIs(assertContext, actual, expected)` in `assertLiteralExpression`.
2. run `SQLParserParameterizedTest`
3. All the SQL cases which have the error assertion results are our targets to be fixed.

### How to fix the above assertion results?
1. Look at the exception log and find the corresponding `SQL Case ID` and `SQL`.
2. Find out the `parsing result` of this `SQL Case ID` in `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml`
3. Calculate the correct `start-index` and `stop-index` of `literal-expression` segment of this `SQL`.
4. Add the calculated `start-index` and `stop-index` labels of `literal-expression` segment to `parsing result` of this `SQL Case ID`, like
```
            <literal-expression value="init" start-index="10" stop-index="11" />
```
5. Add the correct `literal-start-index` and `literal-stop-index` of `order-by` segment to `parsing result` of this `SQL Case ID` when it is necessary, like
```
            <literal-expression value="init" literal-start-index="10" literal-stop-index="11" />
```
6. Run `SQLParserParameterizedTest` again to check whether this `SQL Case ID` does not stay in the list of `SQL` with  `bad assertion result`.

### Note

1. What is the definition of `literal-expression`?

For instance, here is a SQL,
> select * from tb where id = 1 or id =?

The value of `1` is a `LiteralExpressionSegment`, on the other hand, `?` is a `ParameterMarkerExpression `.

2. What is the difference between `literal-start-index` and `start-index`?

When a SQL does not contain parameter maker, i.e.,`?`, this SQL only has one form; Otherwise, you will see two forms of this SQL, i.e, a SQL form filled with parameter and a SQL form only with parameter marks. For instance,
```
Case1 One SQL without parameter mark,
select * from table where id = 1;

Case2 One SQL with parameter mark,
Original SQL: select * from table where id = ?;
SQL filled with Parameter: select * from table where id = 1;
```
Replace `the parameter mark` with `the actual parameter` will change the position of the segment. Therefore we need to add `start-index` to represent the start position of a segment for `Original SQL`, and `literal-start-index` is used to represent the start position of a segment for `SQL filled with Parameter`.

**Comment by zjcnb** [comment]
I'd like to try it,  assigned to me please! 😁

**Comment by terrymanu** [comment]
@zjcnb Thank you for interest. But you still working on #4768, please fix it first.

**Comment by terrymanu** [comment]
The #4768 is merged, I just assign this issue to you @zjcnb

**Comment by zjcnb** [comment]
> The #4768 is merged, I just assign this issue to you @zjcnb

thanks

**Comment by tristaZero** [comment]
@zjcnb Hi How about this issue? If you have any problems, please be free to tell us.

**Comment by zjcnb** [comment]
> @zjcnb Hi How about this issue? If you have any problems, please be free to tell us.

Hi, I'll finished this week, I've been a bit busy at work recently

**Comment by zjcnb** [comment]
hi, i hava a question! 
sql is :
update t_order set status = 'update' where order_id = 1000 and user_id = 10

xml is: 
 <update sql-case-id="update_without_parameters">
        <table name="t_order" start-index="7" stop-index="13" />
        <set start-index="15" stop-index="35">
            <assignment start-index="19" stop-index="35" literal-start-index="28">
                <column name="status" start-index="19" stop-index="24" literal-stop-index="35"/>
                <assignment-value>
                    <literal-expression value="update" />
                </assignment-value>
            </assignment>
        </set>
        <where start-index="37" stop-index="74" literal-start-index="54" literal-stop-index="74">
            <and-predicate>
                <predicate start-index="43" stop-index="57">
                    <column-left-value name="order_id" start-index="43" stop-index="50" literal-start-index="54" literal-stop-index="57"/>
                    <operator type="=" />
                    <compare-right-value>
                        <literal-expression value="1000" />
                    </compare-right-value>
                </predicate>
                <predicate start-index="63" stop-index="74">
                    <column-left-value name="user_id" start-index="63" stop-index="69" literal-start-index="73" literal-stop-index="74"/>
                    <operator type="=" />
                    <compare-right-value>
                        <literal-expression value="10" />
                    </compare-right-value>
                </predicate>
            </and-predicate>
        </where>
    </update>

What's wrong? Can you correct that?
