### ISSUE TITLE
Add start-index and stop-index assertion for ComplexExpressionSegment

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4782]
Hi, we are glad you can fix this issue to become a contributor to Apache Sharding Sphere. 
Welcome! 😃 

By doing this assignment, you can learn more about how a query SQL is parsed and how to verify the parsing result of a SQL in Apache ShardingSphere.

**This issue is to** add the parsing assertion for `ComplexExpressionSegment ` by adding the `start-index` and `stop-index` attributes in `parsing-result.xml`.

It is not difficult, and the following comment also gives you the detailed instruction. BTW, if you need any help, please be free to reply to this one.

**Comment by tristaZero** [comment]
### How to find the targets to be fixed?
1. Open class `ExpressionAssert` and clear the comment of `SQLSegmentAssert.assertIs(assertContext, actual, expected)` in `assertCommonExpression`.
2. run `SQLParserParameterizedTest`
3. All the SQL cases which have the error assertion results are our targets to be fixed.

### How to fix the above assertion results?
1. Look at the exception log and find the corresponding `SQL Case ID` and `SQL`.
2. Find out the `parsing result` of this `SQL Case ID` in `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml`
3. Calculate the correct `start-index` and `stop-index` of `common-expression` segment of this `SQL`.
4. Add the calculated `start-index` and `stop-index` labels of `common-expression` segment to `parsing result` of this `SQL Case ID`, like
```
            <common-expression text="VALUES(status)"  start-index="10" stop-index="11" />
```
5. Add the correct `literal-start-index` and `literal-stop-index` of `common-expression` segment to `parsing result` of this `SQL Case ID` when it is necessary, like
```
            <common-expression text="VALUES(status)" literal-start-index="10" literal-stop-index="11" />
```
6. Run `SQLParserParameterizedTest` again to check whether this `SQL Case ID` does not stay in the list of `SQL` with  `bad assertion result`.

### Note

1. What is the definition of `common-expression`?
`common-expression` means an expression that contains a function or a calculated expression.

For instance, here is a SQL,
> INSERT INTO t_order_item (item_id, order_id, user_id, status, creation_date) VALUES (?, ?, ?, 'insert', now())

The value of `now()` is a `LiteralExpressionSegment`.
> INSERT INTO t_order (t_order.order_id, t_order.user_id, t_order.status) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE t_order.status = VALUES(t_order.status)

This example shows the value of `VALUES(t_order.status)` is a `LiteralExpressionSegment`.

2. What is the difference between `literal-start-index` and `start-index`?

When a SQL does not contain parameter maker, i.e.,`?`, this SQL only has one form; Otherwise, you will see two forms of this SQL, i.e, a SQL form filled with parameter and a SQL form only with parameter marks. For instance,
```
Case1 One SQL without parameter mark,
select * from table where id = 1;

Case2 One SQL with parameter mark,
Original SQL: select * from table where id = ?;
SQL filled with Parameter: select * from table where id = 1;
```
Replace `the parameter mark` with `the actual parameter` will change the position of the segment. Therefore we need to add `start-index` to represent the start position of a segment for `Original SQL`, and `literal-start-index` is used to represent the start position of a segment for `SQL filled with Parameter`.

**Comment by yu199195** [comment]
Hi,I will fix it

**Comment by terrymanu** [comment]
Thank you, assigned @yu199195

**Comment by yu199195** [comment]
@tristaZero @terrymanu  I will fix it, hope to get your advice and help.

**Comment by tristaZero** [comment]
@yu199195 Much appreciate that and look forward to your contribution to the community.
