### ISSUE TITLE
Check uniformed with all actual tables' meta data in once when loading them

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4785]
ShardingSphere will check uniformed for all actual tables' meta data if user config to enable meta data checking.

The current `checkUniformed()` method can only find the first violation and halt the check by throw an exception. The message of exception is included the first violated actual table only.

It will be better to check all actual tables and record all violations. After check finished, the exception can include all violations information.

The code is in `org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader`, please search `// TODO check all meta data in once` to get the check point.

**Comment by JasonKing168** [comment]
I'd like to finish this.

**Comment by kimmking** [comment]
@JasonKing168  Nice. I will do a favor to give you any help.
