### ISSUE TITLE
if you put ShadingSphere in Chinese folder，SQLCasesLoader and SQLCasesLoader can not load File

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shardingsphere#4805]
## Bug Report
https://github.com/apache/incubator-shardingsphere/blob/master/sharding-sql-test/src/main/java/org/apache/shardingsphere/test/sql/loader/SQLCasesLoader.java

https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/java/org/apache/shardingsphere/sql/parser/integrate/jaxb/SQLParserTestCasesRegistry.java

Example  code：

File[] files = new File(url.getPath())

if url has Chinese garbled code ，the files is not exist。

**Comment by kimmking** [comment]
On Windows ?

**Comment by yu199195** [comment]
@kimmking  No ，on mac  os .  I think this path , use utf-8 decode will better..

**Comment by kimmking** [comment]
Can you submit a pr to fix it.

**Comment by yu199195** [comment]
ok,I will fix it .

**Comment by terrymanu** [comment]
> use utf-8 decode will better..

How about if default character is not uft-8?

**Comment by yu199195** [comment]
@terrymanu  ues  toURI() and  then  URI.getPath()  What do you think?

**Comment by kimmking** [comment]
You should modify it and then try it in your case.
