### ISSUE TITLE
sqlserver when table name or db name with "ed" would be disappeared in generated actual sql 

### ISSUE THREAD

**Issue by leehom** [apache/incubator-shardingsphere#4808]
in sqlserver，when table name or db name with “ed”， say,  t_xxx_yyyed_zzz, the generated actual sql , that table name, is  t_xxx_yyy_zzz, “ed" is disappered

**Comment by terrymanu** [comment]
What is your version?

**Comment by leehom** [comment]
3.1.0，we don't use original properties config that ss provide, we dev java configs to build the  sharding rule configuration, i try to toString(), but nothing output. but as so far, no other problem except that one

**Comment by kimmking** [comment]
Can you try 4.0.0

**Comment by terrymanu** [comment]
The version 3.x is out of service. I just close this issue. If you find same problem in version 4.x, please report a new one.
