### ISSUE TITLE
Add test cases for TypedProperties implementation

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#4820]
Please add test cases for TypedProperties implementation. The example is `org.apache.shardingsphere.underlying.common.config.properties.ConfigurationPropertiesTest`

The remains test cases need to be finished are: 

- [ ] Test case of OrchestrationProperties
- [x] Test case of ZookeeperProperties
- [x] Test case of EtcdProperties
- [ ] Test case of NacosProperties
- [x] Test case of ApolloProperties

**Comment by ruanjiehui** [comment]
I want to try the ZookeeperProperties test cases @terrymanu

**Comment by kimmking** [comment]
> I want to try the ZookeeperProperties test cases @terrymanu

Nice, anything could be discussed about here.

**Comment by meAsky** [comment]
I want to try the ApolloProperties test cases @terrymanu

**Comment by terrymanu** [comment]
@meAsky Welcome

**Comment by meAsky** [comment]
Test case of ApolloProperties has been merged into the master in another pull request

**Comment by meAsky** [comment]
I want to try the EtcdProperties  test cases

**Comment by ruanjiehui** [comment]
@terrymanu I want to finish the rest test case, Test case of OrchestrationProperties and  Test case of NacosProperties.
