### ISSUE TITLE
No value specified for parameter 1

### ISSUE THREAD

**Issue by CorsonMi** [apache/incubator-shardingsphere#4822]
使用版本4.0.0-RC3-CW 系统正常使用，升级到4.0.1后系统报错，具体如下

org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLException: No value specified for parameter 1

**Comment by kimmking** [comment]
Plz show the config rules and logic SQL&actual SQL.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by rimal** [comment]
@terrymanu I am actually facing a similar issues after upgrading from 3.1 to 4.0

It is not failing for all entities. One difference which I could find for the entity for which it is failing is, that in `InsertSQLStatementContext`, `insertValueContexts` is empty. This lead to the parser to expect all column values to be there in the insert query, but actually, all columns are not there in insert statement executed by code.

In my case, `id` is auto-generated and the insert query does not have `id` column at all. But the parser is expecting value for this as well and giving an error for `no value specified for parameter`

**Comment by rimal** [comment]
@kimmking 

Logic SQL: `insert into sample_table (client, create_date, source, key_string, source_id, ticket_id) values (?, ?, ?, ?, ?, ?)`

Actual SQL: shard-1 ::: `insert into sample_table (client, create_date, source, key_string, source_id, ticket_id) values (?, ?, ?, ?, ?, ?)`

**Comment by XiaoDongJi** [comment]
i meet the same proplem, param is normal,but i got "java.sql.SQLException: No value specified for parameter 1" exception, i debug found org.apache.shardingsphere.sql.parser.relation.statement.impl.InsertSQLStatementContext#getInsertValueContexts(java.util.List<java.lang.Object>) method got null

**Comment by dengjin001** [comment]
sharding 4.1.1 same the problem,  is there a solution?

**Comment by hmohammed448** [comment]
> @terrymanu I am actually facing a similar issue after upgrading from 3.1 to 4.0
> 
> It is not failing for all entities. One difference which I could find for the entity for which it is failing is, that in `InsertSQLStatementContext`, `insertValueContexts` is empty. This lead to the parser to expect all column values to be there in the insert query, but actually, all columns are not there in insert statement executed by code.
> 
> In my case, `id` is auto-generated and the insert query does not have `id` column at all. But the parser is expecting value for this as well and giving an error for `no value specified for parameter`

Hello rimal i was also stuck in same problem i used
```
// Inserting Data into Table Query
String q = "INSERT INTO youtube(tName, tCity) VALUES(?,?)";

// Prepared Statement Object
            PreparedStatement pstmt = con.prepareStatement(q);

// set the values to query
pstmt.setString(1,"John Smit");
```

![image](https://github.com/apache/shardingsphere/assets/101665407/78db4695-2113-4f12-bbf8-be7df17acfed)
