### ISSUE TITLE
report error Must have sharding column with subquery.

### ISSUE THREAD

**Issue by xiaozichen** [apache/incubator-shardingsphere#4842]
My  version : Sharding-JDBC  4.0.0-RC1 
sql:
select *from tb_user where user_id in  (select user_id from t_order  where order_id ='446429826933325824')

tb_user : bussine table
t_order  sharding table , sharding rule : order_id ;

config:
spring.shardingsphere.sharding.tables.t_order.table-strategy.inline.sharding-column = order_id
spring.shardingsphere.sharding.tables.t_order.table-strategy.inline.algorithm-expression = t_order_$->{order_id % 2 + 1}

**Comment by terrymanu** [comment]
Duplicated with #4722
