### ISSUE TITLE
Some tools cannot display logic schema name

### ISSUE THREAD

**Issue by nevereverever** [apache/incubator-shardingsphere#4846]
Version: sharding-proxy 4.0.1

Description: 
Some tools(just like new version of navicat or idea) cannot display logic schema name,it shows real database name.

I debugger the code , I found that two different statements were executed：

`select database()` and `show databases()`.

select will route to real node.

**Comment by kimmking** [comment]
idea/datagrip, you should turn on "introspect using jdbc metadata"(or it will get all real tables info from informations_schema):
![image](https://user-images.githubusercontent.com/807508/77047762-48ac0a00-6a00-11ea-96b1-6f0a0492d122.png)

**Comment by terrymanu** [comment]
volunteer wanted for support `select database()`

**Comment by terrymanu** [comment]
It is not the necessary SQL we need to support now, and nobody interesting about this issue, so I just close this one until volunteer want to do it.

**Comment by nevereverever** [comment]
I fixed this.
How to contribute?
