### ISSUE TITLE
Is it possible SqlParserResultCache  cause memory leak?

### ISSUE THREAD

**Issue by wowojyc** [apache/incubator-shardingsphere#4875]
## Bug Report
My sharding-jdbc-core version is :
    <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc</artifactId>
        <version>4.0.0-RC2</version>
my IBM memory analyzer show here may cause memory leak
![image](https://user-images.githubusercontent.com/9378228/77218863-e91e3d80-6b6a-11ea-8754-929a643d89b9.png)

**Comment by terrymanu** [comment]
Fixed by #2997 at version 4.0.1
