### ISSUE TITLE
Sharding-Proxy什么时候支持MS SQL呢？

### ISSUE THREAD

**Issue by jikoy** [apache/incubator-shardingsphere#4881]
最近新项目选项，拜读了Sharding-JDBC之后，发现这不正是我想要的吗？

**Comment by jikoy** [comment]
第一个问题解决了，第二个问题又来了，分布之后，我要后台查一个数据，这么多库和表，又麻烦了。惊喜地发现Sharding-Proxy，可惜不支持MS SQL，请问这个有计划吗？

**Comment by kimmking** [comment]
Not in plan table now.
This issue is duplicated with https://github.com/apache/incubator-shardingsphere/issues/4638.

**Comment by tristaZero** [comment]
@jikoy Please abide by the Apache community rule to communicate in English.
As @kimmking said, there is no plan to develop proxy for MS. If you are interested in it, welcome join us to do so.
