### ISSUE TITLE
How to integrate sharding-proxy with seata

### ISSUE THREAD

**Issue by juaihua** [apache/incubator-shardingsphere#4882]
hi , guys

i am looking for integrating shading-proxy with seata,  but i find only little information on how to

operate this,  where can i get some quite clear information or manual . below is the docs from 

sharding-sphere web site :

"BASE目前没有打包到Sharding-Proxy中，使用时需要将实现了ShardingTransactionManagerSPI

jar拷贝至conf/lib目录，然后切换事务类型为BASE。"

no more ,  please pay attention i mean the proxy , not jdbc.

 
thanks very much.

**Comment by cherrylzhao** [comment]
hi, you should build the sharding-proxy by yourself from source code. 
1. git clone shardingshpere project
2. add  seata dependencies in the pom.xml of sharding-proxy-distribution like this
```
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-rm-datasource</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-tm</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-codec-all</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql-connector-java.version}</version>
            <scope>runtime</scope>
```
3. then execute mvn install -Prelease
