### ISSUE TITLE
Parse `Join table` for supporting `Join table` query SQL

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4885]
Content: Parsing `Join table` is first and vital for supporting `Join table` query SQL.
Difficulty Rating: ★★★☆☆

### How to handle this issue?
- [ ] Create `JoinedTableSegment`, `JoinSpecificationSegment`,  and `TableReferenceSegment` like
```
class JoinSpecificationSegment {
PredicateSegment
Collection<columnSegment>
}
class JoinedTableSegment {
tableSegment
joinSpecificationSegment
}
class TableReferenceSegment {
tableSegment
Collection<JoinedTableSegment>
}
```
- [ ] Add `Collection< TableReferenceSegment>` to `SelectStatement`
- [ ] Parse `JoinedTableSegment`, `joinSpecificationSegment` and `TableReferenceSegment ` by visitXXX() 
- [ ] Modify `visitTableReference()`
- [ ] In order to make sure `getAllTables()` in `SelectStatementContext` return correct result, it is needed to move `getTableSegments(result.getValue(), each)` in `XXXDMLVisitor` to `SelectStatementContext`
- [ ] Create `ExpectedJoinedTableSegment `, `ExpectedJoinSpecificationSegment `, `Expected TableReferenceSegment ` and `TableReferenceSegments` in `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/java/org/apache/shardingsphere/sql/parser/integrate/jaxb/domain/segment/impl` for the preparation of Parse integrated tests.
- [ ] Add `TableReferenceSegments ` to `SelectStatementTestCase`
- [ ] Modify `assertTable()` in `SelectStatementAssert`
- [ ] Add `assertJoinTable()` in `SelectStatementAssert `
- [ ] Modify the parsing test results of all the `Select` SQLs in `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml/`
- [ ] Modify the parsing test result of all the `Select join` SQLs ./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml/`
- [ ] Run `SQLParserParameterizedTest` well
- [ ] Run `ShardingSQLRewriterParameterizedTest` well

**Comment by tristaZero** [comment]
It is an uneasy job, so I suggest to split it as multiple sub-tasks to raise PR.

**Comment by jingshanglu** [comment]
I'll support

**Comment by tristaZero** [comment]
Reviwing this issue, it is inferred that the main sub-tasks are 
- [ ] Refactor current `SelectStatement` to include `TableReferenceSegment`
- [ ] Parse out `JoinTableSegment`.
So you can process this issue according to the original todo list or split this one to current sub-tasks. It depends on you. BTW, do you think 2~3 weeks is enough to finish it?

**Comment by tristaZero** [comment]
The final parsed result assertion in `xml` is 
```
<select sql-case-id="select_comparison_symbol_with_single_table" parameters="1, 10, 2, 5">
        <table-references>
            <table-reference>
                <simple-table name="t_order" start-index="14" stop-index="20" />
                <join-table start-index="14" stop-index="20">
                    <simple-table name="t_order" start-index="14" stop-index="20" />
                    <join-specification start-index="14" stop-index="20">
                        <column-name start-index="14" stop-index="20" />
                        <compare-predicate start-index="14" stop-index="20"></compare-predicate>
                    </join-specification>
                </join-table>
                <join-table start-index="14" stop-index="20">
                    <simple-table name="t_order" start-index="14" stop-index="20" />
                </join-table>
            </table-reference>
            <tableReference>
                <simple-table name="t_order" start-index="14" stop-index="20" />
            </tableReference>
        </table-references>
```

**Comment by tristaZero** [comment]
All done
