### ISSUE TITLE
cannot create directory due to Filename too long in Win10

### ISSUE THREAD

**Issue by codefans** [apache/incubator-shardingsphere#4892]
## Bug Report

**For English only**, other languages will not accept.

when i clone this repository in Git Bash of Win10, it occur error:
cannot create directory at 'sharding-transaction/sharding-transaction-2pc/sharding-transaction-xa/sharding-transaction-xa-atomikos/sharding-transaction-xa-atomikos-manager/src/main/java/org/apache/shardingsphere/transaction/xa/atomikos/manager': Filename too long

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by yu199195** [comment]
Hi, set  git config --global core.longpaths true.

**Comment by kimmking** [comment]
you should turn on longpath options of Windows.

**Comment by codefans** [comment]
> Hi, set git config --global core.longpaths true.

thanks, I just think the user experience is not good

**Comment by codefans** [comment]
> you should turn on longpath options of Windows:
> 
> * git: git config --global core.longpaths true
> * windows: User Group strategy -> Long path -> 1    referred: https://www.zhihu.com/pin/1216043691736969216

thanks, I just think we should try to reduce obstacles for users.

**Comment by kimmking** [comment]
@codefans Any idea to avoid this issue?

**Comment by codefans** [comment]
> @codefans Any idea to avoid this issue?

Is it possible change: 
sharding-transaction
	sharding-transaction-2pc
		sharding-transaction-xa
			sharding-transaction-xa-atomikos
				sharding-transaction-xa-atomikos-manager
					src/main/java/org/apache/shardingsphere/transaction/xa/atomikos
to: 	
sharding-transaction
	sharding-transaction-2pc-xa
		src/main/java/org/apache/shardingsphere/transaction/xa/atomikos
		src/main/java/org/apache/shardingsphere/transaction/xa/atomikos/manager

**Comment by kimmking** [comment]
many subproject contains files that exceed window default path-length, this is not a small issue in this way.

**Comment by tuohai666** [comment]
@codefans Maybe we could change the path this time, but long filename will always happen in future.
I agree with @yu199195 and @kimmking, these configuration also useful to other projects, developers have to know how to set.

**Comment by kimmking** [comment]
I had modify FAQ with https://github.com/apache/incubator-shardingsphere/pull/4949
