### ISSUE TITLE
Disclaimer - incorrect text

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-shardingsphere#4902]
The disclaimer has some incorrect text:

"Apache ShardingSphere is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by the name of The Apache Incubator."

This should read:

"Apache ShardingSphere is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by the Apache Incubator."

**Comment by kimmking** [comment]
hi，sebb @sebbASF 
Do you means https://github.com/apache/incubator-shardingsphere/blob/master/DISCLAIMER ?

**Comment by sebbASF** [comment]
I meant the footer on main page of website, i.e. at
http://shardingsphere.incubator.apache.org.

**Comment by kimmking** [comment]
Got it. And will modify it sooner.

**Comment by terrymanu** [comment]
Hi @sebbASF,
 
Thanks for your kind reminder. I fixed it by [1].

[1] https://github.com/apache/incubator-shardingsphere-doc/commit/3113b1b16f9d5ceb3db31f21170526d9e89bb3b7

**Comment by sebbASF** [comment]
Thanks, looks good now
