### ISSUE TITLE
Add several Chinese version documents

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#4906]
Hi,  there are some files in English version, we can add a Chinese version for each:
- [ ] https://github.com/apache/incubator-shardingsphere/blob/master/examples/docker/docker-compose.md
- [x] #2923 https://github.com/apache/incubator-shardingsphere/blob/master/examples/README.md
- [x] #4909 https://github.com/apache/incubator-shardingsphere/blob/master/sharding-scaling/README.md 
- [x] $4914 https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-ui/README.md
- [x] $4914 https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-ui/shardingsphere-ui-frontend/README.md

A tip: Chinese version file name should be origin filename with a "_ZH". If origin filename is "README.md", the new filename should be "README_ZH.md".

These tasks are good for new contributors, reply here to pick any task you want.

**Comment by edidada** [comment]
I will translate it,any problem?

**Comment by meAsky** [comment]
I want to try the second file @kimmking 

> https://github.com/apache/incubator-shardingsphere/blob/master/examples/README.md

**Comment by strongduanmu** [comment]
I want to translate the third file @kimmking 
> https://github.com/apache/incubator-shardingsphere/blob/master/sharding-scaling/README.md

**Comment by kimmking** [comment]
Got it, @edidada @meAsky @strongduanmu 
You can complete your own task now.

**Comment by edidada** [comment]
> Got it, @edidada @meAsky @strongduanmu
> You can complete your own task now.

I have finish it，how I can send file to you？

**Comment by strongduanmu** [comment]
> I want to translate the third file @kimmking
> 
> > https://github.com/apache/incubator-shardingsphere/blob/master/sharding-scaling/README.md

This document has been translated, help me review [this code](https://github.com/apache/incubator-shardingsphere/pull/4909) please.

**Comment by strongduanmu** [comment]
I want to translate the remaining two documents.
> https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-ui/README.md
> https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-ui/shardingsphere-ui-frontend/README.md

**Comment by kimmking** [comment]
@edidada  need polish.
