### ISSUE TITLE
how to integerating sharding and non-sharding transaction with xa 

### ISSUE THREAD

**Issue by leehom** [apache/incubator-shardingsphere#4910]
ss supports xa with sharding datasource，but in most time，we have other non-sharding tables，how to integerating them into a transaction with xa？

**Comment by ssxlulu** [comment]
You can use Begin ... COMMIT around your sqls.
Like this:
```
BEGIN;
UPDATE TABLE non-sharding-table SET name = 'xiaoming' WHERE id = 1;
UPDATE TABLE sharding-table SET name = 'xiaoming' WHERE id = 1;
COMMIT;
```
For ss, we will treat these sqls as one transaction.

**Comment by cherrylzhao** [comment]
yes, we only support distributed transaction in sharding way. for none-sharing table I think you can config the default datasource in sharding-datasource, the XA transaction will also effective.

**Comment by leehom** [comment]
default datasource ? , ok, i should have a test . can ss open an api , developer can manually enlist non-sharding datasouce into sharding xa transaction

**Comment by cherrylzhao** [comment]
I think we can open the api after our pluginable-platform finished

**Comment by cherrylzhao** [comment]
close this issue for no response for more than 7 days
