### ISSUE TITLE
Make official website prominent in Apache way.

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4928]
The following todo list to make website prominent in Apache way, and also it is time to make website more friendly for users and contributors.

- [x] Move all the links concerning Apache to the header.
- [x] Remove `SCM` drop-down list
- [x] Add `gitHub` label to the right of the page[1]
- [x] Remove the sub-item of `Community` drop-down list
- [x] Change `Download` drop-down list to `Download` button locating the left of the `Learn more` button
- [x] Add `Contribution`[2], `Users`[3], `Team`[4] links to `Community`drop-down list
- [x] Replace the `ShardingSphere` logo at the top left corner with Apache trademark[5]
- [x] Move the `ShardingSphere` logo at the top left corner to the center of the page
- [x] Add Apache logo to the bottom right corner of the website[1]

[1] https://struts.apache.org
[2] https://shardingsphere.apache.org/community/en/contribute/
[3] https://shardingsphere.apache.org/community/en/powered-by/
[4] https://shardingsphere.apache.org/community/en/team/
[5] https://tomcat.apache.org

**Comment by hailinmo** [comment]
Please assign to me, thx.

**Comment by tristaZero** [comment]
[#458](https://github.com/apache/incubator-shardingsphere-doc/pull/458) finished this one.
