### ISSUE TITLE
why sharding has many unsupported operation

### ISSUE THREAD

**Issue by wuguowei19880907** [apache/incubator-shardingsphere#4930]
## Question

I know that the sharding has many unsupported operation like
 - AbstractUnsupportedOperationDataSource.setLoginTimeout()
 - AbstractUnsupportedOperationResultSet.getRow()
 - and so on.

If I have only **one datasource** and only use the **encryption**,
Could I use the originalDatasource.setLoginTimeout or the originalResultSet.getRow instead of just **throw SQLFeatureNotSupportedException** ？ 
Do I have omitted something?

**Comment by terrymanu** [comment]
ShardingSphere is an open source project.
The project is not a final status, it still in dev mode.
Please join and contribute together.

**Comment by wuguowei19880907** [comment]
I will do that,but i wonder why just throw exception？

**Comment by terrymanu** [comment]
You may know which do you want to do, what is your expected and design, how the current codes works.

**Comment by wuguowei19880907** [comment]
I actually want to know why these unsupported APIs throw exceptions instead of calling native APIs to support them? For what reason？

**Comment by terrymanu** [comment]
Just waiting for contribution

**Comment by wuguowei19880907** [comment]
ok,thanks
