### ISSUE TITLE
Is there apm-sharding-sphere-4.x-plugin-7.0.0.jar for skywalking7.0

### ISSUE THREAD

**Issue by liuhonglin** [apache/incubator-shardingsphere#4931]
ShardingExecuteDataMap class path is org.apache.shardingsphere.core.execute.ShardingExecuteDataMap at version 4.0.0-RC1 to 4.0.0-RC3, however, from version 4.0.0 the path was changed to org.apache.shardingsphere.core.execute.engine.ShardingExecuteDataMap.
skywalking-agent throw exception as
java.lang.NoClassDefFoundError: org/apache/shardingsphere/core/execute/ShardingExecuteDataMap

**Comment by tuohai666** [comment]
Not yet. The new plugin which will come soon can support 4.0.0/4.0.1 and maybe 4.1.0.

**Comment by tuohai666** [comment]
Please refer to https://github.com/apache/skywalking/issues/4229
