### ISSUE TITLE
UI module feature discuss

### ISSUE THREAD

**Issue by pkwenda** [apache/incubator-shardingsphere#4944]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

master branch last version

### 1 error msg

If import yml config  wrong ， error msg is very simple 

```log
rule configuration is invalid.
```

There are actually many reasons for failure ， maybe this Issues :
https://github.com/apache/incubator-shardingsphere/issues/4921#issuecomment-603714874
or “ yml format error ” or ”It is prohibited to use Tab only space “...

i think error msg can be perfect

### 2 del schema

if i want del some setting , i only del it on zookeeper or other register center ..

![image](https://user-images.githubusercontent.com/14212375/77538256-62ef5780-6eda-11ea-99b6-71a23b448fdf.png)

**Comment by kimmking** [comment]
Can you try a go, submit several PRs to make it better?

**Comment by menghaoranss** [comment]
@pkwenda The UI module is being optimized continuously, and there are still many problems to be solved. If you are interested in this, you can fix them by submitting some PRs. We look forward to your contributions.
