### ISSUE TITLE
how i use sharding-jdbc-spring-boot-starter with spring-jdbc use seata-at,your example is raw-jdbc, can you help me

### ISSUE THREAD

**Issue by zjls007** [apache/incubator-shardingsphere#4954]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by zjls007** [comment]
also can replease spring-jdbc to mybatis

**Comment by kimmking** [comment]
[SpringBoot2.x 集成ShardingSphere+Seata+Mybatis-Plus+DruidDataSource](https://www.jianshu.com/p/41ebdaf403c8)

**Comment by cherrylzhao** [comment]
I have added a sharding-transaction-spring module recently, you can see how we integrated XA with spring in [transaction-2pc-xa-spring-boot-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-2pc-xa-spring-boot-example). seata and XA will use the same spring api to integrate, I'll add another seata example later

**Comment by zjls007** [comment]
> I have added a sharding-transaction-spring module recently, you can see how we integrated XA with spring in [transaction-2pc-xa-spring-boot-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-2pc-xa-spring-boot-example). seata and XA will use the same spring api to integrate, I'll add another seata example later

thanks, i have look you transaction-2pc-xa-spring-boot-example module just now， i very like this. an i learn more for this , and i wish you can support transaction-seata-spring-boot-example later,i can,t look you this example，but i look the alibaba seata example with shardingsphere, but that not 
official， it impl strange， i wish you support help more Your fan。i from chaina , my English is very poor.Please forgive me 。

**Comment by zjls007** [comment]
please see https://github.com/seata/seata-samples/tree/master/springboot-shardingsphere-seata
bu i cant understand，so i wish you support ,an i suggest you use seata 1.1.0 version

**Comment by cherrylzhao** [comment]
here is the [transaction-base-seata-spring-boot-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-spring-boot-example), hope this will help you

**Comment by zjls007** [comment]
thanks， main question Solved，work happy for you!

**Comment by lolashe** [comment]
> here is the [transaction-base-seata-spring-boot-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-spring-boot-example), hope this will help you

@cherrylzhao  The link is invalid. Please give me a new address
