### ISSUE TITLE
jdk兼容问题，jdk8以上版本异常

### ISSUE THREAD

**Issue by gchhy** [apache/incubator-shardingsphere#4959]
## Bug Report

shadring-jdbc发现一个问题，java8以上版本，3.1.0版本查询时候，会报空指针异常，跟进源码发现实际问题是java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext，应该是jdk版本问题，希望能 兼容上。而且在解析语句的时候直接trycatch，导致问题无法直接暴露，是否能优化 。 private final ParsingRuleRegistry parsingRuleRegistry = ParsingRuleRegistry.getInstance();这个方法在init的时候异常

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
