### ISSUE TITLE
the bug about jdk8.0+ Compatibility

### ISSUE THREAD

**Issue by gchhy** [apache/incubator-shardingsphere#4960]
### Which version of ShardingSphere did you use?
3.1.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139) 

### Actual behavior
java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext

### Reason analyze (If you can)
the 9 or 9+jdk will not support  javax.xml.bind.JAXBContext
I hope you are compatible 
I don't know why try catch the proplem, 
This leads to
It's hard to find problems

**Comment by kimmking** [comment]
Since jdk9+, java is a modularized platform.
You need add some javax.* module to your project dependencies.

**Comment by kimmking** [comment]
BTW, strongly recommend upgrade to 4.0.1 or incoming 4.1.0(officially support java8 in sourcecode&compile level)

**Comment by gchhy** [comment]
> Since jdk9+, java is a modularized platform.
> You need add some javax.* module to your project dependencies.

yes,i know the question, It took me half an hour to find out the problem。so I hope you can mark or introduce the corresponding jar package。It's a better experience。

**Comment by kimmking** [comment]
@gchhy I don't think so.
Everyone upgrade his/her projects to jdk9+, should make an investigation what and how to do.
Whatever, it's no matter about ShardingSphere.

**Comment by kimmking** [comment]
BTW2: java9 is not a LTS version, suggest use java11 instead.

**Comment by gchhy** [comment]
> BTW2: java9 is not a LTS version, suggest use java11 instead.

 java11 the same question. I think the biggest problem is that bugs are hidden too deep .It's not on the document，It's confusing for some novices。I just thought it would be better，And I think the shading-jdbc is great。
