### ISSUE TITLE
[Question] When will 5.0.0 Release？

### ISSUE THREAD

**Issue by phoema** [apache/incubator-shardingsphere#4979]
## Question
We want to use shardingsphere with subquery.
I want to know:
When will 5.0.0 Release？Is have a plan？
Looking forward to your reply，thanks。

**Comment by terrymanu** [comment]
No, we are planning for 4.1.0 release, please subscribe the dev mailing list to get release plan.
FIY: https://shardingsphere.apache.org/community/en/contribute/subscribe/
