### ISSUE TITLE
make ShardingDataSource compatible with Seata in micro-service distribution transaction

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#4991]
In micro-service distribution transaction, Seata will wrap `ShardingDataSource` as `DataSourceProxy` which communication with seata-server through RPC protocol,
and DataSourceProxy will invoke some standard JDBC interface to get metadata from ShardingDataSource, however ShardingDataSource don't compatible with it. I have investigated in my local environment and found these issues we should resolve
- [x] support get information by logical schema in CachedDataBaseMetaData
- [x] support getParameterMetaData in ShardingPreparedStatement
- [x] add `sharding.transaction.seata.at.enable ` config in sharding-transaction-base-seata-at

**Comment by kimmking** [comment]
`enable.client.transaction.in.seata.at` is better?

**Comment by cherrylzhao** [comment]
kimmking, thanks for suggestion.
sharding-transaction-base-seata-at module only worked in none-microservice mode since it invoke the seata global transaction api directly, so I want to add a switcher to disable it if user want to introduce seata global transaction in microservice. also I'm consider about better way to implement that

**Comment by cherrylzhao** [comment]
here is the config for integrating seata-at currently in shardingspehre side
```
client {
    application.id = test
    transaction.service.group = my_test_tx_group
}
```

**Comment by cherrylzhao** [comment]
how about this ?
```
sharding.transaction.seata.at.enable = true

client {
    application.id = test
    transaction.service.group = my_test_tx_group
}
```

**Comment by cherrylzhao** [comment]
I have submitted a PR for this config see #4996

**Comment by kimmking** [comment]
it's awesome

**Comment by leapcat** [comment]
When will the 5.0.0 version be released? Look forward to this feature eagerly.

**Comment by dengjin001** [comment]
seata-1.1.0 is supports  *.yml , so  `sharding.transaction.seata.at.enable = true` support yml configuration?

**Comment by cay914** [comment]
@cherrylzhao where to config sharding.transaction.seata.at.enable = true ?
