### ISSUE TITLE
Add parsing integrated test for `update` query SQL

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4995]
**Content**: Add two parsing integrated tests for `update` query SQL.
**Difficulty rating**: ★☆☆☆☆

### How to do
1. Add the following SQL cases to `/Users/trista/Documents/sharding-code-trista/incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/supported/dml/update.xml`

**SQL case ID**: update_with_set_calculation
> UPDATE t_order SET status = status - ? WHERE order_id = ? AND user_id = ?
parameters: 1, 2, 3

**SQL case ID**: update_with_where_calculation
> UPDATE t_order SET status = ? WHERE order_id = order_id - ? AND user_id = ?
parameter: 1, 2, 3

2. Calculate the parsing results of the above SQL cases and add those parsing results to `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/dml/update.xml`
**Tip**: You can refer to the parsing result of SQL case ID `update_without_alias` in the same directory.

3. Run `SQLParserParameterizedTest` to test your SQL cases.

**Comment by tristaZero** [comment]
Here is a good first issue for the community, welcome your join. :)

**Comment by strongduanmu** [comment]
I want to solve this issue, please assign to me!

**Comment by strongduanmu** [comment]
SQL case ID: update_with_where_calculation
> UPDATE t_order SET status = status WHERE order_id = order_id - ? AND user_id = ?
parameter: 1, 2, 3

The sql case above has three parameters, but only two placeholders. Is it right? 
@tristaZero

**Comment by tristaZero** [comment]
@strongduanmu Sorry, it is a typo and I fixed it. Please give it a look.

**Comment by strongduanmu** [comment]
> @strongduanmu Sorry, it is a typo and I fixed it. Please give it a look.

Thank you! :smile:
