### ISSUE TITLE
Why Class TableRule's constructor add a method named "checkRule" ?How can I set "ComplexShardingStrategyConfiguration "without  setting "actualDataNodes" ?

### ISSUE THREAD

**Issue by awaysLoveLittleBear** [apache/incubator-shardingsphere#5018]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
What is your actualDataNodes look like?

**Comment by KomachiSion** [comment]
actualDataNodes describe data source names and actual tables, delimiter as point, multiple data nodes split by comma, support inline expression. **Absent means sharding databases only**. Example: ds${0..7}.tbl${0..7}

The `checkRule` will check actualDataNodes and ShardingStrategy. 
If you configure TableShardingStrategy without actualDataNodes, `checkRule` will find it.

**Comment by KomachiSion** [comment]
No more response in 7 days, I will close this issue.
