### ISSUE TITLE
adding a schema on config center is not working,but updating authentication or props is  working,before rebooting sharding-proxy.

### ISSUE THREAD

**Issue by myzero1** [apache/incubator-shardingsphere#5022]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

- [x] 4.0.0
- [x] 4.1.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
After adding a schema on config center, I hope the Sharding Rroxy could refresh and load configuration automatically or semi-automatic(by sending a command manually), that is, Then I can see that new schema by `show databases;`
### Actual behavior
![](https://raw.githubusercontent.com/myzero1/show-time/master/tmp/QQ%E5%9B%BE%E7%89%8720200331175222.png)
![](https://raw.githubusercontent.com/myzero1/show-time/master/tmp/QQ%E5%9B%BE%E7%89%8720200331175232.png)
![](https://raw.githubusercontent.com/myzero1/show-time/master/tmp/QQ%E5%9B%BE%E7%89%8720200331175941.png)

**Comment by terrymanu** [comment]
The logic schema is configured by yaml and cannot support create by SQL dynamically.

**Comment by myzero1** [comment]
adding a schema on config center is the same as  [#2346](https://github.com/apache/incubator-shardingsphere/issues/2346)
