### ISSUE TITLE
Batch insert data is too slow when using sharding-jdbc for common java projects

### ISSUE THREAD

**Issue by AIYIPOI** [apache/incubator-shardingsphere#5023]
Hello, I am a beginner in sharding-jdbc
When I try to use the following configuration：
`TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration("tb","ds${0..1}.tb${0..1}");
    orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("j", "ds${j% 2}"));
    orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("k", "tb${k% 2}"));`
And use sql statement
`insert into tb(j,k,l) values(1,1,"###")`
Write 10,000 data in batches.I found that it took almost 16000ms, but jdbc only took 450ms.
I'm sure I'm mistaken, this is different from the sharding-jdbc I know.
But by controlling the variables, I found that besides changing the database field length. No matter how the database and table are divided, my write operation has not improved, and it remains at about 16000ms.
Configure only one data source
`TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration("tb","ds0.tb${0..1}");
    orderTableRuleConfig.setDatabaseShardingStrategyConfig(new NoneShardingStrategyConfiguration());
    orderTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("k", "tb${k% 2}"));`
or configure only one table
`TableRuleConfiguration orderTableRuleConfig = new TableRuleConfiguration("tb","ds${0..1}.tb0");
    orderTableRuleConfig.setDatabaseShardingStrategyConfig(new InlineShardingStrategyConfiguration("j", "ds${j% 2}"));
    orderTableRuleConfig.setTableShardingStrategyConfig(new NoneShardingStrategyConfiguration());`
I even changed the way I write to the database hoping to find the difference
`insert into tb(j,k,l) values(1,1,"###"),(2,2,"###"),(3,3,"###")........`
and
`con.setAutoCommit(false);
for(...){ps.addBatch}
ps.executeBatch();
con.commit()`
But sharding-jdbc is still much slower than jdbc, and it will not increase or decrease the time with the configuration file changes.
I'm sure the data is properly sharded according to the configuration.
I even implemented my own sharding algorithm and sharded it correctly.
But I can't write data faster anyway.
I read the test records on the official website and found that sharding-jdbc can achieve a write speed of 2w / s or even faster[https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/stress-test/](url)
Through testing, I can determine that it is a write problem, not that the configuration initialization is taking too much time.
But I can't do it at the moment, and ask for help to find that most of the test cases using sharding-jdbc are based on springboot.
Is anyone willing to correct my configuration or code problems, the configuration demo is exactly the same as the official website, or tell me a good article about sharding-jdbc.
I think I made a very naive mistake, but I really ca n’t find the mistake and ask for help
thanks,and love you guys

**Comment by terrymanu** [comment]
Please use prepared statement

**Comment by AIYIPOI** [comment]
> Please use prepared statement

Of course, I definitely used PreparedStatement

**Comment by AIYIPOI** [comment]
Duplicate of #

**Comment by AIYIPOI** [comment]
My first question was closed, but I didn't find a solution, sad:(

**Comment by huweidada** [comment]
use PreparedStatement，batch insert，312 rows，insert into table (.....) values (...),(...),(...),(...),(...),(...),(...)
from origin sql to logic sql，it takes 5 seconds

ShardingSphere-sharding-jdbc,version:4.0.0

I found,something times,it takes too time,sometime very fast

**Comment by huweidada** [comment]
I have log,do you need it to analysis？
