### ISSUE TITLE
How to simplify this configuration

### ISSUE THREAD

**Issue by Zhumingj** [apache/incubator-shardingsphere#5030]
spring.shardingsphere.datasource.names=tenant-meituan,tenant-taobao,tenant-jd,tenant-common

spring.shardingsphere.datasource.tenant-meituan.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-meituan.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-meituan.url=jdbc:mysql://localhost:3306/tenant_meituan
spring.shardingsphere.datasource.tenant-meituan.username=root
spring.shardingsphere.datasource.tenant-meituan.password=password

spring.shardingsphere.datasource.tenant-taobao.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-taobao.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-taobao.url=jdbc:mysql://localhost:3306/tenant_taobao
spring.shardingsphere.datasource.tenant-taobao.username=root
spring.shardingsphere.datasource.tenant-taobao.password=password

spring.shardingsphere.datasource.tenant-jd.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-jd.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-jd.url=jdbc:mysql://localhost:3306/tenant_jd
spring.shardingsphere.datasource.tenant-jd.username=root
spring.shardingsphere.datasource.tenant-jd.password=password

spring.shardingsphere.datasource.tenant-common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-common.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-common.url=jdbc:mysql://localhost:3306/tenant_common
spring.shardingsphere.datasource.tenant-common.username=root
spring.shardingsphere.datasource.tenant-common.password=password

spring.shardingsphere.sharding.default-data-source-name=tenant-common

### hundreds of tables
spring.shardingsphere.sharding.tables.tb_order.actual-data-nodes=tenant-meituan.tb_order,tenant-taobao.tb_order,tenant-jd.tb_order
spring.shardingsphere.sharding.tables.tb_order_item.actual-data-nodes=tenant-meituan.tb_order_item,tenant-taobao.tb_order_item,tenant-jd.tb_order_item
spring.shardingsphere.sharding.tables.tb_user_info.actual-data-nodes=tenant-meituan.tb_user_info,tenant-taobao.tb_user_info,tenant-jd.tb_user_info
......
spring.shardingsphere.sharding.tables.tb_sys_dict.actual-data-nodes=tenant-meituan.tb_sys_dict,tenant-taobao.tb_sys_dict,tenant-jd.tb_sys_dict

spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column=merchant
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.bsi.shardingsphere.demo.algorithm.DbShardingAlgorithm

spring.shardingsphere.props.sql.show=true

Above are all my configurations， there's no problem, but the configuration is troublesome，because I need to config actual-data-nodes for hundreds of tables. Is there any other solution?

**Comment by kimmking** [comment]
yaml?

**Comment by Zhumingj** [comment]
no,  application.properties

**Comment by tristaZero** [comment]
@Zhumingj Hi, I rather understand your concern, actually I also think they are so dull, that is why I opened an issue to welcome anyone of you to join me to give it a better design. You can look at #5017 to learn more.

Do you have any idea about `actual data nodes`? Or what are you expect?

**Comment by kimmking** [comment]
Approach 1: Spring placeholders.
you can config a piece of these node:
> all-actual-data-nodes = ........
and use a reference in the config rules:
> xx.xx.a.t.actual-data-nodes = ${all-actual-data-nodes}

Approach 2: Spring boot profiles.
Split to multiple properties with spring profiles.
tenant-meituan is one independent file.
tenant-taobao is another one independent file.
and so on.

Approach 3: ShardingSphere yaml
Use ShardingSphere yaml, you can config every tenant with a yaml file.
tenant-meituan is 'tenant-meituan-sharding-rules.yaml' file.
tenant-taobaois 'tenant-taobao-sharding-rules.yaml' file.
and so on.

**Comment by Zhumingj** [comment]
Thank you,  but this doesn't completely solve my problem. I still need to config actual-data-nodes for hundreds of tables.

**Comment by kimmking** [comment]
Can you show a perfect configuration demo in your case?

**Comment by Zhumingj** [comment]
spring.shardingsphere.datasource.names=tenant-meituan,tenant-taobao,tenant-jd,tenant-common

spring.shardingsphere.datasource.tenant-meituan.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-meituan.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-meituan.url=jdbc:mysql://localhost:3306/tenant_meituan
spring.shardingsphere.datasource.tenant-meituan.username=root
spring.shardingsphere.datasource.tenant-meituan.password=password

spring.shardingsphere.datasource.tenant-taobao.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-taobao.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-taobao.url=jdbc:mysql://localhost:3306/tenant_taobao
spring.shardingsphere.datasource.tenant-taobao.username=root
spring.shardingsphere.datasource.tenant-taobao.password=password

spring.shardingsphere.datasource.tenant-jd.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-jd.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-jd.url=jdbc:mysql://localhost:3306/tenant_jd
spring.shardingsphere.datasource.tenant-jd.username=root
spring.shardingsphere.datasource.tenant-jd.password=password

spring.shardingsphere.datasource.tenant-common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.tenant-common.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.tenant-common.url=jdbc:mysql://localhost:3306/tenant_common
spring.shardingsphere.datasource.tenant-common.username=root
spring.shardingsphere.datasource.tenant-common.password=password

spring.shardingsphere.sharding.default-data-source-name=tenant-common

hundreds of tables
spring.shardingsphere.sharding.tables.tb_order.actual-data-nodes=tenant-meituan.tb_order,tenant-taobao.tb_order,tenant-jd.tb_order
spring.shardingsphere.sharding.tables.tb_order_item.actual-data-nodes=tenant-meituan.tb_order_item,tenant-taobao.tb_order_item,tenant-jd.tb_order_item
spring.shardingsphere.sharding.tables.tb_user_info.actual-data-nodes=tenant-meituan.tb_user_info,tenant-taobao.tb_user_info,tenant-jd.tb_user_info
......
spring.shardingsphere.sharding.tables.tb_sys_dict.actual-data-nodes=tenant-meituan.tb_sys_dict,tenant-taobao.tb_sys_dict,tenant-jd.tb_sys_dict

spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column=merchant
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=com.bsi.shardingsphere.demo.algorithm.DbShardingAlgorithm

spring.shardingsphere.props.sql.show=true

**Comment by kimmking** [comment]
only sharding databases, no sharding tables?

**Comment by Zhumingj** [comment]
yes, only sharding databases

**Comment by kimmking** [comment]
Got it.
You should execute:
>  select group_concat(table_name) from information_schema.tables where table_schema='tenant-meituan';

gain all tables' name.
and then use above 'Approach 1'

**Comment by Zhumingj** [comment]
Excuse me, can you explain it in more detail, how to combine the sql with 'Approach 1'

**Comment by kimmking** [comment]
search spring boot properties placeholder.

**Comment by Zhumingj** [comment]
sorry , I don't know how to configure the SQL you mentioned.

select group_concat(table_name) from information_schema.tables where table_schema='tenant-meituan';

**Comment by kimmking** [comment]
@Zhumingj  This issue is out of date, we should close it now.
And you can subscribe #5044 for further discuss, any constructive suggestion is welcome here.
