### ISSUE TITLE
Can it support cross database join which have different tables

### ISSUE THREAD

**Issue by zywj** [apache/incubator-shardingsphere#5055]
```
DB0: user (id, username, class_id)
DB1: class (id, name)

select u.*, c.name as class_name from user u,  class c 
    where u.username="test" and  u.class_id=c.id 
```

**Comment by kimmking** [comment]
If db0 and db1 in the same mysql instance, you can query
`select u.*, c.name as class_name from db0.user u,  db1.class c 
    where u.username="test" and  u.class_id=c.id  `

Otherwise, mysql can't support.

**Comment by zywj** [comment]
thx.  slove it.
