### ISSUE TITLE
[API Changes] Remove default data source configuration

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#5063]
ShardingSphere can load all table meta data from data source and cache them into app memory currently.
It is passable to route correct data source for each un-configured table meta data. The default data source is not useful anymore. 
We can **REMOVE** default data source from sharding rule to simplify user configuration.

The tasks are:

- [x] Load un-configured table meta data with data source.
- [x] Route to correct data source for un-configured table.
- [ ] Remove configuration of default data source in sharding rule.

**Comment by zjcnb** [comment]
Hi, I would like to ask, is this a one-time acquisition of three tasks, or can be claimed separately!

**Comment by owen200008** [comment]
I think this change is not correct
it is different  default and auto

this change is auto， not default。now it don't have default config.

some sql use TABLES, it will be error.
like: SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'canary' UNION SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'canary' UNION SELECT COUNT(*) FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = 'canary'
