### ISSUE TITLE
Sharding proxy not support in navicat mysql for mac and idea database plugin

### ISSUE THREAD

**Issue by jzdayz** [apache/incubator-shardingsphere#5066]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
be opened
navicat version:
![image](https://user-images.githubusercontent.com/35563513/78348983-7b93f780-75d5-11ea-9392-823203a51067.png)
Testing is ok 
![image](https://user-images.githubusercontent.com/35563513/78349110-a8480f00-75d5-11ea-9409-899b34540ad0.png)
IDEA database :
![image](https://user-images.githubusercontent.com/35563513/78349218-d62d5380-75d5-11ea-98af-2f291f50c617.png)

![image](https://user-images.githubusercontent.com/35563513/78348886-57381b00-75d5-11ea-8da4-6762a26eae70.png)
But DBeaver 7.0.1 is ok
![image](https://user-images.githubusercontent.com/35563513/78348947-6cad4500-75d5-11ea-9677-5acad292bab5.png)

**Comment by kimmking** [comment]
1. duplicated with https://github.com/apache/incubator-shardingsphere/issues/4377,you should use 11.1.13 
2. duplicated with https://github.com/apache/incubator-shardingsphere/issues/4846, in idea or datagrip, you should turn on "introspect using jdbc metadata"(or it will get all real tables info from informations_schema).

**Comment by jzdayz** [comment]
> 1. duplicated with #4377 should use 11.1.13
> 2. duplicated with #4846, in idea or datagrip, you should turn on "introspect using jdbc metadata"(or it will get all real tables info from informations_schema).

idea database plugin can't test connection 
![image](https://user-images.githubusercontent.com/35563513/78453886-2c2df400-76c7-11ea-833a-e000d0c903ed.png)
![image](https://user-images.githubusercontent.com/35563513/78453901-3e0f9700-76c7-11ea-82dc-67d35fa04a37.png)
