### ISSUE TITLE
sharding partition key invalid when it work on batch program

### ISSUE THREAD

**Issue by Leejp1990** [apache/incubator-shardingsphere#5080]
I meet a problem in my batch program when use sharding. I have 8 application node to consume the message from rabbitMQ, and every pieces of message has the partition key, but it can't work on one application node and other node works good when batch program running. on the problem node,  we find the problem according to pinpoint, the stack shows the query SQL that with partition key executed on all partitions. we reboot the JVM progress with problem, and the problem has disappeared, but the same question has happened on another application node on the second day...

**Comment by terrymanu** [comment]
Can you provide the version and log of sql.show?

**Comment by Leejp1990** [comment]
1.The sharding-shpere version is 3.1.0.
2.I open the sql.show on dev environment, the logic sql and actual sql is right. Because of the log size, I didn't open this property on prod env.Now I use the hint route method instead of auto route way. 
Thanks your answer once more.

**Comment by terrymanu** [comment]
The version 3.x is out of service, please try 4.x
