### ISSUE TITLE
sharding-ui service cannot find custom algorithm class

### ISSUE THREAD

**Issue by danielzhou888** [apache/incubator-shardingsphere#5084]
## Bug Report
sharding version: 4.0.1(all of version)
A business project define a custom distribution algorithm cannot modify config in sharding-ui, which print an exception 'java.lang.IllegalArgumentException: rule configuration is invalid'.
I find an issue that cannot find custom distribution algorithm which I made in my business project while debuging.

![image](https://user-images.githubusercontent.com/22833421/78626044-2b13e700-78c0-11ea-9274-438098b8ab73.png)

**Comment by menghaoranss** [comment]
@danielzhou888 
I will follow this issue, could you provide the complete configuration above?

**Comment by kimmking** [comment]
@menghaoranss  the custom algorithm class in proxy server, but not in ui server

**Comment by kimmking** [comment]
@danielzhou888 I suggest you should put your custom algorithm class both to proxy & ui server lib directory.

**Comment by danielzhou888** [comment]
@kimmking Thank u for your suggests, I'll take u answer.

**Comment by kimmking** [comment]
@danielzhou888 You are welcome.
We'll close this issue soon.
