### ISSUE TITLE
why this sub query which sharding website told me that is ok can't support

### ISSUE THREAD

**Issue by fyuan1030** [apache/incubator-shardingsphere#5090]
I write a SQL with mybatis, it is just an easy SQL ,like this 
SQL : select count(*) from
        (select
        *
        from t_user) tmp
but it can't be parse; but when I learn it from sharding website, it told me that is ok ;is it a bug?
my version is 3.1.0;
![image](https://user-images.githubusercontent.com/38123832/78649039-74c7f600-78ef-11ea-9f72-5c806d867c81.png)
![image](https://user-images.githubusercontent.com/38123832/78649182-afca2980-78ef-11ea-88fb-4fb9d4fab75a.png)

**Comment by terrymanu** [comment]
Please try to version 4.x, the version 3.x is out of service

**Comment by fyuan1030** [comment]
> Please try to version 4.x, the version 3.x is out of service

OK  Thank you；but I use this dependency 
       <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>
so maybe I can't find the version 4.x
