### ISSUE TITLE
过滤反引号的问题

### ISSUE THREAD

**Issue by lqlcy1** [apache/incubator-shardingsphere#5091]
由于一些数据库的不规范使用原因  有一些字段使用 group这个关键字进行命名，例如 insert into test(group) values('test')这样的sql，为了避免报错 会加上反引号 
 insert into test(`group`) values('test')。
在使用shardingsphere的时候 发现该组件会把反引号过滤掉 导致执行的时候 数据库把字段当成了关键字 执行报错，请问有没有解决方案

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
