### ISSUE TITLE
Can shardingsphere provide a user configurable parser? 

### ISSUE THREAD

**Issue by xfyang1988** [apache/incubator-shardingsphere#5121]
Can sharing sphere provide a user configurable parser? 
For example, durid or ANTLR or do you research by yourself? 
So users balance performance and SQL compatibility?

Are follow-up plans available?

**Comment by kimmking** [comment]
In our plan, parser module is a pluggable and neccessary component.
If you want replace it with another third party one, it's all right and I think you must make some integration issue for it to adapter its parser results to Sharding domain objects.

**Comment by xfyang1988** [comment]
> In our plan, parser module is a pluggable and neccessary component.
> If you want replace it with another third party one, it's all right and I think you must make some integration issue for it to adapter its parser results to Sharding domain objects.

So, do you plan to continue to use "ANTLR" as the only syntax parser of shardingsphere? There is no plan to configure parsers like "durid" or other parsers with better performance

**Comment by terrymanu** [comment]
ShardingSphere can not support parser without ANTLR for now.
If support more sql parser engine, we need define a new API to separate ANTLR and other implementation(such as Druid) which need a lot of work.
There is not plan to do this and it is not easy to do.
Is there anybody interested with this enhancement?

**Comment by xfyang1988** [comment]
> ShardingSphere can not support parser without ANTLR for now.
> If support more sql parser engine, we need define a new API to separate ANTLR and other implementation(such as Druid) which need a lot of work.
> There is not plan to do this and it is not easy to do.
> Is there anybody interested with this enhancement?

ok
