### ISSUE TITLE
Remove stale functions

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#5136]
**Task content:** Remove the stale functions(Not used anymore) in `PostgreSQLDMLVisitor`, `MySQLDMLVisitor`, `OracleDMLVisitor`, `SQLServerDMLVisitor` and `SQL92DMLVisitor`.

**Task difficulty level:** ★☆☆☆☆

**Comment by tristaZero** [comment]
This is a good first issue, welcome newbie to join the community. 😃

**Comment by strongduanmu** [comment]
Hi, i want to solve this issue！
