### ISSUE TITLE
Fix typo of Bootstrap in sharding-proxy

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere#5145]
in [Bootstrap.java](https://github.com/apache/incubator-shardingsphere/blob/master/sharding-proxy/sharding-proxy-bootstrap/src/main/java/org/apache/shardingsphere/shardingproxy/Bootstrap.java) we should fix paredPort => port

```java
private static int getPort(final String[] args) {
        if (0 == args.length) {
            return DEFAULT_PORT;
        }
        Integer paredPort = Ints.tryParse(args[0]);
        return paredPort == null ? DEFAULT_PORT : paredPort;
    }
```

**Comment by strongduanmu** [comment]
Hi, I want to fix this issue, please assign to me!
