### ISSUE TITLE
Is the set or show command supported?

### ISSUE THREAD

**Issue by wangzihaogithub** [apache/incubator-shardingsphere#5155]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Is the set command currently supported?

**Comment by wangzihaogithub** [comment]
1. show status; 
2. show variables; 
3. show variables like '%my_name%'; 
4. show full processlist; 
5. show errors;
6. show warnings;
7. show character set;

8. set global my_var:=my_value; 
9. set @@gloabl.my_var:=my_value;

**Comment by wangzihaogithub** [comment]
Whether the metadata center is relevant?

**Comment by nevereverever** [comment]
Most of them are unicast to single mysql.
Maybe the designer didn't think about some problems.
Such as show full processlist?
Because the PID may be the same.

**Comment by wangzihaogithub** [comment]
ok. What are the plans for the future?

**Comment by terrymanu** [comment]
There is no plan with these SQL, do you interesting with them?

**Comment by wangzihaogithub** [comment]
No, I'm not interested. 
Just to get to know

**Comment by terrymanu** [comment]
OK, Could we close this issue?

**Comment by wangzihaogithub** [comment]
ok
