### ISSUE TITLE
ShardingTransactionType cannot be resolved to a type

### ISSUE THREAD

**Issue by flypangzhi** [apache/incubator-shardingsphere#5171]
## Question
I configured XA transactions as documented, but the ShardingTransactionType cannot be resolved to a type

## Version
```
springboot 2.0.6.RELEASE
mybatis-plus-boot-starter 3.1.0
sharding-jdbc-spring-boot-starter 4.0.0-RC1
sharding-transaction-xa-core 4.0.0-RC1
```

## pom.xml

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-jdbc-spring-boot-starter.version}</version>
        </dependency>
        
		<dependency>
		    <groupId>org.apache.shardingsphere</groupId>
		    <artifactId>sharding-transaction-xa-core</artifactId>
		    <version>${shardingsphere.version}</version>
		</dependency>

## TransactionConfiguration.java
```
@Configuration
@EnableTransactionManagement
public class TransactionConfiguration {

    @Bean
    public PlatformTransactionManager txManager(final DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public JdbcTemplate jdbcTemplate(final DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }
}
```

## error Method
```
 @PostMapping("/xaManage")
    @Transactional
    @ShardingTransactionType(TransactionType.XA)  // ShardingTransactionType cannot be resolved to a type
    public ResponseData<?> xaManage(TabUser tabUser) {
        tabUserService.save(tabUser);
        int i = 5 / 0;
        return ResponseData.out(CodeEnum.SUCCESS, tabUser.getId());
    }
```

**Comment by cherrylzhao** [comment]
this feature is only supported since 4.1.x which will be released recently，you can try it in our master branch.

**Comment by flypangzhi** [comment]
> 
> 
> this feature is only supported since 4.1.x which will be released recently，you can try it in our master branch.

thanks

**Comment by flypangzhi** [comment]
this feature is only supported since 4.1.x which will be released recently，you can try it in our master branch.
