### ISSUE TITLE
Snowflake can be configured under MasterSlaveRules?

### ISSUE THREAD

**Issue by Ikki-Dai** [apache/incubator-shardingsphere#5207]
## Question
Snowflake can be configured under MasterSlaveRules?

I configured master-slave datasource and configured key-generator with snowflake， but it doesn't work.
if master-slave doesn't support snowflake, can you migrate it for master-slave rule?

**Comment by kimmking** [comment]
Id generator should be used with sharding rule, MasterSlaveRules and ShardingRules could be configured together. See the same case examples(it has snowflake key generator): https://github.com/apache/incubator-shardingsphere/blob/master/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-master-slave.yaml
