### ISSUE TITLE
Does ShardingProxy already support automatically disabling unavailable data sources, such as automatically setting DISABLED to the registry？

### ISSUE THREAD

**Issue by fengyunhe** [apache/incubator-shardingsphere#5216]
## Question

Does ShardingProxy already support automatically disabling unavailable data sources, such as automatically setting DISABLED to the registry ？

**Comment by kimmking** [comment]
Not exactly.
For example: shardingProxy proxy 1 master and 3 slaves(slave0,1,2), we can disable one slaves such like slave0 via sharding-ui. And then we only select data from slave1,2.

ShardingProxy don't know `what's unavailable data sources`, so it can't `automatically`  disiable nodes. It's been decided and operated manually by users.

**Comment by fengyunhe** [comment]
i see ,thank you.

**Comment by ddsr-ops** [comment]
> Not exactly.
> For example: shardingProxy proxy 1 master and 3 slaves(slave0,1,2), we can disable one slaves such like slave0 via sharding-ui. And then we only select data from slave1,2.
> 
> ShardingProxy don't know `what's unavailable data sources`, so it can't `automatically` disiable nodes. It's been decided and operated manually by users.

But how to ensue the availability of the master. When master is down, the application will also be down
