### ISSUE TITLE
Please write some summary of how to use Sharding-Sphere in your company(使用Sharding-Sphere的朋友请填写在您公司的使用场景)

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere#605]
There are a lot of company use Sharding-Sphere already, please write some summary here.

Sharding-Sphere已经有不少公司采用，使用的场景也五花八门。希望能有更多的使用场景文章，因此征询志愿者领取任务，感兴趣的同学欢迎联系我。

**Comment by yinwenyu** [comment]
搜狐资讯 在用户模块红包业务中，使用了Sharding-JDBC，以用户ID取模进行分表，解决了用户持续大量增长的过程中，单表数据量增长过快突破限制的问题。后面随着用户量的不断增长将使用Sharding-JDBC以用户为维度进行分库，以解决数据库高访问量的问题。

**Comment by betterjava** [comment]
海豹自选  在虚拟币交易行情模块中，使用了Sharding-JDBC，以交易所id进行分表，在设计之初就 用上了Sharding-JDBC，解决了单日增量数据近3000万的数据存储和查询问题。

**Comment by zhouyutong** [comment]
e代驾 在司机驾驶行为采集中,使用了Sharing-JDBC

**Comment by terrymanu** [comment]
merge with #650
