### ISSUE TITLE
Support Saga Transaction

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#986]
What's Saga?
The paper:
https://www.cs.cornell.edu/andru/cs711/2002fa/reading/sagas.pdf
The github project which Sharding-Sphere will integrate with:
https://github.com/apache/incubator-servicecomb-saga
More information from Willem Jiang's presentation:
http://servicecomb.incubator.apache.org/cn/docs/distributed-transactions-saga-implementation/

The second soft transaction (i.e. flexible transaction) which Sharding-Sphere will support is Saga transaction. In the first step, we plan to implement it in Sharding-JDBC.

SS starts a transaction via Saga API(https://github.com/apache/incubator-servicecomb-saga/blob/old-saga/docs/api/api.md). The API looks like this:
{
  "policy": "",
  "requests": [
    {
      "id": "",
      "type": "",
      "serviceName": "",
      "parents": [
      ],
      "transaction": {
        "method": "",
        "path": "",
        "params": {
        }
      },
      "compensation": {
        "method": "",
        "path": "",
        "params": {
        }
      }
    }
  ]
}
Logic SQLs in a SS transaction will be treated as one Saga Request separately. Users of SS should supply the compensatory SQLs correspondingly:
transaction:
INSERT INTO `t_order` (`order_id`, `user_id`, `status`) VALUES (?, '10', 'INIT');
compensation:
DELETE FROM `t_order` WHERE `order_id`=?;
SS need to implement method of both transaction and compensation for Saga. The path parameter seems to have no use for SS, and should be ignored.
The content of params should include SQL and the parameter of SQL, may implement by currently form parameters.
At last, id and serviceName will be generated by SS uniquely. Saga can use these identifier to find transactions.

**Comment by KomachiSion** [comment]
SS also starts transaction via Saga API [https://github.com/apache/incubator-servicecomb-saga/blob/master/docs/api/api.md](https://github.com/apache/incubator-servicecomb-saga/blob/master/docs/api/api.md) .
The new API looks like:
```
{
  "policy": "",
  "requests": [
    {
      "id": "",
      "type": "",
      "datasource": "",
      "parents": [

      ],
      "transaction": {
        "sql": "",
        "params": [
          []
        ]
      },
      "compensation": {
        "sql": "",
        "params": [
          []
        ]
      }
    }
  ]
}
```
Logic SQLs in a transaction will be parsed and routed, and will be combined into a graph.
This graph will be mapped to saga API json and invoke saga coordinator to execute saga transaction.

**Comment by KomachiSion** [comment]
TODO list of saga transaction:

- [ ]  Support JDBC statement
- [x]  Support JDBC preparedStatement
- [ ]  Support JDBC BatchPreparedStatement
- [x]  Support Proxy JDBC backend
- [ ] Support Proxy NIO backend
- [x] Support forward recover policy
- [ ] Support backward recover policy
- [ ] Persistent Store Saga transaction logs
