### ISSUE TITLE
Introduce the SPI for the transaction manager in the sharding-sphere

### ISSUE THREAD

**Issue by zhfeng** [apache/incubator-shardingsphere#990]
I want to make a proposal to introduce the SPI to allow the transaction manager integration to be pluggable that the different implementation could be used. It could be also used for the XA and the SAGA transaction.

For the XA transaction, it could be
```
void begin()             // start a XA transaction
void commit()          // commit to the TM
void rollback()         // rollback to the TM
```

For the SAGA transaction, it could be
```
void start()              // start a saga transaction
void close()            // close a saga transaction, that means all the sub transaction can be completed
void cancel()          // cancel a saga transaction, that means all the sub transaction can be cancelled
```
any thought ?

**Comment by cherrylzhao** [comment]
that's a great suggest！
we can implement `Atomikos`, `narayana`, `SAGA` transaction manager based on the common SPI.
let's do the detail SPI design together.

**Comment by cherrylzhao** [comment]
@zhfeng 
we have defined XA SPI with class `io.shardingsphere.transaction.api.TransactionManager`.
AtomikosTransactionManager have been refactored in this way.

now, we'd like to discuss how to integrate with `narayana` transaction manager.
Atomikos provided a wrapper datasource to enlist and delist resource into transaction manager while invoking jdbc interface.
I haven't found a equivalence implement in `narayana-jta`，would you please give me some hint？

**Comment by zhfeng** [comment]
Narayana does not have the wrapper for the datasource but it has the transactional driver for doing the similar things. I will investigate and provide the implementation from the Narayana side.

Thanks for your contribution to introduce the XA SPI and it could be great work.

**Comment by cherrylzhao** [comment]
@zhfeng 
thanks for your support, waiting for your goods news.
it looks like Narayana can be integrated with `ManagedDataSource` directly.

[DbcpXADataSourceWrapper](https://github.com/jbosstm/quickstart/blob/master/spring/narayana-spring-boot/src/main/java/org/springframework/boot/jta/narayana/DbcpXADataSourceWrapper.java)

**Comment by zhfeng** [comment]
I just open https://github.com/sharding-sphere/sharding-sphere/pull/1137 to add the warpDataSource method in the XATransactionManager interface which is very similar with what we have done in the spring-boot/jta. Also I refactor the JDBCXABackendDataSourceFactory to build the data source from the wrapDataSource.

And https://github.com/zhfeng/narayana-sharding-sphere hold the Narayana implementation of the sharding-sphere XATransactionManager. I'm still working on the wrapper and I hope to see if this provider would work in a demo.

Did you have any demo or a integration test to run with the xa transaction manager ?

**Comment by cherrylzhao** [comment]
hi, Zheng
thanks for your great job.
I have revise sharing-example using xa spi transaction.
please see more from [XaTransactionMain.java](https://github.com/sharding-sphere/sharding-sphere-example/blob/dev/sharding-jdbc-transaction-example/src/main/java/io/shardingsphere/example/transaction/XaTransactionMain.java)

**Comment by terrymanu** [comment]
Hi, Zheng.
I fix a issue on this.
If we want add XADataSource to Atomikos, we must use method `setXaDataSourceClassName`, otherwise if we use method `setXaDataSource`, Atomikos will not set XaProperties, which will cause user, password and other properties can not set.

**Comment by terrymanu** [comment]
@zhfeng the SPI for sharding-sphere is finished now, any plan on narayana next?

**Comment by zhfeng** [comment]
@terrymanu it could use the following codes to set the properties
```
PropertyUtils.setProperties(this.xaDataSource, this.xaProperties);
```

**Comment by zhfeng** [comment]
can you review the changes https://github.com/sharding-sphere/sharding-sphere/pull/1140 ?
